Arcane: Arcane::ICheckpointMng Class Reference
Arcane::ICheckpointMng Class Reference abstract
Interface of the checkpoint information manager.
#include <arcane/core/ICheckpointMng.h>
Public Member Functions
virtual ~ICheckpointMng ()=default
Frees resources.
virtual ARCANE_DEPRECATED_122 void readCheckpoint ()=0
Reads a checkpoint.
virtual void readCheckpoint (ICheckpointReader *reader)=0
Reads a checkpoint.
virtual ARCANE_DEPRECATED_2018 void readCheckpoint (ByteConstArrayView infos)=0
Reads a checkpoint.
virtual CheckpointInfo readCheckpointInfo (Span< const Byte > infos, const String &buf_name)=0
Reads checkpoint information.
virtual void readCheckpoint (const CheckpointInfo &checkpoint_info)=0
Reads a checkpoint.
virtual ARCANE_DEPRECATED_2018 void readDefaultCheckpoint ()=0
Reads a default checkpoint.
virtual CheckpointInfo readDefaultCheckpointInfo ()=0
Reads default checkpoint information.
virtual ARCANE_DEPRECATED_122 void writeCheckpoint (ICheckpointWriter *writer)=0
Writes a default checkpoint using the writer.
virtual void writeCheckpoint (ICheckpointWriter *writer, ByteArray &infos)=0
Writes a checkpoint using the writer.
virtual void writeDefaultCheckpoint (ICheckpointWriter *writer)=0
Writes a checkpoint using the writer.
virtual IObservable * writeObservable ()=0
Write observable.
virtual IObservable * readObservable ()=0
Read observable.
Detailed Description
Interface of the checkpoint information manager.
This manager handles checkpoint information, namely the saved times, the services used, and other information necessary for recovery. It does not directly manage the writing or reading, which are delegated to an ICheckpointReader or ICheckpointWriter.
Reading a checkpoint causes the modification of all variables and meshes.
Definition at line 38 of file ICheckpointMng.h.
Member Function Documentation
readCheckpoint() [1/4]
virtual ARCANE_DEPRECATED_122 void Arcane::ICheckpointMng::readCheckpoint () pure virtual
Reads a checkpoint.
This operation is collective.
Deprecated
Use readDefaultCheckpoint() instead
Implemented in Arcane::CheckpointMng.
Referenced by Arcane::CodeService::initCase().
readCheckpoint() [2/4]
virtual ARCANE_DEPRECATED_2018 void Arcane::ICheckpointMng::readCheckpoint (ByteConstArrayView infos) pure virtual
Reads a checkpoint.
Reads a checkpoint whose reading information is in infos.
Deprecated
Instead, use the following code:
ICheckpointMng* cm = ...;
Span<const Byte> buffer;
CheckpointInfo checkpoint_info = cm->readChekpointInfo(buffer);
cm->readChekpoint(checkpoint_info);
Implemented in Arcane::CheckpointMng.
readCheckpoint() [3/4]
virtual void Arcane::ICheckpointMng::readCheckpoint (const CheckpointInfo & checkpoint_info) pure virtual
Reads a checkpoint.
Reads a checkpoint whose information is in checkpoint_infos.
Implemented in Arcane::CheckpointMng.
readCheckpoint() [4/4]
virtual void Arcane::ICheckpointMng::readCheckpoint (ICheckpointReader * reader) pure virtual
Reads a checkpoint.
Reads a checkpoint from the reader.
Implemented in Arcane::CheckpointMng.
readCheckpointInfo()
virtual CheckpointInfo Arcane::ICheckpointMng::readCheckpointInfo (Span< const Byte > infos, const String & buf_name) pure virtual
Reads checkpoint information.
Reads the information of a checkpoint contained in the infos buffer. buf_name contains the name of the buffer used in displays in case of an error.
Implemented in Arcane::CheckpointMng.
readDefaultCheckpoint()
virtual ARCANE_DEPRECATED_2018 void Arcane::ICheckpointMng::readDefaultCheckpoint () pure virtual
Reads a default checkpoint.
This operation is collective.
In the default implementation, the information for resumption is stored in a file named 'checkpoint_info.xml' located in the case's export directory (ISubDomain::exportDirectory()).
Deprecated
Instead, use the following code:
ICheckpointMng* cm = ...;
CheckpointInfo checkpoint_info = cm->readDefaultChekpointInfo();
cm->readChekpoint(checkpoint_info);
Implemented in Arcane::CheckpointMng.
readDefaultCheckpointInfo()
virtual CheckpointInfo Arcane::ICheckpointMng::readDefaultCheckpointInfo () pure virtual
Reads default checkpoint information.
This operation is collective.
In the default implementation, the information for resumption is stored in a file named 'checkpoint_info.xml' located in the case's export directory (ISubDomain::exportDirectory()).
After reading the information, it is possible to call readCheckpoint(const CheckpointInfo& checkpoint_info) to read the checkpoint.
Implemented in Arcane::CheckpointMng.
Referenced by Arcane::CodeService::initCase().
readObservable()
virtual IObservable * Arcane::ICheckpointMng::readObservable () pure virtual
Read observable.
Observers registered in this observable are called after a complete checkpoint read.
Implemented in Arcane::CheckpointMng.
writeCheckpoint() [1/2]
virtual ARCANE_DEPRECATED_122 void Arcane::ICheckpointMng::writeCheckpoint (ICheckpointWriter * writer) pure virtual
Writes a default checkpoint using the writer.
This operation is collective.
Deprecated
Use writeDefaultCheckpoint() instead.
Implemented in Arcane::CheckpointMng.
writeCheckpoint() [2/2]
virtual void Arcane::ICheckpointMng::writeCheckpoint (ICheckpointWriter * writer, ByteArray & infos) pure virtual
Writes a checkpoint using the writer.
This operation is collective.
The information required to read it back is stored in the infos array passed as an argument. It is then possible to read a checkpoint back via readCheckpoint(ByteConstArrayView).
The default implementation stores in infos an XML file containing, among other things, the name of the corresponding reader, the number of subdomains, ...
Implemented in Arcane::CheckpointMng.
writeDefaultCheckpoint()
virtual void Arcane::ICheckpointMng::writeDefaultCheckpoint (ICheckpointWriter * writer) pure virtual
Writes a checkpoint using the writer.
This operation is collective.
This is a standard checkpoint that can be read back via readDefaultCheckpoint().
See also
readDefaultCheckpoint
Implemented in Arcane::CheckpointMng.
Referenced by Arcane::ArcaneCheckpointModule::_doCheckpoint().
writeObservable()
virtual IObservable * Arcane::ICheckpointMng::writeObservable () pure virtual
Write observable.
Observers registered in this observable are called before writing a checkpoint.
Implemented in Arcane::CheckpointMng.
The documentation for this class was generated from the following file:
ICheckpointMng.h