Arcane: Arcane::Accelerator::Impl::RunCommandLaunchInfo Class Reference
Arcane::Accelerator::Impl::RunCommandLaunchInfo Class Reference
Temporary object to store the execution information of a command and group tests.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h>
Public Types
using ThreadBlockInfo = KernelLaunchArgs
Public Member Functions
RunCommandLaunchInfo (RunCommand &command, Int64 total_loop_size)
RunCommandLaunchInfo (RunCommand &command, Int64 total_loop_size, bool is_cooperative)
RunCommandLaunchInfo (const RunCommandLaunchInfo &)=delete
RunCommandLaunchInfo operator= (const RunCommandLaunchInfo &)=delete
eExecutionPolicy executionPolicy () const
void beginExecute ()
Indicates that command execution is starting.
void endExecute ()
Signals the end of execution.
ParallelLoopOptions computeParallelLoopOptions () const
Calculates and returns the information for multi-thread loops.
const ForLoopRunInfo & loopRunInfo () const
Loop execution information.
Int64 totalLoopSize () const
Total loop size.
Private Member Functions
KernelLaunchArgs _computeKernelLaunchArgs (const void *func) const
Calculates the arguments for launching the kernel whose address is func.
NativeStream _internalNativeStream ()
void _doEndKernelLaunch ()
void _computeInitialKernelLaunchArgs ()
Calculates the initial value of kernel block/thread/grid based on full_size.
bool _isUseCooperativeLaunch () const
bool _isUseCudaLaunchKernel () const
void _setIsNeedBarrier (bool v)
void _computeLoopRunInfo ()
Calculates the value of m_loop_run_info.
void _addSyclEvent (void *sycl_event_ptr)
void _init ()
Private Attributes
RunCommand & m_command
bool m_has_exec_begun = false
bool m_is_notify_end_kernel_done = false
bool m_is_need_barrier = false
bool m_is_forced_need_barrier = false
bool m_is_cooperative_launch = false
eExecutionPolicy m_exec_policy = eExecutionPolicy::Sequential
KernelLaunchArgs m_kernel_launch_args
ForLoopRunInfo m_loop_run_info
Int64 m_total_loop_size = 0
RunQueueImpl * m_queue_impl = nullptr
Friends
class CudaKernelLauncher
class HipKernelLauncher
class SyclKernelLauncher
Detailed Description
Temporary object to store the execution information of a command and group tests.
Definition at line 36 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
Member Typedef Documentation
ThreadBlockInfo
using Arcane::Accelerator::Impl::RunCommandLaunchInfo::ThreadBlockInfo = KernelLaunchArgs
Definition at line 45 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
Constructor & Destructor Documentation
RunCommandLaunchInfo() [1/2]
Arcane::Accelerator::Impl::RunCommandLaunchInfo::RunCommandLaunchInfo (RunCommand & command, Int64 total_loop_size)
Definition at line 53 of file RunCommandLaunchInfo.cc.
RunCommandLaunchInfo() [2/2]
Arcane::Accelerator::Impl::RunCommandLaunchInfo::RunCommandLaunchInfo (RunCommand & command, Int64 total_loop_size, bool is_cooperative)
Definition at line 64 of file RunCommandLaunchInfo.cc.
~RunCommandLaunchInfo()
Arcane::Accelerator::Impl::RunCommandLaunchInfo::~RunCommandLaunchInfo ()
Definition at line 76 of file RunCommandLaunchInfo.cc.
Member Function Documentation
_addSyclEvent()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::_addSyclEvent (void * sycl_event_ptr) private
Definition at line 223 of file RunCommandLaunchInfo.cc.
_computeInitialKernelLaunchArgs()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::_computeInitialKernelLaunchArgs () private
Calculates the initial value of kernel block/thread/grid based on full_size.
Definition at line 147 of file RunCommandLaunchInfo.cc.
_computeKernelLaunchArgs()
KernelLaunchArgs Arcane::Accelerator::Impl::RunCommandLaunchInfo::_computeKernelLaunchArgs (const void * func) const private
Calculates the arguments for launching the kernel whose address is func.
Determines the kernel configuration.
The configuration depends on the underlying runtime. For CUDA and ROCM, it is a number of blocks and threads.
It is possible to dynamically calculate the optimal values to maximize occupancy.
Definition at line 211 of file RunCommandLaunchInfo.cc.
References totalLoopSize().
_computeLoopRunInfo()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::_computeLoopRunInfo () private
Calculates the value of m_loop_run_info.
This is only useful in multi-thread mode.
Definition at line 191 of file RunCommandLaunchInfo.cc.
References computeParallelLoopOptions().
Referenced by beginExecute().
_doEndKernelLaunch()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::_doEndKernelLaunch () private
Definition at line 118 of file RunCommandLaunchInfo.cc.
_init()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::_init () private
Definition at line 36 of file RunCommandLaunchInfo.cc.
_internalNativeStream()
NativeStream Arcane::Accelerator::Impl::RunCommandLaunchInfo::_internalNativeStream () private
Definition at line 134 of file RunCommandLaunchInfo.cc.
_isUseCooperativeLaunch()
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::_isUseCooperativeLaunch () const private
Definition at line 232 of file RunCommandLaunchInfo.cc.
_isUseCudaLaunchKernel()
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::_isUseCudaLaunchKernel () const private
Definition at line 241 of file RunCommandLaunchInfo.cc.
_setIsNeedBarrier()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::_setIsNeedBarrier (bool v) private
Definition at line 251 of file RunCommandLaunchInfo.cc.
beginExecute()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::beginExecute ()
Indicates that command execution is starting.
Must always be called before launching the command to ensure that this method is called in case of an exception.
Definition at line 87 of file RunCommandLaunchInfo.cc.
References _computeLoopRunInfo(), ARCCORE_FATAL, and Arcane::Accelerator::Thread.
Referenced by Arcane::Accelerator::Impl::_applyConstituentCells(), Arcane::Accelerator::Impl::_applyGenericLoop(), Arcane::Accelerator::impl::_applyItems(), Arcane::Accelerator::Impl::GenericFilteringIf::apply(), Arcane::Accelerator::Impl::GenericPartitionerIf::apply(), and Arcane::Accelerator::Impl::GenericPartitionerIf::apply3().
computeParallelLoopOptions()
ParallelLoopOptions Arcane::Accelerator::Impl::RunCommandLaunchInfo::computeParallelLoopOptions () const
Calculates and returns the information for multi-thread loops.
Definition at line 163 of file RunCommandLaunchInfo.cc.
References Arcane::ParallelLoopOptions::grainSize(), Arcane::ConcurrencyBase::maxAllowedThread(), Arcane::ParallelLoopOptions::maxThread(), and Arcane::ParallelLoopOptions::setGrainSize().
Referenced by _computeLoopRunInfo().
endExecute()
void Arcane::Accelerator::Impl::RunCommandLaunchInfo::endExecute ()
Signals the end of execution.
Notifies the end of command launch.
If the queue associated with the command is asynchronous, the command may continue to execute after this call.
Note that if the command is asynchronous, its execution may continue after calling this method.
Definition at line 107 of file RunCommandLaunchInfo.cc.
References ARCCORE_FATAL.
Referenced by Arcane::Accelerator::Impl::_applyConstituentCells(), Arcane::Accelerator::Impl::_applyGenericLoop(), Arcane::Accelerator::impl::_applyItems(), Arcane::Accelerator::Impl::GenericFilteringIf::apply(), Arcane::Accelerator::Impl::GenericPartitionerIf::apply(), and Arcane::Accelerator::Impl::GenericPartitionerIf::apply3().
executionPolicy()
eExecutionPolicy Arcane::Accelerator::Impl::RunCommandLaunchInfo::executionPolicy () const inline
Definition at line 57 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
loopRunInfo()
const ForLoopRunInfo & Arcane::Accelerator::Impl::RunCommandLaunchInfo::loopRunInfo () const inline
Loop execution information.
This information is only valid if executionPolicy()==eExecutionPolicy::Thread and if beginExecute() has been called.
Definition at line 84 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
Referenced by Arcane::Accelerator::Impl::GenericFilteringIf::apply().
totalLoopSize()
Int64 Arcane::Accelerator::Impl::RunCommandLaunchInfo::totalLoopSize () const inline
Total loop size.
Definition at line 87 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
Referenced by _computeKernelLaunchArgs().
Friends And Related Symbol Documentation
CudaKernelLauncher
friend class CudaKernelLauncher friend
Definition at line 39 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
HipKernelLauncher
friend class HipKernelLauncher friend
Definition at line 40 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
SyclKernelLauncher
friend class SyclKernelLauncher friend
Definition at line 41 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
Member Data Documentation
m_command
RunCommand& Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_command private
Definition at line 91 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_exec_policy
eExecutionPolicy Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_exec_policy = eExecutionPolicy::Sequential private
Definition at line 97 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_has_exec_begun
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_has_exec_begun = false private
Definition at line 92 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_is_cooperative_launch
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_is_cooperative_launch = false private
Definition at line 96 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_is_forced_need_barrier
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_is_forced_need_barrier = false private
Definition at line 95 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_is_need_barrier
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_is_need_barrier = false private
Definition at line 94 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_is_notify_end_kernel_done
bool Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_is_notify_end_kernel_done = false private
Definition at line 93 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_kernel_launch_args
KernelLaunchArgs Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_kernel_launch_args private
Definition at line 98 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_loop_run_info
ForLoopRunInfo Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_loop_run_info private
Definition at line 99 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_queue_impl
RunQueueImpl* Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_queue_impl = nullptr private
Definition at line 101 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
m_total_loop_size
Int64 Arcane::Accelerator::Impl::RunCommandLaunchInfo::m_total_loop_size = 0 private
Definition at line 100 of file arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h.
The documentation for this class was generated from the following files:
arccore/src/common/arccore/common/accelerator/RunCommandLaunchInfo.h
RunCommandLaunchInfo.cc