Arcane: Arcane::mesh::FacesToMergeFinder Class Reference
Arcane::mesh::FacesToMergeFinder Class Reference
This function-class searches for faces to merge when merging two cells.
Public Member Functions
Integer getNumber () const
Integer cell1FaceNumber (Integer i) const
Integer cell2FaceNumber (Integer i) const
FacesToMergeFinder (Cell cell1, Cell cell2, const CommonFaceFinder &common_face)
Private Member Functions
void _setEdgeFaceList (Cell i_cell, IntegerArray &edge_face_list, Integer common_face_number, const CommonFaceFinder::NodesLIDSet &common_face_nodes)
Private Attributes
IntegerUniqueArray m_cell1_edge_face_list
IntegerUniqueArray m_cell2_edge_face_list
Detailed Description
This function-class searches for faces to merge when merging two cells.
Definition at line 513 of file CellMerger.cc.
Constructor & Destructor Documentation
FacesToMergeFinder()
Arcane::mesh::FacesToMergeFinder::FacesToMergeFinder (Cell cell1, Cell cell2, const CommonFaceFinder & common_face) inline
Constructs the different data structures
Parameters
cell1 the first cell
cell2 the second cell
common_face the information of the common face
Definition at line 558 of file CellMerger.cc.
References _setEdgeFaceList(), Arcane::mesh::CommonFaceFinder::cell1LocalNumber(), Arcane::mesh::CommonFaceFinder::cell2LocalNumber(), m_cell1_edge_face_list, and Arcane::mesh::CommonFaceFinder::nodesLID().
Member Function Documentation
_setEdgeFaceList()
void Arcane::mesh::FacesToMergeFinder::_setEdgeFaceList (Cell i_cell, IntegerArray & edge_face_list, Integer common_face_number, const CommonFaceFinder::NodesLIDSet & common_face_nodes) private
Determines the faces to merge by considering the edges that are supported by the common vertices between the cells. For this, the faces are sorted according to the edges supported by common vertices.
Parameters
i_cell the cell studied
edge_face_list the list of face numbers
common_face_number the number of the common face in cell i_cell
common_face_nodes the localIds of the nodes of the common face
Definition at line 601 of file CellMerger.cc.
References Arcane::Array< T >::add(), ARCANE_FATAL, Arcane::Cell::faces(), and Arcane::Array< T >::reserve().
Referenced by FacesToMergeFinder().
cell1FaceNumber()
Integer Arcane::mesh::FacesToMergeFinder::cell1FaceNumber (Integer i) const inline
Access the i-th face number in cell 1
Parameters
i the number in the list of common faces
Returns
the number in cell 1 of the i-th common face
Definition at line 534 of file CellMerger.cc.
References m_cell1_edge_face_list.
Referenced by Arcane::mesh::CellToHexahedronMerger::CellToHexahedronMerger().
cell2FaceNumber()
Integer Arcane::mesh::FacesToMergeFinder::cell2FaceNumber (Integer i) const inline
Access the i-th face number in cell 2
Parameters
i the number in the list of common faces
Returns
the number in cell 2 of the i-th common face
Definition at line 546 of file CellMerger.cc.
Referenced by Arcane::mesh::CellToHexahedronMerger::CellToHexahedronMerger().
getNumber()
Integer Arcane::mesh::FacesToMergeFinder::getNumber () const inline
Access the number of common faces between the two cells
Returns
m_cell1_edge_face_list.size()
Definition at line 522 of file CellMerger.cc.
References m_cell1_edge_face_list.
Referenced by Arcane::mesh::CellToHexahedronMerger::CellToHexahedronMerger().
Member Data Documentation
m_cell1_edge_face_list
IntegerUniqueArray Arcane::mesh::FacesToMergeFinder::m_cell1_edge_face_list private
These lists containing the numbers of the common faces of the two cells are constructed such that the face m_cell1_edge_face_list[i] is to be merged with the face m_cell2_edge_face_list[i]
Definition at line 579 of file CellMerger.cc.
Referenced by cell1FaceNumber(), FacesToMergeFinder(), and getNumber().
m_cell2_edge_face_list
IntegerUniqueArray Arcane::mesh::FacesToMergeFinder::m_cell2_edge_face_list private
Definition at line 580 of file CellMerger.cc.
The documentation for this class was generated from the following file:
CellMerger.cc