Alien: Alien::IAbstractFamily Class Reference
Alien::IAbstractFamily Class Reference abstract
Interface for abstract families of items.
#include <core/alien/index_manager/IAbstractFamily.h>
Classes
class Item
Public Member Functions
IAbstractFamily (const IAbstractFamily &)=delete
IAbstractFamily (IAbstractFamily &&)=delete
void operator= (const IAbstractFamily &)=delete
void operator= (IAbstractFamily &&)=delete
virtual IAbstractFamily * clone () const =0
virtual Int32 maxLocalId () const =0
Max local Id for this family.
virtual void uniqueIdToLocalId (ArrayView< Integer > localIds, ConstArrayView< Int64 > uniqueIds) const =0
virtual Item item (Int32 localId) const =0
Give back an Item from its local id.
virtual SafeConstArrayView< Integer > owners (ConstArrayView< Integer > localIds) const =0
Owners of the given local ids.
virtual SafeConstArrayView< Int64 > uids (ConstArrayView< Integer > localIds) const =0
unique ids of the given local ids.
virtual SafeConstArrayView< Int32 > allLocalIds () const =0
Local ids of this family members.
Detailed Description
Interface for abstract families of items.
Definition at line 33 of file IAbstractFamily.h.
Member Function Documentation
allLocalIds()
virtual SafeConstArrayView< Int32 > Alien::IAbstractFamily::allLocalIds () const pure virtual
Local ids of this family members.
Implemented in Alien::AbstractItemFamily, and Alien::DefaultAbstractFamily.
Referenced by Alien::IndexManager::buildScalarIndexSet(), and Alien::IndexManager::buildVectorIndexSet().
item()
virtual Item Alien::IAbstractFamily::item (Int32 localId) const pure virtual
Give back an Item from its local id.
Implemented in Alien::AbstractItemFamily, and Alien::DefaultAbstractFamily.
maxLocalId()
virtual Int32 Alien::IAbstractFamily::maxLocalId () const pure virtual
Max local Id for this family.
Implemented in Alien::AbstractItemFamily, and Alien::DefaultAbstractFamily.
Referenced by Alien::IndexManager::getIndexes(), and Alien::IndexManager::getIndexes().
uniqueIdToLocalId()
virtual void Alien::IAbstractFamily::uniqueIdToLocalId (ArrayView< Integer > localIds, ConstArrayView< Int64 > uniqueIds) const pure virtual
Convert unique ids to local ids
Exceptions
FatalError if an item is not found.
The documentation for this class was generated from the following file:
IAbstractFamily.h