Arcane: Arcane::ItemTypeMng Class Reference
Arcane::ItemTypeMng Class Reference
Mesh
Mesh entity type manager.
#include <arcane/core/ItemTypeMng.h>
Public Member Functions
void build (IParallelSuperMng *parallel_mng, ITraceMng *trace)
Effective constructor.
void build (IMesh *mesh)
Constructs the instance associated with the mesh mesh.
ConstArrayView< ItemTypeInfo * > types () const
List of available types.
ItemTypeInfo * typeFromId (Integer id) const
Type corresponding to the number id.
ItemTypeInfo * typeFromId (ItemTypeId id) const
Type corresponding to the number id.
String typeName (Integer id) const
Name of the type corresponding to the number id.
String typeName (ItemTypeId id) const
Name of the type corresponding to the number id.
void printTypes (std::ostream &ostr)
Prints information about available types to the stream ostr.
bool hasGeneralCells (IMesh *mesh) const
Indicates if the mesh mesh contains generic cells (outside of built-in or additional types).
void setMeshWithGeneralCells (IMesh *mesh) noexcept
Allows the mesh to indicate to the ItemTypeMng if it has generic cells.
void buildPolygonTypes ()
Builds types to manage polygons.
ItemTypeId getPolygonType (Int16 nb_node) const
Returns the type for a polygon having nb_node.
Static Public Member Functions
static ItemTypeMng * singleton ()
Singleton instance of the type.
static void destroySingleton ()
Destroys the singleton.
static Integer nbBasicItemType ()
number of available types
static Integer nbBuiltInItemType ()
number of built-in types (excluding additional types)
static Int32 nbHChildrenByItemType (Integer type)
AMR.
Protected Member Functions
ItemTypeMng ()
Empty constructor (uninitialized).
Private Member Functions
void _buildSingleton (IParallelSuperMng *parallel_mng, ITraceMng *trace)
void _buildTypes (IMesh *mesh, IParallelSuperMng *parallel_mng, ITraceMng *trace)
Constructs the entity types.
void _readTypes (IParallelSuperMng *parallel_mng, const String &filename)
Reads types from a file named filename.
void _addPolygonType (Int16 type_id, Int32 nb_node, const String &type_name)
Adds a generic polygon type.
Static Private Member Functions
static ItemTypeMng * _singleton ()
Singleton instance of the type.
static void _destroySingleton ()
Destroys the singleton.
static String _legacyTypeName (Integer t)
Private Attributes
friend ItemTypeInfo
friend ItemTypeInfoBuilder
bool m_initialized = false
Initialization flag.
std::atomic< Int32 > m_initialized_counter = 0
ITraceMng * m_trace = nullptr
Trace manager.
UniqueArray< ItemTypeInfo * > m_types
List of types.
MultiBufferT< ItemTypeInfoBuilder > * m_types_buffer = nullptr
Allocations of type objects (a pointer is needed to avoid multiple inclusion).
std::set< IMesh * > m_mesh_with_general_cells
Set of meshes containing generic cells (without a defined type).
UniqueArray< Integer > m_ids_buffer
Array containing type data.
bool m_has_polygon_type = false
Indicates if the types managing polygons have already been built.
Static Private Attributes
static ItemTypeMng * singleton_instance = 0
Singleton instance.
static const Integer m_nb_builtin_item_type = NB_BASIC_ITEM_TYPE
Number of built-in types (excluding additional types).
Friends
class mesh::DynamicMesh
class mesh::PolyhedralMesh
class Application
class ArcaneMain
class Item
Detailed Description
Mesh entity type manager.
You must call build(IMesh*) before being able to use this instance.
The desired types (other than the default types) must be added before the first mesh is created. It is not possible to create new types during execution.
The available types must be strictly identical for all processes (i.e. All ItemTypeMngs of all processes must have the same types).
Definition at line 65 of file ItemTypeMng.h.
Constructor & Destructor Documentation
ItemTypeMng()
Arcane::ItemTypeMng::ItemTypeMng () protected
Empty constructor (uninitialized).
Definition at line 61 of file ItemTypeMng.cc.
Referenced by _singleton(), and singleton().
~ItemTypeMng()
Arcane::ItemTypeMng::~ItemTypeMng () protected
Definition at line 69 of file ItemTypeMng.cc.
Member Function Documentation
_addPolygonType()
void Arcane::ItemTypeMng::_addPolygonType (Int16 type_id, Int32 nb_node, const String & type_name) private
Adds a generic polygon type.
Adds a degree 1 polygon type with nb_node nodes. The type will have index type_id and name type_name.
Definition at line 1161 of file ItemTypeMng.cc.
References Arcane::ItemTypeInfoBuilder::addEdge(), Arcane::ItemTypeInfoBuilder::addFaceLine(), m_types, and m_types_buffer.
Referenced by _buildTypes(), and buildPolygonTypes().
_buildSingleton()
void Arcane::ItemTypeMng::_buildSingleton (IParallelSuperMng * parallel_mng, ITraceMng * trace) private
Definition at line 103 of file ItemTypeMng.cc.
_buildTypes()
void Arcane::ItemTypeMng::_buildTypes (IMesh * mesh, IParallelSuperMng * parallel_mng, ITraceMng * trace) private
Constructs the entity types.
Note
For the singleton instance, mesh is null.
Definition at line 133 of file ItemTypeMng.cc.
References _addPolygonType(), _readTypes(), Arcane::ItemTypeInfoBuilder::addEdge(), Arcane::ItemTypeInfoBuilder::addEdge2D(), Arcane::ItemTypeInfoBuilder::addEdgeAndFaceLine(), Arcane::ItemTypeInfoBuilder::addFaceHeptagon(), Arcane::ItemTypeInfoBuilder::addFaceHexagon(), Arcane::ItemTypeInfoBuilder::addFaceLine(), Arcane::ItemTypeInfoBuilder::addFaceLine3(), Arcane::ItemTypeInfoBuilder::addFaceLine4(), Arcane::ItemTypeInfoBuilder::addFaceOctogon(), Arcane::ItemTypeInfoBuilder::addFacePentagon(), Arcane::ItemTypeInfoBuilder::addFaceQuad(), Arcane::ItemTypeInfoBuilder::addFaceQuad8(), Arcane::ItemTypeInfoBuilder::addFaceQuad9(), Arcane::ItemTypeInfoBuilder::addFaceTriangle(), Arcane::ItemTypeInfoBuilder::addFaceTriangle6(), Arcane::ItemTypeInfoBuilder::addFaceVertex(), ARCANE_FATAL, Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), Arcane::platform::getEnvironmentVariable(), m_nb_builtin_item_type, m_trace, m_types, m_types_buffer, Arcane::String::null(), Arcane::ItemTypeInfoBuilder::setHasCenterNode(), Arcane::ItemTypeInfoBuilder::setIsValidForCell(), and Arcane::ItemTypeInfoBuilder::setOrder().
Referenced by build().
_destroySingleton()
void Arcane::ItemTypeMng::_destroySingleton () static private
Destroys the singleton.
The singleton can then be reconstructed by calling destroySingleton()
Definition at line 1420 of file ItemTypeMng.cc.
References singleton_instance.
Referenced by Arcane::ArcaneMain::arcaneFinalize(), and destroySingleton().
_legacyTypeName()
String Arcane::ItemTypeMng::_legacyTypeName (Integer t) static private
Definition at line 1483 of file ItemTypeMng.cc.
_readTypes()
void Arcane::ItemTypeMng::_readTypes (IParallelSuperMng * pm, const String & filename) private
Reads types from a file named filename.
Reading a Voronoi type file.
A Voronoi cell is a polytope whose number of faces and nodes varies from one cell to another. Here, the type of each cell is read from a type file associated with a given input mesh. This file is passed via the environment variable: ARCANE_ITEM_TYPE_FILE Ex: setenv ARCANE_ITEM_TYPE_FILE PATH_TO_FILE/item_file The file format is as follows:
nb_type type_id nb_faces nb_edges nb_node_face0 node0_face0 ... nodeN_face1 . . . . . . . . . nb_node_faceN node0_faceN ... nodeN_faceN
node0_edge0 node1_edge1 lefFace_edge0 rightFace_edge0 node0_edgeN node1_edge1 lefFace_edgeN rightFace_edgeN
Definition at line 1232 of file ItemTypeMng.cc.
References Arcane::ItemTypeInfoBuilder::addEdge(), Arcane::ItemTypeInfoBuilder::addFaceGeneric(), Arcane::ItemTypeInfoBuilder::addFaceLine(), ARCANE_FATAL, ARCANE_THROW, Arcane::arcaneCheckArraySize(), Arcane::IParallelSuperMng::broadcast(), Arcane::IParallelSuperMng::commRank(), Arcane::platform::getFileLength(), Arcane::Trace::High, Arcane::String::localstr(), m_trace, m_types, m_types_buffer, nbBuiltInItemType(), and Arcane::ItemTypeInfo::typeName().
Referenced by _buildTypes().
_singleton()
ItemTypeMng * Arcane::ItemTypeMng::_singleton () static private
Singleton instance of the type.
The singleton is created upon the first call to this function. It remains valid until destroySingleton() has been called
Todo
: to be removed as soon as no one accesses singleton()
Definition at line 1412 of file ItemTypeMng.cc.
References ItemTypeMng(), and singleton_instance.
Referenced by Arcane::ArcaneMain::arcaneInitialize(), Arcane::Application::initialize(), nbBasicItemType(), and singleton().
build() [1/2]
void Arcane::ItemTypeMng::build (IMesh * mesh)
Constructs the instance associated with the mesh mesh.
Definition at line 78 of file ItemTypeMng.cc.
References _buildTypes(), ARCANE_FATAL, and m_initialized.
build() [2/2]
void Arcane::ItemTypeMng::build (IParallelSuperMng * parallel_mng, ITraceMng * trace)
Effective constructor.
This method should only be called before initializing the obsolete singleton instance.
Deprecated
Use build(IMesh*) instead.
Definition at line 94 of file ItemTypeMng.cc.
Referenced by Arcane::Application::initialize().
buildPolygonTypes()
void Arcane::ItemTypeMng::buildPolygonTypes ()
Builds types to manage polygons.
This makes the ITI_GenericPolygon type accessible. If these types have already been built, this method has no effect.
Definition at line 1131 of file ItemTypeMng.cc.
References _addPolygonType(), m_has_polygon_type, m_types, and typeFromId().
destroySingleton()
void Arcane::ItemTypeMng::destroySingleton () inline static
Destroys the singleton.
The singleton can then be reconstructed by calling singleton()
Definition at line 137 of file ItemTypeMng.h.
References _destroySingleton(), and destroySingleton().
Referenced by destroySingleton().
getPolygonType()
ItemTypeId Arcane::ItemTypeMng::getPolygonType (Int16 nb_node) const
Returns the type for a polygon having nb_node.
If nb_node is between 3 and 8 inclusive, it returns the corresponding internal type (ITI_Triangle3, ITI_Quad4, ..., ITI_Octogon8). Otherwise, it returns the additional type provided that buildPolygonTypes() has been called beforehand.
Throws a NotSupportedException if no type matches.
Definition at line 1517 of file ItemTypeMng.cc.
References ARCANE_THROW, and m_has_polygon_type.
hasGeneralCells()
bool Arcane::ItemTypeMng::hasGeneralCells (IMesh * mesh) const
Indicates if the mesh mesh contains generic cells (outside of built-in or additional types).
Definition at line 1494 of file ItemTypeMng.cc.
References m_mesh_with_general_cells.
Referenced by Arcane::DumpWEnsight7::_computeGroupParts().
nbBasicItemType()
Integer Arcane::ItemTypeMng::nbBasicItemType () static
number of available types
Definition at line 1356 of file ItemTypeMng.cc.
References _singleton(), and types().
Referenced by Arcane::DumpWEnsight7::_computeGroupParts(), and Arcane::VoronoiMeshIOService::_readCellsHybridGrid().
nbBuiltInItemType()
Integer Arcane::ItemTypeMng::nbBuiltInItemType () static
number of built-in types (excluding additional types)
Definition at line 1362 of file ItemTypeMng.cc.
References m_nb_builtin_item_type.
Referenced by Arcane::DumpWEnsight7::_computeGroupParts(), Arcane::VoronoiMeshIOService::_readCellsHybridGrid(), and _readTypes().
nbHChildrenByItemType()
Int32 Arcane::ItemTypeMng::nbHChildrenByItemType (Integer type) static
AMR.
Definition at line 1371 of file ItemTypeMng.cc.
References ARCANE_FATAL.
Referenced by Arcane::mesh::MeshRefinement::init(), and Arcane::mesh::ItemRefinement::refineOneCell().
printTypes()
void Arcane::ItemTypeMng::printTypes (std::ostream & ostr)
Prints information about available types to the stream ostr.
Definition at line 1181 of file ItemTypeMng.cc.
References Arcane::ItemTypeInfo::localFace(), m_initialized, m_types, Arcane::ItemTypeInfo::nbLocalFace(), Arcane::ItemTypeInfo::nbLocalNode(), Arcane::ItemTypeInfo::LocalFace::nbNode(), Arcane::ItemTypeInfo::LocalFace::node(), Arcane::ItemTypeInfo::typeId(), and Arcane::ItemTypeInfo::typeName().
setMeshWithGeneralCells()
void Arcane::ItemTypeMng::setMeshWithGeneralCells (IMesh * mesh) noexcept
Allows the mesh to indicate to the ItemTypeMng if it has generic cells.
Definition at line 1507 of file ItemTypeMng.cc.
References m_mesh_with_general_cells.
singleton()
ItemTypeMng * Arcane::ItemTypeMng::singleton () inline static
Singleton instance of the type.
The singleton is created upon the first call to this function. It remains valid until destroySingleton() has been called
Definition at line 129 of file ItemTypeMng.h.
References _singleton(), ItemTypeMng(), and singleton().
Referenced by singleton().
typeFromId() [1/2]
ItemTypeInfo * Arcane::ItemTypeMng::typeFromId (Integer id) const
Type corresponding to the number id.
Definition at line 1443 of file ItemTypeMng.cc.
References m_initialized, and m_types.
Referenced by Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::VoronoiMeshIOService::_readCellsHybridGrid(), Arcane::MshParallelMeshReader::_readElementsFromFile(), Arcane::MEDMeshReader::_readFaces(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::VtkMeshIOService::_readUnstructuredGrid(), Arcane::mesh::DynamicMeshIncrementalBuilder::addCells(), Arcane::mesh::DynamicMeshIncrementalBuilder::addFaces(), Arcane::mesh::DynamicMeshIncrementalBuilder::addHChildrenCells(), Arcane::mesh::OneMeshItemAdder::addOneParentItem(), buildPolygonTypes(), Arcane::mesh::FullCellInfo::FullCellInfo(), Arcane::UnstructuredMeshUtilities::getFacesLocalIdFromConnectivity(), Arcane::mesh::ItemFamily::readFromDump(), typeName(), and typeName().
typeFromId() [2/2]
ItemTypeInfo * Arcane::ItemTypeMng::typeFromId (ItemTypeId id) const
Type corresponding to the number id.
Definition at line 1453 of file ItemTypeMng.cc.
References m_initialized, and m_types.
typeName() [1/2]
String Arcane::ItemTypeMng::typeName (Integer id) const
Name of the type corresponding to the number id.
Definition at line 1463 of file ItemTypeMng.cc.
References typeFromId(), and Arcane::ItemTypeInfo::typeName().
typeName() [2/2]
String Arcane::ItemTypeMng::typeName (ItemTypeId id) const
Name of the type corresponding to the number id.
Definition at line 1472 of file ItemTypeMng.cc.
References typeFromId(), and Arcane::ItemTypeInfo::typeName().
types()
ConstArrayView< ItemTypeInfo * > Arcane::ItemTypeMng::types () const
List of available types.
Definition at line 1433 of file ItemTypeMng.cc.
References m_initialized, and m_types.
Referenced by nbBasicItemType().
Friends And Related Symbol Documentation
Application
friend class Application friend
Definition at line 70 of file ItemTypeMng.h.
ArcaneMain
friend class ArcaneMain friend
Definition at line 71 of file ItemTypeMng.h.
Item
friend class Item friend
Definition at line 72 of file ItemTypeMng.h.
mesh::DynamicMesh
friend class mesh::DynamicMesh friend
Definition at line 68 of file ItemTypeMng.h.
mesh::PolyhedralMesh
friend class mesh::PolyhedralMesh friend
Definition at line 69 of file ItemTypeMng.h.
Member Data Documentation
ItemTypeInfo
friend Arcane::ItemTypeMng::ItemTypeInfo private
Definition at line 73 of file ItemTypeMng.h.
ItemTypeInfoBuilder
friend Arcane::ItemTypeMng::ItemTypeInfoBuilder private
Definition at line 74 of file ItemTypeMng.h.
m_has_polygon_type
bool Arcane::ItemTypeMng::m_has_polygon_type = false private
Indicates if the types managing polygons have already been built.
Definition at line 223 of file ItemTypeMng.h.
Referenced by buildPolygonTypes(), and getPolygonType().
m_ids_buffer
UniqueArray<Integer> Arcane::ItemTypeMng::m_ids_buffer private
Array containing type data.
Definition at line 220 of file ItemTypeMng.h.
m_initialized
bool Arcane::ItemTypeMng::m_initialized = false private
Initialization flag.
Definition at line 203 of file ItemTypeMng.h.
Referenced by build(), printTypes(), typeFromId(), typeFromId(), and types().
m_initialized_counter
std::atomic<Int32> Arcane::ItemTypeMng::m_initialized_counter = 0 private
Definition at line 205 of file ItemTypeMng.h.
m_mesh_with_general_cells
std::set<IMesh*> Arcane::ItemTypeMng::m_mesh_with_general_cells private
Set of meshes containing generic cells (without a defined type).
Definition at line 217 of file ItemTypeMng.h.
Referenced by hasGeneralCells(), and setMeshWithGeneralCells().
m_nb_builtin_item_type
const Integer Arcane::ItemTypeMng::m_nb_builtin_item_type = NB_BASIC_ITEM_TYPE static private
Number of built-in types (excluding additional types).
Definition at line 200 of file ItemTypeMng.h.
Referenced by _buildTypes(), and nbBuiltInItemType().
m_trace
ITraceMng* Arcane::ItemTypeMng::m_trace = nullptr private
Trace manager.
Definition at line 208 of file ItemTypeMng.h.
Referenced by _buildTypes(), and _readTypes().
m_types
UniqueArray<ItemTypeInfo*> Arcane::ItemTypeMng::m_types private
List of types.
Definition at line 211 of file ItemTypeMng.h.
Referenced by _addPolygonType(), _buildTypes(), _readTypes(), buildPolygonTypes(), printTypes(), typeFromId(), typeFromId(), and types().
m_types_buffer
MultiBufferT<ItemTypeInfoBuilder>* Arcane::ItemTypeMng::m_types_buffer = nullptr private
Allocations of type objects (a pointer is needed to avoid multiple inclusion).
Definition at line 214 of file ItemTypeMng.h.
Referenced by _addPolygonType(), _buildTypes(), and _readTypes().
singleton_instance
ItemTypeMng * Arcane::ItemTypeMng::singleton_instance = 0 static private
Singleton instance.
Definition at line 197 of file ItemTypeMng.h.
Referenced by _destroySingleton(), and _singleton().
The documentation for this class was generated from the following files:
ItemTypeMng.h
ItemTypeMng.cc