Alien: Alien::MatrixConverterRegisterer Class Reference
Alien::MatrixConverterRegisterer Class Reference
Matrix converter registerer.
#include <core/alien/core/backend/MatrixConverterRegisterer.h>
Public Types
typedef IMatrixConverter *(* ConverterCreateFunc) ()
Type of the matrix converter function.
typedef Alien::BackEndId BackEndId
Type of the backend if.
Public Member Functions
MatrixConverterRegisterer (ConverterCreateFunc func)
Creates a matrix converter registerer.
~MatrixConverterRegisterer ()=default
Free resources.
Static Public Member Functions
static IMatrixConverter * getConverter (BackEndId from, BackEndId to)
Get the converter from one matrix format to another one.
Detailed Description
Matrix converter registerer.
Allows to register a matrix converter to convert a matrix from a format to another
Definition at line 42 of file MatrixConverterRegisterer.h.
Member Typedef Documentation
BackEndId
typedef Alien::BackEndId Alien::MatrixConverterRegisterer::BackEndId
Type of the backend if.
Definition at line 48 of file MatrixConverterRegisterer.h.
ConverterCreateFunc
typedef IMatrixConverter *(* Alien::MatrixConverterRegisterer::ConverterCreateFunc) ()
Type of the matrix converter function.
Definition at line 46 of file MatrixConverterRegisterer.h.
Constructor & Destructor Documentation
MatrixConverterRegisterer()
MatrixConverterRegisterer::MatrixConverterRegisterer (ConverterCreateFunc func) explicit
Creates a matrix converter registerer.
Parameters
[in] func Matrix converter function
Definition at line 40 of file MatrixConverterRegisterer.cc.
Member Function Documentation
getConverter()
IMatrixConverter * MatrixConverterRegisterer::getConverter (BackEndId from, BackEndId to) static
Get the converter from one matrix format to another one.
Parameters
[in] from Backend id of the source format
[in] to Backend id of the target format
Returns
Matrix format converter
Definition at line 51 of file MatrixConverterRegisterer.cc.
References Alien::IMatrixConverter::sourceBackend(), and Alien::IMatrixConverter::targetBackend().
Referenced by Alien::MultiMatrixImpl::updateImpl(), and ~MatrixConverterRegisterer().
The documentation for this class was generated from the following files:
MatrixConverterRegisterer.h
MatrixConverterRegisterer.cc