Alien: Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter Class Reference
Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter Class Reference
Public Member Functions
void init ()
@ Méthodes visibles de l'extérieur
Integer getId () const
Identifiant de l'inserter dans son StreamVBlockMatrixBuilder.
Integer size ()
Nombre d'itération dans l'inserter.
Integer count ()
Nombre de données dans l'inserter.
void end ()
Termine l'inserter (déallocation des données).
bool isBegin ()
Retourne si le filler est au début.
bool isEnd ()
Retourn true, le filler est à la fin.
Protected Member Functions
BaseInserter (StreamVBlockMatrixBuilderT< ValueT > *parent, Integer id)
void setMatrixValues (ValueT *matrix_values)
void _startTimer ()
void _stopTimer ()
Protected Attributes
Integer m_id
Integer m_index
Integer m_current_size
Integer * m_current_k
ValueT * m_values
Integer m_count
Integer m_size
UniqueArray< Integer > m_n
Integer m_current_block_size_row
Integer m_current_block_size_col
UniqueArray< Integer > m_block_size_row
UniqueArray< Integer > m_block_size_col
UniqueArray< Integer > m_row_index
UniqueArray< Integer > m_col_index
UniqueArray< Integer > m_data_index
positon of entry in the Matrix CSR structure
StreamVBlockMatrixBuilderT< ValueT > * m_parent
Friends
class StreamVBlockMatrixBuilderT< ValueT >
Detailed Description
template<typename ValueT = Real>
class Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter
Definition at line 29 of file StreamVBlockMatrixBuilderInserter.h.
Constructor & Destructor Documentation
BaseInserter() [1/2]
template<typename ValueT> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::BaseInserter () protected
Definition at line 33 of file StreamVBlockMatrixBuilderInserterT.h.
BaseInserter() [2/2]
template<typename ValueT> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::BaseInserter (StreamVBlockMatrixBuilderT< ValueT > * parent, Integer id) protected
Definition at line 42 of file StreamVBlockMatrixBuilderInserterT.h.
~BaseInserter()
template<typename ValueT> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::~BaseInserter () protected virtual
Definition at line 57 of file StreamVBlockMatrixBuilderInserterT.h.
Member Function Documentation
_startTimer()
template<typename ValueT = Real> void Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::_startTimer () inline protected
Definition at line 62 of file StreamVBlockMatrixBuilderInserter.h.
_stopTimer()
template<typename ValueT = Real> void Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::_stopTimer () inline protected
Definition at line 63 of file StreamVBlockMatrixBuilderInserter.h.
count()
template<typename ValueT> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::count ()
Nombre de données dans l'inserter.
Definition at line 121 of file StreamVBlockMatrixBuilderInserterT.h.
References count().
Referenced by Alien::StreamVBlockMatrixBuilderT< ValueT >::computeProfile(), and count().
end()
template<typename ValueT> void Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::end ()
Termine l'inserter (déallocation des données).
Definition at line 85 of file StreamVBlockMatrixBuilderInserterT.h.
References end(), init(), and m_data_index.
Referenced by end().
getId()
template<typename ValueT> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::getId () const
Identifiant de l'inserter dans son StreamVBlockMatrixBuilder.
Definition at line 77 of file StreamVBlockMatrixBuilderInserterT.h.
References getId().
Referenced by Alien::StreamVBlockMatrixBuilderT< ValueT >::computeProfile(), and getId().
init()
template<typename ValueT> void Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::init ()
@ Méthodes visibles de l'extérieur
Definition at line 63 of file StreamVBlockMatrixBuilderInserterT.h.
References init().
Referenced by end(), and init().
setMatrixValues()
template<typename ValueT> void Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::setMatrixValues (ValueT * matrix_values) protected
Definition at line 99 of file StreamVBlockMatrixBuilderInserterT.h.
size()
template<typename ValueT> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::size ()
Nombre d'itération dans l'inserter.
Definition at line 112 of file StreamVBlockMatrixBuilderInserterT.h.
References size().
Referenced by size().
Friends And Related Symbol Documentation
StreamVBlockMatrixBuilderT< ValueT >
template<typename ValueT = Real> friend class StreamVBlockMatrixBuilderT< ValueT > friend
Definition at line 1 of file StreamVBlockMatrixBuilderInserter.h.
Member Data Documentation
m_block_size_col
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_block_size_col protected
Definition at line 76 of file StreamVBlockMatrixBuilderInserter.h.
m_block_size_row
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_block_size_row protected
Definition at line 75 of file StreamVBlockMatrixBuilderInserter.h.
m_col_index
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_col_index protected
Definition at line 78 of file StreamVBlockMatrixBuilderInserter.h.
m_count
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_count protected
Definition at line 70 of file StreamVBlockMatrixBuilderInserter.h.
m_current_block_size_col
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_current_block_size_col protected
Definition at line 74 of file StreamVBlockMatrixBuilderInserter.h.
m_current_block_size_row
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_current_block_size_row protected
Definition at line 73 of file StreamVBlockMatrixBuilderInserter.h.
m_current_k
template<typename ValueT = Real> Integer* Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_current_k protected
Definition at line 68 of file StreamVBlockMatrixBuilderInserter.h.
m_current_size
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_current_size protected
Definition at line 67 of file StreamVBlockMatrixBuilderInserter.h.
m_data_index
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_data_index protected
positon of entry in the Matrix CSR structure
Definition at line 80 of file StreamVBlockMatrixBuilderInserter.h.
Referenced by Alien::StreamVBlockMatrixBuilderT< ValueT >::computeProfile(), and end().
m_id
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_id protected
Definition at line 65 of file StreamVBlockMatrixBuilderInserter.h.
m_index
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_index protected
Definition at line 66 of file StreamVBlockMatrixBuilderInserter.h.
m_n
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_n protected
Definition at line 72 of file StreamVBlockMatrixBuilderInserter.h.
m_parent
template<typename ValueT = Real> StreamVBlockMatrixBuilderT<ValueT>* Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_parent protected
Definition at line 81 of file StreamVBlockMatrixBuilderInserter.h.
m_row_index
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_row_index protected
Definition at line 77 of file StreamVBlockMatrixBuilderInserter.h.
m_size
template<typename ValueT = Real> Integer Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_size protected
Definition at line 71 of file StreamVBlockMatrixBuilderInserter.h.
m_values
template<typename ValueT = Real> ValueT* Alien::StreamVBlockMatrixBuilderT< ValueT >::BaseInserter::m_values protected
Definition at line 69 of file StreamVBlockMatrixBuilderInserter.h.
The documentation for this class was generated from the following files:
StreamVBlockMatrixBuilderInserter.h
StreamVBlockMatrixBuilderInserterT.h