Alien: Alien::ScalarIndexSet Class Reference
Alien::ScalarIndexSet Class Reference
#include <core/alien/index_manager/ScalarIndexSet.h>
Classes
struct Internal
Public Member Functions
ScalarIndexSet (const ScalarIndexSet &en)
ScalarIndexSet (ScalarIndexSet &&en) noexcept
ScalarIndexSet (const String &name, Integer creationIndex, const IndexManager *manager, Integer kind)
ScalarIndexSet & operator= (const ScalarIndexSet &en)
ScalarIndexSet & operator= (ScalarIndexSet &&en) noexcept
Opérateur de copie.
bool operator== (const ScalarIndexSet &en) const
Opérateur de comparaison.
ConstArrayView< Integer > getOwnIndexes () const
Indices of owned, for this entry.
ConstArrayView< Integer > getAllIndexes () const
Indices of owned then ghosts, for this entry.
ConstArrayView< Integer > getOwnLocalIds () const
ConstArrayView< Integer > getAllLocalIds () const
String getName () const
Integer getKind () const
Item where the entry is defined.
Integer getUid () const
Creation label.
const IAbstractFamily & getFamily () const
const IndexManager * manager () const
Associated index manager.
Private Attributes
std::shared_ptr< Internal > m_internal
Detailed Description
Index handler.
This class is just a proxy, so its copy is cheap and its implementation can vary.
Definition at line 43 of file ScalarIndexSet.h.
Constructor & Destructor Documentation
ScalarIndexSet() [1/2]
Alien::ScalarIndexSet::ScalarIndexSet (ScalarIndexSet && en) noexcept
Definition at line 53 of file ScalarIndexSet.cc.
ScalarIndexSet() [2/2]
Alien::ScalarIndexSet::ScalarIndexSet (const String & name, Integer creationIndex, const IndexManager * manager, Integer kind)
Definition at line 59 of file ScalarIndexSet.cc.
Member Function Documentation
getAllIndexes()
ConstArrayView< Integer > Alien::ScalarIndexSet::getAllIndexes () const
Indices of owned then ghosts, for this entry.
Definition at line 97 of file ScalarIndexSet.cc.
References manager().
getAllLocalIds()
ConstArrayView< Integer > Alien::ScalarIndexSet::getAllLocalIds () const
Definition at line 113 of file ScalarIndexSet.cc.
getFamily()
const IAbstractFamily & Alien::ScalarIndexSet::getFamily () const
Definition at line 137 of file ScalarIndexSet.cc.
getKind()
Integer Alien::ScalarIndexSet::getKind () const
Item where the entry is defined.
Definition at line 129 of file ScalarIndexSet.cc.
getName()
String Alien::ScalarIndexSet::getName () const
Definition at line 121 of file ScalarIndexSet.cc.
getOwnIndexes()
ConstArrayView< Integer > Alien::ScalarIndexSet::getOwnIndexes () const
Indices of owned, for this entry.
Definition at line 89 of file ScalarIndexSet.cc.
References manager().
getOwnLocalIds()
ConstArrayView< Integer > Alien::ScalarIndexSet::getOwnLocalIds () const
Definition at line 105 of file ScalarIndexSet.cc.
getUid()
Integer Alien::ScalarIndexSet::getUid () const
Creation label.
Definition at line 153 of file ScalarIndexSet.cc.
Referenced by Alien::IndexManager::removeIndex().
manager()
const IndexManager * Alien::ScalarIndexSet::manager () const
Associated index manager.
Definition at line 145 of file ScalarIndexSet.cc.
Referenced by getAllIndexes(), Alien::IndexManager::getIndexes(), getOwnIndexes(), and Alien::IndexManager::removeIndex().
operator=()
ScalarIndexSet & Alien::ScalarIndexSet::operator= (ScalarIndexSet && en) noexcept
Opérateur de copie.
Definition at line 72 of file ScalarIndexSet.cc.
operator==()
bool Alien::ScalarIndexSet::operator== (const ScalarIndexSet & en) const
Opérateur de comparaison.
Definition at line 81 of file ScalarIndexSet.cc.
Member Data Documentation
m_internal
std::shared_ptr<Internal> Alien::ScalarIndexSet::m_internal private
Definition at line 86 of file ScalarIndexSet.h.
The documentation for this class was generated from the following files:
ScalarIndexSet.h
ScalarIndexSet.cc