Arcane: Arcane::Real2x2 Class Reference
Arcane::Real2x2 Class Reference
Class managing a 2x2 matrix of reals.
#include <arccore/base/Real2x2.h>
Public Member Functions
constexpr __host__ __device__ Real2x2 ()
Constructs the zero matrix.
constexpr __host__ __device__ Real2x2 (Real2 ax, Real2 ay)
Constructs the pair (ax,ay).
Real2x2 (const Real2x2 &f)=default
Constructs a copy identical to f.
constexpr __host__ __device__ Real2x2 (const Real2x2POD &f)
Constructs a copy identical to f.
constexpr __host__ __device__ Real2x2 (Real v)
Constructs the instance with the triplet (v,v,v).
constexpr __host__ __device__ Real2x2 (ConstArrayView< Real > av)
Constructs the pair ((av[0], av[1]), (av[2], av[3])).
Real2x2 & operator= (const Real2x2 &f)=default
Copy assignment operator.
constexpr __host__ __device__ Real2x2 & operator= (Real v)
Assigns the pair (v,v,v) to the instance.
constexpr __host__ __device__ Real2x2 copy () const
Returns a copy of the pair.
constexpr __host__ __device__ Real2x2 & reset ()
Resets the pair with default constructors.
constexpr __host__ __device__ Real2x2 & assign (Real2 ax, Real2 ay)
Assigns the pair (ax,ay) to the instance.
constexpr __host__ __device__ Real2x2 & assign (Real2x2 f)
Copies the pair f.
constexpr __host__ __device__ ArrayView< Real > view ()
constexpr __host__ __device__ ConstArrayView< Real > constView () const
std::istream & assign (std::istream &i)
Reads the matrix from the stream i The matrix is read in the form of three Real2.
std::ostream & print (std::ostream &o) const
Writes the pair to the stream o readable by an assign().
std::ostream & printXy (std::ostream &o) const
Writes the pair to the stream o in the form (x,y,z).
constexpr __host__ __device__ Real2x2 & add (Real2x2 b)
Adds b to the pair.
constexpr __host__ __device__ Real2x2 & sub (Real2x2 b)
Subtracts b from the pair.
constexpr __host__ __device__ Real2x2 & div (Real2x2 b)
Multiplies each component of the pair by the corresponding component of b.
constexpr __host__ __device__ Real2x2 & addSame (Real2 b)
Adds b to each component of the pair.
constexpr __host__ __device__ Real2x2 & subSame (Real2 b)
Subtracts b from each component of the pair.
constexpr __host__ __device__ Real2x2 & mulSame (Real2 b)
Multiplies each component of the pair by b.
constexpr __host__ __device__ Real2x2 & divSame (Real2 b)
Divides each component of the pair by b.
constexpr __host__ __device__ Real2x2 & operator+= (Real2x2 b)
Adds b to the pair.
constexpr __host__ __device__ Real2x2 & operator-= (Real2x2 b)
Subtracts b from the pair.
constexpr __host__ __device__ void operator*= (Real b)
Multiplies each component of the pair by the corresponding component of b.
constexpr __host__ __device__ void operator/= (Real b)
Divides each component of the pair by the corresponding component of b.
constexpr __host__ __device__ Real2x2 operator+ (Real2x2 b) const
Creates a pair that equals this pair added to b.
constexpr __host__ __device__ Real2x2 operator- (Real2x2 b) const
Creates a pair that equals b subtracted from this pair.
constexpr __host__ __device__ Real2x2 operator- () const
Creates an inverse tensor of the current tensor.
constexpr __host__ __device__ bool operator== (Real2x2 b) const
Compares component by component the current instance to b.
constexpr __host__ __device__ bool operator!= (Real2x2 b) const
Compares two pairs. For the notion of equality, see operator==().
__host__ __device__ Real2 operator[] (Integer i) const
Read-only access to the i-th (between 0 and 1 inclusive) row of the instance.
__host__ __device__ Real2 operator() (Integer i) const
Read-only access to the i-th (between 0 and 1 inclusive) row of the instance.
__host__ __device__ Real operator() (Integer i, Integer j) const
Read-only access to the i-th row and j-th column.
__host__ __device__ Real2 & operator[] (Integer i)
Access to the i-th row (between 0 and 1 inclusive) of the instance.
__host__ __device__ Real2 & operator() (Integer i)
Access to the i-th row (between 0 and 1 inclusive) of the instance.
__host__ __device__ Real & operator() (Integer i, Integer j)
Access to the i-th row and j-th column.
constexpr __host__ __device__ bool isNearlyZero () const
Compares the matrix with the zero matrix.
Static Public Member Functions
constexpr __host__ static __device__ Real2x2 null ()
Constructs the zero matrix.
constexpr __host__ static __device__ Real2x2 fromColumns (Real ax, Real ay, Real bx, Real by)
Constructs the pair ((ax,bx),(ay,by)).
constexpr __host__ static __device__ Real2x2 fromLines (Real ax, Real bx, Real ay, Real by)
Constructs the pair ((ax,bx),(ay,by)).
Public Attributes
Real2 x
First component.
Real2 y
Second component.
Friends
std::ostream & operator<< (std::ostream &o, Real2x2 t)
Writes the pair t to the stream o.
std::istream & operator>> (std::istream &i, Real2x2 &t)
Reads the pair t from the stream o.
constexpr __host__ __device__ Real2x2 operator* (Real sca, Real2x2 vec)
Multiplication by a scalar.
constexpr __host__ __device__ Real2x2 operator* (Real2x2 vec, Real sca)
Multiplication by a scalar.
constexpr __host__ __device__ Real2x2 operator/ (Real2x2 vec, Real sca)
Division by a scalar.
constexpr __host__ __device__ bool operator< (Real2x2 v1, Real2x2 v2)
Comparison operator.
Detailed Description
Class managing a 2x2 matrix of reals.
The matrix comprises two components x and y which are of the type Real2. For example:
Real2x2 matrix;
matrix.x.y = 2.;
matrix.y.y = 3.;
Definition at line 55 of file arccore/src/base/arccore/base/Real2x2.h.
Constructor & Destructor Documentation
Real2x2() [1/5]
__host__ __device__ Arcane::Real2x2::Real2x2 () inline constexpr
Constructs the zero matrix.
Definition at line 60 of file arccore/src/base/arccore/base/Real2x2.h.
References null(), x, and y.
Referenced by add(), addSame(), assign(), assign(), copy(), div(), divSame(), fromColumns(), fromLines(), mulSame(), null(), operator!=(), operator*, operator*, operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/, operator<, operator<<, operator=(), operator=(), operator==(), operator>>, Real2x2(), reset(), sub(), and subSame().
Real2x2() [2/5]
__host__ __device__ Arcane::Real2x2::Real2x2 (Real2 ax, Real2 ay) inline constexpr
Constructs the pair (ax,ay).
Definition at line 66 of file arccore/src/base/arccore/base/Real2x2.h.
References x, and y.
Real2x2() [3/5]
__host__ __device__ Arcane::Real2x2::Real2x2 (const Real2x2POD & f) inline explicit constexpr
Constructs a copy identical to f.
Definition at line 86 of file arccore/src/base/arccore/base/Real2x2.h.
References x, and y.
Real2x2() [4/5]
__host__ __device__ Arcane::Real2x2::Real2x2 (Real v) inline explicit constexpr
Constructs the instance with the triplet (v,v,v).
Definition at line 92 of file arccore/src/base/arccore/base/Real2x2.h.
References x, and y.
Real2x2() [5/5]
__host__ __device__ Arcane::Real2x2::Real2x2 (ConstArrayView< Real > av) inline explicit constexpr
Constructs the pair ((av[0], av[1]), (av[2], av[3])).
Definition at line 98 of file arccore/src/base/arccore/base/Real2x2.h.
References x, and y.
Member Function Documentation
add()
__host__ __device__ Real2x2 & Arcane::Real2x2::add (Real2x2 b) inline constexpr
Adds b to the pair.
Definition at line 190 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
Referenced by operator+=().
addSame()
__host__ __device__ Real2x2 & Arcane::Real2x2::addSame (Real2 b) inline constexpr
Adds b to each component of the pair.
Definition at line 217 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
assign() [1/3]
__host__ __device__ Real2x2 & Arcane::Real2x2::assign (Real2 ax, Real2 ay) inline constexpr
Assigns the pair (ax,ay) to the instance.
Definition at line 148 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
Referenced by operator>>.
assign() [2/3]
__host__ __device__ Real2x2 & Arcane::Real2x2::assign (Real2x2 f) inline constexpr
Copies the pair f.
Definition at line 156 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
assign() [3/3]
std::istream & Arcane::Real2x2::assign (std::istream & i)
Reads the matrix from the stream i The matrix is read in the form of three Real2.
Definition at line 28 of file Real2x2.cc.
References x, and y.
constView()
__host__ __device__ ConstArrayView< Real > Arcane::Real2x2::constView () const inline constexpr
Returns a constant view of the four elements of the matrix. [x.x, x.y, y.x, y.y]
Definition at line 172 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
copy()
__host__ __device__ Real2x2 Arcane::Real2x2::copy () const inline constexpr
Returns a copy of the pair.
Definition at line 138 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2().
div()
__host__ __device__ Real2x2 & Arcane::Real2x2::div (Real2x2 b) inline constexpr
Multiplies each component of the pair by the corresponding component of b.
Divides each component of the pair by the corresponding component of b
Definition at line 209 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
divSame()
__host__ __device__ Real2x2 & Arcane::Real2x2::divSame (Real2 b) inline constexpr
Divides each component of the pair by b.
Definition at line 241 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
fromColumns()
__host__ static __device__ Real2x2 Arcane::Real2x2::fromColumns (Real ax, Real ay, Real bx, Real by) inline static constexpr
Constructs the pair ((ax,bx),(ay,by)).
Definition at line 124 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2().
fromLines()
__host__ static __device__ Real2x2 Arcane::Real2x2::fromLines (Real ax, Real bx, Real ay, Real by) inline static constexpr
Constructs the pair ((ax,bx),(ay,by)).
Definition at line 130 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2().
Referenced by Arcane::NumMatrix< DataType, Row, Column >::operator Real2x2().
isNearlyZero()
__host__ __device__ bool Arcane::Real2x2::isNearlyZero () const inline constexpr
Compares the matrix with the zero matrix.
The matrix is zero if and only if each of its components is less than a given epsilon. The epsilon value used is that of float_info<value_type>::nearlyEpsilon():
\[A=0 \Leftrightarrow |A.x|<\epsilon,|A.y|<\epsilon\]
Return values
true if the matrix is equal to the zero matrix,
false otherwise.
Definition at line 55 of file MathReal2x2.h.
mulSame()
__host__ __device__ Real2x2 & Arcane::Real2x2::mulSame (Real2 b) inline constexpr
Multiplies each component of the pair by b.
Definition at line 233 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
null()
__host__ static __device__ Real2x2 Arcane::Real2x2::null () inline static constexpr
Constructs the zero matrix.
Definition at line 121 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2().
Referenced by Arcane::DataTypeTraitsT< Real2x2 >::defaultValue(), Real2x2(), reset(), and Arcane::Real2x2Proxy::reset().
operator!=()
__host__ __device__ bool Arcane::Real2x2::operator!= (Real2x2 b) const inline constexpr
Compares two pairs. For the notion of equality, see operator==().
Return values
true if the two pairs are different,
false otherwise.
Definition at line 300 of file arccore/src/base/arccore/base/Real2x2.h.
References operator==(), and Real2x2().
operator()() [1/4]
__host__ __device__ Real2 & Arcane::Real2x2::operator() (Integer i) inline
Access to the i-th row (between 0 and 1 inclusive) of the instance.
Parameters
i row number to return
Definition at line 351 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
operator()() [2/4]
__host__ __device__ Real2 Arcane::Real2x2::operator() (Integer i) const inline
Read-only access to the i-th (between 0 and 1 inclusive) row of the instance.
Parameters
i row number to return
Definition at line 319 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
operator()() [3/4]
__host__ __device__ Real & Arcane::Real2x2::operator() (Integer i, Integer j) inline
Access to the i-th row and j-th column.
Parameters
i row number to return
j column number to return
Definition at line 362 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
operator()() [4/4]
__host__ __device__ Real Arcane::Real2x2::operator() (Integer i, Integer j) const inline
Read-only access to the i-th row and j-th column.
Parameters
i row number to return
j column number to return
Definition at line 330 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
operator*=()
__host__ __device__ void Arcane::Real2x2::operator*= (Real b) inline constexpr
Multiplies each component of the pair by the corresponding component of b.
Multiplies each component of the matrix by the real b
Definition at line 258 of file arccore/src/base/arccore/base/Real2x2.h.
References x, and y.
operator+()
__host__ __device__ Real2x2 Arcane::Real2x2::operator+ (Real2x2 b) const inline constexpr
Creates a pair that equals this pair added to b.
Definition at line 275 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator+=()
__host__ __device__ Real2x2 & Arcane::Real2x2::operator+= (Real2x2 b) inline constexpr
Adds b to the pair.
Definition at line 249 of file arccore/src/base/arccore/base/Real2x2.h.
References add(), and Real2x2().
operator-() [1/2]
__host__ __device__ Real2x2 Arcane::Real2x2::operator- () const inline constexpr
Creates an inverse tensor of the current tensor.
Definition at line 281 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator-() [2/2]
__host__ __device__ Real2x2 Arcane::Real2x2::operator- (Real2x2 b) const inline constexpr
Creates a pair that equals b subtracted from this pair.
Definition at line 278 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator-=()
__host__ __device__ Real2x2 & Arcane::Real2x2::operator-= (Real2x2 b) inline constexpr
Subtracts b from the pair.
Definition at line 252 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), and sub().
operator/=()
__host__ __device__ void Arcane::Real2x2::operator/= (Real b) inline constexpr
Divides each component of the pair by the corresponding component of b.
Divides each component of the matrix by the real b
Definition at line 268 of file arccore/src/base/arccore/base/Real2x2.h.
References x, and y.
operator=()
__host__ __device__ Real2x2 & Arcane::Real2x2::operator= (Real v) inline constexpr
Assigns the pair (v,v,v) to the instance.
Definition at line 107 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator==()
__host__ __device__ bool Arcane::Real2x2::operator== (Real2x2 b) const inline constexpr
Compares component by component the current instance to b.
Return values
true if this.x==b.x and this.y==b.y.
false otherwise.
Definition at line 289 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
Referenced by operator!=().
operator[]() [1/2]
__host__ __device__ Real2 & Arcane::Real2x2::operator[] (Integer i) inline
Access to the i-th row (between 0 and 1 inclusive) of the instance.
Parameters
i row number to return
Definition at line 341 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
operator[]() [2/2]
__host__ __device__ Real2 Arcane::Real2x2::operator[] (Integer i) const inline
Read-only access to the i-th (between 0 and 1 inclusive) row of the instance.
Parameters
i row number to return
Definition at line 309 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
print()
std::ostream & Arcane::Real2x2::print (std::ostream & o) const
Writes the pair to the stream o readable by an assign().
Definition at line 38 of file Real2x2.cc.
References x, and y.
printXy()
std::ostream & Arcane::Real2x2::printXy (std::ostream & o) const
Writes the pair to the stream o in the form (x,y,z).
Definition at line 48 of file Real2x2.cc.
References x, and y.
Referenced by operator<<.
reset()
__host__ __device__ Real2x2 & Arcane::Real2x2::reset () inline constexpr
Resets the pair with default constructors.
Definition at line 141 of file arccore/src/base/arccore/base/Real2x2.h.
References null(), and Real2x2().
sub()
__host__ __device__ Real2x2 & Arcane::Real2x2::sub (Real2x2 b) inline constexpr
Subtracts b from the pair.
Definition at line 198 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
Referenced by operator-=().
subSame()
__host__ __device__ Real2x2 & Arcane::Real2x2::subSame (Real2 b) inline constexpr
Subtracts b from each component of the pair.
Definition at line 225 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
view()
__host__ __device__ ArrayView< Real > Arcane::Real2x2::view () inline constexpr
Returns a view of the four elements of the matrix. [x.x, x.y, y.x, y.y]
Definition at line 165 of file arccore/src/base/arccore/base/Real2x2.h.
References x.
Friends And Related Symbol Documentation
operator* [1/2]
__host__ __device__ Real2x2 operator* (Real sca, Real2x2 vec) friend
Multiplication by a scalar.
Definition at line 384 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator* [2/2]
__host__ __device__ Real2x2 operator* (Real2x2 vec, Real sca) friend
Multiplication by a scalar.
Definition at line 390 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator/
__host__ __device__ Real2x2 operator/ (Real2x2 vec, Real sca) friend
Division by a scalar.
Definition at line 396 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator<
__host__ __device__ bool operator< (Real2x2 v1, Real2x2 v2) friend
Comparison operator.
This operator allows sorting Real2x2 for example in std::set
Definition at line 407 of file arccore/src/base/arccore/base/Real2x2.h.
References Real2x2(), x, and y.
operator<<
std::ostream & operator<< (std::ostream & o, Real2x2 t) friend
Writes the pair t to the stream o.
Definition at line 372 of file arccore/src/base/arccore/base/Real2x2.h.
References printXy(), and Real2x2().
operator>>
std::istream & operator>> (std::istream & i, Real2x2 & t) friend
Reads the pair t from the stream o.
Definition at line 378 of file arccore/src/base/arccore/base/Real2x2.h.
References assign(), and Real2x2().
Member Data Documentation
x
Real2 Arcane::Real2x2::x
First component.
Definition at line 115 of file arccore/src/base/arccore/base/Real2x2.h.
Referenced by add(), Arcane::Real2x2Proxy::add(), addSame(), assign(), assign(), assign(), constView(), div(), Arcane::Real2x2Proxy::div(), divSame(), Arcane::math::doubleContraction(), Arcane::math::isNearlyZero(), Arcane::math::max(), Arcane::math::min(), mulSame(), operator()(), operator()(), operator()(), operator()(), operator*, operator*, operator*=(), operator+(), Arcane::Real2x2Proxy::operator+(), operator-(), operator-(), Arcane::Real2x2Proxy::operator-(), operator/, operator/=(), operator<, operator=(), operator==(), operator[](), operator[](), print(), printXy(), Real2x2(), Real2x2(), Real2x2(), Real2x2(), Real2x2(), sub(), Arcane::Real2x2Proxy::sub(), subSame(), and view().
y
Real2 Arcane::Real2x2::y
Second component.
Definition at line 116 of file arccore/src/base/arccore/base/Real2x2.h.
Referenced by add(), Arcane::Real2x2Proxy::add(), addSame(), assign(), assign(), assign(), div(), Arcane::Real2x2Proxy::div(), divSame(), Arcane::math::doubleContraction(), Arcane::math::isNearlyZero(), Arcane::math::max(), Arcane::math::min(), mulSame(), operator*, operator*, operator*=(), operator+(), Arcane::Real2x2Proxy::operator+(), operator-(), operator-(), Arcane::Real2x2Proxy::operator-(), operator/, operator/=(), operator<, operator=(), operator==(), print(), printXy(), Real2x2(), Real2x2(), Real2x2(), Real2x2(), Real2x2(), sub(), Arcane::Real2x2Proxy::sub(), and subSame().
The documentation for this class was generated from the following files:
arccore/src/base/arccore/base/Real2x2.h
MathReal2x2.h
Real2x2.cc