Arcane: Arcane::IndexedItemConnectivityViewT< ItemType, Face > Class Template Reference
Arcane::IndexedItemConnectivityViewT< ItemType, Face > Class Template Reference
View of ItemType->Face connectivity.
#include <arcane/core/IndexedItemConnectivityView.h>
Public Types
using BaseClass = IndexedItemConnectivityGenericViewT<ItemType, Face>
using ItemLocalIdType = ItemType::LocalIdType
using ItemLocalIdViewType = BaseClass::ItemLocalIdViewType
using ItemLocalId2 = BaseClass::ItemLocalId2
Public Types inherited from Arcane::IndexedItemConnectivityGenericViewT< ItemType, Face >
using ItemType1Type
using ItemType2Type
using ItemLocalId1
using ItemLocalId2
using ItemLocalIdViewType
Public Member Functions
explicit (false) IndexedItemConnectivityViewT(IndexedItemConnectivityViewBase view)
constexpr __host__ __device__ Int32 nbFace (ItemLocalIdType lid) const
Number of faces connected to entity lid.
constexpr __host__ __device__ ItemLocalIdViewType faces (ItemLocalIdType lid) const
List of faces connected to entity lid.
constexpr __host__ __device__ ItemLocalIdViewType faceIds (ItemLocalIdType lid) const
List of faces connected to entity lid.
constexpr __host__ __device__ ItemLocalId2 faceId (ItemLocalIdType lid, Int32 index) const
i-th face connected to entity lid
Public Member Functions inherited from Arcane::IndexedItemConnectivityGenericViewT< ItemType, Face >
explicit (false) IndexedItemConnectivityGenericViewT(IndexedItemConnectivityViewBase view)
constexpr __host__ __device__ ItemLocalIdViewType items (ItemLocalId1 lid) const
List of entities connected to entity lid.
constexpr __host__ __device__ ItemLocalIdViewType itemIds (ItemLocalId1 lid) const
List of entities connected to entity lid.
constexpr __host__ __device__ ItemLocalId2 itemId (ItemLocalId1 lid, Int32 index) const
i-th entity connected to entity lid
Public Member Functions inherited from Arcane::IndexedItemConnectivityViewBase2
constexpr __host__ __device__ Int32 nbSourceItem () const
Number of source entities.
constexpr __host__ __device__ Int32 nbItem (ItemLocalId lid) const
Number of entities connected to entity lid.
constexpr __host__ __device__ ItemLocalIdListViewT< Item > items (ItemLocalId lid) const
List of entities connected to entity lid.
Additional Inherited Members
Protected Member Functions inherited from Arcane::IndexedItemConnectivityViewBase2
IndexedItemConnectivityViewBase2 (IndexedItemConnectivityViewBase view)
Protected Attributes inherited from Arcane::IndexedItemConnectivityViewBase2
ItemConnectivityContainerView m_container_view
Detailed Description
template<typename ItemType>
class Arcane::IndexedItemConnectivityViewT< ItemType, Face >
View of ItemType->Face connectivity.
Definition at line 298 of file IndexedItemConnectivityView.h.
Member Typedef Documentation
BaseClass
template<typename ItemType> using Arcane::IndexedItemConnectivityViewT< ItemType, Face >::BaseClass = IndexedItemConnectivityGenericViewT<ItemType, Face>
Definition at line 303 of file IndexedItemConnectivityView.h.
ItemLocalId2
template<typename ItemType> using Arcane::IndexedItemConnectivityViewT< ItemType, Face >::ItemLocalId2 = BaseClass::ItemLocalId2
Definition at line 306 of file IndexedItemConnectivityView.h.
ItemLocalIdType
template<typename ItemType> using Arcane::IndexedItemConnectivityViewT< ItemType, Face >::ItemLocalIdType = ItemType::LocalIdType
Definition at line 304 of file IndexedItemConnectivityView.h.
ItemLocalIdViewType
template<typename ItemType> using Arcane::IndexedItemConnectivityViewT< ItemType, Face >::ItemLocalIdViewType = BaseClass::ItemLocalIdViewType
Definition at line 305 of file IndexedItemConnectivityView.h.
Member Function Documentation
explicit()
template<typename ItemType> Arcane::IndexedItemConnectivityViewT< ItemType, Face >::explicit (false) inline
Definition at line 310 of file IndexedItemConnectivityView.h.
faceId()
template<typename ItemType> __host__ __device__ ItemLocalId2 Arcane::IndexedItemConnectivityViewT< ItemType, Face >::faceId (ItemLocalIdType lid, Int32 index) const inline constexpr
i-th face connected to entity lid
Definition at line 333 of file IndexedItemConnectivityView.h.
References Arcane::IndexedItemConnectivityGenericViewT< ItemType, Face >::itemId().
faceIds()
template<typename ItemType> __host__ __device__ ItemLocalIdViewType Arcane::IndexedItemConnectivityViewT< ItemType, Face >::faceIds (ItemLocalIdType lid) const inline constexpr
List of faces connected to entity lid.
Definition at line 328 of file IndexedItemConnectivityView.h.
References Arcane::IndexedItemConnectivityGenericViewT< ItemType, Face >::items().
faces()
template<typename ItemType> __host__ __device__ ItemLocalIdViewType Arcane::IndexedItemConnectivityViewT< ItemType, Face >::faces (ItemLocalIdType lid) const inline constexpr
List of faces connected to entity lid.
Definition at line 323 of file IndexedItemConnectivityView.h.
References Arcane::IndexedItemConnectivityGenericViewT< ItemType, Face >::items().
nbFace()
template<typename ItemType> __host__ __device__ Int32 Arcane::IndexedItemConnectivityViewT< ItemType, Face >::nbFace (ItemLocalIdType lid) const inline constexpr
Number of faces connected to entity lid.
Definition at line 318 of file IndexedItemConnectivityView.h.
References Arcane::IndexedItemConnectivityViewBase2::nbItem().
The documentation for this class was generated from the following file:
IndexedItemConnectivityView.h