Alien: Alien::Universe Class Reference
Alien::Universe Class Reference final
Alien universe. Common structure to store shared objects between all elements of the library Alien.
#include <core/alien/data/Universe.h>
Classes
struct Internal
Universe internal structure.
Public Member Functions
Universe ()
Default constructor.
void setTraceMng (Arccore::ITraceMng *traceMng)
Set trace manager.
Arccore::ITraceMng * traceMng () const
Get the trace manager.
void setVerbosityLevel (Verbosity::Level level)
Set verbosity level.
Verbosity::Level verbosityLevel () const
Get the verbosity level.
void reset ()
Reset the universe.
UniverseDataBase & dataBase ()
Access the universe data base.
Private Member Functions
Universe (const Universe &)=delete
Universe (Universe &&)=delete
void operator= (const Universe &)=delete
void operator= (Universe &&)=delete
void bigBang ()
Creates the universe.
Static Private Attributes
static std::shared_ptr< Internal > m_internal = nullptr
Internal structure of the universe.
Detailed Description
Alien universe. Common structure to store shared objects between all elements of the library Alien.
Definition at line 52 of file Universe.h.
Constructor & Destructor Documentation
Universe()
Alien::Universe::Universe ()
Default constructor.
Definition at line 74 of file Universe.cc.
References bigBang().
Member Function Documentation
bigBang()
void Alien::Universe::bigBang () private
Creates the universe.
Definition at line 91 of file Universe.cc.
References m_internal.
Referenced by Universe().
dataBase()
UniverseDataBase & Alien::Universe::dataBase ()
Access the universe data base.
Returns
The universe data base
Definition at line 83 of file Universe.cc.
References m_internal.
reset()
void Alien::Universe::reset ()
Reset the universe.
Definition at line 135 of file Universe.cc.
References m_internal.
setTraceMng()
void Alien::Universe::setTraceMng (Arccore::ITraceMng * traceMng)
Set trace manager.
Parameters
[in] traceMng The trace manager
Definition at line 101 of file Universe.cc.
References m_internal, and traceMng().
setVerbosityLevel()
void Alien::Universe::setVerbosityLevel (Verbosity::Level level)
Set verbosity level.
Parameters
[in] level The verbosity level
Definition at line 118 of file Universe.cc.
References m_internal.
traceMng()
ITraceMng * Alien::Universe::traceMng () const
Get the trace manager.
Returns
The trace manager
Definition at line 110 of file Universe.cc.
References m_internal.
Referenced by setTraceMng().
verbosityLevel()
Verbosity::Level Alien::Universe::verbosityLevel () const
Get the verbosity level.
Returns
The verbosity level
Definition at line 127 of file Universe.cc.
References m_internal.
Member Data Documentation
m_internal
std::shared_ptr< Universe::Internal > Alien::Universe::m_internal = nullptr static private
Internal structure of the universe.
Definition at line 108 of file Universe.h.
Referenced by bigBang(), dataBase(), reset(), setTraceMng(), setVerbosityLevel(), traceMng(), and verbosityLevel().
The documentation for this class was generated from the following files:
Universe.h
Universe.cc