Arcane: Arcane::mesh::ItemGroupDynamicMeshObserver Class Reference
Arcane::mesh::ItemGroupDynamicMeshObserver Class Reference
Public Member Functions
ItemGroupDynamicMeshObserver (DynamicMesh *mesh)
void executeExtend (const Int32ConstArrayView *new_items_info)
Execute the action associated with the extension.
void executeReduce (const Int32ConstArrayView *info)
Execute the action associated with the extension.
void executeCompact (const Int32ConstArrayView *pinfo)
Executes the action associated with compaction.
void executeInvalidate ()
Execute the action associated with invalidation.
bool needInfo () const
Indicates whether the observer will need transition information.
Public Member Functions inherited from Arcane::IItemGroupObserver
virtual ~IItemGroupObserver ()=default
Destructor.
Private Attributes
DynamicMesh * m_mesh
Detailed Description
Definition at line 34 of file ItemGroupDynamicMeshObserver.h.
Constructor & Destructor Documentation
ItemGroupDynamicMeshObserver()
Arcane::mesh::ItemGroupDynamicMeshObserver::ItemGroupDynamicMeshObserver (DynamicMesh * mesh) inline
Definition at line 39 of file ItemGroupDynamicMeshObserver.h.
~ItemGroupDynamicMeshObserver()
virtual Arcane::mesh::ItemGroupDynamicMeshObserver::~ItemGroupDynamicMeshObserver () inline virtual
Definition at line 42 of file ItemGroupDynamicMeshObserver.h.
Member Function Documentation
executeCompact()
void Arcane::mesh::ItemGroupDynamicMeshObserver::executeCompact (const Int32ConstArrayView * info) virtual
Executes the action associated with compaction.
Parameters
info list of permutations in the old->new direction Assumes there is no change in size.
Implements Arcane::IItemGroupObserver.
Definition at line 87 of file ItemGroupDynamicMeshObserver.cc.
References ARCANE_CHECK_POINTER, Arcane::arcaneIsDebug(), Arcane::ITraceMng::debug(), Arcane::Trace::Highest, Arcane::mesh::ItemFamily::name(), Arcane::IItemFamily::parentFamily(), and Arcane::ConstArrayView< T >::size().
executeExtend()
void Arcane::mesh::ItemGroupDynamicMeshObserver::executeExtend (const Int32ConstArrayView * info) virtual
Execute the action associated with the extension.
Parameters
info list of added localIds Assumes there is no change in order or renumbering.
This method cannot be parallel.
Implements Arcane::IItemGroupObserver.
Definition at line 30 of file ItemGroupDynamicMeshObserver.cc.
References Arcane::IK_Cell, Arcane::IItemFamily::itemKind(), and Arcane::IItemFamily::view().
Referenced by Arcane::mesh::DynamicMesh::build().
executeInvalidate()
void Arcane::mesh::ItemGroupDynamicMeshObserver::executeInvalidate () virtual
Execute the action associated with invalidation.
No transition information available.
Implements Arcane::IItemGroupObserver.
Definition at line 108 of file ItemGroupDynamicMeshObserver.cc.
References ARCANE_FATAL.
executeReduce()
void Arcane::mesh::ItemGroupDynamicMeshObserver::executeReduce (const Int32ConstArrayView * info) virtual
Execute the action associated with the extension.
Parameters
info list of positions removed in the old group Assumes there is no change in order or renumbering This approach compared to the list of localIds is motivated by the constraint in PartialVariable which is unaware of the localIds it hosts.
info2 list of localIds of deleted elements. Potentially redundant with info, but inevitable for certain structures changing the order relative to the reference group (e.g.: ItemGroupDynamicMeshObserver) (DEPRECATED)
This method cannot be parallel.
Implements Arcane::IItemGroupObserver.
Definition at line 46 of file ItemGroupDynamicMeshObserver.cc.
References Arcane::Array< T >::add(), Arcane::ITraceMng::debug(), Arcane::Trace::High, Arcane::IItemFamily::itemsUniqueIdToLocalId(), Arcane::Array< T >::reserve(), Arcane::AbstractArray< T >::size(), Arcane::ConstArrayView< T >::size(), and Arcane::ItemGenericInfoListView::uniqueId().
needInfo()
bool Arcane::mesh::ItemGroupDynamicMeshObserver::needInfo () const inline virtual
Indicates whether the observer will need transition information.
This information must not change after the first call to this function
Implements Arcane::IItemGroupObserver.
Definition at line 52 of file ItemGroupDynamicMeshObserver.h.
Member Data Documentation
m_mesh
DynamicMesh* Arcane::mesh::ItemGroupDynamicMeshObserver::m_mesh private
Definition at line 56 of file ItemGroupDynamicMeshObserver.h.
The documentation for this class was generated from the following files:
ItemGroupDynamicMeshObserver.h
ItemGroupDynamicMeshObserver.cc