Alien: Alien::VectorDistribution Class Reference
Alien::VectorDistribution Class Reference
Computes a vector distribution.
#include <core/alien/distribution/VectorDistribution.h>
Classes
struct Internal
Internal implementation of the vector distribution.
Public Member Functions
VectorDistribution ()
Constructor.
VectorDistribution (const ISpace &space, Arccore::MessagePassing::IMessagePassingMng *parallel_mng)
Constructor.
VectorDistribution (const ISpace &space, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
VectorDistribution (Arccore::Integer global_size, Arccore::MessagePassing::IMessagePassingMng *parallel_mng)
Constructor.
VectorDistribution (Arccore::Integer global_size, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
VectorDistribution (const ISpace &space, Arccore::Integer local_size, Arccore::MessagePassing::IMessagePassingMng *parallel_mng)
Constructor.
VectorDistribution (const ISpace &space, Arccore::Integer local_size, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
VectorDistribution (Arccore::Integer global_size, Arccore::Integer local_size, Arccore::MessagePassing::IMessagePassingMng *parallel_mng)
Constructor.
VectorDistribution (Arccore::Integer global_size, Arccore::Integer local_size, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
VectorDistribution (const VectorDistribution &dist)
Copy constructor \parm[in] dist The distribution to copy.
VectorDistribution (VectorDistribution &&dist)
Rvalue constructor.
~VectorDistribution ()
Free resources.
VectorDistribution & operator= (const VectorDistribution &dist)
Equal operator.
VectorDistribution & operator= (VectorDistribution &&dist)
Equal operator.
bool operator== (const VectorDistribution &dist) const
Comparison operator.
bool isParallel () const
Whether or not the run is parallel.
std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > sharedParallelMng () const
Get the parallel manager.
Arccore::MessagePassing::IMessagePassingMng * parallelMng () const
Get the parallel manager.
const ISpace & space () const
Get the space.
Arccore::Integer localSize () const
Get the local size.
Arccore::Integer globalSize () const
Get the global size.
Arccore::Integer offset () const
Get the offset.
Arccore::Integer offset (Arccore::Integer p) const
Get the offset for a specific proc.
Arccore::ConstArrayView< Integer > offsets () const
Get all the offsets.
Arccore::Integer owner (Arccore::Integer i) const
Get the owner of an entry.
std::shared_ptr< VectorDistribution > clone () const
Clone the distribution.
Arccore::Integer globalToLocal (Arccore::Integer i) const
Get the local id of an elements with its global id.
Private Member Functions
Arccore::Integer globalToLocal (Arccore::Integer i, Arccore::Integer p) const
Get the local id of a non local element with its global id.
Arccore::Integer localToGlobal (Arccore::Integer i) const
Get the global id of an elements with its local id.
Arccore::Integer localToGlobal (Arccore::Integer i, Arccore::Integer p) const
Get the global id of a non local element with its local id.
Private Attributes
std::shared_ptr< Internal > m_internal
Internal implementation of the vector distribution.
Friends
class MatrixDistribution
Detailed Description
Computes a vector distribution.
Computes or use a pre-existing block row distribution for vectors
Definition at line 33 of file VectorDistribution.h.
Constructor & Destructor Documentation
VectorDistribution() [1/11]
Alien::VectorDistribution::VectorDistribution ()
Constructor.
Definition at line 382 of file VectorDistribution.cc.
References m_internal.
Referenced by operator=(), operator=(), operator==(), VectorDistribution(), VectorDistribution(), VectorDistribution(), and ~VectorDistribution().
VectorDistribution() [2/11]
Alien::VectorDistribution::VectorDistribution (const ISpace & space, Arccore::MessagePassing::IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] parallel_mng The parallel manager
References space().
VectorDistribution() [3/11]
Alien::VectorDistribution::VectorDistribution (const ISpace & space, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] parallel_mng The parallel manager
References space().
VectorDistribution() [4/11]
Alien::VectorDistribution::VectorDistribution (Arccore::Integer global_size, Arccore::MessagePassing::IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] parallel_mng The parallel manager
VectorDistribution() [5/11]
Alien::VectorDistribution::VectorDistribution (Arccore::Integer global_size, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] parallel_mng The parallel manager
VectorDistribution() [6/11]
Alien::VectorDistribution::VectorDistribution (const ISpace & space, Arccore::Integer local_size, Arccore::MessagePassing::IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
References space().
VectorDistribution() [7/11]
Alien::VectorDistribution::VectorDistribution (const ISpace & space, Arccore::Integer local_size, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
References space().
VectorDistribution() [8/11]
Alien::VectorDistribution::VectorDistribution (Arccore::Integer global_size, Arccore::Integer local_size, Arccore::MessagePassing::IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
VectorDistribution() [9/11]
Alien::VectorDistribution::VectorDistribution (Arccore::Integer global_size, Arccore::Integer local_size, std::shared_ptr< Arccore::MessagePassing::IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
References VectorDistribution().
VectorDistribution() [10/11]
Alien::VectorDistribution::VectorDistribution (const VectorDistribution & dist)
Copy constructor \parm[in] dist The distribution to copy.
Definition at line 476 of file VectorDistribution.cc.
References m_internal, and VectorDistribution().
VectorDistribution() [11/11]
Alien::VectorDistribution::VectorDistribution (VectorDistribution && dist)
Rvalue constructor.
Parameters
[in] dist The distribution to take
Definition at line 483 of file VectorDistribution.cc.
References m_internal, and VectorDistribution().
Member Function Documentation
clone()
std::shared_ptr< VectorDistribution > Alien::VectorDistribution::clone () const
Clone the distribution.
Returns
A clone of the distribution
Definition at line 613 of file VectorDistribution.cc.
Referenced by Alien::Move::VectorData::init(), Alien::VectorDistribution::Internal::Internal(), Alien::VectorDistribution::Internal::Internal(), Alien::VectorDistribution::Internal::Internal(), Alien::VectorDistribution::Internal::Internal(), and offset().
globalSize()
Integer Alien::VectorDistribution::globalSize () const
Get the global size.
Returns
The global size
Definition at line 577 of file VectorDistribution.cc.
References m_internal.
Referenced by Alien::computeBlockOffsets(), Alien::operator<<(), and ~VectorDistribution().
globalToLocal() [1/2]
Arccore::Integer Alien::VectorDistribution::globalToLocal (Arccore::Integer i) const
Get the local id of an elements with its global id.
Parameters
[in] i The global id of the element
Returns
The local id of the element
globalToLocal() [2/2]
Arccore::Integer Alien::VectorDistribution::globalToLocal (Arccore::Integer i, Arccore::Integer p) const private
Get the local id of a non local element with its global id.
Parameters
[in] i The global id of the non local element
[in] p The proc which owns the element
Returns
The local id of the element
isParallel()
bool Alien::VectorDistribution::isParallel () const
Whether or not the run is parallel.
Returns
Whether or not the run is parallel
Definition at line 532 of file VectorDistribution.cc.
References m_internal.
Referenced by Alien::operator<<(), and ~VectorDistribution().
localSize()
Integer Alien::VectorDistribution::localSize () const
Get the local size.
Returns
The local size
Definition at line 568 of file VectorDistribution.cc.
References m_internal.
Referenced by Alien::HCSRVector< ValueT >::init(), Alien::SimpleCSRVector< Arccore::Real >::init(), Alien::SYCLVector< ValueType >::init(), Alien::operator<<(), Alien::VBlockImpl::VBlockImpl(), Alien::VBlockSizes::VBlockSizes(), and ~VectorDistribution().
localToGlobal() [1/2]
Arccore::Integer Alien::VectorDistribution::localToGlobal (Arccore::Integer i) const private
Get the global id of an elements with its local id.
Parameters
[in] i The local id of the element
Returns
The global id of the element
localToGlobal() [2/2]
Arccore::Integer Alien::VectorDistribution::localToGlobal (Arccore::Integer i, Arccore::Integer p) const private
Get the global id of a non local element with its local id.
Parameters
[in] i The local id of the non local element
[in] p The proc which owns the element
Returns
The global id of the element
offset() [1/2]
Integer Alien::VectorDistribution::offset () const
Get the offset.
Returns
The offset
Definition at line 586 of file VectorDistribution.cc.
References m_internal.
Referenced by Alien::computeBlockOffsets(), Alien::DoKToSimpleCSRVectorConverter::convert(), Alien::SimpleCSRtoDoKVectorConverter::convert(), Alien::operator<<(), Alien::VBlockImpl::VBlockImpl(), Alien::VBlockSizes::VBlockSizes(), and ~VectorDistribution().
offset() [2/2]
Arccore::Integer Alien::VectorDistribution::offset (Arccore::Integer p) const
Get the offset for a specific proc.
Parameters
[in] p The requested proc
Returns
The offset for the specific proc
References clone(), offsets(), and owner().
offsets()
ConstArrayView< Integer > Alien::VectorDistribution::offsets () const
Get all the offsets.
Returns
Offsets array
Definition at line 604 of file VectorDistribution.cc.
References m_internal.
Referenced by offset().
operator=() [1/2]
VectorDistribution & Alien::VectorDistribution::operator= (const VectorDistribution & dist)
Equal operator.
Parameters
[in] dist The distribution to copy
Returns
The copied distribution
Definition at line 505 of file VectorDistribution.cc.
References m_internal, and VectorDistribution().
Referenced by ~VectorDistribution().
operator=() [2/2]
VectorDistribution & Alien::VectorDistribution::operator= (VectorDistribution && dist)
Equal operator.
Parameters
[in] dist The distribution to copy
Returns
The copied distribution
Definition at line 515 of file VectorDistribution.cc.
References m_internal, and VectorDistribution().
operator==()
bool Alien::VectorDistribution::operator== (const VectorDistribution & dist) const
Comparison operator.
Parameters
[in] dist The distribution to compare
Returns
Whether or not the distribution are identical
Definition at line 524 of file VectorDistribution.cc.
References m_internal, and VectorDistribution().
Referenced by ~VectorDistribution().
owner()
Integer Alien::VectorDistribution::owner (Arccore::Integer i) const
Get the owner of an entry.
Parameters
[in] i The global id of the element
Returns
The proc owner
Definition at line 541 of file VectorDistribution.cc.
References m_internal.
Referenced by offset().
parallelMng()
IMessagePassingMng * Alien::VectorDistribution::parallelMng () const
Get the parallel manager.
Returns
The parallel manager
Definition at line 559 of file VectorDistribution.cc.
References m_internal.
Referenced by Alien::computeBlockOffsets(), Alien::VBlockSizes::VBlockSizes(), and ~VectorDistribution().
sharedParallelMng()
std::shared_ptr< IMessagePassingMng > Alien::VectorDistribution::sharedParallelMng () const
Get the parallel manager.
Returns
The parallel manager
Definition at line 550 of file VectorDistribution.cc.
References m_internal.
Referenced by ~VectorDistribution().
space()
const ISpace & Alien::VectorDistribution::space () const
Get the space.
Returns
The vector space
Definition at line 496 of file VectorDistribution.cc.
References m_internal.
Referenced by Alien::MatrixDistribution::colSpace(), Alien::VectorDistribution::Internal::Internal(), Alien::VectorDistribution::Internal::Internal(), Alien::VectorDistribution::Internal::Internal(), Alien::VectorDistribution::Internal::Internal(), VectorDistribution(), VectorDistribution(), VectorDistribution(), VectorDistribution(), and ~VectorDistribution().
Friends And Related Symbol Documentation
MatrixDistribution
friend class MatrixDistribution friend
Definition at line 246 of file VectorDistribution.h.
Member Data Documentation
m_internal
std::shared_ptr<Internal> Alien::VectorDistribution::m_internal private
Internal implementation of the vector distribution.
Definition at line 251 of file VectorDistribution.h.
Referenced by globalSize(), isParallel(), localSize(), offset(), offsets(), operator=(), operator=(), operator==(), owner(), parallelMng(), sharedParallelMng(), space(), VectorDistribution(), VectorDistribution(), and VectorDistribution().
The documentation for this class was generated from the following files:
VectorDistribution.h
VectorDistribution.cc