Arcane: Arcane::IEntryPoint Class Reference
Arcane::IEntryPoint Class Reference abstract
Module
Interface of a module entry point.
#include <arcane/core/IEntryPoint.h>
Call point
Where the entry point is used.
enum { PNone = 0 , PAutoLoadBegin = 1 , PAutoLoadEnd = 2 }
Properties of an entry point.
static const char *const WComputeLoop = "ComputeLoop"
called during the calculation loop
static const char *const WBuild = "Build"
called for module construction
static const char *const WInit = "Init"
called during initialization
static const char *const WContinueInit = "ContinueInit"
called during continuation initialization
static const char *const WStartInit = "StartInit"
called during new case initialization
static const char *const WRestore = "Restore"
called to restore variables during a rollback
static const char *const WOnMeshChanged = "OnMeshChanged"
called after a mesh change
static const char *const WOnMeshRefinement = "OnMeshRefinement"
called after mesh refinement
static const char *const WExit = "Exit"
virtual ~IEntryPoint ()=default
Releases resources.
virtual String name () const =0
Returns the name of the entry point.
virtual String fullName () const =0
Full name (with the module) of the entry point. This name is unique.
virtual ISubDomain * subDomain () const =0
Returns the main manager.
virtual IModule * module () const =0
Returns the module associated with the entry point.
virtual void executeEntryPoint ()=0
Calls the entry point.
virtual Real totalCPUTime () const =0
Total CPU consumption spent in this entry point (in milliseconds).
virtual Real lastCPUTime () const =0
CPU consumption of the last iteration (in milliseconds).
virtual Real totalElapsedTime () const =0
Elapsed execution time (clock time) in this entry point (in milliseconds).
virtual Real lastElapsedTime () const =0
Elapsed execution time (clock time) of the last iteration (in milliseconds).
virtual Real totalTime (Timer::eTimerType) const =0
Returns totalElapsedTime().
virtual Real lastTime (Timer::eTimerType) const =0
Returns lastElapsedTime().
virtual Integer nbCall () const =0
Returns the number of times the entry point has been executed.
virtual String where () const =0
Returns where the entry point is called.
virtual int property () const =0
Returns the properties of the entry point.
Detailed Description
Interface of a module entry point.
Definition at line 34 of file IEntryPoint.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Properties of an entry point.
Enumerator
PNone
No properties.
PAutoLoadBegin
Automatically loaded at the beginning. This means that a module possessing an entry point with this property will always be loaded, and the entry point will be added to the list of entry points executing at the beginning of the time loop.
PAutoLoadEnd
Automatically loaded at the end. This means that a module possessing an entry point with this property will always be loaded, and the entry point will be added to the list of entry points executing at the end of the time loop.
Definition at line 65 of file IEntryPoint.h.
Member Function Documentation
executeEntryPoint()
virtual void Arcane::IEntryPoint::executeEntryPoint () pure virtual
Calls the entry point.
Implemented in Arcane::EntryPoint.
References executeEntryPoint().
Referenced by executeEntryPoint().
fullName()
virtual String Arcane::IEntryPoint::fullName () const pure virtual
Full name (with the module) of the entry point. This name is unique.
Implemented in Arcane::EntryPoint.
lastCPUTime()
virtual Real Arcane::IEntryPoint::lastCPUTime () const pure virtual
CPU consumption of the last iteration (in milliseconds).
Note
since version 3.6 of Arcane, this method returns the same value as lastElapsedTime().
Implemented in Arcane::EntryPoint.
References lastCPUTime().
Referenced by lastCPUTime().
lastElapsedTime()
virtual Real Arcane::IEntryPoint::lastElapsedTime () const pure virtual
Elapsed execution time (clock time) of the last iteration (in milliseconds).
Implemented in Arcane::EntryPoint.
References lastElapsedTime().
Referenced by lastElapsedTime().
lastTime()
virtual Real Arcane::IEntryPoint::lastTime (Timer::eTimerType) const pure virtual
Returns lastElapsedTime().
Deprecated
Use lastElapsedTime() instead
Implemented in Arcane::EntryPoint.
References lastTime().
Referenced by lastTime().
module()
virtual IModule * Arcane::IEntryPoint::module () const pure virtual
Returns the module associated with the entry point.
Implemented in Arcane::EntryPoint.
References module().
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::EntryPointMng::addEntryPoint(), Arcane::TimeLoopMng::doOneIteration(), and module().
name()
virtual String Arcane::IEntryPoint::name () const pure virtual
Returns the name of the entry point.
Implemented in Arcane::EntryPoint.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::EntryPointMng::addEntryPoint(), Arcane::TimeLoopMng::execOnMeshChangedEntryPoints(), and Arcane::TimeLoopMng::execOnMeshRefinementEntryPoints().
nbCall()
virtual Integer Arcane::IEntryPoint::nbCall () const pure virtual
Returns the number of times the entry point has been executed.
Implemented in Arcane::EntryPoint.
References nbCall().
Referenced by nbCall().
property()
virtual int Arcane::IEntryPoint::property () const pure virtual
Returns the properties of the entry point.
Implemented in Arcane::EntryPoint.
References property().
Referenced by property(), and Arcane::TimeLoopMng::setUsedTimeLoop().
subDomain()
virtual ISubDomain * Arcane::IEntryPoint::subDomain () const pure virtual
Returns the main manager.
Implemented in Arcane::EntryPoint.
References subDomain().
Referenced by subDomain().
totalCPUTime()
virtual Real Arcane::IEntryPoint::totalCPUTime () const pure virtual
Total CPU consumption spent in this entry point (in milliseconds).
Note
since version 3.6 of Arcane, this method returns the same value as totalElapsedTime().
Implemented in Arcane::EntryPoint.
References totalCPUTime().
Referenced by totalCPUTime().
totalElapsedTime()
virtual Real Arcane::IEntryPoint::totalElapsedTime () const pure virtual
Elapsed execution time (clock time) in this entry point (in milliseconds).
Implemented in Arcane::EntryPoint.
References totalElapsedTime().
Referenced by totalElapsedTime().
totalTime()
virtual Real Arcane::IEntryPoint::totalTime (Timer::eTimerType) const pure virtual
Returns totalElapsedTime().
Deprecated
Use totalElapsedTime() instead
Implemented in Arcane::EntryPoint.
References totalTime().
Referenced by totalTime().
where()
virtual String Arcane::IEntryPoint::where () const pure virtual
Returns where the entry point is called.
Implemented in Arcane::EntryPoint.
References where().
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::TimeLoopMng::_processEntryPoints(), Arcane::TimeLoopMng::execBuildEntryPoints(), Arcane::TimeLoopMng::execInitEntryPoints(), and where().
Member Data Documentation
WBuild
const char *const Arcane::IEntryPoint::WBuild = "Build" static
called for module construction
Definition at line 45 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), and Arcane::TimeLoopMng::execBuildEntryPoints().
WComputeLoop
const char *const Arcane::IEntryPoint::WComputeLoop = "ComputeLoop" static
called during the calculation loop
Definition at line 43 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::TimeLoopMng::_processEntryPoints(), Arcane::addEntryPoint(), Arcane::addEntryPoint(), Arcane::EntryPoint::executeEntryPoint(), and Arcane::ModuleMaster::ModuleMaster().
WContinueInit
const char *const Arcane::IEntryPoint::WContinueInit = "ContinueInit" static
called during continuation initialization
Definition at line 49 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::TimeLoopMng::_processEntryPoints(), Arcane::TimeLoopMng::execInitEntryPoints(), and Arcane::ModuleMaster::ModuleMaster().
WExit
const char *const Arcane::IEntryPoint::WExit = "Exit" static
Definition at line 59 of file IEntryPoint.h.
WInit
const char *const Arcane::IEntryPoint::WInit = "Init" static
called during initialization
Definition at line 47 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::TimeLoopMng::_processEntryPoints(), Arcane::TimeLoopMng::execInitEntryPoints(), and Arcane::ModuleMaster::ModuleMaster().
WOnMeshChanged
const char *const Arcane::IEntryPoint::WOnMeshChanged = "OnMeshChanged" static
called after a mesh change
Definition at line 55 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), and Arcane::ModuleMaster::ModuleMaster().
WOnMeshRefinement
const char *const Arcane::IEntryPoint::WOnMeshRefinement = "OnMeshRefinement" static
called after mesh refinement
called upon code termination.
Definition at line 57 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint().
WRestore
const char *const Arcane::IEntryPoint::WRestore = "Restore" static
called to restore variables during a rollback
Definition at line 53 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::TimeLoopMng::_processEntryPoints(), and Arcane::ModuleMaster::ModuleMaster().
WStartInit
const char *const Arcane::IEntryPoint::WStartInit = "StartInit" static
called during new case initialization
Definition at line 51 of file IEntryPoint.h.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::TimeLoopMng::_processEntryPoints(), Arcane::TimeLoopMng::execInitEntryPoints(), and Arcane::ModuleMaster::ModuleMaster().
The documentation for this class was generated from the following files:
IEntryPoint.h
EntryPoint.cc