Alien: Alien::IIndexManager Class Reference
Alien::IIndexManager Class Reference abstract
#include <core/alien/index_manager/IIndexManager.h>
Classes
class IAbstractFamily
Interface des familles abstraites pour l'indexation de items.
class EntryImpl
Interface d'implémentation de Entry.
class Entry
Classe de représentation des Entry.
class EntryEnumeratorImpl
Interface d'implementation de EntryEnumerator.
class EntryEnumerator
Classe d'énumération des Entry connues.
Public Types
typedef Entry ScalarIndexSet
typedef Arccore::UniqueArray< ScalarIndexSet > VectorIndexSet
Public Member Functions
IIndexManager ()=default
Constructeur par défaut.
virtual ~IIndexManager ()=default
Destructeur.
virtual bool isPrepared () const =0
Indique si la phase de préparation est achevée.
virtual void init ()=0
Initialisation les structures.
virtual void prepare ()=0
Préparation : fixe l'indexation (fin des définitions).
virtual void setTraceMng (Arccore::ITraceMng *traceMng)=0
Définit le gestionnaire de trace.
virtual void stats (Arccore::Integer &globalSize, Arccore::Integer &minLocalIndex, Arccore::Integer &localSize) const =0
Statistiques d'indexation.
virtual Arccore::Integer globalSize () const =0
Retourne la taille globale.
virtual Arccore::Integer minLocalIndex () const =0
Retourne l'indice minimum local.
virtual Arccore::Integer localSize () const =0
Retourne l'indice minimum local.
virtual EntryEnumerator enumerateEntry () const =0
Construction d'un enumerateur sur les Entry.
virtual Entry getEntry (const Arccore::String &name) const =0
Retourne l'entrée associée à un nom.
virtual ScalarIndexSet buildScalarIndexSet (const Arccore::String &name, Arccore::ConstArrayView< Arccore::Integer > localIds, const IAbstractFamily &family)=0
Construit une nouvelle entrée scalaire sur des items du maillage.
virtual ScalarIndexSet buildScalarIndexSet (const Arccore::String &name, const IAbstractFamily &family)=0
virtual VectorIndexSet buildVectorIndexSet (const Arccore::String &name, Arccore::ConstArrayView< Arccore::Integer > localIds, const IAbstractFamily &family, Arccore::Integer n)=0
Construit une nouvelle entrée vectorielle sur des items du maillage.
virtual VectorIndexSet buildVectorIndexSet (const Arccore::String &name, const IAbstractFamily &family, Arccore::Integer n)=0
virtual Arccore::UniqueArray< Arccore::Integer > getIndexes (const ScalarIndexSet &entry) const =0
Demande de dé-indexation d'une partie d'une entrée.
virtual Arccore::UniqueArray2< Arccore::Integer > getIndexes (const VectorIndexSet &entry) const =0
Fournit une table de translation indexé par les items.
virtual Alien::IMessagePassingMng * parallelMng () const =0
Donne le gestionnaire parallèle ayant servi à l'indexation.
virtual void setMaxNullIndexOpt (bool flag)=0
virtual Arccore::Integer nullIndex () const =0
return value of null index
virtual void keepAlive (const IAbstractFamily *family)=0
Permet de gérer la mort d'une famille associée à l'index-manager.
Detailed Description
Voir Description des services de solveurslinéaires pour plus de détails
Definition at line 28 of file IIndexManager.h.
Member Typedef Documentation
ScalarIndexSet
typedef Entry Alien::IIndexManager::ScalarIndexSet
Definition at line 302 of file IIndexManager.h.
VectorIndexSet
typedef Arccore::UniqueArray<ScalarIndexSet> Alien::IIndexManager::VectorIndexSet
Definition at line 303 of file IIndexManager.h.
Member Function Documentation
buildScalarIndexSet() [1/2]
virtual ScalarIndexSet Alien::IIndexManager::buildScalarIndexSet (const Arccore::String & name, Arccore::ConstArrayView< Arccore::Integer > localIds, const IAbstractFamily & family) pure virtual
Construit une nouvelle entrée scalaire sur des items du maillage.
Construit une nouvelle entrée scalaire sur un ensemble d'entités abstraites
buildScalarIndexSet() [2/2]
virtual ScalarIndexSet Alien::IIndexManager::buildScalarIndexSet (const Arccore::String & name, const IAbstractFamily & family) pure virtual
Construit une nouvelle entrée scalaire sur l'ensemble des entités d'une familles abstraite
Implemented in Alien::BasicIndexManager.
buildVectorIndexSet() [1/2]
virtual VectorIndexSet Alien::IIndexManager::buildVectorIndexSet (const Arccore::String & name, Arccore::ConstArrayView< Arccore::Integer > localIds, const IAbstractFamily & family, Arccore::Integer n) pure virtual
Construit une nouvelle entrée vectorielle sur des items du maillage.
L'implémentation actuelle considére le multi-scalaire comme du vectoriel Construit une nouvelle entrée vectoriellesur un ensemble d'entités abstraites
L'implémentation actuelle considére le multi-scalaire comme du vectoriel
buildVectorIndexSet() [2/2]
virtual VectorIndexSet Alien::IIndexManager::buildVectorIndexSet (const Arccore::String & name, const IAbstractFamily & family, Arccore::Integer n) pure virtual
Construit une nouvelle entrée scalaire sur l'ensemble des entités d'une familles abstraite
L'implémentation actuelle considére le multi-scalaire comme du vectoriel
Implemented in Alien::BasicIndexManager.
enumerateEntry()
virtual EntryEnumerator Alien::IIndexManager::enumerateEntry () const pure virtual
Construction d'un enumerateur sur les Entry.
Implemented in Alien::BasicIndexManager.
Referenced by Alien::IIndexManager::EntryEnumerator::EntryEnumerator().
getIndexes() [1/2]
virtual Arccore::UniqueArray< Arccore::Integer > Alien::IIndexManager::getIndexes (const ScalarIndexSet & entry) const pure virtual
Demande de dé-indexation d'une partie d'une entrée.
Utilisable uniquement avant prepare Consultation vectorielle d'indexation d'une entrée (après prepare) Fournit une table de translation indexé par les items
Implemented in Alien::BasicIndexManager.
getIndexes() [2/2]
virtual Arccore::UniqueArray2< Arccore::Integer > Alien::IIndexManager::getIndexes (const VectorIndexSet & entry) const pure virtual
Fournit une table de translation indexé par les items.
Implemented in Alien::BasicIndexManager.
globalSize()
virtual Arccore::Integer Alien::IIndexManager::globalSize () const pure virtual
Retourne la taille globale.
Uniquement valide après prepare
Implemented in Alien::BasicIndexManager.
Referenced by stats().
init()
virtual void Alien::IIndexManager::init () pure virtual
Initialisation les structures.
Implicitement appelé par le constructeur
Implemented in Alien::BasicIndexManager.
isPrepared()
virtual bool Alien::IIndexManager::isPrepared () const pure virtual
Indique si la phase de préparation est achevée.
Implemented in Alien::BasicIndexManager.
keepAlive()
virtual void Alien::IIndexManager::keepAlive (const IAbstractFamily * family) pure virtual
Permet de gérer la mort d'une famille associée à l'index-manager.
Méthode de bas niveau pour les implémentationsde IAbstractFamily, usuellement dans le desctructeur des implémentations extérieures de IAbstractFamily
Implemented in Alien::BasicIndexManager.
localSize()
virtual Arccore::Integer Alien::IIndexManager::localSize () const pure virtual
Retourne l'indice minimum local.
Uniquement valide après prepare
Implemented in Alien::BasicIndexManager.
Referenced by stats().
minLocalIndex()
virtual Arccore::Integer Alien::IIndexManager::minLocalIndex () const pure virtual
Retourne l'indice minimum local.
Uniquement valide après prepare
Implemented in Alien::BasicIndexManager.
Referenced by stats().
nullIndex()
virtual Arccore::Integer Alien::IIndexManager::nullIndex () const pure virtual
return value of null index
Implemented in Alien::BasicIndexManager.
parallelMng()
virtual Alien::IMessagePassingMng * Alien::IIndexManager::parallelMng () const pure virtual
Donne le gestionnaire parallèle ayant servi à l'indexation.
Implemented in Alien::BasicIndexManager.
prepare()
virtual void Alien::IIndexManager::prepare () pure virtual
Préparation : fixe l'indexation (fin des définitions).
Implemented in Alien::BasicIndexManager.
setMaxNullIndexOpt()
virtual void Alien::IIndexManager::setMaxNullIndexOpt (bool flag) pure virtual
define null index : default == -1, if true nullIndex() == max index of current indexation
Implemented in Alien::BasicIndexManager.
stats()
virtual void Alien::IIndexManager::stats (Arccore::Integer & globalSize, Arccore::Integer & minLocalIndex, Arccore::Integer & localSize) const pure virtual
Statistiques d'indexation.
Uniquement valide après prepare
Implemented in Alien::BasicIndexManager.
References globalSize(), localSize(), and minLocalIndex().
The documentation for this class was generated from the following file:
IIndexManager.h