Arcane: Arcane::IDataInternal Class Reference
Arcane::IDataInternal Class Reference abstract
Internal part of IData.
#include <arcane/core/internal/IDataInternal.h>
Public Member Functions
virtual bool compressAndClear (DataCompressionBuffer &buf)
Compresses the data and frees the associated memory.
virtual bool decompressAndFill (DataCompressionBuffer &buf)
Decompresses the data and fills the data values.
virtual INumericDataInternal * numericData ()
Generic interface for numeric data (nullptr if the data is not numeric).
virtual void computeHash (DataHashInfo &hash_info)=0
Calculates the hash of the data.
Detailed Description
Internal part of IData.
Definition at line 79 of file IDataInternal.h.
Member Function Documentation
compressAndClear()
virtual bool Arcane::IDataInternal::compressAndClear (DataCompressionBuffer & buf) inline virtual
Compresses the data and frees the associated memory.
Compresses the data and fills buf with the compressed information. Then it frees the associated memory. The instance will no longer be usable until decompressAndFill() has been called.
Return values
true if compression occurred.
false if the instance does not support compression. In this case it remains usable.
Warning
Calling this method modifies the underlying container. If this data is associated with a variable, IVariable::syncReferences() must be called.
Reimplemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
Definition at line 101 of file IDataInternal.h.
computeHash()
virtual void Arcane::IDataInternal::computeHash (DataHashInfo & hash_info) pure virtual
Calculates the hash of the data.
Outputs the version and value into hash_info.m_version and hash_info.m_value.
Implemented in Arcane::Array2DataT< DataType >::Impl, Arcane::ArrayDataT< DataType >::Impl, Arcane::NumArrayDataT< DataType, RankValue >::Internal, Arcane::ScalarDataT< DataType >::Internal, Arcane::StringArrayData::Impl, and Arcane::StringScalarData::Internal.
Referenced by Arcane::VariableIOReaderMng::_checkHashFunction().
decompressAndFill()
virtual bool Arcane::IDataInternal::decompressAndFill (DataCompressionBuffer & buf) inline virtual
Decompresses the data and fills the data values.
Decompresses the data from buf and fills the values of this instance with the decompressed information.
Return values
true if decompression occurred.
false if no decompression occurred because the instance does not support it.
Warning
Calling this method modifies the underlying container. If this data is associated with a variable, IVariable::syncReferences() must be called.
Reimplemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
Definition at line 119 of file IDataInternal.h.
numericData()
virtual INumericDataInternal * Arcane::IDataInternal::numericData () inline virtual
Generic interface for numeric data (nullptr if the data is not numeric).
Reimplemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
Definition at line 126 of file IDataInternal.h.
Referenced by Arcane::VariablePrivate::computeComparisonHashCollective(), Arcane::VariableUtils::prefetchVariableAsync(), Arcane::VariableUtilsInternal::setFromMemoryBuffer(), and Arcane::VariableSynchronizer::synchronizeData().
The documentation for this class was generated from the following file:
IDataInternal.h