Arcane: Arcane::IMeshInternal Class Reference
Arcane::IMeshInternal Class Reference abstract
Internal part of IMesh.
#include <arcane/core/internal/IMeshInternal.h>
Public Member Functions
virtual void setMeshKind (const MeshKind &v)=0
Sets the mesh type.
virtual IItemConnectivityMng * dofConnectivityMng () const noexcept=0
Returns the dof connectivity manager.
virtual IPolyhedralMeshModifier * polyhedralMeshModifier () const noexcept=0
virtual IItemFamilySerializerMngInternal * familySerializerMng () const noexcept
Returns the family serialization tools manager.
Detailed Description
Internal part of IMesh.
Definition at line 36 of file IMeshInternal.h.
Member Function Documentation
dofConnectivityMng()
virtual IItemConnectivityMng * Arcane::IMeshInternal::dofConnectivityMng () const pure virtual noexcept
Returns the dof connectivity manager.
This method is temporary because this dof connectivity manager is intended to be removed, as the evolution of dof connectivities is now managed automatically. For internal use only while awaiting removal.
Implemented in Arcane::mesh::DynamicMeshInternal.
familySerializerMng()
virtual IItemFamilySerializerMngInternal * Arcane::IMeshInternal::familySerializerMng () const inline virtual noexcept
Returns the family serialization tools manager.
This manager is used for the polyhedral mesh, in order to trigger a finalization phase of item addition after calling the deserialization methods, because these methods are asynchronous and the finalization phase must be triggered.
Returns
This method returns nullptr if the manager does not exist.
Definition at line 77 of file IMeshInternal.h.
References familySerializerMng().
Referenced by familySerializerMng().
polyhedralMeshModifier()
virtual IPolyhedralMeshModifier * Arcane::IMeshInternal::polyhedralMeshModifier () const pure virtual noexcept
\bief Returns the polyhedral mesh modification interface
This method returns nullptr if the mesh implementation is not PolyhedralMesh
Implemented in Arcane::mesh::DynamicMeshInternal.
References polyhedralMeshModifier().
Referenced by polyhedralMeshModifier().
setMeshKind()
virtual void Arcane::IMeshInternal::setMeshKind (const MeshKind & v) pure virtual
Sets the mesh type.
For now, this method should only be used to specify the mesh structure (eMeshStructure).
Implemented in Arcane::mesh::DynamicMeshInternal.
The documentation for this class was generated from the following file:
IMeshInternal.h