Arcane: Arcane::DumpWEnsight7 Class Reference
Arcane::DumpWEnsight7 Class Reference
Writes in Ensight7 format.
Classes
struct EnsightPart
Correspondence between Ensight element type and Arcane.
struct GroupPartInfo
Information to share a group into elements of the same subtype.
class WriteBase
Functor for writing a variable.
class WriteDouble
Functor for writing a variable of type Real.
class WriteArrayDouble
Functor for writing a variable of type Real.
class WriteReal3
Functor to write a variable of type Real2.
class WriteArrayReal3
Functor to write a variable of type Real3.
Public Member Functions
void writeFileString (std::ostream &o, const String &str)
void writeFileInt (std::ostream &o, int value)
void writeFileDouble (std::ostream &o, double value)
Integer writeDoubleSize () const
Integer writeIntSize () const
void writeFileArray (std::ostream &o, IntegerConstArrayView value)
bool isBinary () const
DumpWEnsight7 (IMesh *m, const String &filename, RealConstArrayView times, VariableCollection variables, ItemGroupCollection groups, bool is_binary, bool is_parallel, Integer fileset_size, bool use_degenerated_hexa, bool force_first_geometry, bool save_uids)
void writeVal (IVariable &, ConstArrayView< Byte >) override
Writing for variable v of array a.
void writeVal (IVariable &v, ConstArrayView< Real > a) override
void writeVal (IVariable &, ConstArrayView< Real2 >) override
void writeVal (IVariable &, ConstArrayView< Real3 >) override
Saving vector variables.
void writeVal (IVariable &v, ConstArrayView< Int16 > a) override
void writeVal (IVariable &v, ConstArrayView< Int32 > a) override
void writeVal (IVariable &v, ConstArrayView< Int64 > a) override
void writeVal (IVariable &, ConstArrayView< Real2x2 >) override
void writeVal (IVariable &, ConstArrayView< Real3x3 >) override
void writeVal (IVariable &, ConstArrayView< String >) override
void writeVal (IVariable &, ConstArray2View< Byte >) override
void writeVal (IVariable &v, ConstArray2View< Real > a) override
void writeVal (IVariable &, ConstArray2View< Real2 >) override
void writeVal (IVariable &, ConstArray2View< Real3 >) override
Saving vector array variables.
void writeVal (IVariable &v, ConstArray2View< Int16 > a) override
void writeVal (IVariable &v, ConstArray2View< Int32 > a) override
void writeVal (IVariable &v, ConstArray2View< Int64 > a) override
void writeVal (IVariable &, ConstArray2View< Real2x2 >) override
void writeVal (IVariable &, ConstArray2View< Real3x3 >) override
void writeVal (IVariable &, ConstMultiArray2View< Byte >) override
void writeVal (IVariable &v, ConstMultiArray2View< Real > a) override
void writeVal (IVariable &, ConstMultiArray2View< Real2 >) override
void writeVal (IVariable &, ConstMultiArray2View< Real3 > a) override
Saving vector array variables.
void writeVal (IVariable &v, ConstMultiArray2View< Int16 > a) override
void writeVal (IVariable &v, ConstMultiArray2View< Int32 > a) override
void writeVal (IVariable &v, ConstMultiArray2View< Int64 > a) override
void writeVal (IVariable &, ConstMultiArray2View< Real2x2 >) override
void writeVal (IVariable &, ConstMultiArray2View< Real3x3 >) override
void beginWrite () override
Notifies the start of writing.
void endWrite () override
Notifies the end of writing.
void setMetaData (const String &) override
Sets metadata information.
bool isParallelOutput () const
bool isMasterProcessor () const
bool isOneFilePerTime () const
Int32 rank () const
IParallelMng * parallelMng () const
Public Member Functions inherited from Arcane::DumpW
DumpW ()
Constructor.
virtual ~DumpW ()
Frees resources.
void beginWrite (const VariableCollection &vars)
Notifies the start of writing.
void write (IVariable *var, IData *data)
Writes the data data of the variable var.
Public Member Functions inherited from Arcane::IDataWriter
virtual ~IDataWriter ()=default
Frees resources.
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Static Public Attributes
static const int int_width = 10
static const int g_line_length = 80
Private Types
typedef UniqueArray< GroupPartInfo * > GroupPartInfoList
Private Member Functions
bool _isValidVariable (IVariable &) const
Checks the validity of the variable to be saved.
void _createCaseFile ()
void _buildFileName (const String &varname, String &filename)
Constructs the filename for a variable or mesh name.
void _buildPartDirectory ()
Constructs the directory where the variables will be saved.
void _writeWildcardFilename (std::ostream &ofile, const String &filename, char joker=' *')
int _fileOuttype () const
void _writeFileHeader (std::ostream &o, bool write_c_binary)
bool _isNewBlocFile () const
void _computeGroupParts (ItemGroupList list_group, Integer &partid)
void _saveGroup (std::ostream &ofile, const GroupPartInfo &ensight_grp, ConstArrayView< Integer > nodes_index, WriteBase &wf)
void _saveVariableOnGroup (std::ostream &ofile, const GroupPartInfo &ensight_grp, WriteBase &from_func)
bool _isSameKindOfGroup (const ItemGroup &group, eItemKind item_kind)
template<typename T>
void _writeRealValT (IVariable &v, ConstArrayView< T > a)
Template for writing variable as a real variable.
template<typename T>
void _writeRealValT (IVariable &v, ConstArray2View< T > a)
Template for writing array variable as an array real variable.
template<typename T>
void _writeRealValT (IVariable &v, ConstMultiArray2View< T > a)
Template for writing array variable as an array real variable.
Private Attributes
IMesh * m_mesh
Mesh.
IParallelMng * m_parallel_mng
Parallelism manager.
Directory m_base_directory
Storage directory name.
Directory m_part_directory
Storage directory for the current iteration.
std::ofstream m_case_file
File describing the case.
std::ostringstream m_case_file_variables
RealUniqueArray m_times
description of saved variables
VariableList m_save_variables
List of variables to export.
ItemGroupList m_save_groups
List of groups to export.
GroupPartInfoList m_parts
bool m_is_binary
List of parts.
bool m_is_master
true if the processor manages the output
bool m_is_parallel_output
bool m_use_degenerated_hexa
bool m_force_first_geometry
bool m_save_uids
Integer m_total_nb_element
Total number of mesh elements across all groups to be saved.
Integer m_total_nb_group
Number of groups to save (== number of parts).
Integer m_fileset_size
Static Private Attributes
static const Integer m_max_prots_digit = 6
Maximum number of digits to indicate the protection number.
Related Symbols
(Note that these are not member symbols.)
void _computeGroupParts (ItemGroupList list_group, Integer &partid)
Retrieves a group of a given type and its information.
void _saveGroup (std::ostream &ofile, const GroupPartInfo &ensight_grp, ConstArrayView< Integer > nodes_index, WriteBase &wf)
Saves the connectivity of elements in a group.
void _saveVariableOnGroup (std::ostream &ofile, const GroupPartInfo &ensight_grp, WriteBase &from_func)
Applies a functor to the elements of a group.
Additional Inherited Members
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Detailed Description
Writes in Ensight7 format.
The writing is done in Ensight case format and in ASCII.
There are two saving mechanisms depending on whether the temporal aspect is used or not. The choice is made using the array m_times. If it is empty, a snapshot is taken, meaning just an output of the variables. If it is not empty, a temporal output is performed, which contains a list of time instants, and in this case, a time save is performed. The variables are then saved at their current value, considering it to be the last protection of the array m_times. To have larger files, #m_fileset_size protections are saved per file.
In both cases, m_base_directory contains the path and directory where the variables will be saved.
The case format uses one file to describe the case (.case), one file to describe the geometry (.geo), and one file per variable. In the case of a temporal save, there is one geometry and one variable file per time instant. In this case, the file names are suffixed by the protection number. For example, for a variable 'Pressure', the save file name in the case of a snapshot is just 'Pressure'. In the case of a temporal save at the 4th protection, the name will be 'Pressure000004'.
For more precision in the Ensight case format, refer to the user manual for Ensight6 or Ensight7.
Definition at line 96 of file DumpWEnsight7.cc.
Member Typedef Documentation
GroupPartInfoList
typedef UniqueArray<GroupPartInfo*> Arcane::DumpWEnsight7::GroupPartInfoList private
Definition at line 728 of file DumpWEnsight7.cc.
Constructor & Destructor Documentation
DumpWEnsight7()
Arcane::DumpWEnsight7::DumpWEnsight7 (IMesh * m, const String & filename, RealConstArrayView times, VariableCollection variables, ItemGroupCollection groups, bool is_binary, bool is_parallel, Integer fileset_size, bool use_degenerated_hexa, bool force_first_geometry, bool save_uids)
Definition at line 826 of file DumpWEnsight7.cc.
~DumpWEnsight7()
Arcane::DumpWEnsight7::~DumpWEnsight7 ()
Definition at line 863 of file DumpWEnsight7.cc.
Member Function Documentation
_buildFileName()
void Arcane::DumpWEnsight7::_buildFileName (const String & name, String & filename) private
Constructs the filename for a variable or mesh name.
Constructs the filename in which a variable or mesh named name will be saved. The filename is returned in filename.
The protection number is inserted at the end of the file in the form of a number formatted with m_max_prots_digit characters. For example, for 'Pressure' at iteration 4 with #m_max_prot_digit equal to 6, we will get the filename 'Pressure000004'.
Todo
change the filename determination and use Directory.
Definition at line 1771 of file DumpWEnsight7.cc.
References Arcane::Directory::createDirectory(), m_base_directory, m_is_master, m_max_prots_digit, m_part_directory, m_times, and Arcane::StringBuilder::toString().
Referenced by _writeRealValT(), _writeRealValT(), beginWrite(), writeVal(), and writeVal().
_buildPartDirectory()
void Arcane::DumpWEnsight7::_buildPartDirectory () private
Constructs the directory where the variables will be saved.
If you want the outputs in multiple files, the directory of the current block is named 'bloc******'. For example, for the 4th block, it is 'bloc000004'.
the block number is inserted in the form of a number formatted with m_max_prots_digit characters.
Definition at line 1831 of file DumpWEnsight7.cc.
References m_base_directory, m_is_master, m_max_prots_digit, m_part_directory, and m_times.
Referenced by beginWrite().
_fileOuttype()
int Arcane::DumpWEnsight7::_fileOuttype () const private
Definition at line 1911 of file DumpWEnsight7.cc.
_isNewBlocFile()
bool Arcane::DumpWEnsight7::_isNewBlocFile () const private
Definition at line 1891 of file DumpWEnsight7.cc.
_isSameKindOfGroup()
bool Arcane::DumpWEnsight7::_isSameKindOfGroup (const ItemGroup & group, eItemKind item_kind) private
Definition at line 1810 of file DumpWEnsight7.cc.
_isValidVariable()
bool Arcane::DumpWEnsight7::_isValidVariable (IVariable & v) const private
Checks the validity of the variable to be saved.
Only variables at nodes, faces, or cells are processed.
Only variables in the #m_save_variable_list are saved. If this list is empty, all are saved.
Return values
true if the variable is valid
false otherwise
Definition at line 1740 of file DumpWEnsight7.cc.
References Arcane::IK_Cell, Arcane::IK_Face, Arcane::IK_Node, Arcane::IVariable::isUsed(), Arcane::IVariable::itemKind(), and m_save_variables.
Referenced by _writeRealValT(), _writeRealValT(), _writeRealValT(), writeVal(), writeVal(), and writeVal().
_writeFileHeader()
void Arcane::DumpWEnsight7::_writeFileHeader (std::ostream & o, bool write_c_binary) private
Definition at line 1336 of file DumpWEnsight7.cc.
_writeRealValT() [1/3]
template<typename T> void Arcane::DumpWEnsight7::_writeRealValT (IVariable & v, ConstArray2View< T > a) private
Template for writing array variable as an array real variable.
Saving constant dimension array variables (by row) of scalars.
Definition at line 2020 of file DumpWEnsight7.cc.
References _buildFileName(), _isValidVariable(), Arcane::TraceAccessor::debug(), Arcane::IK_Cell, Arcane::IK_Edge, Arcane::IK_Face, Arcane::IK_Node, Arcane::IVariable::isPartial(), Arcane::IVariable::itemGroup(), Arcane::IVariable::itemKind(), Arcane::ItemGroup::localIdToIndex(), m_is_master, and Arcane::IVariable::name().
_writeRealValT() [2/3]
template<typename T> void Arcane::DumpWEnsight7::_writeRealValT (IVariable & v, ConstArrayView< T > a) private
Template for writing variable as a real variable.
Saves scalar variables.
Definition at line 1924 of file DumpWEnsight7.cc.
References _buildFileName(), _isValidVariable(), Arcane::ConstArrayView< T >::data(), Arcane::TraceAccessor::debug(), Arcane::IK_Cell, Arcane::IK_Edge, Arcane::IK_Face, Arcane::IK_Node, Arcane::IVariable::isPartial(), Arcane::IVariable::itemGroup(), Arcane::IVariable::itemKind(), Arcane::ItemGroup::localIdToIndex(), m_is_master, Arcane::IVariable::name(), and Arcane::ConstArrayView< T >::size().
Referenced by endWrite().
_writeRealValT() [3/3]
template<typename T> void Arcane::DumpWEnsight7::_writeRealValT (IVariable & v, ConstMultiArray2View< T > a) private
Template for writing array variable as an array real variable.
Saving non-constant dimension array variables (by row) of scalars.
Definition at line 2117 of file DumpWEnsight7.cc.
References _isValidVariable(), Arcane::IVariable::name(), and Arcane::TraceAccessor::warning().
_writeWildcardFilename()
void Arcane::DumpWEnsight7::_writeWildcardFilename (std::ostream & ofile, const String & filename, char joker = '*') private
Definition at line 1865 of file DumpWEnsight7.cc.
beginWrite()
void Arcane::DumpWEnsight7::beginWrite () override virtual
Notifies the start of writing.
Implements Arcane::DumpW.
Definition at line 1483 of file DumpWEnsight7.cc.
References _buildFileName(), _buildPartDirectory(), Arcane::List< T >::clone(), Arcane::IParallelMng::commRank(), Arcane::CollectionBase::count(), Arcane::TraceAccessor::debug(), ENUMERATE_ITEM, ENUMERATE_NODE, Arcane::Array< T >::fill(), Arcane::IK_Node, Arcane::IParallelMng::isParallel(), Arcane::IVariable::isPartial(), Arcane::IVariable::itemGroup(), Arcane::Item::localId(), m_base_directory, m_is_master, m_is_parallel_output, m_mesh, m_parallel_mng, m_save_groups, m_save_variables, m_times, m_total_nb_element, m_total_nb_group, Arcane::Array< T >::resize(), Arcane::ItemGroup::size(), Arcane::Item::uniqueId(), and Arcane::Array< T >::view().
endWrite()
void Arcane::DumpWEnsight7::endWrite () override virtual
Notifies the end of writing.
Implements Arcane::DumpW.
Definition at line 1626 of file DumpWEnsight7.cc.
References _writeRealValT(), Arcane::IVariable::data(), Arcane::TraceAccessor::debug(), ENUMERATE_CELL, ENUMERATE_NODE, Arcane::String::localstr(), m_base_directory, m_case_file, m_is_master, m_mesh, m_save_variables, m_times, Arcane::IVariable::notifyBeginWrite(), Arcane::IVariable::PPrivate, Arcane::IVariable::PTemporary, Arcane::IVariable::setUsed(), Arcane::VariableRef::variable(), Arcane::TraceAccessor::warning(), and Arcane::DumpW::write().
isBinary()
bool Arcane::DumpWEnsight7::isBinary () const inline
Definition at line 351 of file DumpWEnsight7.cc.
isMasterProcessor()
bool Arcane::DumpWEnsight7::isMasterProcessor () const inline
Definition at line 720 of file DumpWEnsight7.cc.
isOneFilePerTime()
bool Arcane::DumpWEnsight7::isOneFilePerTime () const inline
Definition at line 721 of file DumpWEnsight7.cc.
isParallelOutput()
bool Arcane::DumpWEnsight7::isParallelOutput () const inline
Definition at line 719 of file DumpWEnsight7.cc.
parallelMng()
IParallelMng * Arcane::DumpWEnsight7::parallelMng () const inline
Definition at line 723 of file DumpWEnsight7.cc.
rank()
Int32 Arcane::DumpWEnsight7::rank () const inline
Definition at line 722 of file DumpWEnsight7.cc.
setMetaData()
void Arcane::DumpWEnsight7::setMetaData (const String & meta_data) inline override virtual
Sets metadata information.
Implements Arcane::DumpW.
Definition at line 717 of file DumpWEnsight7.cc.
writeDoubleSize()
Integer Arcane::DumpWEnsight7::writeDoubleSize () const
Definition at line 1289 of file DumpWEnsight7.cc.
writeFileArray()
void Arcane::DumpWEnsight7::writeFileArray (std::ostream & o, IntegerConstArrayView value)
Definition at line 1299 of file DumpWEnsight7.cc.
writeFileDouble()
void Arcane::DumpWEnsight7::writeFileDouble (std::ostream & o, double value)
Definition at line 1270 of file DumpWEnsight7.cc.
writeFileInt()
void Arcane::DumpWEnsight7::writeFileInt (std::ostream & o, int value)
Definition at line 1243 of file DumpWEnsight7.cc.
writeFileString()
void Arcane::DumpWEnsight7::writeFileString (std::ostream & o, const String & str)
Definition at line 1317 of file DumpWEnsight7.cc.
writeIntSize()
Integer Arcane::DumpWEnsight7::writeIntSize () const
Definition at line 1259 of file DumpWEnsight7.cc.
writeVal() [1/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArray2View< Byte >) inline override virtual
Implements Arcane::DumpW.
Definition at line 695 of file DumpWEnsight7.cc.
writeVal() [2/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArray2View< Real2 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 697 of file DumpWEnsight7.cc.
writeVal() [3/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArray2View< Real2x2 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 702 of file DumpWEnsight7.cc.
writeVal() [4/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArray2View< Real3 > ptr) override virtual
Saving vector array variables.
Implements Arcane::DumpW.
Definition at line 2223 of file DumpWEnsight7.cc.
References _buildFileName(), _isValidVariable(), Arcane::TraceAccessor::debug(), Arcane::IK_Cell, Arcane::IK_Edge, Arcane::IK_Face, Arcane::IK_Node, Arcane::IVariable::isPartial(), Arcane::IVariable::itemGroup(), Arcane::IVariable::itemKind(), Arcane::ItemGroup::localIdToIndex(), m_is_master, and Arcane::IVariable::name().
writeVal() [5/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArray2View< Real3x3 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 703 of file DumpWEnsight7.cc.
writeVal() [6/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArrayView< Byte > a) inline override virtual
Writing for variable v of array a.
Implements Arcane::DumpW.
Definition at line 684 of file DumpWEnsight7.cc.
writeVal() [7/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArrayView< Real2 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 686 of file DumpWEnsight7.cc.
writeVal() [8/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArrayView< Real2x2 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 691 of file DumpWEnsight7.cc.
writeVal() [9/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArrayView< Real3 > ptr) override virtual
Saving vector variables.
Implements Arcane::DumpW.
Definition at line 2135 of file DumpWEnsight7.cc.
References _buildFileName(), _isValidVariable(), Arcane::TraceAccessor::debug(), Arcane::IK_Cell, Arcane::IK_Edge, Arcane::IK_Face, Arcane::IK_Node, Arcane::IVariable::isPartial(), Arcane::IVariable::itemGroup(), Arcane::IVariable::itemKind(), Arcane::ItemGroup::localIdToIndex(), m_is_master, Arcane::IVariable::name(), and Arcane::ConstArrayView< T >::size().
writeVal() [10/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArrayView< Real3x3 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 692 of file DumpWEnsight7.cc.
writeVal() [11/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstArrayView< String >) inline override virtual
Implements Arcane::DumpW.
Definition at line 693 of file DumpWEnsight7.cc.
writeVal() [12/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstMultiArray2View< Byte >) inline override virtual
Implements Arcane::DumpW.
Definition at line 705 of file DumpWEnsight7.cc.
writeVal() [13/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstMultiArray2View< Real2 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 707 of file DumpWEnsight7.cc.
writeVal() [14/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstMultiArray2View< Real2x2 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 712 of file DumpWEnsight7.cc.
writeVal() [15/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstMultiArray2View< Real3 > a) override virtual
Saving vector array variables.
Implements Arcane::DumpW.
Definition at line 2317 of file DumpWEnsight7.cc.
References _isValidVariable(), Arcane::IVariable::name(), and Arcane::TraceAccessor::warning().
writeVal() [16/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & , ConstMultiArray2View< Real3x3 >) inline override virtual
Implements Arcane::DumpW.
Definition at line 713 of file DumpWEnsight7.cc.
writeVal() [17/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArray2View< Int16 > a) inline override virtual
Reimplemented from Arcane::DumpW.
Definition at line 699 of file DumpWEnsight7.cc.
writeVal() [18/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArray2View< Int32 > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 700 of file DumpWEnsight7.cc.
writeVal() [19/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArray2View< Int64 > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 701 of file DumpWEnsight7.cc.
writeVal() [20/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArray2View< Real > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 696 of file DumpWEnsight7.cc.
writeVal() [21/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArrayView< Int16 > a) inline override virtual
Reimplemented from Arcane::DumpW.
Definition at line 688 of file DumpWEnsight7.cc.
writeVal() [22/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArrayView< Int32 > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 689 of file DumpWEnsight7.cc.
writeVal() [23/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArrayView< Int64 > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 690 of file DumpWEnsight7.cc.
writeVal() [24/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstArrayView< Real > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 685 of file DumpWEnsight7.cc.
writeVal() [25/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstMultiArray2View< Int16 > a) inline override virtual
Reimplemented from Arcane::DumpW.
Definition at line 709 of file DumpWEnsight7.cc.
writeVal() [26/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstMultiArray2View< Int32 > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 710 of file DumpWEnsight7.cc.
writeVal() [27/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstMultiArray2View< Int64 > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 711 of file DumpWEnsight7.cc.
writeVal() [28/28]
void Arcane::DumpWEnsight7::writeVal (IVariable & v, ConstMultiArray2View< Real > a) inline override virtual
Implements Arcane::DumpW.
Definition at line 706 of file DumpWEnsight7.cc.
Friends And Related Symbol Documentation
_computeGroupParts()
void _computeGroupParts (ItemGroupList list_group, Integer & partid) related
Retrieves a group of a given type and its information.
The template parameter is either a DumpWEnsight7::CellGroup, or a DumpWEnsight7::FaceGroup.
First, iterate through the list of groups (list_group) and retrieve those of type T::GroupType. Add these groups to the list grp_list and assign them a number partid. Note that partid is passed by reference and is incremented in this function. This identifier corresponds to the part number (part) in ensight.
Next, determine for each of its groups the number of elements of each Ensight subtype. For example, for a cell group, determine the number of hexa8, the number of pyramid5, ...
Definition at line 893 of file DumpWEnsight7.cc.
References Arcane::TraceAccessor::debug(), ENUMERATE_ITEM, Arcane::ItemTypeMng::hasGeneralCells(), Arcane::Trace::High, Arcane::IK_Cell, Arcane::IK_Face, Arcane::ItemGroup::isOwn(), Arcane::ItemGroup::itemKind(), Arcane::IMesh::itemTypeMng(), Arcane::ItemGroup::mesh(), Arcane::ItemGroup::name(), Arcane::ItemTypeMng::nbBasicItemType(), Arcane::ItemTypeMng::nbBuiltInItemType(), Arcane::DumpWEnsight7::GroupPartInfo::nbType(), Arcane::ItemGroup::null(), Arcane::ItemGroup::own(), Arcane::Array< T >::resize(), Arcane::Item::toItemWithNodes(), and Arcane::Item::type().
_saveGroup()
void _saveGroup (std::ostream & ofile, const GroupPartInfo & ensight_grp, ConstArrayView< Integer > nodes_index, WriteBase & wf) related
Saves the connectivity of elements in a group.
Saves the connectivity of the elements in group ensight_grp. The difficulty comes from the fact that Ensight requires that elements be saved according to their type, that is, hexa on one side, tetra on the other, and so on. ensight_grp.m_nb_sub_part[] contains the number of elements for each ensight type. Therefore, we iterate through the list of elements of the group autant de fois qu'il y a de possible Ensight types (4 for cells, 2 for faces), and in each pass, we only save elements that are of the correct type. It is a bit tedious, but it avoids having to manage a list for each subtype.
Parameters
ofile output stream
nodes_index index of each node in the Ensight coordinate array.
ensight_grp group to save
wf writer
Definition at line 997 of file DumpWEnsight7.cc.
References Arcane::ConstArrayView< T >::data(), Arcane::Cell::face(), Arcane::Cell::faces(), Arcane::ItemTypeInfo::localFace(), Arcane::Item::localId(), Arcane::String::localstr(), m_mesh, Arcane::ItemGroup::name(), Arcane::Cell::nbFace(), Arcane::ItemTypeInfo::nbLocalFace(), Arcane::ItemTypeInfo::LocalFace::nbNode(), Arcane::ItemWithNodes::nbNode(), Arcane::DumpWEnsight7::GroupPartInfo::nbType(), Arcane::ItemTypeInfo::LocalFace::node(), Arcane::ItemWithNodes::node(), Arcane::Array< T >::resize(), Arcane::ConstArrayView< T >::size(), Arcane::Item::toCell(), Arcane::Item::toItemWithNodes(), Arcane::Item::typeInfo(), and Arcane::Item::uniqueId().
_saveVariableOnGroup()
void _saveVariableOnGroup (std::ostream & ofile, const GroupPartInfo & ensight_grp, WriteBase & from_func) related
Applies a functor to the elements of a group.
Applies the functor from_func to the group ensight_grp.
The functor must derive from WriteBase and is used to save a variable of a given type. In Ensight, variables are saved for each part and each element type (hexa8, ...). The operation is similar to saving the geometry (see the function _ensightSaveGroup()). Therefore, the same procedure must be followed: iterate over the group as many times as there are element types, and in one iteration, only save the variables for a given element type.
Warning
This function will not support the processing of variables defined on a group other than the set of elements.
See also
WriteFunctor
Parameters
ofile output stream
ensight_grp group
from_func functor
Definition at line 1196 of file DumpWEnsight7.cc.
References Arcane::PtrT< T >::get(), Arcane::DumpWEnsight7::GroupPartInfo::nbType(), and Arcane::ConstArrayView< T >::size().
Member Data Documentation
g_line_length
const int Arcane::DumpWEnsight7::g_line_length = 80 static
Definition at line 103 of file DumpWEnsight7.cc.
int_width
const int Arcane::DumpWEnsight7::int_width = 10 static
Definition at line 102 of file DumpWEnsight7.cc.
m_base_directory
Directory Arcane::DumpWEnsight7::m_base_directory private
Storage directory name.
Definition at line 734 of file DumpWEnsight7.cc.
Referenced by _buildFileName(), _buildPartDirectory(), beginWrite(), and endWrite().
m_case_file
std::ofstream Arcane::DumpWEnsight7::m_case_file private
File describing the case.
Definition at line 736 of file DumpWEnsight7.cc.
Referenced by endWrite().
m_case_file_variables
std::ostringstream Arcane::DumpWEnsight7::m_case_file_variables private
Definition at line 737 of file DumpWEnsight7.cc.
m_fileset_size
Integer Arcane::DumpWEnsight7::m_fileset_size private
Definition at line 756 of file DumpWEnsight7.cc.
m_force_first_geometry
bool Arcane::DumpWEnsight7::m_force_first_geometry private
Definition at line 748 of file DumpWEnsight7.cc.
m_is_binary
bool Arcane::DumpWEnsight7::m_is_binary private
List of parts.
true if file is in binary format
Definition at line 742 of file DumpWEnsight7.cc.
m_is_master
bool Arcane::DumpWEnsight7::m_is_master private
true if the processor manages the output
Definition at line 743 of file DumpWEnsight7.cc.
Referenced by _buildFileName(), _buildPartDirectory(), _writeRealValT(), _writeRealValT(), beginWrite(), endWrite(), writeVal(), and writeVal().
m_is_parallel_output
bool Arcane::DumpWEnsight7::m_is_parallel_output private
true if outputs are parallel with a proc collecting the outputs from others
Definition at line 746 of file DumpWEnsight7.cc.
Referenced by beginWrite().
m_max_prots_digit
const Integer Arcane::DumpWEnsight7::m_max_prots_digit = 6 static private
Maximum number of digits to indicate the protection number.
Definition at line 762 of file DumpWEnsight7.cc.
Referenced by _buildFileName(), and _buildPartDirectory().
m_mesh
IMesh* Arcane::DumpWEnsight7::m_mesh private
Mesh.
Definition at line 732 of file DumpWEnsight7.cc.
Referenced by _saveGroup(), beginWrite(), and endWrite().
m_parallel_mng
IParallelMng* Arcane::DumpWEnsight7::m_parallel_mng private
Parallelism manager.
Definition at line 733 of file DumpWEnsight7.cc.
Referenced by beginWrite().
m_part_directory
Directory Arcane::DumpWEnsight7::m_part_directory private
Storage directory for the current iteration.
Definition at line 735 of file DumpWEnsight7.cc.
Referenced by _buildFileName(), and _buildPartDirectory().
m_parts
GroupPartInfoList Arcane::DumpWEnsight7::m_parts private
Definition at line 741 of file DumpWEnsight7.cc.
m_save_groups
ItemGroupList Arcane::DumpWEnsight7::m_save_groups private
List of groups to export.
Definition at line 740 of file DumpWEnsight7.cc.
Referenced by beginWrite().
m_save_uids
bool Arcane::DumpWEnsight7::m_save_uids private
Definition at line 749 of file DumpWEnsight7.cc.
m_save_variables
VariableList Arcane::DumpWEnsight7::m_save_variables private
List of variables to export.
Definition at line 739 of file DumpWEnsight7.cc.
Referenced by _isValidVariable(), beginWrite(), and endWrite().
m_times
RealUniqueArray Arcane::DumpWEnsight7::m_times private
description of saved variables
List of time instants
Definition at line 738 of file DumpWEnsight7.cc.
Referenced by _buildFileName(), _buildPartDirectory(), beginWrite(), and endWrite().
m_total_nb_element
Integer Arcane::DumpWEnsight7::m_total_nb_element private
Total number of mesh elements across all groups to be saved.
Definition at line 751 of file DumpWEnsight7.cc.
Referenced by beginWrite().
m_total_nb_group
Integer Arcane::DumpWEnsight7::m_total_nb_group private
Number of groups to save (== number of parts).
Number of elements in a timeset When saving multiple time instants in one file, a maximum of m_fileset_size time instants are placed in one file, and when this number is reached, another file is used.
Definition at line 752 of file DumpWEnsight7.cc.
Referenced by beginWrite().
m_use_degenerated_hexa
bool Arcane::DumpWEnsight7::m_use_degenerated_hexa private
Definition at line 747 of file DumpWEnsight7.cc.
The documentation for this class was generated from the following file:
DumpWEnsight7.cc