Arcane: Arcane::GnuplotTimeHistoryCurveWriter2 Class Reference
Arcane::GnuplotTimeHistoryCurveWriter2 Class Reference
GNUPLOT format writer.
Public Member Functions
GnuplotTimeHistoryCurveWriter2 (ITraceMng *tm)
void build () override
void beginWrite (const TimeHistoryCurveWriterInfo &infos) override
Notify the start of writing.
void writeCurve (const TimeHistoryCurveInfo &infos) override
Write a curve.
void endWrite () override
Notify the end of writing.
String name () const override
Writer name.
void setOutputPath (const String &path) override
Base directory where curves will be written.
String outputPath () const override
Base directory where curves will be written.
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Public Member Functions inherited from Arcane::ITimeHistoryCurveWriter2
virtual ~ITimeHistoryCurveWriter2 ()=default
Release resources.
Private Attributes
String m_output_path
UniqueArray< Real > m_times
Directory m_gnuplot_path
Additional Inherited Members
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Detailed Description
GNUPLOT format writer.
Definition at line 59 of file TimeHistoryMng2.cc.
Constructor & Destructor Documentation
GnuplotTimeHistoryCurveWriter2()
Arcane::GnuplotTimeHistoryCurveWriter2::GnuplotTimeHistoryCurveWriter2 (ITraceMng * tm) inline
Definition at line 65 of file TimeHistoryMng2.cc.
Member Function Documentation
beginWrite()
void Arcane::GnuplotTimeHistoryCurveWriter2::beginWrite (const TimeHistoryCurveWriterInfo & infos) inline override virtual
Notify the start of writing.
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 73 of file TimeHistoryMng2.cc.
References Arcane::TimeHistoryCurveWriterInfo::path(), Arcane::TimeHistoryCurveWriterInfo::times(), and Arcane::TraceAccessor::warning().
build()
void Arcane::GnuplotTimeHistoryCurveWriter2::build (void) inline override virtual
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 72 of file TimeHistoryMng2.cc.
endWrite()
void Arcane::GnuplotTimeHistoryCurveWriter2::endWrite () inline override virtual
Notify the end of writing.
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 118 of file TimeHistoryMng2.cc.
name()
String Arcane::GnuplotTimeHistoryCurveWriter2::name () const inline override virtual
Writer name.
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 120 of file TimeHistoryMng2.cc.
Referenced by writeCurve().
outputPath()
String Arcane::GnuplotTimeHistoryCurveWriter2::outputPath () const inline override virtual
Base directory where curves will be written.
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 126 of file TimeHistoryMng2.cc.
setOutputPath()
void Arcane::GnuplotTimeHistoryCurveWriter2::setOutputPath (const String & path) inline override virtual
Base directory where curves will be written.
If null, the directory specified during beginWrite() will be used.
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 122 of file TimeHistoryMng2.cc.
writeCurve()
void Arcane::GnuplotTimeHistoryCurveWriter2::writeCurve (const TimeHistoryCurveInfo & infos) inline override virtual
Write a curve.
Curve info is provided by infos Values are in the array values. times and iterations contain respectively the time and the iteration number for each value. path contains the directory where the curves will be written
Implements Arcane::ITimeHistoryCurveWriter2.
Definition at line 88 of file TimeHistoryMng2.cc.
References Arcane::String::clone(), Arcane::TimeHistoryCurveInfo::iterations(), Arcane::String::localstr(), name(), Arcane::TimeHistoryCurveInfo::name(), Arcane::ConstArrayView< T >::size(), Arcane::TimeHistoryCurveInfo::subSize(), Arcane::Convert::toDouble(), Arcane::TimeHistoryCurveInfo::values(), and Arcane::TraceAccessor::warning().
Member Data Documentation
m_gnuplot_path
Directory Arcane::GnuplotTimeHistoryCurveWriter2::m_gnuplot_path private
Definition at line 135 of file TimeHistoryMng2.cc.
m_output_path
String Arcane::GnuplotTimeHistoryCurveWriter2::m_output_path private
Definition at line 133 of file TimeHistoryMng2.cc.
m_times
UniqueArray<Real> Arcane::GnuplotTimeHistoryCurveWriter2::m_times private
Definition at line 134 of file TimeHistoryMng2.cc.
The documentation for this class was generated from the following file:
TimeHistoryMng2.cc