Arcane: Arcane::ItemInfoListView Class Reference
Arcane::ItemInfoListView Class Reference
View of a list to obtain information about entities.
#include <arcane/core/ItemInfoListView.h>
Public Member Functions
ItemInfoListView (IItemFamily *family)
Constructs a view associated with the family family.
IItemFamily * itemFamily () const
Associated family.
Item operator[] (ItemLocalId local_id) const
Entity associated with local ID local_id.
Item operator[] (Int32 local_id) const
Entity associated with local ID local_id.
Public Member Functions inherited from Arcane::ItemGenericInfoListView
ItemGenericInfoListView (IItemFamily *family)
Constructs a view associated with the family family.
ItemGenericInfoListView (const ItemInfoListView &info_list_view)
IItemFamily * itemFamily () const
Associated family.
constexpr __host__ __device__ Int32 owner (Int32 local_id) const
Owner of the entity with local ID local_id.
constexpr __host__ __device__ Int32 owner (ItemLocalId local_id) const
Owner of the entity with local ID local_id.
constexpr __host__ __device__ Int16 typeId (Int32 local_id) const
Type of the entity with local ID local_id.
constexpr __host__ __device__ Int16 typeId (ItemLocalId local_id) const
Type of the entity with local ID local_id.
__host__ __device__ ItemUniqueId uniqueId (Int32 local_id) const
uniqueId() of the entity with local ID local_id
__host__ __device__ ItemUniqueId uniqueId (ItemLocalId local_id) const
uniqueId() of the entity with local ID local_id
constexpr __host__ __device__ bool isOwn (Int32 local_id) const
Indicates if the entity with local ID local_id belongs to the subdomain.
constexpr __host__ __device__ bool isOwn (ItemLocalId local_id) const
Indicates if the entity with local ID local_id belongs to the subdomain.
constexpr __host__ __device__ bool isShared (Int32 local_id) const
Indicates if the entity with local ID local_id is shared by other subdomains.
constexpr __host__ __device__ bool isShared (ItemLocalId local_id) const
Indicates if the entity with local ID local_id is shared by other subdomains.
Protected Member Functions
void _checkValid (eItemKind expected_kind)
Checks that the entity kind matches the expected one.
Friends
class mesh::ItemFamily
template<int Extent>
class ItemConnectedListView
template<typename ItemType>
class ItemEnumeratorBaseT
Detailed Description
View of a list to obtain information about entities.
Like all views, these instances are temporary and should not be kept between two modifications of the associated family.
The methods of this class are only valid if the instance has been initialized with a non-null family (IItemFamily).
Via this class, it is possible to retrieve an Item instance from an ItemLocalId.
Definition at line 40 of file ItemInfoListView.h.
Constructor & Destructor Documentation
ItemInfoListView()
Arcane::ItemInfoListView::ItemInfoListView (IItemFamily * family) explicit
Constructs a view associated with the family family.
family may be nullptr in which case the instance is not usable for retrieving entity information
Definition at line 29 of file ItemInfoListView.cc.
Member Function Documentation
_checkValid()
void Arcane::ItemInfoListView::_checkValid (eItemKind expected_kind) protected
Checks that the entity kind matches the expected one.
Definition at line 41 of file ItemInfoListView.cc.
References ARCANE_FATAL, Arcane::IItemFamily::fullName(), itemFamily(), and Arcane::IItemFamily::itemKind().
Referenced by Arcane::ItemInfoListViewT< Node >::ItemInfoListViewT().
itemFamily()
IItemFamily * Arcane::ItemInfoListView::itemFamily () const inline
Associated family.
Definition at line 69 of file ItemInfoListView.h.
Referenced by _checkValid().
operator[]() [1/2]
Item Arcane::ItemInfoListView::operator[] (Int32 local_id) const inline
Entity associated with local ID local_id.
Definition at line 1877 of file Item.h.
operator[]() [2/2]
Item Arcane::ItemInfoListView::operator[] (ItemLocalId local_id) const inline
Entity associated with local ID local_id.
Definition at line 1868 of file Item.h.
Friends And Related Symbol Documentation
ItemConnectedListView
template<int Extent> friend class ItemConnectedListView friend
Definition at line 48 of file ItemInfoListView.h.
ItemEnumeratorBaseT
template<typename ItemType> friend class ItemEnumeratorBaseT friend
Definition at line 49 of file ItemInfoListView.h.
mesh::ItemFamily
friend class mesh::ItemFamily friend
Definition at line 44 of file ItemInfoListView.h.
The documentation for this class was generated from the following files:
ItemInfoListView.h
Item.h
ItemInfoListView.cc