Alien: Alien::VectorDistribution::Internal Struct Reference
Alien::VectorDistribution::Internal Struct Reference
Internal implementation of the vector distribution.
Public Member Functions
Internal ()
Constructor.
Internal (const ISpace &space, IMessagePassingMng *parallel_mng)
Constructor.
Internal (const ISpace &space, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Internal (Integer global_size, IMessagePassingMng *parallel_mng)
Constructor.
Internal (Integer global_size, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Internal (const ISpace &space, Integer local_size, IMessagePassingMng *parallel_mng)
Constructor.
Internal (const ISpace &space, Integer local_size, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Internal (Integer global_size, Integer local_size, IMessagePassingMng *parallel_mng)
Constructor.
Internal (Integer global_size, Integer local_size, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
~Internal ()=default
Free resources.
bool operator== (const Internal &dist) const
Comparison operator.
bool isParallel () const
Whether or not the run is parallel.
Integer owner (Integer i) const
Get the owner of an entry.
Public Attributes
std::shared_ptr< ISpace > m_space
The space.
std::shared_ptr< IMessagePassingMng > m_parallel_mng
The parallel manager.
Integer m_rank
The local rank.
Integer m_global_size
The global size.
Integer m_local_size
The local size.
Integer m_offset
The local offset.
UniqueArray< Integer > m_offsets
The array of offsets for all proc.
Detailed Description
Internal implementation of the vector distribution.
Definition at line 47 of file VectorDistribution.cc.
Constructor & Destructor Documentation
Internal() [1/9]
Alien::VectorDistribution::Internal::Internal ()
Constructor.
Definition at line 159 of file VectorDistribution.cc.
References m_global_size, m_local_size, m_offset, m_offsets, m_parallel_mng, and m_rank.
Referenced by Internal(), Internal(), Internal(), Internal(), operator==(), and ~Internal().
Internal() [2/9]
Alien::VectorDistribution::Internal::Internal (const ISpace & space, IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] parallel_mng The parallel manager
Definition at line 171 of file VectorDistribution.cc.
References Alien::VectorDistribution::clone(), m_parallel_mng, m_space, and Alien::VectorDistribution::space().
Internal() [3/9]
Alien::VectorDistribution::Internal::Internal (const ISpace & space, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] parallel_mng The parallel manager
Definition at line 200 of file VectorDistribution.cc.
References Alien::VectorDistribution::clone(), m_global_size, m_local_size, m_offset, m_offsets, m_parallel_mng, m_rank, m_space, and Alien::VectorDistribution::space().
Internal() [4/9]
Alien::VectorDistribution::Internal::Internal (Integer global_size, IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] parallel_mng The parallel manager
Definition at line 228 of file VectorDistribution.cc.
References Internal().
Internal() [5/9]
Alien::VectorDistribution::Internal::Internal (Integer global_size, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] parallel_mng The parallel manager
Definition at line 236 of file VectorDistribution.cc.
References Internal().
Internal() [6/9]
Alien::VectorDistribution::Internal::Internal (const ISpace & space, Integer local_size, IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
Definition at line 244 of file VectorDistribution.cc.
References Alien::VectorDistribution::clone(), m_parallel_mng, m_space, and Alien::VectorDistribution::space().
Internal() [7/9]
Alien::VectorDistribution::Internal::Internal (const ISpace & space, Integer local_size, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] space The space of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
Definition at line 282 of file VectorDistribution.cc.
References Alien::VectorDistribution::clone(), m_global_size, m_local_size, m_offset, m_offsets, m_parallel_mng, m_rank, m_space, and Alien::VectorDistribution::space().
Internal() [8/9]
Alien::VectorDistribution::Internal::Internal (Integer global_size, Integer local_size, IMessagePassingMng * parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
Definition at line 319 of file VectorDistribution.cc.
References Internal().
Internal() [9/9]
Alien::VectorDistribution::Internal::Internal (Integer global_size, Integer local_size, std::shared_ptr< IMessagePassingMng > parallel_mng)
Constructor.
Parameters
[in] global_size The global size of the vector
[in] local_size The local size of the vector
[in] parallel_mng The parallel manager
Definition at line 327 of file VectorDistribution.cc.
References Internal().
Member Function Documentation
isParallel()
bool Alien::VectorDistribution::Internal::isParallel () const
Whether or not the run is parallel.
Returns
Whether or not the run is parallel
Definition at line 343 of file VectorDistribution.cc.
References m_parallel_mng.
operator==()
bool Alien::VectorDistribution::Internal::operator== (const Internal & dist) const
Comparison operator.
Parameters
[in] dist The distribution to compare
Returns
Whether or not the distribution are identical
Definition at line 335 of file VectorDistribution.cc.
References Internal(), m_global_size, m_local_size, m_offset, m_parallel_mng, and m_rank.
owner()
Integer Alien::VectorDistribution::Internal::owner (Integer i) const
Get the owner of an entry.
Parameters
[in] i The global id of the element
Returns
The proc owner
Definition at line 352 of file VectorDistribution.cc.
References m_offset, m_offsets, m_parallel_mng, and m_rank.
Member Data Documentation
m_global_size
Integer Alien::VectorDistribution::Internal::m_global_size
The global size.
Definition at line 147 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), and operator==().
m_local_size
Integer Alien::VectorDistribution::Internal::m_local_size
The local size.
Definition at line 149 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), and operator==().
m_offset
Integer Alien::VectorDistribution::Internal::m_offset
The local offset.
Definition at line 151 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), operator==(), and owner().
m_offsets
UniqueArray<Integer> Alien::VectorDistribution::Internal::m_offsets
The array of offsets for all proc.
Definition at line 153 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), and owner().
m_parallel_mng
std::shared_ptr<IMessagePassingMng> Alien::VectorDistribution::Internal::m_parallel_mng
The parallel manager.
Definition at line 142 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), Internal(), Internal(), isParallel(), operator==(), and owner().
m_rank
Integer Alien::VectorDistribution::Internal::m_rank
The local rank.
Definition at line 145 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), operator==(), and owner().
m_space
std::shared_ptr<ISpace> Alien::VectorDistribution::Internal::m_space
The space.
Definition at line 138 of file VectorDistribution.cc.
Referenced by Internal(), Internal(), Internal(), and Internal().
The documentation for this struct was generated from the following file:
VectorDistribution.cc