Arcane: Arcane::Accelerator::RunQueueEvent Class Reference
Arcane::Accelerator::RunQueueEvent Class Reference
Event for a run queue.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/common/arccore/common/accelerator/RunQueueEvent.h>
Classes
class InternalImpl
Public Member Functions
RunQueueEvent (const RunQueueEvent &)
RunQueueEvent & operator= (const RunQueueEvent &)
RunQueueEvent (RunQueueEvent &&) noexcept
RunQueueEvent & operator= (RunQueueEvent &&) noexcept
bool isNull () const
Indicates if the instance is null.
void wait ()
bool hasPendingWork () const
Indicates if the RunQueues associated with this event have finished their work.
Private Member Functions
RunQueueEvent (const Runner &runner)
Constructs an event. Use makeEvent() to construct an instance.
Impl::IRunQueueEventImpl * _internalEventImpl () const
Private Attributes
friend RunQueue
AutoRef2< InternalImpl > m_p
Friends
RunQueueEvent makeEvent (const Runner &runner)
Creates an event associated with runner.
Ref< RunQueueEvent > makeEventRef (const Runner &runner)
Creates an event associated with runner.
Detailed Description
Event for a run queue.
This class has a reference semantics.
The RunQueue::recordEvent() and RunQueue::waitEvent() methods allow associating a RunQueueEvent with a given RunQueue to perform a synchronization.
For example:
Definition at line 44 of file arccore/src/common/arccore/common/accelerator/RunQueueEvent.h.
Constructor & Destructor Documentation
RunQueueEvent() [1/4]
Arcane::Accelerator::RunQueueEvent::RunQueueEvent (const Runner & runner) explicit private
Constructs an event. Use makeEvent() to construct an instance.
Definition at line 79 of file RunQueueEvent.cc.
Referenced by makeEvent, and makeEventRef.
RunQueueEvent() [2/4]
Arcane::Accelerator::RunQueueEvent::RunQueueEvent ()
Definition at line 71 of file RunQueueEvent.cc.
RunQueueEvent() [3/4]
Arcane::Accelerator::RunQueueEvent::RunQueueEvent (const RunQueueEvent & x)
Definition at line 88 of file RunQueueEvent.cc.
RunQueueEvent() [4/4]
Arcane::Accelerator::RunQueueEvent::RunQueueEvent (RunQueueEvent && x) noexcept
Definition at line 97 of file RunQueueEvent.cc.
~RunQueueEvent()
Arcane::Accelerator::RunQueueEvent::~RunQueueEvent ()
Definition at line 127 of file RunQueueEvent.cc.
Member Function Documentation
_internalEventImpl()
Impl::IRunQueueEventImpl * Arcane::Accelerator::RunQueueEvent::_internalEventImpl () const private
Definition at line 156 of file RunQueueEvent.cc.
hasPendingWork()
bool Arcane::Accelerator::RunQueueEvent::hasPendingWork () const
Indicates if the RunQueues associated with this event have finished their work.
Returns false if the RunQueues registered via RunQueue::recordEvent() have finished their work. Returns true otherwise.
Definition at line 145 of file RunQueueEvent.cc.
isNull()
bool Arcane::Accelerator::RunQueueEvent::isNull () const inline
Indicates if the instance is null.
The instance is null if it was constructed with the default constructor.
Definition at line 73 of file arccore/src/common/arccore/common/accelerator/RunQueueEvent.h.
operator=() [1/2]
RunQueueEvent & Arcane::Accelerator::RunQueueEvent::operator= (const RunQueueEvent & x)
Definition at line 106 of file RunQueueEvent.cc.
operator=() [2/2]
RunQueueEvent & Arcane::Accelerator::RunQueueEvent::operator= (RunQueueEvent && x) noexcept
Definition at line 117 of file RunQueueEvent.cc.
wait()
void Arcane::Accelerator::RunQueueEvent::wait ()
Blocks until the queues associated with this event have finished their work.
Definition at line 135 of file RunQueueEvent.cc.
References wait().
Referenced by wait().
Friends And Related Symbol Documentation
makeEvent
RunQueueEvent makeEvent (const Runner & runner) friend
Creates an event associated with runner.
Definition at line 107 of file arccore/src/common/arccore/common/accelerator/RunQueueEvent.h.
References RunQueueEvent().
makeEventRef
Ref< RunQueueEvent > makeEventRef (const Runner & runner) friend
Creates an event associated with runner.
Definition at line 119 of file arccore/src/common/arccore/common/accelerator/RunQueueEvent.h.
References Arcane::makeRef(), and RunQueueEvent().
Member Data Documentation
m_p
AutoRef2<InternalImpl> Arcane::Accelerator::RunQueueEvent::m_p private
Definition at line 94 of file arccore/src/common/arccore/common/accelerator/RunQueueEvent.h.
RunQueue
friend Arcane::Accelerator::RunQueueEvent::RunQueue private
Definition at line 48 of file arccore/src/common/arccore/common/accelerator/RunQueueEvent.h.
The documentation for this class was generated from the following files:
arccore/src/common/arccore/common/accelerator/RunQueueEvent.h
RunQueueEvent.cc