Alien: Alien::ExtractionIndices Class Reference
Alien::ExtractionIndices Class Reference final
Tool to iterate over a matrix.
#include <core/alien/data/utils/ExtractionIndices.h>
Public Member Functions
ExtractionIndices (const Arccore::Integer rowStart, const Arccore::Integer rowRange, const Arccore::Integer colStart=-1, const Arccore::Integer colRange=-1)
Constructor.
~ExtractionIndices ()
Free resources.
ExtractionIndices (const ExtractionIndices &)=delete
ExtractionIndices (ExtractionIndices &&)=delete
ExtractionIndices & operator= (const ExtractionIndices &)=delete
ExtractionIndices & operator= (ExtractionIndices &&)=delete
Arccore::Integer rowStart () const
Get the index of the starting row.
Arccore::Integer rowRange () const
Get the length of the row.
Arccore::Integer colStart () const
Get the index of the starting col.
Arccore::Integer colRange () const
Get the length of the col.
Arccore::Integer toLocalRow (const Arccore::Integer uid) const
Get the local index of a row given a global index.
Arccore::Integer toLocalCol (const Arccore::Integer uid) const
Get the local index of a col given a global index.
Private Attributes
Arccore::Integer m_starting_row
Index of the starting row.
Arccore::Integer m_starting_col
Index of the starting col.
Arccore::Integer m_row_range
Length of the row.
Arccore::Integer m_col_range
Length of the col.
Detailed Description
Tool to iterate over a matrix.
Definition at line 41 of file ExtractionIndices.h.
Constructor & Destructor Documentation
ExtractionIndices()
Alien::ExtractionIndices::ExtractionIndices (const Arccore::Integer rowStart, const Arccore::Integer rowRange, const Arccore::Integer colStart = -1, const Arccore::Integer colRange = -1)
Constructor.
Parameters
[in] rowStart The index of the starting row
[in] rowRange The length of the row
[in] colStart The index of the starting col
[in] colRange The length of the col
References colRange(), colStart(), ExtractionIndices(), rowRange(), rowStart(), toLocalCol(), and toLocalRow().
Referenced by ExtractionIndices().
~ExtractionIndices()
Alien::ExtractionIndices::~ExtractionIndices ()
Free resources.
Definition at line 48 of file ExtractionIndices.cc.
References ~ExtractionIndices().
Referenced by ~ExtractionIndices().
Member Function Documentation
colRange()
Integer Alien::ExtractionIndices::colRange () const
Get the length of the col.
Returns
The length of the col
Definition at line 81 of file ExtractionIndices.cc.
References colRange(), and m_col_range.
Referenced by colRange(), and ExtractionIndices().
colStart()
Integer Alien::ExtractionIndices::colStart () const
Get the index of the starting col.
Returns
The index of the starting col
Definition at line 72 of file ExtractionIndices.cc.
References colStart(), and m_starting_col.
Referenced by colStart(), and ExtractionIndices().
rowRange()
Integer Alien::ExtractionIndices::rowRange () const
Get the length of the row.
Returns
The length of the row
Definition at line 63 of file ExtractionIndices.cc.
References m_row_range, and rowRange().
Referenced by ExtractionIndices(), and rowRange().
rowStart()
Integer Alien::ExtractionIndices::rowStart () const
Get the index of the starting row.
Returns
The index of the starting row
Definition at line 54 of file ExtractionIndices.cc.
References m_starting_row, and rowStart().
Referenced by ExtractionIndices(), and rowStart().
toLocalCol()
Integer Alien::ExtractionIndices::toLocalCol (const Arccore::Integer uid) const
Get the local index of a col given a global index.
Parameters
[in] uid The global index of a col
Returns
The local index of a col
Definition at line 99 of file ExtractionIndices.cc.
References m_starting_col, and toLocalCol().
Referenced by ExtractionIndices(), and toLocalCol().
toLocalRow()
Integer Alien::ExtractionIndices::toLocalRow (const Arccore::Integer uid) const
Get the local index of a row given a global index.
Parameters
[in] uid The global index of a row
Returns
The local index of a row
Definition at line 90 of file ExtractionIndices.cc.
References m_starting_row, and toLocalRow().
Referenced by ExtractionIndices(), and toLocalRow().
Member Data Documentation
m_col_range
Arccore::Integer Alien::ExtractionIndices::m_col_range private
Length of the col.
Definition at line 108 of file ExtractionIndices.h.
Referenced by colRange().
m_row_range
Arccore::Integer Alien::ExtractionIndices::m_row_range private
Length of the row.
Definition at line 106 of file ExtractionIndices.h.
Referenced by rowRange().
m_starting_col
Arccore::Integer Alien::ExtractionIndices::m_starting_col private
Index of the starting col.
Definition at line 104 of file ExtractionIndices.h.
Referenced by colStart(), and toLocalCol().
m_starting_row
Arccore::Integer Alien::ExtractionIndices::m_starting_row private
Index of the starting row.
Definition at line 102 of file ExtractionIndices.h.
Referenced by rowStart(), and toLocalRow().
The documentation for this class was generated from the following files:
ExtractionIndices.h
ExtractionIndices.cc