Alien: Alien::IVector Class Reference
Alien::IVector Class Reference abstract
Interface for all vectors.
#include <core/alien/data/IVector.h>
Public Member Functions
virtual void visit (ICopyOnWriteVector &) const =0
Visit method.
virtual const ISpace & space () const =0
Get the space associated to the vector.
virtual MultiVectorImpl * impl ()=0
Get the multivector implementation.
virtual const MultiVectorImpl * impl () const =0
Get the multivector implementation.
Protected Member Functions
IVector ()
Constructor.
Private Member Functions
IVector (const IVector &)=delete
IVector (IVector &&)=delete
void operator= (const IVector &)=delete
void operator= (IVector &&)=delete
Detailed Description
Interface for all vectors.
Definition at line 50 of file IVector.h.
Constructor & Destructor Documentation
IVector()
Alien::IVector::IVector () inline protected
Constructor.
Definition at line 54 of file IVector.h.
Referenced by Alien::CompositeVector::operator[](), and Alien::CompositeVector::operator[]().
~IVector()
virtual Alien::IVector::~IVector () inline virtual
Definition at line 65 of file IVector.h.
Member Function Documentation
impl() [1/2]
virtual const MultiVectorImpl * Alien::IVector::impl () const pure virtual
Get the multivector implementation.
Returns
The multivector implementation
Implemented in Alien::BlockVector, Alien::CompositeVector, Alien::Move::VectorData, Alien::NullVector, Alien::RedistributedVector, Alien::VBlockVector, and Alien::Vector.
impl() [2/2]
virtual MultiVectorImpl * Alien::IVector::impl () pure virtual
Get the multivector implementation.
Returns
The multivector implementation
Implemented in Alien::BlockVector, Alien::CompositeVector, Alien::Move::VectorData, Alien::NullVector, Alien::RedistributedVector, Alien::VBlockVector, and Alien::Vector.
Referenced by Alien::LinearAlgebra< Tag, TagV >::axpy(), Alien::LinearAlgebraExpr< Tag, TagV >::axpy(), Alien::LinearAlgebra< Tag, TagV >::aypx(), Alien::LinearAlgebraExpr< Tag, TagV >::aypx(), Alien::SchurOp::computePrimarySystem(), Alien::LinearAlgebra< Tag, TagV >::copy(), Alien::LinearAlgebraExpr< Tag, TagV >::copy(), Alien::LinearAlgebra< Tag, TagV >::diagonal(), Alien::LinearAlgebraExpr< Tag, TagV >::diagonal(), Alien::LinearAlgebra< Tag, TagV >::dot(), Alien::LinearAlgebraExpr< Tag, TagV >::dot(), Alien::LinearAlgebra< Tag, TagV >::dump(), Alien::LinearAlgebraExpr< Tag, TagV >::dump(), Alien::LinearAlgebra< Tag, TagV >::mult(), Alien::LinearAlgebraExpr< Tag, TagV >::mult(), Alien::LinearAlgebra< Tag, TagV >::norm0(), Alien::LinearAlgebraExpr< Tag, TagV >::norm0(), Alien::LinearAlgebra< Tag, TagV >::norm1(), Alien::LinearAlgebraExpr< Tag, TagV >::norm1(), Alien::LinearAlgebra< Tag, TagV >::norm2(), Alien::LinearAlgebraExpr< Tag, TagV >::norm2(), Alien::NormalizeOpt::normalize(), Alien::LinearAlgebra< Tag, TagV >::normInf(), Alien::LinearAlgebraExpr< Tag, TagV >::normInf(), Alien::LinearAlgebra< Tag, TagV >::pointwiseMult(), Alien::LinearAlgebraExpr< Tag, TagV >::pointwiseMult(), Alien::LinearAlgebra< Tag, TagV >::reciprocal(), Alien::LinearAlgebraExpr< Tag, TagV >::reciprocal(), Alien::LinearAlgebra< Tag, TagV >::scal(), Alien::LinearAlgebraExpr< Tag, TagV >::scal(), and Alien::LinearSolver< Tag >::solve().
space()
virtual const ISpace & Alien::IVector::space () const pure virtual
Get the space associated to the vector.
Returns
The space
Implemented in Alien::BlockVector, Alien::CompositeVector, Alien::Move::VectorData, Alien::NullVector, Alien::RedistributedVector, Alien::VBlockVector, and Alien::Vector.
visit()
virtual void Alien::IVector::visit (ICopyOnWriteVector &) const pure virtual
Visit method.
Implemented in Alien::BlockVector, Alien::CompositeVector, Alien::Move::VectorData, Alien::NullVector, Alien::RedistributedVector, Alien::VBlockVector, and Alien::Vector.
The documentation for this class was generated from the following file:
IVector.h