Arcane: Arcane::Materials::MeshMaterialVariableSynchronizerList Class Reference
Arcane::Materials::MeshMaterialVariableSynchronizerList Class Reference
Synchronizing a list of material variables.
#include <arcane/materials/MeshMaterialVariableSynchronizerList.h>
Classes
class SyncInfo
class Impl
Public Member Functions
MeshMaterialVariableSynchronizerList (IMeshMaterialMng *material_mng)
MeshMaterialVariableSynchronizerList (const MeshMaterialVariableSynchronizerList &)=delete
MeshMaterialVariableSynchronizerList & operator= (const MeshMaterialVariableSynchronizerList &)=delete
MeshMaterialVariableSynchronizerList (const MeshMaterialVariableSynchronizerList &&)=delete
MeshMaterialVariableSynchronizerList & operator= (const MeshMaterialVariableSynchronizerList &&)=delete
void apply ()
Performs the synchronization.
void add (MeshMaterialVariable *var)
Adds the variable var to the list of variables to synchronize.
Int64 totalMessageSize () const
After calling apply(), contains the size of the messages sent.
void beginSynchronize ()
Starts a non-blocking synchronization.
void endSynchronize ()
Blocks until the ongoing synchronization is finished.
Private Member Functions
void _fillSyncInfo (SyncInfo &sync_info)
void _beginSynchronize (bool is_blocking)
void _endSynchronize (bool is_blocking)
Static Private Member Functions
static void _beginSynchronizeMultiple (SyncInfo &sync_info)
static void _beginSynchronizeMultiple2 (SyncInfo &sync_info)
static void _endSynchronizeMultiple2 (SyncInfo &sync_info)
Private Attributes
Impl * m_p
Detailed Description
Synchronizing a list of material variables.
The add() method allows adding variables to synchronize. You must then call apply() to perform the synchronization.
An instance of this class can be used multiple times.
Definition at line 39 of file MeshMaterialVariableSynchronizerList.h.
Constructor & Destructor Documentation
MeshMaterialVariableSynchronizerList()
Arcane::Materials::MeshMaterialVariableSynchronizerList::MeshMaterialVariableSynchronizerList (IMeshMaterialMng * material_mng) explicit
Definition at line 93 of file MeshMaterialVariableSynchronizerList.cc.
~MeshMaterialVariableSynchronizerList()
Arcane::Materials::MeshMaterialVariableSynchronizerList::~MeshMaterialVariableSynchronizerList ()
Definition at line 102 of file MeshMaterialVariableSynchronizerList.cc.
Member Function Documentation
_beginSynchronize()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::_beginSynchronize (bool is_blocking) private
Definition at line 156 of file MeshMaterialVariableSynchronizerList.cc.
_beginSynchronizeMultiple()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::_beginSynchronizeMultiple (SyncInfo & sync_info) static private
Definition at line 250 of file MeshMaterialVariableSynchronizerList.cc.
_beginSynchronizeMultiple2()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::_beginSynchronizeMultiple2 (SyncInfo & sync_info) static private
Definition at line 281 of file MeshMaterialVariableSynchronizerList.cc.
_endSynchronize()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::_endSynchronize (bool is_blocking) private
Definition at line 199 of file MeshMaterialVariableSynchronizerList.cc.
_endSynchronizeMultiple2()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::_endSynchronizeMultiple2 (SyncInfo & sync_info) static private
Definition at line 375 of file MeshMaterialVariableSynchronizerList.cc.
_fillSyncInfo()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::_fillSyncInfo (SyncInfo & sync_info) private
Definition at line 240 of file MeshMaterialVariableSynchronizerList.cc.
add()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::add (MeshMaterialVariable * var)
Adds the variable var to the list of variables to synchronize.
Definition at line 224 of file MeshMaterialVariableSynchronizerList.cc.
References ARCANE_THROW, Arcane::Materials::Environment, Arcane::Materials::MaterialAndEnvironment, Arcane::Materials::MeshMaterialVariable::name(), and Arcane::Materials::MeshMaterialVariable::space().
Referenced by Arcane::Materials::ItemMaterialVariableArray< DataType >::synchronize().
apply()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::apply ()
Performs the synchronization.
Definition at line 120 of file MeshMaterialVariableSynchronizerList.cc.
Referenced by Arcane::Materials::ItemMaterialVariableArray< DataType >::synchronize().
beginSynchronize()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::beginSynchronize ()
Starts a non-blocking synchronization.
This is only valid if IMeshMaterialMng::synchronizeVariableVersion() equals 7.
Definition at line 135 of file MeshMaterialVariableSynchronizerList.cc.
References ARCANE_FATAL.
endSynchronize()
void Arcane::Materials::MeshMaterialVariableSynchronizerList::endSynchronize ()
Blocks until the ongoing synchronization is finished.
You must call beginSynchronize() before this call.
Definition at line 147 of file MeshMaterialVariableSynchronizerList.cc.
totalMessageSize()
Int64 Arcane::Materials::MeshMaterialVariableSynchronizerList::totalMessageSize () const
After calling apply(), contains the size of the messages sent.
Definition at line 111 of file MeshMaterialVariableSynchronizerList.cc.
Member Data Documentation
m_p
Impl* Arcane::Materials::MeshMaterialVariableSynchronizerList::m_p private
Definition at line 85 of file MeshMaterialVariableSynchronizerList.h.
The documentation for this class was generated from the following files:
MeshMaterialVariableSynchronizerList.h
MeshMaterialVariableSynchronizerList.cc