Arcane: Arcane::ExpressionImpl Class Reference
Arcane::ExpressionImpl Class Reference
Base class for the expression implementation.
#include <arcane/core/expr/ExpressionImpl.h>
Public Member Functions
virtual void addRef ()
virtual void removeRef ()
virtual void setTrace (bool v)
virtual void dumpIf (IExpressionImpl *test_expr, Array< Expression > &exprs)
Public Member Functions inherited from Arcane::IExpressionImpl
virtual void assign (IExpressionImpl *expr)=0
virtual void assign (IExpressionImpl *expr, IntegerConstArrayView indices)=0
virtual Integer vectorSize () const =0
Number of elements in the vector.
virtual void apply (ExpressionResult *result)=0
Protected Member Functions
bool isTraceMode () const
Protected Member Functions inherited from Arcane::IExpressionImpl
virtual ~IExpressionImpl ()
Releases resources. Only called by a removeRef().
Protected Attributes
OperatorMng * m_op_mng
Private Attributes
Integer m_nb_reference
Number of references.
bool m_do_trace
Detailed Description
Base class for the expression implementation.
Definition at line 39 of file ExpressionImpl.h.
Constructor & Destructor Documentation
ExpressionImpl()
Arcane::ExpressionImpl::ExpressionImpl ()
Definition at line 28 of file ExpressionImpl.cc.
Member Function Documentation
addRef()
void Arcane::ExpressionImpl::addRef () virtual
Implements Arcane::IExpressionImpl.
Definition at line 39 of file ExpressionImpl.cc.
dumpIf()
void Arcane::ExpressionImpl::dumpIf (IExpressionImpl * test_expr, Array< Expression > & add_exprs) virtual
Warning
The current implementation assumes that all expressions * passed as parameters are of real type, and the test expression is boolean.
Implements Arcane::IExpressionImpl.
Definition at line 65 of file ExpressionImpl.cc.
References Arcane::Array< T >::resize(), Arcane::AbstractArray< T >::size(), and Arcane::IExpressionImpl::vectorSize().
isTraceMode()
bool Arcane::ExpressionImpl::isTraceMode () const inline protected
Definition at line 56 of file ExpressionImpl.h.
removeRef()
void Arcane::ExpressionImpl::removeRef () virtual
Implements Arcane::IExpressionImpl.
Definition at line 48 of file ExpressionImpl.cc.
setTrace()
virtual void Arcane::ExpressionImpl::setTrace (bool v) inline virtual
Implements Arcane::IExpressionImpl.
Definition at line 50 of file ExpressionImpl.h.
Member Data Documentation
m_do_trace
bool Arcane::ExpressionImpl::m_do_trace private
Definition at line 61 of file ExpressionImpl.h.
m_nb_reference
Integer Arcane::ExpressionImpl::m_nb_reference private
Number of references.
Definition at line 60 of file ExpressionImpl.h.
m_op_mng
OperatorMng* Arcane::ExpressionImpl::m_op_mng protected
Definition at line 55 of file ExpressionImpl.h.
The documentation for this class was generated from the following files:
ExpressionImpl.h
ExpressionImpl.cc