Arcane: Arcane::IPostProcessorWriter Class Reference
Arcane::IPostProcessorWriter Class Reference abstract
IO
Interface for a writer for post-processing information.
#include <arcane/core/IPostProcessorWriter.h>
Public Member Functions
virtual ~IPostProcessorWriter ()=default
Releases resources.
virtual void build ()=0
Constructs the instance.
virtual IDataWriter * dataWriter ()=0
Returns the writer associated with this post-processor.
virtual void setBaseDirectoryName (const String &dirname)=0
Positions the output directory name for files.
virtual const String & baseDirectoryName ()=0
Name of the output directory for files.
virtual String getBaseDirectoryName ()
Name of the output directory for files.
virtual void setBaseFileName (const String &filename)=0
Positions the name of the file containing the outputs.
virtual const String & baseFileName ()=0
Name of the file containing the outputs.
virtual String getBaseFileName ()
Name of the file containing the outputs.
virtual void setMesh (IMesh *mesh)
Positions the mesh.
virtual void setTimes (ConstArrayView< Real > times)=0
Positions the list of times.
virtual ConstArrayView< Real > times ()=0
List of saved times.
virtual void setVariables (VariableCollection variables)=0
Positions the list of variables to output.
virtual VariableCollection variables ()=0
List of variables to save.
virtual void setGroups (ItemGroupCollection groups)=0
Positions the list of groups to output.
virtual ItemGroupCollection groups ()=0
List of groups to save.
virtual void notifyBeginWrite ()=0
Notifies that an output is going to be performed with the current parameters.
virtual void notifyEndWrite ()=0
Notifies that an output has just been performed.
virtual void close ()=0
Closes the writer. After closing, it can no longer be used.
Detailed Description
Interface for a writer for post-processing information.
The instance must return an IDataWriter (via dataWriter()) to handle the writing.
The caller must position the instant fields and start the writing via the call IVariableMng::writePostProcessing(). For example
IPostProcessorWriter* pp = ...;
pp->setBaseDirectoryName(...);
pp->setTimes(...);
pp->setVariables(...);
pp->setGroups(...);
IVariableMng* vm = ...;
vm->writerPostProcessing(pp);
Before writing the variables, the IVariableMng instance will call notifyBeginWrite(). After writing, it calls notifyEndWrite().
Definition at line 58 of file IPostProcessorWriter.h.
Member Function Documentation
baseDirectoryName()
virtual const String & Arcane::IPostProcessorWriter::baseDirectoryName () pure virtual
Name of the output directory for files.
Implemented in Arcane::PostProcessorWriterCommonBase.
References getBaseDirectoryName().
Referenced by getBaseDirectoryName().
baseFileName()
virtual const String & Arcane::IPostProcessorWriter::baseFileName () pure virtual
Name of the file containing the outputs.
Implemented in Arcane::PostProcessorWriterCommonBase.
References getBaseFileName(), and setMesh().
Referenced by getBaseFileName().
build()
virtual void Arcane::IPostProcessorWriter::build () pure virtual
Constructs the instance.
Implemented in Arcane::ManualHdf5VariableWriter, and Arcane::PostProcessorWriterBase.
close()
virtual void Arcane::IPostProcessorWriter::close () pure virtual
Closes the writer. After closing, it can no longer be used.
Implemented in Arcane::ManualHdf5VariableWriter.
References close().
Referenced by close().
dataWriter()
virtual IDataWriter * Arcane::IPostProcessorWriter::dataWriter () pure virtual
Returns the writer associated with this post-processor.
The returned pointer is only valid between calls to notifyBeginWrite() and notifyEndWrite().
Implemented in Arcane::ManualHdf5VariableWriter.
getBaseDirectoryName()
String Arcane::IPostProcessorWriter::getBaseDirectoryName () virtual
Name of the output directory for files.
Definition at line 187 of file PostProcessorWriterBase.cc.
References baseDirectoryName().
Referenced by baseDirectoryName().
getBaseFileName()
String Arcane::IPostProcessorWriter::getBaseFileName () virtual
Name of the file containing the outputs.
Definition at line 196 of file PostProcessorWriterBase.cc.
References baseFileName().
Referenced by baseFileName().
groups()
virtual ItemGroupCollection Arcane::IPostProcessorWriter::groups () pure virtual
List of groups to save.
Implemented in Arcane::PostProcessorWriterCommonBase.
References groups().
Referenced by groups(), and setGroups().
notifyBeginWrite()
virtual void Arcane::IPostProcessorWriter::notifyBeginWrite () pure virtual
Notifies that an output is going to be performed with the current parameters.
Implemented in Arcane::ManualHdf5VariableWriter.
References notifyBeginWrite().
Referenced by notifyBeginWrite().
notifyEndWrite()
virtual void Arcane::IPostProcessorWriter::notifyEndWrite () pure virtual
Notifies that an output has just been performed.
Implemented in Arcane::ManualHdf5VariableWriter.
References notifyEndWrite().
Referenced by notifyEndWrite().
setBaseDirectoryName()
virtual void Arcane::IPostProcessorWriter::setBaseDirectoryName (const String & dirname) pure virtual
Positions the output directory name for files.
This directory must exist.
Implemented in Arcane::PostProcessorWriterCommonBase.
setBaseFileName()
virtual void Arcane::IPostProcessorWriter::setBaseFileName (const String & filename) pure virtual
Positions the name of the file containing the outputs.
Not all writers support changing the file name.
Implemented in Arcane::PostProcessorWriterCommonBase.
setGroups()
virtual void Arcane::IPostProcessorWriter::setGroups (ItemGroupCollection groups) pure virtual
Positions the list of groups to output.
The collection passed as an argument is cloned.
Implemented in Arcane::PostProcessorWriterCommonBase.
References groups(), and setGroups().
Referenced by setGroups().
setMesh()
void Arcane::IPostProcessorWriter::setMesh (IMesh * mesh) virtual
Positions the mesh.
If not overloaded, this method does nothing.
Deprecated
This method is obsolete. It is no longer possible to change the mesh of a service implementing this interface. The choice of the mesh is made when creating the service via ServiceBuilder by passing the desired mesh as an argument.
Definition at line 272 of file InterfaceImpl.cc.
References ARCANE_FATAL, and Arcane::platform::getEnvironmentVariable().
Referenced by baseFileName().
setTimes()
virtual void Arcane::IPostProcessorWriter::setTimes (ConstArrayView< Real > times) pure virtual
Positions the list of times.
Implemented in Arcane::PostProcessorWriterCommonBase.
References setTimes(), and times().
Referenced by setTimes().
setVariables()
virtual void Arcane::IPostProcessorWriter::setVariables (VariableCollection variables) pure virtual
Positions the list of variables to output.
Implemented in Arcane::PostProcessorWriterCommonBase.
References setVariables(), and variables().
Referenced by setVariables().
times()
virtual ConstArrayView< Real > Arcane::IPostProcessorWriter::times () pure virtual
List of saved times.
Implemented in Arcane::PostProcessorWriterCommonBase.
References times().
Referenced by setTimes(), and times().
variables()
virtual VariableCollection Arcane::IPostProcessorWriter::variables () pure virtual
List of variables to save.
Implemented in Arcane::PostProcessorWriterCommonBase.
References variables().
Referenced by setVariables(), and variables().
The documentation for this class was generated from the following files:
IPostProcessorWriter.h
InterfaceImpl.cc
PostProcessorWriterBase.cc