Alien: Alien::VBlockMatrix Class Reference
Alien::VBlockMatrix Class Reference final
Public Member Functions
VBlockMatrix (const VBlock &block, const MatrixDistribution &dist)
VBlockMatrix (const VBlock &row_block, const VBlock &col_block, const MatrixDistribution &dist)
VBlockMatrix (Integer nrows, Integer ncols, Integer nrows_local, const VBlock &row_block, const VBlock &col_block, IMessagePassingMng *parallel_mng)
VBlockMatrix (Integer nrows, Integer ncols, const VBlock &row_block, const VBlock &col_block, IMessagePassingMng *parallel_mng)
VBlockMatrix (VBlockMatrix &&m)
VBlockMatrix & operator= (VBlockMatrix &&m)
VBlockMatrix (const VBlockMatrix &)=delete
VBlockMatrix & operator= (const VBlockMatrix &)=delete
void init (const VBlock &block, const MatrixDistribution &dist)
void free ()
void clear ()
void visit (ICopyOnWriteMatrix &) const
Visit method.
const MatrixDistribution & distribution () const
const ISpace & rowSpace () const
Get row space associated to the matrix.
const ISpace & colSpace () const
Get col space associated to the matrix.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
const VBlock & vblock () const
const VBlock & rowBlock () const
const VBlock & colBlock () const
MultiMatrixImpl * impl ()
Get the multimatrix implementation.
const MultiMatrixImpl * impl () const
Get the multimatrix implementation.
Private Attributes
std::shared_ptr< MultiMatrixImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from Alien::IMatrix
IMatrix ()
Constructor.
Detailed Description
Definition at line 38 of file VBlockMatrix.h.
Constructor & Destructor Documentation
VBlockMatrix() [1/6]
Alien::VBlockMatrix::VBlockMatrix ()
Definition at line 33 of file VBlockMatrix.cc.
VBlockMatrix() [2/6]
Alien::VBlockMatrix::VBlockMatrix (const VBlock & block, const MatrixDistribution & dist)
Definition at line 40 of file VBlockMatrix.cc.
VBlockMatrix() [3/6]
Alien::VBlockMatrix::VBlockMatrix (const VBlock & row_block, const VBlock & col_block, const MatrixDistribution & dist)
Definition at line 49 of file VBlockMatrix.cc.
VBlockMatrix() [4/6]
Alien::VBlockMatrix::VBlockMatrix (Integer nrows, Integer ncols, Integer nrows_local, const VBlock & row_block, const VBlock & col_block, IMessagePassingMng * parallel_mng)
Definition at line 60 of file VBlockMatrix.cc.
VBlockMatrix() [5/6]
Alien::VBlockMatrix::VBlockMatrix (Integer nrows, Integer ncols, const VBlock & row_block, const VBlock & col_block, IMessagePassingMng * parallel_mng)
Definition at line 73 of file VBlockMatrix.cc.
VBlockMatrix() [6/6]
Alien::VBlockMatrix::VBlockMatrix (VBlockMatrix && m)
Definition at line 85 of file VBlockMatrix.cc.
~VBlockMatrix()
Alien::VBlockMatrix::~VBlockMatrix () inline
Definition at line 56 of file VBlockMatrix.h.
Member Function Documentation
clear()
void Alien::VBlockMatrix::clear ()
Definition at line 116 of file VBlockMatrix.cc.
colBlock()
const VBlock & Alien::VBlockMatrix::colBlock () const
Definition at line 195 of file VBlockMatrix.cc.
colSpace()
const ISpace & Alien::VBlockMatrix::colSpace () const virtual
Get col space associated to the matrix.
Returns
The col space
Implements Alien::IMatrix.
Definition at line 147 of file VBlockMatrix.cc.
References colSpace().
Referenced by colSpace().
distribution()
const MatrixDistribution & Alien::VBlockMatrix::distribution () const
Definition at line 131 of file VBlockMatrix.cc.
free()
void Alien::VBlockMatrix::free ()
Definition at line 109 of file VBlockMatrix.cc.
hasUserFeature()
bool Alien::VBlockMatrix::hasUserFeature (String feature) const
Definition at line 161 of file VBlockMatrix.cc.
impl() [1/2]
MultiMatrixImpl * Alien::VBlockMatrix::impl () virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 208 of file VBlockMatrix.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiMatrixImpl * Alien::VBlockMatrix::impl () const virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 223 of file VBlockMatrix.cc.
References impl().
init()
void Alien::VBlockMatrix::init (const VBlock & block, const MatrixDistribution & dist)
Definition at line 100 of file VBlockMatrix.cc.
operator=()
VBlockMatrix & Alien::VBlockMatrix::operator= (VBlockMatrix && m)
Definition at line 92 of file VBlockMatrix.cc.
rowBlock()
const VBlock & Alien::VBlockMatrix::rowBlock () const
Definition at line 182 of file VBlockMatrix.cc.
rowSpace()
const ISpace & Alien::VBlockMatrix::rowSpace () const virtual
Get row space associated to the matrix.
Returns
The row space
Implements Alien::IMatrix.
Definition at line 139 of file VBlockMatrix.cc.
References rowSpace().
Referenced by rowSpace().
setUserFeature()
void Alien::VBlockMatrix::setUserFeature (String feature)
Definition at line 154 of file VBlockMatrix.cc.
vblock()
const VBlock & Alien::VBlockMatrix::vblock () const
Definition at line 169 of file VBlockMatrix.cc.
visit()
void Alien::VBlockMatrix::visit (ICopyOnWriteMatrix &) const virtual
Visit method.
Implements Alien::IMatrix.
Definition at line 123 of file VBlockMatrix.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiMatrixImpl> Alien::VBlockMatrix::m_impl private
Definition at line 93 of file VBlockMatrix.h.
The documentation for this class was generated from the following files:
VBlockMatrix.h
VBlockMatrix.cc