Alien: Alien::CompositeKernel::Space Class Reference
Alien::CompositeKernel::Space Class Reference
Classes
struct Internal
Public Member Functions
Space (const Space &)
Space (Space &&)
Space & operator= (const Space &src)
Space & operator= (Space &&)
bool operator== (const ISpace &space) const
Comparison operator.
bool operator!= (const ISpace &space) const
Comparison operator.
Integer size () const
Get space size.
const String & name () const
Get space name.
void setField (String label, const UniqueArray< Integer > &indices)
Integer nbField () const
Get the number of fields.
String fieldLabel (Integer i) const
const UniqueArray< Integer > & field (Integer i) const
const UniqueArray< Integer > & field (String label) const
std::shared_ptr< ISpace > clone () const
Clone this object.
void resizeSubSpace (Integer size)
std::shared_ptr< ISpace > & operator[] (Integer i)
const std::shared_ptr< ISpace > & operator[] (Integer i) const
Integer subSpaceSize () const
Public Member Functions inherited from Alien::ISpace
virtual ~ISpace ()
Free resources.
virtual void setField (Arccore::String label, const Arccore::UniqueArray< Arccore::Integer > &indices)=0
Set label on matrix entries.
virtual Arccore::String fieldLabel (Arccore::Integer i) const =0
Get the label of the i-th field.
virtual const Arccore::UniqueArray< Arccore::Integer > & field (Arccore::Integer i) const =0
Get indices associated to the i-th field \para[in] i The requested field.
virtual const Arccore::UniqueArray< Arccore::Integer > & field (Arccore::String label) const =0
Get the indices associated to a label.
Private Attributes
std::shared_ptr< Internal > m_internal
Additional Inherited Members
Protected Member Functions inherited from Alien::ISpace
ISpace ()
Constructor.
Detailed Description
Definition at line 40 of file CompositeSpace.h.
Constructor & Destructor Documentation
Space() [1/3]
Alien::CompositeKernel::Space::Space ()
Definition at line 60 of file CompositeSpace.cc.
Space() [2/3]
Alien::CompositeKernel::Space::Space (const Space & space)
Definition at line 66 of file CompositeSpace.cc.
Space() [3/3]
Alien::CompositeKernel::Space::Space (Space && space)
Definition at line 73 of file CompositeSpace.cc.
Member Function Documentation
clone()
std::shared_ptr< ISpace > Alien::CompositeKernel::Space::clone () const virtual
Clone this object.
Returns
A clone of this object
Implements Alien::ISpace.
Definition at line 159 of file CompositeSpace.cc.
field() [1/2]
const UniqueArray< Integer > & Alien::CompositeKernel::Space::field (Integer i) const
Definition at line 271 of file Space.cc.
field() [2/2]
const UniqueArray< Integer > & Alien::CompositeKernel::Space::field (String label) const
Definition at line 262 of file Space.cc.
fieldLabel()
String Alien::CompositeKernel::Space::fieldLabel (Integer i) const
Definition at line 280 of file Space.cc.
name()
const String & Alien::CompositeKernel::Space::name () const virtual
Get space name.
Returns
The name of the space
Implements Alien::ISpace.
Definition at line 118 of file CompositeSpace.cc.
nbField()
Integer Alien::CompositeKernel::Space::nbField () const virtual
Get the number of fields.
Returns
The number of fields (labels)
Implements Alien::ISpace.
Definition at line 133 of file CompositeSpace.cc.
operator!=()
bool Alien::CompositeKernel::Space::operator!= (const ISpace & space) const virtual
Comparison operator.
Parameters
[in] Space related functions. The space to compare to
Returns
Wheteher the spaces are different
Implements Alien::ISpace.
Definition at line 114 of file CompositeSpace.cc.
References Alien::ISpace::ISpace(), and operator==().
operator=() [1/2]
Space & Alien::CompositeKernel::Space::operator= (const Space & src)
Definition at line 79 of file CompositeSpace.cc.
operator=() [2/2]
Space & Alien::CompositeKernel::Space::operator= (Space && src)
Definition at line 87 of file CompositeSpace.cc.
operator==()
bool Alien::CompositeKernel::Space::operator== (const ISpace & space) const virtual
Comparison operator.
Parameters
[in] Space related functions. The space to compare to
Returns
Wheteher the spaces are the same
Implements Alien::ISpace.
Definition at line 107 of file CompositeSpace.cc.
References Alien::ISpace::ISpace(), Alien::ISpace::name(), size(), and Alien::ISpace::size().
Referenced by operator!=().
operator[]() [1/2]
std::shared_ptr< ISpace > & Alien::CompositeKernel::Space::operator[] (Integer i)
Definition at line 172 of file CompositeSpace.cc.
operator[]() [2/2]
const std::shared_ptr< ISpace > & Alien::CompositeKernel::Space::operator[] (Integer i) const
Definition at line 180 of file CompositeSpace.cc.
resizeSubSpace()
void Alien::CompositeKernel::Space::resizeSubSpace (Integer size)
Definition at line 163 of file CompositeSpace.cc.
setField()
void Alien::CompositeKernel::Space::setField (String label, const UniqueArray< Integer > & indices)
Definition at line 122 of file CompositeSpace.cc.
size()
Integer Alien::CompositeKernel::Space::size () const virtual
Get space size.
Returns
The size of the space
Implements Alien::ISpace.
Definition at line 95 of file CompositeSpace.cc.
References size().
Referenced by operator==(), and size().
subSpaceSize()
Integer Alien::CompositeKernel::Space::subSpaceSize () const
Definition at line 188 of file CompositeSpace.cc.
Member Data Documentation
m_internal
std::shared_ptr<Internal> Alien::CompositeKernel::Space::m_internal private
Definition at line 82 of file CompositeSpace.h.
The documentation for this class was generated from the following files:
CompositeSpace.h
Space.cc
CompositeSpace.cc