Arcane: Arcane::ArccoreApplicationBuildInfo Class Reference
Arcane::ArccoreApplicationBuildInfo Class Reference
Information for initializing an application.
#include <arccore/common/ArccoreApplicationBuildInfo.h>
Public Member Functions
ArccoreApplicationBuildInfo (const ArccoreApplicationBuildInfo &rhs)
ArccoreApplicationBuildInfo & operator= (const ArccoreApplicationBuildInfo &rhs)
void setTaskImplementationService (const String &name)
void setTaskImplementationServices (const StringList &names)
StringList taskImplementationServices () const
void setThreadImplementationService (const String &name)
void setThreadImplementationServices (const StringList &names)
StringList threadImplementationServices () const
Int32 nbTaskThread () const
void setNbTaskThread (Integer v)
void addParameter (const String &name, const String &value)
void parseArgumentsAndSetDefaultsValues (const CommandLineArguments &args)
Parses the arguments in args.
virtual void setDefaultValues ()
virtual void setDefaultServices ()
Protected Attributes
ArccoreApplicationBuildInfoImpl * m_core = nullptr
Detailed Description
Information for initializing an application.
Definition at line 32 of file ArccoreApplicationBuildInfo.h.
Constructor & Destructor Documentation
ArccoreApplicationBuildInfo() [1/2]
Arcane::ArccoreApplicationBuildInfo::ArccoreApplicationBuildInfo ()
Definition at line 62 of file ArccoreApplicationBuildInfo.cc.
ArccoreApplicationBuildInfo() [2/2]
Arcane::ArccoreApplicationBuildInfo::ArccoreApplicationBuildInfo (const ArccoreApplicationBuildInfo & rhs)
Definition at line 68 of file ArccoreApplicationBuildInfo.cc.
~ArccoreApplicationBuildInfo()
Arcane::ArccoreApplicationBuildInfo::~ArccoreApplicationBuildInfo () virtual
Definition at line 84 of file ArccoreApplicationBuildInfo.cc.
Member Function Documentation
addParameter()
void Arcane::ArccoreApplicationBuildInfo::addParameter (const String & name, const String & value)
Definition at line 471 of file ApplicationBuildInfo.cc.
nbTaskThread()
Int32 Arcane::ArccoreApplicationBuildInfo::nbTaskThread () const
Definition at line 288 of file ApplicationBuildInfo.cc.
operator=()
ArccoreApplicationBuildInfo & Arcane::ArccoreApplicationBuildInfo::operator= (const ArccoreApplicationBuildInfo & rhs)
Definition at line 74 of file ArccoreApplicationBuildInfo.cc.
parseArgumentsAndSetDefaultsValues()
void Arcane::ArccoreApplicationBuildInfo::parseArgumentsAndSetDefaultsValues (const CommandLineArguments & args)
Parses the arguments in args.
Only arguments of the style -A,x=b,y=c are retrieved. The setDefaultValues() method is called at the end of this method.
Definition at line 480 of file ApplicationBuildInfo.cc.
References Arcane::CollectionBase::count(), and Arcane::CommandLineArguments::fillParameters().
Referenced by Arcane::ApplicationBuildInfo::parseArguments().
setDefaultServices()
void Arcane::ArccoreApplicationBuildInfo::setDefaultServices () virtual
Definition at line 194 of file ApplicationBuildInfo.cc.
setDefaultValues()
void Arcane::ArccoreApplicationBuildInfo::setDefaultValues () virtual
Definition at line 96 of file ArccoreApplicationBuildInfo.cc.
setNbTaskThread()
void Arcane::ArccoreApplicationBuildInfo::setNbTaskThread (Integer v)
Definition at line 297 of file ApplicationBuildInfo.cc.
setTaskImplementationService()
void Arcane::ArccoreApplicationBuildInfo::setTaskImplementationService (const String & name)
Definition at line 246 of file ApplicationBuildInfo.cc.
setTaskImplementationServices()
void Arcane::ArccoreApplicationBuildInfo::setTaskImplementationServices (const StringList & names)
Definition at line 253 of file ApplicationBuildInfo.cc.
setThreadImplementationService()
void Arcane::ArccoreApplicationBuildInfo::setThreadImplementationService (const String & name)
Definition at line 267 of file ApplicationBuildInfo.cc.
setThreadImplementationServices()
void Arcane::ArccoreApplicationBuildInfo::setThreadImplementationServices (const StringList & names)
Definition at line 274 of file ApplicationBuildInfo.cc.
taskImplementationServices()
StringList Arcane::ArccoreApplicationBuildInfo::taskImplementationServices () const
Definition at line 258 of file ApplicationBuildInfo.cc.
threadImplementationServices()
StringList Arcane::ArccoreApplicationBuildInfo::threadImplementationServices () const
Definition at line 279 of file ApplicationBuildInfo.cc.
Member Data Documentation
m_core
ArccoreApplicationBuildInfoImpl* Arcane::ArccoreApplicationBuildInfo::m_core = nullptr protected
Definition at line 70 of file ArccoreApplicationBuildInfo.h.
The documentation for this class was generated from the following files:
ArccoreApplicationBuildInfo.h
ApplicationBuildInfo.cc
ArccoreApplicationBuildInfo.cc