Arcane: Arcane::Materials::MeshEnvironment::InternalApi Class Reference
Arcane::Materials::MeshEnvironment::InternalApi Class Reference
Public Member Functions
InternalApi (MeshEnvironment *env)
MeshMaterialVariableIndexer * variableIndexer () const override
Indexer to access partial variables.
ConstituentItemLocalIdListView constituentItemListView () const override
View of the constituent cells.
Int32 variableIndexerIndex () const override
Index to access partial variables.
Ref< IConstituentItemVectorImpl > createItemVectorImpl () const override
Create an instance of the 'ConstituentItemVectorImpl' implementation.
Ref< IConstituentItemVectorImpl > createItemVectorImpl (ComponentItemVectorView rhs) const override
Create an instance of the 'ConstituentItemVectorImpl' implementation.
Private Attributes
MeshEnvironment * m_environment
Detailed Description
Definition at line 56 of file MeshEnvironment.h.
Constructor & Destructor Documentation
InternalApi()
Arcane::Materials::MeshEnvironment::InternalApi::InternalApi (MeshEnvironment * env) inline
Definition at line 61 of file MeshEnvironment.h.
Member Function Documentation
constituentItemListView()
ConstituentItemLocalIdListView Arcane::Materials::MeshEnvironment::InternalApi::constituentItemListView () const inline override virtual
View of the constituent cells.
Implements Arcane::Materials::IMeshComponentInternal.
Definition at line 71 of file MeshEnvironment.h.
createItemVectorImpl() [1/2]
Ref< IConstituentItemVectorImpl > Arcane::Materials::MeshEnvironment::InternalApi::createItemVectorImpl () const override virtual
Create an instance of the 'ConstituentItemVectorImpl' implementation.
Implements Arcane::Materials::IMeshComponentInternal.
Definition at line 657 of file MeshEnvironment.cc.
References Arcane::makeRef().
createItemVectorImpl() [2/2]
Ref< IConstituentItemVectorImpl > Arcane::Materials::MeshEnvironment::InternalApi::createItemVectorImpl (ComponentItemVectorView rhs) const override virtual
Create an instance of the 'ConstituentItemVectorImpl' implementation.
Implements Arcane::Materials::IMeshComponentInternal.
Definition at line 667 of file MeshEnvironment.cc.
References Arcane::makeRef().
variableIndexer()
MeshMaterialVariableIndexer * Arcane::Materials::MeshEnvironment::InternalApi::variableIndexer () const inline override virtual
Indexer to access partial variables.
Implements Arcane::Materials::IMeshComponentInternal.
Definition at line 67 of file MeshEnvironment.h.
Referenced by variableIndexerIndex().
variableIndexerIndex()
Int32 Arcane::Materials::MeshEnvironment::InternalApi::variableIndexerIndex () const override virtual
Index to access partial variables.
Implements Arcane::Materials::IMeshComponentInternal.
Definition at line 648 of file MeshEnvironment.cc.
References variableIndexer().
Member Data Documentation
m_environment
MeshEnvironment* Arcane::Materials::MeshEnvironment::InternalApi::m_environment private
Definition at line 81 of file MeshEnvironment.h.
The documentation for this class was generated from the following files:
MeshEnvironment.h
MeshEnvironment.cc