Arcane: Arcane::MessagePassing::internal::RequestListBase Class Reference
Arcane::MessagePassing::internal::RequestListBase Class Reference abstract
Public Member Functions
void add (Request r) override
Adds the request r to the list of requests.
void add (Span< Request > r) override
Adds the list of requests rlist to the list of requests.
Int32 wait (eWaitType wait_type) final
Waits for or tests the completion of one or more requests.
Int32 size () const override
Number of requests.
void clear () final
Removes all requests from the list.
void removeDoneRequests () override
Removes completed requests from the list.
bool isRequestDone (Int32 index) const override
Indicates if the request is finished since the last call to wait().
Request request (Int32 index) const override
The index-th request in the list.
ConstArrayView< Int32 > doneRequestIndexes () const final
Indices in the request array of requests completed during the last call to wait().
Protected Member Functions
virtual void _add (const Request &r)
virtual void _add (Span< Request > rlist)
virtual void _removeRequestAtIndex (Integer pos)
virtual void _wait (eWaitType wait_type)=0
Performs the wait or test.
ArrayView< Request > _requests ()
ArrayView< bool > _requestsDone ()
Detailed Description
Definition at line 34 of file RequestListBase.h.
Member Function Documentation
_add() [1/2]
virtual void Arcane::MessagePassing::internal::RequestListBase::_add (const Request & r) inline protected virtual
Definition at line 55 of file RequestListBase.h.
_add() [2/2]
virtual void Arcane::MessagePassing::internal::RequestListBase::_add (Span< Request > rlist) inline protected virtual
Definition at line 60 of file RequestListBase.h.
_removeRequestAtIndex()
virtual void Arcane::MessagePassing::internal::RequestListBase::_removeRequestAtIndex (Integer pos) inline protected virtual
Definition at line 65 of file RequestListBase.h.
_requests()
ArrayView< Request > Arcane::MessagePassing::internal::RequestListBase::_requests () inline protected
Definition at line 81 of file RequestListBase.h.
_requestsDone()
ArrayView< bool > Arcane::MessagePassing::internal::RequestListBase::_requestsDone () inline protected
Definition at line 82 of file RequestListBase.h.
_wait()
virtual void Arcane::MessagePassing::internal::RequestListBase::_wait (eWaitType wait_type) protected pure virtual
Performs the wait or test.
The implementation must fill _requestsDone() with the value true for every completed request unless wait_type equals WaitAll.
Referenced by wait().
add() [1/2]
void Arcane::MessagePassing::internal::RequestListBase::add (Request r) inline override virtual
Adds the request r to the list of requests.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 43 of file RequestListBase.h.
add() [2/2]
void Arcane::MessagePassing::internal::RequestListBase::add (Span< Request > rlist) inline override virtual
Adds the list of requests rlist to the list of requests.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 44 of file RequestListBase.h.
clear()
void Arcane::MessagePassing::internal::RequestListBase::clear () final virtual
Removes all requests from the list.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 26 of file RequestListBase.cc.
doneRequestIndexes()
ConstArrayView< Int32 > Arcane::MessagePassing::internal::RequestListBase::doneRequestIndexes () const final virtual
Indices in the request array of requests completed during the last call to wait().
Implements Arcane::MessagePassing::IRequestList.
Definition at line 54 of file RequestListBase.cc.
isRequestDone()
bool Arcane::MessagePassing::internal::RequestListBase::isRequestDone (Int32 index) const inline override virtual
Indicates if the request is finished since the last call to wait().
Implements Arcane::MessagePassing::IRequestList.
Definition at line 49 of file RequestListBase.h.
References isRequestDone().
Referenced by isRequestDone().
removeDoneRequests()
void Arcane::MessagePassing::internal::RequestListBase::removeDoneRequests () override virtual
Removes completed requests from the list.
All requests for which isRequestDone() is true are removed from the list of requests. After calling this method, it is considered that there are no more completed requests. Consequently, doneRequestIndexes() will be empty and isRequestDone() will always return false.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 37 of file RequestListBase.cc.
request()
Request Arcane::MessagePassing::internal::RequestListBase::request (Int32 index) const inline override virtual
The index-th request in the list.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 50 of file RequestListBase.h.
size()
Int32 Arcane::MessagePassing::internal::RequestListBase::size () const inline override virtual
Number of requests.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 46 of file RequestListBase.h.
Referenced by wait().
wait()
Int32 Arcane::MessagePassing::internal::RequestListBase::wait (eWaitType wait_type) final virtual
Waits for or tests the completion of one or more requests.
It returns the number of newly completed requests. It is then possible to test if a request is finished via the isRequestDone() method or to retrieve the indices of the completed requests via doneRequestIndexes().
Note
Requests completed after a call to wait() remain in the list of requests. The method removeDoneRequests() must be called if you wish to remove them.
Implements Arcane::MessagePassing::IRequestList.
Definition at line 63 of file RequestListBase.cc.
References _wait(), and size().
The documentation for this class was generated from the following files:
RequestListBase.h
RequestListBase.cc