Alien: Alien::VBlockVector Class Reference
Alien::VBlockVector Class Reference final
Public Member Functions
VBlockVector (const VBlock &block, const VectorDistribution &dist)
VBlockVector (Integer nrows, Integer nrows_local, const VBlock &block, IMessagePassingMng *parallel_mng)
VBlockVector (Integer nrows, const VBlock &block, IMessagePassingMng *parallel_mng)
VBlockVector (VBlockVector &&vector)
VBlockVector & operator= (VBlockVector &&vector)
VBlockVector (const VBlockVector &)=delete
VBlockVector & operator= (const VBlockVector &)=delete
void init (const VBlock &block, const VectorDistribution &dist)
void free ()
void clear ()
void visit (ICopyOnWriteVector &) const
Visit method.
const VectorDistribution & distribution () const
const ISpace & space () const
Get the space associated to the vector.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
const VBlock & vblock () const
MultiVectorImpl * impl ()
Get the multivector implementation.
const MultiVectorImpl * impl () const
Get the multivector implementation.
Private Attributes
std::shared_ptr< MultiVectorImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from Alien::IVector
IVector ()
Constructor.
Detailed Description
Definition at line 37 of file VBlockVector.h.
Constructor & Destructor Documentation
VBlockVector() [1/5]
Alien::VBlockVector::VBlockVector ()
Definition at line 33 of file VBlockVector.cc.
VBlockVector() [2/5]
Alien::VBlockVector::VBlockVector (const VBlock & block, const VectorDistribution & dist)
Definition at line 40 of file VBlockVector.cc.
VBlockVector() [3/5]
Alien::VBlockVector::VBlockVector (Integer nrows, Integer nrows_local, const VBlock & block, IMessagePassingMng * parallel_mng)
Definition at line 48 of file VBlockVector.cc.
VBlockVector() [4/5]
Alien::VBlockVector::VBlockVector (Integer nrows, const VBlock & block, IMessagePassingMng * parallel_mng)
Definition at line 59 of file VBlockVector.cc.
VBlockVector() [5/5]
Alien::VBlockVector::VBlockVector (VBlockVector && vector)
Definition at line 69 of file VBlockVector.cc.
~VBlockVector()
Alien::VBlockVector::~VBlockVector () inline
Definition at line 51 of file VBlockVector.h.
Member Function Documentation
clear()
void Alien::VBlockVector::clear ()
Definition at line 99 of file VBlockVector.cc.
distribution()
const VectorDistribution & Alien::VBlockVector::distribution () const
Definition at line 122 of file VBlockVector.cc.
free()
void Alien::VBlockVector::free ()
Definition at line 92 of file VBlockVector.cc.
hasUserFeature()
bool Alien::VBlockVector::hasUserFeature (String feature) const
Definition at line 136 of file VBlockVector.cc.
impl() [1/2]
MultiVectorImpl * Alien::VBlockVector::impl () virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 157 of file VBlockVector.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiVectorImpl * Alien::VBlockVector::impl () const virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 172 of file VBlockVector.cc.
References impl().
init()
void Alien::VBlockVector::init (const VBlock & block, const VectorDistribution & dist)
Definition at line 84 of file VBlockVector.cc.
operator=()
VBlockVector & Alien::VBlockVector::operator= (VBlockVector && vector)
Definition at line 76 of file VBlockVector.cc.
setUserFeature()
void Alien::VBlockVector::setUserFeature (String feature)
Definition at line 129 of file VBlockVector.cc.
space()
const ISpace & Alien::VBlockVector::space () const virtual
Get the space associated to the vector.
Returns
The space
Implements Alien::IVector.
Definition at line 107 of file VBlockVector.cc.
References space().
Referenced by space().
vblock()
const VBlock & Alien::VBlockVector::vblock () const
Definition at line 144 of file VBlockVector.cc.
visit()
void Alien::VBlockVector::visit (ICopyOnWriteVector &) const virtual
Visit method.
Implements Alien::IVector.
Definition at line 114 of file VBlockVector.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiVectorImpl> Alien::VBlockVector::m_impl private
Definition at line 84 of file VBlockVector.h.
The documentation for this class was generated from the following files:
VBlockVector.h
VBlockVector.cc