Arcane: Arcane::ConstArrayView< T > Class Template Reference
Arcane::ConstArrayView< T > Class Template Reference
Collection
Constant view of an array of type T.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/base/arccore/base/ArrayView.h>
Public Types
using ThatClass = ConstArrayView<T>
typedef T value_type
Type of the array elements.
typedef const value_type * const_pointer
Constant pointer type of an array element.
typedef ArrayIterator< const_pointer > const_iterator
Constant iterator type over an array element.
typedef const value_type & const_reference
Constant reference type of an array element.
typedef Integer size_type
Type indexing the array.
typedef std::ptrdiff_t difference_type
Type of a distance between array iterator elements.
using const_value_type = typename std::add_const_t<value_type>
typedef ConstIterT< ConstArrayView< T > > const_iter
Type of a constant iterator over the entire array.
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
constexpr ConstArrayView () noexcept
Constructs an empty array.
constexpr ConstArrayView (Integer s, const_pointer ptr) noexcept
Constructs an array with s elements.
ConstArrayView (const ConstArrayView< T > &from)=default
Copy constructor.
constexpr ConstArrayView (const ArrayView< T > &from) noexcept
Copy constructor.
template<std::size_t N, typename X, typename = std::enable_if_t<std::is_same_v<X, const_value_type>>>
constexpr ConstArrayView (const std::array< X, N > &v)
Creation from a std::array.
ConstArrayView< T > & operator= (const ConstArrayView< T > &from)=default
Copy assignment operator.
constexpr ConstArrayView< T > & operator= (const ArrayView< T > &from)
Copy assignment operator.
template<std::size_t N, typename X, typename = std::enable_if_t<std::is_same_v<X, const_value_type>>>
constexpr ConstArrayView< T > & operator= (const std::array< X, N > &from)
Copy assignment operator.
constexpr ConstArrayView< T > subView (Integer abegin, Integer asize) const noexcept
Sub-view (constant) starting from element abegin and containing asize elements.
constexpr ThatClass subPart (Integer abegin, Integer asize) const noexcept
Sub-view (constant) starting from element abegin and containing asize elements.
constexpr ConstArrayView< T > subConstView (Integer abegin, Integer asize) const noexcept
Sub-view (constant) starting from element abegin and containing asize elements.
constexpr ConstArrayView< T > subViewInterval (Integer index, Integer nb_interval) const
Sub-view corresponding to the interval index over nb_interval.
constexpr ThatClass subPartInterval (Integer index, Integer nb_interval) const
Sub-view corresponding to the interval index over nb_interval.
constexpr const_pointer ptrAt (Integer index) const
Address of the index-th element.
constexpr const_reference operator[] (Integer i) const
i-th element of the array.
constexpr const_reference operator() (Integer i) const
i-th element of the array.
constexpr const_reference item (Integer i) const
i-th element of the array.
constexpr Integer size () const noexcept
Number of elements in the array.
constexpr Integer length () const noexcept
Number of elements in the array.
constexpr const_iterator begin () const noexcept
Iterator over the first element of the array.
constexpr const_iterator end () const noexcept
Iterator over the first element after the end of the array.
constexpr const_reverse_iterator rbegin () const noexcept
Reverse iterator over the first element of the array.
constexpr const_reverse_iterator rend () const noexcept
Reverse iterator over the first element after the end of the array.
constexpr bool empty () const noexcept
true if the array is empty (size()==0)
bool contains (const_reference v) const
true if the array contains the element of value v
void setArray (const ConstArrayView< T > &v) noexcept
constexpr const_pointer unguardedBasePointer () const noexcept
Pointer to the allocated memory.
constexpr const_pointer data () const noexcept
Pointer to the allocated memory.
ArrayRange< const_pointer > range () const
Iteration range from the first to the last element.
Static Public Member Functions
static constexpr ThatClass create (const_pointer ptr, Integer asize) noexcept
Static Private Member Functions
static constexpr Integer _min (Integer a, Integer b) noexcept
Private Attributes
Integer m_size
Number of elements.
const_pointer m_ptr
Pointer to the start of the array.
Friends
class Span< T >
class Span< const T >
class SmallSpan< T >
class SmallSpan< const T >
bool operator== (const ConstArrayView< T > &rhs, const ConstArrayView< T > &lhs)
bool operator!= (const ConstArrayView< T > &rhs, const ConstArrayView< T > &lhs)
std::ostream & operator<< (std::ostream &o, const ConstArrayView< T > &val)
Detailed Description
template<class T>
class Arcane::ConstArrayView< T >
Constant view of an array of type T.
This class functions the same way as ArrayView with the only difference being that the elements of the array cannot be modified.
Definition at line 549 of file arccore/src/base/arccore/base/ArrayView.h.
Member Typedef Documentation
const_iter
template<class T> typedef ConstIterT<ConstArrayView<T> > Arcane::ConstArrayView< T >::const_iter
Type of a constant iterator over the entire array.
Definition at line 576 of file arccore/src/base/arccore/base/ArrayView.h.
const_iterator
template<class T> typedef ArrayIterator<const_pointer> Arcane::ConstArrayView< T >::const_iterator
Constant iterator type over an array element.
Definition at line 565 of file arccore/src/base/arccore/base/ArrayView.h.
const_pointer
template<class T> typedef const value_type* Arcane::ConstArrayView< T >::const_pointer
Constant pointer type of an array element.
Definition at line 563 of file arccore/src/base/arccore/base/ArrayView.h.
const_reference
template<class T> typedef const value_type& Arcane::ConstArrayView< T >::const_reference
Constant reference type of an array element.
Definition at line 567 of file arccore/src/base/arccore/base/ArrayView.h.
const_reverse_iterator
template<class T> typedef std::reverse_iterator<const_iterator> Arcane::ConstArrayView< T >::const_reverse_iterator
Definition at line 578 of file arccore/src/base/arccore/base/ArrayView.h.
const_value_type
template<class T> using Arcane::ConstArrayView< T >::const_value_type = typename std::add_const_t<value_type>
Definition at line 573 of file arccore/src/base/arccore/base/ArrayView.h.
difference_type
template<class T> typedef std::ptrdiff_t Arcane::ConstArrayView< T >::difference_type
Type of a distance between array iterator elements.
Definition at line 571 of file arccore/src/base/arccore/base/ArrayView.h.
size_type
template<class T> typedef Integer Arcane::ConstArrayView< T >::size_type
Type indexing the array.
Definition at line 569 of file arccore/src/base/arccore/base/ArrayView.h.
ThatClass
template<class T> using Arcane::ConstArrayView< T >::ThatClass = ConstArrayView<T>
Definition at line 558 of file arccore/src/base/arccore/base/ArrayView.h.
value_type
template<class T> typedef T Arcane::ConstArrayView< T >::value_type
Type of the array elements.
Definition at line 561 of file arccore/src/base/arccore/base/ArrayView.h.
Constructor & Destructor Documentation
ConstArrayView() [1/4]
template<class T> Arcane::ConstArrayView< T >::ConstArrayView () inline constexpr noexcept
Constructs an empty array.
Definition at line 583 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::ConstArrayView< Type >::subView().
ConstArrayView() [2/4]
template<class T> Arcane::ConstArrayView< T >::ConstArrayView (Integer s, const_pointer ptr) inline constexpr noexcept
Constructs an array with s elements.
Definition at line 588 of file arccore/src/base/arccore/base/ArrayView.h.
ConstArrayView() [3/4]
template<class T> Arcane::ConstArrayView< T >::ConstArrayView (const ArrayView< T > & from) inline constexpr noexcept
Copy constructor.
Warning
Only the pointer is copied. No memory copy is performed.
Definition at line 598 of file arccore/src/base/arccore/base/ArrayView.h.
ConstArrayView() [4/4]
template<class T> template<std::size_t N, typename X, typename = std::enable_if_t<std::is_same_v<X, const_value_type>>> Arcane::ConstArrayView< T >::ConstArrayView (const std::array< X, N > & v) inline constexpr
Creation from a std::array.
Definition at line 605 of file arccore/src/base/arccore/base/ArrayView.h.
Member Function Documentation
_min()
template<class T> constexpr Integer Arcane::ConstArrayView< T >::_min (Integer a, Integer b) inline static constexpr private noexcept
Definition at line 819 of file arccore/src/base/arccore/base/ArrayView.h.
begin()
template<class T> const_iterator Arcane::ConstArrayView< T >::begin () const inline constexpr noexcept
Iterator over the first element of the array.
Definition at line 743 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::ConstArrayView< Type >::rend().
contains()
template<class T> bool Arcane::ConstArrayView< T >::contains (const_reference v) const inline
true if the array contains the element of value v
Definition at line 753 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::SimpleTableInternalMng::addColumns(), and Arcane::SimpleTableInternalMng::addRows().
create()
template<class T> constexpr ThatClass Arcane::ConstArrayView< T >::create (const_pointer ptr, Integer asize) inline static constexpr noexcept
Constructs a view over a memory region starting at ptr and containing asize elements.
Definition at line 640 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::CartesianMeshAMRPatchMng::createSubLevel(), and Arcane::CartesianMeshAMRPatchMng::refine().
data()
template<class T> const_pointer Arcane::ConstArrayView< T >::data () const inline constexpr noexcept
Pointer to the allocated memory.
Warning
Accesses via the returned pointer cannot be verified by Arcane, unlike accesses via operator[](): no overflow check is possible, even in verification mode.
Definition at line 785 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::DumpWEnsight7::_saveGroup(), Arcane::DumpWEnsight7::_writeRealValT(), Arcane::math::add(), Arcane::Bzip2DeflateService::compress(), Arcane::LZ4DeflateService::compress(), Arcane::UdunitsPhysicalUnitConverter::convert(), Arcane::StringUtils::convertToStdWString(), Arcane::Bzip2DeflateService::decompress(), Arcane::LZ4DeflateService::decompress(), Arcane::Process::execute(), Arcane::UnstructuredMeshUtilities::getFacesLocalIdFromConnectivity(), Arcane::GetVariablesValuesParallelOperation::getVariableValues(), Arcane::UnstructuredMeshUtilities::localIdsFromConnectivity(), Arcane::math::mult(), Arcane::IOMng::parseXmlString(), Arcane::mesh::DynamicMeshKindInfos::removeMany(), Arcane::math::sub(), and Arcane::dom::LibXml2_SchemaValidator::validate().
empty()
template<class T> bool Arcane::ConstArrayView< T >::empty () const inline constexpr noexcept
true if the array is empty (size()==0)
Definition at line 751 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::mesh::ItemFamily::_compactFromParentFamily(), Arcane::MshMeshWriter::_writeElements(), Arcane::mesh::DynamicMesh::allocateCells(), Arcane::ItemGroupInternal::checkIsContiguous(), Arcane::MessagePassing::HybridParallelMng::createSubParallelMngRef(), Arcane::MessagePassing::SharedMemoryParallelMng::createSubParallelMngRef(), Arcane::ItemGroupPartialVariableObserver::executeCompact(), Arcane::ItemGroupPartialVariableObserver::executeExtend(), Arcane::ItemGroupPartialVariableObserver::executeReduce(), Arcane::MultiArray2< Pointer >::resize(), and Arcane::dom::LibXml2_SchemaValidator::validate().
end()
template<class T> const_iterator Arcane::ConstArrayView< T >::end () const inline constexpr noexcept
Iterator over the first element after the end of the array.
Definition at line 745 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::ConstArrayView< Type >::rbegin().
item()
template<class T> const_reference Arcane::ConstArrayView< T >::item (Integer i) const inline constexpr
i-th element of the array.
In check mode, checks for overflows.
Definition at line 732 of file arccore/src/base/arccore/base/ArrayView.h.
length()
template<class T> Integer Arcane::ConstArrayView< T >::length () const inline constexpr noexcept
Number of elements in the array.
Definition at line 741 of file arccore/src/base/arccore/base/ArrayView.h.
operator()()
template<class T> const_reference Arcane::ConstArrayView< T >::operator() (Integer i) const inline constexpr
i-th element of the array.
In check mode, checks for overflows.
Definition at line 721 of file arccore/src/base/arccore/base/ArrayView.h.
operator=() [1/3]
template<class T> ConstArrayView< T > & Arcane::ConstArrayView< T >::operator= (const ArrayView< T > & from) inline constexpr
Copy assignment operator.
Warning
Only the pointer is copied. No memory copy is performed.
Definition at line 620 of file arccore/src/base/arccore/base/ArrayView.h.
operator=() [2/3]
template<class T> ConstArrayView< T > & Arcane::ConstArrayView< T >::operator= (const ConstArrayView< T > & from) default
Copy assignment operator.
Warning
Only the pointer is copied. No memory copy is performed.
operator=() [3/3]
template<class T> template<std::size_t N, typename X, typename = std::enable_if_t<std::is_same_v<X, const_value_type>>> ConstArrayView< T > & Arcane::ConstArrayView< T >::operator= (const std::array< X, N > & from) inline constexpr
Copy assignment operator.
Definition at line 629 of file arccore/src/base/arccore/base/ArrayView.h.
operator[]()
template<class T> const_reference Arcane::ConstArrayView< T >::operator[] (Integer i) const inline constexpr
i-th element of the array.
In check mode, checks for overflows.
Definition at line 710 of file arccore/src/base/arccore/base/ArrayView.h.
ptrAt()
template<class T> const_pointer Arcane::ConstArrayView< T >::ptrAt (Integer index) const inline constexpr
Address of the index-th element.
Definition at line 699 of file arccore/src/base/arccore/base/ArrayView.h.
range()
template<class T> ArrayRange< const_pointer > Arcane::ConstArrayView< T >::range () const inline
Iteration range from the first to the last element.
Definition at line 789 of file arccore/src/base/arccore/base/ArrayView.h.
rbegin()
template<class T> const_reverse_iterator Arcane::ConstArrayView< T >::rbegin () const inline constexpr noexcept
Reverse iterator over the first element of the array.
Definition at line 747 of file arccore/src/base/arccore/base/ArrayView.h.
rend()
template<class T> const_reverse_iterator Arcane::ConstArrayView< T >::rend () const inline constexpr noexcept
Reverse iterator over the first element after the end of the array.
Definition at line 749 of file arccore/src/base/arccore/base/ArrayView.h.
setArray()
template<class T> void Arcane::ConstArrayView< T >::setArray (const ConstArrayView< T > & v) inline noexcept
Definition at line 761 of file arccore/src/base/arccore/base/ArrayView.h.
size()
template<class T> Integer Arcane::ConstArrayView< T >::size () const inline constexpr noexcept
Number of elements in the array.
Definition at line 739 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::SimpleMeshGenerator::_addCell(), Arcane::TimeHistoryMngInternal::_addHistoryValue(), Arcane::mesh::DoFFamily::_addItems(), Arcane::MEDMeshReader::_broadcastGroups(), Arcane::MetisWrapper::_callMetisWith2Processors(), Arcane::Materials::MeshComponentData::_changeLocalIdsForInternalList(), Arcane::mesh::OneMeshItemAdder::_checkSameItemCoherency(), Arcane::mesh::ItemFamilyVariableSerializer::_checkSerialization(), Arcane::mesh::ItemFamily::_compactFromParentFamily(), Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::Materials::MeshEnvironment::_computeMaterialIndexesMonoMat(), Arcane::mesh::FaceUniqueIdBuilder2::_computeParallel(), Arcane::ArcaneLoadBalanceModule::_computeWeights(), Arcane::Hdf5VariableReaderHelper2::_createCorrespondance(), Arcane::VtkMeshIOService::_createFaceGroup(), Arcane::VariableSynchronizerComputeList::_createList(), Arcane::AMRPatchPositionSignatureCut::_cutDim(), Arcane::mesh::FaceUniqueIdBuilder::_exchangeData(), Arcane::mesh::Parallel3EdgeUniqueIdBuilder::_exchangeData(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::SimpleGridMeshPartitioner::_findPart(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::VariableIOWriterMng::_generateMeshesMetaData(), Arcane::ArcaneInitialPartitioner::_mergeConstraints(), Arcane::mesh::DynamicMesh::_multipleExchangeItems(), Arcane::VtkMeshIOService::_readData(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::DumpWEnsight7::_saveGroup(), Arcane::DumpWEnsight7::_saveVariableOnGroup(), Arcane::mesh::ItemFamilyVariableSerializer::_serializePartialVariable(), Arcane::MshParallelMeshReader::_setNodesCoordinates(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::ItemFamily::_updateItemsSharedFlag(), Arcane::CheckpointMng::_writeCheckpointInfoFile(), Arcane::MshMeshWriter::_writeElements(), Arcane::DumpWEnsight7::_writeRealValT(), Arcane::math::add(), Arcane::SimpleTableInternalMng::addAverageColumn(), Arcane::mesh::DynamicMeshInternal::addCell(), Arcane::SimpleTableInternalMng::addColumns(), Arcane::mesh::DoFFamily::addDoFs(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::mesh::DynamicMeshIncrementalBuilder::addEdges2(), Arcane::SimpleTableInternalMng::addElementsInColumn(), Arcane::SimpleTableInternalMng::addElementsInRow(), Arcane::ItemTypeInfoBuilder::addFaceGeneric(), Arcane::mesh::DynamicMeshIncrementalBuilder::addFaces2(), Arcane::mesh::DoFFamily::addGhostDoFs(), Arcane::mesh::DoFFamily::addGhostItems(), Arcane::ItemGroupImpl::addItems(), Arcane::mesh::GraphDoFs::addLinks(), Arcane::mesh::DynamicMeshIncrementalBuilder::addNodes(), Arcane::mesh::DynamicMeshIncrementalBuilder::addNodes2(), Arcane::mesh::OneMeshItemAdder::addOneFace(), Arcane::SimpleTableInternalMng::addRows(), Arcane::HoneyComb3DMeshGeneratorService::allocateMeshItems(), Arcane::Parallel::VariableParallelOperationBase::applyOperation(), Arcane::mesh::FaceFamily::applyTiedInterface(), Arcane::TimeHistoryValueT< DataType >::arrayToWrite(), Arcane::StringArrayData::assignSerializedData(), Arcane::ArcaneCurveWriter::beginWrite(), Arcane::Materials::ItemMaterialVariableBase< Traits >::buildFromManager(), Arcane::ItemGroupInternal::checkIsContiguous(), Arcane::ItemGroupImpl::checkIsSorted(), Arcane::mesh::ItemFamily::checkUniqueIds(), Arcane::Array2VariableT< T >::compact(), Arcane::VariableArrayT< T >::compact(), Arcane::Bzip2DeflateService::compress(), Arcane::LZ4DeflateService::compress(), Arcane::BasicRayMeshIntersection::compute(), Arcane::BasicRayMeshIntersection::compute(), Arcane::VariableSynchronizerMpiCommunicator::compute(), Arcane::ItemConnectivitySynchronizer::computeExtraItemsToSend(), Arcane::BasicRayFaceIntersector::computeIntersection(), Arcane::UdunitsPhysicalUnitConverter::convert(), Arcane::StringUtils::convertToStdWString(), Arcane::Array2VariableT< T >::copyItemsMeanValues(), Arcane::mesh::ItemFamily::copyItemsMeanValues(), Arcane::VariableArrayT< T >::copyItemsMeanValues(), Arcane::VariableArrayT< Real >::copyItemsMeanValues(), Arcane::Array2VariableT< T >::copyItemsValues(), Arcane::mesh::ItemFamily::copyItemsValues(), Arcane::VariableArrayT< T >::copyItemsValues(), Arcane::Materials::MeshMaterialMng::createBlock(), Arcane::mesh::ItemFamily::createGroup(), Arcane::ScalarDataT< DataType >::createSerializedDataRef(), Arcane::StringScalarData::createSerializedDataRef(), Arcane::MessagePassing::HybridParallelMng::createSubParallelMngRef(), Arcane::MessagePassing::SharedMemoryParallelMng::createSubParallelMngRef(), Arcane::Bzip2DeflateService::decompress(), Arcane::LZ4DeflateService::decompress(), Arcane::mesh::DynamicMesh::detachCells(), Arcane::Materials::MeshMaterialMng::dumpInfos(), Arcane::MeshUtils::dumpSynchronizerTopologyJSON(), Arcane::Materials::MeshMaterialVariableIndexer::endUpdate(), Arcane::Process::execute(), Arcane::mesh::ItemGroupDynamicMeshObserver::executeCompact(), Arcane::ItemGroupPartialVariableObserver::executeExtend(), Arcane::ItemGroupPartialVariableObserver::executeReduce(), Arcane::mesh::ItemGroupDynamicMeshObserver::executeReduce(), Arcane::FlexLMMng::featureInfo(), Arcane::Materials::ItemMaterialVariableScalar< DataType >::fillFromArray(), Arcane::Materials::ItemMaterialVariableScalar< DataType >::fillToArray(), Arcane::MessagePassing::filterCommonStrings(), Arcane::mesh::TiedInterfaceExchanger::finalize(), Arcane::mesh::MeshRefinement::flagCellToRefine(), Arcane::Materials::AllEnvData::forceRecompute(), Arcane::mesh::ItemFamily::getCommunicatingSubDomains(), Arcane::MeshUtils::getFaceFromNodesLocalId(), Arcane::MeshUtils::getFaceFromNodesUniqueId(), Arcane::UnstructuredMeshUtilities::getFacesLocalIdFromConnectivity(), Arcane::GetVariablesValuesParallelOperation::getVariableValues(), Arcane::DataSynchronizeBufferBase::BufferInfo::initialize(), Arcane::mesh::TiedInterfaceExchanger::initialize(), Arcane::ParallelExchanger::initializeCommunicationsMessages(), Arcane::GraphDistributor::initWithOneRankPerNode(), Arcane::mesh::CellFamily::internalRemoveItems(), Arcane::mesh::ParticleFamily::internalRemoveItems(), Arcane::ItemVector::ItemVector(), Arcane::OneTBBTask::launchAndWait(), Arcane::SerialTask::launchAndWait(), Arcane::UnstructuredMeshUtilities::localIdsFromConnectivity(), Arcane::mesh::MeshNodeMerger::mergeNodes(), Arcane::math::mult(), Arcane::MessagePassing::namedBarrier(), Arcane::ArcaneBasicCheckpointService::notifyBeginWrite(), Arcane::ManualHdf5VariableWriter::notifyBeginWrite(), Arcane::ManualHdf5VariableWriter::notifyEndWrite(), Arcane::mesh::ItemFamily::notifyItemsOwnerChanged(), Arcane::IOMng::parseXmlString(), Arcane::ArcaneInitialPartitioner::partitionAndDistributeMeshes(), Arcane::VariableArrayT< T >::print(), Arcane::XmfMeshReader::readMeshFromFile(), Arcane::Materials::MeshMaterialVariableSynchronizer::recompute(), Arcane::ItemGroupImpl::removeAddItems(), Arcane::mesh::DynamicMesh::removeDetachedCells(), Arcane::mesh::GraphDoFs::removeDualNodes(), Arcane::mesh::GraphDoFs::removeLinks(), Arcane::mesh::DynamicMeshKindInfos::removeMany(), Arcane::ItemGroupImpl::removeSuppressedItems(), Arcane::mesh::FaceFamily::removeTiedInterface(), Arcane::MeshUtils::reorderNodesOfFace(), Arcane::mesh::IncrementalItemConnectivity::replaceConnectedItems(), Arcane::mesh::OneItemIncrementalItemConnectivity::replaceConnectedItems(), Arcane::ConnectivityItemVector::resizeAndCopy(), Arcane::Array< IVariable * >::sample(), Arcane::MetisGraphGather::scatterPart(), Arcane::math::searchExtrema(), Arcane::mesh::BasicParticleExchanger::sendItems(), Arcane::Array2DataT< DataType >::serialize(), Arcane::Materials::ItemMaterialVariableScalar< DataType >::serialize(), Arcane::Materials::MeshMaterialExchangeMng::ExchangeCellStep::serialize(), Arcane::mesh::ItemFamilyVariableSerializer::serialize(), Arcane::NumArrayDataT< DataType, RankValue >::serialize(), Arcane::mesh::ItemFamilySerializer::serializeItemRelations(), Arcane::mesh::CellFamilySerializer::serializeItems(), Arcane::mesh::IndirectItemFamilySerializer::serializeItems(), Arcane::mesh::ItemFamilySerializer::serializeItems(), Arcane::mesh::ParticleFamilySerializer::serializeItems(), Arcane::mesh::IncrementalItemConnectivity::setConnectedItems(), Arcane::ItemGroupImpl::setItems(), Arcane::mesh::ParticleFamily::setParticlesCell(), Arcane::LLVMSymbolizerService::stackTrace(), Arcane::math::sub(), Arcane::Materials::AcceleratorMeshMaterialSynchronizerImpl::synchronizeMaterialsInCells(), Arcane::Materials::LegacyMeshMaterialSynchronizerImpl::synchronizeMaterialsInCells(), Arcane::StringVector::toStringList(), Arcane::TransferValuesParallelOperation::transferValues(), Arcane::GhostLayerFromConnectivityComputer::updateConnectivity(), Arcane::ItemArrayConnectivity::updateConnectivity(), Arcane::ItemConnectivity::updateConnectivity(), Arcane::ItemMultiArrayConnectivity::updateConnectivity(), Arcane::dom::LibXml2_SchemaValidator::validate(), Arcane::ArcaneCurveWriter::writeCurve(), Arcane::GnuplotTimeHistoryCurveWriter2::writeCurve(), Arcane::impl::BasicGenericWriter::writeData(), Arcane::DumpWEnsight7::writeVal(), Arcane::DumpWUCD::writeVal(), and Arcane::DumpWUCD::writeVal().
subConstView()
template<class T> ConstArrayView< T > Arcane::ConstArrayView< T >::subConstView (Integer abegin, Integer asize) const inline constexpr noexcept
Sub-view (constant) starting from element abegin and containing asize elements.
If (abegin+asize) is greater than the array size, the view is truncated to that size, potentially returning an empty view.
Definition at line 681 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::GraphDoFs::addLinks(), and Arcane::ItemConnectivitySynchronizer::serializeGhostItems().
subPart()
template<class T> ThatClass Arcane::ConstArrayView< T >::subPart (Integer abegin, Integer asize) const inline constexpr noexcept
Sub-view (constant) starting from element abegin and containing asize elements.
If (abegin+asize) is greater than the array size, the view is truncated to that size, potentially returning an empty view.
Definition at line 669 of file arccore/src/base/arccore/base/ArrayView.h.
subPartInterval()
template<class T> ThatClass Arcane::ConstArrayView< T >::subPartInterval (Integer index, Integer nb_interval) const inline constexpr
Sub-view corresponding to the interval index over nb_interval.
Definition at line 693 of file arccore/src/base/arccore/base/ArrayView.h.
subView()
template<class T> ConstArrayView< T > Arcane::ConstArrayView< T >::subView (Integer abegin, Integer asize) const inline constexpr noexcept
Sub-view (constant) starting from element abegin and containing asize elements.
If (abegin+asize) is greater than the array size, the view is truncated to that size, potentially returning an empty view.
Definition at line 654 of file arccore/src/base/arccore/base/ArrayView.h.
Referenced by Arcane::Materials::ComponentItemVectorView::_subView(), Arcane::mesh::DynamicMeshIncrementalBuilder::addFamilyItems(), Arcane::MessagePassing::namedBarrier(), Arcane::ConstArrayView< Type >::subConstView(), and Arcane::ConstArrayView< Type >::subPart().
subViewInterval()
template<class T> ConstArrayView< T > Arcane::ConstArrayView< T >::subViewInterval (Integer index, Integer nb_interval) const inline constexpr
Sub-view corresponding to the interval index over nb_interval.
Definition at line 687 of file arccore/src/base/arccore/base/ArrayView.h.
unguardedBasePointer()
template<class T> const_pointer Arcane::ConstArrayView< T >::unguardedBasePointer () const inline constexpr noexcept
Pointer to the allocated memory.
Warning
Accesses via the returned pointer cannot be verified by Arcane, unlike accesses via operator[](): no overflow check is possible, even in verification mode.
Definition at line 775 of file arccore/src/base/arccore/base/ArrayView.h.
Friends And Related Symbol Documentation
operator!=
template<class T> bool operator!= (const ConstArrayView< T > & rhs, const ConstArrayView< T > & lhs) friend
Definition at line 801 of file arccore/src/base/arccore/base/ArrayView.h.
operator<<
template<class T> std::ostream & operator<< (std::ostream & o, const ConstArrayView< T > & val) friend
Definition at line 806 of file arccore/src/base/arccore/base/ArrayView.h.
operator==
template<class T> bool operator== (const ConstArrayView< T > & rhs, const ConstArrayView< T > & lhs) friend
Definition at line 796 of file arccore/src/base/arccore/base/ArrayView.h.
SmallSpan< const T >
template<class T> friend class SmallSpan< const T > friend
Definition at line 532 of file arccore/src/base/arccore/base/ArrayView.h.
SmallSpan< T >
template<class T> friend class SmallSpan< T > friend
Definition at line 532 of file arccore/src/base/arccore/base/ArrayView.h.
Span< const T >
template<class T> friend class Span< const T > friend
Definition at line 532 of file arccore/src/base/arccore/base/ArrayView.h.
Span< T >
template<class T> friend class Span< T > friend
Definition at line 532 of file arccore/src/base/arccore/base/ArrayView.h.
Member Data Documentation
m_ptr
template<class T> const_pointer Arcane::ConstArrayView< T >::m_ptr private
Pointer to the start of the array.
Definition at line 815 of file arccore/src/base/arccore/base/ArrayView.h.
m_size
template<class T> Integer Arcane::ConstArrayView< T >::m_size private
Number of elements.
Definition at line 814 of file arccore/src/base/arccore/base/ArrayView.h.
The documentation for this class was generated from the following file:
arccore/src/base/arccore/base/ArrayView.h