Arcane: Arcane::CaseOptions Class Reference
Arcane::CaseOptions Class Reference
Public Member Functions
CaseOptions (ICaseMng *cm, const String &name)
Constructs an options set.
CaseOptions (ICaseOptionList *, const String &name)
Constructs an options set.
CaseOptions (ICaseMng *cm, const String &name, const XmlNode &parent)
Constructs an options set.
CaseOptions (ICaseOptionList *, const String &name, const XmlNode &parent, bool is_optional=false, bool is_multi=false)
Constructs an options set.
~CaseOptions () override
Frees resources.
String rootTagTrueName () const override
Returns the true name (non-translated) of the element.
String rootTagName () const override
Returns the name of the element in the data set language.
String translatedName (const String &lang) const override
Name in language lang of the option. Returns rootTagTrueName() if no translation exists.
virtual String trueName () const
Returns the true name (non-translated) of the element.
virtual String name () const
Returns the name of the element in the data set language.
void read (bool is_phase1) override
void read (eCaseOptionReadPhase phase) override
Performs the reading of the read_phase phase of the options.
void addInvalidChildren (XmlNodeList &) override
Adds unrecognized elements to nlist.
void printChildren (const String &lang, int indent) override
IServiceInfo * caseServiceInfo () const override
Returns the associated service or 0 if none exists.
IModule * caseModule () const override
Returns the associated module or 0 if none exists.
void setCaseServiceInfo (IServiceInfo *m) override
Associates service m with this data set.
void setCaseModule (IModule *m) override
Associates module m with this data set.
void deepGetChildren (Array< CaseOptionBase * > &col) override
Adds all child options to the list col.
ICaseOptionList * configList () override
const ICaseOptionList * configList () const override
ICaseFunction * activateFunction () override
Function indicating the activation status of the option.
bool isPresent () const override
True if the option is present in the file, false if it is the default value.
void addAlternativeNodeName (const String &lang, const String &name) override
Adds a translation for the option name. Adds the option name name corresponding to language lang. If a translation already exists for this language, it is replaced by this one.
ICaseMng * caseMng () const override
ITraceMng * traceMng () const override
ISubDomain * subDomain () const override
Associated sub-domain.
IMesh * mesh () const override
MeshHandle meshHandle () const override
ICaseDocument * caseDocument () const override
ICaseDocumentFragment * caseDocumentFragment () const override
void detach () override
void visit (ICaseDocumentVisitor *visitor) const override
Applies the visitor to this option.
String xpathFullName () const override
Full name in XPath format corresponding to rootElement().
Ref< ICaseOptions > toReference () override
Protected Member Functions
CaseOptions (ICaseMng *, const String &name, ICaseOptionList *parent)
Constructs an options set.
CaseOptions (ICaseOptionList *, const String &name, ICaseOptionList *parent)
Constructs an options set.
void _setTranslatedName ()
bool _setMeshHandleAndCheckDisabled (const String &mesh_name)
Positions the mesh associated with this option.
Protected Attributes
CaseOptionsPrivate * m_p
Implementation.
Friends
class ServiceBuilderWithOptionsBase
class CaseOptionMultiServiceImpl
Detailed Description
Definition at line 55 of file CaseOptions.h.
Constructor & Destructor Documentation
CaseOptions() [1/6]
Arcane::CaseOptions::CaseOptions (ICaseMng * cm, const String & name)
Constructs an options set.
Definition at line 108 of file CaseOptions.cc.
References m_p, name(), and Arcane::ICaseMng::registerOptions().
CaseOptions() [2/6]
Arcane::CaseOptions::CaseOptions (ICaseOptionList * parent, const String & name)
Constructs an options set.
Definition at line 120 of file CaseOptions.cc.
References m_p.
CaseOptions() [3/6]
Arcane::CaseOptions::CaseOptions (ICaseMng * cm, const String & name, const XmlNode & parent)
Constructs an options set.
Definition at line 131 of file CaseOptions.cc.
References m_p, and Arcane::ICaseMng::registerOptions().
CaseOptions() [4/6]
Arcane::CaseOptions::CaseOptions (ICaseOptionList * parent, const String & name, const XmlNode & parent, bool is_optional = false, bool is_multi = false)
Constructs an options set.
Definition at line 143 of file CaseOptions.cc.
References m_p.
CaseOptions() [5/6]
Arcane::CaseOptions::CaseOptions (ICaseMng * cm, const String & name, ICaseOptionList * parent) protected
Constructs an options set.
Definition at line 158 of file CaseOptions.cc.
References m_p, and Arcane::ICaseMng::registerOptions().
CaseOptions() [6/6]
Arcane::CaseOptions::CaseOptions (ICaseOptionList * parent, const String & name, ICaseOptionList * parent) protected
Constructs an options set.
Definition at line 170 of file CaseOptions.cc.
References m_p.
~CaseOptions()
Arcane::CaseOptions::~CaseOptions () override
Frees resources.
Definition at line 199 of file CaseOptions.cc.
References m_p.
Member Function Documentation
_setMeshHandleAndCheckDisabled()
bool Arcane::CaseOptions::_setMeshHandleAndCheckDisabled (const String & mesh_name) protected
Positions the mesh associated with this option.
If mesh_name is null or empty, the mesh associated with this option is that of the parent option. If the option has no parent, it is the default mesh.
If mesh_name is not null, there are two possibilities:
if the specified mesh exists, the option will be associated with that mesh
if it does not exist, the option is disabled and any potential child options will not be read. This latter case occurs, for example, if a service is associated with an additional mesh but that mesh is optional. In this case, the option must not be read.
Return values
true if the option is disabled following this call.
Definition at line 433 of file CaseOptions.cc.
References Arcane::String::empty(), Arcane::IMeshMng::findMeshHandle(), m_p, and Arcane::MeshHandle::meshMng().
_setTranslatedName()
void Arcane::CaseOptions::_setTranslatedName () protected
Definition at line 459 of file CaseOptions.cc.
activateFunction()
ICaseFunction * Arcane::CaseOptions::activateFunction () override virtual
Function indicating the activation status of the option.
Implements Arcane::ICaseOptions.
Definition at line 493 of file CaseOptions.cc.
References m_p.
addAlternativeNodeName()
void Arcane::CaseOptions::addAlternativeNodeName (const String & lang, const String & name) override virtual
Adds a translation for the option name. Adds the option name name corresponding to language lang. If a translation already exists for this language, it is replaced by this one.
Implements Arcane::ICaseOptions.
Definition at line 262 of file CaseOptions.cc.
References m_p, and name().
addInvalidChildren()
void Arcane::CaseOptions::addInvalidChildren (XmlNodeList & nlist) override virtual
Adds unrecognized elements to nlist.
Implements Arcane::ICaseOptions.
Definition at line 562 of file CaseOptions.cc.
References m_p.
caseDocument()
ICaseDocument * Arcane::CaseOptions::caseDocument () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 376 of file CaseOptions.cc.
caseDocumentFragment()
ICaseDocumentFragment * Arcane::CaseOptions::caseDocumentFragment () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 385 of file CaseOptions.cc.
caseMng()
ICaseMng * Arcane::CaseOptions::caseMng () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 331 of file CaseOptions.cc.
caseModule()
IModule * Arcane::CaseOptions::caseModule () const override virtual
Returns the associated module or 0 if none exists.
Implements Arcane::ICaseOptions.
Definition at line 304 of file CaseOptions.cc.
References m_p.
caseServiceInfo()
IServiceInfo * Arcane::CaseOptions::caseServiceInfo () const override virtual
Returns the associated service or 0 if none exists.
Implements Arcane::ICaseOptions.
Definition at line 295 of file CaseOptions.cc.
References m_p.
configList() [1/2]
const ICaseOptionList * Arcane::CaseOptions::configList () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 286 of file CaseOptions.cc.
configList() [2/2]
ICaseOptionList * Arcane::CaseOptions::configList () override virtual
Implements Arcane::ICaseOptions.
Definition at line 277 of file CaseOptions.cc.
deepGetChildren()
void Arcane::CaseOptions::deepGetChildren (Array< CaseOptionBase * > & col) override virtual
Adds all child options to the list col.
Implements Arcane::ICaseOptions.
Definition at line 589 of file CaseOptions.cc.
References m_p.
detach()
void Arcane::CaseOptions::detach () override virtual
Implements Arcane::ICaseOptions.
Definition at line 214 of file CaseOptions.cc.
isPresent()
bool Arcane::CaseOptions::isPresent () const override virtual
True if the option is present in the file, false if it is the default value.
Implements Arcane::ICaseOptions.
Definition at line 244 of file CaseOptions.cc.
References m_p.
mesh()
IMesh * Arcane::CaseOptions::mesh () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 367 of file CaseOptions.cc.
meshHandle()
MeshHandle Arcane::CaseOptions::meshHandle () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 358 of file CaseOptions.cc.
name()
virtual String Arcane::CaseOptions::name () const inline virtual
Returns the name of the element in the data set language.
Definition at line 122 of file CaseOptions.h.
References rootTagName().
Referenced by addAlternativeNodeName(), and CaseOptions().
printChildren()
void Arcane::CaseOptions::printChildren (const String & lang, int indent) override virtual
Implements Arcane::ICaseOptions.
Definition at line 571 of file CaseOptions.cc.
read() [1/2]
void Arcane::CaseOptions::read (bool is_phase1) inline override virtual
Implements Arcane::ICaseOptions.
Definition at line 124 of file CaseOptions.h.
read() [2/2]
void Arcane::CaseOptions::read (eCaseOptionReadPhase read_phase) override virtual
Performs the reading of the read_phase phase of the options.
Implements Arcane::ICaseOptions.
Reimplemented in Arcane::CaseOptionServiceImpl.
Definition at line 502 of file CaseOptions.cc.
References Arcane::CaseOptionError::addError(), Arcane::XmlNode::attrValue(), Arcane::ICaseDocumentFragment::caseNodeNames(), Arcane::ITraceMng::info(), m_p, Arcane::ICaseFunction::name(), Arcane::String::null(), Arcane::ICaseFunction::ParamReal, Arcane::ICaseFunction::paramType(), Arcane::ICaseFunction::ValueBool, Arcane::ICaseFunction::valueType(), and Arcane::XmlNode::xpathFullName().
rootTagName()
String Arcane::CaseOptions::rootTagName () const override virtual
Returns the name of the element in the data set language.
Implements Arcane::ICaseOptions.
Definition at line 235 of file CaseOptions.cc.
References m_p.
Referenced by name().
rootTagTrueName()
String Arcane::CaseOptions::rootTagTrueName () const override virtual
Returns the true name (non-translated) of the element.
Implements Arcane::ICaseOptions.
Definition at line 226 of file CaseOptions.cc.
References m_p.
Referenced by trueName().
setCaseModule()
void Arcane::CaseOptions::setCaseModule (IModule * m) override virtual
Associates module m with this data set.
Implements Arcane::ICaseOptions.
Definition at line 322 of file CaseOptions.cc.
References m_p.
setCaseServiceInfo()
void Arcane::CaseOptions::setCaseServiceInfo (IServiceInfo * m) override virtual
Associates service m with this data set.
Implements Arcane::ICaseOptions.
Definition at line 313 of file CaseOptions.cc.
References m_p.
subDomain()
ISubDomain * Arcane::CaseOptions::subDomain () const override virtual
Associated sub-domain.
Deprecated
Do not use this method because eventually an option may exist without a sub-domain.
Implements Arcane::ICaseOptions.
Definition at line 349 of file CaseOptions.cc.
References m_p.
toReference()
Ref< ICaseOptions > Arcane::CaseOptions::toReference () override virtual
Implements Arcane::ICaseOptions.
Definition at line 613 of file CaseOptions.cc.
traceMng()
ITraceMng * Arcane::CaseOptions::traceMng () const override virtual
Implements Arcane::ICaseOptions.
Definition at line 340 of file CaseOptions.cc.
translatedName()
String Arcane::CaseOptions::translatedName (const String & lang) const override virtual
Name in language lang of the option. Returns rootTagTrueName() if no translation exists.
Implements Arcane::ICaseOptions.
Definition at line 479 of file CaseOptions.cc.
References m_p, and Arcane::String::null().
trueName()
virtual String Arcane::CaseOptions::trueName () const inline virtual
Returns the true name (non-translated) of the element.
Definition at line 119 of file CaseOptions.h.
References rootTagTrueName().
visit()
void Arcane::CaseOptions::visit (ICaseDocumentVisitor * visitor) const override virtual
Applies the visitor to this option.
Implements Arcane::ICaseOptions.
Reimplemented in Arcane::CaseOptionServiceImpl.
Definition at line 580 of file CaseOptions.cc.
References m_p.
Referenced by Arcane::CaseOptionServiceImpl::visit().
xpathFullName()
String Arcane::CaseOptions::xpathFullName () const override virtual
Full name in XPath format corresponding to rootElement().
Implements Arcane::ICaseOptions.
Definition at line 253 of file CaseOptions.cc.
References m_p.
Friends And Related Symbol Documentation
CaseOptionMultiServiceImpl
friend class CaseOptionMultiServiceImpl friend
Definition at line 190 of file CaseOptions.h.
ServiceBuilderWithOptionsBase
friend class ServiceBuilderWithOptionsBase friend
Definition at line 89 of file CaseOptions.h.
Member Data Documentation
m_p
CaseOptionsPrivate* Arcane::CaseOptions::m_p protected
Implementation.
Definition at line 197 of file CaseOptions.h.
Referenced by _setMeshHandleAndCheckDisabled(), activateFunction(), addAlternativeNodeName(), addInvalidChildren(), caseModule(), CaseOptions(), CaseOptions(), CaseOptions(), CaseOptions(), CaseOptions(), CaseOptions(), caseServiceInfo(), deepGetChildren(), isPresent(), read(), rootTagName(), rootTagTrueName(), setCaseModule(), setCaseServiceInfo(), subDomain(), translatedName(), visit(), xpathFullName(), and ~CaseOptions().
The documentation for this class was generated from the following files:
CaseOptions.h
CaseOptions.cc