Arcane: Arcane::Accelerator::GenericReducer< DataType > Class Template Reference
Arcane::Accelerator::GenericReducer< DataType > Class Template Reference
Generic accelerator reduction algorithm.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/accelerator/arccore/accelerator/GenericReducer.h>
Public Member Functions
GenericReducer (const RunQueue &queue)
void applyMin (SmallSpan< const DataType > values, const TraceInfo &trace_info=TraceInfo())
Applies a 'Min' reduction on the values values.
void applyMax (SmallSpan< const DataType > values, const TraceInfo &trace_info=TraceInfo())
Applies a 'Max' reduction on the values values.
void applySum (SmallSpan< const DataType > values, const TraceInfo &trace_info=TraceInfo())
Applies a 'Sum' reduction on the values values.
template<typename SelectLambda>
void applyMinWithIndex (Int32 nb_value, const SelectLambda &select_lambda, const TraceInfo &trace_info=TraceInfo())
Applies a 'Min' reduction on the values selected by select_lambda.
template<typename SelectLambda>
void applyMaxWithIndex (Int32 nb_value, const SelectLambda &select_lambda, const TraceInfo &trace_info=TraceInfo())
Applies a 'Max' reduction on the values selected by select_lambda.
template<typename SelectLambda>
void applySumWithIndex (Int32 nb_value, const SelectLambda &select_lambda, const TraceInfo &trace_info=TraceInfo())
Applies a 'Sum' reduction on the values selected by select_lambda.
DataType reducedValue ()
Reduction value.
Private Member Functions
template<typename InputIterator, typename ReduceOperator>
void _apply (Int32 nb_value, InputIterator input_iter, ReduceOperator reduce_op, const TraceInfo &trace_info)
template<typename GetterLambda, typename ReduceOperator>
void _applyWithIndex (Int32 nb_value, const GetterLambda &getter_lambda, ReduceOperator reduce_op, const TraceInfo &trace_info)
void _setCalled ()
Private Member Functions inherited from Arcane::Accelerator::Impl::GenericReducerBase< DataType >
GenericReducerBase (const RunQueue &queue)
DataType _reducedValue () const
void _allocate ()
Private Attributes
bool m_is_already_called = false
Private Attributes inherited from Arcane::Accelerator::Impl::GenericReducerBase< DataType >
RunQueue m_queue
GenericDeviceStorage m_algo_storage
DeviceStorage< DataType > m_device_reduce_storage
NumArray< DataType, MDDim1 > m_host_reduce_storage
Detailed Description
template<typename DataType>
class Arcane::Accelerator::GenericReducer< DataType >
Generic accelerator reduction algorithm.
The reduction is performed via calls to applyMin(), applyMax(), applySum(), applyMinWithIndex(), applyMaxWithIndex() or applySumWithIndex(). These methods are asynchronous. After reduction, it is possible to retrieve the reduced value via reducedValue(). The call to reducedValue() blocks until the reduction is complete.
Instances of this class can be used multiple times.
Here is an example to calculate the sum of an array of 50 elements:
using namespace Arcane;
const Int32 nb_value(50);
Arcane::NumArray<Real, MDDim1> t1(nv_value);
Arcane::SmallSpan<const Real> t1_view(t1);
Arcane::RunQueue queue = ...;
Arcane::Accelerator::GenericReducer<Real> reducer(queue);
// Direct calculation
reducer.applySum(t1_view);
std::cout << "Sum is '" << reducer.reducedValue() << "\n";
// Calculation with lambda
auto getter_func = [=] ARCCORE_HOST_DEVICE(Int32 index) -> Real
{
  return t1_view[index];
}
reducer.applySumWithIndex(nb_value,getter_func);
std::cout << "Sum is '" << reducer.reducedValue() << "\n";
Definition at line 253 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
Constructor & Destructor Documentation
GenericReducer()
template<typename DataType> Arcane::Accelerator::GenericReducer< DataType >::GenericReducer (const RunQueue & queue) inline explicit
Definition at line 258 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
Member Function Documentation
_apply()
template<typename DataType> template<typename InputIterator, typename ReduceOperator> void Arcane::Accelerator::GenericReducer< DataType >::_apply (Int32 nb_value, InputIterator input_iter, ReduceOperator reduce_op, const TraceInfo & trace_info) inline private
Definition at line 319 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
_applyWithIndex()
template<typename DataType> template<typename GetterLambda, typename ReduceOperator> void Arcane::Accelerator::GenericReducer< DataType >::_applyWithIndex (Int32 nb_value, const GetterLambda & getter_lambda, ReduceOperator reduce_op, const TraceInfo & trace_info) inline private
Definition at line 329 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
_setCalled()
template<typename DataType> void Arcane::Accelerator::GenericReducer< DataType >::_setCalled () inline private
Definition at line 340 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
applyMax()
template<typename DataType> void Arcane::Accelerator::GenericReducer< DataType >::applyMax (SmallSpan< const DataType > values, const TraceInfo & trace_info = TraceInfo()) inline
Applies a 'Max' reduction on the values values.
Definition at line 273 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
References Arcane::SpanImpl< T, SizeType, Extent >::data(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
applyMaxWithIndex()
template<typename DataType> template<typename SelectLambda> void Arcane::Accelerator::GenericReducer< DataType >::applyMaxWithIndex (Int32 nb_value, const SelectLambda & select_lambda, const TraceInfo & trace_info = TraceInfo()) inline
Applies a 'Max' reduction on the values selected by select_lambda.
Definition at line 293 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
applyMin()
template<typename DataType> void Arcane::Accelerator::GenericReducer< DataType >::applyMin (SmallSpan< const DataType > values, const TraceInfo & trace_info = TraceInfo()) inline
Applies a 'Min' reduction on the values values.
Definition at line 267 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
References Arcane::SpanImpl< T, SizeType, Extent >::data(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
applyMinWithIndex()
template<typename DataType> template<typename SelectLambda> void Arcane::Accelerator::GenericReducer< DataType >::applyMinWithIndex (Int32 nb_value, const SelectLambda & select_lambda, const TraceInfo & trace_info = TraceInfo()) inline
Applies a 'Min' reduction on the values selected by select_lambda.
Definition at line 286 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
applySum()
template<typename DataType> void Arcane::Accelerator::GenericReducer< DataType >::applySum (SmallSpan< const DataType > values, const TraceInfo & trace_info = TraceInfo()) inline
Applies a 'Sum' reduction on the values values.
Definition at line 279 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
References Arcane::SpanImpl< T, SizeType, Extent >::data(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
applySumWithIndex()
template<typename DataType> template<typename SelectLambda> void Arcane::Accelerator::GenericReducer< DataType >::applySumWithIndex (Int32 nb_value, const SelectLambda & select_lambda, const TraceInfo & trace_info = TraceInfo()) inline
Applies a 'Sum' reduction on the values selected by select_lambda.
Definition at line 300 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
reducedValue()
template<typename DataType> DataType Arcane::Accelerator::GenericReducer< DataType >::reducedValue () inline
Reduction value.
Definition at line 306 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
Member Data Documentation
m_is_already_called
template<typename DataType> bool Arcane::Accelerator::GenericReducer< DataType >::m_is_already_called = false private
Definition at line 314 of file arccore/src/accelerator/arccore/accelerator/GenericReducer.h.
The documentation for this class was generated from the following file:
arccore/src/accelerator/arccore/accelerator/GenericReducer.h