Alien: Alien::BlockMatrix Class Reference
Alien::BlockMatrix Class Reference final
Public Member Functions
BlockMatrix (const Block &block, const MatrixDistribution &dist)
BlockMatrix (Integer nrows, Integer ncols, Integer nrows_local, const Block &block, IMessagePassingMng *parallel_mng)
BlockMatrix (Integer nrows, Integer ncols, const Block &block, IMessagePassingMng *parallel_mng)
BlockMatrix (BlockMatrix &&m)
BlockMatrix & operator= (BlockMatrix &&m)
BlockMatrix (const BlockMatrix &)=delete
BlockMatrix & operator= (const BlockMatrix &)=delete
void init (const Block &block, const MatrixDistribution &dist)
void free ()
void clear ()
void visit (ICopyOnWriteMatrix &) const
Visit method.
const MatrixDistribution & distribution () const
const ISpace & rowSpace () const
Get row space associated to the matrix.
const ISpace & colSpace () const
Get col space associated to the matrix.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
const Block & block () const
MultiMatrixImpl * impl ()
Get the multimatrix implementation.
const MultiMatrixImpl * impl () const
Get the multimatrix implementation.
Additional Inherited Members
Protected Member Functions inherited from Alien::IMatrix
IMatrix ()
Constructor.
Detailed Description
Definition at line 39 of file BlockMatrix.h.
Constructor & Destructor Documentation
BlockMatrix() [1/5]
Alien::BlockMatrix::BlockMatrix ()
Definition at line 33 of file BlockMatrix.cc.
BlockMatrix() [2/5]
Alien::BlockMatrix::BlockMatrix (const Block & block, const MatrixDistribution & dist)
Definition at line 40 of file BlockMatrix.cc.
BlockMatrix() [3/5]
Alien::BlockMatrix::BlockMatrix (Integer nrows, Integer ncols, Integer nrows_local, const Block & block, IMessagePassingMng * parallel_mng)
Definition at line 49 of file BlockMatrix.cc.
BlockMatrix() [4/5]
Alien::BlockMatrix::BlockMatrix (Integer nrows, Integer ncols, const Block & block, IMessagePassingMng * parallel_mng)
Definition at line 61 of file BlockMatrix.cc.
BlockMatrix() [5/5]
Alien::BlockMatrix::BlockMatrix (BlockMatrix && m)
Definition at line 72 of file BlockMatrix.cc.
~BlockMatrix()
Alien::BlockMatrix::~BlockMatrix () inline
Definition at line 54 of file BlockMatrix.h.
Member Function Documentation
block()
const Block & Alien::BlockMatrix::block () const
Definition at line 156 of file BlockMatrix.cc.
clear()
void Alien::BlockMatrix::clear ()
Definition at line 103 of file BlockMatrix.cc.
colSpace()
const ISpace & Alien::BlockMatrix::colSpace () const virtual
Get col space associated to the matrix.
Returns
The col space
Implements Alien::IMatrix.
Definition at line 134 of file BlockMatrix.cc.
References colSpace().
Referenced by colSpace().
distribution()
const MatrixDistribution & Alien::BlockMatrix::distribution () const
Definition at line 118 of file BlockMatrix.cc.
free()
void Alien::BlockMatrix::free ()
Definition at line 96 of file BlockMatrix.cc.
hasUserFeature()
bool Alien::BlockMatrix::hasUserFeature (String feature) const
Definition at line 148 of file BlockMatrix.cc.
impl() [1/2]
MultiMatrixImpl * Alien::BlockMatrix::impl () virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 169 of file BlockMatrix.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiMatrixImpl * Alien::BlockMatrix::impl () const virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 184 of file BlockMatrix.cc.
References impl().
init()
void Alien::BlockMatrix::init (const Block & block, const MatrixDistribution & dist)
Definition at line 87 of file BlockMatrix.cc.
operator=()
BlockMatrix & Alien::BlockMatrix::operator= (BlockMatrix && m)
Definition at line 79 of file BlockMatrix.cc.
rowSpace()
const ISpace & Alien::BlockMatrix::rowSpace () const virtual
Get row space associated to the matrix.
Returns
The row space
Implements Alien::IMatrix.
Definition at line 126 of file BlockMatrix.cc.
References rowSpace().
Referenced by rowSpace().
setUserFeature()
void Alien::BlockMatrix::setUserFeature (String feature)
Definition at line 141 of file BlockMatrix.cc.
visit()
void Alien::BlockMatrix::visit (ICopyOnWriteMatrix &) const virtual
Visit method.
Implements Alien::IMatrix.
Definition at line 110 of file BlockMatrix.cc.
References visit().
Referenced by visit().
The documentation for this class was generated from the following files:
BlockMatrix.h
BlockMatrix.cc