Alien: Alien::Timestamp Class Reference
Alien::Timestamp Class Reference
Public Member Functions
manager est nul, il n'y a pas de gestion de timestamp
Constructeur de la classe
Si
Timestamp (const TimestampMng *manager)
virtual ~Timestamp ()
Destructeur de la classe.
virtual Int64 timestamp () const
Donne la valeur courante du timestamp.
void updateTimestamp ()
Met à jour le timestamp.
void copyTimestamp (const Timestamp &v)
Copy un autre timestamp.
manager permet de garantir que l'identité du manager effectuant
Méthode interne de changement de valeur par le manager
Le paramètre cette requête de modification et de garantir l'intégrité des objets
void setTimestamp (const TimestampMng *manager, const Int64 timestamp)
Detailed Description
Definition at line 37 of file Timestamp.h.
Constructor & Destructor Documentation
Timestamp()
Alien::Timestamp::Timestamp (const TimestampMng * manager)
Definition at line 36 of file Timestamp.cc.
~Timestamp()
virtual Alien::Timestamp::~Timestamp () inline virtual
Destructeur de la classe.
Definition at line 45 of file Timestamp.h.
Member Function Documentation
copyTimestamp()
void Alien::Timestamp::copyTimestamp (const Timestamp & v)
Copy un autre timestamp.
Definition at line 58 of file Timestamp.cc.
References copyTimestamp().
Referenced by copyTimestamp().
setTimestamp()
void Alien::Timestamp::setTimestamp (const TimestampMng * manager, const Int64 timestamp)
Definition at line 65 of file Timestamp.cc.
timestamp()
Int64 Alien::Timestamp::timestamp () const virtual
Donne la valeur courante du timestamp.
Definition at line 43 of file Timestamp.cc.
References timestamp().
Referenced by Alien::MultiMatrixImpl::clone(), Alien::MultiVectorImpl::clone(), and timestamp().
updateTimestamp()
void Alien::Timestamp::updateTimestamp ()
Met à jour le timestamp.
La politique actuelle position ce timestamp comme le plus 'à jour' de ceux associés aux même manager
Definition at line 50 of file Timestamp.cc.
References updateTimestamp().
Referenced by Alien::MultiMatrixImpl::clone(), Alien::MultiVectorImpl::clone(), Alien::MultiMatrixImpl::get(), Alien::MultiVectorImpl::get(), and updateTimestamp().
The documentation for this class was generated from the following files:
Timestamp.h
Timestamp.cc