Arcane: Arcane::Accelerator::GenericFilterer Class Reference
Arcane::Accelerator::GenericFilterer Class Reference
Generic filtering algorithm on accelerator.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/accelerator/arccore/accelerator/GenericFilterer.h>
Public Member Functions
GenericFilterer (RunQueue *queue)
Creates an instance.
GenericFilterer (const RunQueue &queue)
Creates an instance.
template<typename InputDataType, typename OutputDataType, typename FlagType>
void apply (SmallSpan< const InputDataType > input, SmallSpan< OutputDataType > output, SmallSpan< const FlagType > flag)
Applies a filter.
template<typename DataType, typename SelectLambda>
void applyIf (SmallSpan< DataType > input_output, const SelectLambda &select_lambda, const TraceInfo &trace_info=TraceInfo())
Applies a filter.
template<typename InputIterator, typename OutputIterator, typename SelectLambda>
void applyIf (Int32 nb_value, InputIterator input_iter, OutputIterator output_iter, const SelectLambda &select_lambda, const TraceInfo &trace_info=TraceInfo())
Applies a filter.
template<typename SelectLambda, typename SetterLambda>
void applyWithIndex (Int32 nb_value, const SelectLambda &select_lambda, const SetterLambda &setter_lambda, const TraceInfo &trace_info=TraceInfo())
Applies a filter with selection based on an index.
Int32 nbOutputElement ()
Number of output elements.
Additional Inherited Members
Private Member Functions inherited from Arcane::Accelerator::Impl::GenericFilteringBase
Int32 _nbOutputElement ()
void _allocate ()
void _allocateTemporaryStorage (size_t size)
int * _getDeviceNbOutPointer ()
void _copyDeviceNbOutToHostNbOut ()
void _setCalled ()
bool _checkEmpty (Int32 nb_value)
Private Attributes inherited from Arcane::Accelerator::Impl::GenericFilteringBase
RunQueue m_queue
Execution queue. Must not be null.
GenericDeviceStorage m_algo_storage
DeviceStorage< int > m_device_nb_out_storage
Device memory for the number of filtered values.
NumArray< Int32, MDDim1 > m_host_nb_out_storage
Host memory for the number of filtered values.
bool m_use_direct_host_storage = true
Indicates which memory is used for the number of filtered values.
bool m_is_already_called = false
Indicates if a call is in progress.
Detailed Description
Generic filtering algorithm on accelerator.
Definition at line 374 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
Constructor & Destructor Documentation
GenericFilterer() [1/2]
Arcane::Accelerator::GenericFilterer::GenericFilterer (RunQueue * queue) inline explicit
Creates an instance.
Precondition
queue!=nullptr
Definition at line 386 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References ARCCORE_CHECK_POINTER, GenericFilterer(), and Arcane::Accelerator::Impl::GenericFilteringBase::m_queue.
Referenced by GenericFilterer().
GenericFilterer() [2/2]
Arcane::Accelerator::GenericFilterer::GenericFilterer (const RunQueue & queue) inline explicit
Creates an instance.
Precondition
queue!=nullptr
Definition at line 398 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References Arcane::Accelerator::Impl::GenericFilteringBase::m_queue.
Member Function Documentation
apply()
template<typename InputDataType, typename OutputDataType, typename FlagType> void Arcane::Accelerator::GenericFilterer::apply (SmallSpan< const InputDataType > input, SmallSpan< OutputDataType > output, SmallSpan< const FlagType > flag) inline
Applies a filter.
Filters all elements in input for which flag is not 0 and fills output with the filtered values. output must be large enough to hold all filtered elements.
The sequential algorithm is as follows:
Int32 index = 0;
for (Int32 i = 0; i < nb_item; ++i) {
  if (flag[i] != 0) {
    output[index] = input[i];
    ++index;
  }
}
return index;
You must call the nbOutputElement() method to get the number of elements after filtering.
Definition at line 430 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References ARCCORE_FATAL, and Arcane::SpanImpl< T, SizeType, Extent >::size().
applyIf() [1/2]
template<typename InputIterator, typename OutputIterator, typename SelectLambda> void Arcane::Accelerator::GenericFilterer::applyIf (Int32 nb_value, InputIterator input_iter, OutputIterator output_iter, const SelectLambda & select_lambda, const TraceInfo & trace_info = TraceInfo()) inline
Applies a filter.
This method is identical to Filterer::applyIf(SmallSpan<const DataType> input, SmallSpan<DataType> output, const SelectLambda& select_lambda) but allows specifying an input_iter iterator for the input and output_iter for the output. The number of input entities is given by nb_value.
The memory regions associated with input_iter and output_iter must not overlap.
Definition at line 529 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References Arcane::Accelerator::Impl::GenericFilteringIf::apply().
applyIf() [2/2]
template<typename DataType, typename SelectLambda> void Arcane::Accelerator::GenericFilterer::applyIf (SmallSpan< DataType > input_output, const SelectLambda & select_lambda, const TraceInfo & trace_info = TraceInfo()) inline
Applies a filter.
Filters all elements in input for which select_lambda equals true and fills output with the filtered values. output must be large enough to hold all filtered elements. The memory regions associated with input and output must not overlap.
select_lambda must have an operator `ARCCORE_HOST_DEVICE bool operator()(const DataType& v) const'.
For example, the following lambda keeps only elements whose value is greater than 569.
auto filter_lambda = [] ARCCORE_HOST_DEVICE (const DataType& x) -> bool {
  return (x > 569.0);
};
The sequential algorithm is as follows:
Int32 index = 0;
for (Int32 i = 0; i < nb_item; ++i) {
  if (select_lambda(input[i])) {
    output[index] = input[i];
    ++index;
  }
}
return index;
You must call the nbOutputElement() method to get the number of elements after filtering. */ template <typename DataType, typename SelectLambda> void applyIf(SmallSpan<const DataType> input, SmallSpan<DataType> output, const SelectLambda& select_lambda, const TraceInfo& trace_info = TraceInfo()) { const Int32 nb_value = input.size(); if (output.size() != nb_value) ARCCORE_FATAL("Sizes are not equals: input={0} output={1}", nb_value, output.size()); if (input.data() == output.data()) ARCCORE_FATAL("Input and Output are the same. Use in place overload instead"); if (_checkEmpty(nb_value)) return; _setCalled(); Impl::GenericFilteringBase* base_ptr = this; Impl::GenericFilteringIf gf; gf.apply<false>(*base_ptr, nb_value, input.data(), output.data(), select_lambda, trace_info); }
/*!
Applies an in-place filter.
This method is identical to applyIf(SmallSpan<const DataType>, SmallSpan<DataType>, const SelectLambda&, const TraceInfo& trace_info) but the filtered values are directly copied into the input_output array.
Definition at line 506 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References Arcane::Accelerator::Impl::GenericFilteringIf::apply(), Arcane::SpanImpl< T, SizeType, Extent >::data(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
applyWithIndex()
template<typename SelectLambda, typename SetterLambda> void Arcane::Accelerator::GenericFilterer::applyWithIndex (Int32 nb_value, const SelectLambda & select_lambda, const SetterLambda & setter_lambda, const TraceInfo & trace_info = TraceInfo()) inline
Applies a filter with selection based on an index.
This method allows filtering by specifying a lambda function for both selection and assignment. The prototype for these lambdas is:
auto select_lambda = [=] ARCCORE_HOST_DEVICE (Int32 index) -> bool;
auto setter_lambda = [=] ARCCORE_HOST_DEVICE (Int32 input_index,Int32 output_index) -> void;
For example, if you want to copy the input array into output whose values are greater than 25.0.
SmallSpan<Real> input = ...;
SmallSpan<Real> output = ...;
auto select_lambda = [=] ARCCORE_HOST_DEVICE (Int32 index) -> bool
{
  return input[index] > 25.0;
};
auto setter_lambda = [=] ARCCORE_HOST_DEVICE (Int32 input_index,Int32 output_index)
{
  output[output_index] = input[input_index];
};
Arcane::Accelerator::RunQueue* queue = ...;
Arcane::Accelerator::GenericFilterer filterer(queue);
filterer.applyWithIndex(input.size(), select_lambda, setter_lambda);
Int32 nb_out = filterer.nbOutputElement();
The memory regions associated with the input and output values must not overlap.
Definition at line 574 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References Arcane::Accelerator::Impl::GenericFilteringIf::apply().
Referenced by Arcane::Materials::MeshMaterialVariableIndexer::transformCells().
nbOutputElement()
Int32 Arcane::Accelerator::GenericFilterer::nbOutputElement () inline
Number of output elements.
This method performs a barrier before retrieving the value.
Definition at line 592 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
Referenced by Arcane::Materials::MeshMaterialVariableIndexer::transformCells().
The documentation for this class was generated from the following file:
arccore/src/accelerator/arccore/accelerator/GenericFilterer.h