Alien: Block related API
Block related API
Matrix Constructor
Topics
Space related functions.
Classes
class Alien::Block
Block elements for block matrices.
class Alien::BlockSizeVector
Block elements for block vectors.
class Alien::BlockSizeVectorFiller
Block vector filler.
class Alien::IBlockBuilder
Interface for non uniform block elements.
class Alien::VBlock
Variable size block elements for block matrices.
class Alien::VBlockImpl
Compute block offsets for variable block elements.
class Alien::VBlockSizes
Compute the actual size of variable block size algebraic elements.
Functions
void Alien::Move::MatrixData::setBlockInfos (const Integer block_size)
void Alien::Move::MatrixData::setBlockInfos (const Block *block)
void Alien::Move::MatrixData::setBlockInfos (const VBlock *block)
Block const * Alien::Move::MatrixData::block () const
VBlock const * Alien::Move::MatrixData::vblock () const
void Alien::Move::MatrixData::free ()
void Alien::Move::MatrixData::clear ()
void Alien::Move::MatrixData::visit (ICopyOnWriteMatrix &) const
void Alien::Move::VectorData::setBlockInfos (const Integer block_size)
void Alien::Move::VectorData::setBlockInfos (const Block *block)
void Alien::Move::VectorData::setBlockInfos (const VBlock *block)
const Block * Alien::Move::VectorData::block () const
const VBlock * Alien::Move::VectorData::vblock () const
void Alien::Move::VectorData::free ()
void Alien::Move::VectorData::clear ()
void Alien::Move::VectorData::visit (ICopyOnWriteVector &) const
Detailed Description
Function Documentation
block() [1/2]
const Block * Alien::Move::MatrixData::block () const
Definition at line 105 of file MatrixData.cc.
block() [2/2]
const Block * Alien::Move::VectorData::block () const
Definition at line 156 of file VectorData.cc.
clear() [1/2]
void Alien::Move::MatrixData::clear ()
Clean all internal data structures.
Internal data are cleared, not deleted.
Definition at line 152 of file MatrixData.cc.
Referenced by operator=().
clear() [2/2]
void Alien::Move::VectorData::clear ()
Clean all internal data structures.
Internal data are cleared, not deleted.
Definition at line 125 of file VectorData.cc.
References Alien::MultiVectorImpl::clear(), and impl().
Referenced by operator=().
free() [1/2]
void Alien::Move::MatrixData::free ()
}@
Delete all internal data structures
Definition at line 145 of file MatrixData.cc.
Referenced by operator=().
free() [2/2]
void Alien::Move::VectorData::free ()
}@
Delete all internal data structures
Definition at line 118 of file VectorData.cc.
References Alien::MultiVectorImpl::free(), and impl().
Referenced by operator=().
setBlockInfos() [1/6]
void Alien::Move::MatrixData::setBlockInfos (const Block * block)
Definition at line 127 of file MatrixData.cc.
setBlockInfos() [2/6]
void Alien::Move::MatrixData::setBlockInfos (const Integer block_size)
Definition at line 120 of file MatrixData.cc.
setBlockInfos() [3/6]
void Alien::Move::MatrixData::setBlockInfos (const VBlock * block)
Definition at line 136 of file MatrixData.cc.
setBlockInfos() [4/6]
void Alien::Move::VectorData::setBlockInfos (const Block * block)
Definition at line 100 of file VectorData.cc.
setBlockInfos() [5/6]
void Alien::Move::VectorData::setBlockInfos (const Integer block_size)
Definition at line 83 of file VectorData.cc.
setBlockInfos() [6/6]
void Alien::Move::VectorData::setBlockInfos (const VBlock * block)
Definition at line 109 of file VectorData.cc.
vblock() [1/2]
const VBlock * Alien::Move::MatrixData::vblock () const
Definition at line 113 of file MatrixData.cc.
vblock() [2/2]
const VBlock * Alien::Move::VectorData::vblock () const
Definition at line 164 of file VectorData.cc.
visit() [1/2]
void Alien::Move::MatrixData::visit (ICopyOnWriteMatrix & m) const virtual
Handle for visitor pattern
Implements Alien::IMatrix.
Definition at line 159 of file MatrixData.cc.
Referenced by operator=().
visit() [2/2]
void Alien::Move::VectorData::visit (ICopyOnWriteVector & v) const virtual
Handle for visitor pattern
Implements Alien::IVector.
Definition at line 132 of file VectorData.cc.
Referenced by operator=().