Arcane: Arcane::Accelerator::AcceleratorMemoryAllocatorBase Class Reference
Arcane::Accelerator::AcceleratorMemoryAllocatorBase Class Reference
Base class of a specific allocator for accelerator.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/common/arccore/common/accelerator/internal/AcceleratorMemoryAllocatorBase.h>
Classes
class IUnderlyingAllocator
Public Types
enum class MemoryPoolFlags { UVM = 1 , Device = 2 , HostPinned = 4 }
List of flags for the memory pool to activate.
using IMemoryPoolAllocator = Arcane::Impl::IMemoryPoolAllocator
using BaseClass = AlignedMemoryAllocator
Public Member Functions
AcceleratorMemoryAllocatorBase (const String &allocator_name, IUnderlyingAllocator *underlying_allocator)
void finalize (ITraceMng *tm)
bool hasRealloc (MemoryAllocationArgs) const final
Indicates whether the allocator supports realloc semantics.
AllocatedMemoryInfo allocate (MemoryAllocationArgs args, Int64 new_size) final
Allocates memory for new_size bytes and returns the pointer.
AllocatedMemoryInfo reallocate (MemoryAllocationArgs args, AllocatedMemoryInfo current_info, Int64 new_size) final
Reallocates memory for new_size bytes and returns the pointer.
void deallocate (MemoryAllocationArgs args, AllocatedMemoryInfo mem_info) final
Frees the memory whose base address is ptr.
Int64 adjustedCapacity (MemoryAllocationArgs args, Int64 wanted_capacity, Int64 element_size) const final
Adjusts the capacity based on the element size.
eMemoryResource memoryResource () const final
Memory resource provided by the allocator.
void copyMemory (MemoryAllocationArgs args, AllocatedMemoryInfo destination, AllocatedMemoryInfo source) final
Copies memory between two regions.
IMemoryPool * memoryPool ()
Public Member Functions inherited from Arcane::AlignedMemoryAllocator
bool hasRealloc (MemoryAllocationArgs) const override
Indicates whether the allocator supports realloc semantics.
AllocatedMemoryInfo allocate (MemoryAllocationArgs args, Int64 new_size) override
AllocatedMemoryInfo reallocate (MemoryAllocationArgs args, AllocatedMemoryInfo current_ptr, Int64 new_size) override
Reallocates memory for new_size bytes and returns the pointer.
void deallocate (MemoryAllocationArgs args, AllocatedMemoryInfo ptr) override
Frees the memory whose base address is ptr.
Int64 adjustedCapacity (MemoryAllocationArgs args, Int64 wanted_capacity, Int64 element_size) const override
Adjusts the capacity based on the element size.
size_t guaranteedAlignment (MemoryAllocationArgs) const override
Value of the alignment guaranteed by the allocator.
eMemoryResource memoryResource () const override
Memory resource provided by the allocator.
Public Member Functions inherited from Arcane::IMemoryAllocator
virtual ~IMemoryAllocator ()=default
Destroys the allocator.
virtual size_t guarantedAlignment (MemoryAllocationArgs args) const
Value of the alignment guaranteed by the allocator.
virtual void notifyMemoryArgsChanged (MemoryAllocationArgs old_args, MemoryAllocationArgs new_args, AllocatedMemoryInfo ptr)
Notifies of a change in instance-specific arguments.
virtual bool isCollective () const
Indicates whether calls to the allocator must be performed collectively.
Protected Member Functions
virtual void _applyHint (void *ptr, size_t new_size, MemoryAllocationArgs args)
virtual void _removeHint (void *ptr, size_t new_size, MemoryAllocationArgs args)
void _doInitializeUVM (bool default_use_memory_pool=false)
Initialization for UVM memory.
void _doInitializeHostPinned (bool default_use_memory_pool=false)
Initialization for HostPinned memory.
void _doInitializeDevice (bool default_use_memory_pool=false)
Initialization for Device memory.
void _setTraceLevel (Int32 v)
Protected Member Functions inherited from Arcane::AlignedMemoryAllocator
AlignedMemoryAllocator (Int32 alignment)
Private Member Functions
void _setUseMemoryPool (bool is_used)
Private Attributes
Impl::MemoryTracerWrapper m_tracer
std::unique_ptr< IUnderlyingAllocator > m_direct_sub_allocator
Arcane::Impl::MemoryPool m_memory_pool
IMemoryPoolAllocator * m_sub_allocator = nullptr
bool m_use_memory_pool = false
String m_allocator_name
std::atomic< Int32 > m_nb_reallocate = 0
std::atomic< Int64 > m_reallocate_size = 0
Int32 m_print_level = 0
BlockAllocatorWrapper m_block_wrapper
Additional Inherited Members
Static Public Member Functions inherited from Arcane::AlignedMemoryAllocator
static constexpr Integer simdAlignment ()
Alignment for structures using vectorization.
static constexpr Integer cacheLineAlignment ()
Alignment for a cache line.
static AlignedMemoryAllocator * Simd ()
Allocator guaranteeing alignment to use vectorization on the target platform.
static AlignedMemoryAllocator * CacheLine ()
Allocator guaranteeing alignment to a cache line.
Detailed Description
Base class of a specific allocator for accelerator.
Definition at line 131 of file AcceleratorMemoryAllocatorBase.h.
Member Typedef Documentation
BaseClass
using Arcane::Accelerator::AcceleratorMemoryAllocatorBase::BaseClass = AlignedMemoryAllocator
Definition at line 137 of file AcceleratorMemoryAllocatorBase.h.
IMemoryPoolAllocator
using Arcane::Accelerator::AcceleratorMemoryAllocatorBase::IMemoryPoolAllocator = Arcane::Impl::IMemoryPoolAllocator
Definition at line 136 of file AcceleratorMemoryAllocatorBase.h.
Member Enumeration Documentation
MemoryPoolFlags
enum class Arcane::Accelerator::AcceleratorMemoryAllocatorBase::MemoryPoolFlags strong
List of flags for the memory pool to activate.
Definition at line 142 of file AcceleratorMemoryAllocatorBase.h.
Constructor & Destructor Documentation
AcceleratorMemoryAllocatorBase()
Arcane::Accelerator::AcceleratorMemoryAllocatorBase::AcceleratorMemoryAllocatorBase (const String & allocator_name, IUnderlyingAllocator * underlying_allocator)
Definition at line 46 of file AcceleratorMemoryAllocatorBase.cc.
Member Function Documentation
_applyHint()
virtual void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_applyHint (void * ptr, size_t new_size, MemoryAllocationArgs args) inline protected virtual
Definition at line 211 of file AcceleratorMemoryAllocatorBase.h.
_doInitializeDevice()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_doInitializeDevice (bool default_use_memory_pool = false) protected
Initialization for Device memory.
Definition at line 146 of file AcceleratorMemoryAllocatorBase.cc.
_doInitializeHostPinned()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_doInitializeHostPinned (bool default_use_memory_pool = false) protected
Initialization for HostPinned memory.
Definition at line 135 of file AcceleratorMemoryAllocatorBase.cc.
_doInitializeUVM()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_doInitializeUVM (bool default_use_memory_pool = false) protected
Initialization for UVM memory.
Definition at line 119 of file AcceleratorMemoryAllocatorBase.cc.
References Arcane::platform::getPageSize().
_removeHint()
virtual void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_removeHint (void * ptr, size_t new_size, MemoryAllocationArgs args) inline protected virtual
Definition at line 213 of file AcceleratorMemoryAllocatorBase.h.
_setTraceLevel()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_setTraceLevel (Int32 v) inline protected
Definition at line 240 of file AcceleratorMemoryAllocatorBase.h.
_setUseMemoryPool()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::_setUseMemoryPool (bool is_used) private
Definition at line 157 of file AcceleratorMemoryAllocatorBase.cc.
adjustedCapacity()
Int64 Arcane::Accelerator::AcceleratorMemoryAllocatorBase::adjustedCapacity (MemoryAllocationArgs args, Int64 wanted_capacity, Int64 element_size) const inline final virtual
Adjusts the capacity based on the element size.
This method is used to optionally modify the number of allocated elements based on their size. This allows, for example, aligned allocators to ensure that the number of elements allocated is a multiple of this alignment.
Implements Arcane::IMemoryAllocator.
Definition at line 196 of file AcceleratorMemoryAllocatorBase.h.
References Arcane::AlignedMemoryAllocator::adjustedCapacity().
allocate()
AllocatedMemoryInfo Arcane::Accelerator::AcceleratorMemoryAllocatorBase::allocate (MemoryAllocationArgs args, Int64 new_size) inline final virtual
Allocates memory for new_size bytes and returns the pointer.
The semantics are equivalent to malloc():
new_size can be zero, in which case the returned pointer is either null or a specific value
the returned pointer may be null if the memory could not be allocated.
Implements Arcane::IMemoryAllocator.
Definition at line 171 of file AcceleratorMemoryAllocatorBase.h.
References ARCCORE_FATAL.
Referenced by reallocate().
copyMemory()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::copyMemory (MemoryAllocationArgs args, AllocatedMemoryInfo destination, AllocatedMemoryInfo source) inline final virtual
Copies memory between two regions.
The default implementation uses std::memcpy().
Parameters
args memory region arguments
destination destination of the copy
source source of the copy
Reimplemented from Arcane::IMemoryAllocator.
Definition at line 202 of file AcceleratorMemoryAllocatorBase.h.
deallocate()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::deallocate (MemoryAllocationArgs args, AllocatedMemoryInfo ptr) inline final virtual
Frees the memory whose base address is ptr.
The pointer ptr must have been allocated via a call to allocate() or reallocate() on this instance.
The semantics of this method are equivalent to free(), and thus ptr may be null, in which case no operation is performed.
Implements Arcane::IMemoryAllocator.
Definition at line 183 of file AcceleratorMemoryAllocatorBase.h.
Referenced by reallocate().
finalize()
void Arcane::Accelerator::AcceleratorMemoryAllocatorBase::finalize (ITraceMng * tm)
Definition at line 61 of file AcceleratorMemoryAllocatorBase.cc.
hasRealloc()
bool Arcane::Accelerator::AcceleratorMemoryAllocatorBase::hasRealloc (MemoryAllocationArgs) const inline final virtual
Indicates whether the allocator supports realloc semantics.
Default C allocators (malloc/realloc/free) obviously support realloc, but this is not necessarily the case for specific allocators with memory alignment (such as posix_memalign).
Reimplemented from Arcane::IMemoryAllocator.
Definition at line 170 of file AcceleratorMemoryAllocatorBase.h.
memoryPool()
IMemoryPool * Arcane::Accelerator::AcceleratorMemoryAllocatorBase::memoryPool () inline
Definition at line 207 of file AcceleratorMemoryAllocatorBase.h.
memoryResource()
eMemoryResource Arcane::Accelerator::AcceleratorMemoryAllocatorBase::memoryResource () const inline final virtual
Memory resource provided by the allocator.
Reimplemented from Arcane::IMemoryAllocator.
Definition at line 201 of file AcceleratorMemoryAllocatorBase.h.
reallocate()
AllocatedMemoryInfo Arcane::Accelerator::AcceleratorMemoryAllocatorBase::reallocate (MemoryAllocationArgs args, AllocatedMemoryInfo current_ptr, Int64 new_size) final virtual
Reallocates memory for new_size bytes and returns the pointer.
The pointer current_ptr must have been allocated via a call to allocate() or reallocate() on this instance.
The semantics of this method are equivalent to realloc():
current_ptr may be null, in which case this call is equivalent to allocate().
the returned pointer may be null if the memory could not be allocated.
Implements Arcane::IMemoryAllocator.
Definition at line 85 of file AcceleratorMemoryAllocatorBase.cc.
References allocate(), Arcane::AllocatedMemoryInfo::baseAddress(), Arcane::AllocatedMemoryInfo::capacity(), deallocate(), Arcane::platform::getStackTrace(), Arcane::String::null(), and Arcane::AllocatedMemoryInfo::size().
Member Data Documentation
m_allocator_name
String Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_allocator_name private
Definition at line 223 of file AcceleratorMemoryAllocatorBase.h.
m_block_wrapper
BlockAllocatorWrapper Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_block_wrapper private
Definition at line 227 of file AcceleratorMemoryAllocatorBase.h.
m_direct_sub_allocator
std::unique_ptr<IUnderlyingAllocator> Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_direct_sub_allocator private
Definition at line 219 of file AcceleratorMemoryAllocatorBase.h.
m_memory_pool
Arcane::Impl::MemoryPool Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_memory_pool private
Definition at line 220 of file AcceleratorMemoryAllocatorBase.h.
m_nb_reallocate
std::atomic<Int32> Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_nb_reallocate = 0 private
Definition at line 224 of file AcceleratorMemoryAllocatorBase.h.
m_print_level
Int32 Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_print_level = 0 private
Definition at line 226 of file AcceleratorMemoryAllocatorBase.h.
m_reallocate_size
std::atomic<Int64> Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_reallocate_size = 0 private
Definition at line 225 of file AcceleratorMemoryAllocatorBase.h.
m_sub_allocator
IMemoryPoolAllocator* Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_sub_allocator = nullptr private
Definition at line 221 of file AcceleratorMemoryAllocatorBase.h.
m_tracer
Impl::MemoryTracerWrapper Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_tracer private
Definition at line 218 of file AcceleratorMemoryAllocatorBase.h.
m_use_memory_pool
bool Arcane::Accelerator::AcceleratorMemoryAllocatorBase::m_use_memory_pool = false private
Definition at line 222 of file AcceleratorMemoryAllocatorBase.h.
The documentation for this class was generated from the following files:
AcceleratorMemoryAllocatorBase.h
AcceleratorMemoryAllocatorBase.cc