Arcane: Arcane::Materials::IMeshMaterialMngInternal Class Reference
Arcane::Materials::IMeshMaterialMngInternal Class Reference abstract
Internal Arcane API for 'IMeshMaterialMng'.
#include <arcane/core/materials/internal/IMeshMaterialMngInternal.h>
Public Member Functions
virtual void addVariable (IMeshMaterialVariable *var)=0
Adds the variable var.
virtual void removeVariable (IMeshMaterialVariable *var)=0
Removes the variable var.
virtual MeshMaterialModifierImpl * modifier ()=0
Modifier implementation.
virtual ConstArrayView< MeshMaterialVariableIndexer * > variablesIndexer ()=0
List of information to index material variables.
virtual IMeshMaterialVariableSynchronizer * allCellsMatEnvSynchronizer ()=0
Synchronizer for material and medium variables across all cells.
virtual IMeshMaterialVariableSynchronizer * allCellsEnvOnlySynchronizer ()=0
Synchronizer for medium-only variables across all cells.
virtual AllCellToAllEnvCellContainer * getAllCellToAllEnvCellContainer () const =0
Returns the "connectivity" table CellLocalId -> AllEnvCell intended to be used in a RUNCOMMAND_ENUMERATE_CELL_ALLENVCELL in conjunction with the ENUMERATE_CELL_ALLENVCELL macro.
virtual void createAllCellToAllEnvCell ()=0
Constructs the "connectivity" table CellLocalId -> AllEnvCell intended to be used in a RUNCOMMAND_ENUMERATE_CELL_ALLENVCELL in conjunction with the ENUMERATE_CELL_ALLENVCELL macro.
virtual ComponentItemSharedInfo * componentItemSharedInfo (Int32 level) const =0
ComponentItemSharedInfo instance for a constituent.
virtual RunQueue & runQueue () const =0
Default run queue.
virtual Accelerator::RunQueuePool & asyncRunQueuePool () const =0
List of asynchronous queues.
virtual Real additionalCapacityRatio () const =0
Ratio for additional capacity to allocate when resizing variables.
virtual bool isUseAcceleratorForConstituentItemVector () const =0
Indicates whether the accelerator API is used to position the values of ConstituentItemVectorImpl.
virtual RunQueue runQueue (Accelerator::eExecutionPolicy policy) const =0
Run queue for the policy.
virtual SmallSpan< const Int32 > identitySelectionView () const =0
View of the array corresponding to a selection across all entities.
Detailed Description
Internal Arcane API for 'IMeshMaterialMng'.
Definition at line 33 of file IMeshMaterialMngInternal.h.
Member Function Documentation
additionalCapacityRatio()
virtual Real Arcane::Materials::IMeshMaterialMngInternal::additionalCapacityRatio () const pure virtual
Ratio for additional capacity to allocate when resizing variables.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
Referenced by Arcane::Materials::ItemMaterialVariableBase< Traits >::buildFromManager().
addVariable()
virtual void Arcane::Materials::IMeshMaterialMngInternal::addVariable (IMeshMaterialVariable * var) pure virtual
Adds the variable var.
This method must not be called directly. References to the variables call it if necessary. This method must be called with the variableLock() active.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
Referenced by Arcane::Materials::MeshMaterialVariableCommonStaticImpl< TrueType >::getReference().
allCellsEnvOnlySynchronizer()
virtual IMeshMaterialVariableSynchronizer * Arcane::Materials::IMeshMaterialMngInternal::allCellsEnvOnlySynchronizer () pure virtual
Synchronizer for medium-only variables across all cells.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
allCellsMatEnvSynchronizer()
virtual IMeshMaterialVariableSynchronizer * Arcane::Materials::IMeshMaterialMngInternal::allCellsMatEnvSynchronizer () pure virtual
Synchronizer for material and medium variables across all cells.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
asyncRunQueuePool()
virtual Accelerator::RunQueuePool & Arcane::Materials::IMeshMaterialMngInternal::asyncRunQueuePool () const pure virtual
List of asynchronous queues.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
componentItemSharedInfo()
virtual ComponentItemSharedInfo * Arcane::Materials::IMeshMaterialMngInternal::componentItemSharedInfo (Int32 level) const pure virtual
ComponentItemSharedInfo instance for a constituent.
The value of level must be LEVEL_MATERIAL or LEVEL_ENVIRONMENT
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
createAllCellToAllEnvCell()
virtual void Arcane::Materials::IMeshMaterialMngInternal::createAllCellToAllEnvCell () pure virtual
Constructs the "connectivity" table CellLocalId -> AllEnvCell intended to be used in a RUNCOMMAND_ENUMERATE_CELL_ALLENVCELL in conjunction with the ENUMERATE_CELL_ALLENVCELL macro.
If no allocator is specified, the method platform::getDefaultDataAllocator() is used
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
getAllCellToAllEnvCellContainer()
virtual AllCellToAllEnvCellContainer * Arcane::Materials::IMeshMaterialMngInternal::getAllCellToAllEnvCellContainer () const pure virtual
Returns the "connectivity" table CellLocalId -> AllEnvCell intended to be used in a RUNCOMMAND_ENUMERATE_CELL_ALLENVCELL in conjunction with the ENUMERATE_CELL_ALLENVCELL macro.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
identitySelectionView()
virtual SmallSpan< const Int32 > Arcane::Materials::IMeshMaterialMngInternal::identitySelectionView () const pure virtual
View of the array corresponding to a selection across all entities.
Returns a view of an array v sized to the number of cells in the mesh and having v[i] == i for all i. This array is invalidated if the number of cells changes. It is used notably for indexed selections (via the ConstituentItemIndexedSelectionView class).
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
isUseAcceleratorForConstituentItemVector()
virtual bool Arcane::Materials::IMeshMaterialMngInternal::isUseAcceleratorForConstituentItemVector () const pure virtual
Indicates whether the accelerator API is used to position the values of ConstituentItemVectorImpl.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
modifier()
virtual MeshMaterialModifierImpl * Arcane::Materials::IMeshMaterialMngInternal::modifier () pure virtual
Modifier implementation.
This modifier allows changing the list of cells composing a medium or a material. This method should in principle not be called directly. To modify, it is better to use an instance of MeshMaterialModifier which guarantees that the update functions are called.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
removeVariable()
virtual void Arcane::Materials::IMeshMaterialMngInternal::removeVariable (IMeshMaterialVariable * var) pure virtual
Removes the variable var.
This method must not be called directly. References to the variables call it if necessary. This method must be called with the variableLock() active. Note that this function does not call the delete operator on var.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
runQueue() [1/2]
virtual RunQueue & Arcane::Materials::IMeshMaterialMngInternal::runQueue () const pure virtual
Default run queue.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
runQueue() [2/2]
virtual RunQueue Arcane::Materials::IMeshMaterialMngInternal::runQueue (Accelerator::eExecutionPolicy policy) const pure virtual
Run queue for the policy.
If policy equals eExecutionPolicy::None, then runQueue() is returned. The other possible values are eExecutionPolicy::Sequential or eExecutionPolicy::Thread.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
variablesIndexer()
virtual ConstArrayView< MeshMaterialVariableIndexer * > Arcane::Materials::IMeshMaterialMngInternal::variablesIndexer () pure virtual
List of information to index material variables.
Implemented in Arcane::Materials::MeshMaterialMng::InternalApi.
Referenced by Arcane::Materials::ItemMaterialVariableBase< Traits >::buildFromManager(), and Arcane::Materials::MeshMaterialVariableCommonStaticImpl< TrueType >::getReference().
The documentation for this class was generated from the following file:
IMeshMaterialMngInternal.h