Arcane: Arcane::Real2x2Proxy Class Reference
Arcane::Real2x2Proxy Class Reference
Proxy of type 'Real2x2'.
#include <arcane/utils/Real2x2Proxy.h>
Public Member Functions
Real2x2Proxy (Real2x2 &value, const MemoryAccessInfo &info)
Constructs the pair (ax,ay).
Real2x2Proxy (const Real2x2Proxy &f)
Constructs a pair identical to f.
const Real2x2Proxy & operator= (const Real2x2Proxy &f)
const Real2x2Proxy & operator= (Real2x2 f)
const Real2x2Proxy & operator= (Real v)
Assigns the triplet (v,v,v) to the instance.
Real2x2 copy () const
Returns a copy of the pair.
Real2x2Proxy & reset ()
Resets the pair using default constructors.
Real2x2Proxy & assign (Real2 ax, Real2 ay)
Assigns the triplet (ax,ay,az) to the instance.
Real2x2Proxy & assign (Real2x2Proxy f)
Copies the pair f.
operator const Real2x2 & () const
bool isNearlyZero () const
Compares the matrix with the zero matrix.
istream & assign (istream &i)
Reads the matrix from the stream i The matrix is read in the form of three Real2s.
ostream & print (ostream &o) const
Writes the pair to the stream o readable by an assign().
ostream & printXy (ostream &o) const
Writes the pair to the stream o in the form (x,y,z).
Real2x2Proxy & add (Real2x2 b)
Adds b to the pair.
Real2x2Proxy & sub (Real2x2 b)
Subtracts b from the pair.
Real2x2Proxy & div (Real2x2 b)
Multiplies each component of the pair by the corresponding component of b.
Real2x2Proxy & addSame (Real2 b)
Adds b to each component of the pair.
Real2x2Proxy & subSame (Real2 b)
Subtracts b from each component of the pair.
Real2x2Proxy & mulSame (Real2 b)
Multiplies each component of the pair by b.
Real2x2Proxy & divSame (Real2 b)
Divides each component of the pair by b.
Real2x2Proxy & operator+= (Real2x2 b)
Adds b to the pair.
Real2x2Proxy & operator-= (Real2x2 b)
Subtracts b from the pair.
void operator*= (Real b)
Multiplies each component of the pair by the corresponding component of b.
void operator/= (Real b)
Divides each component of the pair by the corresponding component of b.
Real2x2 operator+ (Real2x2 b) const
Creates a pair that equals this pair added to b.
Real2x2 operator- (Real2x2 b) const
Creates a pair that equals b subtracted from this pair.
Real2x2 operator- () const
Creates a tensor opposite to the current tensor.
const Real2x2 & getValue () const
Creates a pair that equals this pair whose each component has been multiplied by the corresponding component of b.
Real2x2 & getValueMutable ()
Public Attributes
Real2Proxy x
First component.
Real2Proxy y
Second component.
Static Private Member Functions
static bool _eq (Real a, Real b)
Compares the values of a and b with the TypeEqualT comparator.
Private Attributes
Real2x2 & m_value
MemoryAccessInfo m_info
Related Symbols
(Note that these are not member symbols.)
ostream & operator<< (ostream &o, const Real2x2Proxy &t)
Writes the pair t to the stream o.
istream & operator>> (istream &i, Real2x2Proxy &t)
Reads the pair t from the stream o.
Detailed Description
Proxy of type 'Real2x2'.
Definition at line 32 of file Real2x2Proxy.h.
Constructor & Destructor Documentation
Real2x2Proxy() [1/2]
Arcane::Real2x2Proxy::Real2x2Proxy (Real2x2 & value, const MemoryAccessInfo & info) inline
Constructs the pair (ax,ay).
Definition at line 37 of file Real2x2Proxy.h.
References x, and y.
Referenced by add(), addSame(), assign(), assign(), div(), divSame(), mulSame(), operator+=(), operator-=(), operator<<(), operator=(), operator>>(), Real2x2Proxy(), reset(), sub(), and subSame().
Real2x2Proxy() [2/2]
Arcane::Real2x2Proxy::Real2x2Proxy (const Real2x2Proxy & f) inline
Constructs a pair identical to f.
Definition at line 45 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
Member Function Documentation
_eq()
bool Arcane::Real2x2Proxy::_eq (Real a, Real b) inline static private
Compares the values of a and b with the TypeEqualT comparator.
Return values
true if a and b are equal,
false otherwise.
Definition at line 272 of file Real2x2Proxy.h.
References Arcane::TypeEqualT< T >::isEqual().
add()
Real2x2Proxy & Arcane::Real2x2Proxy::add (Real2x2 b) inline
Adds b to the pair.
Definition at line 147 of file Real2x2Proxy.h.
References Real2x2Proxy(), Arcane::Real2x2::x, x, Arcane::Real2x2::y, and y.
Referenced by operator+=().
addSame()
Real2x2Proxy & Arcane::Real2x2Proxy::addSame (Real2 b) inline
Adds b to each component of the pair.
Definition at line 174 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
assign() [1/2]
Real2x2Proxy & Arcane::Real2x2Proxy::assign (Real2 ax, Real2 ay) inline
Assigns the triplet (ax,ay,az) to the instance.
Definition at line 95 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
Referenced by operator>>().
assign() [2/2]
Real2x2Proxy & Arcane::Real2x2Proxy::assign (Real2x2Proxy f) inline
Copies the pair f.
Definition at line 103 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
copy()
Real2x2 Arcane::Real2x2Proxy::copy () const inline
Returns a copy of the pair.
Definition at line 85 of file Real2x2Proxy.h.
References getValue().
div()
Real2x2Proxy & Arcane::Real2x2Proxy::div (Real2x2 b) inline
Multiplies each component of the pair by the corresponding component of b.
Divides each component of the pair by the corresponding component of b
Definition at line 166 of file Real2x2Proxy.h.
References Real2x2Proxy(), Arcane::Real2x2::x, x, Arcane::Real2x2::y, and y.
divSame()
Real2x2Proxy & Arcane::Real2x2Proxy::divSame (Real2 b) inline
Divides each component of the pair by b.
Definition at line 198 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
getValue()
const Real2x2 & Arcane::Real2x2Proxy::getValue () const inline
Creates a pair that equals this pair whose each component has been multiplied by the corresponding component of b.
Creates a pair that equals this pair whose each component has been divided by the corresponding component of b.
Definition at line 254 of file Real2x2Proxy.h.
Referenced by copy(), and Arcane::operator<().
getValueMutable()
Real2x2 & Arcane::Real2x2Proxy::getValueMutable () inline
Definition at line 259 of file Real2x2Proxy.h.
isNearlyZero()
bool Arcane::Real2x2Proxy::isNearlyZero () const inline
Compares the matrix with the zero matrix.
The matrix is zero if and only if each of its components is less than a given epsilon. The epsilon value used is that of float_info<value_type>::nearlyEpsilon():
\[A=0 \Leftrightarrow |A.x|<\epsilon,|A.y|<\epsilon\]
Return values
true if the matrix is equal to the zero matrix,
false otherwise.
Definition at line 129 of file Real2x2Proxy.h.
References x, and y.
mulSame()
Real2x2Proxy & Arcane::Real2x2Proxy::mulSame (Real2 b) inline
Multiplies each component of the pair by b.
Definition at line 190 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
operator const Real2x2 &()
Arcane::Real2x2Proxy::operator const Real2x2 & () const inline
Definition at line 109 of file Real2x2Proxy.h.
operator*=()
void Arcane::Real2x2Proxy::operator*= (Real b) inline
Multiplies each component of the pair by the corresponding component of b.
Multiplies each component of the matrix by the real b
Definition at line 215 of file Real2x2Proxy.h.
References x, and y.
operator+()
Real2x2 Arcane::Real2x2Proxy::operator+ (Real2x2 b) const inline
Creates a pair that equals this pair added to b.
Definition at line 232 of file Real2x2Proxy.h.
References Arcane::Real2x2::x, x, Arcane::Real2x2::y, and y.
operator+=()
Real2x2Proxy & Arcane::Real2x2Proxy::operator+= (Real2x2 b) inline
Adds b to the pair.
Definition at line 206 of file Real2x2Proxy.h.
References add(), and Real2x2Proxy().
operator-() [1/2]
Real2x2 Arcane::Real2x2Proxy::operator- () const inline
Creates a tensor opposite to the current tensor.
Definition at line 238 of file Real2x2Proxy.h.
References x, and y.
operator-() [2/2]
Real2x2 Arcane::Real2x2Proxy::operator- (Real2x2 b) const inline
Creates a pair that equals b subtracted from this pair.
Definition at line 235 of file Real2x2Proxy.h.
References Arcane::Real2x2::x, x, Arcane::Real2x2::y, and y.
operator-=()
Real2x2Proxy & Arcane::Real2x2Proxy::operator-= (Real2x2 b) inline
Subtracts b from the pair.
Definition at line 209 of file Real2x2Proxy.h.
References Real2x2Proxy(), and sub().
operator/=()
void Arcane::Real2x2Proxy::operator/= (Real b) inline
Divides each component of the pair by the corresponding component of b.
Divides each component of the matrix by the real b
Definition at line 225 of file Real2x2Proxy.h.
References x, and y.
operator=() [1/3]
const Real2x2Proxy & Arcane::Real2x2Proxy::operator= (const Real2x2Proxy & f) inline
Definition at line 51 of file Real2x2Proxy.h.
operator=() [2/3]
const Real2x2Proxy & Arcane::Real2x2Proxy::operator= (Real v) inline
Assigns the triplet (v,v,v) to the instance.
Definition at line 65 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
operator=() [3/3]
const Real2x2Proxy & Arcane::Real2x2Proxy::operator= (Real2x2 f) inline
Definition at line 57 of file Real2x2Proxy.h.
reset()
Real2x2Proxy & Arcane::Real2x2Proxy::reset () inline
Resets the pair using default constructors.
Definition at line 88 of file Real2x2Proxy.h.
References Arcane::Real2x2::null(), and Real2x2Proxy().
sub()
Real2x2Proxy & Arcane::Real2x2Proxy::sub (Real2x2 b) inline
Subtracts b from the pair.
Definition at line 155 of file Real2x2Proxy.h.
References Real2x2Proxy(), Arcane::Real2x2::x, x, Arcane::Real2x2::y, and y.
Referenced by operator-=().
subSame()
Real2x2Proxy & Arcane::Real2x2Proxy::subSame (Real2 b) inline
Subtracts b from each component of the pair.
Definition at line 182 of file Real2x2Proxy.h.
References Real2x2Proxy(), x, and y.
Friends And Related Symbol Documentation
operator<<()
ostream & operator<< (ostream & o, const Real2x2Proxy & t) related
Writes the pair t to the stream o.
Definition at line 323 of file Real2x2Proxy.h.
References operator<<(), printXy(), and Real2x2Proxy().
Referenced by operator<<().
operator>>()
istream & operator>> (istream & i, Real2x2Proxy & t) related
Reads the pair t from the stream o.
Definition at line 334 of file Real2x2Proxy.h.
References assign(), and Real2x2Proxy().
Member Data Documentation
m_info
MemoryAccessInfo Arcane::Real2x2Proxy::m_info private
Definition at line 80 of file Real2x2Proxy.h.
m_value
Real2x2& Arcane::Real2x2Proxy::m_value private
Definition at line 79 of file Real2x2Proxy.h.
x
Real2Proxy Arcane::Real2x2Proxy::x
First component.
Definition at line 74 of file Real2x2Proxy.h.
Referenced by add(), addSame(), assign(), assign(), div(), divSame(), isNearlyZero(), mulSame(), Arcane::operator*(), Arcane::operator*(), operator*=(), operator+(), operator-(), operator-(), Arcane::operator/(), operator/=(), operator=(), Real2x2Proxy(), Real2x2Proxy(), sub(), and subSame().
y
Real2Proxy Arcane::Real2x2Proxy::y
Second component.
Definition at line 75 of file Real2x2Proxy.h.
Referenced by add(), addSame(), assign(), assign(), div(), divSame(), isNearlyZero(), mulSame(), Arcane::operator*(), Arcane::operator*(), operator*=(), operator+(), operator-(), operator-(), Arcane::operator/(), operator/=(), operator=(), Real2x2Proxy(), Real2x2Proxy(), sub(), and subSame().
The documentation for this class was generated from the following file:
Real2x2Proxy.h