Arcane: Arcane::Accelerator::Cuda::CudaRunQueueStream Class Reference
Arcane::Accelerator::Cuda::CudaRunQueueStream Class Reference
Public Member Functions
CudaRunQueueStream (Impl::IRunnerRuntime *runtime, const RunQueueBuildInfo &bi)
void notifyBeginLaunchKernel (Impl::RunCommandImpl &c) override
Notification before command launch.
void notifyEndLaunchKernel (Impl::RunCommandImpl &) override
Notification of command launch completion.
void barrier () override
Blocks until all actions associated with this queue are finished.
bool _barrierNoException () override
Barrier without exception. Returns true in case of error.
void copyMemory (const MemoryCopyArgs &args) override
Performs a copy between two memory regions.
void prefetchMemory (const MemoryPrefetchArgs &args) override
Performs a prefetch of a memory region.
Impl::NativeStream nativeStream () override
Pointer to the internal structure dependent on the implementation.
cudaStream_t trueStream () const
Public Member Functions inherited from Arcane::Accelerator::Impl::IRunQueueStream
virtual void _setSyclLastCommandEvent (void *sycl_event_ptr)
For SYCL, positions the event associated with the last executed command.
Private Attributes
Impl::IRunnerRuntime * m_runtime = nullptr
cudaStream_t m_cuda_stream = nullptr
Detailed Description
Definition at line 508 of file CudaAcceleratorRuntime.cc.
Constructor & Destructor Documentation
CudaRunQueueStream()
Arcane::Accelerator::Cuda::CudaRunQueueStream::CudaRunQueueStream (Impl::IRunnerRuntime * runtime, const RunQueueBuildInfo & bi) inline
Definition at line 513 of file CudaAcceleratorRuntime.cc.
~CudaRunQueueStream()
Arcane::Accelerator::Cuda::CudaRunQueueStream::~CudaRunQueueStream () inline override
Definition at line 523 of file CudaAcceleratorRuntime.cc.
Member Function Documentation
_barrierNoException()
bool Arcane::Accelerator::Cuda::CudaRunQueueStream::_barrierNoException () inline override virtual
Barrier without exception. Returns true in case of error.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 554 of file CudaAcceleratorRuntime.cc.
barrier()
void Arcane::Accelerator::Cuda::CudaRunQueueStream::barrier () inline override virtual
Blocks until all actions associated with this queue are finished.
This includes commands (RunCommandImpl) and other actions such as asynchronous memory copies.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 548 of file CudaAcceleratorRuntime.cc.
Referenced by copyMemory(), and prefetchMemory().
copyMemory()
void Arcane::Accelerator::Cuda::CudaRunQueueStream::copyMemory (const MemoryCopyArgs & args) inline override virtual
Performs a copy between two memory regions.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 558 of file CudaAcceleratorRuntime.cc.
References barrier(), Arcane::ConstMemoryView::bytes(), and Arcane::MutableMemoryView::data().
nativeStream()
Impl::NativeStream Arcane::Accelerator::Cuda::CudaRunQueueStream::nativeStream () inline override virtual
Pointer to the internal structure dependent on the implementation.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 588 of file CudaAcceleratorRuntime.cc.
notifyBeginLaunchKernel()
void Arcane::Accelerator::Cuda::CudaRunQueueStream::notifyBeginLaunchKernel (Impl::RunCommandImpl & command) inline override virtual
Notification before command launch.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 530 of file CudaAcceleratorRuntime.cc.
notifyEndLaunchKernel()
void Arcane::Accelerator::Cuda::CudaRunQueueStream::notifyEndLaunchKernel (Impl::RunCommandImpl & command) inline override virtual
Notification of command launch completion.
In asynchronous mode, the command can continue to run in the background.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 541 of file CudaAcceleratorRuntime.cc.
prefetchMemory()
void Arcane::Accelerator::Cuda::CudaRunQueueStream::prefetchMemory (const MemoryPrefetchArgs & args) inline override virtual
Performs a prefetch of a memory region.
Implements Arcane::Accelerator::Impl::IRunQueueStream.
Definition at line 567 of file CudaAcceleratorRuntime.cc.
References Arcane::Accelerator::DeviceId::asInt32(), barrier(), Arcane::ConstMemoryView::bytes(), and Arcane::Accelerator::DeviceId::isHost().
trueStream()
cudaStream_t Arcane::Accelerator::Cuda::CudaRunQueueStream::trueStream () const inline
Definition at line 595 of file CudaAcceleratorRuntime.cc.
Member Data Documentation
m_cuda_stream
cudaStream_t Arcane::Accelerator::Cuda::CudaRunQueueStream::m_cuda_stream = nullptr private
Definition at line 603 of file CudaAcceleratorRuntime.cc.
m_runtime
Impl::IRunnerRuntime* Arcane::Accelerator::Cuda::CudaRunQueueStream::m_runtime = nullptr private
Definition at line 602 of file CudaAcceleratorRuntime.cc.
The documentation for this class was generated from the following file:
CudaAcceleratorRuntime.cc