Arcane: Arcane::MeshBuildInfo Class Reference
Arcane::MeshBuildInfo Class Reference
Parameters necessary for building a mesh.
#include <arcane/core/MeshBuildInfo.h>
Public Member Functions
MeshBuildInfo (const String &name)
Constructs a default mesh with the name name.
MeshBuildInfo & addFactoryName (const String &factory_name)
Sets the factory name to create this mesh.
MeshBuildInfo & addParallelMng (Ref< IParallelMng > pm)
Sets the parallelism manager to create the mesh.
MeshBuildInfo & addParentGroup (const ItemGroup &parent_group)
Sets the cell group for a sub-mesh.
MeshBuildInfo & addNeedPartitioning (bool v)
Indicates whether the generator needs to call a partitioner.
MeshBuildInfo & addMeshKind (const MeshKind &v)
Sets the mesh characteristics.
const String & name () const
Name of the new mesh.
const String & factoryName () const
Factory name to create the mesh (via IMeshFactory).
Ref< IParallelMng > parallelMngRef () const
Parallelism manager in the case of a new mesh.
const ItemGroup & parentGroup () const
Parent group in the case of a sub-mesh, null otherwise.
bool isNeedPartitioning () const
Indicates if the reader/generator requires partitioning.
const MeshKind meshKind () const
Mesh characteristics.
Private Attributes
String m_name
String m_factory_name
Ref< IParallelMng > m_parallel_mng
ItemGroup m_parent_group
bool m_is_need_partitioning = false
MeshKind m_mesh_kind
Detailed Description
Parameters necessary for building a mesh.
Only the name (name()) is essential. The other parameters are optional depending on the desired creation type. If they are not defined and useful, a default value will be used.
There are two possibilities for creation:
creation of a new mesh. In this case, it is necessary to specify the associated IParallelMng via addParallelMng().
creation of a sub-mesh of an existing mesh. In this case, it is necessary to position the group via addItemGroup(). The associated IParallelMng must be that of the parent mesh. The created sub-mesh will include the cells of this group.
Definition at line 48 of file MeshBuildInfo.h.
Constructor & Destructor Documentation
MeshBuildInfo()
Arcane::MeshBuildInfo::MeshBuildInfo (const String & name) explicit
Constructs a default mesh with the name name.
Definition at line 25 of file MeshBuildInfo.cc.
References name().
Referenced by addFactoryName(), addMeshKind(), addNeedPartitioning(), addParallelMng(), and addParentGroup().
Member Function Documentation
addFactoryName()
MeshBuildInfo & Arcane::MeshBuildInfo::addFactoryName (const String & factory_name)
Sets the factory name to create this mesh.
Definition at line 36 of file MeshBuildInfo.cc.
References MeshBuildInfo().
Referenced by Arcane::ArcaneCaseMeshService::createMesh(), Arcane::MainFactory::createMesh(), Arcane::MainFactory::createSubMesh(), and Arcane::VtkPolyhedralCaseMeshReader::Builder::fillMeshBuildInfo().
addMeshKind()
MeshBuildInfo & Arcane::MeshBuildInfo::addMeshKind (const MeshKind & v)
Sets the mesh characteristics.
Definition at line 76 of file MeshBuildInfo.cc.
References MeshBuildInfo().
Referenced by Arcane::ArcaneCaseMeshService::createMesh(), Arcane::MainFactory::createMesh(), Arcane::mesh::DynamicMeshFactoryBase::createMesh(), and Arcane::VtkPolyhedralCaseMeshReader::Builder::fillMeshBuildInfo().
addNeedPartitioning()
MeshBuildInfo & Arcane::MeshBuildInfo::addNeedPartitioning (bool v)
Indicates whether the generator needs to call a partitioner.
This is the case, for example, if the reader can only generate sequential meshes.
Definition at line 66 of file MeshBuildInfo.cc.
References MeshBuildInfo().
Referenced by Arcane::HoneyComb2DMeshGeneratorService::fillMeshBuildInfo(), Arcane::HoneyComb3DMeshGeneratorService::fillMeshBuildInfo(), and Arcane::VtkPolyhedralCaseMeshReader::Builder::fillMeshBuildInfo().
addParallelMng()
MeshBuildInfo & Arcane::MeshBuildInfo::addParallelMng (Ref< IParallelMng > pm)
Sets the parallelism manager to create the mesh.
Definition at line 46 of file MeshBuildInfo.cc.
References MeshBuildInfo().
Referenced by Arcane::ArcaneCaseMeshService::createMesh(), and Arcane::MainFactory::createMesh().
addParentGroup()
MeshBuildInfo & Arcane::MeshBuildInfo::addParentGroup (const ItemGroup & parent_group)
Sets the cell group for a sub-mesh.
Definition at line 56 of file MeshBuildInfo.cc.
References MeshBuildInfo().
Referenced by Arcane::MainFactory::createSubMesh().
factoryName()
const String & Arcane::MeshBuildInfo::factoryName () const inline
Factory name to create the mesh (via IMeshFactory).
Definition at line 78 of file MeshBuildInfo.h.
Referenced by Arcane::ArcaneCaseMeshService::createMesh().
isNeedPartitioning()
bool Arcane::MeshBuildInfo::isNeedPartitioning () const inline
Indicates if the reader/generator requires partitioning.
Definition at line 84 of file MeshBuildInfo.h.
Referenced by Arcane::ArcaneCaseMeshService::createMesh().
meshKind()
const MeshKind Arcane::MeshBuildInfo::meshKind () const inline
Mesh characteristics.
Definition at line 86 of file MeshBuildInfo.h.
Referenced by Arcane::ArcaneCaseMeshService::createMesh(), Arcane::MainFactory::createMesh(), and Arcane::mesh::DynamicMeshFactoryBase::createMesh().
name()
const String & Arcane::MeshBuildInfo::name () const inline
Name of the new mesh.
Definition at line 76 of file MeshBuildInfo.h.
Referenced by MeshBuildInfo().
parallelMngRef()
Ref< IParallelMng > Arcane::MeshBuildInfo::parallelMngRef () const inline
Parallelism manager in the case of a new mesh.
Definition at line 80 of file MeshBuildInfo.h.
Referenced by Arcane::ArcaneCaseMeshService::createMesh().
parentGroup()
const ItemGroup & Arcane::MeshBuildInfo::parentGroup () const inline
Parent group in the case of a sub-mesh, null otherwise.
Definition at line 82 of file MeshBuildInfo.h.
Referenced by Arcane::mesh::DynamicMeshFactoryBase::createMesh(), and Arcane::MeshFactoryMng::createMesh().
Member Data Documentation
m_factory_name
String Arcane::MeshBuildInfo::m_factory_name private
Definition at line 91 of file MeshBuildInfo.h.
m_is_need_partitioning
bool Arcane::MeshBuildInfo::m_is_need_partitioning = false private
Definition at line 94 of file MeshBuildInfo.h.
m_mesh_kind
MeshKind Arcane::MeshBuildInfo::m_mesh_kind private
Definition at line 95 of file MeshBuildInfo.h.
m_name
String Arcane::MeshBuildInfo::m_name private
Definition at line 90 of file MeshBuildInfo.h.
m_parallel_mng
Ref<IParallelMng> Arcane::MeshBuildInfo::m_parallel_mng private
Definition at line 92 of file MeshBuildInfo.h.
m_parent_group
ItemGroup Arcane::MeshBuildInfo::m_parent_group private
Definition at line 93 of file MeshBuildInfo.h.
The documentation for this class was generated from the following files:
MeshBuildInfo.h
MeshBuildInfo.cc