Arcane: Arcane::AnyItem::Group::BlockItemEnumerator Class Reference
Arcane::AnyItem::Group::BlockItemEnumerator Class Reference
Enumerator of an item block.
#include <arcane/core/anyitem/AnyItemGroup.h>
Public Member Functions
BlockItemEnumerator (const Private::GroupIndexInfo &info)
BlockItemEnumerator (const BlockItemEnumerator &e)
Item operator* () const
Dereference to the associated Arcane item.
ItemInternal * operator-> () const
Indirect dereference to the associated Arcane item.
void operator++ ()
Advancement of the enumerator.
bool hasNext ()
Test for end of enumerator.
Integer count () const
Number of elements in the enumerator.
Integer varIndex () const
localId() of the current entity.
Integer localId () const
localId() of the current entity.
Integer groupIndex () const
Index in the current AnyItem::Family group.
ItemGroup group () const
Current underlying group.
Private Types
typedef ItemInternal * ItemInternalPtr
Private Attributes
const Private::GroupIndexInfo & m_info
ItemInfoListView m_items
const Int32 *ARCANE_RESTRICT m_local_ids
Integer m_index
Integer m_count
bool m_is_partial
Detailed Description
Enumerator of an item block.
Arcane enumerator enriched with the position in the family
Definition at line 100 of file AnyItemGroup.h.
Member Typedef Documentation
ItemInternalPtr
typedef ItemInternal* Arcane::AnyItem::Group::BlockItemEnumerator::ItemInternalPtr private
Definition at line 104 of file AnyItemGroup.h.
Constructor & Destructor Documentation
BlockItemEnumerator() [1/2]
Arcane::AnyItem::Group::BlockItemEnumerator::BlockItemEnumerator (const Private::GroupIndexInfo & info) inline
Definition at line 108 of file AnyItemGroup.h.
BlockItemEnumerator() [2/2]
Arcane::AnyItem::Group::BlockItemEnumerator::BlockItemEnumerator (const BlockItemEnumerator & e) inline
Definition at line 117 of file AnyItemGroup.h.
Member Function Documentation
count()
Integer Arcane::AnyItem::Group::BlockItemEnumerator::count () const inline
Number of elements in the enumerator.
Definition at line 136 of file AnyItemGroup.h.
group()
ItemGroup Arcane::AnyItem::Group::BlockItemEnumerator::group () const inline
Current underlying group.
Definition at line 148 of file AnyItemGroup.h.
groupIndex()
Integer Arcane::AnyItem::Group::BlockItemEnumerator::groupIndex () const inline
Index in the current AnyItem::Family group.
Definition at line 145 of file AnyItemGroup.h.
Referenced by Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::VariableArray< DataType >::operator[](), and Arcane::AnyItem::VariableArray< DataType >::operator[]().
hasNext()
bool Arcane::AnyItem::Group::BlockItemEnumerator::hasNext () inline
Test for end of enumerator.
Definition at line 134 of file AnyItemGroup.h.
localId()
Integer Arcane::AnyItem::Group::BlockItemEnumerator::localId () const inline
localId() of the current entity.
Definition at line 142 of file AnyItemGroup.h.
operator*()
Item Arcane::AnyItem::Group::BlockItemEnumerator::operator* () const inline
Dereference to the associated Arcane item.
Definition at line 127 of file AnyItemGroup.h.
operator++()
void Arcane::AnyItem::Group::BlockItemEnumerator::operator++ () inline
Advancement of the enumerator.
Definition at line 132 of file AnyItemGroup.h.
operator->()
ItemInternal * Arcane::AnyItem::Group::BlockItemEnumerator::operator-> () const inline
Indirect dereference to the associated Arcane item.
Definition at line 130 of file AnyItemGroup.h.
varIndex()
Integer Arcane::AnyItem::Group::BlockItemEnumerator::varIndex () const inline
localId() of the current entity.
Definition at line 139 of file AnyItemGroup.h.
Referenced by Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::VariableArray< DataType >::operator[](), and Arcane::AnyItem::VariableArray< DataType >::operator[]().
Member Data Documentation
m_count
Integer Arcane::AnyItem::Group::BlockItemEnumerator::m_count private
Definition at line 157 of file AnyItemGroup.h.
m_index
Integer Arcane::AnyItem::Group::BlockItemEnumerator::m_index private
Definition at line 156 of file AnyItemGroup.h.
m_info
const Private::GroupIndexInfo& Arcane::AnyItem::Group::BlockItemEnumerator::m_info private
Definition at line 152 of file AnyItemGroup.h.
m_is_partial
bool Arcane::AnyItem::Group::BlockItemEnumerator::m_is_partial private
Definition at line 158 of file AnyItemGroup.h.
m_items
ItemInfoListView Arcane::AnyItem::Group::BlockItemEnumerator::m_items private
Definition at line 154 of file AnyItemGroup.h.
m_local_ids
const Int32* ARCANE_RESTRICT Arcane::AnyItem::Group::BlockItemEnumerator::m_local_ids private
Definition at line 155 of file AnyItemGroup.h.
The documentation for this class was generated from the following file:
AnyItemGroup.h