Arcane: Arcane::ISimpleTableInternalMng Class Reference
Arcane::ISimpleTableInternalMng Class Reference abstract
Class interface representing a manager for SimpleTableInternal (aka STI).
#include <arcane/core/ISimpleTableInternalMng.h>
Public Member Functions
virtual void clearInternal ()=0
Method to clear the content of the SimpleTableInternal.
virtual Integer addRow (const String &row_name)=0
Method to add a row.
virtual Integer addRow (const String &row_name, ConstArrayView< Real > elements)=0
Method to add a row.
virtual bool addRows (StringConstArrayView rows_names)=0
Method to add multiple rows.
virtual Integer addColumn (const String &column_name)=0
Method to add a column.
virtual Integer addColumn (const String &column_name, ConstArrayView< Real > elements)=0
Method to add a column.
virtual bool addColumns (StringConstArrayView columns_names)=0
Method to add multiple columns.
virtual bool addElementInRow (Integer position, Real element)=0
Method to add an element to a row.
virtual bool addElementInRow (const String &row_name, Real element, bool create_if_not_exist=true)=0
Method to add an element to a row.
virtual bool addElementInSameRow (Real element)=0
Method to add an element to the row most recently manipulated.
virtual bool addElementsInRow (Integer position, ConstArrayView< Real > elements)=0
Method to add multiple elements to a row.
virtual bool addElementsInRow (const String &row_name, ConstArrayView< Real > elements, bool create_if_not_exist=true)=0
Method to add multiple elements to a row.
virtual bool addElementsInSameRow (ConstArrayView< Real > elements)=0
Method to add multiple elements to the row most recently manipulated.
virtual bool addElementInColumn (Integer position, Real element)=0
Method to add an element to a column.
virtual bool addElementInColumn (const String &column_name, Real element, bool create_if_not_exist=true)=0
Method to add an element to a column.
virtual bool addElementInSameColumn (Real element)=0
Method to add an element to the column most recently manipulated.
virtual bool addElementsInColumn (Integer position, ConstArrayView< Real > elements)=0
Method to add multiple elements to a column.
virtual bool addElementsInColumn (const String &column_name, ConstArrayView< Real > elements, bool create_if_not_exist=true)=0
Method to add multiple elements to a column.
virtual bool addElementsInSameColumn (ConstArrayView< Real > elements)=0
Method to add multiple elements to the column most recently manipulated.
virtual bool editElementUp (Real element, bool update_last_position=true)=0
Method to edit an element above the last element most recently manipulated (row above/same column).
virtual bool editElementDown (Real element, bool update_last_position=true)=0
Method to edit an element below the last element most recently manipulated (row below/same column).
virtual bool editElementLeft (Real element, bool update_last_position=true)=0
Method to edit an element to the left of the last element most recently manipulated (same row/column to the left).
virtual bool editElementRight (Real element, bool update_last_position=true)=0
Method allowing editing an element to the right of the last element recently manipulated (same row/column to the right).
virtual Real elementUp (bool update_last_position=false)=0
Method allowing retrieval of an element above the last element recently manipulated (row above/same column).
virtual Real elementDown (bool update_last_position=false)=0
Method allowing retrieval of an element below the last element recently manipulated (row below/same column).
virtual Real elementLeft (bool update_last_position=false)=0
Method allowing retrieval of an element to the left of the last element recently manipulated (same row/column to the left).
virtual Real elementRight (bool update_last_position=false)=0
Method allowing retrieval of an element to the right of the last element recently manipulated (same row/column to the right).
virtual bool editElement (Real element)=0
Method allowing modification of an element in the table.
virtual bool editElement (Integer position_x, Integer position_y, Real element)=0
Method allowing modification of an element in the table.
virtual bool editElement (const String &column_name, const String &row_name, Real element)=0
Method allowing modification of an element in the table.
virtual Real element ()=0
Method allowing retrieval of a copy of an element.
virtual Real element (Integer position_x, Integer position_y, bool update_last_position=false)=0
Method allowing retrieval of a copy of an element.
virtual Real element (const String &column_name, const String &row_name, bool update_last_position=false)=0
Method allowing retrieval of a copy of an element.
virtual RealUniqueArray row (Integer position)=0
Method allowing retrieval of a copy of a row.
virtual RealUniqueArray row (const String &row_name)=0
Method allowing retrieval of a copy of a row.
virtual RealUniqueArray column (Integer position)=0
Method allowing retrieval of a copy of a column.
virtual RealUniqueArray column (const String &column_name)=0
Method allowing retrieval of a copy of a column.
virtual Integer rowSize (Integer position)=0
Method allowing retrieval of the size of a row. Including hypothetical 'gaps' in the row.
virtual Integer rowSize (const String &row_name)=0
Method allowing retrieval of the size of a row. Including hypothetical 'gaps' in the row.
virtual Integer columnSize (Integer position)=0
Method allowing retrieval of the size of a column. Including hypothetical 'gaps' in the column.
virtual Integer columnSize (const String &column_name)=0
Method allowing retrieval of the size of a column. Including hypothetical 'gaps' in the column.
virtual Integer rowPosition (const String &row_name)=0
Method allowing retrieval of the position of a row.
virtual Integer columnPosition (const String &column_name)=0
Method allowing retrieval of the position of a column.
virtual Integer numberOfRows ()=0
Method allowing retrieval of the number of rows in the table. This is, in a sense, the maximum number of elements a column can contain.
virtual Integer numberOfColumns ()=0
Method allowing retrieval of the number of columns in the table. This is, in a sense, the maximum number of elements a row can contain.
virtual String rowName (Integer position)=0
Method allowing retrieval of the name of a row from its position.
virtual String columnName (Integer position)=0
Method allowing retrieval of the name of a column from its position.
virtual bool editRowName (Integer position, const String &new_name)=0
Method allowing changing the name of a row.
virtual bool editRowName (const String &row_name, const String &new_name)=0
Method allowing changing the name of a row.
virtual bool editColumnName (Integer position, const String &new_name)=0
Method allowing changing the name of a column.
virtual bool editColumnName (const String &column_name, const String &new_name)=0
Method allowing changing the name of a column.
virtual Integer addAverageColumn (const String &column_name)=0
Method allowing creation of a column containing the average of elements of each row.
virtual Ref< SimpleTableInternal > internal ()=0
Method allowing retrieval of a reference to the object SimpleTableInternal used.
virtual void setInternal (const Ref< SimpleTableInternal > &simple_table_internal)=0
Method allowing setting a reference to a SimpleTableInternal.
Detailed Description
Class interface representing a manager for SimpleTableInternal (aka STI).
This manager allows for several types of operations on the STI: adding rows, columns, values, etc.
There are two modes of operation (which can be mixed):
using the names or positions of rows/columns,
using a position pointer within the array.
The first mode is the easiest to use and is sufficient for most users. You provide a name (or position) of a row or column and a value, and this value is placed after the other values in the row or column.
The second mode is more advanced and is mainly used to replace elements already present or to optimize performance (if there are 40 rows, 40 values to add sequentially, and you use the column names 40 times, this results in 40 String searches in a StringUniqueArray, which is not optimal performance). A pointer representing the last added element is present in STI. You can modify elements around this pointer (top, bottom, left, right) using the available methods. This pointer can be placed anywhere using the element() methods. This pointer is not read by the methods of the first mode but is updated by them.
Definition at line 61 of file ISimpleTableInternalMng.h.
Member Function Documentation
addAverageColumn()
virtual Integer Arcane::ISimpleTableInternalMng::addAverageColumn (const String & column_name) pure virtual
Method allowing creation of a column containing the average of elements of each row.
Parameters
column_name The name of the new column. Must not be empty.
Returns
Integer The position of the column.
Implemented in Arcane::SimpleTableInternalMng.
addColumn() [1/2]
virtual Integer Arcane::ISimpleTableInternalMng::addColumn (const String & column_name) pure virtual
Method to add a column.
Parameters
column_name The name of the column. Must not be empty.
Returns
Integer The position of the column in the array. (-1 if the given name is incorrect).
Implemented in Arcane::SimpleTableInternalMng.
addColumn() [2/2]
virtual Integer Arcane::ISimpleTableInternalMng::addColumn (const String & column_name, ConstArrayView< Real > elements) pure virtual
Method to add a column.
If the number of elements in 'elements' is greater than the number of rows, the addition still takes place (but the extra elements will not be added).
Parameters
column_name The name of the column. Must not be empty.
elements The elements to add to the column.
Returns
Integer The position of the column in the array. (-1 if the given name is incorrect).
Implemented in Arcane::SimpleTableInternalMng.
addColumns()
virtual bool Arcane::ISimpleTableInternalMng::addColumns (StringConstArrayView columns_names) pure virtual
Method to add multiple columns.
Parameters
rows_names The names of the columns. Each name must not be empty.
Returns
true If all columns were created.
false If not all columns were created.
Implemented in Arcane::SimpleTableInternalMng.
addElementInColumn() [1/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementInColumn (const String & column_name, Real element, bool create_if_not_exist = true) pure virtual
Method to add an element to a column.
Parameters
column_name The name of the column.
element The element to add.
create_if_not_exist To specify whether the column should be created if it does not already exist.
Returns
true If the element was successfully added.
false If the element could not be added.
Implemented in Arcane::SimpleTableInternalMng.
References element().
addElementInColumn() [2/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementInColumn (Integer position, Real element) pure virtual
Method to add an element to a column.
Parameters
position The position of the column.
element The element to add.
Returns
true If the element was successfully added.
false If the element could not be added.
Implemented in Arcane::SimpleTableInternalMng.
References element().
addElementInRow() [1/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementInRow (const String & row_name, Real element, bool create_if_not_exist = true) pure virtual
Method to add an element to a row.
Parameters
row_name The name of the row.
element The element to add.
create_if_not_exist To specify whether the row should be created if it does not already exist.
Returns
true If the element was successfully added.
false If the element could not be added.
Implemented in Arcane::SimpleTableInternalMng.
References element().
addElementInRow() [2/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementInRow (Integer position, Real element) pure virtual
Method to add an element to a row.
Parameters
position The position of the row.
element The element to add.
Returns
true If the element was successfully added.
false If the element could not be added.
Implemented in Arcane::SimpleTableInternalMng.
References element().
addElementInSameColumn()
virtual bool Arcane::ISimpleTableInternalMng::addElementInSameColumn (Real element) pure virtual
Method to add an element to the column most recently manipulated.
This method differs from 'editElementDown()' because here, an element is added to the end of the column, not necessarily after the last added element.
Parameters
element The element to add.
Returns
true If the element was added.
false If the element could not be added.
Implemented in Arcane::SimpleTableInternalMng.
References element().
addElementInSameRow()
virtual bool Arcane::ISimpleTableInternalMng::addElementInSameRow (Real element) pure virtual
Method to add an element to the row most recently manipulated.
This method differs from 'editElementRight()' because here, an element is added to the end of the row, not necessarily after the last added element.
Parameters
element The element to add.
Returns
true If the element was added.
false If the element could not be added.
Implemented in Arcane::SimpleTableInternalMng.
References element().
addElementsInColumn() [1/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementsInColumn (const String & column_name, ConstArrayView< Real > elements, bool create_if_not_exist = true) pure virtual
Method to add multiple elements to a column.
If the number of elements in 'elements' is greater than the number of available rows, the addition still takes place (but the extra elements will not be added) and a return value of false will be returned.
Parameters
column_name The name of the column.
elements The array of elements to add.
create_if_not_exist To specify whether the column should be created if it does not already exist.
Returns
true If all elements were added.
false If [0;len(elements)[ elements were added.
Implemented in Arcane::SimpleTableInternalMng.
addElementsInColumn() [2/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementsInColumn (Integer position, ConstArrayView< Real > elements) pure virtual
Method to add multiple elements to a column.
If the number of elements in 'elements' is greater than the number of available rows, the addition still takes place (but the extra elements will not be added) and a return value of false will be returned.
Parameters
position The position of the column.
elements The array of elements to add.
Returns
true If all elements were added.
false If [0;len(elements)[ elements were added.
Implemented in Arcane::SimpleTableInternalMng.
addElementsInRow() [1/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementsInRow (const String & row_name, ConstArrayView< Real > elements, bool create_if_not_exist = true) pure virtual
Method to add multiple elements to a row.
If the number of elements in 'elements' is greater than the number of available columns, the addition still takes place (but the extra elements will not be added) and a return value of false will be returned.
Parameters
row_name The name of the row.
elements The array of elements to add.
create_if_not_exist To specify whether the row should be created if it does not already exist.
Returns
true If all elements were added.
false If [0;len(elements)[ elements were added.
Implemented in Arcane::SimpleTableInternalMng.
addElementsInRow() [2/2]
virtual bool Arcane::ISimpleTableInternalMng::addElementsInRow (Integer position, ConstArrayView< Real > elements) pure virtual
Method to add multiple elements to a row.
If the number of elements in 'elements' is greater than the number of available columns, the addition still takes place (but the extra elements will not be added) and a return value of false will be returned.
Parameters
position The position of the row.
elements The array of elements to add.
Returns
true If all elements were added.
false If [0;len(elements)[ elements were added.
Implemented in Arcane::SimpleTableInternalMng.
addElementsInSameColumn()
virtual bool Arcane::ISimpleTableInternalMng::addElementsInSameColumn (ConstArrayView< Real > elements) pure virtual
Method to add multiple elements to the column most recently manipulated.
If the number of elements in 'elements' is greater than the number of available rows, the addition still takes place (but the extra elements will not be added) and a return value of false will be returned.
Apart from the fact that we are manipulating an array here, this method differs from 'editElementDown()' because here, elements are added to the end of the column, not necessarily after the last added element.
Parameters
elements The array of elements to add.
Returns
true If all elements were added.
false If [0;len(elements)[ elements were added.
Implemented in Arcane::SimpleTableInternalMng.
addElementsInSameRow()
virtual bool Arcane::ISimpleTableInternalMng::addElementsInSameRow (ConstArrayView< Real > elements) pure virtual
Method to add multiple elements to the row most recently manipulated.
If the number of elements in 'elements' is greater than the number of available columns, the addition still takes place (but the extra elements will not be added) and a return value of false will be returned.
Apart from the fact that we are manipulating an array here, this method differs from 'editElementRight()' because here, elements are added to the end of the row, not necessarily after the last added element.
Parameters
elements The array of elements to add.
Returns
true If all elements were added.
false If [0;len(elements)[ elements were added.
Implemented in Arcane::SimpleTableInternalMng.
addRow() [1/2]
virtual Integer Arcane::ISimpleTableInternalMng::addRow (const String & row_name) pure virtual
Method to add a row.
Parameters
row_name The name of the row. Must not be empty.
Returns
Integer The position of the row in the array (-1 if the given name is incorrect).
Implemented in Arcane::SimpleTableInternalMng.
addRow() [2/2]
virtual Integer Arcane::ISimpleTableInternalMng::addRow (const String & row_name, ConstArrayView< Real > elements) pure virtual
Method to add a row.
If the number of elements in 'elements' is greater than the number of columns, the addition still takes place (but the extra elements will not be added).
Parameters
row_name The name of the row. Must not be empty.
elements The elements to insert into the row.
Returns
Integer The position of the row in the array. (-1 if the given name is incorrect).
Implemented in Arcane::SimpleTableInternalMng.
addRows()
virtual bool Arcane::ISimpleTableInternalMng::addRows (StringConstArrayView rows_names) pure virtual
Method to add multiple rows.
Parameters
rows_names The names of the rows. Each name must not be empty.
Returns
true If all rows were created.
false If not all rows were created.
Implemented in Arcane::SimpleTableInternalMng.
clearInternal()
virtual void Arcane::ISimpleTableInternalMng::clearInternal () pure virtual
Method to clear the content of the SimpleTableInternal.
Implemented in Arcane::SimpleTableInternalMng.
column() [1/2]
virtual RealUniqueArray Arcane::ISimpleTableInternalMng::column (const String & column_name) pure virtual
Method allowing retrieval of a copy of a column.
Parameters
column_name The name of the column.
Returns
RealUniqueArray The copy of the column (empty array if not found).
Implemented in Arcane::SimpleTableInternalMng.
column() [2/2]
virtual RealUniqueArray Arcane::ISimpleTableInternalMng::column (Integer position) pure virtual
Method allowing retrieval of a copy of a column.
Parameters
position The position of the column.
Returns
RealUniqueArray The copy of the column (empty array if not found).
Implemented in Arcane::SimpleTableInternalMng.
columnName()
virtual String Arcane::ISimpleTableInternalMng::columnName (Integer position) pure virtual
Method allowing retrieval of the name of a column from its position.
Parameters
position The position of the column.
Returns
String The name of the column (empty string if the column was not found).
Implemented in Arcane::SimpleTableInternalMng.
columnPosition()
virtual Integer Arcane::ISimpleTableInternalMng::columnPosition (const String & column_name) pure virtual
Method allowing retrieval of the position of a column.
Parameters
row_name The name of the column.
Returns
Integer The position of the column (-1 if not found).
Implemented in Arcane::SimpleTableInternalMng.
columnSize() [1/2]
virtual Integer Arcane::ISimpleTableInternalMng::columnSize (const String & column_name) pure virtual
Method allowing retrieval of the size of a column. Including hypothetical 'gaps' in the column.
Parameters
position The name of the column.
Returns
Integer The size of the column (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
columnSize() [2/2]
virtual Integer Arcane::ISimpleTableInternalMng::columnSize (Integer position) pure virtual
Method allowing retrieval of the size of a column. Including hypothetical 'gaps' in the column.
Parameters
position The position of the column.
Returns
Integer The size of the column (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
editColumnName() [1/2]
virtual bool Arcane::ISimpleTableInternalMng::editColumnName (const String & column_name, const String & new_name) pure virtual
Method allowing changing the name of a column.
Parameters
column_name The current name of the column.
new_name The new name of the column. Must not be empty.
Returns
true If the change occurred.
false If the change did not occur.
Implemented in Arcane::SimpleTableInternalMng.
editColumnName() [2/2]
virtual bool Arcane::ISimpleTableInternalMng::editColumnName (Integer position, const String & new_name) pure virtual
Method allowing changing the name of a column.
Parameters
position The position of the column.
new_name The new name of the column. Must not be empty.
Returns
true If the change occurred.
false If the change did not occur.
Implemented in Arcane::SimpleTableInternalMng.
editElement() [1/3]
virtual bool Arcane::ISimpleTableInternalMng::editElement (const String & column_name, const String & row_name, Real element) pure virtual
Method allowing modification of an element in the table.
Parameters
column_name The name of the column where the element is located.
row_name The name of the row where the element is located.
element The replacement element.
Returns
true If the element was successfully replaced.
false If the element could not be replaced.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editElement() [2/3]
virtual bool Arcane::ISimpleTableInternalMng::editElement (Integer position_x, Integer position_y, Real element) pure virtual
Method allowing modification of an element in the table.
Parameters
position_x The position of the column to modify.
position_y The position of the row to modify.
element The replacement element.
Returns
true If the element was successfully replaced.
false If the element was not replaced.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editElement() [3/3]
virtual bool Arcane::ISimpleTableInternalMng::editElement (Real element) pure virtual
Method allowing modification of an element in the table.
The x and y positions correspond to the location of the last manipulated element.
This method is useful after using 'elemUDLR(true)', for example.
Parameters
element The replacement element.
Returns
true If the element was successfully replaced.
false If the element was not replaced.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editElementDown()
virtual bool Arcane::ISimpleTableInternalMng::editElementDown (Real element, bool update_last_position = true) pure virtual
Method to edit an element below the last element most recently manipulated (row below/same column).
The element being modified thus becomes the last modified element at the end of this method (if update_last_position = true).
This method differs from 'addElementInSameColumn()' because here, an element is added (or modified) below the last manipulated element, which is not necessarily at the end of the column.
Parameters
element The element to modify.
update_last_position Should the "last modified element" cursor be moved?
Returns
true If the element was modified.
false If the element could not be modified.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editElementLeft()
virtual bool Arcane::ISimpleTableInternalMng::editElementLeft (Real element, bool update_last_position = true) pure virtual
Method to edit an element to the left of the last element most recently manipulated (same row/column to the left).
The element being modified thus becomes the last modified element at the end of this method (if update_last_position = true).
Parameters
element The element to modify.
update_last_position Should the "last modified element" cursor be moved?
Returns
true If the element was modified.
false If the element could not be modified.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editElementRight()
virtual bool Arcane::ISimpleTableInternalMng::editElementRight (Real element, bool update_last_position = true) pure virtual
Method allowing editing an element to the right of the last element recently manipulated (same row/column to the right).
The element being modified thus becomes the last modified element at the end of this method (if update_last_position = true).
This method differs from 'addElementInSameRow()' because here, we add (or modify) an element to the right of the last manipulated element, which is not necessarily at the end of the column.
Parameters
element The element to modify.
update_last_position Should the "last modified element" cursor be moved?
Returns
true If the element was modified.
false If the element could not be modified.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editElementUp()
virtual bool Arcane::ISimpleTableInternalMng::editElementUp (Real element, bool update_last_position = true) pure virtual
Method to edit an element above the last element most recently manipulated (row above/same column).
The element being modified thus becomes the last modified element at the end of this method (if update_last_position = true).
Parameters
element The element to modify.
update_last_position Should the "last modified element" cursor be moved?
Returns
true If the element was modified.
false If the element could not be modified.
Implemented in Arcane::SimpleTableInternalMng.
References element().
editRowName() [1/2]
virtual bool Arcane::ISimpleTableInternalMng::editRowName (const String & row_name, const String & new_name) pure virtual
Method allowing changing the name of a row.
Parameters
row_name The current name of the row.
new_name The new name of the row. Must not be empty.
Returns
true If the change occurred.
false If the change did not occur.
Implemented in Arcane::SimpleTableInternalMng.
editRowName() [2/2]
virtual bool Arcane::ISimpleTableInternalMng::editRowName (Integer position, const String & new_name) pure virtual
Method allowing changing the name of a row.
Parameters
position The position of the row.
new_name The new name of the row. Must not be empty.
Returns
true If the change occurred.
false If the change did not occur.
Implemented in Arcane::SimpleTableInternalMng.
element() [1/3]
virtual Real Arcane::ISimpleTableInternalMng::element () pure virtual
Method allowing retrieval of a copy of an element.
The x and y positions correspond to the location of the last manipulated element.
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
Referenced by addElementInColumn(), addElementInColumn(), addElementInRow(), addElementInRow(), addElementInSameColumn(), addElementInSameRow(), editElement(), editElement(), editElement(), editElementDown(), editElementLeft(), editElementRight(), and editElementUp().
element() [2/3]
virtual Real Arcane::ISimpleTableInternalMng::element (const String & column_name, const String & row_name, bool update_last_position = false) pure virtual
Method allowing retrieval of a copy of an element.
Parameters
column_name The name of the column where the element is located.
row_name The name of the row where the element is located.
update_last_position Should the "last modified element" cursor be moved?
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
element() [3/3]
virtual Real Arcane::ISimpleTableInternalMng::element (Integer position_x, Integer position_y, bool update_last_position = false) pure virtual
Method allowing retrieval of a copy of an element.
Parameters
position_x The position of the column where the element is located.
position_y The position of the row where the element is located.
update_last_position Should the "last modified element" cursor be moved?
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
elementDown()
virtual Real Arcane::ISimpleTableInternalMng::elementDown (bool update_last_position = false) pure virtual
Method allowing retrieval of an element below the last element recently manipulated (row below/same column).
The element retrieved thus becomes the last "modified" element at the end of this method (if update_last_position = true).
Parameters
update_last_position Should the "last modified element" cursor be moved?
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
elementLeft()
virtual Real Arcane::ISimpleTableInternalMng::elementLeft (bool update_last_position = false) pure virtual
Method allowing retrieval of an element to the left of the last element recently manipulated (same row/column to the left).
The element retrieved thus becomes the last "modified" element at the end of this method (if update_last_position = true).
Parameters
update_last_position Should the "last modified element" cursor be moved?
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
elementRight()
virtual Real Arcane::ISimpleTableInternalMng::elementRight (bool update_last_position = false) pure virtual
Method allowing retrieval of an element to the right of the last element recently manipulated (same row/column to the right).
The element retrieved thus becomes the last "modified" element at the end of this method (if update_last_position = true).
Parameters
update_last_position Should the "last modified element" cursor be moved?
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
elementUp()
virtual Real Arcane::ISimpleTableInternalMng::elementUp (bool update_last_position = false) pure virtual
Method allowing retrieval of an element above the last element recently manipulated (row above/same column).
The element retrieved thus becomes the last "modified" element at the end of this method (if update_last_position = true).
Parameters
update_last_position Should the "last modified element" cursor be moved?
Returns
Real The found element (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
internal()
virtual Ref< SimpleTableInternal > Arcane::ISimpleTableInternalMng::internal () pure virtual
Method allowing retrieval of a reference to the object SimpleTableInternal used.
Returns
Ref<SimpleTableInternal> A copy of the reference.
Implemented in Arcane::SimpleTableInternalMng.
numberOfColumns()
virtual Integer Arcane::ISimpleTableInternalMng::numberOfColumns () pure virtual
Method allowing retrieval of the number of columns in the table. This is, in a sense, the maximum number of elements a row can contain.
Returns
Integer The number of columns in the table.
Implemented in Arcane::SimpleTableInternalMng.
numberOfRows()
virtual Integer Arcane::ISimpleTableInternalMng::numberOfRows () pure virtual
Method allowing retrieval of the number of rows in the table. This is, in a sense, the maximum number of elements a column can contain.
Returns
Integer The number of rows in the table.
Implemented in Arcane::SimpleTableInternalMng.
row() [1/2]
virtual RealUniqueArray Arcane::ISimpleTableInternalMng::row (const String & row_name) pure virtual
Method allowing retrieval of a copy of a row.
Parameters
row_name The name of the row.
Returns
RealUniqueArray The copy of the row (empty array if not found).
Implemented in Arcane::SimpleTableInternalMng.
row() [2/2]
virtual RealUniqueArray Arcane::ISimpleTableInternalMng::row (Integer position) pure virtual
Method allowing retrieval of a copy of a row.
Parameters
position The position of the row.
Returns
RealUniqueArray The copy of the row (empty array if not found).
Implemented in Arcane::SimpleTableInternalMng.
rowName()
virtual String Arcane::ISimpleTableInternalMng::rowName (Integer position) pure virtual
Method allowing retrieval of the name of a row from its position.
Parameters
position The position of the row.
Returns
String The name of the row (empty string if the row was not found).
Implemented in Arcane::SimpleTableInternalMng.
rowPosition()
virtual Integer Arcane::ISimpleTableInternalMng::rowPosition (const String & row_name) pure virtual
Method allowing retrieval of the position of a row.
Parameters
row_name The name of the row.
Returns
Integer The position of the row (-1 if not found).
Implemented in Arcane::SimpleTableInternalMng.
rowSize() [1/2]
virtual Integer Arcane::ISimpleTableInternalMng::rowSize (const String & row_name) pure virtual
Method allowing retrieval of the size of a row. Including hypothetical 'gaps' in the row.
Parameters
position The name of the row.
Returns
Integer The size of the row (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
rowSize() [2/2]
virtual Integer Arcane::ISimpleTableInternalMng::rowSize (Integer position) pure virtual
Method allowing retrieval of the size of a row. Including hypothetical 'gaps' in the row.
Parameters
position The position of the row.
Returns
Integer The size of the row (0 if not found).
Implemented in Arcane::SimpleTableInternalMng.
setInternal()
virtual void Arcane::ISimpleTableInternalMng::setInternal (const Ref< SimpleTableInternal > & simple_table_internal) pure virtual
Method allowing setting a reference to a SimpleTableInternal.
Parameters
simple_table_internal The reference to a SimpleTableInternal.
Implemented in Arcane::SimpleTableInternalMng.
The documentation for this class was generated from the following file:
ISimpleTableInternalMng.h