Arcane: Arcane::INumericDataInternal Class Reference
Arcane::INumericDataInternal Class Reference abstract
Interface for an 'IData' of a numeric type.
#include <arcane/core/internal/IDataInternal.h>
Public Member Functions
virtual MutableMemoryView memoryView ()=0
Memory view of the data.
virtual Int32 extent0 () const =0
Number of elements in the first dimension.
virtual void changeAllocator (const MemoryAllocationOptions &alloc_info)=0
Changes the variable's allocator.
virtual IMemoryAllocator * memoryAllocator () const =0
Allocator used for the data.
Detailed Description
Interface for an 'IData' of a numeric type.
Numeric types are the types of eBasicDataType.
Generally, all IData are of this type except StringScalarData or StringArrayData.
Definition at line 147 of file IDataInternal.h.
Member Function Documentation
changeAllocator()
virtual void Arcane::INumericDataInternal::changeAllocator (const MemoryAllocationOptions & alloc_info) pure virtual
Changes the variable's allocator.
Warning
For experimental use only.
Implemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
Referenced by Arcane::VariablePrivate::changeAllocator().
extent0()
virtual Int32 Arcane::INumericDataInternal::extent0 () const pure virtual
Number of elements in the first dimension.
Implemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
memoryAllocator()
virtual IMemoryAllocator * Arcane::INumericDataInternal::memoryAllocator () const pure virtual
Allocator used for the data.
Implemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
Referenced by Arcane::VariableUtils::prefetchVariableAsync().
memoryView()
virtual MutableMemoryView Arcane::INumericDataInternal::memoryView () pure virtual
Memory view of the data.
Implemented in Arcane::Array2DataT< DataType >::Impl, and Arcane::ArrayDataT< DataType >::Impl.
Referenced by Arcane::DataSynchronizeDispatcher::beginSynchronize(), Arcane::VariablePrivate::computeComparisonHashCollective(), and Arcane::VariableUtils::prefetchVariableAsync().
The documentation for this class was generated from the following file:
IDataInternal.h