Arcane: Arcane::MessagePassing::SharedMemoryMessageRequest Class Reference
Arcane::MessagePassing::SharedMemoryMessageRequest Class Reference
Message within SharedMemoryMessageQueue.
#include <arcane/parallel/thread/SharedMemoryMessageQueue.h>
Classes
class SortFunctor
Public Types
using SubQueue = SharedMemoryMessageQueue::SubQueue
Public Member Functions
SharedMemoryMessageRequest (SubQueue *queue, Int64 request_id, MessageRank orig, MessageRank dest, MessageTag tag, ReceiveBufferInfo buf)
Create a send request.
SharedMemoryMessageRequest (SubQueue *queue, Int64 request_id, MessageRank orig, MessageRank dest, MessageTag tag, SendBufferInfo buf)
Create a receive request.
MessageRank orig ()
MessageRank dest ()
MessageTag tag ()
bool isRecv ()
bool isDone ()
void setDone (bool v)
SendBufferInfo sendBufferInfo ()
ReceiveBufferInfo receiveBufferInfo ()
SharedMemoryMessageQueue::SubQueue * queue ()
void copyFromSender (SharedMemoryMessageRequest *sender)
Copies the sender message information into the receive message.
Int64 id () const
void destroy ()
ISerializer * recvSerializer ()
const ISerializer * sendSerializer ()
void setSource (MessageRank s)
SharedMemoryMessageRequest * matchingSendRequest ()
Associated request in the case it is a receive resulting from a probe.
void setMatchingSendRequest (SharedMemoryMessageRequest *r)
Private Attributes
SubQueue * m_queue
Int64 m_request_id
bool m_is_recv
MessageRank m_orig
MessageRank m_dest
MessageTag m_tag
bool m_is_done = false
SharedMemoryMessageRequest * m_matching_send_request = nullptr
bool m_is_destroyed = false
SendBufferInfo m_send_buffer_info
ReceiveBufferInfo m_receive_buffer_info
Detailed Description
Message within SharedMemoryMessageQueue.
This class handles both send and receive messages.
Definition at line 110 of file SharedMemoryMessageQueue.h.
Member Typedef Documentation
SubQueue
using Arcane::MessagePassing::SharedMemoryMessageRequest::SubQueue = SharedMemoryMessageQueue::SubQueue
Definition at line 155 of file SharedMemoryMessageQueue.h.
Constructor & Destructor Documentation
SharedMemoryMessageRequest() [1/2]
Arcane::MessagePassing::SharedMemoryMessageRequest::SharedMemoryMessageRequest (SubQueue * queue, Int64 request_id, MessageRank orig, MessageRank dest, MessageTag tag, ReceiveBufferInfo buf) inline
Create a send request.
Definition at line 160 of file SharedMemoryMessageQueue.h.
Referenced by copyFromSender(), and matchingSendRequest().
SharedMemoryMessageRequest() [2/2]
Arcane::MessagePassing::SharedMemoryMessageRequest::SharedMemoryMessageRequest (SubQueue * queue, Int64 request_id, MessageRank orig, MessageRank dest, MessageTag tag, SendBufferInfo buf) inline
Create a receive request.
Definition at line 172 of file SharedMemoryMessageQueue.h.
Member Function Documentation
copyFromSender()
void Arcane::MessagePassing::SharedMemoryMessageRequest::copyFromSender (SharedMemoryMessageRequest * sender)
Copies the sender message information into the receive message.
If an 'ISerializer' is available, it uses it. Otherwise, it is a memory area and the values are copied directly.
Note
It would be possible, if we knew the origin of the memory area, to avoid copying by just passing the pointer.
Definition at line 53 of file SharedMemoryMessageQueue.cc.
References ARCANE_FATAL, Arcane::ISerializer::copy(), Arcane::MemoryResourceMng::genericCopy(), and SharedMemoryMessageRequest().
dest()
MessageRank Arcane::MessagePassing::SharedMemoryMessageRequest::dest () inline
Definition at line 187 of file SharedMemoryMessageQueue.h.
destroy()
void Arcane::MessagePassing::SharedMemoryMessageRequest::destroy ()
Definition at line 82 of file SharedMemoryMessageQueue.cc.
id()
Int64 Arcane::MessagePassing::SharedMemoryMessageRequest::id () const inline
Definition at line 196 of file SharedMemoryMessageQueue.h.
isDone()
bool Arcane::MessagePassing::SharedMemoryMessageRequest::isDone () inline
Definition at line 190 of file SharedMemoryMessageQueue.h.
isRecv()
bool Arcane::MessagePassing::SharedMemoryMessageRequest::isRecv () inline
Definition at line 189 of file SharedMemoryMessageQueue.h.
matchingSendRequest()
SharedMemoryMessageRequest * Arcane::MessagePassing::SharedMemoryMessageRequest::matchingSendRequest () inline
Associated request in the case it is a receive resulting from a probe.
Definition at line 207 of file SharedMemoryMessageQueue.h.
References SharedMemoryMessageRequest().
orig()
MessageRank Arcane::MessagePassing::SharedMemoryMessageRequest::orig () inline
Definition at line 186 of file SharedMemoryMessageQueue.h.
queue()
SharedMemoryMessageQueue::SubQueue * Arcane::MessagePassing::SharedMemoryMessageRequest::queue () inline
Definition at line 194 of file SharedMemoryMessageQueue.h.
receiveBufferInfo()
ReceiveBufferInfo Arcane::MessagePassing::SharedMemoryMessageRequest::receiveBufferInfo () inline
Definition at line 193 of file SharedMemoryMessageQueue.h.
recvSerializer()
ISerializer * Arcane::MessagePassing::SharedMemoryMessageRequest::recvSerializer () inline
Definition at line 198 of file SharedMemoryMessageQueue.h.
sendBufferInfo()
SendBufferInfo Arcane::MessagePassing::SharedMemoryMessageRequest::sendBufferInfo () inline
Definition at line 192 of file SharedMemoryMessageQueue.h.
sendSerializer()
const ISerializer * Arcane::MessagePassing::SharedMemoryMessageRequest::sendSerializer () inline
Definition at line 199 of file SharedMemoryMessageQueue.h.
setDone()
void Arcane::MessagePassing::SharedMemoryMessageRequest::setDone (bool v) inline
Definition at line 191 of file SharedMemoryMessageQueue.h.
setMatchingSendRequest()
void Arcane::MessagePassing::SharedMemoryMessageRequest::setMatchingSendRequest (SharedMemoryMessageRequest * r) inline
Definition at line 208 of file SharedMemoryMessageQueue.h.
setSource()
void Arcane::MessagePassing::SharedMemoryMessageRequest::setSource (MessageRank s) inline
Definition at line 201 of file SharedMemoryMessageQueue.h.
tag()
MessageTag Arcane::MessagePassing::SharedMemoryMessageRequest::tag () inline
Definition at line 188 of file SharedMemoryMessageQueue.h.
Member Data Documentation
m_dest
MessageRank Arcane::MessagePassing::SharedMemoryMessageRequest::m_dest private
Definition at line 216 of file SharedMemoryMessageQueue.h.
m_is_destroyed
bool Arcane::MessagePassing::SharedMemoryMessageRequest::m_is_destroyed = false private
Definition at line 220 of file SharedMemoryMessageQueue.h.
m_is_done
bool Arcane::MessagePassing::SharedMemoryMessageRequest::m_is_done = false private
Definition at line 218 of file SharedMemoryMessageQueue.h.
m_is_recv
bool Arcane::MessagePassing::SharedMemoryMessageRequest::m_is_recv private
Definition at line 214 of file SharedMemoryMessageQueue.h.
m_matching_send_request
SharedMemoryMessageRequest* Arcane::MessagePassing::SharedMemoryMessageRequest::m_matching_send_request = nullptr private
Definition at line 219 of file SharedMemoryMessageQueue.h.
m_orig
MessageRank Arcane::MessagePassing::SharedMemoryMessageRequest::m_orig private
Definition at line 215 of file SharedMemoryMessageQueue.h.
m_queue
SubQueue* Arcane::MessagePassing::SharedMemoryMessageRequest::m_queue private
Definition at line 212 of file SharedMemoryMessageQueue.h.
m_receive_buffer_info
ReceiveBufferInfo Arcane::MessagePassing::SharedMemoryMessageRequest::m_receive_buffer_info private
Definition at line 222 of file SharedMemoryMessageQueue.h.
m_request_id
Int64 Arcane::MessagePassing::SharedMemoryMessageRequest::m_request_id private
Definition at line 213 of file SharedMemoryMessageQueue.h.
m_send_buffer_info
SendBufferInfo Arcane::MessagePassing::SharedMemoryMessageRequest::m_send_buffer_info private
Definition at line 221 of file SharedMemoryMessageQueue.h.
m_tag
MessageTag Arcane::MessagePassing::SharedMemoryMessageRequest::m_tag private
Definition at line 217 of file SharedMemoryMessageQueue.h.
The documentation for this class was generated from the following files:
SharedMemoryMessageQueue.h
SharedMemoryMessageQueue.cc