Arcane: Arcane::Array< T > Class Template Reference
Arcane::Array< T > Class Template Reference
Collection
Base class for 1D data vectors.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/common/arccore/common/Array.h>
Public Types
typedef AbstractArray< T > BaseClassType
typedef ArrayTraits< T >::ConstReferenceType ConstReferenceType
typedef ArrayIterator< const_pointer > const_iterator
Type of the constant iterator over an array element.
typedef const value_type * const_pointer
Constant pointer type of an array element.
typedef ConstReferenceType const_reference
Type constant reference of an array element.
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ptrdiff_t difference_type
Type of a distance between array element iterators.
typedef ArrayIterator< pointer > iterator
Type of the iterator over an array element.
typedef value_type * pointer
Pointer type of an array element.
typedef value_type & reference
Type reference of an array element.
typedef std::reverse_iterator< iterator > reverse_iterator
typedef Int64 size_type
Type indexing the array.
typedef T value_type
Type of the array elements.
Public Types inherited from Arcane::AbstractArray< T >
typedef ArrayTraits< T >::ConstReferenceType ConstReferenceType
typedef ArrayTraits< T >::IsPODType IsPODType
typedef AbstractArray< T > ThatClassType
using TrueImpl = T
typedef T value_type
Type of the array elements.
typedef value_type * pointer
Pointer type of an array element.
typedef const value_type * const_pointer
Constant pointer type of an array element.
typedef ArrayIterator< pointer > iterator
Type of the iterator over an array element.
typedef ArrayIterator< const_pointer > const_iterator
Type of the constant iterator over an array element.
typedef value_type & reference
Type reference of an array element.
typedef ConstReferenceType const_reference
Type constant reference of an array element.
typedef Int64 size_type
Type indexing the array.
typedef ptrdiff_t difference_type
Type of a distance between array element iterators.
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
Public Member Functions
operator ConstArrayView< T > () const
operator ArrayView< T > ()
operator Span< const T > () const
operator Span< T > ()
ConstArrayView< T > constView () const
Constant view of this array.
Span< const T > constSpan () const
Constant view of this array.
ConstArrayView< T > subConstView (Int64 abegin, Int32 asize) const
Sub-view starting from element abegin and containing asize elements.
ArrayView< T > view () const
Mutable view of this array.
Span< const T > span () const
Immutable view of this array.
Span< T > span ()
Mutable view of this array.
SmallSpan< const T > smallSpan () const
Immutable view of this array.
SmallSpan< const T > constSmallSpan () const
Immutable view of this array.
SmallSpan< T > smallSpan ()
Mutable view of this array.
ArrayView< T > subView (Int64 abegin, Integer asize)
Sub-view starting from element abegin and containing asize elements.
void sample (ConstArrayView< Integer > indexes, ArrayView< T > result) const
Extracts a sub-array from a list of indices.
void add (ConstReferenceType val)
Adds element val to the end of the array.
void addRange (ConstReferenceType val, Int64 n)
Adds n elements of value val to the end of the array.
void addRange (ConstArrayView< T > val)
Adds n elements of value val to the end of the array.
void addRange (Span< const T > val)
Adds n elements of value val to the end of the array.
void addRange (ArrayView< T > val)
Adds n elements of value val to the end of the array.
void addRange (Span< T > val)
Adds n elements of value val to the end of the array.
void addRange (const Array< T > &val)
Adds n elements of value val to the end of the array.
void resize (Int64 s)
Changes the number of elements in the array to s.
void resize (Int64 s, ConstReferenceType fill_value)
Changes the number of elements in the array to s.
void resizeNoInit (Int64 s)
Resizes without initializing new values.
void reserve (Int64 new_capacity)
Reserves memory for new_capacity elements.
void shrink ()
Reallocates to free unused memory.
void shrink (Int64 new_capacity)
Reallocates memory to have a capacity close to new_capacity.
void shrink_to_fit ()
Reallocates to free unused memory.
void remove (Int64 index)
Removes the entity at index index.
void popBack ()
Removes the last entity from the array.
T & at (Int64 i)
Element at index i. Always checks for overflows.
ConstReferenceType at (Int64 i) const
Element at index i. Always checks for overflows.
void setAt (Int64 i, ConstReferenceType value)
Sets the element at index i. Always checks for overflows.
ConstReferenceType item (Int64 i) const
Element at index i.
void setItem (Int64 i, ConstReferenceType v)
Element at index i.
ConstReferenceType operator[] (Int64 i) const
Element at index i.
T & operator[] (Int64 i)
Element at index i.
ConstReferenceType operator() (Int64 i) const
T & operator() (Int64 i)
Element at index i.
T & back ()
Last element of the array.
ConstReferenceType back () const
Last element of the array (const).
T & front ()
First element of the array.
ConstReferenceType front () const
First element of the array (const).
void clear ()
Removes the elements from the array.
void fill (ConstReferenceType value)
Fills the array with the value value.
void copy (Span< const T > rhs)
Copies the values from rhs into the instance.
Array< T > clone () const
Clones the array.
const T * unguardedBasePointer () const
T * unguardedBasePointer ()
const T * data () const
Access to the root of the array without any protection.
T * data ()
iterator begin ()
Iterator over the first element of the array.
const_iterator begin () const
Constant iterator over the first element of the array.
iterator end ()
Iterator over the first element after the end of the array.
const_iterator end () const
Constant iterator over the first element after the end of the array.
reverse_iterator rbegin ()
Reverse iterator over the first element of the array.
const_reverse_iterator rbegin () const
Reverse iterator over the first element of the array.
reverse_iterator rend ()
Reverse iterator over the first element after the end of the array.
const_reverse_iterator rend () const
Reverse iterator over the first element after the end of the array.
ArrayRange< pointer > range ()
Iteration range from the first to the last element.
ArrayRange< const_pointer > range () const
Iteration range from the first to the last element.
void push_back (ConstReferenceType val)
Adds the element val to the end of the array.
Public Member Functions inherited from Arcane::AbstractArray< T >
AbstractArray (const AbstractArray< T > &rhs)=delete
AbstractArray< T > & operator= (const AbstractArray< T > &rhs)=delete
void dispose ()
Frees the memory used by the array.
operator ConstArrayView< T > () const
operator Span< const T > () const
operator SmallSpan< const T > () const
Integer size () const
Number of elements in the vector.
Integer length () const
Number of elements in the vector.
Integer capacity () const
Capacity (number of allocated elements) of the vector.
Int64 largeSize () const
Number of elements in the vector (in 64 bits).
Int64 largeLength () const
Number of elements in the vector (in 64 bits).
Int64 largeCapacity () const
Capacity (number of allocated elements) of the vector (in 64 bits).
bool empty () const
Capacity (number of allocated elements) of the vector.
bool contains (ConstReferenceType v) const
True if the array contains the value element v.
ConstReferenceType operator[] (Int64 i) const
Element at index i.
ConstReferenceType operator() (Int64 i) const
Element at index i.
void setMemoryLocationHint (eMemoryLocationHint new_hint)
Modifies the memory location information.
void _internalSetHostDeviceMemoryLocation (eHostDeviceMemoryLocation location)
Sets the physical location of the memory region.
eHostDeviceMemoryLocation hostDeviceMemoryLocation () const
Sets the physical location of the memory region.
void changeAllocator (const MemoryAllocationOptions &options, RunQueue *queue)
void changeAllocator (const MemoryAllocationOptions &options)
Public Member Functions inherited from Arcane::AbstractArrayBase
IMemoryAllocator * allocator () const
MemoryAllocationOptions allocationOptions () const
void setDebugName (const String &name)
Sets the array name for debug information.
String debugName () const
Debug name (null if no name specified).
void printInfos (std::ostream &o)
Protected Member Functions
Array (Array< T > &&rhs) ARCCORE_NOEXCEPT
Move constructor (only for UniqueArray).
void _initFromInitializerList (std::initializer_list< T > alist)
Protected Member Functions inherited from Arcane::AbstractArray< T >
AbstractArray ()
Constructs an empty vector with the default allocator.
AbstractArray (ThatClassType &&rhs) ARCCORE_NOEXCEPT
Move constructor. Should only be used by UniqueArray.
AllocatedMemoryInfo _currentMemoryInfo () const
void _initFromSpan (const Span< const T > &view)
Initializes the array with the view view.
void _initFromAllocator (MemoryAllocationOptions o, Int64 acapacity, void *pre_allocated_buffer=nullptr)
Constructs an empty vector with a specific allocator a.
void _reserve (Int64 new_capacity)
Reserves memory for new_capacity elements.
void _internalRealloc (Int64 new_capacity, bool compute_capacity, RunQueue *queue=nullptr)
Reallocates the array for a new capacity equal to new_capacity.
void _internalReallocate (Int64 new_capacity, RunQueue *queue)
void _internalDeallocate (RunQueue *queue=nullptr)
void _internalAllocate (Int64 new_capacity, RunQueue *queue)
void _copyFromMemory (const T *source)
virtual void _updateReferences ()
Update references.
virtual Integer _getNbRef ()
Update references.
void _addRange (ConstReferenceType val, Int64 n)
Adds n elements of value val to the end of the array.
void _addRange (Span< const T > val)
Adds n elements of value val to the end of the array.
void _checkFreeMemory ()
Destroys the instance if no one references it.
void _destroy ()
void _destroyRange (Int64, Int64, TrueType)
void _destroyRange (Int64 abegin, Int64 aend, FalseType)
void _createRangeDefault (Int64, Int64, TrueType)
void _createRangeDefault (Int64 abegin, Int64 aend, FalseType)
void _createRange (Int64 abegin, Int64 aend, ConstReferenceType value, TrueType)
void _createRange (Int64 abegin, Int64 aend, ConstReferenceType value, FalseType)
void _createRange (Int64 abegin, Int64 aend, const T *values)
void _fill (ConstReferenceType value)
void _clone (const ThatClassType &orig_array)
template<typename PodType>
void _resizeHelper (Int64 s, PodType pod_type, RunQueue *queue)
void _resize (Int64 s)
void _resizeNoInit (Int64 s, RunQueue *queue=nullptr)
Redimensionne sans initialiser les nouvelles valeurs.
void _clear ()
void _resize (Int64 s, ConstReferenceType value)
Redimensionne et remplit les nouvelles valeurs avec value.
void _copy (const T *rhs_begin, TrueType)
void _copy (const T *rhs_begin, FalseType)
void _copy (const T *rhs_begin)
void _resizeAndCopyView (Span< const T > rhs)
Redimensionne l'instance et recopie les valeurs de rhs.
void _move (ThatClassType &rhs) ARCCORE_NOEXCEPT
Implements the move assignment operator.
void _swap (ThatClassType &rhs) ARCCORE_NOEXCEPT
Swaps the values of the instance with those of rhs.
void _shrink ()
void _shrink (Int64 new_capacity)
void _reset ()
Resets the array to an empty array.
constexpr Integer _clampSizeOffet (Int64 offset, Int32 asize) const
void _assignFromArray (const AbstractArray< T > &rhs)
void _setMP (TrueImpl *new_mp)
void _setMP2 (TrueImpl *new_mp, ArrayMetaData *new_md)
bool _isSharedNull ()
Protected Member Functions inherited from Arcane::AbstractArrayBase
virtual bool _isUseOwnMetaData () const
Indicates if m_md refers to m_meta_data.
void _swapMetaData (AbstractArrayBase &rhs)
void _copyMetaData (const AbstractArrayBase &rhs)
void _allocateMetaData ()
void _deallocateMetaData (ArrayMetaData *md)
void _checkValidSharedArray ()
Private Member Functions
Array (const Array< T > &rhs)=delete
void operator= (const Array< T > &rhs)=delete
Static Private Member Functions
static int TV_ttf_display_type (const Array< T > *obj)
Method called from totalview debugger.
Additional Inherited Members
Static Protected Member Functions inherited from Arcane::AbstractArray< T >
static constexpr Int64 typeSize ()
Static Protected Member Functions inherited from Arcane::AbstractArrayBase
static constexpr RunQueue * _nullRunQueue ()
Explicit method for a null RunQueue.
Protected Attributes inherited from Arcane::AbstractArray< T >
T * m_ptr = nullptr
Protected Attributes inherited from Arcane::AbstractArrayBase
ArrayMetaData * m_md = nullptr
ArrayMetaData m_meta_data
Detailed Description
template<typename T>
class Arcane::Array< T >
Base class for 1D data vectors.
This class manipulates a 1D vector (array) of data.
Instances of this class are neither copyable nor assignable. To create a copyable array, you must use SharedArray (for reference semantics) or UniqueArray (for value semantics like STL).
Definition at line 42 of file arccore/src/common/arccore/common/Array.h.
Member Typedef Documentation
BaseClassType
template<typename T> typedef AbstractArray<T> Arcane::Array< T >::BaseClassType
Definition at line 52 of file arccore/src/common/arccore/common/Array.h.
const_iterator
template<typename T> typedef ArrayIterator<const_pointer> Arcane::AbstractArray< T >::const_iterator
Type of the constant iterator over an array element.
Definition at line 191 of file AbstractArray.h.
const_pointer
template<typename T> typedef const value_type* Arcane::AbstractArray< T >::const_pointer
Constant pointer type of an array element.
Definition at line 187 of file AbstractArray.h.
const_reference
template<typename T> typedef ConstReferenceType Arcane::AbstractArray< T >::const_reference
Type constant reference of an array element.
Definition at line 195 of file AbstractArray.h.
const_reverse_iterator
template<typename T> typedef std::reverse_iterator<const_iterator> Arcane::AbstractArray< T >::const_reverse_iterator
Definition at line 202 of file AbstractArray.h.
ConstReferenceType
template<typename T> typedef ArrayTraits<T>::ConstReferenceType Arcane::AbstractArray< T >::ConstReferenceType
Definition at line 175 of file AbstractArray.h.
difference_type
template<typename T> typedef ptrdiff_t Arcane::AbstractArray< T >::difference_type
Type of a distance between array element iterators.
Definition at line 199 of file AbstractArray.h.
iterator
template<typename T> typedef ArrayIterator<pointer> Arcane::AbstractArray< T >::iterator
Type of the iterator over an array element.
Definition at line 189 of file AbstractArray.h.
pointer
template<typename T> typedef value_type* Arcane::AbstractArray< T >::pointer
Pointer type of an array element.
Definition at line 185 of file AbstractArray.h.
reference
template<typename T> typedef value_type& Arcane::AbstractArray< T >::reference
Type reference of an array element.
Definition at line 193 of file AbstractArray.h.
reverse_iterator
template<typename T> typedef std::reverse_iterator<iterator> Arcane::AbstractArray< T >::reverse_iterator
Definition at line 201 of file AbstractArray.h.
size_type
template<typename T> typedef Int64 Arcane::AbstractArray< T >::size_type
Type indexing the array.
Definition at line 197 of file AbstractArray.h.
value_type
template<typename T> typedef T Arcane::AbstractArray< T >::value_type
Type of the array elements.
Definition at line 183 of file AbstractArray.h.
Constructor & Destructor Documentation
Array() [1/2]
template<typename T> Arcane::Array< T >::Array () inline protected
Definition at line 71 of file arccore/src/common/arccore/common/Array.h.
Array() [2/2]
template<typename T> Arcane::Array< T >::Array (Array< T > && rhs) inline protected
Move constructor (only for UniqueArray).
Definition at line 76 of file arccore/src/common/arccore/common/Array.h.
~Array()
template<typename T> Arcane::Array< T >::~Array () inline
Definition at line 95 of file arccore/src/common/arccore/common/Array.h.
Member Function Documentation
_initFromInitializerList()
template<typename T> void Arcane::Array< T >::_initFromInitializerList (std::initializer_list< T > alist) inline protected
Definition at line 80 of file arccore/src/common/arccore/common/Array.h.
add()
template<typename T> void Arcane::Array< T >::add (ConstReferenceType val) inline
Adds element val to the end of the array.
Definition at line 207 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::ArcaneCasePartitioner::_addGhostGroups(), Arcane::ArcaneCasePartitioner::_addGhostLayers(), Arcane::MshMeshWriter::_addGroupsToProcess(), Arcane::CartesianMeshImpl::_addPatch(), Arcane::Materials::MeshComponentData::_changeLocalIdsForInternalList(), Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::ArcaneCasePartitioner::_computeGroups(), Arcane::mesh::TiedInterfaceBuilder::_computeMasterInterface(), Arcane::ArcaneBasicMeshSubdividerService::_computeNodeUid(), Arcane::mesh::FaceUniqueIdBuilder2::_computeParallel(), Arcane::mesh::FaceUniqueIdBuilder2::_computeSequential(), Arcane::mesh::MeshRefinement::_contract(), Arcane::CartesianMeshCoarsening2::_createCoarseCells2D(), Arcane::CartesianMeshCoarsening2::_createCoarseCells3D(), Arcane::Hdf5VariableReaderHelper2::_createCorrespondance(), Arcane::VariableSynchronizerComputeList::_createList(), Arcane::ArcaneBasicMeshSubdividerService::_faceOrderArcane(), Arcane::Materials::MeshMaterialVariableSynchronizer::_fillCellsSequential(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::mesh::SubMeshTools::_fillGhostItems(), Arcane::Materials::MaterialModifierOperation::_filterValidIds(), Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::ArcaneBasicMeshSubdividerService::_generateOneHexa(), Arcane::ArcaneBasicMeshSubdividerService::_generateOneTetra(), Arcane::FaceDirectionMng::_internalComputeInfos(), Arcane::FaceDirectionMng::_internalComputeInfos(), Arcane::NodeDirectionMng::_internalComputeInfos(), Arcane::CellDirectionMng::_internalComputeInnerAndOuterItems(), Arcane::Accelerator::Impl::RunQueueImpl::_internalFreeRunningCommands(), Arcane::mesh::MeshRefinement::_makeFlagParallelConsistent(), Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_mergeProcessors(), Arcane::mesh::DynamicMesh::_multipleExchangeItems(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::MshMeshReader::_readElementsFromAsciiMshV4File(), Arcane::VtkMeshIOService::_readItemGroup(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::VtkMeshIOService::_readNodeGroup(), Arcane::VtkMeshIOService::_readStructuredGrid(), Arcane::mesh::MeshRefinement::_refineItems(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::ArcaneBasicMeshSubdividerService::_refineWithArcaneFaces(), Arcane::MetisMeshPartitioner::_removeEmptyPartsV2Helper(), Arcane::mesh::TiedInterfaceBuilder::_removeMasterFacesWithNoSlave(), Arcane::CaseMng::_searchInvalidOptions(), Arcane::mesh::ItemFamilyVariableSerializer::_serializePartialVariable(), Arcane::mesh::Faces2DToMergeFinder::_setEdgeFaceList(), Arcane::mesh::FacesToMergeFinder::_setEdgeFaceList(), Arcane::CartesianMeshAMRPatchMng::_shareInfosOfCellsAroundPatch(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::ItemTypeInfoBuilder::addEdge(), Arcane::ItemTypeInfoBuilder::addEdge2D(), Arcane::ItemTypeInfoBuilder::addFaceGeneric(), Arcane::ItemTypeInfoBuilder::addFaceHeptagon(), Arcane::ItemTypeInfoBuilder::addFaceHexagon(), Arcane::ItemTypeInfoBuilder::addFaceLine(), Arcane::ItemTypeInfoBuilder::addFaceLine3(), Arcane::ItemTypeInfoBuilder::addFaceLine4(), Arcane::ItemTypeInfoBuilder::addFaceOctogon(), Arcane::ItemTypeInfoBuilder::addFacePentagon(), Arcane::ItemTypeInfoBuilder::addFaceQuad(), Arcane::ItemTypeInfoBuilder::addFaceQuad8(), Arcane::ItemTypeInfoBuilder::addFaceQuad9(), Arcane::ItemTypeInfoBuilder::addFaceTriangle(), Arcane::ItemTypeInfoBuilder::addFaceTriangle6(), Arcane::ItemTypeInfoBuilder::addFaceVertex(), Arcane::mesh::GhostLayerBuilder::addGhostChildFromParent(), Arcane::ItemGroupImpl::addItems(), Arcane::ExternalPartitionConstraint::addLinkedCells(), Arcane::mesh::GraphDoFs::addLinks(), Arcane::mesh::MeshPartitionConstraintMng::addWeakConstraint(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::mesh::FaceFamily::applyTiedInterface(), Arcane::AMRZonePosition::cellsInPatch(), Arcane::AMRZonePosition::cellsInPatch(), Arcane::mesh::TiedInterfaceBuilder::changeOwners(), Arcane::MeshUtils::checkUniqueIdsHashCollective(), Arcane::mesh::DynamicMeshChecker::checkValidReplication(), Arcane::XmlNode::children(), Arcane::XmlNode::children(), Arcane::CartesianMeshAMRPatchMng::coarsen(), Arcane::mesh::MeshRefinement::coarsenItemsV2(), Arcane::BasicRayMeshIntersection::compute(), Arcane::VariableSynchronizerComputeList::compute(), Arcane::ItemConnectivitySynchronizer::computeExtraItemsToSend(), Arcane::mesh::TiedInterfaceBuilder::computeInterfaceConnections(), Arcane::UnstructuredMeshUtilities::computeNormal(), Arcane::SplitSDMeshPartitioner::ConnexifieDomaine(), Arcane::CartesianMeshCoarsening::createCoarseCells(), Arcane::ArrayDataT< DataType >::createSerializedDataRef(), Arcane::ScalarDataT< DataType >::createSerializedDataRef(), Arcane::StringScalarData::createSerializedDataRef(), Arcane::CartesianMeshAMRPatchMng::createSubLevel(), Arcane::MessagePassing::HybridParallelMng::createSubParallelMngRef(), Arcane::AMRPatchPositionSignatureCut::cut(), Arcane::CaseOptionList::deepGetChildren(), Arcane::Materials::MeshMaterialVariable::dependInfos(), Arcane::Variable::dependInfos(), Arcane::InternalInfosDumper::dumpArcaneDatabase(), Arcane::MeshPartitionerBase::dumpObject(), Arcane::VariableMng::dumpStats(), Arcane::AlephKappaService::execute(), Arcane::Process::execute(), Arcane::ActiveCellGroupComputeFunctor::executeFunctor(), Arcane::ActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::GhostItemGroupComputeFunctor::executeFunctor(), Arcane::InnerActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::InnerFaceItemGroupComputeFunctor::executeFunctor(), Arcane::InterfaceItemGroupComputeFunctor::executeFunctor(), Arcane::ItemItemGroupComputeFunctor< ItemType >::executeFunctor(), Arcane::LevelCellGroupComputeFunctor::executeFunctor(), Arcane::OuterActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::OuterFaceItemGroupComputeFunctor::executeFunctor(), Arcane::OwnActiveCellGroupComputeFunctor::executeFunctor(), Arcane::OwnActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::OwnItemGroupComputeFunctor::executeFunctor(), Arcane::OwnLevelCellGroupComputeFunctor::executeFunctor(), Arcane::ItemGroupPartialVariableObserver::executeReduce(), Arcane::mesh::ItemGroupDynamicMeshObserver::executeReduce(), Arcane::Materials::MeshMaterialMng::fillWithUsedVariables(), Arcane::MessagePassing::filterCommonStrings(), Arcane::VariableUtilities::filterCommonVariables(), Arcane::SodStandardGroupsBuilder::generateGroups(), Arcane::CaseOptionEnumValues::getValidNames(), Arcane::mesh::ItemFamilyVariableSerializer::initialize(), Arcane::SplitSDMeshPartitioner::LissageDuFront(), Arcane::SplitSDMeshPartitioner::MAJDomaine(), Arcane::mesh::ParallelAMRConsistency::makeNewItemsConsistent(), Arcane::mesh::DynamicMesh::mergeMeshes(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), Arcane::SplitSDMeshPartitioner::ParcoursFrontalDelta(), Arcane::mesh::ItemsExchangeInfo2::prepareToSend(), Arcane::Array< IVariable * >::push_back(), Arcane::XmfMeshReader::readMeshFromFile(), Arcane::CartesianMeshImpl::reduceNbGhostLayers(), Arcane::CartesianMeshAMRPatchMng::refine(), Arcane::VariableMng::removeAllVariables(), Arcane::mesh::ItemFamily::removeItems2(), Arcane::mesh::DynamicMeshIncrementalBuilder::removeNeedRemoveMarkedItems(), Arcane::mesh::ItemFamily::removeNeedRemoveMarkedItems(), Arcane::mesh::ParticleFamily::removeNeedRemoveMarkedItems(), Arcane::CartesianMeshCoarsening::removeRefinedCells(), Arcane::ItemGroupImpl::removeSuppressedItems(), Arcane::SplitSDMeshPartitioner::SelectElements(), Arcane::Materials::ItemMaterialVariableScalar< DataType >::serialize(), Arcane::mesh::ItemFamilyVariableSerializer::serialize(), Arcane::AlephKernel::setup(), Arcane::mesh::ItemGroupsSynchronize::synchronize(), Arcane::Materials::LegacyMeshMaterialSynchronizerImpl::synchronizeMaterialsInCells(), Arcane::TransferValuesParallelOperation::transferValues(), Arcane::Numerics::ParallelCorefinementService::update(), Arcane::Hdf5VariableInfoBase::writeGroup(), Arcane::MeshUtils::writeMeshConnectivity(), and Arcane::XmfMeshWriter::writeMeshToFile().
addRange() [1/6]
template<typename T> void Arcane::Array< T >::addRange (ArrayView< T > val) inline
Adds n elements of value val to the end of the array.
Definition at line 230 of file arccore/src/common/arccore/common/Array.h.
addRange() [2/6]
template<typename T> void Arcane::Array< T >::addRange (const Array< T > & val) inline
Adds n elements of value val to the end of the array.
Definition at line 240 of file arccore/src/common/arccore/common/Array.h.
addRange() [3/6]
template<typename T> void Arcane::Array< T >::addRange (ConstArrayView< T > val) inline
Adds n elements of value val to the end of the array.
Definition at line 220 of file arccore/src/common/arccore/common/Array.h.
addRange() [4/6]
template<typename T> void Arcane::Array< T >::addRange (ConstReferenceType val, Int64 n) inline
Adds n elements of value val to the end of the array.
Definition at line 215 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::CartesianMeshCoarsening2::_createCoarseCells3D(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::MshMeshReader::_readElementsFromAsciiMshV4File(), Arcane::MshParallelMeshReader::_readOneElementBlock(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::GraphDoFs::addLinks(), Arcane::ItemConnectivitySynchronizer::computeExtraItemsToSend(), Arcane::Process::execute(), Arcane::ParameterOptionElementsCollection::getIndexInAddr(), Arcane::Materials::ItemMaterialVariableArray< DataType >::serialize(), and Arcane::ItemConnectivityMng::setModifiedItems().
addRange() [5/6]
template<typename T> void Arcane::Array< T >::addRange (Span< const T > val) inline
Adds n elements of value val to the end of the array.
Definition at line 225 of file arccore/src/common/arccore/common/Array.h.
addRange() [6/6]
template<typename T> void Arcane::Array< T >::addRange (Span< T > val) inline
Adds n elements of value val to the end of the array.
Definition at line 235 of file arccore/src/common/arccore/common/Array.h.
at() [1/2]
template<typename T> T & Arcane::Array< T >::at (Int64 i) inline
Element at index i. Always checks for overflows.
Definition at line 335 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::Otf2LibWrapper::_buildOtf2LocationDefinition(), Arcane::VariableArrayT< T >::compact(), and Arcane::AlephKappaService::execute().
at() [2/2]
template<typename T> ConstReferenceType Arcane::Array< T >::at (Int64 i) const inline
Element at index i. Always checks for overflows.
Definition at line 341 of file arccore/src/common/arccore/common/Array.h.
back() [1/2]
template<typename T> T & Arcane::Array< T >::back () inline
Last element of the array.
The array must not be empty
Definition at line 381 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::mesh::ItemFamily::removeItems2().
back() [2/2]
template<typename T> ConstReferenceType Arcane::Array< T >::back () const inline
Last element of the array (const).
The array must not be empty
Definition at line 388 of file arccore/src/common/arccore/common/Array.h.
begin() [1/2]
template<typename T> iterator Arcane::Array< T >::begin () inline
Iterator over the first element of the array.
Definition at line 454 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::ArcaneCasePartitioner::_addGhostGroups(), Arcane::ArcaneBasicMeshSubdividerService::_computeNodeUid(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::ParallelExchanger::_processExchangeWithControl(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::MeshUtils::checkUniqueIdsHashCollective(), Arcane::AMRPatchPositionLevelGroup::fusionPatches(), Arcane::SplitSDMeshPartitioner::MAJDomaine(), Arcane::Array< IVariable * >::rend(), Arcane::Array< IVariable * >::rend(), and Arcane::VariableCollection::sortByName().
begin() [2/2]
template<typename T> const_iterator Arcane::Array< T >::begin () const inline
Constant iterator over the first element of the array.
Definition at line 457 of file arccore/src/common/arccore/common/Array.h.
clear()
template<typename T> void Arcane::Array< T >::clear () inline
Removes the elements from the array.
Definition at line 411 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::VariableIOReaderMng::_checkHashFunction(), Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::ArcaneCasePartitioner::_computeGroups(), Arcane::mesh::MeshExchange::_computeMeshConnectivityInfos2(), Arcane::Materials::IncrementalComponentModifier::_copyBetweenPartialsAndGlobals(), Arcane::Materials::MeshMaterialVariableSynchronizer::_fillCells(), Arcane::mesh::SubMeshTools::_fillGhostItems(), Arcane::Materials::MaterialModifierOperation::_filterValidIds(), Arcane::MEDMeshReader::_readItems(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::ArcaneBasicMeshSubdividerService::_refineWithArcaneFaces(), Arcane::Materials::IncrementalComponentModifier::_resizeVariablesIndexer(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::GhostLayerBuilder::addGhostChildFromParent(), Arcane::ConfigurationReader::addValuesFromXmlNode(), Arcane::mesh::FaceFamily::applyTiedInterface(), Arcane::AMRZonePosition::cellsInPatch(), Arcane::AMRZonePosition::cellsInPatch(), Arcane::ItemGroupImpl::clear(), Arcane::mesh::TiedInterfaceBuilder::computeInterfaceConnections(), Arcane::Numerics::GeometryKernelSurfaceToolsService::computeSurfaceContact(), Arcane::SplitSDMeshPartitioner::ConnexifieDomaine(), Arcane::AMRPatchPositionSignatureCut::cut(), Arcane::mesh::BasicParticleExchanger::exchangeItems(), Arcane::Process::execute(), Arcane::Materials::MeshMaterialMng::fillWithUsedVariables(), Arcane::MessagePassing::filterCommonStrings(), Arcane::GatherGroup::gatherToMasterIOT(), Arcane::TimeHistoryMngInternal::iterationsAndValues(), Arcane::ItemConnectivityMng::notifyLocalIdChanged(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), Arcane::mesh::CellFamilySerializer::serializeItems(), Arcane::mesh::ItemGroupsSynchronize::synchronize(), and Arcane::MeshUtils::writeMeshConnectivity().
clone()
template<typename T> Array< T > Arcane::Array< T >::clone () const inline
Clones the array.
Definition at line 434 of file arccore/src/common/arccore/common/Array.h.
constSmallSpan()
template<typename T> SmallSpan< const T > Arcane::Array< T >::constSmallSpan () const inline
Immutable view of this array.
Definition at line 165 of file arccore/src/common/arccore/common/Array.h.
constSpan()
template<typename T> Span< const T > Arcane::Array< T >::constSpan () const inline
Constant view of this array.
Definition at line 126 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::Array< IVariable * >::addRange(), Arcane::asBytes(), Arcane::MeshUtils::checkUniqueIdsHashCollective(), Arcane::Array< IVariable * >::clone(), Arcane::SharedArray< XmlNode >::clone(), Arcane::SmallArray< T, NbElement >::operator=(), Arcane::SharedArray< T >::SharedArray(), and Arcane::SmallArray< T, NbElement >::SmallArray().
constView()
template<typename T> ConstArrayView< T > Arcane::Array< T >::constView () const inline
Constant view of this array.
Definition at line 120 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::mesh::MeshRefinement::_interpolateData(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::ArcaneBasicMeshSubdividerService::_refineWithArcaneFaces(), Arcane::mesh::GraphDoFs::addLinks(), Arcane::MetisGraphGather::gatherGraph(), and Arcane::MetisGraphGather::scatterPart().
copy()
template<typename T> void Arcane::Array< T >::copy (Span< const T > rhs) inline
Copies the values from rhs into the instance.
The instance is resized so that this->size()==rhs.size().
Definition at line 427 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::VariableArrayT< T >::_compareVariable(), Arcane::mesh::DynamicMeshChecker::checkValidReplication(), Arcane::Array< IVariable * >::clone(), Arcane::mesh::TiedInterfaceBuilder::computeInterfaceConnections(), Arcane::mesh::ItemFamily::getCommunicatingSubDomains(), Arcane::SharedArray< T >::operator=(), Arcane::SharedArray< XmlNode >::operator=(), Arcane::SharedArray< XmlNode >::operator=(), Arcane::SharedArray< XmlNode >::operator=(), Arcane::SharedArray< XmlNode >::operator=(), Arcane::SmallArray< T, NbElement >::operator=(), Arcane::SmallArray< T, NbElement >::operator=(), Arcane::SmallArray< T, NbElement >::operator=(), Arcane::SmallArray< T, NbElement >::operator=(), Arcane::SmallArray< T, NbElement >::operator=(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), Arcane::UniqueArray< CaseOptionEnumValue * >::operator=(), and Arcane::UniqueArray< CaseOptionEnumValue * >::operator=().
data() [1/2]
template<typename T> T * Arcane::Array< T >::data () inline
Access to the root of the array without any protection
Definition at line 449 of file arccore/src/common/arccore/common/Array.h.
data() [2/2]
template<typename T> const T * Arcane::Array< T >::data () const inline
Access to the root of the array without any protection.
Definition at line 447 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::Materials::IncrementalComponentModifier::_copyBetweenPartialsAndGlobals(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::MEDMeshReader::_readItems(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::Materials::IncrementalComponentModifier::_resizeVariablesIndexer(), Arcane::mesh::DynamicMeshKindInfos::beginCompactItems(), Arcane::mesh::IncrementalItemConnectivity::compactConnectivityList(), Arcane::Bzip2DataCompressor::compress(), Arcane::Bzip2DeflateService::compress(), Arcane::LZ4DataCompressor::compress(), Arcane::LZ4DeflateService::compress(), Arcane::ZstdDataCompressor::compress(), Arcane::BasicRayMeshIntersection::compute(), Arcane::VariableSynchronizerMpiCommunicator::compute(), Arcane::Array2DataT< DataType >::computeHash(), Arcane::Process::execute(), Arcane::MetisGraphGather::gatherGraph(), Arcane::GatherGroup::gatherToMasterIOT(), Arcane::Hdf5ReaderWriter::metaData(), Arcane::MetisGraphGather::scatterPart(), Arcane::Array2DataT< DataType >::serialize(), Arcane::ArrayDataT< DataType >::serialize(), Arcane::Materials::ItemMaterialVariableArray< DataType >::serialize(), Arcane::Materials::ItemMaterialVariableScalar< DataType >::serialize(), Arcane::NumArrayDataT< DataType, RankValue >::serialize(), and Arcane::SHA3Algorithm::SHA3::sha3_final().
end() [1/2]
template<typename T> iterator Arcane::Array< T >::end () inline
Iterator over the first element after the end of the array.
Definition at line 460 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::ArcaneBasicMeshSubdividerService::_computeNodeUid(), Arcane::ParallelExchanger::_processExchangeWithControl(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::MeshUtils::checkUniqueIdsHashCollective(), Arcane::AMRPatchPositionLevelGroup::fusionPatches(), Arcane::Array< IVariable * >::rbegin(), Arcane::Array< IVariable * >::rbegin(), and Arcane::VariableCollection::sortByName().
end() [2/2]
template<typename T> const_iterator Arcane::Array< T >::end () const inline
Constant iterator over the first element after the end of the array.
Definition at line 463 of file arccore/src/common/arccore/common/Array.h.
fill()
template<typename T> void Arcane::Array< T >::fill (ConstReferenceType value) inline
Fills the array with the value value.
Definition at line 417 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::ArcaneCasePartitioner::_addGhostLayers(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::ArcaneCasePartitioner::_computeGroups(), Arcane::mesh::MeshExchange::_computeMeshConnectivityInfos2(), Arcane::VariableSynchronizerComputeList::_createList(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::VtkLegacyMeshWriter::_writeMeshToFile(), Arcane::ItemGroupImpl::addItems(), Arcane::ExternalPartitionConstraint::addLinkedCells(), Arcane::AlephMatrix::assemble(), Arcane::mesh::DynamicMeshKindInfos::beginCompactItems(), Arcane::DumpWEnsight7::beginWrite(), Arcane::mesh::TiedInterfaceBuilder::changeOwners(), Arcane::mesh::TiedInterfaceBuilder::changeOwnersOld(), Arcane::BasicRayMeshIntersection::compute(), Arcane::mesh::Parallel3EdgeUniqueIdBuilder::compute(), Arcane::MeshPartitionerBase::dumpObject(), Arcane::ActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::InnerActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::InnerFaceItemGroupComputeFunctor::executeFunctor(), Arcane::ItemItemGroupComputeFunctor< ItemType >::executeFunctor(), Arcane::OuterActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::OuterFaceItemGroupComputeFunctor::executeFunctor(), Arcane::OwnActiveFaceItemGroupComputeFunctor::executeFunctor(), Arcane::SplitSDMeshPartitioner::MAJDomaine(), and Arcane::Materials::LegacyMeshMaterialSynchronizerImpl::synchronizeMaterialsInCells().
front() [1/2]
template<typename T> T & Arcane::Array< T >::front () inline
First element of the array.
The array must not be empty
Definition at line 396 of file arccore/src/common/arccore/common/Array.h.
front() [2/2]
template<typename T> ConstReferenceType Arcane::Array< T >::front () const inline
First element of the array (const).
The array must not be empty
Definition at line 404 of file arccore/src/common/arccore/common/Array.h.
item()
template<typename T> ConstReferenceType Arcane::Array< T >::item (Int64 i) const inline
Element at index i.
Definition at line 353 of file arccore/src/common/arccore/common/Array.h.
operator ArrayView< T >()
template<typename T> Arcane::Array< T >::operator ArrayView< T > () inline
Definition at line 106 of file arccore/src/common/arccore/common/Array.h.
operator ConstArrayView< T >()
template<typename T> Arcane::Array< T >::operator ConstArrayView< T > () const inline
Definition at line 101 of file arccore/src/common/arccore/common/Array.h.
operator Span< const T >()
template<typename T> Arcane::Array< T >::operator Span< const T > () const inline
Definition at line 111 of file arccore/src/common/arccore/common/Array.h.
operator Span< T >()
template<typename T> Arcane::Array< T >::operator Span< T > () inline
Definition at line 115 of file arccore/src/common/arccore/common/Array.h.
operator()() [1/2]
template<typename T> T & Arcane::Array< T >::operator() (Int64 i) inline
Element at index i.
Definition at line 374 of file arccore/src/common/arccore/common/Array.h.
operator()() [2/2]
template<typename T> ConstReferenceType Arcane::Array< T >::operator() (Int64 i) const inline
Definition at line 368 of file arccore/src/common/arccore/common/Array.h.
operator[]() [1/2]
template<typename T> T & Arcane::Array< T >::operator[] (Int64 i) inline
Element at index i.
Definition at line 363 of file arccore/src/common/arccore/common/Array.h.
operator[]() [2/2]
template<typename T> ConstReferenceType Arcane::Array< T >::operator[] (Int64 i) const inline
Element at index i.
Definition at line 357 of file arccore/src/common/arccore/common/Array.h.
popBack()
template<typename T> void Arcane::Array< T >::popBack () inline
Removes the last entity from the array.
Definition at line 328 of file arccore/src/common/arccore/common/Array.h.
push_back()
template<typename T> void Arcane::Array< T >::push_back (ConstReferenceType val) inline
Adds the element val to the end of the array.
Definition at line 497 of file arccore/src/common/arccore/common/Array.h.
range() [1/2]
template<typename T> ArrayRange< pointer > Arcane::Array< T >::range () inline
Iteration range from the first to the last element.
Definition at line 481 of file arccore/src/common/arccore/common/Array.h.
range() [2/2]
template<typename T> ArrayRange< const_pointer > Arcane::Array< T >::range () const inline
Iteration range from the first to the last element.
Definition at line 488 of file arccore/src/common/arccore/common/Array.h.
rbegin() [1/2]
template<typename T> reverse_iterator Arcane::Array< T >::rbegin () inline
Reverse iterator over the first element of the array.
Definition at line 466 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::VariableCollection::sortByName().
rbegin() [2/2]
template<typename T> const_reverse_iterator Arcane::Array< T >::rbegin () const inline
Reverse iterator over the first element of the array.
Definition at line 469 of file arccore/src/common/arccore/common/Array.h.
remove()
template<typename T> void Arcane::Array< T >::remove (Int64 index) inline
Removes the entity at index index.
All elements of this array after the removed one are shifted.
Definition at line 316 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::AMRPatchPositionLevelGroup::fusionPatches().
rend() [1/2]
template<typename T> reverse_iterator Arcane::Array< T >::rend () inline
Reverse iterator over the first element after the end of the array.
Definition at line 472 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::VariableCollection::sortByName().
rend() [2/2]
template<typename T> const_reverse_iterator Arcane::Array< T >::rend () const inline
Reverse iterator over the first element after the end of the array.
Definition at line 475 of file arccore/src/common/arccore/common/Array.h.
reserve()
template<typename T> void Arcane::Array< T >::reserve (Int64 new_capacity) inline
Reserves memory for new_capacity elements.
Definition at line 276 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::ArcaneCasePartitioner::_addGhostGroups(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::mesh::FaceUniqueIdBuilder2::_computeSequential(), Arcane::Materials::IncrementalComponentModifier::_copyBetweenPartialsAndGlobals(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::Materials::MaterialModifierOperation::_filterValidIds(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::FaceDirectionMng::_internalComputeInfos(), Arcane::FaceDirectionMng::_internalComputeInfos(), Arcane::mesh::MeshRefinement::_makeFlagParallelConsistent(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::ArcaneBasicMeshSubdividerService::_refineWithArcaneFaces(), Arcane::Materials::IncrementalComponentModifier::_resizeVariablesIndexer(), Arcane::mesh::Faces2DToMergeFinder::_setEdgeFaceList(), Arcane::mesh::FacesToMergeFinder::_setEdgeFaceList(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::mesh::GraphDoFs::addLinks(), Arcane::Parallel::VariableParallelOperationBase::applyOperation(), Arcane::MemoryUtils::checkResizeArrayWithCapacity(), Arcane::mesh::Parallel3EdgeUniqueIdBuilder::compute(), Arcane::mesh::CellFamilySerializer::deserializeItems(), Arcane::ItemGroupPartialVariableObserver::executeReduce(), Arcane::mesh::ItemGroupDynamicMeshObserver::executeReduce(), Arcane::UnstructuredMeshUtilities::localIdsFromConnectivity(), Arcane::mesh::ParallelAMRConsistency::makeNewItemsConsistent(), Arcane::mesh::ItemsExchangeInfo2::prepareToSend(), Arcane::CartesianMeshAMRPatchMng::refine(), Arcane::mesh::DynamicMeshIncrementalBuilder::removeNeedRemoveMarkedItems(), Arcane::mesh::ItemFamily::removeNeedRemoveMarkedItems(), Arcane::mesh::ParticleFamily::removeNeedRemoveMarkedItems(), Arcane::ItemGroupImpl::removeSuppressedItems(), Arcane::mesh::ItemFamilyVariableSerializer::serialize(), Arcane::mesh::CellFamilySerializer::serializeItems(), Arcane::mesh::ItemGroupsSynchronize::synchronize(), and Arcane::MeshUtils::writeMeshConnectivity().
resize() [1/2]
template<typename T> void Arcane::Array< T >::resize (Int64 s) inline
Changes the number of elements in the array to s.
Note
If the new array is larger than the old one, the new elements are not initialized if it is a POD type.
Definition at line 250 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::mesh::DynamicMeshChecker::_checkFacesOrientation(), Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::DumpWEnsight7::_computeGroupParts(), Arcane::Materials::AllEnvData::_computeInfosForEnvCells(), Arcane::ArcaneBasicMeshSubdividerService::_computeNodeUid(), Arcane::VariableSynchronizerComputeList::_createList(), Arcane::Materials::MeshMaterialVariableSynchronizer::_fillCellsAccelerator(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_mergeProcessors(), Arcane::mesh::DynamicMesh::_multipleExchangeItems(), Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::SubDomain::_printCPUAffinity(), Arcane::VoronoiMeshIOService::_readCellsHybridGrid(), Arcane::VtkMeshIOService::_readCellsUnstructuredGrid(), Arcane::MshMeshReader::_readElementsFromAsciiMshV4File(), Arcane::MshParallelMeshReader::_readElementsFromFile(), Arcane::VtkMeshIOService::_readFacesMesh(), Arcane::MEDMeshReader::_readItems(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::MshMeshReader::_readNodesFromAsciiMshV4File(), Arcane::MshParallelMeshReader::_readNodesFromFile(), Arcane::VoronoiMeshIOService::_readNodesHybridGrid(), Arcane::VtkMeshIOService::_readNodesUnstructuredGrid(), Arcane::MshParallelMeshReader::_readOneElementBlock(), Arcane::MshParallelMeshReader::_readPeriodic(), Arcane::LimaCutInfosReader::_readUniqueIndex(), Arcane::VtkMeshIOService::_readUnstructuredGrid(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::DumpWEnsight7::_saveGroup(), Arcane::mesh::ItemFamilyVariableSerializer::_serializePartialVariable(), Arcane::MshParallelMeshReader::_setNodesCoordinates(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::DynamicMeshIncrementalBuilder::addCells3(), Arcane::mesh::GraphDoFs::addDualNodes(), Arcane::ExternalPartitionConstraint::addLinkedCells(), Arcane::Parallel::VariableParallelOperationBase::applyOperation(), Arcane::AlephMatrix::assemble(), Arcane::DumpWEnsight7::beginWrite(), Arcane::MemoryUtils::checkResizeArrayWithCapacity(), Arcane::mesh::DynamicMeshChecker::checkValidReplication(), Arcane::Bzip2DataCompressor::compress(), Arcane::Bzip2DeflateService::compress(), Arcane::LZ4DataCompressor::compress(), Arcane::LZ4DeflateService::compress(), Arcane::ZstdDataCompressor::compress(), Arcane::BasicRayMeshIntersection::compute(), Arcane::BasicRayMeshIntersection::compute(), Arcane::SimpleGridMeshPartitioner::GhostCellsBuilder::computeExtraCellsToSend(), Arcane::mesh::FaceUniqueIdBuilder2::computeFacesUniqueIdAndOwnerVersion5(), Arcane::CartesianMeshCoarsening2::createCoarseCells(), Arcane::CartesianMeshCoarsening::createCoarseCells(), Arcane::Array2DataT< DataType >::createSerializedDataRef(), Arcane::MessagePassing::HybridParallelMng::createSubParallelMngRef(), Arcane::mesh::CellFamilySerializer::deserializeItems(), Arcane::mesh::IndirectItemFamilySerializer::deserializeItems(), Arcane::mesh::ParticleFamilySerializer::deserializeItems(), Arcane::Hdf5Utils::StandardArrayT< DataType >::directRead(), Arcane::ExpressionImpl::dumpIf(), Arcane::Materials::CellMaterialVariableScalarRef< DataType_ >::fillToArray(), Arcane::Materials::CellMaterialVariableScalarRef< DataType_ >::fillToArray(), Arcane::MeshUtils::fillUniqueIds(), Arcane::mesh::TiedInterfaceExchanger::finalize(), Arcane::MetisGraphGather::gatherGraph(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::BasicSerializer::getArray(), Arcane::mesh::ItemFamily::getCommunicatingSubDomains(), Arcane::UnstructuredMeshUtilities::localIdsFromConnectivity(), Arcane::mesh::MeshNodeMerger::mergeNodes(), Arcane::DataSynchronizeInfo::recompute(), Arcane::ItemGroupImpl::removeAddItems(), Arcane::ItemGroupImpl::removeSuppressedItems(), Arcane::MetisGraphGather::scatterPart(), Arcane::Array2DataT< DataType >::serialize(), Arcane::Materials::ItemMaterialVariableArray< DataType >::serialize(), Arcane::Materials::ItemMaterialVariableScalar< DataType >::serialize(), Arcane::NumArrayDataT< DataType, RankValue >::serialize(), Arcane::ItemGroupImpl::setItems(), Arcane::SHA3Algorithm::SHA3::sha3_final(), Arcane::Numerics::ParallelCorefinementService::update(), Arcane::ItemMultiArrayConnectivity::updateConnectivity(), Arcane::MeshUtils::writeMeshConnectivity(), and Arcane::Hdf5ItemVariableInfo< VariableType, DataType >::writeVariable().
resize() [2/2]
template<typename T> void Arcane::Array< T >::resize (Int64 s, ConstReferenceType fill_value) inline
Changes the number of elements in the array to s.
If the new array is larger than the old one, the new elements are initialized with the value fill_value.
Definition at line 257 of file arccore/src/common/arccore/common/Array.h.
resizeNoInit()
template<typename T> void Arcane::Array< T >::resizeNoInit (Int64 s) inline
Resizes without initializing new values.
Warning
This can cause undefined behavior if the type T is not trivially copyable because the values are not initialized afterwards and the destructor of T will be called upon instance destruction.
Definition at line 270 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::GatherGroup::gatherToMasterIOT().
sample()
template<typename T> void Arcane::Array< T >::sample (ConstArrayView< Integer > indexes, ArrayView< T > result) const inline
Extracts a sub-array from a list of indices.
The result is stored in result whose size must be at least equal to the size of indexes.
Definition at line 193 of file arccore/src/common/arccore/common/Array.h.
setAt()
template<typename T> void Arcane::Array< T >::setAt (Int64 i, ConstReferenceType value) inline
Sets the element at index i. Always checks for overflows.
Definition at line 347 of file arccore/src/common/arccore/common/Array.h.
setItem()
template<typename T> void Arcane::Array< T >::setItem (Int64 i, ConstReferenceType v) inline
Element at index i.
Definition at line 355 of file arccore/src/common/arccore/common/Array.h.
shrink() [1/2]
template<typename T> void Arcane::Array< T >::shrink () inline
Reallocates to free unused memory.
After this call, capacity() will be equal to size(). If size() is null or very small, it is possible that capacity() is slightly larger.
Definition at line 287 of file arccore/src/common/arccore/common/Array.h.
shrink() [2/2]
template<typename T> void Arcane::Array< T >::shrink (Int64 new_capacity) inline
Reallocates memory to have a capacity close to new_capacity.
Definition at line 295 of file arccore/src/common/arccore/common/Array.h.
shrink_to_fit()
template<typename T> void Arcane::Array< T >::shrink_to_fit () inline
Reallocates to free unused memory.
See also
shrink().
Definition at line 305 of file arccore/src/common/arccore/common/Array.h.
smallSpan() [1/2]
template<typename T> SmallSpan< T > Arcane::Array< T >::smallSpan () inline
Mutable view of this array.
Definition at line 170 of file arccore/src/common/arccore/common/Array.h.
smallSpan() [2/2]
template<typename T> SmallSpan< const T > Arcane::Array< T >::smallSpan () const inline
Immutable view of this array.
Definition at line 159 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::Array< IVariable * >::constSmallSpan().
span() [1/2]
template<typename T> Span< T > Arcane::Array< T >::span () inline
Mutable view of this array.
Definition at line 154 of file arccore/src/common/arccore/common/Array.h.
span() [2/2]
template<typename T> Span< const T > Arcane::Array< T >::span () const inline
Immutable view of this array.
Definition at line 149 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::SimpleTableWriterHelper::_computeName(), Arcane::MEDMeshReader::_readFaces(), Arcane::asWritableBytes(), Arcane::SimpleTableInternalMng::column(), Arcane::SimpleTableInternalMng::row(), Arcane::Accelerator::viewIn(), Arcane::Accelerator::viewInOut(), and Arcane::Accelerator::viewOut().
subConstView()
template<typename T> ConstArrayView< T > Arcane::Array< T >::subConstView (Int64 abegin, Int32 asize) const inline
Sub-view starting from element abegin and containing asize elements.
If (abegin + asize) is greater than the array size, the view is truncated to that size, potentially returning an empty view.
Definition at line 136 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::mesh::GraphDoFs::addLinks(), and Arcane::SimpleCsvReaderWriter::readTable().
subView()
template<typename T> ArrayView< T > Arcane::Array< T >::subView (Int64 abegin, Integer asize) inline
Sub-view starting from element abegin and containing asize elements.
If (abegin + asize) is greater than the array size, the view is truncated to that size, potentially returning an empty view.
Definition at line 181 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::VtkMeshIOService::_readUnstructuredGrid(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::CartesianMeshAMRPatchMng::_shareInfosOfCellsAroundPatch(), Arcane::ItemGroupImpl::addItems(), Arcane::AMRPatchPositionSignature::compress(), Arcane::CartesianMeshAMRPatchMng::createSubLevel(), and Arcane::CartesianMeshAMRPatchMng::refine().
unguardedBasePointer() [1/2]
template<typename T> T * Arcane::Array< T >::unguardedBasePointer () inline
Access to the root of the array without any protection
Definition at line 444 of file arccore/src/common/arccore/common/Array.h.
unguardedBasePointer() [2/2]
template<typename T> const T * Arcane::Array< T >::unguardedBasePointer () const inline
Access to the root of the array without any protection
Definition at line 442 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::TimeHistoryMngInternal::_dumpSummaryOfCurves(), Arcane::TimeHistoryMngInternal::_dumpSummaryOfCurvesLegacy(), Arcane::ItemGroupImpl::addItems(), Arcane::TimeHistoryMngInternal::dumpCurves(), Arcane::ItemGroupImpl::removeSuppressedItems(), and Arcane::CheckpointMng::writeDefaultCheckpoint().
view()
template<typename T> ArrayView< T > Arcane::Array< T >::view () const inline
Mutable view of this array.
Definition at line 143 of file arccore/src/common/arccore/common/Array.h.
Referenced by Arcane::MshParallelMeshReader::_addFaceGroup(), Arcane::Materials::AllEnvData::_computeInfosForEnvCells(), Arcane::ArcaneBasicMeshSubdividerService::_generateOneHexa(), Arcane::ArcaneBasicMeshSubdividerService::_generateOneQuad(), Arcane::ArcaneBasicMeshSubdividerService::_generateOneTetra(), Arcane::ArcaneBasicMeshSubdividerService::_generateOneTri(), Arcane::mesh::MeshRefinement::_interpolateData(), Arcane::MshParallelMeshReader::_readOneElementBlock(), Arcane::ArcaneBasicMeshSubdividerService::_refineOnce(), Arcane::mesh::DynamicMeshIncrementalBuilder::addEdges2(), Arcane::mesh::DynamicMeshIncrementalBuilder::addFaces2(), Arcane::mesh::GraphDoFs::addLinks(), Arcane::DumpWEnsight7::beginWrite(), Arcane::mesh::DynamicMeshChecker::checkValidReplication(), Arcane::mesh::ParticleFamilySerializer::deserializeItems(), Arcane::AlephKappaService::execute(), Arcane::Materials::CellMaterialVariableScalarRef< DataType_ >::fillToArray(), Arcane::Materials::CellMaterialVariableScalarRef< DataType_ >::fillToArray(), Arcane::MetisGraphGather::gatherGraph(), Arcane::mesh::ItemFamily::removeItems2(), Arcane::MetisGraphGather::scatterPart(), Arcane::Array2DataT< DataType >::serialize(), Arcane::NumArrayDataT< DataType, RankValue >::serialize(), and Arcane::AlephKernel::setup().
The documentation for this class was generated from the following file:
arccore/src/common/arccore/common/Array.h