Arcane: Arcane::geometric::GeomShapeView Class Reference
Arcane::geometric::GeomShapeView Class Reference
Geometric elements.
Constant view on a geometric shape GeomShape.
#include <arcane/geometry/GeomShapeView.h>
Public Member Functions
Filling of control sub-volumes for a specific type.
The geometric type (geomType()) of the instance must match the chosen method.
void fillSubZoneTriangle3 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneQuad4 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZonePentagon5 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneHexagon6 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneTetraedron4 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZonePyramid5 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZonePentaedron6 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneHexaedron8 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneHeptaedron10 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneOctaedron12 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Filling of control sub-volumes (obsolete methods)
These methods are obsolete and must be replaced by the equivalent method with the full element name.
void fillSubZoneTriangle (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneQuad (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZonePentagon (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneHexagon (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneTetra (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZonePyramid (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZonePenta (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneHexa (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneWedge7 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
void fillSubZoneWedge8 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Triangle3ElementConstView toTriangle3Element () const
Returns a specific view to a geometric element of type GeomType::Triangle3.
Quad4ElementConstView toQuad4Element () const
Returns a specific view to a geometric element of type GeomType::Quad4.
Pentagon5ElementConstView toPentagon5Element () const
Returns a specific view to a geometric element of type GeomType::Pentagon5.
Hexagon6ElementConstView toHexagon6Element () const
Returns a specific view to a geometric element of type GeomType::Hexagon6.
Tetraedron4ElementConstView toTetraedron4Element () const
Returns a specific view to a geometric element of type GeomType::Tetraedron4.
Pyramid5ElementConstView toPyramid5Element () const
Returns a specific view to a geometric element of type GeomType::Pyramid5.
Pentaedron6ElementConstView toPentaedron6Element () const
Returns a specific view to a geometric element of type GeomType::Pentaedron6.
Hexaedron8ElementConstView toHexaedron8Element () const
Returns a specific view to a geometric element of type GeomType::Hexaedron8.
Heptaedron10ElementConstView toHeptaedron10Element () const
Returns a specific view to a geometric element of type GeomType::Heptaedron10.
Octaedron12ElementConstView toOctaedron12Element () const
Returns a specific view to a geometric element of type GeomType::Octaedron12.
Triangle3ShapeView toTriangle3Shape () const
Returns a specific view for a geometric shape of type GeomType::Triangle3.
Quad4ShapeView toQuad4Shape () const
Returns a specific view for a geometric shape of type GeomType::Quad4.
Pentagon5ShapeView toPentagon5Shape () const
Returns a specific view for a geometric shape of type GeomType::Pentagon5.
Hexagon6ShapeView toHexagon6Shape () const
Returns a specific view for a geometric shape of type GeomType::Hexagon6.
Tetraedron4ShapeView toTetraedron4Shape () const
Returns a specific view for a geometric shape of type GeomType::Tetraedron4.
Pyramid5ShapeView toPyramid5Shape () const
Returns a specific view for a geometric shape of type GeomType::Pyramid5.
Pentaedron6ShapeView toPentaedron6Shape () const
Returns a specific view for a geometric shape of type GeomType::Pentaedron6.
Hexaedron8ShapeView toHexaedron8Shape () const
Returns a specific view for a geometric shape of type GeomType::Hexaedron8.
Heptaedron10ShapeView toHeptaedron10Shape () const
Returns a specific view for a geometric shape of type GeomType::Heptaedron10.
Octaedron12ShapeView toOctaedron12Shape () const
Returns a specific view for a geometric shape of type GeomType::Octaedron12.
void fillSubZoneElement (HexaElementView hexa, Integer i)
Fills hexa with the information of the i-th sub-control volume.
void fillSubZoneElement (QuadElementView quad, Integer i)
Fills quad with the information of the i-th sub-control volume.
ARCANE_DEPRECATED_122 void initFromHexa (HexaElementConstView hexa, GeomShape &geom_cell)
ARCANE_DEPRECATED_122 void initFromQuad (QuadElementConstView hexa, GeomShape &geom_cell)
Static Public Member Functions
static void initializeConnectivity ()
Friends
class GeomShapeMng
class GeomShape
class GeomShapeConnectivity
Coordinate Retrieval.
const Real3 node (Integer i) const
Position of the i-th node of the shape.
const Real3 face (Integer i) const
Position of the center of the i-th face of the shape.
const Real3 center () const
Position of the center of the shape.
const Real3 edge (Integer i) const
Position of the center of the i-th edge of the shape.
Item item () const
Associated entity (null if none).
Cell cell () const
Associated cell (null if none).
Face face () const
Associated face (null if none).
void _setArray (const Real3 *node_ptr, const Real3 *face_ptr, const Real3 *center_ptr)
const Real3POD * _nodeView () const
Connectivity Information.
const NodeConnectic & nodeConnectic (Integer i) const
Node connectivity information.
const EdgeConnectic & edgeConnectic (Integer i) const
Edge connectivity information.
const FaceConnectic & faceConnectic (Integer i) const
Face connectivity information.
Integer nbSubZone () const
Number of sub-control volumes.
Integer nbSvcFace () const
Number of internal SVC faces.
Integer nodeAssociation (Integer i) const
Local number of the vertex associated with the sub-control volume.
const SVCFaceConnectic & svcFaceConnectic (Integer i) const
Integer edgeNodeSubZoneId (Integer i) const
Local numbers within the sub-control volumes.
Integer faceNodeSubZoneId (Integer i) const
GeomType geomType () const
Geometric type of the shape.
void _setItem (Item item)
void _setNullItem (int item_type)
Detailed Description
Constant view on a geometric shape GeomShape.
A view on a geometric shape allows for the optimized retrieval of the position of nodes, faces, and edges (in 3D) of a geometric object.
This class manages a view on a geometric shape. There are two ways to initialize a view:
by retrieving the view associated with a mesh cell via the call to GeomShapeMng::initShape(). In this case, it is possible to retrieve the associated cell via the cell() method.
from a temporary instance of GeomShape via one of the two methods initFromHexa() or initFromQuad().
Definition at line 59 of file GeomShapeView.h.
Constructor & Destructor Documentation
GeomShapeView()
Arcane::geometric::GeomShapeView::GeomShapeView () inline
Definition at line 76 of file GeomShapeView.h.
Member Function Documentation
_nodeView()
const Real3POD * Arcane::geometric::GeomShapeView::_nodeView () const inline protected
Definition at line 165 of file GeomShapeView.h.
_setArray()
void Arcane::geometric::GeomShapeView::_setArray (const Real3 * node_ptr, const Real3 * face_ptr, const Real3 * center_ptr) inline protected
Definition at line 145 of file GeomShapeView.h.
_setItem()
void Arcane::geometric::GeomShapeView::_setItem (Item item) inline protected
Definition at line 241 of file GeomShapeView.h.
_setNullItem()
void Arcane::geometric::GeomShapeView::_setNullItem (int item_type) inline protected
Definition at line 247 of file GeomShapeView.h.
cell()
Cell Arcane::geometric::GeomShapeView::cell () const inline
Associated cell (null if none).
Definition at line 139 of file GeomShapeView.h.
center()
const Real3 Arcane::geometric::GeomShapeView::center () const inline
Position of the center of the shape.
Definition at line 124 of file GeomShapeView.h.
Referenced by fillSubZoneElement(), fillSubZoneElement(), fillSubZoneHeptaedron10(), fillSubZoneHexaedron8(), fillSubZoneOctaedron12(), fillSubZonePentaedron6(), fillSubZonePyramid5(), fillSubZoneQuad4(), fillSubZoneTetraedron4(), and fillSubZoneTriangle3().
edge()
const Real3 Arcane::geometric::GeomShapeView::edge (Integer i) const inline
Position of the center of the i-th edge of the shape.
Definition at line 130 of file GeomShapeView.h.
References node().
Referenced by fillSubZoneElement(), fillSubZoneHeptaedron10(), fillSubZoneHexaedron8(), fillSubZoneOctaedron12(), fillSubZonePentaedron6(), fillSubZonePyramid5(), and fillSubZoneTetraedron4().
edgeConnectic()
const EdgeConnectic & Arcane::geometric::GeomShapeView::edgeConnectic (Integer i) const inline
Edge connectivity information.
Definition at line 180 of file GeomShapeView.h.
edgeNodeSubZoneId()
Integer Arcane::geometric::GeomShapeView::edgeNodeSubZoneId (Integer i) const inline
Local numbers within the sub-control volumes.
Definition at line 215 of file GeomShapeView.h.
face() [1/2]
Face Arcane::geometric::GeomShapeView::face () const inline
Associated face (null if none).
Definition at line 141 of file GeomShapeView.h.
Referenced by fillSubZoneElement(), fillSubZoneElement(), fillSubZoneHeptaedron10(), fillSubZoneHexaedron8(), fillSubZoneOctaedron12(), fillSubZonePentaedron6(), fillSubZonePyramid5(), fillSubZoneQuad4(), fillSubZoneTetraedron4(), and fillSubZoneTriangle3().
face() [2/2]
const Real3 Arcane::geometric::GeomShapeView::face (Integer i) const inline
Position of the center of the i-th face of the shape.
Definition at line 118 of file GeomShapeView.h.
Referenced by fillSubZoneElement().
faceConnectic()
const FaceConnectic & Arcane::geometric::GeomShapeView::faceConnectic (Integer i) const inline
Face connectivity information.
Definition at line 186 of file GeomShapeView.h.
faceNodeSubZoneId()
Integer Arcane::geometric::GeomShapeView::faceNodeSubZoneId (Integer i) const inline
Definition at line 220 of file GeomShapeView.h.
fillSubZoneElement() [1/2]
void Arcane::geometric::GeomShapeView::fillSubZoneElement (HexaElementView hexa, Integer i)
Fills hexa with the information of the i-th sub-control volume.
Definition at line 243 of file GeomShapeView.cc.
References center(), edge(), face(), face(), Arcane::geometric::Hexaedron8ElementView::init(), node(), nodeAssociation(), and nodeConnectic().
Referenced by fillSubZonePentagon(), and fillSubZoneQuad().
fillSubZoneElement() [2/2]
void Arcane::geometric::GeomShapeView::fillSubZoneElement (QuadElementView quad, Integer i)
Fills quad with the information of the i-th sub-control volume.
Definition at line 170 of file GeomShapeView.cc.
References center(), face(), Arcane::geometric::Quad4ElementView::init(), node(), nodeAssociation(), and nodeConnectic().
fillSubZoneHeptaedron10()
void Arcane::geometric::GeomShapeView::fillSubZoneHeptaedron10 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Heptaedron10
Definition at line 374 of file GeomShapeView.cc.
References center(), edge(), face(), Arcane::geometric::Hexaedron8ElementView::init(), and node().
fillSubZoneHexa()
void Arcane::geometric::GeomShapeView::fillSubZoneHexa (Hexaedron8ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneHexaedron8() instead
Definition at line 129 of file GeomShapeView.h.
fillSubZoneHexaedron8()
void Arcane::geometric::GeomShapeView::fillSubZoneHexaedron8 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Hexaedron8
Definition at line 256 of file GeomShapeView.cc.
References center(), edge(), face(), Arcane::geometric::Hexaedron8ElementView::init(), and node().
fillSubZoneHexagon()
void Arcane::geometric::GeomShapeView::fillSubZoneHexagon (Quad4ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneHexagon6() instead
Definition at line 101 of file GeomShapeView.h.
References initFromQuad().
fillSubZoneHexagon6()
void Arcane::geometric::GeomShapeView::fillSubZoneHexagon6 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Hexagon6
Definition at line 234 of file GeomShapeView.cc.
fillSubZoneOctaedron12()
void Arcane::geometric::GeomShapeView::fillSubZoneOctaedron12 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Octaedron12
Definition at line 414 of file GeomShapeView.cc.
References center(), edge(), face(), Arcane::geometric::Hexaedron8ElementView::init(), and node().
fillSubZonePenta()
void Arcane::geometric::GeomShapeView::fillSubZonePenta (Hexaedron8ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZonePentaedron6() instead
Definition at line 122 of file GeomShapeView.h.
fillSubZonePentaedron6()
void Arcane::geometric::GeomShapeView::fillSubZonePentaedron6 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Pentaedron6
Definition at line 324 of file GeomShapeView.cc.
References center(), edge(), face(), Arcane::geometric::Hexaedron8ElementView::init(), and node().
fillSubZonePentagon()
void Arcane::geometric::GeomShapeView::fillSubZonePentagon (Quad4ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZonePentagon5() instead
Definition at line 94 of file GeomShapeView.h.
References fillSubZoneElement(), and initFromHexa().
fillSubZonePentagon5()
void Arcane::geometric::GeomShapeView::fillSubZonePentagon5 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Pentagon5
Definition at line 225 of file GeomShapeView.cc.
fillSubZonePyramid()
void Arcane::geometric::GeomShapeView::fillSubZonePyramid (Hexaedron8ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZonePyramid5() instead
Definition at line 115 of file GeomShapeView.h.
fillSubZonePyramid5()
void Arcane::geometric::GeomShapeView::fillSubZonePyramid5 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Pyramid5
Definition at line 290 of file GeomShapeView.cc.
References center(), edge(), face(), Arcane::geometric::Hexaedron8ElementView::init(), and node().
fillSubZoneQuad()
void Arcane::geometric::GeomShapeView::fillSubZoneQuad (Quad4ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneQuad4() instead
Definition at line 87 of file GeomShapeView.h.
References fillSubZoneElement().
fillSubZoneQuad4()
void Arcane::geometric::GeomShapeView::fillSubZoneQuad4 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Quad4
Definition at line 181 of file GeomShapeView.cc.
References center(), face(), Arcane::geometric::Quad4ElementView::init(), and node().
fillSubZoneTetra()
void Arcane::geometric::GeomShapeView::fillSubZoneTetra (Hexaedron8ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneTetraedron4() instead
Definition at line 108 of file GeomShapeView.h.
fillSubZoneTetraedron4()
void Arcane::geometric::GeomShapeView::fillSubZoneTetraedron4 (Hexaedron8ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Tetraedron4
Definition at line 352 of file GeomShapeView.cc.
References center(), edge(), face(), Arcane::geometric::Hexaedron8ElementView::init(), and node().
fillSubZoneTriangle()
void Arcane::geometric::GeomShapeView::fillSubZoneTriangle (Quad4ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneTriangle3() instead
Definition at line 80 of file GeomShapeView.h.
fillSubZoneTriangle3()
void Arcane::geometric::GeomShapeView::fillSubZoneTriangle3 (Quad4ElementView svc, Integer i)
Fills svc with the information of the i-th control sub-volume.
Precondition
type()==GeomType::Triangle3
Definition at line 203 of file GeomShapeView.cc.
References center(), face(), Arcane::geometric::Quad4ElementView::init(), and node().
fillSubZoneWedge7()
void Arcane::geometric::GeomShapeView::fillSubZoneWedge7 (Hexaedron8ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneHeptaedron10() instead
Definition at line 136 of file GeomShapeView.h.
fillSubZoneWedge8()
void Arcane::geometric::GeomShapeView::fillSubZoneWedge8 (Hexaedron8ElementView svc, Integer i) inline
Fills svc with the information of the i-th control sub-volume.
Deprecated
Use fillSubZoneOctaedron12() instead
Definition at line 143 of file GeomShapeView.h.
geomType()
GeomType Arcane::geometric::GeomShapeView::geomType () const inline
Geometric type of the shape.
If the shape is associated with an entity (retrievable via item()), it is also the type of the entity.
Returns GeomType::NullType if the instance is not initialized.
Definition at line 234 of file GeomShapeView.h.
Referenced by toHeptaedron10Element(), toHexaedron8Element(), toHexagon6Element(), toOctaedron12Element(), toPentaedron6Element(), toPentagon5Element(), toPyramid5Element(), toQuad4Element(), toTetraedron4Element(), and toTriangle3Element().
initFromHexa()
void Arcane::geometric::GeomShapeView::initFromHexa (HexaElementConstView hexa, GeomShape & geom_cell)
Deprecated
Use GeomShape::initFromHexaedron8() instead.
Definition at line 139 of file GeomShapeView.cc.
References Arcane::geometric::GeomShapeStdBuilder::computeNodePositionFromHexa(), and Arcane::geometric::GeomShape::toMutableView().
Referenced by fillSubZonePentagon().
initFromQuad()
void Arcane::geometric::GeomShapeView::initFromQuad (QuadElementConstView hexa, GeomShape & geom_cell)
Deprecated
Use GeomShape::initFromQuad4() instead.
Definition at line 153 of file GeomShapeView.cc.
References Arcane::geometric::GeomShapeStdBuilder::computeNodePositionFromQuad(), and Arcane::geometric::GeomShape::toMutableView().
Referenced by fillSubZoneHexagon().
initializeConnectivity()
void Arcane::geometric::GeomShapeView::initializeConnectivity () static
Definition at line 79 of file GeomShapeView.cc.
item()
Item Arcane::geometric::GeomShapeView::item () const inline
Associated entity (null if none).
Definition at line 137 of file GeomShapeView.h.
nbSubZone()
Integer Arcane::geometric::GeomShapeView::nbSubZone () const inline
Number of sub-control volumes.
Definition at line 192 of file GeomShapeView.h.
Referenced by Arcane::geometric::Tetraedron4ShapeView::elemView().
nbSvcFace()
Integer Arcane::geometric::GeomShapeView::nbSvcFace () const inline
Number of internal SVC faces.
Definition at line 198 of file GeomShapeView.h.
node()
const Real3 Arcane::geometric::GeomShapeView::node (Integer i) const inline
Position of the i-th node of the shape.
Definition at line 112 of file GeomShapeView.h.
Referenced by edge(), fillSubZoneElement(), fillSubZoneElement(), fillSubZoneHeptaedron10(), fillSubZoneHexaedron8(), fillSubZoneOctaedron12(), fillSubZonePentaedron6(), fillSubZonePyramid5(), fillSubZoneQuad4(), fillSubZoneTetraedron4(), and fillSubZoneTriangle3().
nodeAssociation()
Integer Arcane::geometric::GeomShapeView::nodeAssociation (Integer i) const inline
Local number of the vertex associated with the sub-control volume.
Definition at line 204 of file GeomShapeView.h.
Referenced by fillSubZoneElement(), and fillSubZoneElement().
nodeConnectic()
const NodeConnectic & Arcane::geometric::GeomShapeView::nodeConnectic (Integer i) const inline
Node connectivity information.
Definition at line 174 of file GeomShapeView.h.
Referenced by fillSubZoneElement(), and fillSubZoneElement().
svcFaceConnectic()
const SVCFaceConnectic & Arcane::geometric::GeomShapeView::svcFaceConnectic (Integer i) const inline
Definition at line 209 of file GeomShapeView.h.
toHeptaedron10Element()
Heptaedron10ElementConstView Arcane::geometric::GeomShapeView::toHeptaedron10Element () const inline
Returns a specific view to a geometric element of type GeomType::Heptaedron10.
Precondition
type()==GeomType::Heptaedron10
Definition at line 499 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Heptaedron10.
toHeptaedron10Shape()
Heptaedron10ShapeView Arcane::geometric::GeomShapeView::toHeptaedron10Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Heptaedron10.
Precondition
type()==GeomType::Heptaedron10
Definition at line 432 of file GeneratedGeomShapeView.h.
toHexaedron8Element()
Hexaedron8ElementConstView Arcane::geometric::GeomShapeView::toHexaedron8Element () const inline
Returns a specific view to a geometric element of type GeomType::Hexaedron8.
Precondition
type()==GeomType::Hexaedron8
Definition at line 493 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Hexaedron8.
toHexaedron8Shape()
Hexaedron8ShapeView Arcane::geometric::GeomShapeView::toHexaedron8Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Hexaedron8.
Precondition
type()==GeomType::Hexaedron8
Definition at line 427 of file GeneratedGeomShapeView.h.
toHexagon6Element()
Hexagon6ElementConstView Arcane::geometric::GeomShapeView::toHexagon6Element () const inline
Returns a specific view to a geometric element of type GeomType::Hexagon6.
Precondition
type()==GeomType::Hexagon6
Definition at line 469 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Hexagon6.
toHexagon6Shape()
Hexagon6ShapeView Arcane::geometric::GeomShapeView::toHexagon6Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Hexagon6.
Precondition
type()==GeomType::Hexagon6
Definition at line 407 of file GeneratedGeomShapeView.h.
toOctaedron12Element()
Octaedron12ElementConstView Arcane::geometric::GeomShapeView::toOctaedron12Element () const inline
Returns a specific view to a geometric element of type GeomType::Octaedron12.
Precondition
type()==GeomType::Octaedron12
Definition at line 505 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Octaedron12.
toOctaedron12Shape()
Octaedron12ShapeView Arcane::geometric::GeomShapeView::toOctaedron12Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Octaedron12.
Precondition
type()==GeomType::Octaedron12
Definition at line 437 of file GeneratedGeomShapeView.h.
toPentaedron6Element()
Pentaedron6ElementConstView Arcane::geometric::GeomShapeView::toPentaedron6Element () const inline
Returns a specific view to a geometric element of type GeomType::Pentaedron6.
Precondition
type()==GeomType::Pentaedron6
Definition at line 487 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Pentaedron6.
toPentaedron6Shape()
Pentaedron6ShapeView Arcane::geometric::GeomShapeView::toPentaedron6Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Pentaedron6.
Precondition
type()==GeomType::Pentaedron6
Definition at line 422 of file GeneratedGeomShapeView.h.
toPentagon5Element()
Pentagon5ElementConstView Arcane::geometric::GeomShapeView::toPentagon5Element () const inline
Returns a specific view to a geometric element of type GeomType::Pentagon5.
Precondition
type()==GeomType::Pentagon5
Definition at line 463 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Pentagon5.
toPentagon5Shape()
Pentagon5ShapeView Arcane::geometric::GeomShapeView::toPentagon5Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Pentagon5.
Precondition
type()==GeomType::Pentagon5
Definition at line 402 of file GeneratedGeomShapeView.h.
toPyramid5Element()
Pyramid5ElementConstView Arcane::geometric::GeomShapeView::toPyramid5Element () const inline
Returns a specific view to a geometric element of type GeomType::Pyramid5.
Precondition
type()==GeomType::Pyramid5
Definition at line 481 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Pyramid5.
toPyramid5Shape()
Pyramid5ShapeView Arcane::geometric::GeomShapeView::toPyramid5Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Pyramid5.
Precondition
type()==GeomType::Pyramid5
Definition at line 417 of file GeneratedGeomShapeView.h.
toQuad4Element()
Quad4ElementConstView Arcane::geometric::GeomShapeView::toQuad4Element () const inline
Returns a specific view to a geometric element of type GeomType::Quad4.
Precondition
type()==GeomType::Quad4
Definition at line 457 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Quad4.
toQuad4Shape()
Quad4ShapeView Arcane::geometric::GeomShapeView::toQuad4Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Quad4.
Precondition
type()==GeomType::Quad4
Definition at line 397 of file GeneratedGeomShapeView.h.
toTetraedron4Element()
Tetraedron4ElementConstView Arcane::geometric::GeomShapeView::toTetraedron4Element () const inline
Returns a specific view to a geometric element of type GeomType::Tetraedron4.
Precondition
type()==GeomType::Tetraedron4
Definition at line 475 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Tetraedron4.
toTetraedron4Shape()
Tetraedron4ShapeView Arcane::geometric::GeomShapeView::toTetraedron4Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Tetraedron4.
Precondition
type()==GeomType::Tetraedron4
Definition at line 412 of file GeneratedGeomShapeView.h.
toTriangle3Element()
Triangle3ElementConstView Arcane::geometric::GeomShapeView::toTriangle3Element () const inline
Returns a specific view to a geometric element of type GeomType::Triangle3.
Precondition
type()==GeomType::Triangle3
Definition at line 451 of file GeneratedGeomShapeView.h.
References geomType(), and Arcane::geometric::GeomType::Triangle3.
toTriangle3Shape()
Triangle3ShapeView Arcane::geometric::GeomShapeView::toTriangle3Shape () const inline
Returns a specific view for a geometric shape of type GeomType::Triangle3.
Precondition
type()==GeomType::Triangle3
Definition at line 392 of file GeneratedGeomShapeView.h.
Friends And Related Symbol Documentation
GeomShape
friend class GeomShape friend
Definition at line 62 of file GeomShapeView.h.
GeomShapeConnectivity
friend class GeomShapeConnectivity friend
Definition at line 63 of file GeomShapeView.h.
GeomShapeMng
friend class GeomShapeMng friend
Definition at line 61 of file GeomShapeView.h.
The documentation for this class was generated from the following files:
GeomShapeView.h
GeneratedGeomShapeView.h
GeomShapeView.cc