Arcane: Arcane::geometric::GeomElementBase< NbNode > Class Template Reference
Arcane::geometric::GeomElementBase< NbNode > Class Template Reference
Geometric elements.
Base class for geometric elements.
#include <arcane/geometry/GeomElement.h>
Public Member Functions
GeomElementBase ()
Empty constructor.
GeomElementBase (const VariableNodeReal3 &coords, ItemWithNodes item)
Constructor from the coordinates coords of the nodes of the entity item.
GeomElementBase (Real3ConstArrayView coords)
Constructor from the coordinates coords.
const Real3 s (Integer i) const
Retrieves the value of the i-th node.
const Real3 operator[] (Integer i) const
Retrieves the value of the i-th node.
void setItem (Integer i, const Real3 &v)
Positions the value of the i-th node at v.
void setItem (Integer i, Real x, Real y, Real z)
Positions the value of the i-th node at Real3(x,y,z).
void fillView (Real3ArrayView view) const
Fills the view view with the coordinates of the instance.
void init (const VariableNodeReal3 &coords, ItemWithNodes item)
Initializes the coordinates with those of the nodes of the entity item.
Protected Attributes
Real3POD m_s [NbNode]
Detailed Description
template<int NbNode>
class Arcane::geometric::GeomElementBase< NbNode >
Base class for geometric elements.
A geometric element contains the coordinates of the NbNode nodes that compose this element.
For performance reasons, the default constructor does not initialize the coordinates.
To retrieve the coordinates of the i-th node of the geometric element, simply use the [] operator. Modification is done via setItem().
Definition at line 44 of file GeomElement.h.
Constructor & Destructor Documentation
GeomElementBase() [1/3]
template<int NbNode> Arcane::geometric::GeomElementBase< NbNode >::GeomElementBase () inline
Empty constructor.
Definition at line 49 of file GeomElement.h.
Referenced by Arcane::geometric::Triangle3Element::view().
GeomElementBase() [2/3]
template<int NbNode> Arcane::geometric::GeomElementBase< NbNode >::GeomElementBase (const VariableNodeReal3 & coords, ItemWithNodes item) inline
Constructor from the coordinates coords of the nodes of the entity item.
Definition at line 51 of file GeomElement.h.
References init().
GeomElementBase() [3/3]
template<int NbNode> Arcane::geometric::GeomElementBase< NbNode >::GeomElementBase (Real3ConstArrayView coords) inline
Constructor from the coordinates coords.
Definition at line 56 of file GeomElement.h.
References setItem().
Member Function Documentation
fillView()
template<int NbNode> void Arcane::geometric::GeomElementBase< NbNode >::fillView (Real3ArrayView view) const inline
Fills the view view with the coordinates of the instance.
Definition at line 74 of file GeomElement.h.
init()
template<int NbNode> void Arcane::geometric::GeomElementBase< NbNode >::init (const VariableNodeReal3 & coords, ItemWithNodes item) inline
Initializes the coordinates with those of the nodes of the entity item.
Definition at line 83 of file GeomElement.h.
Referenced by GeomElementBase().
operator[]()
template<int NbNode> const Real3 Arcane::geometric::GeomElementBase< NbNode >::operator[] (Integer i) const inline
Retrieves the value of the i-th node.
Definition at line 65 of file GeomElement.h.
s()
template<int NbNode> const Real3 Arcane::geometric::GeomElementBase< NbNode >::s (Integer i) const inline
Retrieves the value of the i-th node.
Definition at line 63 of file GeomElement.h.
setItem() [1/2]
template<int NbNode> void Arcane::geometric::GeomElementBase< NbNode >::setItem (Integer i, const Real3 & v) inline
Positions the value of the i-th node at v.
Definition at line 67 of file GeomElement.h.
Referenced by GeomElementBase().
setItem() [2/2]
template<int NbNode> void Arcane::geometric::GeomElementBase< NbNode >::setItem (Integer i, Real x, Real y, Real z) inline
Positions the value of the i-th node at Real3(x,y,z).
Definition at line 69 of file GeomElement.h.
Member Data Documentation
m_s
template<int NbNode> Real3POD Arcane::geometric::GeomElementBase< NbNode >::m_s[NbNode] protected
Definition at line 91 of file GeomElement.h.
The documentation for this class was generated from the following file:
GeomElement.h