Alien: Alien::RedistributedVector Class Reference
Alien::RedistributedVector Class Reference final
Public Member Functions
RedistributedVector (RedistributedVector &&vector)=delete
RedistributedVector (IVector &vector, Redistributor &redist)
RedistributedVector & operator= (RedistributedVector &&vector)=delete
RedistributedVector (const RedistributedVector &vector)=delete
RedistributedVector & operator= (const RedistributedVector &vector)=delete
void visit (ICopyOnWriteVector &) const
Visit method.
const VectorDistribution & distribution () const
const ISpace & space () const
Get the space associated to the vector.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
MultiVectorImpl * impl ()
Get the multivector implementation.
const MultiVectorImpl * impl () const
Get the multivector implementation.
Private Attributes
std::shared_ptr< MultiVectorImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from Alien::IVector
IVector ()
Constructor.
Detailed Description
Definition at line 35 of file RedistributedVector.h.
Constructor & Destructor Documentation
RedistributedVector()
Alien::RedistributedVector::RedistributedVector (IVector & vector, Redistributor & redist)
Definition at line 35 of file RedistributedVector.cc.
~RedistributedVector()
Alien::RedistributedVector::~RedistributedVector ()
Definition at line 39 of file RedistributedVector.cc.
Member Function Documentation
distribution()
const VectorDistribution & Alien::RedistributedVector::distribution () const
Definition at line 51 of file RedistributedVector.cc.
hasUserFeature()
bool Alien::RedistributedVector::hasUserFeature (String feature) const
Definition at line 73 of file RedistributedVector.cc.
impl() [1/2]
MultiVectorImpl * Alien::RedistributedVector::impl () virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 81 of file RedistributedVector.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiVectorImpl * Alien::RedistributedVector::impl () const virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 96 of file RedistributedVector.cc.
References impl().
setUserFeature()
void Alien::RedistributedVector::setUserFeature (String feature)
Definition at line 66 of file RedistributedVector.cc.
space()
const ISpace & Alien::RedistributedVector::space () const virtual
Get the space associated to the vector.
Returns
The space
Implements Alien::IVector.
Definition at line 59 of file RedistributedVector.cc.
References space().
Referenced by space().
visit()
void Alien::RedistributedVector::visit (ICopyOnWriteVector &) const virtual
Visit method.
Implements Alien::IVector.
Definition at line 43 of file RedistributedVector.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiVectorImpl> Alien::RedistributedVector::m_impl private
Definition at line 67 of file RedistributedVector.h.
The documentation for this class was generated from the following files:
RedistributedVector.h
RedistributedVector.cc