Arcane: Arcane::mesh::CommonItemGroupFilterer Class Reference
Arcane::mesh::CommonItemGroupFilterer Class Reference
Utility class for common groups across all parts of a mesh.
#include <arcane/mesh/CommonItemGroupFilterer.h>
Public Member Functions
CommonItemGroupFilterer (IItemFamily *family)
CommonItemGroupFilterer (const CommonItemGroupFilterer &rhs)=delete
CommonItemGroupFilterer & operator= (const CommonItemGroupFilterer &rhs)=delete
void addGroupToFilter (const ItemGroup &group)
void applyFiltering ()
Filters the common groups.
ItemGroupCollection sortedCommonGroups ()
List of common groups sorted alphabetically.
Private Attributes
IItemFamily * m_family
List< ItemGroup > m_input_groups
List< ItemGroup > m_sorted_common_groups
Detailed Description
Utility class for common groups across all parts of a mesh.
To use this class, you must add the groups you wish to filter via addGroupToFilter(). You must then call the applyFiltering() method to perform the filtering.
Definition at line 36 of file CommonItemGroupFilterer.h.
Constructor & Destructor Documentation
CommonItemGroupFilterer()
Arcane::mesh::CommonItemGroupFilterer::CommonItemGroupFilterer (IItemFamily * family) explicit
Definition at line 34 of file CommonItemGroupFilterer.cc.
Member Function Documentation
addGroupToFilter()
void Arcane::mesh::CommonItemGroupFilterer::addGroupToFilter (const ItemGroup & group)
Definition at line 43 of file CommonItemGroupFilterer.cc.
applyFiltering()
void Arcane::mesh::CommonItemGroupFilterer::applyFiltering ()
Filters the common groups.
If there are groups that are not common to all ranks, an exception is raised.
Definition at line 52 of file CommonItemGroupFilterer.cc.
References Arcane::Array< T >::add(), Arcane::IParallelMng::allGather(), Arcane::BasicSerializer::allocateBuffer(), ARCANE_FATAL, Arcane::IParallelMng::commSize(), Arcane::AbstractArray< T >::empty(), Arcane::ItemGroup::fullName(), Arcane::BasicSerializer::get(), Arcane::BasicSerializer::getInteger(), Arcane::ITraceMng::info(), Arcane::ISerializer::ModeGet, Arcane::ISerializer::ModePut, Arcane::BasicSerializer::put(), Arcane::BasicSerializer::putInteger(), Arcane::BasicSerializer::reserve(), Arcane::BasicSerializer::setMode(), and Arcane::AbstractArray< T >::size().
Referenced by Arcane::mesh::ItemGroupsSynchronize::synchronize().
sortedCommonGroups()
ItemGroupCollection Arcane::mesh::CommonItemGroupFilterer::sortedCommonGroups () inline
List of common groups sorted alphabetically.
Definition at line 59 of file CommonItemGroupFilterer.h.
Member Data Documentation
m_family
IItemFamily* Arcane::mesh::CommonItemGroupFilterer::m_family private
Definition at line 63 of file CommonItemGroupFilterer.h.
m_input_groups
List<ItemGroup> Arcane::mesh::CommonItemGroupFilterer::m_input_groups private
Definition at line 64 of file CommonItemGroupFilterer.h.
m_sorted_common_groups
List<ItemGroup> Arcane::mesh::CommonItemGroupFilterer::m_sorted_common_groups private
Definition at line 65 of file CommonItemGroupFilterer.h.
The documentation for this class was generated from the following files:
CommonItemGroupFilterer.h
CommonItemGroupFilterer.cc