Arcane: Arcane::mesh::CommonFaceFinder Class Reference
Arcane::mesh::CommonFaceFinder Class Reference
Finds the common face between two cells.
Public Types
typedef std::set< Integer > NodesLIDSet
Public Member Functions
const NodesLIDSet & nodesLID () const
Set of localIds of common nodes.
Integer cell1LocalNumber () const
Integer cell2LocalNumber () const
CommonFaceFinder (Cell i_cell_1, Cell i_cell_2)
Private Attributes
Integer m_cell_1_local_number
Number of the common face in cell 1.
Integer m_cell_2_local_number
Number of the common face in cell 2.
NodesLIDSet m_nodes_lid_set
Detailed Description
Finds the common face between two cells.
This utility class aims to determine the common face between two cells. If the two cells are not joined by a face, an error is generated.
Definition at line 142 of file CellMerger.cc.
Member Typedef Documentation
NodesLIDSet
typedef std::set<Integer> Arcane::mesh::CommonFaceFinder::NodesLIDSet
Definition at line 146 of file CellMerger.cc.
Constructor & Destructor Documentation
CommonFaceFinder()
Arcane::mesh::CommonFaceFinder::CommonFaceFinder (Cell i_cell_1, Cell i_cell_2)
Constructor. All data structures are generated upon calling the constructor
Parameters
i_cell_1 the 1st cell
i_cell_2 the 2nd cell
Definition at line 202 of file CellMerger.cc.
References ARCANE_FATAL, Arcane::Cell::face(), Arcane::Cell::faces(), m_cell_1_local_number, m_cell_2_local_number, and Arcane::ItemWithNodes::nodes().
~CommonFaceFinder()
Arcane::mesh::CommonFaceFinder::~CommonFaceFinder () inline
Definition at line 196 of file CellMerger.cc.
Member Function Documentation
cell1LocalNumber()
Integer Arcane::mesh::CommonFaceFinder::cell1LocalNumber () const inline
Read access to the local number of the common face in cell 1
Returns
m_cell_1_local_number
Definition at line 173 of file CellMerger.cc.
References m_cell_1_local_number.
Referenced by Arcane::mesh::CellToHexahedronMerger::CellToHexahedronMerger(), Arcane::mesh::CellToQuadrilateralMerger::CellToQuadrilateralMerger(), Arcane::mesh::Faces2DToMergeFinder::Faces2DToMergeFinder(), and Arcane::mesh::FacesToMergeFinder::FacesToMergeFinder().
cell2LocalNumber()
Integer Arcane::mesh::CommonFaceFinder::cell2LocalNumber () const inline
Read access to the local number of the common face in cell 2
Returns
m_cell_2_local_number
Definition at line 184 of file CellMerger.cc.
References m_cell_2_local_number.
Referenced by Arcane::mesh::CellToHexahedronMerger::CellToHexahedronMerger(), Arcane::mesh::CellToQuadrilateralMerger::CellToQuadrilateralMerger(), Arcane::mesh::Faces2DToMergeFinder::Faces2DToMergeFinder(), and Arcane::mesh::FacesToMergeFinder::FacesToMergeFinder().
nodesLID()
const NodesLIDSet & Arcane::mesh::CommonFaceFinder::nodesLID () const inline
Set of localIds of common nodes.
Read access to the list of common node localIds
Returns
m_nodes_lid_set
Definition at line 162 of file CellMerger.cc.
Referenced by Arcane::mesh::Faces2DToMergeFinder::Faces2DToMergeFinder(), and Arcane::mesh::FacesToMergeFinder::FacesToMergeFinder().
Member Data Documentation
m_cell_1_local_number
Integer Arcane::mesh::CommonFaceFinder::m_cell_1_local_number private
Number of the common face in cell 1.
Definition at line 150 of file CellMerger.cc.
Referenced by cell1LocalNumber(), and CommonFaceFinder().
m_cell_2_local_number
Integer Arcane::mesh::CommonFaceFinder::m_cell_2_local_number private
Number of the common face in cell 2.
Definition at line 151 of file CellMerger.cc.
Referenced by cell2LocalNumber(), and CommonFaceFinder().
m_nodes_lid_set
NodesLIDSet Arcane::mesh::CommonFaceFinder::m_nodes_lid_set private
Definition at line 153 of file CellMerger.cc.
The documentation for this class was generated from the following file:
CellMerger.cc