Arcane: Arcane::Materials::ComponentPartItemVectorView Class Reference
Arcane::Materials::ComponentPartItemVectorView Class Reference
Materials and Media.
View over pure or partial entities of a component.
#include <arcane/core/materials/ComponentPartItemVectorView.h>
Public Member Functions
ComponentPartItemVectorView ()=default
Constructs an uninitialized view.
Integer nbItem () const
Number of entities in the view.
IMeshComponent * component () const
Associated component.
Int32 componentPartIndex () const
Int32ConstArrayView valueIndexes () const
List of valueIndex() of the part.
Int32ConstArrayView itemIndexes () const
List of indices into itemsInternal() of the entities.
eMatPart part () const
Part of the component.
Protected Member Functions
ComponentPartItemVectorView (IMeshComponent *component, Int32 component_part_index, Int32ConstArrayView value_indexes, Int32ConstArrayView item_indexes, const ConstituentItemLocalIdListView &constituent_list_view, eMatPart part)
Constructs a view over a part of the component entities component.
const ConstituentItemLocalIdListView & constituentItemListView () const
Internal list of constituent items.
Private Attributes
IMeshComponent * m_component = nullptr
Constituent manager.
Int32 m_component_part_index = -1
Constituent index for accessing partial values.
Int32ConstArrayView m_value_indexes
List of valueIndex() of the part.
Int32ConstArrayView m_item_indexes
List of indices into m_items_internal for each material cell.
ConstituentItemLocalIdListView m_constituent_list_view
List of ComponentItemInternal* for this constituent.
eMatPart m_part = eMatPart::Pure
Part of the constituent.
Friends
class MeshComponentPartData
class ComponentPartCellEnumerator
Detailed Description
View over pure or partial entities of a component.
Definition at line 35 of file core/materials/ComponentPartItemVectorView.h.
Constructor & Destructor Documentation
ComponentPartItemVectorView()
Arcane::Materials::ComponentPartItemVectorView::ComponentPartItemVectorView (IMeshComponent * component, Int32 component_part_index, Int32ConstArrayView value_indexes, Int32ConstArrayView item_indexes, const ConstituentItemLocalIdListView & constituent_list_view, eMatPart part) inline protected
Constructs a view over a part of the component entities component.
This constructor is generally not called directly. To construct such a view, it is preferable to use the methods IMeshComponent::pureItems(), IMeshComponent::impureItems() or IMeshComponent::partItems().
Definition at line 50 of file core/materials/ComponentPartItemVectorView.h.
References component(), m_component, m_component_part_index, m_constituent_list_view, m_item_indexes, m_part, m_value_indexes, and part().
Referenced by Arcane::Materials::ComponentImpurePartItemVectorView::ComponentImpurePartItemVectorView(), Arcane::Materials::ComponentPurePartItemVectorView::ComponentPurePartItemVectorView(), Arcane::Materials::EnvPartItemVectorView::EnvPartItemVectorView(), and Arcane::Materials::MatPartItemVectorView::MatPartItemVectorView().
Member Function Documentation
component()
IMeshComponent * Arcane::Materials::ComponentPartItemVectorView::component () const inline
Associated component.
Definition at line 75 of file core/materials/ComponentPartItemVectorView.h.
References m_component.
Referenced by Arcane::Materials::ComponentImpurePartItemVectorView::ComponentImpurePartItemVectorView(), ComponentPartItemVectorView(), and Arcane::Materials::ComponentPurePartItemVectorView::ComponentPurePartItemVectorView().
componentPartIndex()
Int32 Arcane::Materials::ComponentPartItemVectorView::componentPartIndex () const inline
Definition at line 78 of file core/materials/ComponentPartItemVectorView.h.
constituentItemListView()
const ConstituentItemLocalIdListView & Arcane::Materials::ComponentPartItemVectorView::constituentItemListView () const inline protected
Internal list of constituent items.
Definition at line 92 of file core/materials/ComponentPartItemVectorView.h.
References m_constituent_list_view.
itemIndexes()
Int32ConstArrayView Arcane::Materials::ComponentPartItemVectorView::itemIndexes () const inline
List of indices into itemsInternal() of the entities.
Definition at line 84 of file core/materials/ComponentPartItemVectorView.h.
References m_item_indexes.
nbItem()
Integer Arcane::Materials::ComponentPartItemVectorView::nbItem () const inline
Number of entities in the view.
Definition at line 72 of file core/materials/ComponentPartItemVectorView.h.
References m_value_indexes.
part()
eMatPart Arcane::Materials::ComponentPartItemVectorView::part () const inline
Part of the component.
Definition at line 87 of file core/materials/ComponentPartItemVectorView.h.
References m_part.
Referenced by ComponentPartItemVectorView().
valueIndexes()
Int32ConstArrayView Arcane::Materials::ComponentPartItemVectorView::valueIndexes () const inline
List of valueIndex() of the part.
Definition at line 81 of file core/materials/ComponentPartItemVectorView.h.
References m_value_indexes.
Friends And Related Symbol Documentation
ComponentPartCellEnumerator
friend class ComponentPartCellEnumerator friend
Definition at line 38 of file core/materials/ComponentPartItemVectorView.h.
MeshComponentPartData
friend class MeshComponentPartData friend
Definition at line 37 of file core/materials/ComponentPartItemVectorView.h.
Member Data Documentation
m_component
IMeshComponent* Arcane::Materials::ComponentPartItemVectorView::m_component = nullptr private
Constituent manager.
Definition at line 97 of file core/materials/ComponentPartItemVectorView.h.
Referenced by component(), and ComponentPartItemVectorView().
m_component_part_index
Int32 Arcane::Materials::ComponentPartItemVectorView::m_component_part_index = -1 private
Constituent index for accessing partial values.
Definition at line 100 of file core/materials/ComponentPartItemVectorView.h.
Referenced by ComponentPartItemVectorView().
m_constituent_list_view
ConstituentItemLocalIdListView Arcane::Materials::ComponentPartItemVectorView::m_constituent_list_view private
List of ComponentItemInternal* for this constituent.
Definition at line 109 of file core/materials/ComponentPartItemVectorView.h.
Referenced by ComponentPartItemVectorView(), and constituentItemListView().
m_item_indexes
Int32ConstArrayView Arcane::Materials::ComponentPartItemVectorView::m_item_indexes private
List of indices into m_items_internal for each material cell.
Definition at line 106 of file core/materials/ComponentPartItemVectorView.h.
Referenced by ComponentPartItemVectorView(), and itemIndexes().
m_part
eMatPart Arcane::Materials::ComponentPartItemVectorView::m_part = eMatPart::Pure private
Part of the constituent.
Definition at line 112 of file core/materials/ComponentPartItemVectorView.h.
Referenced by ComponentPartItemVectorView(), and part().
m_value_indexes
Int32ConstArrayView Arcane::Materials::ComponentPartItemVectorView::m_value_indexes private
List of valueIndex() of the part.
Definition at line 103 of file core/materials/ComponentPartItemVectorView.h.
Referenced by ComponentPartItemVectorView(), nbItem(), and valueIndexes().
The documentation for this class was generated from the following file:
core/materials/ComponentPartItemVectorView.h