Alien: Internal data structure access.
Internal data structure access.
Matrix Constructor » Block related API » Space related functions. » Protection functions. » Algebraic properties management.
Classes
class Alien::IMatrixImpl
Interface to handle abstract matrices implementation.
class Alien::IVectorImpl
Interface to handle abstract vectors implementation.
class Alien::MultiMatrixImpl
Multi matrices representation container.
Functions
Alien::MultiVectorImpl::MultiVectorImpl ()
Multi vectors representation container.
MultiMatrixImpl * Alien::Move::MatrixData::impl ()
Get the multimatrix implementation.
const MultiMatrixImpl * Alien::Move::MatrixData::impl () const
Get the multimatrix implementation.
MultiVectorImpl * Alien::Move::VectorData::impl ()
Get the multivector implementation.
const MultiVectorImpl * Alien::Move::VectorData::impl () const
Get the multivector implementation.
Variables
std::shared_ptr< MultiMatrixImpl > Alien::Move::MatrixData::m_impl
std::shared_ptr< MultiVectorImpl > Alien::Move::VectorData::m_impl
Friends
MatrixData Alien::Move::MatrixData::createMatrixData (std::shared_ptr< MultiMatrixImpl > multi)
VectorData Alien::Move::VectorData::createVectorData (std::shared_ptr< MultiVectorImpl > multi)
Detailed Description
Access multi-representation object.
}@
Access multi-representation object.
Function Documentation
impl() [1/4]
MultiMatrixImpl * Alien::Move::MatrixData::impl () virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 212 of file MatrixData.cc.
References Alien::MultiMatrixImpl::get().
impl() [2/4]
const MultiMatrixImpl * Alien::Move::MatrixData::impl () const virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 224 of file MatrixData.cc.
References Alien::MultiMatrixImpl::get().
impl() [3/4]
MultiVectorImpl * Alien::Move::VectorData::impl () virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 186 of file VectorData.cc.
References Alien::MultiVectorImpl::get().
Referenced by clear(), free(), hasUserFeature(), operator=(), setUserFeature(), and space().
impl() [4/4]
const MultiVectorImpl * Alien::Move::VectorData::impl () const virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 201 of file VectorData.cc.
References Alien::MultiVectorImpl::get().
MultiVectorImpl()
Alien::MultiVectorImpl::MultiVectorImpl ()
Multi vectors representation container.
This class allows to store and access several implementations of the same vector. It also stores all shared information between those implementation such as distribution, or block information. It provided two accessors, one to access the vector in read-only, that do not increase the timestamp and one in read-write mode, that can increase the timestamp. The former implementation might therefore become the up to date vector.
While requesting a vector in a specific format, if the up to date vector is not in that specific format, the up to vector matrix will be converted, provided a converter exists. Default constructor
Definition at line 39 of file MultiVectorImpl.cc.
References m_block, and m_variable_block.
Referenced by clone(), and MultiVectorImpl().
Variable Documentation
m_impl [1/2]
std::shared_ptr<MultiMatrixImpl> Alien::Move::MatrixData::m_impl private
Definition at line 230 of file MatrixData.h.
m_impl [2/2]
std::shared_ptr<MultiVectorImpl> Alien::Move::VectorData::m_impl private
Definition at line 192 of file VectorData.h.
Friends
createMatrixData
MatrixData createMatrixData (std::shared_ptr< MultiMatrixImpl > multi) friend
} @
Definition at line 239 of file MatrixData.cc.
References createMatrixData, and MatrixData().
Referenced by createMatrixData.
createVectorData
VectorData createVectorData (std::shared_ptr< MultiVectorImpl > multi) friend
}@
Definition at line 216 of file VectorData.cc.
References createVectorData, and VectorData().
Referenced by createVectorData, and operator=().