Arcane: Arcane::ItemTypeInfo Class Reference
Arcane::ItemTypeInfo Class Reference
Mesh
Info on a mesh entity type.
#include <arcane/core/ItemTypeInfo.h>
Classes
class LocalFace
Local information about a cell face.
class LocalEdge
Local information about a cell edge.
Public Member Functions
Int16 typeId () const
Type number.
ItemTypeId itemTypeId () const
Type number.
Integer nbLocalNode () const
Number of nodes of the entity.
Integer nbLocalFace () const
Number of faces of the entity.
Integer nbLocalEdge () const
Number of edges of the entity.
String typeName () const
Type name.
Int16 dimension () const
Dimension of the element (<0 if unknown).
bool isValidForCell () const
Indicates if the type is valid for creating a cell.
Int32 order () const
Order of the type.
Int16 linearTypeId () const
Type of the corresponding linear element.
ItemTypeId linearItemTypeId () const
Type of the corresponding linear element.
const ItemTypeInfo * linearTypeInfo () const
Type of the corresponding linear element.
bool hasCenterNode () const
Indicates if the type has a center node.
bool isPolygon () const
Indicates if the type is a polygon.
LocalEdge localEdge (Integer id) const
Local connectivity of the i-th edge of the cell.
LocalFace localFace (Integer id) const
Local connectivity of the i-th face of the cell.
Protected Member Functions
ItemTypeInfo ()=default
Default constructor.
Protected Attributes
ItemTypeMng * m_mng = nullptr
ItemTypeId m_type_id { IT_NullType }
ItemTypeId m_linear_type_id { IT_NullType }
Int16 m_dimension = (-1)
Dimension (-1) if not initialized.
bool m_is_valid_for_cell = true
Indicates if the type is valid for a cell.
bool m_has_center_node = false
Indicates if the type has a center node (for faces or cells).
bool m_is_polygon = false
Indicates if the type is a polygon.
Integer m_nb_node = 0
Integer m_nb_edge = 0
Integer m_nb_face = 0
Int32 m_order = 1
Integer m_first_item_index = 0
Index of this type in the list of indices of m_mng.
String m_type_name
Detailed Description
Info on a mesh entity type.
An instance of this class describes a mesh entity type, such as a hexahedral cell, a quadrilateral cell.
See also
ItemTypeMng
There should only be one instance per entity type. Creation of a type is done by the derived class ItemTypeInfoBuilder. Types must be created before any mesh creation (i.e. during the initialization of the architecture).
Definition at line 45 of file ItemTypeInfo.h.
Member Function Documentation
dimension()
Int16 Arcane::ItemTypeInfo::dimension () const inline
Dimension of the element (<0 if unknown).
Definition at line 128 of file ItemTypeInfo.h.
References m_dimension.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), Arcane::VtkMeshIOService::_readUnstructuredGrid(), Arcane::ItemTypeInfoBuilder::setInfos(), Arcane::ItemTypeInfoBuilder::setInfos(), and Arcane::ItemTypeInfoBuilder::setInfos().
hasCenterNode()
bool Arcane::ItemTypeInfo::hasCenterNode () const inline
Indicates if the type has a center node.
Definition at line 140 of file ItemTypeInfo.h.
References m_has_center_node.
isPolygon()
bool Arcane::ItemTypeInfo::isPolygon () const inline
Indicates if the type is a polygon.
A polygon is a 2D element of order 1 containing at least 5 nodes.
Definition at line 146 of file ItemTypeInfo.h.
References m_is_polygon.
Referenced by Arcane::VtkLegacyMeshWriter::_writeMeshToFile().
isValidForCell()
bool Arcane::ItemTypeInfo::isValidForCell () const inline
Indicates if the type is valid for creating a cell.
Definition at line 130 of file ItemTypeInfo.h.
References m_is_valid_for_cell.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell().
itemTypeId()
ItemTypeId Arcane::ItemTypeInfo::itemTypeId () const inline
Type number.
Definition at line 118 of file ItemTypeInfo.h.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), and Arcane::MshParallelMeshReader::_readElementsFromFile().
linearItemTypeId()
ItemTypeId Arcane::ItemTypeInfo::linearItemTypeId () const inline
Type of the corresponding linear element.
Definition at line 136 of file ItemTypeInfo.h.
linearTypeId()
Int16 Arcane::ItemTypeInfo::linearTypeId () const inline
Type of the corresponding linear element.
Definition at line 134 of file ItemTypeInfo.h.
linearTypeInfo()
const ItemTypeInfo * Arcane::ItemTypeInfo::linearTypeInfo () const inline
Type of the corresponding linear element.
Definition at line 138 of file ItemTypeInfo.h.
References ItemTypeInfo().
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell().
localEdge()
LocalEdge Arcane::ItemTypeInfo::localEdge (Integer id) const inline
Local connectivity of the i-th edge of the cell.
Definition at line 151 of file ItemTypeInfo.h.
References m_first_item_index.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), Arcane::MeshUtils::computeBoundaryNodeNodeViaEdgeConnectivity(), Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), and Arcane::MeshUtils::computeNodeNodeViaEdgeConnectivity().
localFace()
LocalFace Arcane::ItemTypeInfo::localFace (Integer id) const inline
Local connectivity of the i-th face of the cell.
Definition at line 159 of file ItemTypeInfo.h.
References m_first_item_index.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), Arcane::CartesianMeshCoarsening2::_createCoarseCells2D(), Arcane::CartesianMeshCoarsening2::_createCoarseCells3D(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::DumpWEnsight7::_saveGroup(), Arcane::FaceReorienter::checkAndChangeOrientation(), Arcane::FaceReorienter::checkAndChangeOrientationAMR(), Arcane::CartesianMeshCoarsening::createCoarseCells(), and Arcane::ItemTypeMng::printTypes().
nbLocalEdge()
Integer Arcane::ItemTypeInfo::nbLocalEdge () const inline
Number of edges of the entity.
Definition at line 124 of file ItemTypeInfo.h.
Referenced by Arcane::VoronoiMeshIOService::_readCellsHybridGrid(), Arcane::MeshUtils::computeBoundaryNodeNodeViaEdgeConnectivity(), Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), Arcane::MeshUtils::computeNodeNodeViaEdgeConnectivity(), and Arcane::mesh::FullCellInfo::memoryUsed().
nbLocalFace()
Integer Arcane::ItemTypeInfo::nbLocalFace () const inline
Number of faces of the entity.
Definition at line 122 of file ItemTypeInfo.h.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::VoronoiMeshIOService::_readCellsHybridGrid(), Arcane::DumpWEnsight7::_saveGroup(), Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), Arcane::mesh::FullCellInfo::memoryUsed(), and Arcane::ItemTypeMng::printTypes().
nbLocalNode()
Integer Arcane::ItemTypeInfo::nbLocalNode () const inline
Number of nodes of the entity.
Definition at line 120 of file ItemTypeInfo.h.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV2(), Arcane::mesh::DynamicMeshIncrementalBuilder::_fillFaceInfo(), Arcane::VoronoiMeshIOService::_readCellsHybridGrid(), Arcane::MshParallelMeshReader::_readElementsFromFile(), Arcane::LimaMalippReaderT< ReaderWrapper >::_readMeshPart(), Arcane::MshMeshWriter::_writeElements(), Arcane::mesh::DynamicMeshIncrementalBuilder::addCells(), Arcane::mesh::DynamicMeshIncrementalBuilder::addFaces(), Arcane::mesh::DynamicMeshIncrementalBuilder::addHChildrenCells(), Arcane::UnstructuredMeshUtilities::getFacesLocalIdFromConnectivity(), Arcane::mesh::FullCellInfo::memoryUsed(), and Arcane::ItemTypeMng::printTypes().
order()
Int32 Arcane::ItemTypeInfo::order () const inline
Order of the type.
Definition at line 132 of file ItemTypeInfo.h.
Referenced by Arcane::ItemTypeInfoBuilder::setInfos(), and Arcane::ItemTypeInfoBuilder::setOrder().
typeId()
Int16 Arcane::ItemTypeInfo::typeId () const inline
Type number.
Definition at line 116 of file ItemTypeInfo.h.
Referenced by Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), Arcane::ItemTypeMng::printTypes(), and Arcane::Hdf5VariableInfoBase::writeGroup().
typeName()
String Arcane::ItemTypeInfo::typeName () const inline
Type name.
Definition at line 126 of file ItemTypeInfo.h.
Referenced by Arcane::mesh::OneMeshItemAdder::_addOneCell(), Arcane::ItemPrinter::Internal::_printBasics(), Arcane::MshParallelMeshReader::_readElementsFromFile(), Arcane::MEDMeshReader::_readFaces(), Arcane::ItemTypeMng::_readTypes(), Arcane::MshMeshWriter::_writeElements(), Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), Arcane::ItemTypeMng::printTypes(), Arcane::ItemTypeMng::typeName(), and Arcane::ItemTypeMng::typeName().
Member Data Documentation
m_dimension
Int16 Arcane::ItemTypeInfo::m_dimension = (-1) protected
Dimension (-1) if not initialized.
Definition at line 172 of file ItemTypeInfo.h.
Referenced by dimension(), and Arcane::ItemTypeInfoBuilder::setInfos().
m_first_item_index
Integer Arcane::ItemTypeInfo::m_first_item_index = 0 protected
Index of this type in the list of indices of m_mng.
Definition at line 184 of file ItemTypeInfo.h.
Referenced by Arcane::ItemTypeInfoBuilder::addEdge(), Arcane::ItemTypeInfoBuilder::addEdge2D(), Arcane::ItemTypeInfoBuilder::addFaceGeneric(), Arcane::ItemTypeInfoBuilder::addFaceHeptagon(), Arcane::ItemTypeInfoBuilder::addFaceHexagon(), Arcane::ItemTypeInfoBuilder::addFaceLine(), Arcane::ItemTypeInfoBuilder::addFaceLine3(), Arcane::ItemTypeInfoBuilder::addFaceLine4(), Arcane::ItemTypeInfoBuilder::addFaceOctogon(), Arcane::ItemTypeInfoBuilder::addFacePentagon(), Arcane::ItemTypeInfoBuilder::addFaceQuad(), Arcane::ItemTypeInfoBuilder::addFaceQuad8(), Arcane::ItemTypeInfoBuilder::addFaceQuad9(), Arcane::ItemTypeInfoBuilder::addFaceTriangle(), Arcane::ItemTypeInfoBuilder::addFaceTriangle6(), Arcane::ItemTypeInfoBuilder::addFaceVertex(), Arcane::ItemTypeInfoBuilder::computeFaceEdgeInfos(), localEdge(), and localFace().
m_has_center_node
bool Arcane::ItemTypeInfo::m_has_center_node = false protected
Indicates if the type has a center node (for faces or cells).
Definition at line 176 of file ItemTypeInfo.h.
Referenced by hasCenterNode(), and Arcane::ItemTypeInfoBuilder::setHasCenterNode().
m_is_polygon
bool Arcane::ItemTypeInfo::m_is_polygon = false protected
Indicates if the type is a polygon.
Definition at line 178 of file ItemTypeInfo.h.
Referenced by isPolygon().
m_is_valid_for_cell
bool Arcane::ItemTypeInfo::m_is_valid_for_cell = true protected
Indicates if the type is valid for a cell.
Definition at line 174 of file ItemTypeInfo.h.
Referenced by isValidForCell(), and Arcane::ItemTypeInfoBuilder::setIsValidForCell().
m_linear_type_id
ItemTypeId Arcane::ItemTypeInfo::m_linear_type_id { IT_NullType } protected
Definition at line 170 of file ItemTypeInfo.h.
m_mng
ItemTypeMng* Arcane::ItemTypeInfo::m_mng = nullptr protected
Definition at line 168 of file ItemTypeInfo.h.
m_nb_edge
Integer Arcane::ItemTypeInfo::m_nb_edge = 0 protected
Definition at line 180 of file ItemTypeInfo.h.
m_nb_face
Integer Arcane::ItemTypeInfo::m_nb_face = 0 protected
Definition at line 181 of file ItemTypeInfo.h.
m_nb_node
Integer Arcane::ItemTypeInfo::m_nb_node = 0 protected
Definition at line 179 of file ItemTypeInfo.h.
m_order
Int32 Arcane::ItemTypeInfo::m_order = 1 protected
Definition at line 182 of file ItemTypeInfo.h.
m_type_id
ItemTypeId Arcane::ItemTypeInfo::m_type_id { IT_NullType } protected
Definition at line 169 of file ItemTypeInfo.h.
m_type_name
String Arcane::ItemTypeInfo::m_type_name protected
Definition at line 185 of file ItemTypeInfo.h.
The documentation for this class was generated from the following file:
ItemTypeInfo.h