Arcane: Arcane::ServiceBuildInfoBase Class Reference
Arcane::ServiceBuildInfoBase Class Reference
Information for creating a service.
#include <arcane/core/ServiceBuildInfo.h>
Public Member Functions
IApplication * application () const
Access to the associated IApplication.
ISession * session () const
Access to the associated ISession.
ISubDomain * subDomain () const
Access to the associated ISubDomain.
IMesh * mesh () const
Access to the associated IMesh.
const MeshHandle & meshHandle () const
Access to the associated mesh handle MeshHandle.
ICaseOptions * caseOptions () const
Access to the associated ICaseOptions.
IBase * serviceParent () const
Access to the parent instance that created this instance.
eServiceType creationType () const
Type of service that can be created by this instance.
Constructors.
The different constructors allow defining the service type (eServiceType).
ServiceBuildInfoBase (IApplication *app)
Service associated with an application IApplication.
ServiceBuildInfoBase (ISession *session)
Service associated with a session ISession.
ServiceBuildInfoBase (ISubDomain *sd)
Service associated with a subdomain ISubDomain.
ServiceBuildInfoBase (ISubDomain *sd, IMesh *mesh)
Service associated with a mesh mesh.
ServiceBuildInfoBase (const MeshHandle &mesh_handle)
Service associated with a mesh mesh_handle.
ServiceBuildInfoBase (ISubDomain *sd, const MeshHandle &mesh_handle)
Service associated with a mesh mesh_handle.
ServiceBuildInfoBase (ICaseOptions *co)
Service associated with a dataset option co.
ServiceBuildInfoBase (ISubDomain *sd, ICaseOptions *co)
Service associated with a dataset option co.
ServiceBuildInfoBase (IMesh *mesh)
Service associated with a mesh mesh.
Private Attributes
IApplication * m_application = nullptr
ISession * m_session = nullptr
ISubDomain * m_sub_domain = nullptr
MeshHandle m_mesh_handle
ICaseOptions * m_case_options = nullptr
IBase * m_service_parent = nullptr
eServiceType m_creation_type = ST_None
Detailed Description
Information for creating a service.
Instances of this class are internal to Arcane. Generally, you must use the ServiceBuildInfo class.
The different fields of this class are not all valid. Their validity depends on the constructor used. Only application() is always valid. It is possible to know the valid fields via the value of creationType().
Definition at line 42 of file ServiceBuildInfo.h.
Constructor & Destructor Documentation
ServiceBuildInfoBase() [1/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (IApplication * app) explicit
Service associated with an application IApplication.
The service will be of type ST_Application.
Definition at line 32 of file ServiceBuildInfo.cc.
References Arcane::ST_Application.
Referenced by ServiceBuildInfoBase(), ServiceBuildInfoBase(), ServiceBuildInfoBase(), and ServiceBuildInfoBase().
ServiceBuildInfoBase() [2/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (ISession * session) explicit
Service associated with a session ISession.
The service will be of type ST_Session.
Definition at line 43 of file ServiceBuildInfo.cc.
References session(), and Arcane::ST_Session.
ServiceBuildInfoBase() [3/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (ISubDomain * sd) explicit
Service associated with a subdomain ISubDomain.
The service will be of type ST_SubDomain. Also provides access to the mesh property (mesh())
Definition at line 93 of file ServiceBuildInfo.cc.
References Arcane::ST_SubDomain.
ServiceBuildInfoBase() [4/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (ISubDomain * sd, IMesh * mesh)
Service associated with a mesh mesh.
The service will be of type ST_SubDomain.
Definition at line 63 of file ServiceBuildInfo.cc.
References mesh(), and ServiceBuildInfoBase().
ServiceBuildInfoBase() [5/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (const MeshHandle & mesh_handle) explicit
Service associated with a mesh mesh_handle.
The service will be of type ST_SubDomain.
Definition at line 84 of file ServiceBuildInfo.cc.
References ServiceBuildInfoBase(), and subDomain().
ServiceBuildInfoBase() [6/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (ISubDomain * sd, const MeshHandle & mesh_handle)
Service associated with a mesh mesh_handle.
The service will be of type ST_SubDomain.
Definition at line 72 of file ServiceBuildInfo.cc.
References Arcane::ST_SubDomain.
ServiceBuildInfoBase() [7/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (ICaseOptions * co) explicit
Service associated with a dataset option co.
The service will be of type ST_CaseOption. Also provides access to the mesh (mesh()) and subdomain (subDomain()) properties.
Definition at line 118 of file ServiceBuildInfo.cc.
References ServiceBuildInfoBase(), and subDomain().
ServiceBuildInfoBase() [8/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (ISubDomain * sd, ICaseOptions * co)
Service associated with a dataset option co.
The service will be of type ST_CaseOption. Also provides access to the mesh (mesh()) and subdomain (subDomain()) properties.
Definition at line 105 of file ServiceBuildInfo.cc.
References meshHandle(), and Arcane::ST_CaseOption.
ServiceBuildInfoBase() [9/9]
Arcane::ServiceBuildInfoBase::ServiceBuildInfoBase (IMesh * mesh) explicit
Service associated with a mesh mesh.
The service will be of type ST_SubDomain.
Deprecated
Use ServiceBuildInfoBase(const MeshHandle&) instead.
Definition at line 54 of file ServiceBuildInfo.cc.
References mesh(), ServiceBuildInfoBase(), and subDomain().
Member Function Documentation
application()
IApplication * Arcane::ServiceBuildInfoBase::application () const inline
Access to the associated IApplication.
The instance is never null regardless of the service.
Definition at line 133 of file ServiceBuildInfo.h.
caseOptions()
ICaseOptions * Arcane::ServiceBuildInfoBase::caseOptions () const inline
Access to the associated ICaseOptions.
Precondition
creationType() & ST_CaseOption
Definition at line 168 of file ServiceBuildInfo.h.
Referenced by ArcaneAlephTestSchemeFacesObject::ArcaneAlephTestSchemeFacesObject(), Arcane::ArcaneArcaneBasicCheckpointObject::ArcaneArcaneBasicCheckpointObject(), Arcane::ArcaneArcaneBasicMeshSubdividerServiceObject::ArcaneArcaneBasicMeshSubdividerServiceObject(), Arcane::ArcaneArcaneCaseMeshMasterServiceObject::ArcaneArcaneCaseMeshMasterServiceObject(), ArcaneArcaneCaseMeshServiceObject::ArcaneArcaneCaseMeshServiceObject(), Arcane::ArcaneArcaneCasePartitionerObject::ArcaneArcaneCasePartitionerObject(), Arcane::ArcaneArcaneGeometricMeshPartitionerServiceObject::ArcaneArcaneGeometricMeshPartitionerServiceObject(), Arcane::ArcaneArcaneMeshConverterObject::ArcaneArcaneMeshConverterObject(), Arcane::ArcaneBasicParticleExchangerObject::ArcaneBasicParticleExchangerObject(), Arcane::ArcaneCartesian2DMeshGeneratorObject::ArcaneCartesian2DMeshGeneratorObject(), Arcane::ArcaneCartesian3DMeshGeneratorObject::ArcaneCartesian3DMeshGeneratorObject(), Arcane::ArcaneEnsight7PostProcessorObject::ArcaneEnsight7PostProcessorObject(), ArcaneEuclidian3GeometryObject::ArcaneEuclidian3GeometryObject(), Arcane::ArcaneHdf5MpiReaderWriterObject::ArcaneHdf5MpiReaderWriterObject(), Arcane::ArcaneHdf5ReaderWriterObject::ArcaneHdf5ReaderWriterObject(), Arcane::ArcaneHdf5VariableReaderObject::ArcaneHdf5VariableReaderObject(), Arcane::ArcaneHdf5VariableWriterObject::ArcaneHdf5VariableWriterObject(), Arcane::ArcaneHoneyComb2DMeshGeneratorObject::ArcaneHoneyComb2DMeshGeneratorObject(), Arcane::ArcaneHoneyComb3DMeshGeneratorObject::ArcaneHoneyComb3DMeshGeneratorObject(), Arcane::ArcaneKdiPostProcessorObject::ArcaneKdiPostProcessorObject(), Arcane::ArcaneMeshPartitionerTesterServiceObject::ArcaneMeshPartitionerTesterServiceObject(), Arcane::ArcaneMetisMeshPartitionerObject::ArcaneMetisMeshPartitionerObject(), ArcanePDESRandomNumberGeneratorObject::ArcanePDESRandomNumberGeneratorObject(), Arcane::ArcanePTScotchMeshPartitionerObject::ArcanePTScotchMeshPartitionerObject(), ArcaneSimpleCsvComparatorObject::ArcaneSimpleCsvComparatorObject(), ArcaneSimpleCsvOutputObject::ArcaneSimpleCsvOutputObject(), Arcane::ArcaneSod3DMeshGeneratorObject::ArcaneSod3DMeshGeneratorObject(), Arcane::ArcaneSplitSDMeshPartitionerObject::ArcaneSplitSDMeshPartitionerObject(), Arcane::ArcaneVtkHdfPostProcessorObject::ArcaneVtkHdfPostProcessorObject(), Arcane::ArcaneVtkHdfV2PostProcessorObject::ArcaneVtkHdfV2PostProcessorObject(), Arcane::ArcaneVtkPolyhedralMeshIOObject::ArcaneVtkPolyhedralMeshIOObject(), and Arcane::ArcaneZoltanMeshPartitionerObject::ArcaneZoltanMeshPartitionerObject().
creationType()
eServiceType Arcane::ServiceBuildInfoBase::creationType () const inline
Type of service that can be created by this instance.
Definition at line 176 of file ServiceBuildInfo.h.
mesh()
IMesh * Arcane::ServiceBuildInfoBase::mesh () const
Access to the associated IMesh.
Precondition
creationType() & (ST_CaseOption|ST_SubDomain)
Definition at line 127 of file ServiceBuildInfo.cc.
Referenced by ServiceBuildInfoBase(), and ServiceBuildInfoBase().
meshHandle()
const MeshHandle & Arcane::ServiceBuildInfoBase::meshHandle () const inline
Access to the associated mesh handle MeshHandle.
Precondition
creationType() & (ST_CaseOption|ST_SubDomain)
Definition at line 161 of file ServiceBuildInfo.h.
Referenced by ServiceBuildInfoBase().
serviceParent()
IBase * Arcane::ServiceBuildInfoBase::serviceParent () const inline
Access to the parent instance that created this instance.
Definition at line 173 of file ServiceBuildInfo.h.
Referenced by Arcane::ServiceLoader::_loadServices().
session()
ISession * Arcane::ServiceBuildInfoBase::session () const inline
Access to the associated ISession.
Precondition
creationType() & (ST_CaseOption|ST_SubDomain|ST_Session)
Definition at line 140 of file ServiceBuildInfo.h.
Referenced by ServiceBuildInfoBase().
subDomain()
ISubDomain * Arcane::ServiceBuildInfoBase::subDomain () const inline
Access to the associated ISubDomain.
Precondition
creationType() & (ST_CaseOption|ST_SubDomain)
Definition at line 147 of file ServiceBuildInfo.h.
Referenced by Arcane::ArcaneArcaneDirectExecutionObject::ArcaneArcaneDirectExecutionObject(), ServiceBuildInfoBase(), ServiceBuildInfoBase(), and ServiceBuildInfoBase().
Member Data Documentation
m_application
IApplication* Arcane::ServiceBuildInfoBase::m_application = nullptr private
Definition at line 181 of file ServiceBuildInfo.h.
m_case_options
ICaseOptions* Arcane::ServiceBuildInfoBase::m_case_options = nullptr private
Definition at line 185 of file ServiceBuildInfo.h.
m_creation_type
eServiceType Arcane::ServiceBuildInfoBase::m_creation_type = ST_None private
Definition at line 187 of file ServiceBuildInfo.h.
m_mesh_handle
MeshHandle Arcane::ServiceBuildInfoBase::m_mesh_handle private
Definition at line 184 of file ServiceBuildInfo.h.
m_service_parent
IBase* Arcane::ServiceBuildInfoBase::m_service_parent = nullptr private
Definition at line 186 of file ServiceBuildInfo.h.
m_session
ISession* Arcane::ServiceBuildInfoBase::m_session = nullptr private
Definition at line 182 of file ServiceBuildInfo.h.
m_sub_domain
ISubDomain* Arcane::ServiceBuildInfoBase::m_sub_domain = nullptr private
Definition at line 183 of file ServiceBuildInfo.h.
The documentation for this class was generated from the following files:
ServiceBuildInfo.h
ServiceBuildInfo.cc