Arcane: Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits > Class Template Reference
Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits > Class Template Reference
Parallel bitonic sort algorithm.
#include <arcane/core/parallel/BitonicSort.h>
Public Member Functions
BitonicSort (IParallelMng *parallel_mng)
BitonicSort (IParallelMng *parallel_mng, const KeyTypeTraits &traits)
void sort (ConstArrayView< KeyType > keys) override
Parallelly sorts the elements of keys on all ranks.
ConstArrayView< KeyType > keys () const override
After a sort, returns the list of elements on this rank.
Int32ConstArrayView keyRanks () const override
After a sort, returns the array of original ranks of the elements of keys().
Int32ConstArrayView keyIndexes () const override
After a sort, returns the array of indices in the original list of the elements of keys().
void setNeedIndexAndRank (bool want_index_and_rank)
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Private Member Functions
void _mergeLevels (Int32 begin, Int32 size)
Bitonic sort of the variable key.
void _mergeProcessors (Int32 proc1, Int32 proc2)
Merging lists from two processors.
void _separator (Int32 begin, Int32 size)
Bitonic sort algorithm separator stage.
void _localHeapSort ()
Local heap sort of the variable m_key.
void _init (ConstArrayView< KeyType > keys)
Private Attributes
UniqueArray< KeyType > m_keys
Variable containing the sorting key.
UniqueArray< Int32 > m_key_ranks
Array containing the rank of the processor where the key is located.
UniqueArray< Int32 > m_key_indexes
Array containing the index of the key within the processor.
IParallelMng * m_parallel_mng = nullptr
Parallelism manager.
Int64 m_init_size = 0
Number of local elements.
Int64 m_size = 0
Number of local elements for the bitonic sort.
bool m_want_index_and_rank = true
Indicates whether rank and index information is desired.
Integer m_nb_merge = 0
Statistics on the number of message levels.
KeyTypeTraits m_traits
Additional Inherited Members
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Detailed Description
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>>
class Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >
Parallel bitonic sort algorithm.
The key type can be arbitrary, but it must possess a comparison operator. The necessary characteristics are provided by the KeyTypeTraits class. The implementation provides operations for Int32, Int64, and Real types via the BitonicSortDefaultTraits class. For other types, it is necessary to specialize this class.
The sort() method performs the sort. After calling this method, it is possible to retrieve the list of keys via keys() and the ranks and indices in the original list of each key element via the keyRanks() and keyIndexes() methods. If this information is not useful, it is possible to call setNeedIndexAndRank() to disable it, which allows the sort to be slightly accelerated.
The sort is performed such that the elements are sorted in ascending order starting with rank processor 0, then rank 1, and so on until the end. For example, for a list of 5000 elements distributed over 4 ranks, the rank 0 processor will have the 1250 smallest elements at the end of the sort, the rank 1 processor the next 1250 elements, and so on.
To accelerate the algorithm, it is preferable that all processors have approximately the same number of elements in their list initially. At the end of the sort, it is possible that not all processors have the same number of elements in the list, and notably the highest-ranked processors may not have any elements.
Definition at line 99 of file BitonicSort.h.
Constructor & Destructor Documentation
BitonicSort() [1/2]
template<typename KeyType, typename KeyTypeTraits> Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::BitonicSort (IParallelMng * parallel_mng) explicit
Definition at line 32 of file BitonicSortT.H.
BitonicSort() [2/2]
template<typename KeyType, typename KeyTypeTraits> Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::BitonicSort (IParallelMng * parallel_mng, const KeyTypeTraits & traits) explicit
Definition at line 39 of file BitonicSortT.H.
Member Function Documentation
_init()
template<typename KeyType, typename KeyTypeTraits> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_init (ConstArrayView< KeyType > keys) private
Definition at line 50 of file BitonicSortT.H.
_localHeapSort()
template<typename KeyType, typename KeyTypeTraits> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_localHeapSort () private
Local heap sort of the variable m_key.
Upon exiting the call, the variable is sorted in ascending order within each processor.
Definition at line 360 of file BitonicSortT.H.
References m_key_indexes, m_key_ranks, m_keys, and m_size.
Referenced by sort().
_mergeLevels()
template<typename KeyType, typename KeyTypeTraits> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_mergeLevels (Int32 begin, Int32 size) private
Bitonic sort of the variable key.
Upon exiting the call, the key variable is entirely sorted in ascending order: the first elements are located in ascending order on processor 0, the following on processor 1, etc... The sorting is done 'in place', so that the size of the arrays on the different processors is not modified.
Definition at line 165 of file BitonicSortT.H.
References _mergeProcessors(), and _separator().
Referenced by sort().
_mergeProcessors()
template<typename KeyType, typename KeyTypeTraits> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_mergeProcessors (Int32 iproc1, Int32 iproc2) private
Merging lists from two processors.
Parameters
iproc1 processor with lower ID whose list is merged
iproc2 processor with higher ID whose list is merged
This operation is the elementary building block of the bitonic merge sort algorithm. On input, it takes the numbers of two processors with iproc1<iproc2. On output, the m_key arrays of these two processors are sorted: the smallest elements are sorted in ascending order on iproc1, the largest elements are sorted in ascending order on iproc2.
Definition at line 214 of file BitonicSortT.H.
References Arcane::Array< T >::add(), ARCANE_FATAL, Arcane::TraceAccessor::info(), m_init_size, m_key_indexes, m_key_ranks, m_keys, m_nb_merge, m_parallel_mng, m_size, m_want_index_and_rank, and Arcane::Array< T >::resize().
Referenced by _mergeLevels(), and _separator().
_separator()
template<typename KeyType, typename KeyTypeTraits> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::_separator (Int32 begin, Int32 size) private
Bitonic sort algorithm separator stage.
Definition at line 190 of file BitonicSortT.H.
References _mergeProcessors().
Referenced by _mergeLevels().
keyIndexes()
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> Int32ConstArrayView Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::keyIndexes () const inline override virtual
After a sort, returns the array of indices in the original list of the elements of keys().
Implements Arcane::Parallel::IParallelSort< KeyType >.
Definition at line 124 of file BitonicSort.h.
References m_key_indexes.
keyRanks()
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> Int32ConstArrayView Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::keyRanks () const inline override virtual
After a sort, returns the array of original ranks of the elements of keys().
Implements Arcane::Parallel::IParallelSort< KeyType >.
Definition at line 121 of file BitonicSort.h.
References m_key_ranks.
keys()
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> ConstArrayView< KeyType > Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::keys () const inline override virtual
After a sort, returns the list of elements on this rank.
Implements Arcane::Parallel::IParallelSort< KeyType >.
Definition at line 118 of file BitonicSort.h.
References m_keys.
Referenced by Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::mesh::FaceUniqueIdBuilder2::_computeParallel(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), Arcane::mesh::ItemsOwnerBuilderImpl::_sortInfos(), and sort().
setNeedIndexAndRank()
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::setNeedIndexAndRank (bool want_index_and_rank) inline
Definition at line 128 of file BitonicSort.h.
sort()
template<typename KeyType, typename KeyTypeTraits> void Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::sort (ConstArrayView< KeyType > keys) inline override virtual
Parallelly sorts the elements of keys on all ranks.
Bitonic sort of the variable m_key.
This operation is collective.
Upon exiting the call, the key variable is entirely sorted in ascending order: the first elements are located in ascending order on processor 0, the following on processor 1, etc... The sorting is done 'in place', so that the size of the arrays on the different processors is not modified.
Implements Arcane::Parallel::IParallelSort< KeyType >.
Definition at line 98 of file BitonicSortT.H.
References _localHeapSort(), _mergeLevels(), Arcane::TraceAccessor::info(), keys(), m_key_indexes, m_key_ranks, m_keys, m_nb_merge, m_parallel_mng, m_size, and m_want_index_and_rank.
Referenced by Arcane::mesh::FaceUniqueIdBuilder2::_computeAndSortBoundaryFaces(), Arcane::mesh::FaceUniqueIdBuilder2::_computeParallel(), Arcane::mesh::GhostLayerBuilder2::_sortBoundaryNodeList(), and Arcane::mesh::ItemsOwnerBuilderImpl::_sortInfos().
Member Data Documentation
m_init_size
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> Int64 Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_init_size = 0 private
Number of local elements.
Definition at line 151 of file BitonicSort.h.
Referenced by _mergeProcessors().
m_key_indexes
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> UniqueArray<Int32> Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_key_indexes private
Array containing the index of the key within the processor.
Definition at line 147 of file BitonicSort.h.
Referenced by _localHeapSort(), _mergeProcessors(), keyIndexes(), and sort().
m_key_ranks
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> UniqueArray<Int32> Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_key_ranks private
Array containing the rank of the processor where the key is located.
Definition at line 145 of file BitonicSort.h.
Referenced by _localHeapSort(), _mergeProcessors(), keyRanks(), and sort().
m_keys
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> UniqueArray<KeyType> Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_keys private
Variable containing the sorting key.
Definition at line 143 of file BitonicSort.h.
Referenced by _localHeapSort(), _mergeProcessors(), keys(), and sort().
m_nb_merge
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> Integer Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_nb_merge = 0 private
Statistics on the number of message levels.
Definition at line 159 of file BitonicSort.h.
Referenced by _mergeProcessors(), and sort().
m_parallel_mng
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> IParallelMng* Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_parallel_mng = nullptr private
Parallelism manager.
Definition at line 149 of file BitonicSort.h.
Referenced by _mergeProcessors(), and sort().
m_size
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> Int64 Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_size = 0 private
Number of local elements for the bitonic sort.
Definition at line 153 of file BitonicSort.h.
Referenced by _localHeapSort(), _mergeProcessors(), and sort().
m_traits
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> KeyTypeTraits Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_traits private
Definition at line 161 of file BitonicSort.h.
m_want_index_and_rank
template<typename KeyType, typename KeyTypeTraits = BitonicSortDefaultTraits<KeyType>> bool Arcane::Parallel::BitonicSort< KeyType, KeyTypeTraits >::m_want_index_and_rank = true private
Indicates whether rank and index information is desired.
Definition at line 156 of file BitonicSort.h.
Referenced by _mergeProcessors(), and sort().
The documentation for this class was generated from the following files:
BitonicSort.h
BitonicSortT.H