Arcane: Arcane::CartesianGridDimension Class Reference
Arcane::CartesianGridDimension Class Reference
Information about the dimensions of a Cartesian grid.
#include <arcane/core/CartesianGridDimension.h>
Classes
class NodeUniqueIdComputer2D
Class for calculating the uniqueId() of a node in 2D based on its position in the grid.
class CellUniqueIdComputer2D
Class for calculating the uniqueId() of a cell in 2D based on its position in the grid.
class FaceUniqueIdComputer2D
Class for calculating the uniqueId() of a face in 2D based on its position in the grid.
class NodeUniqueIdComputer3D
Class for calculating the uniqueId() of a node in 3D based on its position in the grid.
class CellUniqueIdComputer3D
Class for calculating the uniqueId() of a cell in 3D based on its position in the grid.
class FaceUniqueIdComputer3D
Class for calculating the uniqueId() of a face in 2D based on its position in the grid.
Public Member Functions
CartesianGridDimension (Int64 nb_cell_x, Int64 nb_cell_y)
Constructs a 2D grid of dimension (nb_cell_x,nb_cell_y).
CartesianGridDimension (Int64 nb_cell_x, Int64 nb_cell_y, Int64 nb_cell_z)
Constructs a 3D grid of dimension (nb_cell_x,nb_cell_y,nb_cell_z).
CartesianGridDimension (const Int64x2 &dims)
Constructs a 2D grid of dimension dims.
CartesianGridDimension (const Int64x3 &dims)
Constructs a 3D grid of dimension dims.
CartesianGridDimension (const Int32x2 &dims)
Constructs a 2D grid of dimension dims.
CartesianGridDimension (const Int32x3 &dims)
Constructs a 3D grid of dimension dims.
constexpr Int64x3 nbCell () const
Number of cells in each direction.
constexpr Int64x3 nbNode () const
Number of nodes in each direction.
constexpr Int64x3 nbFace () const
Number of faces in each direction.
constexpr Int64x3 nbFaceParallelToDirection () const
Total number of faces parallel to a given direction.
constexpr Int64 totalNbCell () const
Total number of cells.
Private Member Functions
NodeUniqueIdComputer2D getNodeComputer2D (Int64 offset) const
Instance to calculate the uniqueIds() of nodes for this grid.
NodeUniqueIdComputer3D getNodeComputer3D (Int64 offset) const
Instance to calculate the uniqueIds() of nodes for this grid.
CellUniqueIdComputer2D getCellComputer2D (Int64 offset) const
Instance to calculate the uniqueIds() of cells for this grid.
CellUniqueIdComputer3D getCellComputer3D (Int64 offset) const
Instance to calculate the uniqueIds() of cells for this grid.
FaceUniqueIdComputer2D getFaceComputer2D (Int64 offset) const
Instance to calculate the uniqueIds() of faces for this grid.
FaceUniqueIdComputer3D getFaceComputer3D (Int64 offset) const
Instance to calculate the uniqueIds() of faces for this grid.
void _init ()
Private Attributes
Int64x3 m_nb_cell
Number of cells in each direction.
Int64x3 m_nb_node
Number of nodes in each direction.
Int64x3 m_nb_face
Number of faces in each direction.
Int64x3 m_nb_face_oriented
Total number of faces in a given orientation.
Int64 m_nb_cell_xy = 0
Int64 m_total_nb_cell = 0
Friends
class CartesianMeshUniqueIdRenumbering
class CartesianMeshCoarsening
class CartesianMeshCoarsening2
Detailed Description
Information about the dimensions of a Cartesian grid.
This class allows obtaining, based on the number of cells in each direction, the various information about the dimensions of the mesh.
Definition at line 48 of file CartesianGridDimension.h.
Constructor & Destructor Documentation
CartesianGridDimension() [1/6]
Arcane::CartesianGridDimension::CartesianGridDimension (Int64 nb_cell_x, Int64 nb_cell_y)
Constructs a 2D grid of dimension (nb_cell_x,nb_cell_y).
Definition at line 40 of file CartesianGridDimension.cc.
CartesianGridDimension() [2/6]
Arcane::CartesianGridDimension::CartesianGridDimension (Int64 nb_cell_x, Int64 nb_cell_y, Int64 nb_cell_z)
Constructs a 3D grid of dimension (nb_cell_x,nb_cell_y,nb_cell_z).
Definition at line 30 of file CartesianGridDimension.cc.
References m_nb_cell.
CartesianGridDimension() [3/6]
Arcane::CartesianGridDimension::CartesianGridDimension (const Int64x2 & dims) explicit
Constructs a 2D grid of dimension dims.
Definition at line 49 of file CartesianGridDimension.cc.
CartesianGridDimension() [4/6]
Arcane::CartesianGridDimension::CartesianGridDimension (const Int64x3 & dims) explicit
Constructs a 3D grid of dimension dims.
Definition at line 58 of file CartesianGridDimension.cc.
CartesianGridDimension() [5/6]
Arcane::CartesianGridDimension::CartesianGridDimension (const Int32x2 & dims) explicit
Constructs a 2D grid of dimension dims.
Definition at line 67 of file CartesianGridDimension.cc.
CartesianGridDimension() [6/6]
Arcane::CartesianGridDimension::CartesianGridDimension (const Int32x3 & dims) explicit
Constructs a 3D grid of dimension dims.
Definition at line 76 of file CartesianGridDimension.cc.
Member Function Documentation
_init()
void Arcane::CartesianGridDimension::_init () private
Definition at line 85 of file CartesianGridDimension.cc.
getCellComputer2D()
CellUniqueIdComputer2D Arcane::CartesianGridDimension::getCellComputer2D (Int64 offset) const inline private
Instance to calculate the uniqueIds() of cells for this grid.
Definition at line 349 of file CartesianGridDimension.h.
References m_nb_cell.
Referenced by Arcane::CartesianMeshCoarsening2::_createCoarseCells2D(), and Arcane::CartesianMeshCoarsening::createCoarseCells().
getCellComputer3D()
CellUniqueIdComputer3D Arcane::CartesianGridDimension::getCellComputer3D (Int64 offset) const inline private
Instance to calculate the uniqueIds() of cells for this grid.
Definition at line 354 of file CartesianGridDimension.h.
References m_nb_cell.
Referenced by Arcane::CartesianMeshCoarsening2::_createCoarseCells3D().
getFaceComputer2D()
FaceUniqueIdComputer2D Arcane::CartesianGridDimension::getFaceComputer2D (Int64 offset) const inline private
Instance to calculate the uniqueIds() of faces for this grid.
Definition at line 359 of file CartesianGridDimension.h.
References m_nb_cell, m_nb_face, and nbFaceParallelToDirection().
Referenced by Arcane::CartesianMeshCoarsening2::_createCoarseCells2D(), Arcane::mesh::CartesianFaceUniqueIdBuilder::computeFacesUniqueIdAndOwner(), and Arcane::CartesianMeshCoarsening::createCoarseCells().
getFaceComputer3D()
FaceUniqueIdComputer3D Arcane::CartesianGridDimension::getFaceComputer3D (Int64 offset) const inline private
Instance to calculate the uniqueIds() of faces for this grid.
Definition at line 365 of file CartesianGridDimension.h.
References m_nb_cell, m_nb_face, and nbFaceParallelToDirection().
Referenced by Arcane::CartesianMeshCoarsening2::_createCoarseCells3D(), and Arcane::mesh::CartesianFaceUniqueIdBuilder::computeFacesUniqueIdAndOwner().
getNodeComputer2D()
NodeUniqueIdComputer2D Arcane::CartesianGridDimension::getNodeComputer2D (Int64 offset) const inline private
Instance to calculate the uniqueIds() of nodes for this grid.
Definition at line 339 of file CartesianGridDimension.h.
References m_nb_node.
Referenced by Arcane::CartesianMeshCoarsening2::_createCoarseCells2D(), and Arcane::CartesianMeshCoarsening::createCoarseCells().
getNodeComputer3D()
NodeUniqueIdComputer3D Arcane::CartesianGridDimension::getNodeComputer3D (Int64 offset) const inline private
Instance to calculate the uniqueIds() of nodes for this grid.
Definition at line 344 of file CartesianGridDimension.h.
References m_nb_node.
Referenced by Arcane::CartesianMeshCoarsening2::_createCoarseCells3D().
nbCell()
Int64x3 Arcane::CartesianGridDimension::nbCell () const inline constexpr
Number of cells in each direction.
Definition at line 322 of file CartesianGridDimension.h.
References m_nb_cell.
Referenced by Arcane::mesh::CartesianFaceUniqueIdBuilder::computeFacesUniqueIdAndOwner().
nbFace()
Int64x3 Arcane::CartesianGridDimension::nbFace () const inline constexpr
Number of faces in each direction.
Definition at line 328 of file CartesianGridDimension.h.
References m_nb_face.
Referenced by Arcane::mesh::CartesianFaceUniqueIdBuilder::computeFacesUniqueIdAndOwner().
nbFaceParallelToDirection()
Int64x3 Arcane::CartesianGridDimension::nbFaceParallelToDirection () const inline constexpr
Total number of faces parallel to a given direction.
Definition at line 331 of file CartesianGridDimension.h.
References m_nb_face_oriented.
Referenced by Arcane::mesh::CartesianFaceUniqueIdBuilder::computeFacesUniqueIdAndOwner(), getFaceComputer2D(), and getFaceComputer3D().
nbNode()
Int64x3 Arcane::CartesianGridDimension::nbNode () const inline constexpr
Number of nodes in each direction.
Definition at line 325 of file CartesianGridDimension.h.
References m_nb_node.
totalNbCell()
Int64 Arcane::CartesianGridDimension::totalNbCell () const inline constexpr
Total number of cells.
Definition at line 334 of file CartesianGridDimension.h.
Friends And Related Symbol Documentation
CartesianMeshCoarsening
friend class CartesianMeshCoarsening friend
Definition at line 54 of file CartesianGridDimension.h.
CartesianMeshCoarsening2
friend class CartesianMeshCoarsening2 friend
Definition at line 55 of file CartesianGridDimension.h.
CartesianMeshUniqueIdRenumbering
friend class CartesianMeshUniqueIdRenumbering friend
Definition at line 53 of file CartesianGridDimension.h.
Member Data Documentation
m_nb_cell
Int64x3 Arcane::CartesianGridDimension::m_nb_cell private
Number of cells in each direction.
Definition at line 376 of file CartesianGridDimension.h.
Referenced by CartesianGridDimension(), getCellComputer2D(), getCellComputer3D(), getFaceComputer2D(), getFaceComputer3D(), and nbCell().
m_nb_cell_xy
Int64 Arcane::CartesianGridDimension::m_nb_cell_xy = 0 private
Definition at line 384 of file CartesianGridDimension.h.
m_nb_face
Int64x3 Arcane::CartesianGridDimension::m_nb_face private
Number of faces in each direction.
Definition at line 380 of file CartesianGridDimension.h.
Referenced by getFaceComputer2D(), getFaceComputer3D(), and nbFace().
m_nb_face_oriented
Int64x3 Arcane::CartesianGridDimension::m_nb_face_oriented private
Total number of faces in a given orientation.
Definition at line 382 of file CartesianGridDimension.h.
Referenced by nbFaceParallelToDirection().
m_nb_node
Int64x3 Arcane::CartesianGridDimension::m_nb_node private
Number of nodes in each direction.
Definition at line 378 of file CartesianGridDimension.h.
Referenced by getNodeComputer2D(), getNodeComputer3D(), and nbNode().
m_total_nb_cell
Int64 Arcane::CartesianGridDimension::m_total_nb_cell = 0 private
Definition at line 385 of file CartesianGridDimension.h.
The documentation for this class was generated from the following files:
CartesianGridDimension.h
CartesianGridDimension.cc