Arcane: Arcane::ICaseOptions Class Reference
Arcane::ICaseOptions Class Reference abstract
Interface for a list of data set options.
#include <arcane/core/ICaseOptions.h>
Public Member Functions
virtual String rootTagTrueName () const =0
True name (untranslated) of the element.
virtual String rootTagName () const =0
Name of the element in the data set language.
virtual String translatedName (const String &lang) const =0
Name in the language lang of the option. Returns rootTagTrueName() if no translation exists.
virtual void read (bool is_phase1)=0
virtual void read (eCaseOptionReadPhase read_phase)=0
Performs the reading of the read_phase phase of the options.
virtual void addInvalidChildren (XmlNodeList &)=0
virtual void printChildren (const String &lang, int indent)=0
virtual IServiceInfo * caseServiceInfo () const =0
Returns the associated service or nullptr if none exists.
virtual IModule * caseModule () const =0
Returns the associated module or nullptr if none exists.
virtual void setCaseServiceInfo (IServiceInfo *m)=0
Associates the service m with this data set.
virtual void setCaseModule (IModule *m)=0
Associates the module m with this data set.
virtual void deepGetChildren (Array< CaseOptionBase * > &col)=0
Adds all child options to the list col.
virtual ICaseOptionList * configList ()=0
virtual const ICaseOptionList * configList () const =0
virtual ICaseFunction * activateFunction ()=0
Function indicating the activation status of the option.
virtual bool isPresent () const =0
Indicates whether the option is present in the data set.
virtual void addAlternativeNodeName (const String &lang, const String &name)=0
Adds a translation for the option name.
virtual ICaseMng * caseMng () const =0
virtual ITraceMng * traceMng () const =0
virtual ISubDomain * subDomain () const =0
Associated sub-domain.
virtual IMesh * mesh () const =0
virtual MeshHandle meshHandle () const =0
virtual ICaseDocument * caseDocument () const =0
virtual ICaseDocumentFragment * caseDocumentFragment () const =0
virtual void detach ()=0
virtual void visit (ICaseDocumentVisitor *visitor) const =0
Applies the visitor to this option.
virtual String xpathFullName () const =0
Full name in XPath format corresponding to rootElement().
virtual Ref< ICaseOptions > toReference ()=0
Private Member Functions
ARCCORE_DECLARE_REFERENCE_COUNTED_INCLASS_METHODS ()
Detailed Description
Interface for a list of data set options.
This interface is managed by a reference counter and should not be explicitly destroyed.
Definition at line 35 of file ICaseOptions.h.
Member Function Documentation
activateFunction()
virtual ICaseFunction * Arcane::ICaseOptions::activateFunction () pure virtual
Function indicating the activation status of the option.
Implemented in Arcane::CaseOptions.
References activateFunction().
Referenced by activateFunction(), and Arcane::TimeLoopMng::doOneIteration().
addAlternativeNodeName()
virtual void Arcane::ICaseOptions::addAlternativeNodeName (const String & lang, const String & name) pure virtual
Adds a translation for the option name.
Adds the option name name corresponding to the language lang. If a translation already exists for this language, it is replaced by this one.
Implemented in Arcane::CaseOptions.
References addAlternativeNodeName().
Referenced by addAlternativeNodeName().
addInvalidChildren()
virtual void Arcane::ICaseOptions::addInvalidChildren (XmlNodeList &) pure virtual
Implemented in Arcane::CaseOptions.
caseModule()
virtual IModule * Arcane::ICaseOptions::caseModule () const pure virtual
Returns the associated module or nullptr if none exists.
Implemented in Arcane::CaseOptions.
References caseModule().
Referenced by caseModule(), Arcane::TimeLoopMng::doOneIteration(), and Arcane::SubDomain::dumpInternalInfos().
caseServiceInfo()
virtual IServiceInfo * Arcane::ICaseOptions::caseServiceInfo () const pure virtual
Returns the associated service or nullptr if none exists.
Implemented in Arcane::CaseOptions.
References caseServiceInfo().
Referenced by caseServiceInfo().
deepGetChildren()
virtual void Arcane::ICaseOptions::deepGetChildren (Array< CaseOptionBase * > & col) pure virtual
Adds all child options to the list col.
Implemented in Arcane::CaseOptions.
References deepGetChildren().
Referenced by deepGetChildren().
detach()
virtual void Arcane::ICaseOptions::detach () pure virtual
Detaches the option from its parent.
Implemented in Arcane::CaseOptions.
References detach().
Referenced by detach().
isPresent()
virtual bool Arcane::ICaseOptions::isPresent () const pure virtual
Indicates whether the option is present in the data set.
An option may not appear if it only contains options with a default value.
Implemented in Arcane::CaseOptions.
References isPresent().
Referenced by isPresent().
read()
virtual void Arcane::ICaseOptions::read (eCaseOptionReadPhase read_phase) pure virtual
Performs the reading of the read_phase phase of the options.
Implemented in Arcane::CaseOptions, and Arcane::CaseOptionServiceImpl.
rootTagName()
virtual String Arcane::ICaseOptions::rootTagName () const pure virtual
Name of the element in the data set language.
Implemented in Arcane::CaseOptions.
Referenced by Arcane::CaseOptionList::addChild(), Arcane::SubDomain::dumpInternalInfos(), Arcane::CaseMng::registerOptions(), and Arcane::CaseOptionList::removeChild().
rootTagTrueName()
virtual String Arcane::ICaseOptions::rootTagTrueName () const pure virtual
True name (untranslated) of the element.
Implemented in Arcane::CaseOptions.
setCaseModule()
virtual void Arcane::ICaseOptions::setCaseModule (IModule * m) pure virtual
Associates the module m with this data set.
Implemented in Arcane::CaseOptions.
References setCaseModule().
Referenced by setCaseModule().
setCaseServiceInfo()
virtual void Arcane::ICaseOptions::setCaseServiceInfo (IServiceInfo * m) pure virtual
Associates the service m with this data set.
Implemented in Arcane::CaseOptions.
References setCaseServiceInfo().
Referenced by setCaseServiceInfo().
subDomain()
virtual ISubDomain * Arcane::ICaseOptions::subDomain () const pure virtual
Associated sub-domain.
Deprecated
Do not use this method because eventually an option may exist without a sub-domain.
Implemented in Arcane::CaseOptions.
References subDomain().
Referenced by subDomain().
translatedName()
virtual String Arcane::ICaseOptions::translatedName (const String & lang) const pure virtual
Name in the language lang of the option. Returns rootTagTrueName() if no translation exists.
Implemented in Arcane::CaseOptions.
visit()
virtual void Arcane::ICaseOptions::visit (ICaseDocumentVisitor * visitor) const pure virtual
Applies the visitor to this option.
Implemented in Arcane::CaseOptionMultiServiceImpl, Arcane::CaseOptions, and Arcane::CaseOptionServiceImpl.
References visit().
Referenced by visit().
xpathFullName()
virtual String Arcane::ICaseOptions::xpathFullName () const pure virtual
Full name in XPath format corresponding to rootElement().
Implemented in Arcane::CaseOptions.
References xpathFullName().
Referenced by xpathFullName().
The documentation for this class was generated from the following file:
ICaseOptions.h