Arcane: Arcane::platform Namespace Reference
Arcane::platform Namespace Reference
Namespace for platform-dependent functions.
Functions
void platformInitialize ()
Platform-specific initialization.
void platformTerminate ()
Platform-specific program termination routines.
IProcessorAffinityService * getProcessorAffinityService ()
Service used for managing processor affinity.
IProcessorAffinityService * setProcessorAffinityService (IProcessorAffinityService *service)
Sets the service used for managing processor affinity.
IProfilingService * getProfilingService ()
Service used to obtain profiling information.
IProfilingService * setProfilingService (IProfilingService *service)
Sets the service used to obtain profiling information.
IOnlineDebuggerService * getOnlineDebuggerService ()
Service used to set up an online debug architecture.
IOnlineDebuggerService * setOnlineDebuggerService (IOnlineDebuggerService *service)
Sets the service to be used for the online debug architecture.
IThreadImplementation * getThreadImplementationService ()
Service used to manage threads.
IThreadImplementation * setThreadImplementationService (IThreadImplementation *service)
Sets the service used to manage threads.
IPerformanceCounterService * setPerformanceCounterService (IPerformanceCounterService *service)
Sets the service used to manage internal processor counters.
IPerformanceCounterService * getPerformanceCounterService ()
Service used to obtain internal processor counters.
void resetAlarmTimer (Integer nb_second)
Resets the alarm timer to nb_second.
bool hasDotNETRuntime ()
True if the code is running with the .NET runtime.
void setHasDotNETRuntime (bool v)
Sets whether the code is running with the .NET runtime.
void callDotNETGarbageCollector ()
Calls the .Net Garbage Collector if available.
IMemoryAllocator * getAcceleratorHostMemoryAllocator ()
Allocator specific to accelerators.
IMemoryAllocator * setAcceleratorHostMemoryAllocator (IMemoryAllocator *a)
Sets the allocator specific to accelerators.
IMemoryAllocator * getDefaultDataAllocator ()
Default allocator for data.
IMemoryRessourceMng * setDataMemoryRessourceMng (IMemoryRessourceMng *mng)
Sets the memory resource manager for data.
IMemoryRessourceMng * getDataMemoryRessourceMng ()
Memory resource manager for data.
bool readAllFile (StringView filename, bool is_binary, ByteArray &out_bytes)
Reads the content of a file and stores it in out_bytes.
bool readAllFile (StringView filename, bool is_binary, Array< std::byte > &out_bytes)
Reads the content of a file and stores it in out_bytes.
String getExeFullPath ()
Returns the full name with the executable path.
void fillCommandLineArguments (StringList &arg_list)
Fills arg_list with command line arguments.
String getGDBStack ()
Retrieves the call stack via gdb.
String getLLDBStack ()
Retrieves the call stack via lldb.
bool createDirectory (const String &dir_name)
Create a directory.
Int64 getCPUTime ()
CPU time used in microseconds.
String getCurrentDate ()
Current date.
String getCurrentDateTime ()
Current date and time in ISO 8601 format.
String getCurrentDirectory ()
Current directory path.
long getCurrentTime ()
Current time.
String getEnvironmentVariable (const String &name)
Environment variable named name.
String getFileDirName (const String &file_name)
Returns the directory name of a file.
long unsigned int getFileLength (const String &filename)
Length of the file filename. If the file is not readable or does not exist, returns 0.
String getHomeDirectory ()
Directory containing user documents.
String getHostName ()
Name of the machine running the process.
double getMemoryUsed ()
Memory used in bytes.
Int64 getPageSize ()
Host system page size in bytes.
int getProcessId ()
Process ID.
Real getRealTime ()
Real time used in seconds.
Int64 getRealTimeNS ()
Clock time in nanoseconds.
String getUserName ()
Username.
bool isDenormalized (Real v)
Returns true if v is denormalized (invalid float).
bool isFileReadable (const String &file_name)
Checks if the file file_name is accessible and readable.
bool recursiveCreateDirectory (const String &dir_name)
Create a directory.
bool removeFile (const String &file_name)
Delete the file file_name.
void safeStringCopy (char *output, Integer output_len, const char *input)
void sleep (Integer nb_second)
Puts the process to sleep for nb_second seconds.
void stdMemcpy (void *to, const void *from, ::size_t len)
Memory block copy.
String timeToHourMinuteSecond (Real t)
Returns time in hours, minutes, and seconds format.
void enableFloatingException (bool active)
Enables or disables exceptions during a floating-point calculation. This operation is not supported on all platforms. If it is not supported, nothing happens.
bool hasFloatingExceptionSupport ()
Indicates if the implementation allows modifying the floating exception activation state.
bool isFloatingExceptionEnabled ()
Indicates if processor floating exceptions are enabled.
void raiseFloatingException ()
Raises a floating exception.
void dumpStackTrace (std::ostream &ostr)
Dumps the call stack to the stream ostr.
String getStackTrace ()
Returns a string containing the call stack.
IStackTraceService * getStackTraceService ()
Service used to obtain the call stack.
ISymbolizerService * getSymbolizerService ()
Service used to obtain information about source code symbols.
IStackTraceService * setStackTraceService (IStackTraceService *service)
Sets the service used to obtain the call stack.
ISymbolizerService * setSymbolizerService (ISymbolizerService *service)
Sets the service to obtain information about source code symbols.
String getCompilerId ()
Character string used to identify the compiler used to compile Arccore.
bool getConsoleHasColor ()
Indicates if the console supports colors.
String getLoadedSharedLibraryFullPath (const String &dll_name)
Returns the full path of a loaded dynamic library.
Variables
IOnlineDebuggerService * global_online_debugger_service = nullptr
IProfilingService * global_profiling_service = nullptr
IProcessorAffinityService * global_processor_affinity_service = nullptr
IPerformanceCounterService * global_performance_counter_service = nullptr
bool global_has_color_console = false
Detailed Description
Namespace for platform-dependent functions.
This namespace contains all platform-dependent functions.
Function Documentation
callDotNETGarbageCollector()
void Arcane::platform::callDotNETGarbageCollector ()
Calls the .Net Garbage Collector if available.
Definition at line 529 of file arcane/src/arcane/utils/PlatformUtils.cc.
createDirectory()
bool Arcane::Platform::createDirectory (const String & dir_name)
Create a directory.
Creates a directory named dir_name. This function assumes that the parent directory already exists.
Return values
true in case of failure,
false in case of success or if the directory already exists.
Definition at line 191 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::Directory::createDirectory().
dumpStackTrace()
void Arcane::Platform::dumpStackTrace (std::ostream & ostr)
Dumps the call stack to the stream ostr.
Definition at line 370 of file arccore/src/base/arccore/base/PlatformUtils.cc.
enableFloatingException()
void Arcane::Platform::enableFloatingException (bool active)
Enables or disables exceptions during a floating-point calculation. This operation is not supported on all platforms. If it is not supported, nothing happens.
Definition at line 338 of file arccore/src/base/arccore/base/PlatformUtils.cc.
fillCommandLineArguments()
void Arcane::platform::fillCommandLineArguments (StringList & arg_list)
Fills arg_list with command line arguments.
This function fills arg_list with the arguments used in the call to main().
Currently, this method only works on Linux. For other platforms, it returns an empty list.
Definition at line 400 of file arcane/src/arcane/utils/PlatformUtils.cc.
References Arcane::Array< T >::addRange(), ARCANE_FATAL, ARCANE_THROW, Arcane::CollectionBase::clear(), Arcane::Array< T >::data(), Arcane::Array< T >::reserve(), and Arcane::AbstractArray< T >::size().
getAcceleratorHostMemoryAllocator()
IMemoryAllocator * Arcane::platform::getAcceleratorHostMemoryAllocator ()
Allocator specific to accelerators.
Deprecated
Use MemoryUtils::getDefaultDataAllocator() instead.
Definition at line 191 of file arcane/src/arcane/utils/PlatformUtils.cc.
References Arcane::MemoryUtils::getAcceleratorHostMemoryAllocator().
getCompilerId()
String Arcane::Platform::getCompilerId ()
Character string used to identify the compiler used to compile Arccore.
Definition at line 386 of file arccore/src/base/arccore/base/PlatformUtils.cc.
References Arcane::String::localstr().
getConsoleHasColor()
bool Arcane::Platform::getConsoleHasColor ()
Indicates if the console supports colors.
Definition at line 376 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getCPUTime()
Int64 Arcane::Platform::getCPUTime ()
CPU time used in microseconds.
The origin of the CPU time is taken when calling platformInitialize().
Returns
the CPU time used in microseconds.
Definition at line 246 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::ModuleMaster::dumpStandardCurves(), and Arcane::ModuleMaster::timeLoopBegin().
getCurrentDate()
String Arcane::Platform::getCurrentDate ()
Current date.
The string is returned in the format day/month/year.
Definition at line 86 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getCurrentDateTime()
String Arcane::Platform::getCurrentDateTime ()
Current date and time in ISO 8601 format.
The string is returned in the format YYYY-MM-DDTHH:MM:SS.
Definition at line 118 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::MessagePassing::dumpDateAndMemoryUsage(), Arcane::ModuleMaster::dumpStandardCurves(), and Arcane::ModuleMaster::timeLoopBegin().
getCurrentDirectory()
String Arcane::Platform::getCurrentDirectory ()
Current directory path.
Definition at line 130 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getCurrentTime()
long Arcane::Platform::getCurrentTime ()
Current time.
Returns the current date, expressed in seconds elapsed since January 1, 1970.
Definition at line 98 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getDataMemoryRessourceMng()
IMemoryRessourceMng * Arcane::platform::getDataMemoryRessourceMng ()
Memory resource manager for data.
It is guaranteed that the alignment is at least that returned by AlignedMemoryAllocator::Simd().
Deprecated
This method is internal to Arcane. Use methods from MemoryUtils instead.
Definition at line 227 of file arcane/src/arcane/utils/PlatformUtils.cc.
getDefaultDataAllocator()
IMemoryAllocator * Arcane::platform::getDefaultDataAllocator ()
Default allocator for data.
This allocator uses the one returned by getAcceleratorHostMemoryAllocator() if available; otherwise, it uses an aligned allocator.
It is guaranteed that the returned allocator will allow the data to be used on the accelerator if available.
It is guaranteed that the alignment is at least that returned by AlignedMemoryAllocator::Simd().
Definition at line 209 of file arcane/src/arcane/utils/PlatformUtils.cc.
References Arcane::MemoryUtils::getDefaultDataAllocator().
getEnvironmentVariable()
String Arcane::Platform::getEnvironmentVariable (const String & name)
Environment variable named name.
If no variable named name is defined, an empty string is returned.
Definition at line 167 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::IPostProcessorWriter::setMesh().
getExeFullPath()
String Arcane::platform::getExeFullPath ()
Returns the full name with the executable path.
Definition at line 368 of file arcane/src/arcane/utils/PlatformUtils.cc.
Referenced by Arcane::ArcaneLauncher::getExeDirectory().
getFileDirName()
String Arcane::Platform::getFileDirName (const String & file_name)
Returns the directory name of a file.
Returns the directory name where the file named file_name is located. For example, if file_name is "/tmp/toto.cc", it returns "/tmp". If the file does not contain directories, it returns ".".
Definition at line 220 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::dom::DOMImplementation::_load(), and Arcane::ArcaneLauncher::getExeDirectory().
getFileLength()
long unsigned int Arcane::Platform::getFileLength (const String & filename)
Length of the file filename. If the file is not readable or does not exist, returns 0.
Definition at line 158 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getGDBStack()
String Arcane::platform::getGDBStack ()
Retrieves the call stack via gdb.
This method only works on Linux and if GDB is installed. In other cases, the null string is returned.
This method calls the std::system() command to launch gdb, which must be in the PATH. Since gdb then loads the debug symbols, the command can take a long time to execute.
Definition at line 480 of file arcane/src/arcane/utils/PlatformUtils.cc.
getHomeDirectory()
String Arcane::Platform::getHomeDirectory ()
Directory containing user documents.
This corresponds to the HOME environment variable on Unix, or the 'My Documents' directory under Win32.
Definition at line 151 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getHostName()
String Arcane::Platform::getHostName ()
Name of the machine running the process.
Definition at line 124 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getLLDBStack()
String Arcane::platform::getLLDBStack ()
Retrieves the call stack via lldb.
This method is similar to getGDBStack() but uses 'lldb' to retrieve the call stack. If dotnet-sos is installed, it also allows retrieving information about 'dotnet' runtime methods.
Definition at line 499 of file arcane/src/arcane/utils/PlatformUtils.cc.
getLoadedSharedLibraryFullPath()
String Arcane::Platform::getLoadedSharedLibraryFullPath (const String & dll_name)
Returns the full path of a loaded dynamic library.
Returns the full path of the dynamic library named dll_name. dll_name must only contain the library name without platform-specific extensions. For example, on Linux, do not use 'libtoto.so' but just 'toto'.
Returns a null string if the full path cannot be determined.
Definition at line 412 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getMemoryUsed()
double Arcane::Platform::getMemoryUsed ()
Memory used in bytes.
Returns
the memory used or a negative number if unknown
Definition at line 236 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::MessagePassing::dumpDateAndMemoryUsage(), Arcane::ModuleMaster::dumpStandardCurves(), and Arcane::ModuleMaster::timeLoopBegin().
getOnlineDebuggerService()
IOnlineDebuggerService * Arcane::platform::getOnlineDebuggerService ()
Service used to set up an online debug architecture.
May return null if no service is available.
Definition at line 111 of file arcane/src/arcane/utils/PlatformUtils.cc.
Referenced by Arcane::ModuleMaster::timeLoopBegin().
getPageSize()
Int64 Arcane::Platform::getPageSize ()
Host system page size in bytes.
Definition at line 395 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getPerformanceCounterService()
IPerformanceCounterService * Arcane::platform::getPerformanceCounterService ()
Service used to obtain internal processor counters.
May return null if no service is available.
Definition at line 171 of file arcane/src/arcane/utils/PlatformUtils.cc.
getProcessId()
int Arcane::Platform::getProcessId ()
Process ID.
Definition at line 136 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::CodeService::initCase().
getProcessorAffinityService()
IProcessorAffinityService * Arcane::platform::getProcessorAffinityService ()
Service used for managing processor affinity.
May return null if no service is available.
Definition at line 151 of file arcane/src/arcane/utils/PlatformUtils.cc.
getProfilingService()
IProfilingService * Arcane::platform::getProfilingService ()
Service used to obtain profiling information.
May return null if no service is available.
Definition at line 131 of file arcane/src/arcane/utils/PlatformUtils.cc.
Referenced by Arcane::CodeService::initCase().
getRealTime()
Real Arcane::Platform::getRealTime ()
Real time used in seconds.
Returns
the time used in seconds.
Definition at line 254 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by Arcane::ModuleMaster::dumpStandardCurves(), and Arcane::ModuleMaster::timeLoopBegin().
getRealTimeNS()
Int64 Arcane::Platform::getRealTimeNS ()
Clock time in nanoseconds.
Definition at line 107 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getStackTrace()
String Arcane::Platform::getStackTrace ()
Returns a string containing the call stack.
If no call stack management service is present (getStackTraceService()==0), the returned string is null.
Definition at line 297 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getStackTraceService()
IStackTraceService * Arcane::Platform::getStackTraceService ()
Service used to obtain the call stack.
May return null if no service is available.
Definition at line 280 of file arccore/src/base/arccore/base/PlatformUtils.cc.
getSymbolizerService()
ISymbolizerService * Arcane::Platform::getSymbolizerService ()
Service used to obtain information about source code symbols.
May return null if no service is available.
Definition at line 306 of file arccore/src/base/arccore/base/PlatformUtils.cc.
References recursiveCreateDirectory().
getThreadImplementationService()
IThreadImplementation * Arcane::platform::getThreadImplementationService ()
Service used to manage threads.
May return null if no service is available.
Definition at line 236 of file arcane/src/arcane/utils/PlatformUtils.cc.
Referenced by Arcane::arcaneCurrentThread().
getUserName()
String Arcane::Platform::getUserName ()
Username.
Definition at line 142 of file arccore/src/base/arccore/base/PlatformUtils.cc.
hasDotNETRuntime()
bool Arcane::platform::hasDotNETRuntime ()
True if the code is running with the .NET runtime.
Definition at line 353 of file arcane/src/arcane/utils/PlatformUtils.cc.
Referenced by Arcane::EntryPoint::executeEntryPoint().
hasFloatingExceptionSupport()
bool Arcane::Platform::hasFloatingExceptionSupport ()
Indicates if the implementation allows modifying the floating exception activation state.
If this method returns false, then the methods enableFloatingException() and isFloatingExceptionEnabled() have no effect.
Definition at line 364 of file arccore/src/base/arccore/base/PlatformUtils.cc.
isDenormalized()
bool Arcane::Platform::isDenormalized (Real v)
Returns true if v is denormalized (invalid float).
If the platform does not support this concept, it always returns false.
Definition at line 272 of file arccore/src/base/arccore/base/PlatformUtils.cc.
isFileReadable()
bool Arcane::Platform::isFileReadable (const String & file_name)
Checks if the file file_name is accessible and readable.
Return values
true if the file is readable,
false otherwise.
Definition at line 209 of file arccore/src/base/arccore/base/PlatformUtils.cc.
isFloatingExceptionEnabled()
bool Arcane::Platform::isFloatingExceptionEnabled ()
Indicates if processor floating exceptions are enabled.
Definition at line 342 of file arccore/src/base/arccore/base/PlatformUtils.cc.
platformInitialize()
void Arcane::platform::platformInitialize ()
Platform-specific initialization.
This routine is called when the architecture is initialized. It allows certain platform-dependent processes to be performed.
Definition at line 276 of file arcane/src/arcane/utils/PlatformUtils.cc.
References Arcane::Platform::platformInitialize().
platformTerminate()
void Arcane::platform::platformTerminate ()
Platform-specific program termination routines.
This routine is called just before exiting the program.
Definition at line 285 of file arcane/src/arcane/utils/PlatformUtils.cc.
References Arcane::Platform::platformTerminate().
raiseFloatingException()
void Arcane::Platform::raiseFloatingException ()
Raises a floating exception.
This method does nothing if hasFloatingExceptionSupport()==false. Generally under Linux, this translates to sending a signal of type SIGFPE. By default, Arccore catches this signal and raises an 'ArithmeticException'.
Definition at line 353 of file arccore/src/base/arccore/base/PlatformUtils.cc.
References Arcane::String::length(), and Arcane::String::localstr().
readAllFile() [1/2]
bool Arcane::platform::readAllFile (StringView filename, bool is_binary, Array< std::byte > & out_bytes)
Reads the content of a file and stores it in out_bytes.
Reads the file named filename and fills out_bytes with the content of this file. If is_binary is true, the file is opened in binary mode. Otherwise, it is opened in text mode.
Return values
true in case of error
false otherwise.
Definition at line 343 of file arcane/src/arcane/utils/PlatformUtils.cc.
readAllFile() [2/2]
bool Arcane::platform::readAllFile (StringView filename, bool is_binary, ByteArray & out_bytes)
Reads the content of a file and stores it in out_bytes.
Reads the file named filename and fills out_bytes with the content of this file. If is_binary is true, the file is opened in binary mode. Otherwise, it is opened in text mode.
Return values
true in case of error
false otherwise.
Definition at line 334 of file arcane/src/arcane/utils/PlatformUtils.cc.
recursiveCreateDirectory()
bool Arcane::Platform::recursiveCreateDirectory (const String & dir_name)
Create a directory.
Creates the directory named dir_name. If necessary, creates the required parent directories.
Return values
true in case of failure,
false in case of success or if the directory already exists.
Definition at line 179 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Referenced by getSymbolizerService().
removeFile()
bool Arcane::Platform::removeFile (const String & file_name)
Delete the file file_name.
Return values
true in case of failure,
false in case of success or if the file does not exist.
Definition at line 200 of file arccore/src/base/arccore/base/PlatformUtils.cc.
resetAlarmTimer()
void Arcane::platform::resetAlarmTimer (Integer nb_second)
Resets the alarm timer to nb_second.
The timer will trigger a signal (SIGALRM) after nb_second.
Definition at line 254 of file arcane/src/arcane/utils/PlatformUtils.cc.
safeStringCopy()
void Arcane::Platform::safeStringCopy (char * output, Integer output_len, const char * input)
Definition at line 325 of file arccore/src/base/arccore/base/PlatformUtils.cc.
setAcceleratorHostMemoryAllocator()
IMemoryAllocator * Arcane::platform::setAcceleratorHostMemoryAllocator (IMemoryAllocator * a)
Sets the allocator specific to accelerators.
Returns the previously used allocator. The specified allocator must remain valid throughout the application's lifetime.
Deprecated
This method is internal to Arcane.
Definition at line 200 of file arcane/src/arcane/utils/PlatformUtils.cc.
setDataMemoryRessourceMng()
IMemoryRessourceMng * Arcane::platform::setDataMemoryRessourceMng (IMemoryRessourceMng * mng)
Sets the memory resource manager for data.
The manager must remain valid throughout the program's execution.
Returns the previously used manager.
Deprecated
This method is internal to Arcane.
Definition at line 218 of file arcane/src/arcane/utils/PlatformUtils.cc.
setHasDotNETRuntime()
void Arcane::platform::setHasDotNETRuntime (bool v)
Sets whether the code is running with the .NET runtime.
This function can only be set at the start of the calculation before arcaneInitialize().
Definition at line 359 of file arcane/src/arcane/utils/PlatformUtils.cc.
setOnlineDebuggerService()
IOnlineDebuggerService * Arcane::platform::setOnlineDebuggerService (IOnlineDebuggerService * service)
Sets the service to be used for the online debug architecture.
Returns the previously used service.
Definition at line 120 of file arcane/src/arcane/utils/PlatformUtils.cc.
setPerformanceCounterService()
IPerformanceCounterService * Arcane::platform::setPerformanceCounterService (IPerformanceCounterService * service)
Sets the service used to manage internal processor counters.
Returns the previously used service.
Definition at line 180 of file arcane/src/arcane/utils/PlatformUtils.cc.
setProcessorAffinityService()
IProcessorAffinityService * Arcane::platform::setProcessorAffinityService (IProcessorAffinityService * service)
Sets the service used for managing processor affinity.
Returns the previously used service.
Definition at line 160 of file arcane/src/arcane/utils/PlatformUtils.cc.
setProfilingService()
IProfilingService * Arcane::platform::setProfilingService (IProfilingService * service)
Sets the service used to obtain profiling information.
Returns the previously used service.
Definition at line 140 of file arcane/src/arcane/utils/PlatformUtils.cc.
setStackTraceService()
IStackTraceService * Arcane::Platform::setStackTraceService (IStackTraceService * service)
Sets the service used to obtain the call stack.
Returns the previously used service.
Definition at line 288 of file arccore/src/base/arccore/base/PlatformUtils.cc.
setSymbolizerService()
ISymbolizerService * Arcane::Platform::setSymbolizerService (ISymbolizerService * service)
Sets the service to obtain information about source code symbols.
Returns the previously used service.
Definition at line 315 of file arccore/src/base/arccore/base/PlatformUtils.cc.
setThreadImplementationService()
IThreadImplementation * Arcane::platform::setThreadImplementationService (IThreadImplementation * service)
Sets the service used to manage threads.
Returns the previously used service.
Definition at line 245 of file arcane/src/arcane/utils/PlatformUtils.cc.
sleep()
void Arcane::Platform::sleep (Integer nb_second)
Puts the process to sleep for nb_second seconds.
Definition at line 331 of file arccore/src/base/arccore/base/PlatformUtils.cc.
stdMemcpy()
void Arcane::Platform::stdMemcpy (void * to, const void * from, ::size_t len)
Memory block copy.
Copies len bytes from address from to address to.
Definition at line 228 of file arccore/src/base/arccore/base/PlatformUtils.cc.
timeToHourMinuteSecond()
String Arcane::Platform::timeToHourMinuteSecond (Real t)
Returns time in hours, minutes, and seconds format.
Converts t, expressed in seconds, into the format AhBmCs where A is hours, B is minutes, and C is seconds. For example, 3732 becomes 1h2m12s.
Definition at line 264 of file arccore/src/base/arccore/base/PlatformUtils.cc.
Variable Documentation
global_has_color_console
bool Arcane::platform::global_has_color_console = false
Definition at line 105 of file arcane/src/arcane/utils/PlatformUtils.cc.
global_online_debugger_service
IOnlineDebuggerService* Arcane::platform::global_online_debugger_service = nullptr
Definition at line 101 of file arcane/src/arcane/utils/PlatformUtils.cc.
global_performance_counter_service
IPerformanceCounterService* Arcane::platform::global_performance_counter_service = nullptr
Definition at line 104 of file arcane/src/arcane/utils/PlatformUtils.cc.
global_processor_affinity_service
IProcessorAffinityService* Arcane::platform::global_processor_affinity_service = nullptr
Definition at line 103 of file arcane/src/arcane/utils/PlatformUtils.cc.
global_profiling_service
IProfilingService* Arcane::platform::global_profiling_service = nullptr
Definition at line 102 of file arcane/src/arcane/utils/PlatformUtils.cc.