Arcane: Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList Class Reference
Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList Class Reference
Singleton containing the instances of the copy functions on accelerators.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/accelerator/arccore/accelerator/internal/AcceleratorMemoryCopier.h>
Public Member Functions
void addExplicitTemplate1 ()
void addExplicitTemplate2 ()
void addExplicitTemplate3 ()
void addExplicitTemplate4 ()
Public Member Functions inherited from Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >
void addCopier ()
Adds a specific copier.
void printStats ()
void checkValid ()
void copyTo (Int32 datatype_size, const IndexedMemoryCopyArgs &args) override
void copyFrom (Int32 datatype_size, const IndexedMemoryCopyArgs &args) override
void fill (Int32 datatype_size, const IndexedMemoryCopyArgs &args) override
Public Member Functions inherited from Arcane::Impl::ISpecificMemoryCopyList
virtual void copyTo (Int32 datatype_size, const IndexedMultiMemoryCopyArgs &args)=0
virtual void copyFrom (Int32 datatype_size, const IndexedMultiMemoryCopyArgs &args)=0
virtual void fill (Int32 datatype_size, const IndexedMultiMemoryCopyArgs &args)=0
Additional Inherited Members
Public Types inherited from Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >
using InterfaceType
using SpecificType
using RefType
Static Public Attributes inherited from Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >
static constexpr Int32 NB_COPIER
Detailed Description
Singleton containing the instances of the copy functions on accelerators.
Definition at line 334 of file AcceleratorMemoryCopier.h.
Constructor & Destructor Documentation
AcceleratorSpecificMemoryCopyList()
Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList::AcceleratorSpecificMemoryCopyList ()
Definition at line 33 of file MemoryCopier.cc.
Member Function Documentation
addExplicitTemplate1()
void Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList::addExplicitTemplate1 ()
Adds specific implementations for the first common sizes
Definition at line 22 of file MemoryCopierTpl1.cc.
References Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >::addCopier().
addExplicitTemplate2()
void Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList::addExplicitTemplate2 ()
Adds specific implementations for the first common sizes
Definition at line 25 of file MemoryCopierTpl2.cc.
References Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >::addCopier().
addExplicitTemplate3()
void Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList::addExplicitTemplate3 ()
Adds specific implementations for the first common sizes
Definition at line 22 of file MemoryCopierTpl3.cc.
References Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >::addCopier().
addExplicitTemplate4()
void Arcane::Accelerator::Impl::AcceleratorSpecificMemoryCopyList::addExplicitTemplate4 ()
Adds specific implementations for the first common sizes
Definition at line 22 of file MemoryCopierTpl4.cc.
References Arcane::Impl::SpecificMemoryCopyList< AcceleratorIndexedCopyTraits >::addCopier().
The documentation for this class was generated from the following files:
AcceleratorMemoryCopier.h
MemoryCopier.cc
MemoryCopierTpl1.cc
MemoryCopierTpl2.cc
MemoryCopierTpl3.cc
MemoryCopierTpl4.cc