Arcane: Arcane::ModuleBuildInfo Class Reference
Arcane::ModuleBuildInfo Class Reference
Module
Information for building a module.
#include <arcane/core/ModuleBuildInfo.h>
Public Member Functions
ModuleBuildInfo (ISubDomain *sd, IMesh *mesh, const String &name)
Constructor from a subdomain, a mesh, and a module implementation name.
ModuleBuildInfo (ISubDomain *sd, const MeshHandle &mesh_handle, const String &name)
Constructor from a subdomain, a mesh, and a module implementation name.
ModuleBuildInfo (ISubDomain *sd, const String &name)
Constructor from a subdomain and a module implementation name.
virtual ~ModuleBuildInfo ()
Destructor.
ISubDomain * subDomain () const
Access to the associated subdomain.
const MeshHandle & meshHandle () const
Access to the associated mesh.
const String & name () const
Name of the implementation sought.
IMesh * mesh () const
Access to the associated mesh.
Private Attributes
ISubDomain * m_sub_domain
Associated subdomain.
MeshHandle m_mesh_handle
Associated mesh.
String m_name
Name of the implementation sought.
Detailed Description
Information for building a module.
ModuleBuildInfo is usually used via BasicModule (basic module) and AbstractModule (any module) for the creation of different modules.
Definition at line 38 of file ModuleBuildInfo.h.
Constructor & Destructor Documentation
ModuleBuildInfo() [1/3]
Arcane::ModuleBuildInfo::ModuleBuildInfo (ISubDomain * sd, IMesh * mesh, const String & name)
Constructor from a subdomain, a mesh, and a module implementation name.
Deprecated
Use the overload that takes a MeshHandle instead.
Definition at line 29 of file ModuleBuildInfo.cc.
References m_mesh_handle, m_name, m_sub_domain, mesh(), and name().
ModuleBuildInfo() [2/3]
Arcane::ModuleBuildInfo::ModuleBuildInfo (ISubDomain * sd, const MeshHandle & mesh_handle, const String & name)
Constructor from a subdomain, a mesh, and a module implementation name.
Definition at line 40 of file ModuleBuildInfo.cc.
References m_mesh_handle, m_name, m_sub_domain, and name().
ModuleBuildInfo() [3/3]
Arcane::ModuleBuildInfo::ModuleBuildInfo (ISubDomain * sd, const String & name)
Constructor from a subdomain and a module implementation name.
The mesh considered is then the default mesh ISubDomain::defautMesh()
Definition at line 51 of file ModuleBuildInfo.cc.
References m_mesh_handle, m_name, m_sub_domain, and name().
~ModuleBuildInfo()
virtual Arcane::ModuleBuildInfo::~ModuleBuildInfo () inline virtual
Destructor.
Definition at line 64 of file ModuleBuildInfo.h.
Member Function Documentation
mesh()
IMesh * Arcane::ModuleBuildInfo::mesh () const inline
Access to the associated mesh.
The mesh does not always exist if the dataset has not been read yet.
Deprecated
You must use meshHandle() instead.
Definition at line 87 of file ModuleBuildInfo.h.
References m_mesh_handle.
Referenced by ModuleBuildInfo().
meshHandle()
const MeshHandle & Arcane::ModuleBuildInfo::meshHandle () const inline
Access to the associated mesh.
Definition at line 72 of file ModuleBuildInfo.h.
References m_mesh_handle.
name()
const String & Arcane::ModuleBuildInfo::name () const inline
Name of the implementation sought.
Definition at line 75 of file ModuleBuildInfo.h.
References m_name.
Referenced by ModuleBuildInfo(), ModuleBuildInfo(), and ModuleBuildInfo().
subDomain()
ISubDomain * Arcane::ModuleBuildInfo::subDomain () const inline
Access to the associated subdomain.
Definition at line 69 of file ModuleBuildInfo.h.
References m_sub_domain.
Referenced by Arcane::ModuleMaster::ModuleMaster().
Member Data Documentation
m_mesh_handle
MeshHandle Arcane::ModuleBuildInfo::m_mesh_handle private
Associated mesh.
Definition at line 95 of file ModuleBuildInfo.h.
Referenced by mesh(), meshHandle(), ModuleBuildInfo(), ModuleBuildInfo(), and ModuleBuildInfo().
m_name
String Arcane::ModuleBuildInfo::m_name private
Name of the implementation sought.
Definition at line 98 of file ModuleBuildInfo.h.
Referenced by ModuleBuildInfo(), ModuleBuildInfo(), ModuleBuildInfo(), and name().
m_sub_domain
ISubDomain* Arcane::ModuleBuildInfo::m_sub_domain private
Associated subdomain.
Definition at line 92 of file ModuleBuildInfo.h.
Referenced by ModuleBuildInfo(), ModuleBuildInfo(), ModuleBuildInfo(), and subDomain().
The documentation for this class was generated from the following files:
ModuleBuildInfo.h
ModuleBuildInfo.cc