Arcane: Arcane::Internal::ServiceAllInterfaceRegisterer< ServiceType > Class Template Reference
Arcane::Internal::ServiceAllInterfaceRegisterer< ServiceType > Class Template Reference
Class allowing the creation and registration of factories for a service.
#include <arcane/core/ServiceFactory.h>
Static Public Member Functions
template<typename... Interfaces>
static void registerToServiceInfo (ServiceInfo *si, const Interfaces &... args)
Registers the factories for the Interfaces interfaces in the service.
Static Private Member Functions
template<typename InterfaceType>
static void _create (ServiceInfo *si, const InterfaceType &i1)
Overload for 1 interface.
template<typename I1, typename I2, typename... OtherInterfaces>
static void _create (ServiceInfo *si, const I1 &i1, const I2 &i2, const OtherInterfaces &... args)
Overload for 2 or more interfaces.
Detailed Description
template<typename ServiceType>
class Arcane::Internal::ServiceAllInterfaceRegisterer< ServiceType >
Class allowing the creation and registration of factories for a service.
Definition at line 482 of file ServiceFactory.h.
Member Function Documentation
_create() [1/2]
template<typename ServiceType> template<typename I1, typename I2, typename... OtherInterfaces> void Arcane::Internal::ServiceAllInterfaceRegisterer< ServiceType >::_create (ServiceInfo * si, const I1 & i1, const I2 & i2, const OtherInterfaces &... args) inline static private
Overload for 2 or more interfaces.
Definition at line 494 of file ServiceFactory.h.
References _create().
_create() [2/2]
template<typename ServiceType> template<typename InterfaceType> void Arcane::Internal::ServiceAllInterfaceRegisterer< ServiceType >::_create (ServiceInfo * si, const InterfaceType & i1) inline static private
Overload for 1 interface.
Definition at line 488 of file ServiceFactory.h.
References registerToServiceInfo().
Referenced by _create(), and registerToServiceInfo().
registerToServiceInfo()
template<typename ServiceType> template<typename... Interfaces> void Arcane::Internal::ServiceAllInterfaceRegisterer< ServiceType >::registerToServiceInfo (ServiceInfo * si, const Interfaces &... args) inline static
Registers the factories for the Interfaces interfaces in the service.
Definition at line 505 of file ServiceFactory.h.
References _create().
Referenced by _create().
The documentation for this class was generated from the following files:
ArcaneTypes.h
ServiceFactory.h