Arcane: Arcane::GeometricUtilities::ProjectionInfo Class Reference
Arcane::GeometricUtilities::ProjectionInfo Class Reference
Public Member Functions
ProjectionInfo (Real distance, int region, Real alpha, Real beta, Real3 aprojection)
Static Public Member Functions
static ProjectionInfo projection (Real3 v1, Real3 v2, Real3 v3, Real3 point)
Projection of point point onto the triangle defined by v1, v2 and v3.
static ProjectionInfo projection (Real3 v1, Real3 v2, Real3 point)
Projection of point point onto the segment defined by v1, v2.
static bool isInside (Real3 v1, Real3 v2, Real3 v3, Real3 point)
Indicates if the projection of point point is inside the triangle defined by v1, v2 and v3.
static bool isInside (Real3 v1, Real3 v2, Real3 point)
Indicates if the projection of point point is inside the segment defined by v1 and v2.
Public Attributes
Real m_distance = FloatInfo<Real>::maxValue()
Distance of the point to its projection.
int m_region = -1
Region where the projection is located (0 if inside the segment or triangle).
Real m_alpha = -1.0
Barycentric x-coordinate of the projection.
Real m_beta = -1.0
Barycentric y-coordinate of the projection.
Real3 m_projection
Position of the projection.
Detailed Description
Definition at line 98 of file GeometricUtilities.h.
Constructor & Destructor Documentation
ProjectionInfo()
Arcane::GeometricUtilities::ProjectionInfo::ProjectionInfo (Real distance, int region, Real alpha, Real beta, Real3 aprojection) inline
Definition at line 102 of file GeometricUtilities.h.
Member Function Documentation
isInside() [1/2]
bool Arcane::GeometricUtilities::ProjectionInfo::isInside (Real3 v1, Real3 v2, Real3 point) static
Indicates if the projection of point point is inside the segment defined by v1 and v2.
Definition at line 715 of file GeometricUtilities.cc.
References Arcane::math::dot(), and Arcane::Real3::squareNormL2().
isInside() [2/2]
bool Arcane::GeometricUtilities::ProjectionInfo::isInside (Real3 v1, Real3 v2, Real3 v3, Real3 point) static
Indicates if the projection of point point is inside the triangle defined by v1, v2 and v3.
Definition at line 681 of file GeometricUtilities.cc.
References Arcane::math::dot(), and Arcane::Real3::squareNormL2().
projection() [1/2]
GeometricUtilities::ProjectionInfo Arcane::GeometricUtilities::ProjectionInfo::projection (Real3 v1, Real3 v2, Real3 point) static
Projection of point point onto the segment defined by v1, v2.
Definition at line 645 of file GeometricUtilities.cc.
References Arcane::math::dot(), projection(), and Arcane::Real3::squareNormL2().
projection() [2/2]
GeometricUtilities::ProjectionInfo Arcane::GeometricUtilities::ProjectionInfo::projection (Real3 v1, Real3 v2, Real3 v3, Real3 point) static
Projection of point point onto the triangle defined by v1, v2 and v3.
Definition at line 446 of file GeometricUtilities.cc.
References Arcane::math::dot(), projection(), and Arcane::Real3::squareNormL2().
Referenced by projection(), and projection().
Member Data Documentation
m_alpha
Real Arcane::GeometricUtilities::ProjectionInfo::m_alpha = -1.0
Barycentric x-coordinate of the projection.
Definition at line 118 of file GeometricUtilities.h.
m_beta
Real Arcane::GeometricUtilities::ProjectionInfo::m_beta = -1.0
Barycentric y-coordinate of the projection.
Definition at line 120 of file GeometricUtilities.h.
m_distance
Real Arcane::GeometricUtilities::ProjectionInfo::m_distance = FloatInfo<Real>::maxValue()
Distance of the point to its projection.
Definition at line 114 of file GeometricUtilities.h.
m_projection
Real3 Arcane::GeometricUtilities::ProjectionInfo::m_projection
Position of the projection.
Definition at line 122 of file GeometricUtilities.h.
m_region
int Arcane::GeometricUtilities::ProjectionInfo::m_region = -1
Region where the projection is located (0 if inside the segment or triangle).
Definition at line 116 of file GeometricUtilities.h.
The documentation for this class was generated from the following files:
GeometricUtilities.h
GeometricUtilities.cc