Arcane: Arcane::IMainFactory Class Reference
Arcane::IMainFactory Class Reference abstract
Public Member Functions
virtual ~IMainFactory ()
Releases resources.
virtual IArcaneMain * createArcaneMain (const ApplicationInfo &app_info)=0
Creates an instance of IArcaneMain.
virtual IApplication * createApplication (IArcaneMain *)=0
Creates an instance of a supervisor.
virtual IVariableMng * createVariableMng (ISubDomain *)=0
Creates an instance of the variable manager.
virtual IModuleMng * createModuleMng (ISubDomain *)=0
Creates an instance of the module manager.
virtual IEntryPointMng * createEntryPointMng (ISubDomain *)=0
Creates an instance of the entry point manager.
virtual ITimeHistoryMng * createTimeHistoryMng (ISubDomain *)=0
Creates an instance of the time history manager.
virtual ICaseMng * createCaseMng (ISubDomain *)=0
Creates an instance of the case manager.
virtual ICaseDocument * createCaseDocument (IApplication *)=0
Creates an instance of a case document.
virtual ICaseDocument * createCaseDocument (IApplication *, const String &lang)=0
Creates an instance of a case document for a given language lang.
virtual ICaseDocument * createCaseDocument (IApplication *, IXmlDocumentHolder *doc)=0
Creates an instance of a case document.
virtual ARCANE_DEPRECATED_116 ITimeStats * createTimeStats (ISubDomain *)=0
Creates an instance of execution time statistics.
virtual ITimeStats * createTimeStats (ITimerMng *tim, ITraceMng *trm, const String &name)=0
Creates an instance of execution time statistics.
virtual ITimeLoopMng * createTimeLoopMng (ISubDomain *)=0
Creates an instance of the time loop manager.
virtual ITimeLoop * createTimeLoop (IApplication *sm, const String &name)=0
Creates a time loop named name.
virtual IIOMng * createIOMng (IApplication *)=0
Creates an instance of the I/O manager.
virtual IIOMng * createIOMng (IParallelMng *pm)=0
Creates an instance of the I/O manager for the parallelism manager pm.
virtual IServiceLoader * createServiceLoader ()=0
Creates an instance of the service loader.
virtual IServiceMng * createServiceMng (IBase *)=0
Creates an instance of the service manager.
virtual ICheckpointMng * createCheckpointMng (ISubDomain *)=0
Creates an instance of the checkpoint manager.
virtual IPropertyMng * createPropertyMng (ISubDomain *)=0
Creates an instance of the property manager.
virtual Ref< IPropertyMng > createPropertyMngReference (ISubDomain *)=0
Creates an instance of the property manager.
virtual IPrimaryMesh * createMesh (ISubDomain *sub_domain, const String &name)=0
Creates or retrieves a mesh.
virtual IPrimaryMesh * createMesh (ISubDomain *sub_domain, const String &name, bool is_amr)=0
Creates or retrieves a mesh.
virtual IPrimaryMesh * createMesh (ISubDomain *sub_domain, const String &name, eMeshAMRKind amr_type)=0
Creates or retrieves a mesh.
virtual IPrimaryMesh * createMesh (ISubDomain *sub_domain, IParallelMng *pm, const String &name)=0
Creates or retrieves a mesh.
virtual IPrimaryMesh * createMesh (ISubDomain *sub_domain, IParallelMng *pm, const String &name, bool is_amr)=0
Creates or retrieves a mesh.
virtual IPrimaryMesh * createMesh (ISubDomain *sub_domain, IParallelMng *pm, const String &name, eMeshAMRKind amr_type)=0
Creates or retrieves a mesh.
virtual IMesh * createSubMesh (IMesh *mesh, const ItemGroup &group, const String &name)=0
Creates a sub-mesh for the mesh mesh, named name.
virtual IDataFactory * createDataFactory (IApplication *)=0
Creates a factory for data.
virtual Ref< IDataFactoryMng > createDataFactoryMngRef (IApplication *)=0
Creates a factory manager for data.
virtual Ref< IAcceleratorMng > createAcceleratorMngRef (ITraceMng *tm)=0
Creates a manager for accelerators.
virtual ITraceMng * createTraceMng ()=0
Creates a trace manager.
virtual ITraceMngPolicy * createTraceMngPolicy (IApplication *app)=0
Creates a configuration manager for a trace manager.
virtual IModuleMaster * createModuleMaster (ISubDomain *sd)=0
Creates the master module for the sub-domain sd.
virtual ILoadBalanceMng * createLoadBalanceMng (ISubDomain *sd)=0
Creates a description manager for load balancing.
Detailed Description
Definition at line 93 of file IMainFactory.h.
Constructor & Destructor Documentation
~IMainFactory()
virtual Arcane::IMainFactory::~IMainFactory () inline virtual
Releases resources.
Definition at line 97 of file IMainFactory.h.
Member Function Documentation
createMesh() [1/6]
virtual IPrimaryMesh * Arcane::IMainFactory::createMesh (ISubDomain * sub_domain, const String & name) pure virtual
Creates or retrieves a mesh.
Creates or retrieves a mesh named name for the sub-domain sub_domain.
If the sub-domain already has a mesh with the name name, the latter is returned.
References createMesh().
Referenced by createMesh(), createMesh(), createMesh(), createMesh(), createMesh(), createMesh(), and Arcane::MeshReaderMng::readMesh().
createMesh() [2/6]
virtual IPrimaryMesh * Arcane::IMainFactory::createMesh (ISubDomain * sub_domain, const String & name, bool is_amr) pure virtual
Creates or retrieves a mesh.
Creates or retrieves a mesh named name for the sub-domain sub_domain.
If the sub-domain already has a mesh with the name name, the latter is returned.
References createMesh().
createMesh() [3/6]
virtual IPrimaryMesh * Arcane::IMainFactory::createMesh (ISubDomain * sub_domain, const String & name, eMeshAMRKind amr_type) pure virtual
Creates or retrieves a mesh.
Creates or retrieves a mesh named name for the sub-domain sub_domain.
If the sub-domain already has a mesh with the name name, the latter is returned.
References createMesh().
createMesh() [4/6]
virtual IPrimaryMesh * Arcane::IMainFactory::createMesh (ISubDomain * sub_domain, IParallelMng * pm, const String & name) pure virtual
Creates or retrieves a mesh.
Creates or retrieves a mesh named name for the sub-domain sub_domain associated with the parallelism manager pm. If the sub-domain already has a mesh with the name name, the latter is returned.
The parallelism manager must be the same as that of the sub-domain or derived from it.
References createMesh().
createMesh() [5/6]
virtual IPrimaryMesh * Arcane::IMainFactory::createMesh (ISubDomain * sub_domain, IParallelMng * pm, const String & name, bool is_amr) pure virtual
Creates or retrieves a mesh.
Creates or retrieves a mesh named name for the sub-domain sub_domain associated with the parallelism manager pm. If the sub-domain already has a mesh with the name name, the latter is returned.
The parallelism manager must be the same as that of the sub-domain or derived from it.
References createMesh().
createMesh() [6/6]
virtual IPrimaryMesh * Arcane::IMainFactory::createMesh (ISubDomain * sub_domain, IParallelMng * pm, const String & name, eMeshAMRKind amr_type) pure virtual
Creates or retrieves a mesh.
Creates or retrieves a mesh named name for the sub-domain sub_domain associated with the parallelism manager pm. If the sub-domain already has a mesh with the name name, the latter is returned.
The parallelism manager must be the same as that of the sub-domain or derived from it.
References createMesh().
createSubMesh()
virtual IMesh * Arcane::IMainFactory::createSubMesh (IMesh * mesh, const ItemGroup & group, const String & name) pure virtual
Creates a sub-mesh for the mesh mesh, named name.
The sub-mesh is initialized with the items of the group group. Currently, this group cannot be a complete group (isAllItems()) nor a calculated group (if not incremental).
References createSubMesh().
Referenced by createSubMesh().
createTimeStats()
virtual ARCANE_DEPRECATED_116 ITimeStats * Arcane::IMainFactory::createTimeStats (ISubDomain *) pure virtual
Creates an instance of execution time statistics.
Use the overloaded createTimeStats(ITimerMng*,ITraceMng*,const String& name).
createTraceMng()
virtual ITraceMng * Arcane::IMainFactory::createTraceMng () pure virtual
Creates a trace manager.
The returned instance must be initialized via an ITraceMngPolicy.
References createTraceMng().
Referenced by createTraceMng().
The documentation for this class was generated from the following file:
IMainFactory.h