Arcane: Arcane::ItemPartialVariableArrayRefT< DataTypeT > Class Template Reference
Arcane::ItemPartialVariableArrayRefT< DataTypeT > Class Template Reference
Variable
Scalar partial variable on a mesh entity type.
#include <arcane/core/MeshPartialVariableArrayRef.h>
Public Types
typedef DataTypeT DataType
typedef UniqueArray2< DataType > ValueType
typedef ConstArrayView< DataType > ConstReturnReferenceType
typedef ArrayView< DataType > ReturnReferenceType
Public Member Functions
ItemPartialVariableArrayRefT (const VariableBuildInfo &vb, eItemKind ik)
Constructs a reference to the variable specified in vb.
ItemPartialVariableArrayRefT (IVariable *var)
Constructs a reference from var.
ItemPartialVariableArrayRefT (const ItemPartialVariableArrayRefT< DataType > &rhs)
Constructs a reference from rhs.
void fill (const DataType &value)
void copy (const ItemPartialVariableArrayRefT< DataType > &v)
void internalSetUsed (bool v)
ConstArrayType operator[] (const Item &i) const
ArrayType operator[] (const Item &i)
ConstArrayType operator[] (const ItemGroupRangeIterator &i) const
ArrayType operator[] (const ItemGroupRangeIterator &i)
ConstArrayType operator[] (const ItemEnumerator &i) const
ArrayType operator[] (const ItemEnumerator &i)
ConstArrayType operator[] (ItemEnumeratorIndex i) const
ArrayType operator[] (ItemEnumeratorIndex i)
GroupIndexTableView tableView () const
View of the group indirection table.
Public Member Functions inherited from Arcane::PrivateVariableArrayT< DataTypeT >
Array2View< DataTypeT > asArray ()
Integer totalNbElement () const
Integer arraySize () const
If the variable is an array, returns its dimension, otherwise returns 0.
bool isArrayVariable () const
void updateFromInternal ()
Updates from the internal part.
ItemGroup itemGroup () const
void resize (Int32 dim2_size)
void resizeAndReshape (const ArrayShape &shape)
SmallSpan2< DataTypeT > _internalSpan ()
SmallSpan2< const DataTypeT > _internalConstSpan () const
Public Member Functions inherited from Arcane::MeshVariableRef
MeshVariableRef (const VariableBuildInfo &vb)
Constructs a reference linked to the module.
void synchronize ()
void synchronize (Int32ConstArrayView local_ids)
Public Member Functions inherited from Arcane::VariableRef
virtual ~VariableRef ()
Releases resources.
ISubDomain * subDomain () const
Sub-domain associated with the variable (TODO deprecate end of 2023).
IVariableMng * variableMng () const
Variable manager associated with the variable.
String name () const
Variable name.
virtual eDataType dataType () const
Variable type (Real, Integer, ...).
virtual void print (std::ostream &o) const
Prints the variable value.
virtual IModule * module () const
Module associated with the variable (or nullptr, if none).
virtual int property () const
Variable properties.
virtual int referenceProperty () const
Reference properties (internal).
virtual void setProperty (int property)
Sets the property property.
virtual void unsetProperty (int property)
Unsets the property property.
virtual void registerVariable ()
Registers the variable (internal).
virtual void unregisterVariable ()
Unregisters the variable (internal).
IVariable * variable () const
Associated variable.
virtual Integer checkIfSync (int max_print=0)
Checks if the variable is synchronized.
virtual Integer checkIfSameOnAllReplica (int max_print=0)
Checks if the variable has the same values on all replicas.
void setUsed (bool v)
bool isUsed () const
const String & assignmentStackTrace () const
Call stack at the time of assigning this instance.
void addTag (const String &tagname, const String &tagvalue)
Adds the tag tagname with the value tagvalue.
void removeTag (const String &tagname)
Removes the tag tagname.
bool hasTag (const String &tagname) const
true if the variable has the tag tagname
String tagValue (const String &tagname) const
Value of the tag tagname. The string is null if the tag does not exist.
void update ()
Recalculates the variable if necessary.
void setUpToDate ()
Indicates that the variable has just been updated.
Int64 modifiedTime ()
Time when the variable was updated.
void addDependCurrentTime (const VariableRef &var)
Adds var to the dependency list at the current time.
void addDependCurrentTime (const VariableRef &var, const TraceInfo &tinfo)
Adds var to the dependency list at the current time with trace info tinfo.
void addDependPreviousTime (const VariableRef &var)
Adds var to the dependency list at the previous time.
void addDependPreviousTime (const VariableRef &var, const TraceInfo &tinfo)
Adds var to the dependency list at the previous time with trace info tinfo.
void removeDepend (const VariableRef &var)
Removes var from the dependency list.
template<typename ClassType>
void setComputeFunction (ClassType *instance, void(ClassType::*func)())
Sets the variable's recalculation function.
template<typename ClassType>
void setComputeFunction (ClassType *instance, void(ClassType::*func)(), const TraceInfo &tinfo)
Sets the variable's recalculation function.
VariableRef * previousReference ()
Previous reference (or null) to variable().
VariableRef * nextReference ()
Next reference (or null) to variable().
void setPreviousReference (VariableRef *v)
void setNextReference (VariableRef *v)
Protected Types
typedef PrivateVariableArrayT< DataType > BaseClass
typedef BaseClass::PrivatePartType PrivatePartType
typedef ArrayView< DataType > ArrayType
typedef ConstArrayView< DataType > ConstArrayType
Protected Types inherited from Arcane::PrivateVariableArrayT< DataTypeT >
typedef DataTypeT & DataTypeReturnReference
typedef Array2VariableT< DataTypeT > PrivatePartType
Protected Member Functions
void operator= (const ItemPartialVariableArrayRefT< DataType > &rhs)
Copy assignment operator.
Protected Member Functions inherited from Arcane::PrivateVariableArrayT< DataTypeT >
PrivateVariableArrayT (const VariableBuildInfo &vb, const VariableInfo &vi)
void operator= (const PrivateVariableArrayT &rhs)
void _internalInit ()
Protected Member Functions inherited from Arcane::MeshVariableRef
MeshVariableRef (const MeshVariableRef &rhs)
MeshVariableRef (IVariable *var)
void operator= (const MeshVariableRef &rhs)
void _internalInit (IVariable *)
Protected Member Functions inherited from Arcane::VariableRef
VariableRef (const VariableBuildInfo &vbi)
Constructs a reference to a variable with the infos vbi.
VariableRef (const VariableRef &from)
Copy constructor.
VariableRef (IVariable *var)
Constructs a reference to a variable var.
VariableRef & operator= (const VariableRef &from)
Copy assignment operator.
VariableRef ()
Default constructor.
void _setComputeFunction (IVariableComputeFunction *v)
void _internalInit (IVariable *)
Internal initialization of the variable.
IVariable * _variable () const
Referenced variable.
void _executeUpdateFunctors ()
void _internalAssignVariable (const VariableRef &var)
Static Protected Member Functions
static VariableInfo _buildVariableInfo (const VariableBuildInfo &vbi, eItemKind ik)
static VariableTypeInfo _buildVariableTypeInfo (eItemKind ik)
Protected Attributes
SharedPtrT< GroupIndexTable > m_table
Protected Attributes inherited from Arcane::PrivateVariableArrayT< DataTypeT >
PrivatePartType * m_private_part
Array2View< DataTypeT > m_view
bool m_has_trace = false
Additional Inherited Members
static void setTraceCreation (bool v)
static bool hasTraceCreation ()
Detailed Description
template<typename DataTypeT>
class Arcane::ItemPartialVariableArrayRefT< DataTypeT >
Scalar partial variable on a mesh entity type.
Definition at line 40 of file MeshPartialVariableArrayRef.h.
Member Typedef Documentation
ArrayType
template<typename DataTypeT> typedef ArrayView<DataType> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::ArrayType protected
Definition at line 55 of file MeshPartialVariableArrayRef.h.
BaseClass
template<typename DataTypeT> typedef PrivateVariableArrayT<DataType> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::BaseClass protected
Definition at line 52 of file MeshPartialVariableArrayRef.h.
ConstArrayType
template<typename DataTypeT> typedef ConstArrayView<DataType> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::ConstArrayType protected
Definition at line 56 of file MeshPartialVariableArrayRef.h.
ConstReturnReferenceType
template<typename DataTypeT> typedef ConstArrayView<DataType> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::ConstReturnReferenceType
Definition at line 47 of file MeshPartialVariableArrayRef.h.
DataType
template<typename DataTypeT> typedef DataTypeT Arcane::ItemPartialVariableArrayRefT< DataTypeT >::DataType
Definition at line 45 of file MeshPartialVariableArrayRef.h.
PrivatePartType
template<typename DataTypeT> typedef BaseClass::PrivatePartType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::PrivatePartType protected
Definition at line 53 of file MeshPartialVariableArrayRef.h.
ReturnReferenceType
template<typename DataTypeT> typedef ArrayView<DataType> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::ReturnReferenceType
Definition at line 48 of file MeshPartialVariableArrayRef.h.
ValueType
template<typename DataTypeT> typedef UniqueArray2<DataType> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::ValueType
Definition at line 46 of file MeshPartialVariableArrayRef.h.
Constructor & Destructor Documentation
ItemPartialVariableArrayRefT() [1/3]
template<class DataType> Arcane::ItemPartialVariableArrayRefT< DataType >::ItemPartialVariableArrayRefT (const VariableBuildInfo & vb, eItemKind ik)
Constructs a reference to the variable specified in vb.
Definition at line 54 of file MeshPartialVariableArrayRef.inst.h.
Referenced by ItemPartialVariableArrayRefT(), Arcane::MeshPartialVariableArrayRefT< ItemTypeT, DataTypeT >::MeshPartialVariableArrayRefT(), Arcane::MeshPartialVariableArrayRefT< ItemTypeT, DataTypeT >::MeshPartialVariableArrayRefT(), and operator=().
ItemPartialVariableArrayRefT() [2/3]
template<class DataType> Arcane::ItemPartialVariableArrayRefT< DataType >::ItemPartialVariableArrayRefT (IVariable * var) explicit
Constructs a reference from var.
Definition at line 66 of file MeshPartialVariableArrayRef.inst.h.
ItemPartialVariableArrayRefT() [3/3]
template<class DataType> Arcane::ItemPartialVariableArrayRefT< DataType >::ItemPartialVariableArrayRefT (const ItemPartialVariableArrayRefT< DataType > & rhs)
Constructs a reference from rhs.
Definition at line 78 of file MeshPartialVariableArrayRef.inst.h.
References ItemPartialVariableArrayRefT().
Member Function Documentation
_buildVariableInfo()
template<typename DataType> VariableInfo Arcane::ItemPartialVariableArrayRefT< DataType >::_buildVariableInfo (const VariableBuildInfo & vbi, eItemKind ik) static protected
Definition at line 42 of file MeshPartialVariableArrayRef.inst.h.
_buildVariableTypeInfo()
template<typename DataType> VariableTypeInfo Arcane::ItemPartialVariableArrayRefT< DataType >::_buildVariableTypeInfo (eItemKind ik) static protected
Definition at line 31 of file MeshPartialVariableArrayRef.inst.h.
copy()
template<typename DataType> void Arcane::ItemPartialVariableArrayRefT< DataType >::copy (const ItemPartialVariableArrayRefT< DataType > & v)
Definition at line 125 of file MeshPartialVariableArrayRef.inst.h.
fill()
template<class DataType> void Arcane::ItemPartialVariableArrayRefT< DataType >::fill (const DataType & value)
Definition at line 113 of file MeshPartialVariableArrayRef.inst.h.
internalSetUsed()
template<typename DataType> void Arcane::ItemPartialVariableArrayRefT< DataType >::internalSetUsed (bool v) virtual
Reimplemented from Arcane::VariableRef.
Definition at line 89 of file MeshPartialVariableArrayRef.inst.h.
operator=()
template<class DataType> void Arcane::ItemPartialVariableArrayRefT< DataType >::operator= (const ItemPartialVariableArrayRefT< DataType > & rhs) protected
Copy assignment operator.
Definition at line 102 of file MeshPartialVariableArrayRef.inst.h.
References ItemPartialVariableArrayRefT().
Referenced by Arcane::MeshPartialVariableArrayRefT< ItemTypeT, DataTypeT >::refersTo().
operator[]() [1/8]
template<typename DataTypeT> ArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (const Item & i) inline
Definition at line 89 of file MeshPartialVariableArrayRef.h.
operator[]() [2/8]
template<typename DataTypeT> ConstArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (const Item & i) const inline
Definition at line 82 of file MeshPartialVariableArrayRef.h.
operator[]() [3/8]
template<typename DataTypeT> ArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (const ItemEnumerator & i) inline
Definition at line 111 of file MeshPartialVariableArrayRef.h.
operator[]() [4/8]
template<typename DataTypeT> ConstArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (const ItemEnumerator & i) const inline
Definition at line 106 of file MeshPartialVariableArrayRef.h.
operator[]() [5/8]
template<typename DataTypeT> ArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (const ItemGroupRangeIterator & i) inline
Definition at line 101 of file MeshPartialVariableArrayRef.h.
operator[]() [6/8]
template<typename DataTypeT> ConstArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (const ItemGroupRangeIterator & i) const inline
Definition at line 96 of file MeshPartialVariableArrayRef.h.
operator[]() [7/8]
template<typename DataTypeT> ArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (ItemEnumeratorIndex i) inline
Definition at line 120 of file MeshPartialVariableArrayRef.h.
operator[]() [8/8]
template<typename DataTypeT> ConstArrayType Arcane::ItemPartialVariableArrayRefT< DataTypeT >::operator[] (ItemEnumeratorIndex i) const inline
Definition at line 116 of file MeshPartialVariableArrayRef.h.
tableView()
template<typename DataTypeT> GroupIndexTableView Arcane::ItemPartialVariableArrayRefT< DataTypeT >::tableView () const inline
View of the group indirection table.
Definition at line 128 of file MeshPartialVariableArrayRef.h.
Referenced by Arcane::Accelerator::viewIn(), Arcane::Accelerator::viewInOut(), and Arcane::Accelerator::viewOut().
Member Data Documentation
m_table
template<typename DataTypeT> SharedPtrT<GroupIndexTable> Arcane::ItemPartialVariableArrayRefT< DataTypeT >::m_table protected
Definition at line 132 of file MeshPartialVariableArrayRef.h.
The documentation for this class was generated from the following files:
MeshPartialVariableArrayRef.h
MeshPartialVariableArrayRef.inst.h