Alien: Alien::LinearAlgebraExpr< Tag, TagV > Class Template Reference
Alien::LinearAlgebraExpr< Tag, TagV > Class Template Reference
Linear algebra interface.
#include <core/alien/core/backend/LinearAlgebraExpr.h>
Public Member Functions
template<typename... T>
LinearAlgebraExpr (T... args)
Creates a linear algebra.
virtual ~LinearAlgebraExpr ()
Free resources.
Real norm0 (const IVector &x) const
Compute L0 norm of a vector.
Real norm1 (const IVector &x) const
Compute L1 norm of a vector.
Real norm2 (const IVector &x) const
Compute L2 norm of a vector.
Real normInf (const IVector &x) const
Compute LInf norm of a vector.
Real norm2 (const IMatrix &x) const
Compute L2 (Frobenous) norm of a matrix.
void mult (const IMatrix &a, const IVector &x, IVector &r) const
Compute a matrix vector product.
void axpy (Real alpha, const IVector &x, IVector &y) const
Scale a vector by a factor and adds the result to another vector.
void aypx (Real alpha, IVector &y, const IVector &x) const
Scale a vector by a factor and adds the result to another vector.
void copy (const IVector &x, IVector &r) const
Copy a vector in another one.
void copy (const IMatrix &x, IMatrix &r) const
Copy a matrix in another one.
void add (const IMatrix &a, IMatrix &b) const
Add two matrices A and B.
Real dot (const IVector &x, const IVector &y) const
Compute the dot product of two vectors.
void scal (Real alpha, IVector &x) const
Scale a vector by a factor.
void scal (Real alpha, IMatrix &a) const
Scale a matrix by a factor.
void diagonal (const IMatrix &a, IVector &x) const
Extract the diagonal of a matrix in a vector.
void reciprocal (IVector &x) const
Compute the reciprocal of a vector.
void pointwiseMult (const IVector &x, const IVector &y, IVector &w) const
Compute the point wise multiplication of two vectors and store the result in another one.
void mult (const IMatrix &a, const UniqueArray< Real > &x, UniqueArray< Real > &r) const
Compute a matrix vector product.
void axpy (Real alpha, const UniqueArray< Real > &x, UniqueArray< Real > &r) const
Scale a vector by a factor and adds the result to another vector.
void aypx (Real alpha, UniqueArray< Real > &y, const UniqueArray< Real > &x) const
Scale a vector by a factor and adds the result to another vector.
void copy (const UniqueArray< Real > &x, UniqueArray< Real > &r) const
Copy a vector in another one.
Real dot (Integer local_size, const UniqueArray< Real > &x, const UniqueArray< Real > &y) const
Compute the dot product of two vectors.
void scal (Real alpha, UniqueArray< Real > &x) const
Scale a vector by a factor.
void dump (IMatrix const &a, std::string const &filename) const
Dumps a matrix to a file.
void dump (IVector const &x, std::string const &filename) const
Dumps a vector to a file.
Detailed Description
template<class Tag, class TagV = Tag>
class Alien::LinearAlgebraExpr< Tag, TagV >
Linear algebra interface.
Interface for all linear algebra package
Template Parameters
Tag The tag of the type of matrix used
TagV The tag of the type of vector used
Definition at line 48 of file LinearAlgebraExpr.h.
Constructor & Destructor Documentation
LinearAlgebraExpr()
template<class Tag, class TagV = Tag> template<typename... T> Alien::LinearAlgebraExpr< Tag, TagV >::LinearAlgebraExpr (T... args) inline
Creates a linear algebra.
Creates a linear algebra using traits and the linear algebra factory
Template Parameters
T Variadics type of linear algebra
Parameters
[in] args Linear algebras
Definition at line 60 of file LinearAlgebraExpr.h.
~LinearAlgebraExpr()
template<class Tag, class TagV> Alien::LinearAlgebraExpr< Tag, TagV >::~LinearAlgebraExpr () virtual
Free resources.
Definition at line 32 of file LinearAlgebraExprT.h.
Member Function Documentation
add()
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::add (const IMatrix & a, IMatrix & b) const
Add two matrices A and B.
Parameters
[in] a The matrix A
[in] b The matrix B
[in,out] c The resulting matrix
Definition at line 145 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), and Alien::IMatrix::impl().
axpy() [1/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::axpy (Real alpha, const IVector & x, IVector & y) const
Scale a vector by a factor and adds the result to another vector.
Scale the vector x by the real value alpha and add the result to the vector y : y += alpha * x
Parameters
[in] alpha The real value to scale with
[in] x The vector to be scaled
[in,out] y The resulting vector
Definition at line 104 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
axpy() [2/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::axpy (Real alpha, const UniqueArray< Real > & x, UniqueArray< Real > & r) const
Scale a vector by a factor and adds the result to another vector.
Scale the vector x by the real value alpha and add the result to the vector y : y += alpha * x
Parameters
[in] alpha The real value to scale with
[in] x The vector to be scaled
[in,out] y The resulting vector
Definition at line 233 of file LinearAlgebraExprT.h.
aypx() [1/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::aypx (Real alpha, IVector & y, const IVector & x) const
Scale a vector by a factor and adds the result to another vector.
Scale the vector y by the real value alpha and add the values of x : alpha * y += x
Parameters
[in] alpha The real value to scale with
[in,out] y The vector to be scaled
[in] x The vector to add
Definition at line 116 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
aypx() [2/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::aypx (Real alpha, UniqueArray< Real > & y, const UniqueArray< Real > & x) const
Scale a vector by a factor and adds the result to another vector.
Scale the vector y by the real value alpha and add the values of x : alpha * y += x
Parameters
[in] alpha The real value to scale with
[in,out] y The vector to be scaled
[in] x The vector to add
Definition at line 242 of file LinearAlgebraExprT.h.
copy() [1/3]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::copy (const IMatrix & x, IMatrix & r) const
Copy a matrix in another one.
Parameters
[in] x The matrix to copy
[in,out] r The copied matrix
Definition at line 136 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), and Alien::IMatrix::impl().
copy() [2/3]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::copy (const IVector & x, IVector & r) const
Copy a vector in another one.
Parameters
[in] x The vector to copy
[in,out] r The copied vector
Definition at line 127 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
copy() [3/3]
template<class Tag, class TagV = Tag> void Alien::LinearAlgebraExpr< Tag, TagV >::copy (const UniqueArray< Real > & x, UniqueArray< Real > & r) const
Copy a vector in another one.
Parameters
[in] x The vector to copy
[in,out] r The copied vector
diagonal()
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::diagonal (const IMatrix & a, IVector & x) const
Extract the diagonal of a matrix in a vector.
Parameters
[in] a The matrix to extract the diagonal
[in,out] x The diagonal elements of the matrix stored in a vector
Definition at line 167 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), Alien::MultiVectorImpl::get(), Alien::IMatrix::impl(), and Alien::IVector::impl().
dot() [1/2]
template<class Tag, class TagV> Real Alien::LinearAlgebraExpr< Tag, TagV >::dot (const IVector & x, const IVector & y) const
Compute the dot product of two vectors.
Parameters
[in] x The first vector
[in] y The second vector
Returns
The dot product of x * y
Definition at line 156 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
dot() [2/2]
template<class Tag, class TagV> Real Alien::LinearAlgebraExpr< Tag, TagV >::dot (Integer local_size, const UniqueArray< Real > & x, const UniqueArray< Real > & y) const
Compute the dot product of two vectors.
Parameters
[in] local_size The size of the vectors
[in] x The first vector
[in] y The second vector
Returns
The dot product of x * y
Definition at line 261 of file LinearAlgebraExprT.h.
dump() [1/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::dump (IMatrix const & a, std::string const & filename) const
Dumps a matrix to a file.
Parameters
[in] a The matrix to dump
[in] filename The name of the file
Definition at line 280 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), and Alien::IMatrix::impl().
dump() [2/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::dump (IVector const & x, std::string const & filename) const
Dumps a vector to a file.
Parameters
[in] x The vector to dump
[in] filename The name of the file
Definition at line 290 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
mult() [1/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::mult (const IMatrix & a, const IVector & x, IVector & r) const
Compute a matrix vector product.
Compute the matrix-vector product a by x and store it in r : r = a * x
Parameters
[in] a The matrix to be multiplied
[in] x The vector to be multipled
[in,out] r The resulting vector
Definition at line 90 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), Alien::MultiVectorImpl::get(), Alien::IMatrix::impl(), and Alien::IVector::impl().
mult() [2/2]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::mult (const IMatrix & a, const UniqueArray< Real > & x, UniqueArray< Real > & r) const
Compute a matrix vector product.
Compute the matrix-vector product a by x and store it in r : r = a * x
Parameters
[in] a The matrix to be multiplied
[in] x The vector to be multipled
[in,out] r The resulting vector
Definition at line 222 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), and Alien::IMatrix::impl().
norm0()
template<class Tag, class TagV> Arccore::Real Alien::LinearAlgebraExpr< Tag, TagV >::norm0 (const IVector & x) const
Compute L0 norm of a vector.
Parameters
[in] x The vector on which norm0 is computed
Returns
The norm0 of the vector
Definition at line 38 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
norm1()
template<class Tag, class TagV> Arccore::Real Alien::LinearAlgebraExpr< Tag, TagV >::norm1 (const IVector & x) const
Compute L1 norm of a vector.
Parameters
[in] x The vector on which norm0 is computed
Returns
The norm1 of the vector
Definition at line 48 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
norm2() [1/2]
template<class Tag, class TagV> Arccore::Real Alien::LinearAlgebraExpr< Tag, TagV >::norm2 (const IMatrix & x) const
Compute L2 (Frobenous) norm of a matrix.
Parameters
[in] x The matrix on which norm2 is computed
Returns
The norm2 of the matrix
Definition at line 81 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), and Alien::IMatrix::impl().
norm2() [2/2]
template<class Tag, class TagV> Arccore::Real Alien::LinearAlgebraExpr< Tag, TagV >::norm2 (const IVector & x) const
Compute L2 norm of a vector.
Parameters
[in] x The vector on which norm0 is computed
Returns
The norm2 of the vector
Definition at line 59 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
normInf()
template<class Tag, class TagV> Arccore::Real Alien::LinearAlgebraExpr< Tag, TagV >::normInf (const IVector & x) const
Compute LInf norm of a vector.
Parameters
[in] x The vector on which norm0 is computed
Returns
The normInf of the vector
Definition at line 70 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
pointwiseMult()
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::pointwiseMult (const IVector & x, const IVector & y, IVector & w) const
Compute the point wise multiplication of two vectors and store the result in another one.
Parameters
[in] x The first vector
[in] y The second vector
[in,out] w The resulting vector
Definition at line 207 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
reciprocal()
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::reciprocal (IVector & x) const
Compute the reciprocal of a vector.
Parameters
[in,out] x The vector to be processed
Definition at line 180 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
scal() [1/3]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::scal (Real alpha, IMatrix & a) const
Scale a matrix by a factor.
Parameters
[in] alpha The real value to scale with
[in,out] x The vector to be scaled
Definition at line 197 of file LinearAlgebraExprT.h.
References Alien::MultiMatrixImpl::get(), and Alien::IMatrix::impl().
scal() [2/3]
template<class Tag, class TagV> void Alien::LinearAlgebraExpr< Tag, TagV >::scal (Real alpha, IVector & x) const
Scale a vector by a factor.
Parameters
[in] alpha The real value to scale with
[in,out] x The vector to be scaled
Definition at line 190 of file LinearAlgebraExprT.h.
References Alien::MultiVectorImpl::get(), and Alien::IVector::impl().
scal() [3/3]
template<class Tag, class TagV = Tag> void Alien::LinearAlgebraExpr< Tag, TagV >::scal (Real alpha, UniqueArray< Real > & x) const
Scale a vector by a factor.
Parameters
[in] alpha The real value to scale with
[in,out] x The vector to be scaled
The documentation for this class was generated from the following files:
LinearAlgebraExpr.h
LinearAlgebraExprT.h