Arcane: Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ > Class Template Reference
Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ > Class Template Reference
Information of a loop using hierarchical parallelism on the host.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/accelerator/arccore/accelerator/RunCommandLaunchImpl.h>
Public Types
using IndexType = IndexType_
Public Member Functions
HostLaunchLoopRangeBase (IndexType total_size, Int32 nb_group, IndexType block_size)
constexpr IndexType nbElement () const
Number of elements to process.
constexpr IndexType blockSize () const
Block size.
constexpr Int32 nbBlock () const
Number of blocks.
constexpr IndexType lastBlockSize () const
Number of elements in the last block.
constexpr IndexType nbActiveItem (Int32 i) const
Number of active items for the i-th block.
ThreadGridSynchronizer * threadGridSynchronizer () const
Grid synchronizer (non-null only in cooperative multi-threading).
void setThreadGridSynchronizer (ThreadGridSynchronizer *v)
Private Attributes
ThreadGridSynchronizer * m_thread_grid_synchronizer = nullptr
This instance is managed by arcaneParallelFor(HostLaunchLoopRange<>...).
IndexType m_total_size = 0
IndexType m_block_size = 0
IndexType m_last_block_size = 0
Int32 m_nb_block = 0
Detailed Description
template<typename IndexType_>
class Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >
Information of a loop using hierarchical parallelism on the host.
Definition at line 41 of file RunCommandLaunchImpl.h.
Member Typedef Documentation
IndexType
template<typename IndexType_> using Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::IndexType = IndexType_
Definition at line 45 of file RunCommandLaunchImpl.h.
Constructor & Destructor Documentation
HostLaunchLoopRangeBase()
template<typename IndexType_> Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::HostLaunchLoopRangeBase (IndexType total_size, Int32 nb_group, IndexType block_size)
Definition at line 34 of file RunCommandLaunch.cc.
Member Function Documentation
blockSize()
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::blockSize () const inline constexpr
Block size.
Definition at line 57 of file RunCommandLaunchImpl.h.
Referenced by Arcane::Accelerator::Impl::WorkGroupSequentialForHelper::apply().
lastBlockSize()
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::lastBlockSize () const inline constexpr
Number of elements in the last block.
Definition at line 61 of file RunCommandLaunchImpl.h.
nbActiveItem()
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::nbActiveItem (Int32 i) const inline constexpr
Number of active items for the i-th block.
Definition at line 63 of file RunCommandLaunchImpl.h.
Referenced by Arcane::Accelerator::Impl::WorkGroupSequentialForHelper::apply().
nbBlock()
template<typename IndexType_> Int32 Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::nbBlock () const inline constexpr
Number of blocks.
Definition at line 59 of file RunCommandLaunchImpl.h.
Referenced by Arcane::Accelerator::Impl::WorkGroupSequentialForHelper::apply().
nbElement()
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::nbElement () const inline constexpr
Number of elements to process.
Definition at line 55 of file RunCommandLaunchImpl.h.
Referenced by Arcane::Accelerator::Impl::WorkGroupSequentialForHelper::apply().
setThreadGridSynchronizer()
template<typename IndexType_> void Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::setThreadGridSynchronizer (ThreadGridSynchronizer * v) inline
Definition at line 72 of file RunCommandLaunchImpl.h.
threadGridSynchronizer()
template<typename IndexType_> ThreadGridSynchronizer * Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::threadGridSynchronizer () const inline
Grid synchronizer (non-null only in cooperative multi-threading).
Definition at line 68 of file RunCommandLaunchImpl.h.
Referenced by Arcane::Accelerator::Impl::WorkGroupSequentialForHelper::apply().
Member Data Documentation
m_block_size
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::m_block_size = 0 private
Definition at line 82 of file RunCommandLaunchImpl.h.
m_last_block_size
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::m_last_block_size = 0 private
Definition at line 83 of file RunCommandLaunchImpl.h.
m_nb_block
template<typename IndexType_> Int32 Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::m_nb_block = 0 private
Definition at line 84 of file RunCommandLaunchImpl.h.
m_thread_grid_synchronizer
template<typename IndexType_> ThreadGridSynchronizer* Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::m_thread_grid_synchronizer = nullptr private
This instance is managed by arcaneParallelFor(HostLaunchLoopRange<>...).
Definition at line 80 of file RunCommandLaunchImpl.h.
m_total_size
template<typename IndexType_> IndexType Arcane::Accelerator::Impl::HostLaunchLoopRangeBase< IndexType_ >::m_total_size = 0 private
Definition at line 81 of file RunCommandLaunchImpl.h.
The documentation for this class was generated from the following files:
RunCommandLaunchImpl.h
RunCommandLaunch.cc