Arcane: Arcane::ConcurrencyBase Class Reference
Arcane::ConcurrencyBase Class Reference
Basic information for multi-threading management.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/base/arccore/base/ConcurrencyBase.h>
Static Public Member Functions
static Int32 maxAllowedThread ()
Maximum number of allowed threads for multi-threading.
static void setDefaultParallelLoopOptions (const ParallelLoopOptions &v)
Sets the default execution values for a parallel loop.
static const ParallelLoopOptions & defaultParallelLoopOptions ()
Default execution values for a parallel loop.
Static Private Member Functions
static void _setMaxAllowedThread (Int32 v)
Sets the maximum number of threads to use.
Static Private Attributes
static Int32 m_max_allowed_thread = 1
static ParallelLoopOptions m_default_loop_options
Friends
class TBBTaskImplementation
Detailed Description
Basic information for multi-threading management.
Definition at line 31 of file ConcurrencyBase.h.
Member Function Documentation
_setMaxAllowedThread()
void Arcane::ConcurrencyBase::_setMaxAllowedThread (Int32 v) static private
Sets the maximum number of threads to use.
This method must be called by the ITaskImplementation implementation during initialization. It should not be modified afterward.
Definition at line 37 of file ConcurrencyBase.cc.
defaultParallelLoopOptions()
const ParallelLoopOptions & Arcane::ConcurrencyBase::defaultParallelLoopOptions () inline static
Default execution values for a parallel loop.
Definition at line 55 of file ConcurrencyBase.h.
Referenced by Arcane::TaskFactory::defaultParallelLoopOptions().
maxAllowedThread()
Int32 Arcane::ConcurrencyBase::maxAllowedThread () inline static
Maximum number of allowed threads for multi-threading.
This value is only meaningful once the management service for multi-threading has been created.
Definition at line 44 of file ConcurrencyBase.h.
Referenced by Arcane::Accelerator::Impl::RunCommandLaunchInfo::computeParallelLoopOptions(), Arcane::Accelerator::AcceleratorRuntimeInitialisationInfo::executionPolicy(), Arcane::ITaskImplementation::nbAllowedThread(), and Arcane::TaskFactory::nbAllowedThread().
setDefaultParallelLoopOptions()
void Arcane::ConcurrencyBase::setDefaultParallelLoopOptions (const ParallelLoopOptions & v) inline static
Sets the default execution values for a parallel loop.
Definition at line 49 of file ConcurrencyBase.h.
Referenced by Arcane::TaskFactory::setDefaultParallelLoopOptions().
Friends And Related Symbol Documentation
TBBTaskImplementation
friend class TBBTaskImplementation friend
Definition at line 34 of file ConcurrencyBase.h.
Member Data Documentation
m_default_loop_options
ParallelLoopOptions Arcane::ConcurrencyBase::m_default_loop_options static private
Definition at line 63 of file ConcurrencyBase.h.
m_max_allowed_thread
Int32 Arcane::ConcurrencyBase::m_max_allowed_thread = 1 static private
Definition at line 62 of file ConcurrencyBase.h.
The documentation for this class was generated from the following files:
ConcurrencyBase.h
ConcurrencyBase.cc