Arcane: Arcane::Real3x3Proxy Class Reference
Arcane::Real3x3Proxy Class Reference
Proxy for a 'Real3x3'.
#include <arcane/utils/Real3x3Proxy.h>
Public Member Functions
Real3x3Proxy (Real3x3 &value, const MemoryAccessInfo &info)
Constructs the triplet (ax,ay,az).
Real3x3Proxy (const Real3x3Proxy &f)
Constructs a triplet identical to f.
const Real3x3 & operator= (const Real3x3Proxy f)
const Real3x3 & operator= (Real3x3 f)
const Real3x3 & operator= (Real v)
Assigns the triplet (v,v,v) to the instance.
operator const Real3x3 & () const
Real3x3 copy () const
Returns a copy of the triplet.
Real3x3Proxy & reset ()
Resets the triplet using default constructors.
Real3x3Proxy & assign (Real3 ax, Real3 ay, Real3 az)
Assigns the triplet (ax,ay,az) to the instance.
Real3x3Proxy & assign (Real3x3 f)
Copies the triplet f.
bool isNearlyZero () const
Compares the matrix with the zero matrix.
std::istream & assign (std::istream &i)
Reads the matrix from the stream i The matrix is read in the form of three Real3s.
std::ostream & print (std::ostream &o) const
Writes the triplet to the stream o readable by an assign().
std::ostream & printXyz (std::ostream &o) const
Writes the triplet to the stream o in the form (x,y,z).
Real3x3Proxy & add (Real3x3 b)
Adds b to the triplet.
Real3x3Proxy & sub (Real3x3 b)
Subtracts b from the triplet.
Real3x3Proxy & addSame (Real3 b)
Adds b to each component of the triplet.
Real3x3Proxy & subSame (Real3 b)
Subtracts b from each component of the triplet.
Real3x3Proxy & mulSame (Real3 b)
Multiplies each component of the triplet by b.
Real3x3Proxy & divSame (Real3 b)
Divides each component of the triplet by b.
Real3x3Proxy & operator+= (Real3x3 b)
Adds b to the triplet.
Real3x3Proxy & operator-= (Real3x3 b)
Subtracts b from the triplet.
void operator*= (Real b)
Multiplies each component of the matrix by the real b.
void operator/= (Real b)
Divides each component of the matrix by the real b.
Real3x3 operator+ (Real3x3 b) const
Creates a triplet that equals this triplet added to b.
Real3x3 operator- (Real3x3 b) const
Creates a triplet that equals b subtracted from this triplet.
Real3x3 operator- () const
Creates a tensor opposite to the current tensor.
const Real3x3 & getValue () const
Real3x3 & getValueMutable ()
Public Attributes
Real3Proxy x
first element of the triplet
Real3Proxy y
first element of the triplet
Real3Proxy z
first element of the triplet
Static Private Member Functions
static bool _eq (Real a, Real b)
Compares the values of a and b with the TypeEqualT comparator.
Private Attributes
Real3x3 & m_value
MemoryAccessInfo m_info
Detailed Description
Proxy for a 'Real3x3'.
Definition at line 32 of file Real3x3Proxy.h.
Constructor & Destructor Documentation
Real3x3Proxy() [1/2]
Arcane::Real3x3Proxy::Real3x3Proxy (Real3x3 & value, const MemoryAccessInfo & info) inline
Constructs the triplet (ax,ay,az).
Definition at line 37 of file Real3x3Proxy.h.
References x, y, and z.
Referenced by add(), addSame(), assign(), assign(), divSame(), mulSame(), operator+=(), operator-=(), Real3x3Proxy(), reset(), sub(), and subSame().
Real3x3Proxy() [2/2]
Arcane::Real3x3Proxy::Real3x3Proxy (const Real3x3Proxy & f) inline
Constructs a triplet identical to f.
Definition at line 46 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
Member Function Documentation
_eq()
bool Arcane::Real3x3Proxy::_eq (Real a, Real b) inline static private
Compares the values of a and b with the TypeEqualT comparator.
Return values
true if a and b are equal,
false otherwise.
Definition at line 259 of file Real3x3Proxy.h.
References Arcane::TypeEqualT< T >::isEqual().
add()
Real3x3Proxy & Arcane::Real3x3Proxy::add (Real3x3 b) inline
Adds b to the triplet.
Definition at line 155 of file Real3x3Proxy.h.
References Real3x3Proxy(), Arcane::Real3x3::x, x, Arcane::Real3x3::y, y, Arcane::Real3x3::z, and z.
Referenced by operator+=().
addSame()
Real3x3Proxy & Arcane::Real3x3Proxy::addSame (Real3 b) inline
Adds b to each component of the triplet.
Definition at line 173 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
assign() [1/3]
Real3x3Proxy & Arcane::Real3x3Proxy::assign (Real3 ax, Real3 ay, Real3 az) inline
Assigns the triplet (ax,ay,az) to the instance.
Definition at line 109 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
Referenced by assign(), and Arcane::Real3::operator>>().
assign() [2/3]
Real3x3Proxy & Arcane::Real3x3Proxy::assign (Real3x3 f) inline
Copies the triplet f.
Definition at line 118 of file Real3x3Proxy.h.
References Real3x3Proxy(), Arcane::Real3x3::x, x, Arcane::Real3x3::y, y, Arcane::Real3x3::z, and z.
assign() [3/3]
std::istream & Arcane::Real3x3Proxy::assign (std::istream & i)
Reads the matrix from the stream i The matrix is read in the form of three Real3s.
Definition at line 27 of file arcane/src/arcane/utils/Real3x3.cc.
References assign().
copy()
Real3x3 Arcane::Real3x3Proxy::copy () const inline
Returns a copy of the triplet.
Definition at line 97 of file Real3x3Proxy.h.
divSame()
Real3x3Proxy & Arcane::Real3x3Proxy::divSame (Real3 b) inline
Divides each component of the triplet by b.
Definition at line 200 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
getValue()
const Real3x3 & Arcane::Real3x3Proxy::getValue () const inline
Definition at line 241 of file Real3x3Proxy.h.
getValueMutable()
Real3x3 & Arcane::Real3x3Proxy::getValueMutable () inline
Definition at line 246 of file Real3x3Proxy.h.
isNearlyZero()
bool Arcane::Real3x3Proxy::isNearlyZero () const inline
Compares the matrix with the zero matrix.
The matrix is zero if and only if each of its components is less than a given epsilon. The epsilon value used is that of float_info<value_type>::nearlyEpsilon():
\[A=0 \Leftrightarrow |A.x|<\epsilon,|A.y|<\epsilon,|A.z|<\epsilon \]
Return values
true if the matrix is equal to the zero matrix,
false otherwise.
Definition at line 137 of file Real3x3Proxy.h.
References x, y, and z.
mulSame()
Real3x3Proxy & Arcane::Real3x3Proxy::mulSame (Real3 b) inline
Multiplies each component of the triplet by b.
Definition at line 191 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
operator const Real3x3 &()
Arcane::Real3x3Proxy::operator const Real3x3 & () const inline
Definition at line 74 of file Real3x3Proxy.h.
operator*=()
void Arcane::Real3x3Proxy::operator*= (Real b) inline
Multiplies each component of the matrix by the real b.
Definition at line 215 of file Real3x3Proxy.h.
References x, y, and z.
operator+()
Real3x3 Arcane::Real3x3Proxy::operator+ (Real3x3 b) const inline
Creates a triplet that equals this triplet added to b.
Definition at line 231 of file Real3x3Proxy.h.
References Arcane::Real3x3::x, x, Arcane::Real3x3::y, y, Arcane::Real3x3::z, and z.
operator+=()
Real3x3Proxy & Arcane::Real3x3Proxy::operator+= (Real3x3 b) inline
Adds b to the triplet.
Definition at line 209 of file Real3x3Proxy.h.
References add(), and Real3x3Proxy().
operator-() [1/2]
Real3x3 Arcane::Real3x3Proxy::operator- () const inline
Creates a tensor opposite to the current tensor.
Definition at line 237 of file Real3x3Proxy.h.
References x, y, and z.
operator-() [2/2]
Real3x3 Arcane::Real3x3Proxy::operator- (Real3x3 b) const inline
Creates a triplet that equals b subtracted from this triplet.
Definition at line 234 of file Real3x3Proxy.h.
References Arcane::Real3x3::x, x, Arcane::Real3x3::y, y, Arcane::Real3x3::z, and z.
operator-=()
Real3x3Proxy & Arcane::Real3x3Proxy::operator-= (Real3x3 b) inline
Subtracts b from the triplet.
Definition at line 212 of file Real3x3Proxy.h.
References Real3x3Proxy(), and sub().
operator/=()
void Arcane::Real3x3Proxy::operator/= (Real b) inline
Divides each component of the matrix by the real b.
Definition at line 223 of file Real3x3Proxy.h.
References x, y, and z.
operator=() [1/3]
const Real3x3 & Arcane::Real3x3Proxy::operator= (const Real3x3Proxy f) inline
Definition at line 53 of file Real3x3Proxy.h.
operator=() [2/3]
const Real3x3 & Arcane::Real3x3Proxy::operator= (Real v) inline
Assigns the triplet (v,v,v) to the instance.
Definition at line 69 of file Real3x3Proxy.h.
References x, y, and z.
operator=() [3/3]
const Real3x3 & Arcane::Real3x3Proxy::operator= (Real3x3 f) inline
Definition at line 60 of file Real3x3Proxy.h.
print()
std::ostream & Arcane::Real3x3Proxy::print (std::ostream & o) const
Writes the triplet to the stream o readable by an assign().
Definition at line 37 of file arcane/src/arcane/utils/Real3x3.cc.
References print().
Referenced by print().
printXyz()
std::ostream & Arcane::Real3x3Proxy::printXyz (std::ostream & o) const
Writes the triplet to the stream o in the form (x,y,z).
Definition at line 46 of file arcane/src/arcane/utils/Real3x3.cc.
Referenced by Arcane::Real3::operator<<().
reset()
Real3x3Proxy & Arcane::Real3x3Proxy::reset () inline
Resets the triplet using default constructors.
Definition at line 100 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
sub()
Real3x3Proxy & Arcane::Real3x3Proxy::sub (Real3x3 b) inline
Subtracts b from the triplet.
Definition at line 164 of file Real3x3Proxy.h.
References Real3x3Proxy(), Arcane::Real3x3::x, x, Arcane::Real3x3::y, y, Arcane::Real3x3::z, and z.
Referenced by operator-=().
subSame()
Real3x3Proxy & Arcane::Real3x3Proxy::subSame (Real3 b) inline
Subtracts b from each component of the triplet.
Definition at line 182 of file Real3x3Proxy.h.
References Real3x3Proxy(), x, y, and z.
Member Data Documentation
m_info
MemoryAccessInfo Arcane::Real3x3Proxy::m_info private
Definition at line 92 of file Real3x3Proxy.h.
m_value
Real3x3& Arcane::Real3x3Proxy::m_value private
Definition at line 91 of file Real3x3Proxy.h.
x
Real3Proxy Arcane::Real3x3Proxy::x
first element of the triplet
Definition at line 85 of file Real3x3Proxy.h.
Referenced by add(), addSame(), assign(), assign(), divSame(), isNearlyZero(), mulSame(), Arcane::operator*(), Arcane::operator*(), operator*=(), operator+(), operator-(), operator-(), Arcane::operator/(), operator/=(), Arcane::operator<(), operator=(), Real3x3Proxy(), Real3x3Proxy(), reset(), sub(), and subSame().
y
Real3Proxy Arcane::Real3x3Proxy::y
first element of the triplet
Definition at line 86 of file Real3x3Proxy.h.
Referenced by add(), addSame(), assign(), assign(), divSame(), isNearlyZero(), mulSame(), Arcane::operator*(), Arcane::operator*(), operator*=(), operator+(), operator-(), operator-(), Arcane::operator/(), operator/=(), Arcane::operator<(), operator=(), Real3x3Proxy(), Real3x3Proxy(), reset(), sub(), and subSame().
z
Real3Proxy Arcane::Real3x3Proxy::z
first element of the triplet
Definition at line 87 of file Real3x3Proxy.h.
Referenced by add(), addSame(), assign(), assign(), divSame(), isNearlyZero(), mulSame(), Arcane::operator*(), Arcane::operator*(), operator*=(), operator+(), operator-(), operator-(), Arcane::operator/(), operator/=(), Arcane::operator<(), operator=(), Real3x3Proxy(), Real3x3Proxy(), reset(), sub(), and subSame().
The documentation for this class was generated from the following files:
Real3x3Proxy.h
arcane/src/arcane/utils/Real3x3.cc