Arcane: Arcane::Materials::EnvCell Class Reference
Arcane::Materials::EnvCell Class Reference
Materials and Media.
Arcane cell of an environment.
#include <arcane/core/materials/MatItem.h>
Public Member Functions
__host__ __device__ EnvCell (const matimpl::ConstituentItemBase &item_base)
__host__ __device__ EnvCell (const ComponentCell &item)
__host__ __device__ Int32 nbMaterial () const
__host__ __device__ AllEnvCell allEnvCell () const
Cell containing information about all environments.
__host__ __device__ MatCell cell (Integer i) const
i-th material cell of this cell
IMeshEnvironment * environment () const
Associated environment.
__host__ __device__ Int32 environmentId () const
Environment identifier.
__host__ __device__ CellMatCellEnumerator subMatItems () const
Enumerator over the material cells of this cell.
Public Member Functions inherited from Arcane::Materials::ConstituentItem
__host__ __device__ ConstituentItem (const matimpl::ConstituentItemBase &mii)
__host__ __device__ operator ComponentItemLocalId () const
Conversion operator to a ComponentItemLocalId.
__host__ __device__ MatVarIndex _varIndex () const
__host__ __device__ matimpl::ConstituentItemBase constituentItemBase () const
IMeshComponent * component () const
Associated constituent.
__host__ __device__ Int32 componentId () const
Component identifier in the list of components of this type.
__host__ __device__ bool null () const
Indicates if it is the null cell.
__host__ __device__ ComponentCell superCell () const
Higher-level cell in the hierarchy.
__host__ __device__ Int32 level () const
Hierarchical level of the entity.
__host__ __device__ Int32 nbSubItem () const
Number of sub-elements.
Cell globalCell () const
Global cell.
__host__ __device__ CellLocalId globalCellId () const
localId() of the global cell
Int64 componentUniqueId () const
Unique number of the constituent entity.
__host__ __device__ CellComponentCellEnumerator subItems () const
List of sub-constituents of this entity.
Additional Inherited Members
Protected Member Functions inherited from Arcane::Materials::ConstituentItem
__host__ __device__ matimpl::ConstituentItemBase _subItemBase (Int32 index) const
__host__ __device__ matimpl::ConstituentItemBase _superItemBase () const
__host__ __device__ ConstituentItemIndex _firstSubConstituentLocalId () const
Static Protected Member Functions inherited from Arcane::Materials::ConstituentItem
static __host__ __device__ void _checkLevel (matimpl::ConstituentItemBase item_base, Int32 expected_level)
static void _badConversion (matimpl::ConstituentItemBase item_base, Int32 level, Int32 expected_level)
Protected Attributes inherited from Arcane::Materials::ConstituentItem
ConstituentItemIndex m_constituent_item_index
ComponentItemSharedInfo * m_shared_info = nullptr
Detailed Description
Arcane cell of an environment.
Such a cell contains information about the materials of an environment for a given cell.
There is a special cell, called the null cell, for which null() is true and which represents an invalid cell. In the case of the invalid cell, none of the other class methods should be called, under penalty of causing a crash.
Warning
These meshes are invalidated as soon as the list of meshes of a material or environment changes. Therefore, one must not keep a cell of this type between two changes of this list.
Definition at line 106 of file core/materials/MatItem.h.
Constructor & Destructor Documentation
EnvCell() [1/2]
__host__ __device__ Arcane::Materials::EnvCell::EnvCell (const matimpl::ConstituentItemBase & item_base) inline explicit
Definition at line 111 of file core/materials/MatItem.h.
EnvCell() [2/2]
__host__ __device__ Arcane::Materials::EnvCell::EnvCell (const ComponentCell & item) inline explicit
Definition at line 118 of file core/materials/MatItem.h.
Member Function Documentation
allEnvCell()
__host__ __device__ AllEnvCell Arcane::Materials::EnvCell::allEnvCell () const inline
Cell containing information about all environments.
Definition at line 214 of file core/materials/MatItem.h.
cell()
__host__ __device__ MatCell Arcane::Materials::EnvCell::cell (Integer i) const inline
i-th material cell of this cell
Definition at line 133 of file core/materials/MatItem.h.
environment()
IMeshEnvironment * Arcane::Materials::EnvCell::environment () const inline
Associated environment.
Definition at line 136 of file core/materials/MatItem.h.
environmentId()
__host__ __device__ Int32 Arcane::Materials::EnvCell::environmentId () const inline
Environment identifier.
Definition at line 139 of file core/materials/MatItem.h.
References Arcane::Materials::ConstituentItem::componentId().
Referenced by Arcane::Materials::CellEnvironmentVariableScalarRef< DataType_ >::envValue(), and Arcane::Materials::CellMaterialVariableScalarRef< DataType_ >::envValue().
nbMaterial()
__host__ __device__ Int32 Arcane::Materials::EnvCell::nbMaterial () const inline
Definition at line 127 of file core/materials/MatItem.h.
subMatItems()
__host__ __device__ CellMatCellEnumerator Arcane::Materials::EnvCell::subMatItems () const inline
Enumerator over the material cells of this cell.
Definition at line 142 of file core/materials/MatItem.h.
The documentation for this class was generated from the following file:
core/materials/MatItem.h