Arcane: Arcane::DirNode Class Reference
Arcane::DirNode Class Reference
Cartesian meshes.
Node before and after a node following a direction.
#include <arcane/cartesianmesh/NodeDirectionMng.h>
Public Member Functions
Node previous () const
Previous cell.
NodeLocalId previousId () const
Previous cell.
Node next () const
Next cell.
NodeLocalId nextId () const
Next cell.
Int32 cellIndex (Int32 position) const
Index in the list of cells for this node in a cell based on its position.
CellLocalId cellId (Int32 position) const
Local index of a cell based on its position relative to this node.
Cell cell (Int32 position) const
Cell based on its position relative to this node.
Cell nextLeftCell () const
NextLeftCell: Cell in front and to the left in the direction.
Cell nextRightCell () const
NextRightCell: Cell in front and to the right in the direction.
Cell previousRightCell () const
PreviousRightCell: Cell behind and to the right in the direction.
Cell previousLeftCell () const
PreviousLeftCell: Cell behind and to the left in the direction.
CellLocalId nextLeftCellId () const
NextLeftCell: Cell in front and to the left in the direction.
CellLocalId nextRightCellId () const
NextRightCell: Cell in front and to the right in the direction.
CellLocalId previousRightCellId () const
PreviousRightCell: Cell behind and to the right in the direction.
CellLocalId previousLeftCellId () const
PreviousLeftCell: Cell behind and to the left in the direction.
Cell topNextLeftCell () const
TopNextLeftCell: Cell in front and to the left in the direction.
Cell topNextRightCell () const
TopNextRightCell: Cell in front and to the right in the direction.
Cell topPreviousRightCell () const
TopPreviousRightCell: Cell behind and to the right in the direction.
Cell topPreviousLeftCell () const
TopPreviousLeftCell: Cell behind and to the left in the direction.
CellLocalId topNextLeftCellId () const
TopNextLeftCell: Cell in front and to the left in the direction.
CellLocalId topNextRightCellId () const
TopNextRightCell: Cell in front and to the right in the direction.
CellLocalId topPreviousRightCellId () const
TopPreviousRightCell: Cell behind and to the right in the direction.
CellLocalId topPreviousLeftCellId () const
TopPreviousLeftCell: Cell behind and to the left in the direction.
Friends
class DirNodeLocalId
Detailed Description
Node before and after a node following a direction.
Instances of this class are temporary and constructed via NodeDirectionMng::node().
Definition at line 40 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
Member Function Documentation
cell()
Cell Arcane::DirNode::cell (Int32 position) const inline
Cell based on its position relative to this node.
Possible values for position are given by the enumeration eCellNodePosition.
Definition at line 110 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellIndex().
Referenced by nextLeftCell(), nextRightCell(), previousLeftCell(), previousRightCell(), topNextLeftCell(), topNextRightCell(), topPreviousLeftCell(), and topPreviousRightCell().
cellId()
CellLocalId Arcane::DirNode::cellId (Int32 position) const inline
Local index of a cell based on its position relative to this node.
Possible values for position are given by the enumeration eCellNodePosition.
Definition at line 99 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellIndex().
Referenced by nextLeftCellId(), nextRightCellId(), previousLeftCellId(), previousRightCellId(), topNextLeftCellId(), topNextRightCellId(), topPreviousLeftCellId(), and topPreviousRightCellId().
cellIndex()
Int32 Arcane::DirNode::cellIndex (Int32 position) const inline
Index in the list of cells for this node in a cell based on its position.
Possible values for position are given by the enumeration eCellNodePosition.
Definition at line 92 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
Referenced by cell(), and cellId().
next()
Node Arcane::DirNode::next () const inline
Next cell.
Definition at line 82 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
nextId()
NodeLocalId Arcane::DirNode::nextId () const inline
Next cell.
Definition at line 84 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
nextLeftCell()
Cell Arcane::DirNode::nextLeftCell () const inline
NextLeftCell: Cell in front and to the left in the direction.
Definition at line 117 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
nextLeftCellId()
CellLocalId Arcane::DirNode::nextLeftCellId () const inline
NextLeftCell: Cell in front and to the left in the direction.
Definition at line 126 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
nextRightCell()
Cell Arcane::DirNode::nextRightCell () const inline
NextRightCell: Cell in front and to the right in the direction.
Definition at line 119 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
nextRightCellId()
CellLocalId Arcane::DirNode::nextRightCellId () const inline
NextRightCell: Cell in front and to the right in the direction.
Definition at line 128 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
previous()
Node Arcane::DirNode::previous () const inline
Previous cell.
Definition at line 78 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
previousId()
NodeLocalId Arcane::DirNode::previousId () const inline
Previous cell.
Definition at line 80 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
previousLeftCell()
Cell Arcane::DirNode::previousLeftCell () const inline
PreviousLeftCell: Cell behind and to the left in the direction.
Definition at line 123 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
previousLeftCellId()
CellLocalId Arcane::DirNode::previousLeftCellId () const inline
PreviousLeftCell: Cell behind and to the left in the direction.
Definition at line 132 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
previousRightCell()
Cell Arcane::DirNode::previousRightCell () const inline
PreviousRightCell: Cell behind and to the right in the direction.
Definition at line 121 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
previousRightCellId()
CellLocalId Arcane::DirNode::previousRightCellId () const inline
PreviousRightCell: Cell behind and to the right in the direction.
Definition at line 130 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
topNextLeftCell()
Cell Arcane::DirNode::topNextLeftCell () const inline
TopNextLeftCell: Cell in front and to the left in the direction.
Definition at line 135 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
topNextLeftCellId()
CellLocalId Arcane::DirNode::topNextLeftCellId () const inline
TopNextLeftCell: Cell in front and to the left in the direction.
Definition at line 144 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
topNextRightCell()
Cell Arcane::DirNode::topNextRightCell () const inline
TopNextRightCell: Cell in front and to the right in the direction.
Definition at line 137 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
topNextRightCellId()
CellLocalId Arcane::DirNode::topNextRightCellId () const inline
TopNextRightCell: Cell in front and to the right in the direction.
Definition at line 146 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
topPreviousLeftCell()
Cell Arcane::DirNode::topPreviousLeftCell () const inline
TopPreviousLeftCell: Cell behind and to the left in the direction.
Definition at line 141 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
topPreviousLeftCellId()
CellLocalId Arcane::DirNode::topPreviousLeftCellId () const inline
TopPreviousLeftCell: Cell behind and to the left in the direction.
Definition at line 150 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
topPreviousRightCell()
Cell Arcane::DirNode::topPreviousRightCell () const inline
TopPreviousRightCell: Cell behind and to the right in the direction.
Definition at line 139 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cell().
topPreviousRightCellId()
CellLocalId Arcane::DirNode::topPreviousRightCellId () const inline
TopPreviousRightCell: Cell behind and to the right in the direction.
Definition at line 148 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
References cellId().
Friends And Related Symbol Documentation
DirNodeLocalId
friend class DirNodeLocalId friend
Definition at line 43 of file src/arcane/cartesianmesh/NodeDirectionMng.h.
The documentation for this class was generated from the following file:
src/arcane/cartesianmesh/NodeDirectionMng.h