Alien: Alien::IMatrix Class Reference
Alien::IMatrix Class Reference abstract
Interface for all matrices.
#include <core/alien/data/IMatrix.h>
Public Member Functions
virtual void visit (ICopyOnWriteMatrix &) const =0
Visit method.
virtual const ISpace & rowSpace () const =0
Get row space associated to the matrix.
virtual const ISpace & colSpace () const =0
Get col space associated to the matrix.
virtual MultiMatrixImpl * impl ()=0
Get the multimatrix implementation.
virtual const MultiMatrixImpl * impl () const =0
Get the multimatrix implementation.
Protected Member Functions
IMatrix ()
Constructor.
Private Member Functions
IMatrix (const IMatrix &)=delete
IMatrix (IMatrix &&)=delete
void operator= (const IMatrix &)=delete
void operator= (IMatrix &&)=delete
Detailed Description
Interface for all matrices.
Definition at line 50 of file IMatrix.h.
Constructor & Destructor Documentation
IMatrix()
Alien::IMatrix::IMatrix () inline protected
Constructor.
Definition at line 54 of file IMatrix.h.
Referenced by Alien::CompositeMatrix::operator()(), and Alien::CompositeMatrix::operator()().
~IMatrix()
virtual Alien::IMatrix::~IMatrix () inline virtual
Definition at line 65 of file IMatrix.h.
Member Function Documentation
colSpace()
virtual const ISpace & Alien::IMatrix::colSpace () const pure virtual
Get col space associated to the matrix.
Returns
The col space
Implemented in Alien::BlockMatrix, Alien::CompositeMatrix, Alien::Matrix, Alien::Move::MatrixData, Alien::NullMatrix, Alien::RedistributedMatrix, and Alien::VBlockMatrix.
impl() [1/2]
virtual const MultiMatrixImpl * Alien::IMatrix::impl () const pure virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implemented in Alien::BlockMatrix, Alien::CompositeMatrix, Alien::Matrix, Alien::Move::MatrixData, Alien::NullMatrix, Alien::RedistributedMatrix, and Alien::VBlockMatrix.
impl() [2/2]
virtual MultiMatrixImpl * Alien::IMatrix::impl () pure virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implemented in Alien::BlockMatrix, Alien::CompositeMatrix, Alien::Matrix, Alien::Move::MatrixData, Alien::NullMatrix, Alien::RedistributedMatrix, and Alien::VBlockMatrix.
Referenced by Alien::LinearAlgebraExpr< Tag, TagV >::add(), Alien::SchurOp::computePrimarySystem(), Alien::LinearAlgebraExpr< Tag, TagV >::copy(), Alien::LinearAlgebra< Tag, TagV >::diagonal(), Alien::LinearAlgebraExpr< Tag, TagV >::diagonal(), Alien::LinearAlgebra< Tag, TagV >::dump(), Alien::LinearAlgebraExpr< Tag, TagV >::dump(), Alien::LinearAlgebra< Tag, TagV >::mult(), Alien::LinearAlgebraExpr< Tag, TagV >::mult(), Alien::LinearAlgebraExpr< Tag, TagV >::mult(), Alien::LinearAlgebraExpr< Tag, TagV >::norm2(), Alien::NormalizeOpt::normalize(), Alien::LinearAlgebraExpr< Tag, TagV >::scal(), and Alien::LinearSolver< Tag >::solve().
rowSpace()
virtual const ISpace & Alien::IMatrix::rowSpace () const pure virtual
Get row space associated to the matrix.
Returns
The row space
Implemented in Alien::BlockMatrix, Alien::CompositeMatrix, Alien::Matrix, Alien::Move::MatrixData, Alien::NullMatrix, Alien::RedistributedMatrix, and Alien::VBlockMatrix.
visit()
virtual void Alien::IMatrix::visit (ICopyOnWriteMatrix &) const pure virtual
Visit method.
Implemented in Alien::BlockMatrix, Alien::CompositeMatrix, Alien::Matrix, Alien::Move::MatrixData, Alien::NullMatrix, Alien::RedistributedMatrix, and Alien::VBlockMatrix.
The documentation for this class was generated from the following file:
IMatrix.h