Arcane: Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor > Class Template Reference
Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor > Class Template Reference
Write view on a scalar constituent variable.
#include <arcane/accelerator/MaterialVariableViews.h>
Public Member Functions
MatItemVariableScalarOutViewT (const ViewBuildInfo &vbi, IMeshMaterialVariable *var, ArrayView< DataType > *v)
__host__ __device__ Accessor operator[] (ComponentItemLocalId lid) const
Access operator for entity item.
__host__ __device__ Accessor operator[] (PureMatVarIndex pmvi) const
__host__ __device__ Accessor operator[] (ItemIndexType item) const
Override to access the global value from the cell id.
__host__ __device__ Accessor value (ComponentItemLocalId lid) const
Access operator for entity item.
__host__ __device__ void setValue (ComponentItemLocalId lid, const DataType &v) const
Positions the value for entity item at v.
__host__ __device__ Accessor value0 (PureMatVarIndex idx) const
Public Member Functions inherited from Arcane::Accelerator::MatVariableViewBase
MatVariableViewBase (const ViewBuildInfo &, IMeshMaterialVariable *)
Private Types
using DataType = typename Accessor::ValueType
using DataTypeReturnType = DataType&
using ItemIndexType = typename ItemTraitsT<ItemType>::LocalIdType
Private Attributes
ArrayView< DataType > * m_value = nullptr
Detailed Description
template<typename ItemType, typename Accessor>
class Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >
Write view on a scalar constituent variable.
Definition at line 115 of file MaterialVariableViews.h.
Member Typedef Documentation
DataType
template<typename ItemType, typename Accessor> using Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::DataType = typename Accessor::ValueType private
Definition at line 120 of file MaterialVariableViews.h.
DataTypeReturnType
template<typename ItemType, typename Accessor> using Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::DataTypeReturnType = DataType& private
Definition at line 121 of file MaterialVariableViews.h.
ItemIndexType
template<typename ItemType, typename Accessor> using Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::ItemIndexType = typename ItemTraitsT<ItemType>::LocalIdType private
Definition at line 122 of file MaterialVariableViews.h.
Constructor & Destructor Documentation
MatItemVariableScalarOutViewT()
template<typename ItemType, typename Accessor> Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::MatItemVariableScalarOutViewT (const ViewBuildInfo & vbi, IMeshMaterialVariable * var, ArrayView< DataType > * v) inline
Definition at line 130 of file MaterialVariableViews.h.
Member Function Documentation
operator[]() [1/3]
template<typename ItemType, typename Accessor> __host__ __device__ Accessor Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::operator[] (ComponentItemLocalId lid) const inline
Access operator for entity item.
Definition at line 137 of file MaterialVariableViews.h.
References Arcane::Materials::MatVarIndex::arrayIndex(), Arcane::Materials::ConstituentItemLocalId::localId(), and Arcane::Materials::MatVarIndex::valueIndex().
operator[]() [2/3]
template<typename ItemType, typename Accessor> __host__ __device__ Accessor Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::operator[] (ItemIndexType item) const inline
Override to access the global value from the cell id.
Definition at line 148 of file MaterialVariableViews.h.
operator[]() [3/3]
template<typename ItemType, typename Accessor> __host__ __device__ Accessor Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::operator[] (PureMatVarIndex pmvi) const inline
Definition at line 142 of file MaterialVariableViews.h.
setValue()
template<typename ItemType, typename Accessor> __host__ __device__ void Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::setValue (ComponentItemLocalId lid, const DataType & v) const inline
Positions the value for entity item at v.
Definition at line 161 of file MaterialVariableViews.h.
References Arcane::Materials::MatVarIndex::arrayIndex(), Arcane::Materials::ConstituentItemLocalId::localId(), and Arcane::Materials::MatVarIndex::valueIndex().
value()
template<typename ItemType, typename Accessor> __host__ __device__ Accessor Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::value (ComponentItemLocalId lid) const inline
Access operator for entity item.
Definition at line 155 of file MaterialVariableViews.h.
References Arcane::Materials::MatVarIndex::arrayIndex(), Arcane::Materials::ConstituentItemLocalId::localId(), and Arcane::Materials::MatVarIndex::valueIndex().
value0()
template<typename ItemType, typename Accessor> __host__ __device__ Accessor Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::value0 (PureMatVarIndex idx) const inline
Definition at line 166 of file MaterialVariableViews.h.
Member Data Documentation
m_value
template<typename ItemType, typename Accessor> ArrayView<DataType>* Arcane::Accelerator::MatItemVariableScalarOutViewT< ItemType, Accessor >::m_value = nullptr private
Definition at line 173 of file MaterialVariableViews.h.
The documentation for this class was generated from the following file:
MaterialVariableViews.h