Arcane: Arcane::AnyItem::LinkFamilyInternal::LinkData Class Reference
Arcane::AnyItem::LinkFamilyInternal::LinkData Class Reference
Data per link.
#include <arcane/core/anyitem/AnyItemLinkFamily.h>
Public Member Functions
Integer groupIndex () const
Identifier of the group associated with the item referenced by this LinkData.
Integer varIndex () const
LocalId identifier of the item referenced in its original IItemFamily.
Integer localId () const
LocalId identifier of the item referenced in its AnyItemFamily.
bool operator== (const LinkData &data) const
Comparison operator.
Private Member Functions
void setGroupIndex (Integer group_index)
void setLocalId (Integer local_id)
void setVarIndex (Integer item_local_id)
Private Attributes
unsigned m_group_index
Index of the group from which this item comes.
unsigned m_local_id
Identifier in the global indexing of AnyItem::Family.
Integer m_var_index
Index for partials, localId otherwise.
Friends
class LinkFamilyInternal
Detailed Description
Data per link.
Definition at line 75 of file AnyItemLinkFamily.h.
Constructor & Destructor Documentation
LinkData()
Arcane::AnyItem::LinkFamilyInternal::LinkData::LinkData () inline
Definition at line 130 of file AnyItemLinkFamily.h.
Member Function Documentation
groupIndex()
Integer Arcane::AnyItem::LinkFamilyInternal::LinkData::groupIndex () const inline
Identifier of the group associated with the item referenced by this LinkData.
Definition at line 136 of file AnyItemLinkFamily.h.
References m_group_index.
Referenced by Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::VariableArray< DataType >::operator[](), and Arcane::AnyItem::VariableArray< DataType >::operator[]().
localId()
Integer Arcane::AnyItem::LinkFamilyInternal::LinkData::localId () const inline
LocalId identifier of the item referenced in its AnyItemFamily.
Definition at line 140 of file AnyItemLinkFamily.h.
References m_local_id.
operator==()
bool Arcane::AnyItem::LinkFamilyInternal::LinkData::operator== (const LinkData & data) const inline
Comparison operator.
Definition at line 142 of file AnyItemLinkFamily.h.
References m_group_index, m_local_id, and m_var_index.
setGroupIndex()
void Arcane::AnyItem::LinkFamilyInternal::LinkData::setGroupIndex (Integer group_index) inline private
Definition at line 149 of file AnyItemLinkFamily.h.
setLocalId()
void Arcane::AnyItem::LinkFamilyInternal::LinkData::setLocalId (Integer local_id) inline private
Definition at line 150 of file AnyItemLinkFamily.h.
setVarIndex()
void Arcane::AnyItem::LinkFamilyInternal::LinkData::setVarIndex (Integer item_local_id) inline private
Definition at line 151 of file AnyItemLinkFamily.h.
varIndex()
Integer Arcane::AnyItem::LinkFamilyInternal::LinkData::varIndex () const inline
LocalId identifier of the item referenced in its original IItemFamily.
Definition at line 138 of file AnyItemLinkFamily.h.
References m_var_index.
Referenced by Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::Variable< DataType >::operator[](), Arcane::AnyItem::VariableArray< DataType >::operator[](), and Arcane::AnyItem::VariableArray< DataType >::operator[]().
Friends And Related Symbol Documentation
LinkFamilyInternal
friend class LinkFamilyInternal friend
Definition at line 77 of file AnyItemLinkFamily.h.
Member Data Documentation
m_group_index
unsigned Arcane::AnyItem::LinkFamilyInternal::LinkData::m_group_index private
Index of the group from which this item comes.
Definition at line 155 of file AnyItemLinkFamily.h.
Referenced by groupIndex(), and operator==().
m_local_id
unsigned Arcane::AnyItem::LinkFamilyInternal::LinkData::m_local_id private
Identifier in the global indexing of AnyItem::Family.
Definition at line 156 of file AnyItemLinkFamily.h.
Referenced by localId(), and operator==().
m_var_index
Integer Arcane::AnyItem::LinkFamilyInternal::LinkData::m_var_index private
Index for partials, localId otherwise.
Definition at line 157 of file AnyItemLinkFamily.h.
Referenced by operator==(), and varIndex().
The documentation for this class was generated from the following file:
AnyItemLinkFamily.h