Alien: Alien::NullMatrix Class Reference
Alien::NullMatrix Class Reference final
Public Member Functions
NullMatrix (const NullMatrix &)=delete
NullMatrix (NullMatrix &&)=delete
NullMatrix & operator= (NullMatrix &&vector)=delete
NullMatrix & operator= (const NullMatrix &)=delete
void visit (ICopyOnWriteMatrix &) const
Visit method.
const MatrixDistribution & distribution () const
const Space & rowSpace () const
Get row space associated to the matrix.
const Space & colSpace () const
Get col space associated to the matrix.
MultiMatrixImpl * impl ()
Get the multimatrix implementation.
const MultiMatrixImpl * impl () const
Get the multimatrix implementation.
Private Attributes
Space m_space
MatrixDistribution m_distribution
Additional Inherited Members
Protected Member Functions inherited from Alien::IMatrix
IMatrix ()
Constructor.
Detailed Description
Definition at line 34 of file NullMatrix.h.
Constructor & Destructor Documentation
NullMatrix()
Alien::NullMatrix::NullMatrix ()
Definition at line 35 of file NullMatrix.cc.
~NullMatrix()
Alien::NullMatrix::~NullMatrix () inline
Definition at line 39 of file NullMatrix.h.
Member Function Documentation
colSpace()
const Space & Alien::NullMatrix::colSpace () const virtual
Get col space associated to the matrix.
Returns
The col space
Implements Alien::IMatrix.
Definition at line 65 of file NullMatrix.cc.
References colSpace().
Referenced by colSpace().
distribution()
const MatrixDistribution & Alien::NullMatrix::distribution () const
Definition at line 49 of file NullMatrix.cc.
impl() [1/2]
MultiMatrixImpl * Alien::NullMatrix::impl () virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 73 of file NullMatrix.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiMatrixImpl * Alien::NullMatrix::impl () const virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 82 of file NullMatrix.cc.
References impl().
rowSpace()
const Space & Alien::NullMatrix::rowSpace () const virtual
Get row space associated to the matrix.
Returns
The row space
Implements Alien::IMatrix.
Definition at line 57 of file NullMatrix.cc.
References rowSpace().
Referenced by rowSpace().
visit()
void Alien::NullMatrix::visit (ICopyOnWriteMatrix &) const virtual
Visit method.
Implements Alien::IMatrix.
Definition at line 41 of file NullMatrix.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_distribution
MatrixDistribution Alien::NullMatrix::m_distribution private
Definition at line 62 of file NullMatrix.h.
m_space
Space Alien::NullMatrix::m_space private
Definition at line 61 of file NullMatrix.h.
The documentation for this class was generated from the following files:
NullMatrix.h
NullMatrix.cc