Alien: Alien::Block Class Reference
Alien::Block Class Reference final
Matrix Constructor » Block related API
Block elements for block matrices.
#include <core/alien/core/block/Block.h>
Classes
struct Internal
Internal structure for square or rectangular blocks.
Public Member Functions
Block (Arccore::Integer block_size)
Square block constructor.
Block (Arccore::Integer block_sizeX, Arccore::Integer block_sizeY)
Rectangular block constructor.
Block (const Block &block)
Copy constructor.
~Block ()=default
Free resources.
Block (Block &&block)=delete
Block & operator= (const Block &block)=delete
Arccore::Integer size () const
Get square block size.
Arccore::Integer sizeX () const
Get rectangular block size in the "X" direction.
Arccore::Integer sizeY () const
Get rectangular block size in the "Y" direction.
std::shared_ptr< Block > clone () const
Clone this object.
Private Attributes
std::shared_ptr< Internal > m_internal
Actual implementation.
Detailed Description
Block elements for block matrices.
Defines block parameters, for square or rectangulars block entries in a block matrix. All blocks in the matrix are identical in term of size.
Definition at line 44 of file Block.h.
Constructor & Destructor Documentation
Block() [1/3]
Alien::Block::Block (Arccore::Integer block_size) explicit
Square block constructor.
Parameters
[in] block_size Size of the block
Referenced by Block(), Block(), and ~Block().
Block() [2/3]
Alien::Block::Block (Arccore::Integer block_sizeX, Arccore::Integer block_sizeY)
Rectangular block constructor.
Parameters
[in] block_sizeX Size of the block in "X" direction
[in] block_sizeY Size of the block in "Y" direction
References Block().
Block() [3/3]
Alien::Block::Block (const Block & block)
Copy constructor.
Parameters
[in] Block related API The block to copy
Definition at line 68 of file Block.cc.
References Block(), and m_internal.
Member Function Documentation
clone()
std::shared_ptr< Block > Alien::Block::clone () const
Clone this object.
Returns
A copy of this object
Definition at line 117 of file Block.cc.
Referenced by Alien::MultiMatrixImpl::setBlockInfos(), Alien::MultiVectorImpl::setBlockInfos(), and ~Block().
size()
Integer Alien::Block::size () const
Get square block size.
Returns
The size of the block
Definition at line 90 of file Block.cc.
References m_internal.
Referenced by Alien::NormalizeOpt::_normalize(), Alien::NormalizeOpt::_normalize(), Alien::computeBlockOffsets(), Alien::computeBlockOffsets(), Alien::SchurOp::computePrimarySystem(), Alien::NormalizeOpt::Op::Op(), Alien::NormalizeOpt::Op2::Op2(), Alien::IVectorImpl::scalarizedGlobalSize(), Alien::IVectorImpl::scalarizedLocalSize(), Alien::IVectorImpl::scalarizedOffset(), and ~Block().
sizeX()
Integer Alien::Block::sizeX () const
Get rectangular block size in the "X" direction.
Returns
Block size in the "X" direction
Definition at line 99 of file Block.cc.
References m_internal.
Referenced by Alien::Block::Internal::newFixedSizeBlock(), and ~Block().
sizeY()
Integer Alien::Block::sizeY () const
Get rectangular block size in the "Y" direction.
Returns
Block size in the "Y" direction
Definition at line 108 of file Block.cc.
References m_internal.
Referenced by Alien::Block::Internal::newFixedSizeBlock(), and ~Block().
Member Data Documentation
m_internal
std::shared_ptr<Internal> Alien::Block::m_internal private
Actual implementation.
Definition at line 100 of file Block.h.
Referenced by Block(), size(), sizeX(), and sizeY().
The documentation for this class was generated from the following files:
Block.h
Block.cc