Alien: Alien::StreamMatrixBuilderT< ValueT >::BaseInserter Class Reference
Alien::StreamMatrixBuilderT< ValueT >::BaseInserter Class Reference
Public Member Functions
void init ()
@ Méthodes visibles de l'extérieur
Integer getId () const
Identifiant de l'inserter dans son StreamMatrixBuilder.
Integer size ()
Nombre d'itération dans l'inserter.
Integer count ()
Nombre de données dans l'inserter.
void end ()
Termine l'inserter (déallocation des données).
Protected Member Functions
BaseInserter (StreamMatrixBuilderT< ValueT > *parent, Integer id)
void setMatrixValues (ValueT *matrix_values, Integer block_size=1)
void _startTimer ()
void _stopTimer ()
Protected Attributes
Integer m_id
Integer m_index
Integer m_current_size
Integer * m_current_k
ValueT __restrict__ * m_values
Integer m_count
Integer m_size
Integer m_block_size
UniqueArray< Integer > m_n
UniqueArray< Integer > m_row_index
UniqueArray< Integer > m_col_index
UniqueArray< Integer > m_data_index
positon of entry in the Matrix CSR structure
StreamMatrixBuilderT< ValueT > * m_parent
Friends
class StreamMatrixBuilderT< ValueT >
Detailed Description
template<typename ValueT = Real>
class Alien::StreamMatrixBuilderT< ValueT >::BaseInserter
Definition at line 19 of file StreamMatrixBuilderInserter.h.
Constructor & Destructor Documentation
BaseInserter() [1/2]
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::BaseInserter () protected
Definition at line 32 of file StreamMatrixBuilderInserterT.h.
BaseInserter() [2/2]
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::BaseInserter (StreamMatrixBuilderT< ValueT > * parent, Integer id) protected
Definition at line 41 of file StreamMatrixBuilderInserterT.h.
~BaseInserter()
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::~BaseInserter () protected virtual
Definition at line 57 of file StreamMatrixBuilderInserterT.h.
Member Function Documentation
_startTimer()
template<typename ValueT = Real> void Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::_startTimer () inline protected
Definition at line 46 of file StreamMatrixBuilderInserter.h.
_stopTimer()
template<typename ValueT = Real> void Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::_stopTimer () inline protected
Definition at line 47 of file StreamMatrixBuilderInserter.h.
count()
template<typename ValueT> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::count ()
Nombre de données dans l'inserter.
Definition at line 130 of file StreamMatrixBuilderInserterT.h.
Referenced by Alien::StreamMatrixBuilderT< ValueT >::computeProfile().
end()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::end ()
Termine l'inserter (déallocation des données).
Definition at line 84 of file StreamMatrixBuilderInserterT.h.
References init(), and m_data_index.
getId()
template<typename ValueT> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::getId () const
Identifiant de l'inserter dans son StreamMatrixBuilder.
Definition at line 76 of file StreamMatrixBuilderInserterT.h.
Referenced by Alien::StreamMatrixBuilderT< ValueT >::computeProfile().
init()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::init ()
@ Méthodes visibles de l'extérieur
Definition at line 62 of file StreamMatrixBuilderInserterT.h.
Referenced by end().
setMatrixValues()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::setMatrixValues (ValueT * matrix_values, Integer block_size = 1) protected
Definition at line 96 of file StreamMatrixBuilderInserterT.h.
size()
template<typename ValueT> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::size ()
Nombre d'itération dans l'inserter.
Definition at line 121 of file StreamMatrixBuilderInserterT.h.
Referenced by Alien::StreamMatrixBuilderT< ValueT >::computeProfile().
Friends And Related Symbol Documentation
StreamMatrixBuilderT< ValueT >
template<typename ValueT = Real> friend class StreamMatrixBuilderT< ValueT > friend
Definition at line 1 of file StreamMatrixBuilderInserter.h.
Member Data Documentation
m_block_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_block_size protected
Definition at line 60 of file StreamMatrixBuilderInserter.h.
m_col_index
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_col_index protected
Definition at line 63 of file StreamMatrixBuilderInserter.h.
m_count
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_count protected
Definition at line 58 of file StreamMatrixBuilderInserter.h.
m_current_k
template<typename ValueT = Real> Integer* Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_current_k protected
Definition at line 52 of file StreamMatrixBuilderInserter.h.
m_current_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_current_size protected
Definition at line 51 of file StreamMatrixBuilderInserter.h.
m_data_index
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_data_index protected
positon of entry in the Matrix CSR structure
Definition at line 65 of file StreamMatrixBuilderInserter.h.
Referenced by Alien::StreamMatrixBuilderT< ValueT >::computeProfile(), and end().
m_id
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_id protected
Definition at line 49 of file StreamMatrixBuilderInserter.h.
m_index
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_index protected
Definition at line 50 of file StreamMatrixBuilderInserter.h.
m_n
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_n protected
Definition at line 61 of file StreamMatrixBuilderInserter.h.
m_parent
template<typename ValueT = Real> StreamMatrixBuilderT<ValueT>* Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_parent protected
Definition at line 66 of file StreamMatrixBuilderInserter.h.
m_row_index
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_row_index protected
Definition at line 62 of file StreamMatrixBuilderInserter.h.
m_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_size protected
Definition at line 59 of file StreamMatrixBuilderInserter.h.
m_values
template<typename ValueT = Real> ValueT __restrict__* Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_values protected
Definition at line 56 of file StreamMatrixBuilderInserter.h.
The documentation for this class was generated from the following files:
StreamMatrixBuilderInserter.h
StreamMatrixBuilderInserterT.h