Arcane: Arcane::Numerics::ParallelCorefinementService Class Reference
Arcane::Numerics::ParallelCorefinementService Class Reference
Classes
class Internal
Public Member Functions
ParallelCorefinementService (const Arcane::ServiceBuildInfo &sbi)
virtual ~ParallelCorefinementService ()
void init (const FaceGroup &masterGroup, const FaceGroup &slaveGroup, const Real boxTolerance, IGeometry *geometry)
Initialization.
void update ()
Update.
const FaceFaceContactList & contacts ()
Access to computed contacts.
Private Attributes
FaceGroup m_master_group
FaceGroup m_slave_group
Real m_box_tolerance
IGeometry * m_geometry
FaceFaceContactList m_contacts
Internal * m_internal
Detailed Description
Definition at line 39 of file ParallelCorefinementService.h.
Constructor & Destructor Documentation
ParallelCorefinementService()
ParallelCorefinementService::ParallelCorefinementService (const Arcane::ServiceBuildInfo & sbi)
Class constructor
Definition at line 254 of file ParallelCorefinementService.cc.
~ParallelCorefinementService()
ParallelCorefinementService::~ParallelCorefinementService () virtual
Class destructor
Definition at line 265 of file ParallelCorefinementService.cc.
Member Function Documentation
contacts()
const IParallelCorefinement::FaceFaceContactList & ParallelCorefinementService::contacts ()
Access to computed contacts.
Definition at line 735 of file ParallelCorefinementService.cc.
init()
void ParallelCorefinementService::init (const FaceGroup & masterGroup, const FaceGroup & slaveGroup, const Real boxTolerance, IGeometry * geometry)
Initialization.
Definition at line 274 of file ParallelCorefinementService.cc.
update()
void ParallelCorefinementService::update ()
Update.
Definition at line 289 of file ParallelCorefinementService.cc.
References Arcane::Array< T >::add(), Arcane::Real3::add(), Arcane::MessagePassing::ISerializeMessageList::addMessage(), Arcane::Real3::addSame(), Arcane::IParallelMng::allGather(), Arcane::BasicSerializer::allocateBuffer(), Arcane::IParallelMng::commRank(), Arcane::IParallelMng::commSize(), Arcane::Numerics::ISurfaceUtils::computeSurfaceContact(), Arcane::IParallelMng::createSerializeMessageList(), Arcane::Numerics::ISurfaceUtils::createSurface(), Arcane::DT_Int64, Arcane::DT_Real, Arcane::ItemGroup::empty(), ENUMERATE_FACE, Arcane::BasicSerializer::get(), Arcane::BasicSerializer::getInteger(), Arcane::BasicSerializer::getReal(), Arcane::Item::isOwn(), Arcane::IParallelMng::isParallel(), Arcane::Item::localId(), Arcane::math::max(), Arcane::Trace::Medium, Arcane::math::min(), Arcane::ISerializer::ModeGet, Arcane::ISerializer::ModePut, Arcane::ItemWithNodes::nodes(), Arcane::math::normeR3(), Arcane::Item::null(), Arcane::Item::owner(), Arcane::MessagePassing::ISerializeMessageList::processPendingMessages(), Arcane::BasicSerializer::put(), Arcane::BasicSerializer::putInteger(), Arcane::BasicSerializer::putReal(), Arcane::IParallelMng::reduce(), Arcane::Parallel::ReduceMin, Arcane::BasicSerializer::reserve(), Arcane::Array< T >::resize(), Arcane::Numerics::ISurfaceUtils::setFaceToSurface(), Arcane::BasicSerializer::setMode(), Arcane::Item::uniqueId(), Arcane::MessagePassing::ISerializeMessageList::waitMessages(), Arcane::Real3POD::x, Arcane::Real3POD::y, and Arcane::Real3POD::z.
Member Data Documentation
m_box_tolerance
Real Arcane::Numerics::ParallelCorefinementService::m_box_tolerance private
Definition at line 67 of file ParallelCorefinementService.h.
m_contacts
FaceFaceContactList Arcane::Numerics::ParallelCorefinementService::m_contacts private
Definition at line 69 of file ParallelCorefinementService.h.
m_geometry
IGeometry* Arcane::Numerics::ParallelCorefinementService::m_geometry private
Definition at line 68 of file ParallelCorefinementService.h.
m_internal
Internal* Arcane::Numerics::ParallelCorefinementService::m_internal private
Definition at line 74 of file ParallelCorefinementService.h.
m_master_group
FaceGroup Arcane::Numerics::ParallelCorefinementService::m_master_group private
Definition at line 65 of file ParallelCorefinementService.h.
m_slave_group
FaceGroup Arcane::Numerics::ParallelCorefinementService::m_slave_group private
Definition at line 66 of file ParallelCorefinementService.h.
The documentation for this class was generated from the following files:
ParallelCorefinementService.h
ParallelCorefinementService.cc