Arcane: Arcane::Directory Class Reference
Arcane::Directory Class Reference
IO
Class managing a directory.
#include <arcane/core/Directory.h>
Public Member Functions
Directory (const String &path)
Directory (const Directory &directory)
Directory (const IDirectory &directory, const String &sub_path)
Directory (const IDirectory &directory)
Directory & operator= (const IDirectory &from)
Directory & operator= (const Directory &from)
bool createDirectory () const override
Creates the directory.
String path () const override
Returns the path of the directory.
String file (const String &file_name) const override
Returns the full path of the file file_name in the directory.
Public Member Functions inherited from Arcane::IDirectory
virtual ~IDirectory ()=default
Frees the resources.
Private Attributes
String m_directory_path
Detailed Description
Class managing a directory.
Definition at line 34 of file Directory.h.
Constructor & Destructor Documentation
Directory() [1/4]
Arcane::Directory::Directory (const String & path) explicit
Definition at line 45 of file Directory.cc.
Directory() [2/4]
Arcane::Directory::Directory (const Directory & directory)
Definition at line 72 of file Directory.cc.
Directory() [3/4]
Arcane::Directory::Directory (const IDirectory & directory, const String & sub_path)
Definition at line 54 of file Directory.cc.
Directory() [4/4]
Arcane::Directory::Directory (const IDirectory & directory)
Definition at line 63 of file Directory.cc.
Member Function Documentation
createDirectory()
bool Arcane::Directory::createDirectory () const override virtual
Creates the directory.
Return values
true in case of failure,
false in case of success or if the directory already exists.
Implements Arcane::IDirectory.
Definition at line 101 of file Directory.cc.
References Arcane::platform::createDirectory().
Referenced by Arcane::DumpWEnsight7::_buildFileName(), Arcane::SimpleTableReaderWriterUtils::createDirectoryOnlyProcess0(), and Arcane::ArcaneSession::setLogAndErrorFiles().
file()
String Arcane::Directory::file (const String & file_name) const override virtual
Returns the full path of the file file_name in the directory.
Implements Arcane::IDirectory.
Definition at line 119 of file Directory.cc.
References path().
Referenced by Arcane::VariableIOReaderMng::_checkHashFunction(), Arcane::LLVMSymbolizerService::_checkValid(), Arcane::TimeHistoryMngInternal::_dumpSummaryOfCurves(), Arcane::Application::_openUserConfig(), Arcane::ArcaneSession::build(), Arcane::InternalInfosDumper::dumpArcaneDatabase(), Arcane::InternalInfosDumper::dumpInternalAllInfos(), Arcane::ManualHdf5VariableReader::initialize(), Arcane::SimpleTableReaderWriterUtils::isFileExist(), Arcane::ArcaneBasic2CheckpointReaderService::notifyBeginRead(), Arcane::ArcaneBasicCheckpointService::notifyBeginRead(), Arcane::ArcaneHdf5CheckpointService2::notifyBeginRead(), Arcane::ArcaneBasicCheckpointService::notifyBeginWrite(), Arcane::ArcaneHdf5CheckpointService2::notifyBeginWrite(), Arcane::KdiPostProcessor::notifyBeginWrite(), Arcane::VtkHdfPostProcessor::notifyBeginWrite(), Arcane::VtkHdfV2PostProcessor::notifyBeginWrite(), Arcane::ArcaneSession::setLogAndErrorFiles(), Arcane::CheckpointMng::writeDefaultCheckpoint(), and Arcane::SimpleCsvReaderWriter::writeTable().
operator=() [1/2]
Directory & Arcane::Directory::operator= (const Directory & from)
Definition at line 91 of file Directory.cc.
operator=() [2/2]
Directory & Arcane::Directory::operator= (const IDirectory & from)
Definition at line 81 of file Directory.cc.
path()
String Arcane::Directory::path () const override virtual
Returns the path of the directory.
Implements Arcane::IDirectory.
Definition at line 110 of file Directory.cc.
Referenced by Arcane::Application::build(), and file().
Member Data Documentation
m_directory_path
String Arcane::Directory::m_directory_path private
Definition at line 58 of file Directory.h.
The documentation for this class was generated from the following files:
Directory.h
Directory.cc