Arcane: Arcane::LinearOffsetMap< DataType > Class Template Reference
Arcane::LinearOffsetMap< DataType > Class Template Reference
List of linear offsets.
#include <arcane/utils/LinearOffsetMap.h>
Public Member Functions
void add (DataType size, DataType offset)
Adds an offset offset of size size.
DataType getAndRemoveOffset (DataType size)
Retrieves a sufficient offset for an element of size size.
Int32 size () const
Number of elements in the table.
Private Attributes
std::multimap< DataType, DataType > m_offset_map
Detailed Description
template<typename DataType>
class Arcane::LinearOffsetMap< DataType >
List of linear offsets.
DataType must be Int32 or Int64.
Warning
Experimental class. Do not use outside of Arcane.
Definition at line 39 of file LinearOffsetMap.h.
Member Function Documentation
add()
template<typename DataType> void Arcane::LinearOffsetMap< DataType >::add (DataType size, DataType offset)
Adds an offset offset of size size.
Definition at line 27 of file LinearOffsetMap.cc.
References size().
Referenced by getAndRemoveOffset().
getAndRemoveOffset()
template<typename DataType> DataType Arcane::LinearOffsetMap< DataType >::getAndRemoveOffset (DataType size)
Retrieves a sufficient offset for an element of size size.
Returns a negative value if no offset is available. If an offset is available, it returns its value. The found offset is removed from the list and an offset is added for the remaining size if it is not zero: if the found offset is offset and the associated size is offset_size, call add(offset_size - size, offset + size).
Definition at line 37 of file LinearOffsetMap.cc.
References add(), and size().
size()
template<typename DataType> Int32 Arcane::LinearOffsetMap< DataType >::size () const
Number of elements in the table.
Definition at line 58 of file LinearOffsetMap.cc.
Referenced by add(), and getAndRemoveOffset().
Member Data Documentation
m_offset_map
template<typename DataType> std::multimap<DataType, DataType> Arcane::LinearOffsetMap< DataType >::m_offset_map private
Definition at line 66 of file LinearOffsetMap.h.
The documentation for this class was generated from the following files:
LinearOffsetMap.h
LinearOffsetMap.cc