Arcane: Arcane::ParameterListWithCaseOption Class Reference
Arcane::ParameterListWithCaseOption Class Reference
Parameter list with information to override dataset options.
#include <arcane/utils/internal/ParameterListWithCaseOption.h>
Classes
class Impl
Public Member Functions
ParameterListWithCaseOption ()
Constructs a dictionary.
ParameterListWithCaseOption (const ParameterListWithCaseOption &rhs)
Constructs a dictionary.
~ParameterListWithCaseOption ()
Releases resources.
String getParameterOrNull (const String &param_name) const
Retrieves the parameter with name param_name.
bool addParameterLine (const String &line)
Parses the line line.
ParameterCaseOption getParameterCaseOption (const String &language) const
Method to retrieve an object of type ParameterCaseOption.
void addParameters (const ParameterList &parameters)
Adds the parameters from parameters to the instance's parameters.
Private Attributes
Impl * m_p = nullptr
Implementation.
Detailed Description
Parameter list with information to override dataset options.
Definition at line 33 of file ParameterListWithCaseOption.h.
Constructor & Destructor Documentation
ParameterListWithCaseOption() [1/2]
Arcane::ParameterListWithCaseOption::ParameterListWithCaseOption ()
Constructs a dictionary.
Definition at line 171 of file ParameterListWithCaseOption.cc.
References m_p.
Referenced by ParameterListWithCaseOption().
ParameterListWithCaseOption() [2/2]
Arcane::ParameterListWithCaseOption::ParameterListWithCaseOption (const ParameterListWithCaseOption & rhs)
Constructs a dictionary.
Definition at line 180 of file ParameterListWithCaseOption.cc.
References m_p, and ParameterListWithCaseOption().
~ParameterListWithCaseOption()
Arcane::ParameterListWithCaseOption::~ParameterListWithCaseOption ()
Releases resources.
Definition at line 189 of file ParameterListWithCaseOption.cc.
References m_p.
Member Function Documentation
addParameterLine()
bool Arcane::ParameterListWithCaseOption::addParameterLine (const String & line)
Parses the line line.
The line must have one of the following forms, with A the parameter and B the value:
A=B,
A:=B
A+=B,
A-=B
In case (1) or (3), the argument value is added to the already present occurrences. In case (2), the argument value replaces all already present occurrences. In case (4), the occurrence having the value B is deleted if it was present and nothing happens if it was absent.
Return values
false if a parameter could be parsed
true otherwise.
Definition at line 207 of file ParameterListWithCaseOption.cc.
References Arcane::String::bytes(), m_p, and Arcane::String::substring().
addParameters()
void Arcane::ParameterListWithCaseOption::addParameters (const ParameterList & parameters)
Adds the parameters from parameters to the instance's parameters.
Definition at line 247 of file ParameterListWithCaseOption.cc.
References Arcane::CollectionBase::count(), Arcane::ParameterList::fillParameters(), and m_p.
getParameterCaseOption()
ParameterCaseOption Arcane::ParameterListWithCaseOption::getParameterCaseOption (const String & language) const
Method to retrieve an object of type ParameterCaseOption.
This object can be destroyed after use.
Parameters
language The language in which the dataset is written.
Returns
An object of type ParameterCaseOption.
Definition at line 238 of file ParameterListWithCaseOption.cc.
References m_p.
Referenced by Arcane::CaseOptionMultiExtended::_search(), and Arcane::CaseOptionMultiSimpleT< T >::_search().
getParameterOrNull()
String Arcane::ParameterListWithCaseOption::getParameterOrNull (const String & param_name) const
Retrieves the parameter with name param_name.
Returns a null string if no parameter with this name exists.
If the parameter is present multiple times, only the last value is returned.
Definition at line 198 of file ParameterListWithCaseOption.cc.
References m_p.
Referenced by Arcane::StringVariableReplace::replaceWithCmdLineArgs().
Member Data Documentation
m_p
Impl* Arcane::ParameterListWithCaseOption::m_p = nullptr private
Implementation.
Definition at line 93 of file ParameterListWithCaseOption.h.
Referenced by addParameterLine(), addParameters(), getParameterCaseOption(), getParameterOrNull(), ParameterListWithCaseOption(), ParameterListWithCaseOption(), and ~ParameterListWithCaseOption().
The documentation for this class was generated from the following files:
ParameterListWithCaseOption.h
ParameterListWithCaseOption.cc