Alien: Alien::ISpace Class Reference
Alien::ISpace Class Reference abstract
Interface for algebraic space objects.
#include <core/alien/data/ISpace.h>
Public Member Functions
virtual ~ISpace ()
Free resources.
virtual bool operator== (const ISpace &space) const =0
Comparison operator.
virtual bool operator!= (const ISpace &space) const =0
Comparison operator.
virtual Arccore::Integer size () const =0
Get space size.
virtual const Arccore::String & name () const =0
Get space name.
virtual void setField (Arccore::String label, const Arccore::UniqueArray< Arccore::Integer > &indices)=0
Set label on matrix entries.
virtual Arccore::Integer nbField () const =0
Get the number of fields.
virtual Arccore::String fieldLabel (Arccore::Integer i) const =0
Get the label of the i-th field.
virtual const Arccore::UniqueArray< Arccore::Integer > & field (Arccore::Integer i) const =0
Get indices associated to the i-th field \para[in] i The requested field.
virtual const Arccore::UniqueArray< Arccore::Integer > & field (Arccore::String label) const =0
Get the indices associated to a label.
virtual std::shared_ptr< ISpace > clone () const =0
Clone this object.
Protected Member Functions
ISpace ()
Constructor.
Private Member Functions
ISpace (const ISpace &)=delete
ISpace (ISpace &&)=delete
void operator= (const ISpace &)=delete
void operator= (ISpace &&)=delete
Detailed Description
Interface for algebraic space objects.
Definition at line 43 of file ISpace.h.
Constructor & Destructor Documentation
ISpace()
Alien::ISpace::ISpace () inline protected
Constructor.
Definition at line 47 of file ISpace.h.
Referenced by Alien::CompositeKernel::Space::operator!=(), operator!=(), Alien::Space::operator!=(), Alien::CompositeKernel::Space::operator==(), operator==(), Alien::Space::operator==(), Alien::Space::Space(), and Alien::Space::Space().
~ISpace()
virtual Alien::ISpace::~ISpace () inline virtual
Free resources.
Definition at line 61 of file ISpace.h.
Member Function Documentation
clone()
virtual std::shared_ptr< ISpace > Alien::ISpace::clone () const pure virtual
Clone this object.
Returns
A clone of this object
Implemented in Alien::CompositeKernel::Space, and Alien::Space.
field() [1/2]
virtual const Arccore::UniqueArray< Arccore::Integer > & Alien::ISpace::field (Arccore::Integer i) const pure virtual
Get indices associated to the i-th field \para[in] i The requested field.
Returns
The indices associated to the field
Implemented in Alien::Space.
field() [2/2]
virtual const Arccore::UniqueArray< Arccore::Integer > & Alien::ISpace::field (Arccore::String label) const pure virtual
Get the indices associated to a label.
Parameters
[in] label The requested label
Returns
The indices associated to the field
Implemented in Alien::Space.
fieldLabel()
virtual Arccore::String Alien::ISpace::fieldLabel (Arccore::Integer i) const pure virtual
Get the label of the i-th field.
Parameters
[in] i The requested field
Returns
The associated label
Implemented in Alien::Space.
name()
virtual const Arccore::String & Alien::ISpace::name () const pure virtual
Get space name.
Returns
The name of the space
Implemented in Alien::CompositeKernel::Space, and Alien::Space.
Referenced by Alien::CompositeKernel::Space::operator==(), and Alien::Space::operator==().
nbField()
virtual Arccore::Integer Alien::ISpace::nbField () const pure virtual
Get the number of fields.
Returns
The number of fields (labels)
Implemented in Alien::CompositeKernel::Space, and Alien::Space.
operator!=()
virtual bool Alien::ISpace::operator!= (const ISpace & space) const pure virtual
Comparison operator.
Parameters
[in] Space related functions. The space to compare to
Returns
Wheteher the spaces are different
Implemented in Alien::CompositeKernel::Space, and Alien::Space.
References ISpace().
operator==()
virtual bool Alien::ISpace::operator== (const ISpace & space) const pure virtual
Comparison operator.
Parameters
[in] Space related functions. The space to compare to
Returns
Wheteher the spaces are the same
Implemented in Alien::CompositeKernel::Space, and Alien::Space.
References ISpace().
setField()
virtual void Alien::ISpace::setField (Arccore::String label, const Arccore::UniqueArray< Arccore::Integer > & indices) pure virtual
Set label on matrix entries.
Parameters
[in] label The name of the label
[in] indices The indices to which label is set
Implemented in Alien::Space.
size()
virtual Arccore::Integer Alien::ISpace::size () const pure virtual
Get space size.
Returns
The size of the space
Implemented in Alien::CompositeKernel::Space, and Alien::Space.
Referenced by Alien::MatrixDistribution::MatrixDistribution(), Alien::MatrixDistribution::MatrixDistribution(), Alien::CompositeKernel::Space::operator==(), and Alien::Space::operator==().
The documentation for this class was generated from the following file:
ISpace.h