Arcane: Arcane::Materials::ComponentItemVector Class Reference
Arcane::Materials::ComponentItemVector Class Reference
Vector over the entities of a constituent.
#include <arcane/core/materials/ComponentItemVector.h>
Public Member Functions
ComponentItemVector (const ComponentItemVector &rhs)=default
Copy constructor. This instance then references rhs.
ComponentItemVector & operator= (const ComponentItemVector &)=default
Copy assignment operator.
operator ComponentItemVectorView () const
Conversion to a view of this vector.
ComponentItemVectorView view () const
View of this vector.
IMeshComponent * component () const
Associated constituent.
ComponentItemVector clone () const
Clone this vector.
ComponentPurePartItemVectorView pureItems () const
List of pure entities (associated with the global cell) of the constituent.
ComponentImpurePartItemVectorView impureItems () const
List of impure (partial) entities of the constituent.
Protected Member Functions
ComponentItemVector (IMeshComponent *component)
Constructs a vector for the constituent component.
ComponentItemVector (ComponentItemVectorView rhs)
Copy constructor. This instance is a copy of rhs.
ConstArrayView< MatVarIndex > _matvarIndexes () const
ConstituentItemLocalIdListView _constituentItemListView () const
void _setItems (SmallSpan< const Int32 > local_ids)
ConstArrayView< Int32 > _localIds () const
IMeshMaterialMng * _materialMng () const
IMeshComponent * _component () const
Detailed Description
Vector over the entities of a constituent.
Warning
This vector is only valid as long as the medium and the supporting group do not change.
This class is similar to the ItemVector class but contains a list of constituent entities (IMeshComponent). All entities must belong to the same constituent.
Instances of this class are generally not constructed directly unless they are copies. For original creation, MatCellVector or EnvCellVector must be used.
This class uses a reference semantics. To perform a copy, you must use the clone() command or construct an object via a view:
ComponentItemVector v1 = ...;
ComponentItemVector v2 = v1; // v2 references v1
ComponentItemVector v3 = v1.clone(); // v3 is a copy of v1
ComponentItemVector v4 = v1.view(); // v4 is a copy of v1
Definition at line 88 of file core/materials/ComponentItemVector.h.
Constructor & Destructor Documentation
ComponentItemVector() [1/2]
Arcane::Materials::ComponentItemVector::ComponentItemVector (IMeshComponent * component) explicit protected
Constructs a vector for the constituent component.
Definition at line 28 of file ComponentItemVector.cc.
References component().
ComponentItemVector() [2/2]
Arcane::Materials::ComponentItemVector::ComponentItemVector (ComponentItemVectorView rhs) explicit protected
Copy constructor. This instance is a copy of rhs.
Definition at line 37 of file ComponentItemVector.cc.
References component().
Member Function Documentation
_component()
IMeshComponent * Arcane::Materials::ComponentItemVector::_component () const protected
Definition at line 121 of file ComponentItemVector.cc.
_constituentItemListView()
ConstituentItemLocalIdListView Arcane::Materials::ComponentItemVector::_constituentItemListView () const protected
Definition at line 85 of file ComponentItemVector.cc.
_localIds()
ConstArrayView< Int32 > Arcane::Materials::ComponentItemVector::_localIds () const protected
Definition at line 103 of file ComponentItemVector.cc.
_materialMng()
IMeshMaterialMng * Arcane::Materials::ComponentItemVector::_materialMng () const protected
Definition at line 112 of file ComponentItemVector.cc.
_matvarIndexes()
ConstArrayView< MatVarIndex > Arcane::Materials::ComponentItemVector::_matvarIndexes () const protected
Definition at line 94 of file ComponentItemVector.cc.
_setItems()
void Arcane::Materials::ComponentItemVector::_setItems (SmallSpan< const Int32 > local_ids) protected
Definition at line 49 of file ComponentItemVector.cc.
clone()
ComponentItemVector Arcane::Materials::ComponentItemVector::clone () const inline
Clone this vector.
Definition at line 121 of file core/materials/ComponentItemVector.h.
References ComponentItemVector(), and view().
component()
IMeshComponent * Arcane::Materials::ComponentItemVector::component () const inline
Associated constituent.
Definition at line 118 of file core/materials/ComponentItemVector.h.
Referenced by ComponentItemVector(), ComponentItemVector(), Arcane::Materials::EnvCellVector::environment(), Arcane::Materials::MatCellVector::material(), and operator=().
impureItems()
ComponentImpurePartItemVectorView Arcane::Materials::ComponentItemVector::impureItems () const
List of impure (partial) entities of the constituent.
Definition at line 76 of file ComponentItemVector.cc.
operator ComponentItemVectorView()
Arcane::Materials::ComponentItemVector::operator ComponentItemVectorView () const inline
Conversion to a view of this vector.
Definition at line 109 of file core/materials/ComponentItemVector.h.
References view().
pureItems()
ComponentPurePartItemVectorView Arcane::Materials::ComponentItemVector::pureItems () const
List of pure entities (associated with the global cell) of the constituent.
Definition at line 67 of file ComponentItemVector.cc.
view()
ComponentItemVectorView Arcane::Materials::ComponentItemVector::view () const
View of this vector.
Definition at line 58 of file ComponentItemVector.cc.
Referenced by clone(), and operator ComponentItemVectorView().
The documentation for this class was generated from the following files:
core/materials/ComponentItemVector.h
ComponentItemVector.cc