Arcane: Arcane::BasicSerializer Class Reference
Arcane::BasicSerializer Class Reference
Basic implementation of 'ISerializer'.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/serialize/arccore/serialize/BasicSerializer.h>
Classes
class SizesPrinter
class Impl
class Impl2
Public Member Functions
BasicSerializer (const BasicSerializer &sb)
void reserveSpan (eDataType dt, Int64 n) override
Reserves memory for n values of dt.
void reserveSpan (eBasicDataType dt, Int64 n) override
Reserves memory for n values of dt.
void reserve (eBasicDataType dt, Int64 n) override
Reserves memory for n objects of type dt.
void reserve (eDataType dt, Int64 n) override
Reserves memory for n objects of type dt.
void reserveInteger (Int64 n) override
void reserve (const String &str) override
Reserve memory for a character string str.
void reserveArray (Span< const Real > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Int16 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Int32 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Int64 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Byte > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Int8 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Float16 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const BFloat16 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Float32 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Float128 > values) override
Reserve to save the number of elements and the values elements.
void reserveArray (Span< const Int128 > values) override
Reserve to save the number of elements and the values elements.
void put (Span< const Real > values) override
Add the array values.
void put (Span< const Int16 > values) override
Add the array values.
void put (Span< const Int32 > values) override
Add the array values.
void put (Span< const Int64 > values) override
Add the array values.
void put (Span< const Byte > values) override
Add the array values.
void putSpan (Span< const Int8 > values) override
Add the array values.
void putSpan (Span< const Float16 > values) override
Add the array values.
void putSpan (Span< const BFloat16 > values) override
Add the array values.
void putSpan (Span< const Float32 > values) override
Add the array values.
void putSpan (Span< const Float128 > values) override
Add the array values.
void putSpan (Span< const Int128 > values) override
Add the array values.
void put (const String &value) override
Add the string value.
void put (Real value) override
Add value.
void put (Int64 value) override
Add value.
void put (Int32 value) override
Add value.
void put (Int16 value) override
Add value.
void put (Byte value) override
Add value.
void put (Int8 value) override
Add value.
void put (Float16 value) override
Add value.
void put (BFloat16 value) override
Add value.
void put (Float32 value) override
Add value.
void put (Float128 value) override
Add value.
void put (Int128 value) override
Add value.
void putReal (Real value) override
Add the real value.
void putInt64 (Int64 value) override
Add the integer value.
void putInt32 (Int32 value) override
Add the integer value.
void putInt16 (Int16 value) override
Add the integer value.
void putInteger (Integer value) override
Add the integer value.
void putByte (Byte value) override
Add the byte value.
void putInt8 (Int8 value) override
Add value.
void putFloat16 (Float16 value) override
Add value.
void putBFloat16 (BFloat16 value) override
Add value.
void putFloat32 (Float32 value) override
Add value.
void putFloat128 (Float128 value) override
Add value.
void putInt128 (Int128 value) override
Add value.
void putArray (Span< const Real > values) override
Save the number of elements and the values elements.
void putArray (Span< const Int16 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Int32 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Int64 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Byte > values) override
Save the number of elements and the values elements.
void putArray (Span< const Int8 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Float16 > values) override
Save the number of elements and the values elements.
void putArray (Span< const BFloat16 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Float32 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Float128 > values) override
Save the number of elements and the values elements.
void putArray (Span< const Int128 > values) override
Save the number of elements and the values elements.
void get (ArrayView< Real > values) override
Retrieve the array values.
void get (ArrayView< Int64 > values) override
Retrieve the array values.
void get (ArrayView< Int32 > values) override
Retrieve the array values.
void get (ArrayView< Int16 > values) override
Retrieve the array values.
void get (ArrayView< Byte > values) override
Retrieve the array values.
void getSpan (Span< Real > values) override
Retrieve the array values.
void getSpan (Span< Int16 > values) override
Retrieve the array values.
void getSpan (Span< Int32 > values) override
Retrieve the array values.
void getSpan (Span< Int64 > values) override
Retrieve the array values.
void getSpan (Span< Byte > values) override
Retrieve the array values.
void getSpan (Span< Int8 > values) override
Retrieve the array values.
void getSpan (Span< Float16 > values) override
Retrieve the array values.
void getSpan (Span< BFloat16 > values) override
Retrieve the array values.
void getSpan (Span< Float32 > values) override
Retrieve the array values.
void getSpan (Span< Float128 > values) override
Retrieve the array values.
void getSpan (Span< Int128 > values) override
Retrieve the array values.
void getArray (Array< Real > &values) override
Resize and fill values.
void getArray (Array< Int16 > &values) override
Resize and fill values.
void getArray (Array< Int32 > &values) override
Resize and fill values.
void getArray (Array< Int64 > &values) override
Resize and fill values.
void getArray (Array< Byte > &values) override
Resize and fill values.
void getArray (Array< Int8 > &values) override
Resize and fill values.
void getArray (Array< Float16 > &values) override
Resize and fill values.
void getArray (Array< BFloat16 > &values) override
Resize and fill values.
void getArray (Array< Float32 > &values) override
Resize and fill values.
void getArray (Array< Float128 > &values) override
Resize and fill values.
void getArray (Array< Int128 > &values) override
Resize and fill values.
void get (String &values) override
Retrieve the string value.
Real getReal () override
Retrieve a real number.
Int64 getInt64 () override
Retrieve a size.
Int32 getInt32 () override
Retrieve an integer.
Int16 getInt16 () override
Retrieve a 16-bit integer.
Integer getInteger () override
Retrieve a size.
Byte getByte () override
Retrieve a byte.
Int8 getInt8 () override
Retrieve an Int8.
Float16 getFloat16 () override
Retrieve a Float16.
BFloat16 getBFloat16 () override
Retrieve a BFloat16.
Float32 getFloat32 () override
Retrieve a Float32.
Float128 getFloat128 () override
Retrieve a Float128.
Int128 getInt128 () override
Retrieve an Int128.
void allocateBuffer () override
Allocates the serializer memory.
eMode mode () const override
Current operating mode.
void setMode (eMode new_mode) override
Sets the current mode.
eReadMode readMode () const override
Read mode.
void setReadMode (eReadMode new_read_mode) override
Sets the read mode.
void setSerializeTypeInfo (bool v)
Indicates whether to serialize the data type to ensure consistency.
bool isSerializeTypeInfo () const
Span< Real > realBuffer ()
Span< Int64 > int64Buffer ()
Span< Int32 > int32Buffer ()
Span< Int16 > int16Buffer ()
Span< Byte > byteBuffer ()
ConstArrayView< Byte > copyAndGetSizesBuffer ()
Span< Byte > globalBuffer ()
Span< const Byte > globalBuffer () const
ConstArrayView< Int64 > sizesBuffer ()
Int64 totalSize () const
void preallocate (Int64 size)
void releaseBuffer ()
void setFromSizes ()
void printSizes (std::ostream &o) const
void initFromBuffer (Span< const Byte > buf)
Initializes the serializer for reading from the data buf.
void copy (const ISerializer *from) override
Copies the data from from into this instance.
void copy (const BasicSerializer &rhs)
void reserve (int dt, Int64 n)
Public Member Functions inherited from Arcane::ISerializer
virtual ~ISerializer ()=default
Frees resources.
void reserveReal (Int64 n)
Reserve for n Real.
void reserveInt16 (Int64 n)
Reserve for n Int16.
void reserveInt64 (Int64 n)
Reserve for n Int64.
void reserveInt32 (Int64 n)
Reserve for n Int32.
void reserveByte (Int64 n)
Reserve for n Byte.
void reserveInt8 (Int64 n)
Reserve for n Int8.
void reserveFloat16 (Int64 n)
Reserve for n Float16.
void reserveFloat32 (Int64 n)
Reserve for n Float32.
void reserveBFloat16 (Int64 n)
Reserve for n BFloat16.
void reserveFloat128 (Int64 n)
Reserve for n Float128.
void reserveInt128 (Int64 n)
Reserve for n Int128.
void reserveSpan (int dt, Int64 n)
void reserve (int dt, Int64 n)
Static Public Member Functions
static ARCCORE_CONSTEXPR Integer paddingSize ()
Padding and alignment size.
Protected Member Functions
Impl * _p () const
Protected Attributes
Impl2 * m_p2
Private Types
typedef BasicSerializer ThatClass
Private Member Functions
void operator= (const BasicSerializer &sb)
void allocateBuffer (Int64 nb_real, Int64 nb_int16, Int64 nb_int32, Int64 nb_int64, Int64 nb_byte) override
virtual void putSpan (Span< const Real > values)
Add the array values.
virtual void putSpan (Span< const Int16 > values)
Add the array values.
virtual void putSpan (Span< const Int32 > values)
Add the array values.
virtual void putSpan (Span< const Int64 > values)
Add the array values.
virtual void putSpan (Span< const Byte > values)
Add the array values.
virtual void reserveSpan (Span< const Real > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Int16 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Int32 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Int64 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Byte > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Int8 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Float16 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const BFloat16 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Float32 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Float128 > values)
Reserve for a view of values elements.
virtual void reserveSpan (Span< const Int128 > values)
Reserve for a view of values elements.
void reserveSpan (int dt, Int64 n)
Friends
std::ostream & operator<< (std::ostream &o, const BasicSerializer::SizesPrinter &x)
Additional Inherited Members
Public Types inherited from Arcane::ISerializer
enum eMode { ModeReserve , ModePut , ModeGet }
Serializer operating mode.
enum eReadMode { ReadReplace , ReadAdd }
Serializer read mode.
enum eDataType {
DT_Byte = 0 , DT_Real = 1 , DT_Int16 = 2 , DT_Int32 = 3 ,
DT_Int64 = 4 , DT_Float32 = 12 , DT_Float16 = 11 , DT_BFloat16 = 10 ,
DT_Int8 = 13 , DT_Float128 = 14 , DT_Int128 = 15 , DT_Float64 = DT_Real
}
Detailed Description
Basic implementation of 'ISerializer'.
Definition at line 93 of file BasicSerializer.h.
Member Typedef Documentation
ThatClass
typedef BasicSerializer Arcane::BasicSerializer::ThatClass private
Definition at line 97 of file BasicSerializer.h.
Constructor & Destructor Documentation
BasicSerializer() [1/2]
Arcane::BasicSerializer::BasicSerializer ()
Definition at line 817 of file BasicSerializer.cc.
BasicSerializer() [2/2]
Arcane::BasicSerializer::BasicSerializer (const BasicSerializer & sb)
Definition at line 826 of file BasicSerializer.cc.
~BasicSerializer()
Arcane::BasicSerializer::~BasicSerializer () override
Definition at line 836 of file BasicSerializer.cc.
Member Function Documentation
_p()
BasicSerializer::Impl * Arcane::BasicSerializer::_p () const protected
Definition at line 845 of file BasicSerializer.cc.
allocateBuffer() [1/2]
void Arcane::BasicSerializer::allocateBuffer () override virtual
Allocates the serializer memory.
Implements Arcane::ISerializer.
Definition at line 1434 of file BasicSerializer.cc.
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::Hdf5ReaderWriter::_writeValParallel(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::MessagePassing::filterCommonStrings(), Arcane::VariableUtilities::filterCommonVariables(), Arcane::Hdf5ReaderWriter::setMetaData(), Arcane::Numerics::ParallelCorefinementService::update(), and Arcane::PropertyMng::writeTo().
allocateBuffer() [2/2]
void Arcane::BasicSerializer::allocateBuffer (Int64 nb_real, Int64 nb_int16, Int64 nb_int32, Int64 nb_int64, Int64 nb_byte) override private virtual
Implements Arcane::ISerializer.
Definition at line 1479 of file BasicSerializer.cc.
byteBuffer()
Span< Byte > Arcane::BasicSerializer::byteBuffer ()
Definition at line 871 of file BasicSerializer.cc.
copy() [1/2]
void Arcane::BasicSerializer::copy (const BasicSerializer & rhs)
Definition at line 1489 of file BasicSerializer.cc.
copy() [2/2]
void Arcane::BasicSerializer::copy (const ISerializer * from) override virtual
Copies the data from from into this instance.
Implements Arcane::ISerializer.
Definition at line 1498 of file BasicSerializer.cc.
References ARCCORE_FATAL, and copy().
Referenced by copy().
copyAndGetSizesBuffer()
ConstArrayView< Byte > Arcane::BasicSerializer::copyAndGetSizesBuffer ()
Definition at line 1528 of file BasicSerializer.cc.
get() [1/6]
void Arcane::BasicSerializer::get (ArrayView< Byte > values) inline override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 292 of file BasicSerializer.h.
References getSpan().
get() [2/6]
void Arcane::BasicSerializer::get (ArrayView< Int16 > values) inline override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 291 of file BasicSerializer.h.
References getSpan().
get() [3/6]
void Arcane::BasicSerializer::get (ArrayView< Int32 > values) inline override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 290 of file BasicSerializer.h.
References getSpan().
get() [4/6]
void Arcane::BasicSerializer::get (ArrayView< Int64 > values) inline override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 289 of file BasicSerializer.h.
References getSpan().
get() [5/6]
void Arcane::BasicSerializer::get (ArrayView< Real > values) inline override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 288 of file BasicSerializer.h.
References getSpan().
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::MessagePassing::filterCommonStrings(), Arcane::VariableUtilities::filterCommonVariables(), getByte(), getInt16(), getInt32(), getInt64(), getReal(), Arcane::Hdf5ReaderWriter::setMetaData(), and Arcane::Numerics::ParallelCorefinementService::update().
get() [6/6]
void Arcane::BasicSerializer::get (String & value) override virtual
Retrieve the string value.
Implements Arcane::ISerializer.
Definition at line 1419 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::ISerializer::ModeGet.
getArray() [1/11]
void Arcane::BasicSerializer::getArray (Array< BFloat16 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1388 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [2/11]
void Arcane::BasicSerializer::getArray (Array< Byte > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1367 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [3/11]
void Arcane::BasicSerializer::getArray (Array< Float128 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1402 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [4/11]
void Arcane::BasicSerializer::getArray (Array< Float16 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1381 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [5/11]
void Arcane::BasicSerializer::getArray (Array< Float32 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1395 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [6/11]
void Arcane::BasicSerializer::getArray (Array< Int128 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1409 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [7/11]
void Arcane::BasicSerializer::getArray (Array< Int16 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1346 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [8/11]
void Arcane::BasicSerializer::getArray (Array< Int32 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1353 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [9/11]
void Arcane::BasicSerializer::getArray (Array< Int64 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1360 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [10/11]
void Arcane::BasicSerializer::getArray (Array< Int8 > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1374 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
getArray() [11/11]
void Arcane::BasicSerializer::getArray (Array< Real > & values) override virtual
Resize and fill values.
Implements Arcane::ISerializer.
Definition at line 1339 of file BasicSerializer.cc.
References getInt64(), getSpan(), and Arcane::Array< T >::resize().
Referenced by Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), and Arcane::mesh::ParallelAMRConsistency::_gatherItems().
getBFloat16()
BFloat16 Arcane::BasicSerializer::getBFloat16 () inline override virtual
Retrieve a BFloat16.
Implements Arcane::ISerializer.
Definition at line 370 of file BasicSerializer.h.
References getSpan().
getByte()
Byte Arcane::BasicSerializer::getByte () inline override virtual
Retrieve a byte.
Implements Arcane::ISerializer.
Definition at line 352 of file BasicSerializer.h.
References get().
getFloat128()
Float128 Arcane::BasicSerializer::getFloat128 () inline override virtual
Retrieve a Float128.
Implements Arcane::ISerializer.
Definition at line 382 of file BasicSerializer.h.
References getSpan().
getFloat16()
Float16 Arcane::BasicSerializer::getFloat16 () inline override virtual
Retrieve a Float16.
Implements Arcane::ISerializer.
Definition at line 364 of file BasicSerializer.h.
References getSpan().
getFloat32()
Float32 Arcane::BasicSerializer::getFloat32 () inline override virtual
Retrieve a Float32.
Implements Arcane::ISerializer.
Definition at line 376 of file BasicSerializer.h.
References getSpan().
getInt128()
Int128 Arcane::BasicSerializer::getInt128 () inline override virtual
Retrieve an Int128.
Implements Arcane::ISerializer.
Definition at line 388 of file BasicSerializer.h.
References getSpan().
getInt16()
Int16 Arcane::BasicSerializer::getInt16 () inline override virtual
Retrieve a 16-bit integer.
Implements Arcane::ISerializer.
Definition at line 338 of file BasicSerializer.h.
References get().
getInt32()
Int32 Arcane::BasicSerializer::getInt32 () inline override virtual
Retrieve an integer.
Implements Arcane::ISerializer.
Definition at line 332 of file BasicSerializer.h.
References get().
Referenced by Arcane::MessagePassing::filterCommonStrings(), and getInteger().
getInt64()
Int64 Arcane::BasicSerializer::getInt64 () inline override virtual
Retrieve a size.
Implements Arcane::ISerializer.
Definition at line 326 of file BasicSerializer.h.
References get().
Referenced by get(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), and getInteger().
getInt8()
Int8 Arcane::BasicSerializer::getInt8 () inline override virtual
Retrieve an Int8.
Implements Arcane::ISerializer.
Definition at line 358 of file BasicSerializer.h.
References getSpan().
getInteger()
Integer Arcane::BasicSerializer::getInteger () inline override virtual
Retrieve a size.
Implements Arcane::ISerializer.
Definition at line 344 of file BasicSerializer.h.
References getInt32(), and getInt64().
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::VariableUtilities::filterCommonVariables(), and Arcane::Numerics::ParallelCorefinementService::update().
getReal()
Real Arcane::BasicSerializer::getReal () inline override virtual
Retrieve a real number.
Implements Arcane::ISerializer.
Definition at line 320 of file BasicSerializer.h.
References get().
Referenced by Arcane::Numerics::ParallelCorefinementService::update().
getSpan() [1/11]
void Arcane::BasicSerializer::getSpan (Span< BFloat16 > values) override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 1295 of file BasicSerializer.cc.
References Arcane::ISerializer::ModeGet.
getSpan() [2/11]
void Arcane::BasicSerializer::getSpan (Span< Byte > values) override virtual
Retrieve the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 1262 of file BasicSerializer.cc.
References Arcane::Byte, and Arcane::ISerializer::ModeGet.
getSpan() [3/11]
void Arcane::BasicSerializer::getSpan (Span< Float128 > values) override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 1317 of file BasicSerializer.cc.
References Arcane::Float128, and Arcane::ISerializer::ModeGet.
getSpan() [4/11]
void Arcane::BasicSerializer::getSpan (Span< Float16 > values) override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 1284 of file BasicSerializer.cc.
References Arcane::Float16, and Arcane::ISerializer::ModeGet.
getSpan() [5/11]
void Arcane::BasicSerializer::getSpan (Span< Float32 > values) override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 1306 of file BasicSerializer.cc.
References Arcane::Float32, and Arcane::ISerializer::ModeGet.
getSpan() [6/11]
void Arcane::BasicSerializer::getSpan (Span< Int128 > values) override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 1328 of file BasicSerializer.cc.
References Arcane::Int128, and Arcane::ISerializer::ModeGet.
getSpan() [7/11]
void Arcane::BasicSerializer::getSpan (Span< Int16 > values) override virtual
Retrieve the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 1251 of file BasicSerializer.cc.
References Arcane::Int16, and Arcane::ISerializer::ModeGet.
getSpan() [8/11]
void Arcane::BasicSerializer::getSpan (Span< Int32 > values) override virtual
Retrieve the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 1240 of file BasicSerializer.cc.
References Arcane::Int32, and Arcane::ISerializer::ModeGet.
getSpan() [9/11]
void Arcane::BasicSerializer::getSpan (Span< Int64 > values) override virtual
Retrieve the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 1229 of file BasicSerializer.cc.
References Arcane::Int64, and Arcane::ISerializer::ModeGet.
getSpan() [10/11]
void Arcane::BasicSerializer::getSpan (Span< Int8 > values) override virtual
Retrieve the array values.
Implements Arcane::ISerializer.
Definition at line 1273 of file BasicSerializer.cc.
References Arcane::Int8, and Arcane::ISerializer::ModeGet.
getSpan() [11/11]
void Arcane::BasicSerializer::getSpan (Span< Real > values) override virtual
Retrieve the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 1218 of file BasicSerializer.cc.
References Arcane::Float64, and Arcane::ISerializer::ModeGet.
Referenced by get(), get(), get(), get(), get(), get(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getArray(), getBFloat16(), getFloat128(), getFloat16(), getFloat32(), getInt128(), and getInt8().
globalBuffer() [1/2]
Span< Byte > Arcane::BasicSerializer::globalBuffer ()
Definition at line 1510 of file BasicSerializer.cc.
globalBuffer() [2/2]
Span< const Byte > Arcane::BasicSerializer::globalBuffer () const
Definition at line 1519 of file BasicSerializer.cc.
initFromBuffer()
void Arcane::BasicSerializer::initFromBuffer (Span< const Byte > buf)
Initializes the serializer for reading from the data buf.
The array buf must have been obtained via the call to globalBuffer() from a writing serializer.
Definition at line 1591 of file BasicSerializer.cc.
References Arcane::ISerializer::ModeGet, setMode(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
Referenced by Arcane::PropertyMng::readFrom().
int16Buffer()
Span< Int16 > Arcane::BasicSerializer::int16Buffer ()
Definition at line 867 of file BasicSerializer.cc.
int32Buffer()
Span< Int32 > Arcane::BasicSerializer::int32Buffer ()
Definition at line 863 of file BasicSerializer.cc.
int64Buffer()
Span< Int64 > Arcane::BasicSerializer::int64Buffer ()
Definition at line 859 of file BasicSerializer.cc.
isSerializeTypeInfo()
bool Arcane::BasicSerializer::isSerializeTypeInfo () const
Definition at line 1613 of file BasicSerializer.cc.
mode()
BasicSerializer::eMode Arcane::BasicSerializer::mode () const override virtual
Current operating mode.
Implements Arcane::ISerializer.
Definition at line 1443 of file BasicSerializer.cc.
paddingSize()
ARCCORE_CONSTEXPR Integer Arcane::BasicSerializer::paddingSize () inline static
Padding and alignment size.
It is guaranteed that every array (buffer) managed by this serializer has a size that is a multiple of paddingSize() in bytes and an alignment on paddingSize().
Definition at line 476 of file BasicSerializer.h.
References ARCCORE_CONSTEXPR.
preallocate()
void Arcane::BasicSerializer::preallocate (Int64 size)
Definition at line 1546 of file BasicSerializer.cc.
printSizes()
void Arcane::BasicSerializer::printSizes (std::ostream & o) const
Definition at line 1582 of file BasicSerializer.cc.
put() [1/17]
void Arcane::BasicSerializer::put (BFloat16 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 206 of file BasicSerializer.h.
References putBFloat16().
put() [2/17]
void Arcane::BasicSerializer::put (Byte value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 194 of file BasicSerializer.h.
References putByte().
put() [3/17]
void Arcane::BasicSerializer::put (const String & value) override virtual
Add the string value.
Implements Arcane::ISerializer.
Definition at line 1126 of file BasicSerializer.cc.
References Arcane::String::bytes(), Arcane::String::length(), Arcane::ISerializer::ModePut, putInt64(), and putSpan().
put() [4/17]
void Arcane::BasicSerializer::put (Float128 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 214 of file BasicSerializer.h.
References putFloat128().
put() [5/17]
void Arcane::BasicSerializer::put (Float16 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 202 of file BasicSerializer.h.
References putFloat16().
put() [6/17]
void Arcane::BasicSerializer::put (Float32 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 210 of file BasicSerializer.h.
References putFloat32().
put() [7/17]
void Arcane::BasicSerializer::put (Int128 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 218 of file BasicSerializer.h.
References putInt128().
put() [8/17]
void Arcane::BasicSerializer::put (Int16 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 190 of file BasicSerializer.h.
References putInt16().
put() [9/17]
void Arcane::BasicSerializer::put (Int32 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 186 of file BasicSerializer.h.
References putInt32().
put() [10/17]
void Arcane::BasicSerializer::put (Int64 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 182 of file BasicSerializer.h.
References putInt64().
put() [11/17]
void Arcane::BasicSerializer::put (Int8 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 198 of file BasicSerializer.h.
References putInt8().
put() [12/17]
void Arcane::BasicSerializer::put (Real value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 178 of file BasicSerializer.h.
References putReal().
put() [13/17]
void Arcane::BasicSerializer::put (Span< const Byte > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1049 of file BasicSerializer.cc.
References Arcane::Byte, and Arcane::ISerializer::ModePut.
put() [14/17]
void Arcane::BasicSerializer::put (Span< const Int16 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1038 of file BasicSerializer.cc.
References Arcane::Int16, and Arcane::ISerializer::ModePut.
put() [15/17]
void Arcane::BasicSerializer::put (Span< const Int32 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1027 of file BasicSerializer.cc.
References Arcane::Int32, and Arcane::ISerializer::ModePut.
put() [16/17]
void Arcane::BasicSerializer::put (Span< const Int64 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1016 of file BasicSerializer.cc.
References Arcane::Int64, and Arcane::ISerializer::ModePut.
put() [17/17]
void Arcane::BasicSerializer::put (Span< const Real > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1005 of file BasicSerializer.cc.
References Arcane::Float64, and Arcane::ISerializer::ModePut.
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::Hdf5ReaderWriter::_writeValParallel(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::MessagePassing::filterCommonStrings(), Arcane::VariableUtilities::filterCommonVariables(), putByte(), putInt16(), putInt32(), putInt64(), putInteger(), putReal(), Arcane::Hdf5ReaderWriter::setMetaData(), and Arcane::Numerics::ParallelCorefinementService::update().
putArray() [1/11]
void Arcane::BasicSerializer::putArray (Span< const BFloat16 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1187 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [2/11]
void Arcane::BasicSerializer::putArray (Span< const Byte > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1166 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [3/11]
void Arcane::BasicSerializer::putArray (Span< const Float128 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1201 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [4/11]
void Arcane::BasicSerializer::putArray (Span< const Float16 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1180 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [5/11]
void Arcane::BasicSerializer::putArray (Span< const Float32 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1194 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [6/11]
void Arcane::BasicSerializer::putArray (Span< const Int128 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1208 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [7/11]
void Arcane::BasicSerializer::putArray (Span< const Int16 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1145 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [8/11]
void Arcane::BasicSerializer::putArray (Span< const Int32 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1152 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [9/11]
void Arcane::BasicSerializer::putArray (Span< const Int64 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1159 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [10/11]
void Arcane::BasicSerializer::putArray (Span< const Int8 > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1173 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
putArray() [11/11]
void Arcane::BasicSerializer::putArray (Span< const Real > values) override virtual
Save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 1138 of file BasicSerializer.cc.
References putInt64(), putSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
Referenced by Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), and Arcane::mesh::ParallelAMRConsistency::_gatherItems().
putBFloat16()
void Arcane::BasicSerializer::putBFloat16 (BFloat16 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 259 of file BasicSerializer.h.
References putSpan().
Referenced by put().
putByte()
void Arcane::BasicSerializer::putByte (Byte value) inline override virtual
Add the byte value.
Implements Arcane::ISerializer.
Definition at line 247 of file BasicSerializer.h.
References put().
Referenced by put().
putFloat128()
void Arcane::BasicSerializer::putFloat128 (Float128 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 267 of file BasicSerializer.h.
References putSpan().
Referenced by put().
putFloat16()
void Arcane::BasicSerializer::putFloat16 (Float16 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 255 of file BasicSerializer.h.
References putSpan().
Referenced by put().
putFloat32()
void Arcane::BasicSerializer::putFloat32 (Float32 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 263 of file BasicSerializer.h.
References putSpan().
Referenced by put().
putInt128()
void Arcane::BasicSerializer::putInt128 (Int128 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 271 of file BasicSerializer.h.
References putSpan().
Referenced by put().
putInt16()
void Arcane::BasicSerializer::putInt16 (Int16 value) inline override virtual
Add the integer value.
Implements Arcane::ISerializer.
Definition at line 235 of file BasicSerializer.h.
References put().
Referenced by put().
putInt32()
void Arcane::BasicSerializer::putInt32 (Int32 value) inline override virtual
Add the integer value.
Implements Arcane::ISerializer.
Definition at line 231 of file BasicSerializer.h.
References put().
Referenced by Arcane::Hdf5ReaderWriter::_writeValParallel(), Arcane::MessagePassing::filterCommonStrings(), and put().
putInt64()
void Arcane::BasicSerializer::putInt64 (Int64 value) inline override virtual
Add the integer value.
Implements Arcane::ISerializer.
Definition at line 227 of file BasicSerializer.h.
References put().
Referenced by put(), put(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), and putArray().
putInt8()
void Arcane::BasicSerializer::putInt8 (Int8 value) inline override virtual
Add value.
Implements Arcane::ISerializer.
Definition at line 251 of file BasicSerializer.h.
References putSpan().
Referenced by put().
putInteger()
void Arcane::BasicSerializer::putInteger (Integer value) inline override virtual
Add the integer value.
Implements Arcane::ISerializer.
Definition at line 239 of file BasicSerializer.h.
References put().
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::VariableUtilities::filterCommonVariables(), and Arcane::Numerics::ParallelCorefinementService::update().
putReal()
void Arcane::BasicSerializer::putReal (Real value) inline override virtual
Add the real value.
Implements Arcane::ISerializer.
Definition at line 223 of file BasicSerializer.h.
References put().
Referenced by put(), and Arcane::Numerics::ParallelCorefinementService::update().
putSpan() [1/11]
void Arcane::BasicSerializer::putSpan (Span< const BFloat16 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1082 of file BasicSerializer.cc.
References Arcane::ISerializer::ModePut.
putSpan() [2/11]
void Arcane::ISerializer::putSpan (Span< const Byte > values) private virtual
Add the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 258 of file SerializeGlobal.cc.
putSpan() [3/11]
void Arcane::BasicSerializer::putSpan (Span< const Float128 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1104 of file BasicSerializer.cc.
References Arcane::Float128, and Arcane::ISerializer::ModePut.
putSpan() [4/11]
void Arcane::BasicSerializer::putSpan (Span< const Float16 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1071 of file BasicSerializer.cc.
References Arcane::Float16, and Arcane::ISerializer::ModePut.
putSpan() [5/11]
void Arcane::BasicSerializer::putSpan (Span< const Float32 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1093 of file BasicSerializer.cc.
References Arcane::Float32, and Arcane::ISerializer::ModePut.
putSpan() [6/11]
void Arcane::BasicSerializer::putSpan (Span< const Int128 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1115 of file BasicSerializer.cc.
References Arcane::Int128, and Arcane::ISerializer::ModePut.
putSpan() [7/11]
void Arcane::ISerializer::putSpan (Span< const Int16 > values) private virtual
Add the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 252 of file SerializeGlobal.cc.
putSpan() [8/11]
void Arcane::ISerializer::putSpan (Span< const Int32 > values) private virtual
Add the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 254 of file SerializeGlobal.cc.
putSpan() [9/11]
void Arcane::ISerializer::putSpan (Span< const Int64 > values) private virtual
Add the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 256 of file SerializeGlobal.cc.
putSpan() [10/11]
void Arcane::BasicSerializer::putSpan (Span< const Int8 > values) override virtual
Add the array values.
Implements Arcane::ISerializer.
Definition at line 1060 of file BasicSerializer.cc.
References Arcane::Int8, and Arcane::ISerializer::ModePut.
Referenced by put(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putArray(), putBFloat16(), putFloat128(), putFloat16(), putFloat32(), putInt128(), and putInt8().
putSpan() [11/11]
void Arcane::ISerializer::putSpan (Span< const Real > values) private virtual
Add the array values.
Reimplemented from Arcane::ISerializer.
Definition at line 250 of file SerializeGlobal.cc.
readMode()
BasicSerializer::eReadMode Arcane::BasicSerializer::readMode () const override virtual
Read mode.
Implements Arcane::ISerializer.
Definition at line 1461 of file BasicSerializer.cc.
realBuffer()
Span< Real > Arcane::BasicSerializer::realBuffer ()
Definition at line 855 of file BasicSerializer.cc.
releaseBuffer()
void Arcane::BasicSerializer::releaseBuffer ()
Definition at line 1555 of file BasicSerializer.cc.
reserve() [1/4]
void Arcane::BasicSerializer::reserve (const String & str) override virtual
Reserve memory for a character string str.
Implements Arcane::ISerializer.
Definition at line 915 of file BasicSerializer.cc.
References Arcane::String::bytes(), Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserve() [2/4]
void Arcane::BasicSerializer::reserve (eBasicDataType dt, Int64 n) override virtual
Reserves memory for n objects of type dt.
n calls to a put() method with a single value must be made for the serialization to be correct.
If you want to serialize multiple values with a single call to put(), you must use the reserveSpan() method.
Implements Arcane::ISerializer.
Definition at line 906 of file BasicSerializer.cc.
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::Hdf5ReaderWriter::_writeValParallel(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::MessagePassing::filterCommonStrings(), Arcane::VariableUtilities::filterCommonVariables(), Arcane::Hdf5ReaderWriter::setMetaData(), and Arcane::Numerics::ParallelCorefinementService::update().
reserve() [3/4]
void Arcane::BasicSerializer::reserve (eDataType dt, Int64 n) override virtual
Reserves memory for n objects of type dt.
\dt must be an integral type: DT_Int16, DT_Int32, DT_Int64, DT_Real or DT_Byte.
n calls to a put() method with a single value must be made for the serialization to be correct.
If you want to serialize multiple values with a single call to put(), you must use the reserveSpan() method.
Implements Arcane::ISerializer.
Definition at line 897 of file BasicSerializer.cc.
reserve() [4/4]
void Arcane::ISerializer::reserve (int dt, Int64 n)
See also
reserve(eDataType dt,Int64 n)
Definition at line 225 of file SerializeGlobal.cc.
reserveArray() [1/11]
void Arcane::BasicSerializer::reserveArray (Span< const BFloat16 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 974 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [2/11]
void Arcane::BasicSerializer::reserveArray (Span< const Byte > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 953 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [3/11]
void Arcane::BasicSerializer::reserveArray (Span< const Float128 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 988 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [4/11]
void Arcane::BasicSerializer::reserveArray (Span< const Float16 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 967 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [5/11]
void Arcane::BasicSerializer::reserveArray (Span< const Float32 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 981 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [6/11]
void Arcane::BasicSerializer::reserveArray (Span< const Int128 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 995 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [7/11]
void Arcane::BasicSerializer::reserveArray (Span< const Int16 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 932 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [8/11]
void Arcane::BasicSerializer::reserveArray (Span< const Int32 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 939 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [9/11]
void Arcane::BasicSerializer::reserveArray (Span< const Int64 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 946 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [10/11]
void Arcane::BasicSerializer::reserveArray (Span< const Int8 > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 960 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
reserveArray() [11/11]
void Arcane::BasicSerializer::reserveArray (Span< const Real > values) override virtual
Reserve to save the number of elements and the values elements.
Implements Arcane::ISerializer.
Definition at line 925 of file BasicSerializer.cc.
References Arcane::ISerializer::reserveInt64(), and reserveSpan().
Referenced by Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), and Arcane::mesh::ParallelAMRConsistency::_gatherItems().
reserveInteger()
void Arcane::BasicSerializer::reserveInteger (Int64 n) inline override virtual
Implements Arcane::ISerializer.
Definition at line 143 of file BasicSerializer.h.
reserveSpan() [1/14]
void Arcane::BasicSerializer::reserveSpan (eBasicDataType dt, Int64 n) override virtual
Reserves memory for n values of dt.
A call to a putSpan() method must be made for the serialization to be correct.
Implements Arcane::ISerializer.
Definition at line 888 of file BasicSerializer.cc.
reserveSpan() [2/14]
void Arcane::BasicSerializer::reserveSpan (eDataType dt, Int64 n) override virtual
Reserves memory for n values of dt.
\dt must be an integral type: DT_Int16, DT_Int32, DT_Int64, DT_Real or DT_Byte.
A call to a putSpan() method must be made for the serialization to be correct.
Deprecated
Use reserveSpan(eBasicDataType) instead
Implements Arcane::ISerializer.
Definition at line 879 of file BasicSerializer.cc.
Referenced by reserve(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), reserveArray(), and reserveArray().
reserveSpan() [3/14]
void Arcane::ISerializer::reserveSpan (int dt, Int64 n) private
See also
reserve(eDataType dt,Int64 n)
Definition at line 207 of file SerializeGlobal.cc.
reserveSpan() [4/14]
void Arcane::ISerializer::reserveSpan (Span< const BFloat16 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 120 of file SerializeGlobal.cc.
reserveSpan() [5/14]
void Arcane::ISerializer::reserveSpan (Span< const Byte > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 114 of file SerializeGlobal.cc.
reserveSpan() [6/14]
void Arcane::ISerializer::reserveSpan (Span< const Float128 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 124 of file SerializeGlobal.cc.
References Arcane::Int128, Arcane::ISerializer::reserveSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
reserveSpan() [7/14]
void Arcane::ISerializer::reserveSpan (Span< const Float16 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 118 of file SerializeGlobal.cc.
References Arcane::Float128, Arcane::ISerializer::reserveSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
reserveSpan() [8/14]
void Arcane::ISerializer::reserveSpan (Span< const Float32 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 122 of file SerializeGlobal.cc.
reserveSpan() [9/14]
void Arcane::ISerializer::reserveSpan (Span< const Int128 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 126 of file SerializeGlobal.cc.
reserveSpan() [10/14]
void Arcane::ISerializer::reserveSpan (Span< const Int16 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 108 of file SerializeGlobal.cc.
reserveSpan() [11/14]
void Arcane::ISerializer::reserveSpan (Span< const Int32 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 110 of file SerializeGlobal.cc.
reserveSpan() [12/14]
void Arcane::ISerializer::reserveSpan (Span< const Int64 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 112 of file SerializeGlobal.cc.
References Arcane::ISerializer::DT_Float32, Arcane::ISerializer::reserveSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
reserveSpan() [13/14]
void Arcane::ISerializer::reserveSpan (Span< const Int8 > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 116 of file SerializeGlobal.cc.
reserveSpan() [14/14]
void Arcane::ISerializer::reserveSpan (Span< const Real > values) private virtual
Reserve for a view of values elements.
Reimplemented from Arcane::ISerializer.
Definition at line 106 of file SerializeGlobal.cc.
References Arcane::ISerializer::DT_BFloat16, Arcane::ISerializer::reserveSpan(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
setFromSizes()
void Arcane::BasicSerializer::setFromSizes ()
Definition at line 1564 of file BasicSerializer.cc.
setMode()
void Arcane::BasicSerializer::setMode (eMode new_mode) override virtual
Sets the current mode.
Implements Arcane::ISerializer.
Definition at line 1452 of file BasicSerializer.cc.
Referenced by Arcane::mesh::TiedInterfaceBuilder::_gatherAllNodesInfo(), Arcane::mesh::ParallelAMRConsistency::_gatherFaces(), Arcane::mesh::TiedInterfaceBuilder::_gatherFaces(), Arcane::mesh::ParallelAMRConsistency::_gatherItems(), Arcane::Hdf5ReaderWriter::_writeValParallel(), Arcane::mesh::CommonItemGroupFilterer::applyFiltering(), Arcane::MessagePassing::filterCommonStrings(), Arcane::VariableUtilities::filterCommonVariables(), initFromBuffer(), Arcane::Hdf5ReaderWriter::setMetaData(), Arcane::Numerics::ParallelCorefinementService::update(), and Arcane::PropertyMng::writeTo().
setReadMode()
void Arcane::BasicSerializer::setReadMode (eReadMode read_mode) override virtual
Sets the read mode.
Implements Arcane::ISerializer.
Definition at line 1470 of file BasicSerializer.cc.
setSerializeTypeInfo()
void Arcane::BasicSerializer::setSerializeTypeInfo (bool v)
Indicates whether to serialize the data type to ensure consistency.
If active, it requires that calls to reserve() and reserveArray() are consistent with put(). Since this has not been the case historically, this option is not active by default.
It is only useful to set this option during writing. In reading, the information is contained in the serializer.
Definition at line 1604 of file BasicSerializer.cc.
Referenced by Arcane::PropertyMng::readFrom(), and Arcane::PropertyMng::writeTo().
sizesBuffer()
ConstArrayView< Int64 > Arcane::BasicSerializer::sizesBuffer ()
Definition at line 1537 of file BasicSerializer.cc.
totalSize()
Int64 Arcane::BasicSerializer::totalSize () const
Definition at line 1573 of file BasicSerializer.cc.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & o, const BasicSerializer::SizesPrinter & x) friend
Definition at line 451 of file BasicSerializer.h.
Member Data Documentation
m_p2
Impl2* Arcane::BasicSerializer::m_p2 protected
Definition at line 481 of file BasicSerializer.h.
The documentation for this class was generated from the following files:
BasicSerializer.h
BasicSerializer.cc