Arcane: Arcane::Accelerator::Impl::GenericFilteringIf Class Reference
Arcane::Accelerator::Impl::GenericFilteringIf Class Reference
Public Member Functions
template<bool InPlace, typename SelectLambda, typename InputIterator, typename OutputIterator>
void apply (GenericFilteringBase &s, Int32 nb_item, InputIterator input_iter, OutputIterator output_iter, const SelectLambda &select_lambda, const TraceInfo &trace_info)
Applies the filter.
Detailed Description
Definition at line 259 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
Member Function Documentation
apply()
template<bool InPlace, typename SelectLambda, typename InputIterator, typename OutputIterator> void Arcane::Accelerator::Impl::GenericFilteringIf::apply (GenericFilteringBase & s, Int32 nb_item, InputIterator input_iter, OutputIterator output_iter, const SelectLambda & select_lambda, const TraceInfo & trace_info) inline
Applies the filter.
If InPlace is true, then OutputIterator equals InputIterator and we update input_iter directly.
Definition at line 270 of file arccore/src/accelerator/arccore/accelerator/GenericFilterer.h.
References ARCCORE_FATAL, Arcane::Accelerator::Impl::RunCommandLaunchInfo::beginExecute(), Arcane::Accelerator::CUDA, Arcane::Accelerator::Impl::RunCommandLaunchInfo::endExecute(), Arcane::Accelerator::RunQueue::executionPolicy(), Arcane::Accelerator::HIP, Arcane::Accelerator::Impl::RunCommandLaunchInfo::loopRunInfo(), Arcane::Accelerator::Impl::GenericFilteringBase::m_host_nb_out_storage, Arcane::Accelerator::Impl::GenericFilteringBase::m_queue, Arcane::Accelerator::makeCommand(), Arcane::Accelerator::Sequential, Arcane::Accelerator::SYCL, and Arcane::Accelerator::Thread.
Referenced by Arcane::Accelerator::GenericFilterer::applyIf(), Arcane::Accelerator::GenericFilterer::applyIf(), and Arcane::Accelerator::GenericFilterer::applyWithIndex().
The documentation for this class was generated from the following file:
arccore/src/accelerator/arccore/accelerator/GenericFilterer.h