Arcane: Arcane::MessagePassing::IMessagePassingMng Class Reference
Arcane::MessagePassing::IMessagePassingMng Class Reference abstract
Interface of the message passing manager.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/message_passing/arccore/message_passing/IMessagePassingMng.h>
Public Member Functions
virtual Int32 commRank () const =0
Rank of this instance in the communicator.
virtual Int32 commSize () const =0
Number of instances in the communicator.
virtual ITimeMetricCollector * timeMetricCollector () const =0
Interface for collecting execution times (can be null).
virtual Communicator communicator () const
MPI communicator associated with this instance.
virtual IDispatchers * dispatchers ()=0
Private Member Functions
ARCCORE_DECLARE_REFERENCE_COUNTED_INCLASS_METHODS ()
Friends
void mpDelete (IMessagePassingMng *p)
Destroys the instance p.
Detailed Description
Interface of the message passing manager.
This manager does not do much itself and merely delegates operations via the IDispatchers interface.
Instances of these classes must be destroyed via the method mpDelete().
Definition at line 48 of file IMessagePassingMng.h.
Member Function Documentation
commRank()
virtual Int32 Arcane::MessagePassing::IMessagePassingMng::commRank () const pure virtual
Rank of this instance in the communicator.
Implemented in Arcane::MessagePassing::MessagePassingMng, and Arccore::MessagePassing::MessagePassingMng.
Referenced by Arcane::MessagePassing::mpCreateSerializeMessage(), and Arcane::MessagePassing::mpCreateSerializeMessage().
commSize()
virtual Int32 Arcane::MessagePassing::IMessagePassingMng::commSize () const pure virtual
Number of instances in the communicator.
Implemented in Arcane::MessagePassing::MessagePassingMng, and Arccore::MessagePassing::MessagePassingMng.
communicator()
Communicator Arcane::MessagePassing::IMessagePassingMng::communicator () const virtual
MPI communicator associated with this instance.
The communicator is only valid if the instance is associated with an MPI implementation.
Reimplemented in Arcane::MessagePassing::MessagePassingMng, and Arccore::MessagePassing::MessagePassingMng.
Definition at line 89 of file MessagePassingMng.cc.
Referenced by timeMetricCollector().
timeMetricCollector()
virtual ITimeMetricCollector * Arcane::MessagePassing::IMessagePassingMng::timeMetricCollector () const pure virtual
Interface for collecting execution times (can be null).
Implemented in Arcane::MessagePassing::MessagePassingMng, and Arccore::MessagePassing::MessagePassingMng.
References communicator().
Friends And Related Symbol Documentation
mpDelete
void mpDelete (IMessagePassingMng * p) friend
Destroys the instance p.
The instance p must not be used after this call
Definition at line 81 of file MessagePassingMng.cc.
References mpDelete.
Referenced by mpDelete.
The documentation for this class was generated from the following files:
IMessagePassingMng.h
MessagePassingMng.cc