Arcane: Arcane::IModule Class Reference
Arcane::IModule Class Reference abstract
Module
Interface of a module.
#include <arcane/core/IModule.h>
Public Member Functions
virtual ~IModule ()
Destructor.
virtual String name () const =0
Module name.
virtual VersionInfo versionInfo () const =0
Module version.
virtual ISession * session () const =0
Module session.
virtual ISubDomain * subDomain () const =0
Sub-domain manager.
virtual IMesh * defaultMesh () const =0
Associated mesh. Can be null. Use defaultMeshHandle() instead.
virtual MeshHandle defaultMeshHandle () const =0
Associated mesh.
virtual IParallelMng * parallelMng () const =0
Message passing parallelism manager.
virtual IAcceleratorMng * acceleratorMng () const =0
Accelerator manager.
virtual ITraceMng * traceMng () const =0
Trace manager.
virtual void setUsed (bool v)=0
Indicates whether a module is used or not (internal).
virtual bool used () const =0
true if the module is used.
virtual void setDisabled (bool v)=0
Temporarily activates or deactivates the module (internal).
virtual bool disabled () const =0
true if the module is disabled
virtual bool isGarbageCollected () const =0
Indicates if the module is managed by a garbage collector, in which case the delete operator should not be called on it.
Detailed Description
Interface of a module.
Definition at line 39 of file IModule.h.
Constructor & Destructor Documentation
~IModule()
virtual Arcane::IModule::~IModule () inline virtual
Destructor.
Definition at line 44 of file IModule.h.
Member Function Documentation
acceleratorMng()
virtual IAcceleratorMng * Arcane::IModule::acceleratorMng () const pure virtual
Accelerator manager.
Implemented in Arcane::AbstractModule.
defaultMesh()
virtual IMesh * Arcane::IModule::defaultMesh () const pure virtual
Associated mesh. Can be null. Use defaultMeshHandle() instead.
Implemented in Arcane::AbstractModule.
defaultMeshHandle()
virtual MeshHandle Arcane::IModule::defaultMeshHandle () const pure virtual
Associated mesh.
Implemented in Arcane::AbstractModule.
disabled()
virtual bool Arcane::IModule::disabled () const pure virtual
true if the module is disabled
Implemented in Arcane::AbstractModule.
Referenced by Arcane::TimeLoopMng::doOneIteration().
isGarbageCollected()
virtual bool Arcane::IModule::isGarbageCollected () const pure virtual
Indicates if the module is managed by a garbage collector, in which case the delete operator should not be called on it.
Implemented in Arcane::AbstractModule.
name()
virtual String Arcane::IModule::name () const pure virtual
Module name.
Implemented in Arcane::AbstractModule.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint(), Arcane::EntryPointMng::addEntryPoint(), Arcane::TimeLoopMng::doOneIteration(), and Arcane::SubDomain::dumpInternalInfos().
parallelMng()
virtual IParallelMng * Arcane::IModule::parallelMng () const pure virtual
Message passing parallelism manager.
Implemented in Arcane::AbstractModule.
session()
virtual ISession * Arcane::IModule::session () const pure virtual
Module session.
Implemented in Arcane::AbstractModule.
setDisabled()
virtual void Arcane::IModule::setDisabled (bool v) pure virtual
Temporarily activates or deactivates the module (internal).
When a module is disabled, its calculation loop entry points are no longer called (but others like initialization or termination ones still are).
Implemented in Arcane::AbstractModule.
Referenced by Arcane::TimeLoopMng::doOneIteration().
setUsed()
virtual void Arcane::IModule::setUsed (bool v) pure virtual
Indicates whether a module is used or not (internal).
A module is used if and only if at least one of its entry points is used in the time loop.
Implemented in Arcane::AbstractModule.
Referenced by Arcane::TimeLoopMng::_addExecuteEntryPoint().
subDomain()
virtual ISubDomain * Arcane::IModule::subDomain () const pure virtual
Sub-domain manager.
Implemented in Arcane::AbstractModule.
traceMng()
virtual ITraceMng * Arcane::IModule::traceMng () const pure virtual
Trace manager.
Implemented in Arcane::AbstractModule.
used()
virtual bool Arcane::IModule::used () const pure virtual
true if the module is used.
Implemented in Arcane::AbstractModule.
Referenced by Arcane::VariableMng::initializeVariables().
versionInfo()
virtual VersionInfo Arcane::IModule::versionInfo () const pure virtual
Module version.
Implemented in Arcane::AbstractModule, Arcane::ArcaneCheckpointModule, Arcane::ArcaneLoadBalanceModule, Arcane::ArcanePostProcessingModule, Arcane::ArcaneVerifierModule, Arcane::MasterModule, Arcane::ModuleMaster, Arcane::TimeHistoryMng2, and Arcane::UnitTestModule.
The documentation for this class was generated from the following file:
IModule.h