Arcane: Arcane::ItemPairGroupImpl Class Reference
Arcane::ItemPairGroupImpl Class Reference
Implementation of an array of lists of entities.
#include <arcane/core/ItemPairGroupImpl.h>
Public Member Functions
ItemPairGroupImpl (const ItemGroup &group, const ItemGroup &sub_group)
~ItemPairGroupImpl () override
Releases resources.
virtual ISharedReference & sharedReference ()
const String & name () const
Group name.
virtual Integer nbRef () const
Number of references on the group.
bool null () const
Returns true if the group is null.
IMesh * mesh () const
Mesh to which the group belongs (0 for the null group).
eItemKind itemKind () const
Group kind. This is the kind of its elements.
eItemKind subItemKind () const
Group kind. This is the kind of its elements.
IItemFamily * itemFamily () const
Family to which the group belongs (or 0 if none).
IItemFamily * subItemFamily () const
Family to which the group belongs (or 0 if none).
const ItemGroup & itemGroup () const
Group of entities.
const ItemGroup & subItemGroup () const
Group of sub-entities.
Integer size () const
Number of entities in the group.
void invalidate (bool force_recompute)
Invalidates the group.
void checkValid ()
Checks that the group is valid.
bool checkNeedUpdate ()
Updates the group if necessary.
void changeIds (IntegerConstArrayView old_to_new_ids)
Changes the indices of the group's entities.
Array< Int64 > & unguardedIndexes () const
Array< Int32 > & unguardedLocalIds () const
void setComputeFunctor (IFunctor *functor)
Int64ArrayView indexes ()
Span< const Int32 > subItemsLocalId ()
void addRef () override
Increments the reference counter.
void removeRef () override
Decrements the reference counter.
Public Member Functions inherited from Arcane::SharedReference
void addRef () override
Increments the reference counter.
void removeRef () override
Decrements the reference counter.
Int32 refCount () const override
Returns the value of the reference counter.
Public Member Functions inherited from Arcane::ISharedReference
virtual ~ISharedReference ()=default
Releases resources.
Static Public Member Functions
static ItemPairGroupImpl * checkSharedNull ()
Static Public Attributes
static ItemPairGroupImpl * shared_null = 0
Private Member Functions
void deleteMe () override
Private Attributes
ItemPairGroupImplPrivate * m_p = nullptr
Group implementation.
Detailed Description
Implementation of an array of lists of entities.
Definition at line 34 of file ItemPairGroupImpl.h.
Constructor & Destructor Documentation
ItemPairGroupImpl() [1/2]
Arcane::ItemPairGroupImpl::ItemPairGroupImpl ()
Definition at line 189 of file ItemPairGroupImpl.cc.
ItemPairGroupImpl() [2/2]
Arcane::ItemPairGroupImpl::ItemPairGroupImpl (const ItemGroup & group, const ItemGroup & sub_group)
Definition at line 178 of file ItemPairGroupImpl.cc.
~ItemPairGroupImpl()
Arcane::ItemPairGroupImpl::~ItemPairGroupImpl () override
Releases resources.
Definition at line 198 of file ItemPairGroupImpl.cc.
References m_p.
Member Function Documentation
addRef()
void Arcane::ItemPairGroupImpl::addRef () override virtual
Increments the reference counter.
Implements Arcane::ISharedReference.
Definition at line 221 of file ItemPairGroupImpl.cc.
References Arcane::SharedReference::addRef().
checkNeedUpdate()
bool Arcane::ItemPairGroupImpl::checkNeedUpdate ()
Updates the group if necessary.
A group must be updated when it becomes invalid, for example following a call to invalidate().
Return values
true if the group was updated,
false otherwise.
Definition at line 330 of file ItemPairGroupImpl.cc.
References m_p.
Referenced by invalidate(), and size().
checkSharedNull()
ItemPairGroupImpl * Arcane::ItemPairGroupImpl::checkSharedNull () static
Definition at line 165 of file ItemPairGroupImpl.cc.
checkValid()
void Arcane::ItemPairGroupImpl::checkValid ()
Checks that the group is valid.
Definition at line 311 of file ItemPairGroupImpl.cc.
Referenced by size().
deleteMe()
void Arcane::ItemPairGroupImpl::deleteMe () override private virtual
Todo
To be deleted...
Implements Arcane::SharedReference.
Definition at line 212 of file ItemPairGroupImpl.cc.
indexes()
ArrayView< Int64 > Arcane::ItemPairGroupImpl::indexes ()
Definition at line 363 of file ItemPairGroupImpl.cc.
invalidate()
void Arcane::ItemPairGroupImpl::invalidate (bool force_recompute)
Invalidates the group.
Definition at line 319 of file ItemPairGroupImpl.cc.
References checkNeedUpdate(), and m_p.
Referenced by size().
itemFamily()
IItemFamily * Arcane::ItemPairGroupImpl::itemFamily () const
Family to which the group belongs (or 0 if none).
Definition at line 248 of file ItemPairGroupImpl.cc.
References m_p.
itemGroup()
const ItemGroup & Arcane::ItemPairGroupImpl::itemGroup () const
Group of entities.
Definition at line 293 of file ItemPairGroupImpl.cc.
References m_p.
itemKind()
eItemKind Arcane::ItemPairGroupImpl::itemKind () const
Group kind. This is the kind of its elements.
Definition at line 275 of file ItemPairGroupImpl.cc.
References m_p.
mesh()
IMesh * Arcane::ItemPairGroupImpl::mesh () const
Mesh to which the group belongs (0 for the null group).
Definition at line 239 of file ItemPairGroupImpl.cc.
References m_p.
nbRef()
virtual Integer Arcane::ItemPairGroupImpl::nbRef () const inline virtual
Number of references on the group.
Definition at line 58 of file ItemPairGroupImpl.h.
References Arcane::SharedReference::refCount().
null()
bool Arcane::ItemPairGroupImpl::null () const
Returns true if the group is null.
Definition at line 266 of file ItemPairGroupImpl.cc.
References m_p.
removeRef()
void Arcane::ItemPairGroupImpl::removeRef () override virtual
Decrements the reference counter.
Implements Arcane::ISharedReference.
Definition at line 230 of file ItemPairGroupImpl.cc.
References Arcane::SharedReference::removeRef().
setComputeFunctor()
void Arcane::ItemPairGroupImpl::setComputeFunctor (IFunctor * functor)
Definition at line 383 of file ItemPairGroupImpl.cc.
References m_p.
Referenced by changeIds().
sharedReference()
virtual ISharedReference & Arcane::ItemPairGroupImpl::sharedReference () inline virtual
Definition at line 50 of file ItemPairGroupImpl.h.
subItemFamily()
IItemFamily * Arcane::ItemPairGroupImpl::subItemFamily () const
Family to which the group belongs (or 0 if none).
Definition at line 257 of file ItemPairGroupImpl.cc.
References m_p.
subItemGroup()
const ItemGroup & Arcane::ItemPairGroupImpl::subItemGroup () const
Group of sub-entities.
Definition at line 302 of file ItemPairGroupImpl.cc.
References m_p.
subItemKind()
eItemKind Arcane::ItemPairGroupImpl::subItemKind () const
Group kind. This is the kind of its elements.
Definition at line 284 of file ItemPairGroupImpl.cc.
References m_p.
subItemsLocalId()
Span< const Int32 > Arcane::ItemPairGroupImpl::subItemsLocalId ()
Definition at line 373 of file ItemPairGroupImpl.cc.
unguardedIndexes()
Array< Int64 > & Arcane::ItemPairGroupImpl::unguardedIndexes () const
Definition at line 345 of file ItemPairGroupImpl.cc.
References m_p.
Referenced by changeIds().
unguardedLocalIds()
Array< Int32 > & Arcane::ItemPairGroupImpl::unguardedLocalIds () const
Definition at line 354 of file ItemPairGroupImpl.cc.
References m_p.
Referenced by changeIds().
Member Data Documentation
m_p
ItemPairGroupImplPrivate* Arcane::ItemPairGroupImpl::m_p = nullptr private
Group implementation.
Definition at line 127 of file ItemPairGroupImpl.h.
Referenced by checkNeedUpdate(), invalidate(), itemFamily(), itemGroup(), itemKind(), mesh(), null(), setComputeFunctor(), subItemFamily(), subItemGroup(), subItemKind(), unguardedIndexes(), unguardedLocalIds(), and ~ItemPairGroupImpl().
shared_null
ItemPairGroupImpl * Arcane::ItemPairGroupImpl::shared_null = 0 static
Definition at line 45 of file ItemPairGroupImpl.h.
The documentation for this class was generated from the following files:
ItemPairGroupImpl.h
ItemPairGroupImpl.cc