Arcane: Arcane::Numerics::GeometryKernelSurfaceToolsService Class Reference
Arcane::Numerics::GeometryKernelSurfaceToolsService Class Reference
Public Member Functions
GeometryKernelSurfaceToolsService (const Arcane::ServiceBuildInfo &sbi)
virtual ~GeometryKernelSurfaceToolsService ()
void init ()
Initialization.
ISurface * createSurface ()
Creation of a new surface.
void setFaceToSurface (ISurface *surface, FaceGroup face_group)
Defines the faces of a surface.
void computeSurfaceContact (ISurface *surface1, ISurface *surface2, FaceFaceContactList &contact)
compute for each face of surface1 the nearest face of surface2
Private Member Functions
GeometryKernelSurfaceImpl * castSurface (ISurface *) const
void buildFaceGroupSurface (FaceGroup group, GeometryKernelSurfaceImpl *surface_impl) const
Detailed Description
Definition at line 32 of file GeometryKernelSurfaceToolsService.h.
Constructor & Destructor Documentation
GeometryKernelSurfaceToolsService()
Arcane::Numerics::GeometryKernelSurfaceToolsService::GeometryKernelSurfaceToolsService (const Arcane::ServiceBuildInfo & sbi) inline
Class constructor
Definition at line 37 of file GeometryKernelSurfaceToolsService.h.
~GeometryKernelSurfaceToolsService()
virtual Arcane::Numerics::GeometryKernelSurfaceToolsService::~GeometryKernelSurfaceToolsService () inline virtual
Class destructor
Definition at line 44 of file GeometryKernelSurfaceToolsService.h.
Member Function Documentation
buildFaceGroupSurface()
void GeometryKernelSurfaceToolsService::buildFaceGroupSurface (FaceGroup group, GeometryKernelSurfaceImpl * surface_impl) const private
Definition at line 292 of file GeometryKernelSurfaceToolsService.cc.
castSurface()
GeometryKernelSurfaceImpl * GeometryKernelSurfaceToolsService::castSurface (ISurface * s) const private
Definition at line 281 of file GeometryKernelSurfaceToolsService.cc.
computeSurfaceContact()
void GeometryKernelSurfaceToolsService::computeSurfaceContact (ISurface * surface1, ISurface * surface2, FaceFaceContactList & contact)
compute for each face of surface1 the nearest face of surface2
Definition at line 63 of file GeometryKernelSurfaceToolsService.cc.
References Arcane::Array< T >::clear(), Arcane::Numerics::GeometryKernelSurfaceImpl::m_face_array, Arcane::Numerics::GeometryKernelSurfaceImpl::m_face_reorient, Arcane::Numerics::GeometryKernelSurfaceImpl::m_mean_normal, Arcane::math::min(), Arcane::ItemWithNodes::nbNode(), Arcane::math::normeR3(), Arcane::Item::null(), and Arcane::Parallel::ReduceSum.
createSurface()
ISurface * GeometryKernelSurfaceToolsService::createSurface ()
Creation of a new surface.
Definition at line 46 of file GeometryKernelSurfaceToolsService.cc.
init()
void GeometryKernelSurfaceToolsService::init ()
Initialization.
Definition at line 37 of file GeometryKernelSurfaceToolsService.cc.
setFaceToSurface()
void GeometryKernelSurfaceToolsService::setFaceToSurface (ISurface * surface, FaceGroup face_group)
Defines the faces of a surface.
Definition at line 54 of file GeometryKernelSurfaceToolsService.cc.
The documentation for this class was generated from the following files:
GeometryKernelSurfaceToolsService.h
GeometryKernelSurfaceToolsService.cc