Arcane: Arcane::ICaseOptionList Class Reference
Arcane::ICaseOptionList Class Reference abstract
Public Member Functions
virtual XmlNode rootElement () const =0
Returns the element associated with this options list.
virtual XmlNode parentElement () const =0
Returns the parent element.
virtual void addChild (ICaseOptions *co)=0
Adds the list co to the list of children.
virtual void removeChild (ICaseOptions *co)=0
Removes co from the list of children.
virtual ICaseMng * caseMng () const =0
Returns the case manager.
virtual void readChildren (bool is_phase1)=0
Reads the option values from the DOM elements.
virtual void printChildren (const String &lang, int indent)=0
Displays the list of child options in language lang and their value.
virtual String rootTagName () const =0
Returns the name of the element of this list.
virtual void deepGetChildren (Array< CaseOptionBase * > &col)=0
Adds all child options to the list col.
virtual bool isPresent () const =0
Indicates if the option is present in the data set.
virtual bool isOptional () const =0
Indicates if the option is optional.
virtual Integer minOccurs () const =0
Minimum number of occurrences.
virtual Integer maxOccurs () const =0
Maximum number of occurrences.
virtual void visit (ICaseDocumentVisitor *visitor)=0
Applies the visitor visitor.
virtual String xpathFullName () const =0
Full name in XPath format corresponding to rootElement().
virtual MeshHandle meshHandle () const =0
Handle of the associated mesh.
virtual ICaseDocumentFragment * caseDocumentFragment () const =0
Associated document.
virtual void disable ()=0
Disables the option as if it were absent.
virtual void addConfig (CaseOptionBase *o, XmlNode parent)=0
Adds option o with parent parent.
virtual void setRootElementWithParent (XmlNode parent_element)=0
Positions the root element of the list, with parent_element as parent. If already positioned, does nothing.
virtual void setRootElement (XmlNode root_element)=0
Positions the root element of the list. If already positioned, throws an exception.
virtual void addInvalidChildren (XmlNodeList &nlist)=0
Adds child elements that do not correspond to options in nlist.
virtual ICaseOptionListInternal * _internalApi ()=0
Internal Arcane API.
Detailed Description
Definition at line 38 of file ICaseOptionList.h.
Member Function Documentation
_internalApi()
virtual ICaseOptionListInternal * Arcane::ICaseOptionList::_internalApi () pure virtual
Internal Arcane API.
Implemented in Arcane::CaseOptionList.
References _internalApi().
Referenced by _internalApi(), and Arcane::CaseOptionListMulti::readChildren().
addChild()
virtual void Arcane::ICaseOptionList::addChild (ICaseOptions * co) pure virtual
Adds the list co to the list of children.
Implemented in Arcane::CaseOptionList.
addConfig()
virtual void Arcane::ICaseOptionList::addConfig (CaseOptionBase * o, XmlNode parent) pure virtual
Adds option o with parent parent.
Implemented in Arcane::CaseOptionList.
References addConfig().
Referenced by addConfig().
addInvalidChildren()
virtual void Arcane::ICaseOptionList::addInvalidChildren (XmlNodeList & nlist) pure virtual
Adds child elements that do not correspond to options in nlist.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
References addInvalidChildren().
Referenced by addInvalidChildren().
caseDocumentFragment()
virtual ICaseDocumentFragment * Arcane::ICaseOptionList::caseDocumentFragment () const pure virtual
Associated document.
Implemented in Arcane::CaseOptionList.
caseMng()
virtual ICaseMng * Arcane::ICaseOptionList::caseMng () const pure virtual
Returns the case manager.
Implemented in Arcane::CaseOptionList.
deepGetChildren()
virtual void Arcane::ICaseOptionList::deepGetChildren (Array< CaseOptionBase * > & col) pure virtual
Adds all child options to the list col.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
disable()
virtual void Arcane::ICaseOptionList::disable () pure virtual
Disables the option as if it were absent.
This is used, for example, if the option is associated with a mesh that is not defined.
Implemented in Arcane::CaseOptionList.
isOptional()
virtual bool Arcane::ICaseOptionList::isOptional () const pure virtual
Indicates if the option is optional.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
isPresent()
virtual bool Arcane::ICaseOptionList::isPresent () const pure virtual
Indicates if the option is present in the data set.
Implemented in Arcane::CaseOptionList.
maxOccurs()
virtual Integer Arcane::ICaseOptionList::maxOccurs () const pure virtual
Maximum number of occurrences.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
meshHandle()
virtual MeshHandle Arcane::ICaseOptionList::meshHandle () const pure virtual
Handle of the associated mesh.
Implemented in Arcane::CaseOptionList.
Referenced by Arcane::CaseOptionExtended::_search(), and Arcane::CaseOptionMultiExtended::_search().
minOccurs()
virtual Integer Arcane::ICaseOptionList::minOccurs () const pure virtual
Minimum number of occurrences.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
parentElement()
virtual XmlNode Arcane::ICaseOptionList::parentElement () const pure virtual
Returns the parent element.
Implemented in Arcane::CaseOptionList.
printChildren()
virtual void Arcane::ICaseOptionList::printChildren (const String & lang, int indent) pure virtual
Displays the list of child options in language lang and their value.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
readChildren()
virtual void Arcane::ICaseOptionList::readChildren (bool is_phase1) pure virtual
Reads the option values from the DOM elements.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
removeChild()
virtual void Arcane::ICaseOptionList::removeChild (ICaseOptions * co) pure virtual
Removes co from the list of children.
Implemented in Arcane::CaseOptionList.
rootElement()
virtual XmlNode Arcane::ICaseOptionList::rootElement () const pure virtual
Returns the element associated with this options list.
If there are none, returns a null XmlNode. If there are multiple, returns the first one.
Implemented in Arcane::CaseOptionList.
rootTagName()
virtual String Arcane::ICaseOptionList::rootTagName () const pure virtual
Returns the name of the element of this list.
Implemented in Arcane::CaseOptionList.
setRootElement()
virtual void Arcane::ICaseOptionList::setRootElement (XmlNode root_element) pure virtual
Positions the root element of the list. If already positioned, throws an exception.
Implemented in Arcane::CaseOptionList.
References setRootElement().
Referenced by setRootElement().
setRootElementWithParent()
virtual void Arcane::ICaseOptionList::setRootElementWithParent (XmlNode parent_element) pure virtual
Positions the root element of the list, with parent_element as parent. If already positioned, does nothing.
Implemented in Arcane::CaseOptionList.
References setRootElementWithParent().
Referenced by setRootElementWithParent().
visit()
virtual void Arcane::ICaseOptionList::visit (ICaseDocumentVisitor * visitor) pure virtual
Applies the visitor visitor.
Implemented in Arcane::CaseOptionList, and Arcane::CaseOptionListMulti.
xpathFullName()
virtual String Arcane::ICaseOptionList::xpathFullName () const pure virtual
Full name in XPath format corresponding to rootElement().
Implemented in Arcane::CaseOptionList.
The documentation for this class was generated from the following file:
ICaseOptionList.h