Arcane: Arcane::MeshHandleOrMesh Class Reference
Arcane::MeshHandleOrMesh Class Reference
Compatibility class to hold a MeshHandle or an IMesh*.
#include <arcane/core/MeshHandle.h>
Public Member Functions
MeshHandleOrMesh (const MeshHandle &handle)
Constructs an instance from a MeshHandle.
MeshHandleOrMesh (IMesh *mesh)
Constructs an instance from an IMesh*.
IMesh * mesh () const
Associated mesh. Can be null if the mesh has not yet been created.
operator IMesh * () const
Associated mesh. Can be null if the mesh has not yet been created.
const MeshHandle & handle () const
Associated handle.
Private Attributes
MeshHandle m_handle
Detailed Description
Compatibility class to hold a MeshHandle or an IMesh*.
Eventually, the constructors and converters to IMesh* will be removed.
Definition at line 195 of file MeshHandle.h.
Constructor & Destructor Documentation
MeshHandleOrMesh() [1/2]
Arcane::MeshHandleOrMesh::MeshHandleOrMesh (const MeshHandle & handle)
Constructs an instance from a MeshHandle.
Definition at line 198 of file MeshHandle.cc.
References handle().
MeshHandleOrMesh() [2/2]
Arcane::MeshHandleOrMesh::MeshHandleOrMesh (IMesh * mesh)
Constructs an instance from an IMesh*.
If mesh is null, the associated MeshHandle will also be null.
Definition at line 206 of file MeshHandle.cc.
References mesh().
Member Function Documentation
handle()
const MeshHandle & Arcane::MeshHandleOrMesh::handle () const inline
Associated handle.
Definition at line 219 of file MeshHandle.h.
Referenced by Arcane::ICartesianMesh::getReference(), Arcane::Materials::IMeshMaterialMng::getReference(), and MeshHandleOrMesh().
mesh()
IMesh * Arcane::MeshHandleOrMesh::mesh () const inline
Associated mesh. Can be null if the mesh has not yet been created.
Definition at line 213 of file MeshHandle.h.
Referenced by MeshHandleOrMesh(), and operator IMesh *().
operator IMesh *()
Arcane::MeshHandleOrMesh::operator IMesh * () const inline
Associated mesh. Can be null if the mesh has not yet been created.
Definition at line 216 of file MeshHandle.h.
References mesh().
Member Data Documentation
m_handle
MeshHandle Arcane::MeshHandleOrMesh::m_handle private
Definition at line 223 of file MeshHandle.h.
The documentation for this class was generated from the following files:
MeshHandle.h
MeshHandle.cc