Arcane: Arcane::CaseOptionError Class Reference
Arcane::CaseOptionError Class Reference
CaseOption
Error in the dataset.
#include <arcane/core/CaseOptionError.h>
Public Member Functions
CaseOptionError (const TraceInfo &where, const String &node_name, const String &message, bool is_collective=false)
Generic error.
const String & nodeName () const
const String & message () const
bool isCollective () const
const TraceInfo & trace () const
Static Public Member Functions
static void addInvalidTypeError (ICaseDocumentFragment *document, const TraceInfo &where, const String &node_name, const XmlNode &parent, const String &value, const String &expected_type)
Error when a dataset value is not of the correct type. This error is collective.
static void addInvalidTypeError (ICaseDocumentFragment *document, const TraceInfo &where, const String &node_name, const XmlNode &parent, const String &value, const String &expected_type, StringConstArrayView valid_values)
Error when a dataset value is not of the correct type. This error is collective.
static void addOptionNotFoundError (ICaseDocumentFragment *document, const TraceInfo &where, const String &node_name, const XmlNode &parent)
Error when a dataset option is not found. This error is collective.
static void addError (ICaseDocumentFragment *document, const TraceInfo &where, const String &node_name, const String &message, bool is_collective=false)
Generic error.
static void addWarning (ICaseDocumentFragment *document, const TraceInfo &where, const String &node_name, const String &message, bool is_collective=false)
Generic error.
Detailed Description
Error in the dataset.
Definition at line 41 of file CaseOptionError.h.
Constructor & Destructor Documentation
CaseOptionError()
Arcane::CaseOptionError::CaseOptionError (const TraceInfo & where, const String & node_name, const String & message, bool is_collective = false)
Generic error.
Definition at line 29 of file CaseOptionError.cc.
Referenced by addError(), addInvalidTypeError(), addInvalidTypeError(), addOptionNotFoundError(), and addWarning().
Member Function Documentation
addError()
void Arcane::CaseOptionError::addError (ICaseDocumentFragment * document, const TraceInfo & where, const String & node_name, const String & message, bool is_collective = false) static
Generic error.
Definition at line 94 of file CaseOptionError.cc.
References Arcane::ICaseDocumentFragment::addError(), and CaseOptionError().
Referenced by Arcane::CaseOptions::read().
addInvalidTypeError() [1/2]
void Arcane::CaseOptionError::addInvalidTypeError (ICaseDocumentFragment * document, const TraceInfo & where, const String & node_name, const XmlNode & parent, const String & value, const String & expected_type) static
Error when a dataset value is not of the correct type. This error is collective.
Definition at line 57 of file CaseOptionError.cc.
References Arcane::ICaseDocumentFragment::addError(), CaseOptionError(), and Arcane::XmlNode::xpathFullName().
Referenced by Arcane::CaseOptionExtended::_search(), Arcane::CaseOptionMultiExtended::_search(), Arcane::CaseOptionMultiSimpleT< T >::_search(), and Arcane::CaseOptionSimpleT< T >::_search().
addInvalidTypeError() [2/2]
void Arcane::CaseOptionError::addInvalidTypeError (ICaseDocumentFragment * document, const TraceInfo & where, const String & node_name, const XmlNode & parent, const String & value, const String & expected_type, StringConstArrayView valid_values) static
Error when a dataset value is not of the correct type. This error is collective.
Definition at line 75 of file CaseOptionError.cc.
References Arcane::ICaseDocumentFragment::addError(), CaseOptionError(), and Arcane::XmlNode::xpathFullName().
addOptionNotFoundError()
void Arcane::CaseOptionError::addOptionNotFoundError (ICaseDocumentFragment * document, const TraceInfo & where, const String & node_name, const XmlNode & parent) static
Error when a dataset option is not found. This error is collective.
Definition at line 42 of file CaseOptionError.cc.
References Arcane::ICaseDocumentFragment::addError(), CaseOptionError(), and Arcane::XmlNode::xpathFullName().
Referenced by Arcane::CaseOptionExtended::_search(), Arcane::CaseOptionMultiExtended::_search(), Arcane::CaseOptionMultiSimpleT< T >::_search(), and Arcane::CaseOptionSimpleT< T >::_search().
addWarning()
void Arcane::CaseOptionError::addWarning (ICaseDocumentFragment * document, const TraceInfo & where, const String & node_name, const String & message, bool is_collective = false) static
Generic error.
Definition at line 105 of file CaseOptionError.cc.
References Arcane::ICaseDocumentFragment::addWarning(), and CaseOptionError().
Referenced by Arcane::XmlElementContentChecker::check(), and Arcane::CaseOptionList::readChildren().
isCollective()
bool Arcane::CaseOptionError::isCollective () const inline
Definition at line 99 of file CaseOptionError.h.
message()
const String & Arcane::CaseOptionError::message () const inline
Definition at line 97 of file CaseOptionError.h.
nodeName()
const String & Arcane::CaseOptionError::nodeName () const inline
Definition at line 95 of file CaseOptionError.h.
trace()
const TraceInfo & Arcane::CaseOptionError::trace () const inline
Definition at line 101 of file CaseOptionError.h.
The documentation for this class was generated from the following files:
CaseOptionError.h
CaseOptionError.cc