Arcane: Arcane::FaceReorienter Class Reference
Arcane::FaceReorienter Class Reference
This function/class reorients faces.
#include <arcane/core/FaceReorienter.h>
Public Member Functions
ARCANE_DEPRECATED_260 FaceReorienter (ITraceMng *tm)
FaceReorienter (IMesh *mesh)
Constructor.
ARCANE_DEPRECATED_260 void checkAndChangeOrientation (ItemInternal *face)
ARCANE_DEPRECATED_260 void checkAndChangeOrientationAMR (ItemInternal *face)
void checkAndChangeOrientation (Face face)
Checks and optionally changes the orientation of the face.
void checkAndChangeOrientationAMR (Face face)
Checks and optionally changes the orientation of the face.
Detailed Description
This function/class reorients faces.
This class is used, for example, to ensure the correct orientation of faces after a mesh topology change.
Definition at line 36 of file FaceReorienter.h.
Constructor & Destructor Documentation
FaceReorienter() [1/2]
Arcane::FaceReorienter::FaceReorienter (ITraceMng * tm)
Constructor.
Deprecated
Use FaceReorienter(IMesh*) instead.
Definition at line 35 of file FaceReorienter.cc.
FaceReorienter() [2/2]
Arcane::FaceReorienter::FaceReorienter (IMesh * mesh) explicit
Constructor.
Definition at line 45 of file FaceReorienter.cc.
Member Function Documentation
checkAndChangeOrientation() [1/2]
void Arcane::FaceReorienter::checkAndChangeOrientation (Face face)
Checks and optionally changes the orientation of the face.
Parameters
face face to reorient
Definition at line 74 of file FaceReorienter.cc.
References ARCANE_FATAL, Arcane::Face::cell(), Arcane::Cell::face(), Arcane::Item::itemFamily(), Arcane::ItemTypeInfo::localFace(), Arcane::Item::localId(), Arcane::Face::nbCell(), Arcane::Cell::nbFace(), Arcane::ItemTypeInfo::LocalFace::nbNode(), Arcane::ItemWithNodes::nbNode(), Arcane::ItemTypeInfo::LocalFace::node(), Arcane::ItemWithNodes::node(), Arcane::IItemFamilyTopologyModifier::replaceNode(), Arcane::IItemFamilyTopologyModifier::setBackAndFrontCells(), Arcane::Item::typeInfo(), and Arcane::Item::uniqueId().
checkAndChangeOrientation() [2/2]
void Arcane::FaceReorienter::checkAndChangeOrientation (ItemInternal * face)
Deprecated
Use checkAndChangeOrientation(Face) instead.
Definition at line 56 of file FaceReorienter.cc.
References checkAndChangeOrientation().
Referenced by checkAndChangeOrientation().
checkAndChangeOrientationAMR() [1/2]
void Arcane::FaceReorienter::checkAndChangeOrientationAMR (Face face)
Checks and optionally changes the orientation of the face.
AMR.
Parameters
face face to reorient
Definition at line 165 of file FaceReorienter.cc.
References ARCANE_FATAL, Arcane::Face::cell(), Arcane::Cell::face(), Arcane::Item::itemFamily(), Arcane::Cell::level(), Arcane::ItemTypeInfo::localFace(), Arcane::Item::localId(), Arcane::Face::nbCell(), Arcane::Cell::nbFace(), Arcane::ItemTypeInfo::LocalFace::nbNode(), Arcane::ItemWithNodes::nbNode(), Arcane::ItemTypeInfo::LocalFace::node(), Arcane::ItemWithNodes::node(), Arcane::Item::null(), Arcane::IItemFamilyTopologyModifier::replaceNode(), Arcane::IItemFamilyTopologyModifier::setBackAndFrontCells(), Arcane::Item::typeInfo(), and Arcane::Item::uniqueId().
checkAndChangeOrientationAMR() [2/2]
void Arcane::FaceReorienter::checkAndChangeOrientationAMR (ItemInternal * face)
Deprecated
Use checkAndChangeOrientationAMR(Face) instead.
Definition at line 65 of file FaceReorienter.cc.
References checkAndChangeOrientationAMR().
Referenced by checkAndChangeOrientationAMR().
The documentation for this class was generated from the following files:
FaceReorienter.h
FaceReorienter.cc