Arcane: Arcane::TBBTaskImplementation Class Reference
Arcane::TBBTaskImplementation Class Reference
Classes
class MDParallelForExecute
class TaskInfoLockGuard
Class for positioning TaskThreadInfo::taskIndex().
class Impl
class ParallelForExecute
Public Member Functions
class ARCCORE_ALIGNAS_PACKED (64) TaskThreadInfo
void build ()
void initialize (Int32 nb_thread) override
void terminate () override
ITask * createRootTask (ITaskFunctor *f) override
Creates a root task. The implementation must copy the value of f, which is either a TaskFunctor or a TaskFunctorWithContext.
void executeParallelFor (Int32 begin, Int32 size, const ParallelLoopOptions &options, IRangeFunctor *f) final
Executes the functor f in parallel.
void executeParallelFor (Int32 begin, Int32 size, Integer grain_size, IRangeFunctor *f) final
Executes the functor f in parallel.
void executeParallelFor (Int32 begin, Int32 size, IRangeFunctor *f) final
Executes the functor f in parallel.
void executeParallelFor (const ParallelFor1DLoopInfo &loop_info) override
Executes the loop loop_info in parallel.
void executeParallelFor (const ComplexForLoopRanges< 1 > &loop_ranges, const ForLoopRunInfo &run_info, IMDRangeFunctor< 1 > *functor) final
Executes a 1D loop in parallel.
void executeParallelFor (const ComplexForLoopRanges< 2 > &loop_ranges, const ForLoopRunInfo &run_info, IMDRangeFunctor< 2 > *functor) final
Executes a 2D loop in parallel.
void executeParallelFor (const ComplexForLoopRanges< 3 > &loop_ranges, const ForLoopRunInfo &run_info, IMDRangeFunctor< 3 > *functor) final
Executes a 3D loop in parallel.
void executeParallelFor (const ComplexForLoopRanges< 4 > &loop_ranges, const ForLoopRunInfo &run_info, IMDRangeFunctor< 4 > *functor) final
Executes a 4D loop in parallel.
bool isActive () const final
Indicates if the implementation is active.
Int32 currentTaskThreadIndex () const final
Implementation of TaskFactory::currentTaskThreadIndex().
Int32 currentTaskIndex () const final
Implementation of TaskFactory::currentTaskIndex().
void printInfos (std::ostream &o) const final
Prints information about the runtime used.
TaskThreadInfo * currentTaskThreadInfo () const
Instance of TaskThreadInfo associated with the current thread.
Public Member Functions inherited from Arcane::ITaskImplementation
Int32 nbAllowedThread () const
Maximum number of threads used to manage tasks.
Private Member Functions
template<int RankValue>
void _executeMDParallelFor (const ComplexForLoopRanges< RankValue > &loop_ranges, IMDRangeFunctor< RankValue > *functor, const ForLoopRunInfo &run_info)
Execution of an N-dimensional loop.
void _executeParallelFor (const ParallelFor1DLoopInfo &loop_info)
Private Attributes
bool m_is_active = false
Impl * m_p = nullptr
Detailed Description
Definition at line 344 of file TBBTaskImplementation.cc.
Constructor & Destructor Documentation
~TBBTaskImplementation()
Arcane::TBBTaskImplementation::~TBBTaskImplementation () override
Definition at line 1036 of file TBBTaskImplementation.cc.
Member Function Documentation
_executeMDParallelFor()
template<int RankValue> void Arcane::TBBTaskImplementation::_executeMDParallelFor (const ComplexForLoopRanges< RankValue > & loop_ranges, IMDRangeFunctor< RankValue > * functor, const ForLoopRunInfo & run_info) private
Execution of an N-dimensional loop.
Warning
The current implementation does not take into account options for loops other than one dimension.
Definition at line 1147 of file TBBTaskImplementation.cc.
References Arcane::TaskFactory::defaultParallelLoopOptions(), Arcane::ParallelLoopOptions::grainSize(), Arcane::makeLoopRanges(), Arcane::ParallelLoopOptions::maxThread(), Arcane::ParallelLoopOptions::mergeUnsetValues(), and Arcane::TaskFactory::verboseLevel().
Referenced by executeParallelFor(), executeParallelFor(), executeParallelFor(), and executeParallelFor().
_executeParallelFor()
void Arcane::TBBTaskImplementation::_executeParallelFor (const ParallelFor1DLoopInfo & loop_info) private
Definition at line 1084 of file TBBTaskImplementation.cc.
ARCCORE_ALIGNAS_PACKED()
class Arcane::TBBTaskImplementation::ARCCORE_ALIGNAS_PACKED (64) inline
Definition at line 332 of file TBBTaskImplementation.cc.
build()
void Arcane::TBBTaskImplementation::build () inline
Definition at line 413 of file TBBTaskImplementation.cc.
createRootTask()
ITask * Arcane::TBBTaskImplementation::createRootTask (ITaskFunctor * f) inline override virtual
Creates a root task. The implementation must copy the value of f, which is either a TaskFunctor or a TaskFunctorWithContext.
Implements Arcane::ITaskImplementation.
Definition at line 417 of file TBBTaskImplementation.cc.
currentTaskIndex()
Int32 Arcane::TBBTaskImplementation::currentTaskIndex () const final virtual
Implementation of TaskFactory::currentTaskIndex().
Implements Arcane::ITaskImplementation.
Definition at line 1244 of file TBBTaskImplementation.cc.
References currentTaskThreadIndex(), and currentTaskThreadInfo().
currentTaskThreadIndex()
Int32 Arcane::TBBTaskImplementation::currentTaskThreadIndex () const inline final virtual
Implementation of TaskFactory::currentTaskThreadIndex().
Implements Arcane::ITaskImplementation.
Definition at line 461 of file TBBTaskImplementation.cc.
References Arcane::ITaskImplementation::nbAllowedThread().
Referenced by currentTaskIndex(), and currentTaskThreadInfo().
currentTaskThreadInfo()
TBBTaskImplementation::TaskThreadInfo * Arcane::TBBTaskImplementation::currentTaskThreadInfo () const
Instance of TaskThreadInfo associated with the current thread.
May be null if the current thread is not associated with a TBB thread or if it is outside the execution of a task or a parallel loop.
Definition at line 1232 of file TBBTaskImplementation.cc.
References currentTaskThreadIndex().
Referenced by currentTaskIndex().
executeParallelFor() [1/8]
void Arcane::TBBTaskImplementation::executeParallelFor (const ComplexForLoopRanges< 1 > & loop_ranges, const ForLoopRunInfo & run_info, IMDRangeFunctor< 1 > * functor) inline final virtual
Executes a 1D loop in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 431 of file TBBTaskImplementation.cc.
References _executeMDParallelFor().
executeParallelFor() [2/8]
void Arcane::TBBTaskImplementation::executeParallelFor (const ComplexForLoopRanges< 2 > & loop_ranges, const ForLoopRunInfo & run_info, IMDRangeFunctor< 2 > * functor) inline final virtual
Executes a 2D loop in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 437 of file TBBTaskImplementation.cc.
References _executeMDParallelFor().
executeParallelFor() [3/8]
void Arcane::TBBTaskImplementation::executeParallelFor (const ComplexForLoopRanges< 3 > & loop_ranges, const ForLoopRunInfo & run_info, IMDRangeFunctor< 3 > * functor) inline final virtual
Executes a 3D loop in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 443 of file TBBTaskImplementation.cc.
References _executeMDParallelFor().
executeParallelFor() [4/8]
void Arcane::TBBTaskImplementation::executeParallelFor (const ComplexForLoopRanges< 4 > & loop_ranges, const ForLoopRunInfo & run_info, IMDRangeFunctor< 4 > * functor) inline final virtual
Executes a 4D loop in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 449 of file TBBTaskImplementation.cc.
References _executeMDParallelFor().
executeParallelFor() [5/8]
void Arcane::TBBTaskImplementation::executeParallelFor (const ParallelFor1DLoopInfo & loop_info) override virtual
Executes the loop loop_info in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 1132 of file TBBTaskImplementation.cc.
executeParallelFor() [6/8]
void Arcane::TBBTaskImplementation::executeParallelFor (Int32 begin, Int32 size, const ParallelLoopOptions & options, IRangeFunctor * f) final virtual
Executes the functor f in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 1223 of file TBBTaskImplementation.cc.
References executeParallelFor().
Referenced by executeParallelFor(), executeParallelFor(), and executeParallelFor().
executeParallelFor() [7/8]
void Arcane::TBBTaskImplementation::executeParallelFor (Int32 begin, Int32 size, Integer block_size, IRangeFunctor * f) final virtual
Executes the functor f in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 1211 of file TBBTaskImplementation.cc.
References Arcane::TaskFactory::defaultParallelLoopOptions(), executeParallelFor(), and Arcane::ParallelLoopOptions::setGrainSize().
executeParallelFor() [8/8]
void Arcane::TBBTaskImplementation::executeParallelFor (Int32 begin, Int32 size, IRangeFunctor * f) inline final virtual
Executes the functor f in parallel.
Implements Arcane::ITaskImplementation.
Definition at line 425 of file TBBTaskImplementation.cc.
References Arcane::TaskFactory::defaultParallelLoopOptions(), and executeParallelFor().
initialize()
void Arcane::TBBTaskImplementation::initialize (Int32 nb_thread) override virtual
. Initializes the implementation with a maximum of nb_thread. If nb_thread is 0, the implementation can choose the number of threads automatically. This method is internal to Arcane and should only be called during the execution initialization.
Implements Arcane::ITaskImplementation.
Definition at line 1045 of file TBBTaskImplementation.cc.
References Arcane::TaskFactory::defaultParallelLoopOptions(), Arcane::ITaskImplementation::nbAllowedThread(), Arcane::TaskFactory::setDefaultParallelLoopOptions(), and Arcane::ParallelLoopOptions::setMaxThread().
isActive()
bool Arcane::TBBTaskImplementation::isActive () const inline final virtual
Indicates if the implementation is active.
Implements Arcane::ITaskImplementation.
Definition at line 456 of file TBBTaskImplementation.cc.
printInfos()
void Arcane::TBBTaskImplementation::printInfos (std::ostream & o) const final virtual
Prints information about the runtime used.
Implements Arcane::ITaskImplementation.
Definition at line 1072 of file TBBTaskImplementation.cc.
terminate()
void Arcane::TBBTaskImplementation::terminate () override virtual
. Terminates the use of the implementation. This method must be called only at the end of the calculation.
Implements Arcane::ITaskImplementation.
Definition at line 1063 of file TBBTaskImplementation.cc.
Member Data Documentation
m_is_active
bool Arcane::TBBTaskImplementation::m_is_active = false private
Definition at line 482 of file TBBTaskImplementation.cc.
m_p
Impl* Arcane::TBBTaskImplementation::m_p = nullptr private
Definition at line 483 of file TBBTaskImplementation.cc.
The documentation for this class was generated from the following file:
TBBTaskImplementation.cc