Arcane: Arcane::Accelerator::Impl::DeviceStorage< DataType, N > Class Template Reference
Arcane::Accelerator::Impl::DeviceStorage< DataType, N > Class Template Reference
Manages internal allocation on the device for a given type.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/accelerator/arccore/accelerator/CommonUtils.h>
Public Member Functions
DataType * address ()
size_t size () const
DataType * allocate ()
void deallocate ()
void copyToAsync (SmallSpan< DataType > dest_ptr, const RunQueue &queue)
Copies the instance into dest_ptr.
Additional Inherited Members
Protected Member Functions inherited from Arcane::Accelerator::Impl::DeviceStorageBase
void _copyToAsync (Span< std::byte > destination, Span< const std::byte > source, const RunQueue &queue)
Copies the instance into dest_ptr.
Protected Attributes inherited from Arcane::Accelerator::Impl::DeviceStorageBase
GenericDeviceStorage m_storage
Detailed Description
template<typename DataType, Int32 N = 1>
class Arcane::Accelerator::Impl::DeviceStorage< DataType, N >
Manages internal allocation on the device for a given type.
Definition at line 161 of file arccore/src/accelerator/arccore/accelerator/CommonUtils.h.
Member Function Documentation
address()
template<typename DataType, Int32 N = 1> DataType * Arcane::Accelerator::Impl::DeviceStorage< DataType, N >::address () inline
Definition at line 166 of file arccore/src/accelerator/arccore/accelerator/CommonUtils.h.
allocate()
template<typename DataType, Int32 N = 1> DataType * Arcane::Accelerator::Impl::DeviceStorage< DataType, N >::allocate () inline
Definition at line 168 of file arccore/src/accelerator/arccore/accelerator/CommonUtils.h.
copyToAsync()
template<typename DataType, Int32 N = 1> void Arcane::Accelerator::Impl::DeviceStorage< DataType, N >::copyToAsync (SmallSpan< DataType > dest_ptr, const RunQueue & queue) inline
Copies the instance into dest_ptr.
Definition at line 176 of file arccore/src/accelerator/arccore/accelerator/CommonUtils.h.
References Arcane::Accelerator::Impl::DeviceStorageBase::_copyToAsync(), and Arcane::asWritableBytes().
Referenced by Arcane::Accelerator::Impl::GenericPartitionerIf::apply(), and Arcane::Accelerator::Impl::GenericPartitionerIf::apply3().
deallocate()
template<typename DataType, Int32 N = 1> void Arcane::Accelerator::Impl::DeviceStorage< DataType, N >::deallocate () inline
Definition at line 173 of file arccore/src/accelerator/arccore/accelerator/CommonUtils.h.
size()
template<typename DataType, Int32 N = 1> size_t Arcane::Accelerator::Impl::DeviceStorage< DataType, N >::size () const inline
Definition at line 167 of file arccore/src/accelerator/arccore/accelerator/CommonUtils.h.
The documentation for this class was generated from the following file:
arccore/src/accelerator/arccore/accelerator/CommonUtils.h