Alien: Space related functions.
Space related functions.
Matrix Constructor » Block related API
Topics
Protection functions.
Functions
const ISpace & Alien::Move::MatrixData::rowSpace () const
const ISpace & Alien::Move::MatrixData::colSpace () const
const MatrixDistribution & Alien::Move::MatrixData::distribution () const
const ISpace & Alien::Move::VectorData::space () const
const VectorDistribution & Alien::Move::VectorData::distribution () const
Detailed Description
Function Documentation
colSpace()
const ISpace & Alien::Move::MatrixData::colSpace () const virtual
CoDomain Space of the current matrix
Returns
CoDomain Space.
Exceptions
FatalException if uninitialized. Call isNull before to avoid any problem.
Implements Alien::IMatrix.
Definition at line 175 of file MatrixData.cc.
Referenced by operator=().
distribution() [1/2]
const MatrixDistribution & Alien::Move::MatrixData::distribution () const
}@
Parallel distribution of the Matrix.
Returns
Parallel distribution of the Matrix.
Definition at line 183 of file MatrixData.cc.
Referenced by operator=().
distribution() [2/2]
const VectorDistribution & Alien::Move::VectorData::distribution () const
Parallel distribution of the Vector.
Returns
Parallel distribution of the Vector.
Definition at line 148 of file VectorData.cc.
Referenced by operator=().
rowSpace()
const ISpace & Alien::Move::MatrixData::rowSpace () const virtual
Domain Space of the current matrix
Returns
Domain Space.
Exceptions
FatalException if uninitialized. Call isNull before to avoid any problem.
Implements Alien::IMatrix.
Definition at line 167 of file MatrixData.cc.
Referenced by operator=().
space()
const ISpace & Alien::Move::VectorData::space () const virtual
Domain Space of the current vector
Returns
Definition Space.
Exceptions
FatalException if uninitialized. Call isNull before to avoid any problem.
Implements Alien::IVector.
Definition at line 140 of file VectorData.cc.
References impl(), and Alien::MultiVectorImpl::space().
Referenced by init(), operator=(), VectorData(), VectorData(), and ~VectorData().