Alien: Alien::StreamMatrixBuilderT< ValueT > Class Template Reference
Alien::StreamMatrixBuilderT< ValueT > Class Template Reference
Classes
class BaseInserter
class Profiler
class Filler
class Inserter
Public Types
enum eColOrdering { eUndef , eOwnAndGhost , eFull }
typedef Alien::Matrix MatrixType
using Matrix = Alien::Matrix
using BlockMatrix = Alien::BlockMatrix
Public Member Functions
StreamMatrixBuilderT (Matrix &matrix, bool init_and_start=true)
StreamMatrixBuilderT (BlockMatrix &matrix, bool init_and_start=true)
StreamMatrixBuilderT (IMatrix &matrix, bool init_and_start=true)
virtual ~StreamMatrixBuilderT ()
void setOrderRowColsOpt (bool value)
void setTraceMng (ITraceMng *trace_mng)
void init ()
void start ()
Inserter & getNewInserter ()
Inserter & getInserter (Integer id)
void allocate ()
void fillZero ()
void finalize ()
void end ()
Protected Types
enum State { eNone , eInit , ePrepared , eStart }
Protected Attributes
IMatrix & m_matrix
SimpleCSRMatrix< ValueT > * m_matrix_impl
Integer m_local_size = 0
Integer m_global_size = 0
Integer m_local_offset = 0
UniqueArray< Integer > m_ghost_row_size
Integer m_ghost_size = 0
UniqueArray< Integer > m_offset
Integer m_matrix_size = 0
UniqueArray< Integer > m_row_size
Integer m_myrank = 0
Integer m_nproc = 1
UniqueArray< Integer > m_ordered_idx
eColOrdering m_col_ordering
bool m_order_row_cols_opt = false
IMessagePassingMng * m_parallel_mng = nullptr
ITraceMng * m_trace = nullptr
State m_state
Private Member Functions
void _freeInserters ()
void computeProfile ()
Private Attributes
UniqueArray< Inserter * > m_inserters
Detailed Description
template<typename ValueT = Real>
class Alien::StreamMatrixBuilderT< ValueT >
Definition at line 30 of file StreamMatrixBuilder.h.
Member Typedef Documentation
BlockMatrix
template<typename ValueT = Real> using Alien::StreamMatrixBuilderT< ValueT >::BlockMatrix = Alien::BlockMatrix
Definition at line 40 of file StreamMatrixBuilder.h.
Matrix
template<typename ValueT = Real> using Alien::StreamMatrixBuilderT< ValueT >::Matrix = Alien::Matrix
Definition at line 39 of file StreamMatrixBuilder.h.
MatrixType
template<typename ValueT = Real> typedef Alien::Matrix Alien::StreamMatrixBuilderT< ValueT >::MatrixType
Definition at line 38 of file StreamMatrixBuilder.h.
Member Enumeration Documentation
eColOrdering
template<typename ValueT = Real> enum Alien::StreamMatrixBuilderT::eColOrdering
Definition at line 42 of file StreamMatrixBuilder.h.
State
template<typename ValueT = Real> enum Alien::StreamMatrixBuilderT::State protected
Definition at line 114 of file StreamMatrixBuilder.h.
Constructor & Destructor Documentation
StreamMatrixBuilderT() [1/3]
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::StreamMatrixBuilderT (Matrix & matrix, bool init_and_start = true)
Constructeur de la classe
Definition at line 54 of file StreamMatrixBuilderT.h.
StreamMatrixBuilderT() [2/3]
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::StreamMatrixBuilderT (BlockMatrix & matrix, bool init_and_start = true)
Definition at line 68 of file StreamMatrixBuilderT.h.
StreamMatrixBuilderT() [3/3]
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::StreamMatrixBuilderT (IMatrix & matrix, bool init_and_start = true)
Definition at line 83 of file StreamMatrixBuilderT.h.
~StreamMatrixBuilderT()
template<typename ValueT> Alien::StreamMatrixBuilderT< ValueT >::~StreamMatrixBuilderT () virtual
Destructeur de la classe
Definition at line 97 of file StreamMatrixBuilderT.h.
Member Function Documentation
_freeInserters()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::_freeInserters () private
Definition at line 165 of file StreamMatrixBuilderT.h.
allocate()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::allocate ()
Definition at line 157 of file StreamMatrixBuilderT.h.
computeProfile()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::computeProfile () private
Purpose : build the matrix profile store in inserter the position in the CSR matrix to avoid searching algorithm The CSR matrix has an extra position for ghost row equivalent to /dev/null When filling ghost row position, entries has written in that null position
Definition at line 230 of file StreamMatrixBuilderT.h.
References Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::count(), Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::getId(), Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::m_data_index, and Alien::StreamMatrixBuilderT< ValueT >::BaseInserter::size().
end()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::end ()
Definition at line 149 of file StreamMatrixBuilderT.h.
fillZero()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::fillZero ()
Definition at line 222 of file StreamMatrixBuilderT.h.
finalize()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::finalize ()
Definition at line 128 of file StreamMatrixBuilderT.h.
getInserter()
template<typename ValueT> StreamMatrixBuilderT< ValueT >::Inserter & Alien::StreamMatrixBuilderT< ValueT >::getInserter (Integer id)
Definition at line 117 of file StreamMatrixBuilderT.h.
getNewInserter()
template<typename ValueT> StreamMatrixBuilderT< ValueT >::Inserter & Alien::StreamMatrixBuilderT< ValueT >::getNewInserter ()
Definition at line 106 of file StreamMatrixBuilderT.h.
init()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::init ()
Definition at line 175 of file StreamMatrixBuilderT.h.
setOrderRowColsOpt()
template<typename ValueT = Real> void Alien::StreamMatrixBuilderT< ValueT >::setOrderRowColsOpt (bool value) inline
Definition at line 58 of file StreamMatrixBuilder.h.
setTraceMng()
template<typename ValueT = Real> void Alien::StreamMatrixBuilderT< ValueT >::setTraceMng (ITraceMng * trace_mng) inline
Definition at line 60 of file StreamMatrixBuilder.h.
start()
template<typename ValueT> void Alien::StreamMatrixBuilderT< ValueT >::start ()
Definition at line 213 of file StreamMatrixBuilderT.h.
Member Data Documentation
m_col_ordering
template<typename ValueT = Real> eColOrdering Alien::StreamMatrixBuilderT< ValueT >::m_col_ordering protected
Definition at line 108 of file StreamMatrixBuilder.h.
m_ghost_row_size
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::m_ghost_row_size protected
Definition at line 99 of file StreamMatrixBuilder.h.
m_ghost_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_ghost_size = 0 protected
Definition at line 100 of file StreamMatrixBuilder.h.
m_global_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_global_size = 0 protected
Definition at line 96 of file StreamMatrixBuilder.h.
m_inserters
template<typename ValueT = Real> UniqueArray<Inserter*> Alien::StreamMatrixBuilderT< ValueT >::m_inserters private
Definition at line 85 of file StreamMatrixBuilder.h.
m_local_offset
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_local_offset = 0 protected
Definition at line 97 of file StreamMatrixBuilder.h.
m_local_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_local_size = 0 protected
Definition at line 95 of file StreamMatrixBuilder.h.
m_matrix
template<typename ValueT = Real> IMatrix& Alien::StreamMatrixBuilderT< ValueT >::m_matrix protected
Definition at line 92 of file StreamMatrixBuilder.h.
m_matrix_impl
template<typename ValueT = Real> SimpleCSRMatrix<ValueT>* Alien::StreamMatrixBuilderT< ValueT >::m_matrix_impl protected
Definition at line 93 of file StreamMatrixBuilder.h.
m_matrix_size
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_matrix_size = 0 protected
Definition at line 102 of file StreamMatrixBuilder.h.
m_myrank
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_myrank = 0 protected
Definition at line 104 of file StreamMatrixBuilder.h.
m_nproc
template<typename ValueT = Real> Integer Alien::StreamMatrixBuilderT< ValueT >::m_nproc = 1 protected
Definition at line 105 of file StreamMatrixBuilder.h.
m_offset
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::m_offset protected
Definition at line 101 of file StreamMatrixBuilder.h.
m_order_row_cols_opt
template<typename ValueT = Real> bool Alien::StreamMatrixBuilderT< ValueT >::m_order_row_cols_opt = false protected
Definition at line 109 of file StreamMatrixBuilder.h.
m_ordered_idx
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::m_ordered_idx protected
Definition at line 107 of file StreamMatrixBuilder.h.
m_parallel_mng
template<typename ValueT = Real> IMessagePassingMng* Alien::StreamMatrixBuilderT< ValueT >::m_parallel_mng = nullptr protected
Definition at line 111 of file StreamMatrixBuilder.h.
m_row_size
template<typename ValueT = Real> UniqueArray<Integer> Alien::StreamMatrixBuilderT< ValueT >::m_row_size protected
Definition at line 103 of file StreamMatrixBuilder.h.
m_state
template<typename ValueT = Real> State Alien::StreamMatrixBuilderT< ValueT >::m_state protected
Definition at line 121 of file StreamMatrixBuilder.h.
m_trace
template<typename ValueT = Real> ITraceMng* Alien::StreamMatrixBuilderT< ValueT >::m_trace = nullptr protected
Definition at line 112 of file StreamMatrixBuilder.h.
The documentation for this class was generated from the following files:
StreamMatrixBuilder.h
StreamMatrixBuilderT.h