Arcane: Arcane::Materials::ConstituentConnectivityList Class Reference
Arcane::Materials::ConstituentConnectivityList Class Reference
Management of constituent connectivity lists.
#include <arcane/materials/internal/ComponentConnectivityList.h>
Classes
class ConstituentContainer
Container for connectivity data for a constituent type.
class NumberOfMaterialComputer
Class for calculating the number of materials in an environment.
class Container
Public Member Functions
ConstituentConnectivityList (MeshMaterialMng *mm)
ConstituentConnectivityList (ConstituentConnectivityList &&)=delete
ConstituentConnectivityList (const ConstituentConnectivityList &)=delete
ConstituentConnectivityList & operator= (ConstituentConnectivityList &&)=delete
ConstituentConnectivityList & operator= (const ConstituentConnectivityList &)=delete
void endCreate (bool is_continue)
void addCellsToEnvironment (Int16 env_id, ConstArrayView< Int32 > cell_ids)
void removeCellsToEnvironment (Int16 env_id, ConstArrayView< Int32 > cell_ids)
void addCellsToMaterial (Int16 mat_id, ConstArrayView< Int32 > cell_ids)
void removeCellsToMaterial (Int16 mat_id, ConstArrayView< Int32 > cell_ids)
ConstArrayView< Int16 > cellsNbEnvironment () const
ConstArrayView< Int16 > cellsNbMaterial () const
Int16 cellNbMaterial (CellLocalId cell_id, Int16 env_id)
Number of materials of the cell cell_id for environment index env_id.
IItemFamily * sourceFamily () const override
Source family.
void notifySourceFamilyLocalIdChanged (Int32ConstArrayView new_to_old_ids) override
Notifies the connectivity that the source family has been compacted.
void notifySourceItemAdded (ItemLocalId item) override
Notifies the connectivity that an entity has been added to the source family.
void reserveMemoryForNbSourceItems (Int32 n, bool pre_alloc_connectivity) override
Reserves memory for n source entities.
void notifyReadFromDump () override
Notifies the connectivity that a read has been performed from a dump.
Ref< IIncrementalItemSourceConnectivity > toSourceReference () override
Returns a reference to the instance.
ConstituentConnectivityList (MeshMaterialMng *mm)
ConstituentConnectivityList (ConstituentConnectivityList &&)=delete
ConstituentConnectivityList (const ConstituentConnectivityList &)=delete
ConstituentConnectivityList & operator= (ConstituentConnectivityList &&)=delete
ConstituentConnectivityList & operator= (const ConstituentConnectivityList &)=delete
void endCreate (bool is_continue)
void addCellsToEnvironment (Int16 env_id, SmallSpan< const Int32 > cell_ids, RunQueue &queue)
void removeCellsToEnvironment (Int16 env_id, SmallSpan< const Int32 > cell_ids, RunQueue &queue)
void addCellsToMaterial (Int16 mat_id, SmallSpan< const Int32 > cell_ids, RunQueue &queue)
void removeCellsToMaterial (Int16 mat_id, SmallSpan< const Int32 > cell_ids, RunQueue &queue)
ConstArrayView< Int16 > cellsNbEnvironment () const
Arrays of the total number of environments per cell (indexed by localId()).
ConstArrayView< Int16 > cellsNbMaterial () const
Arrays of the total number of materials per cell (indexed by localId()).
Int16 cellNbMaterial (CellLocalId cell_id, Int16 env_id) const
Number of materials of cell cell_id for environment index env_id.
void removeAllConnectivities ()
Removes all connected entities.
void fillCellsNbMaterial (SmallSpan< const Int32 > cells_local_id, Int16 env_id, SmallSpan< Int16 > cells_nb_material, RunQueue &queue)
Fills cells_nb_material with the number of materials of environment env_id.
Int32 fillCellsToTransform (SmallSpan< const Int32 > cells_local_id, Int16 env_id, SmallSpan< bool > cells_do_transform, bool is_add, RunQueue &queue)
Fills cells_do_transform indicating if the cell transitions from pure to partial.
void fillCellsIsPartial (SmallSpan< const Int32 > cells_local_id, Int16 env_id, SmallSpan< bool > cells_is_partial, RunQueue &queue)
Fills cells_is_partial indicating if the cell is partial for environment env_id.
void fillModifiedConstituents (SmallSpan< const Int32 > cells_local_id, SmallSpan< bool > is_modified_materials, SmallSpan< bool > is_modified_environments, int modified_mat_id, bool is_add, const RunQueue &queue)
Fills the constituents affected by a modification.
void printConstituents (SmallSpan< const Int32 > cells_local_id) const
Displays the constituents of a list of entities.
bool isActive () const
Indicates if the instance is active.
IItemFamily * sourceFamily () const override
Source family.
void notifySourceFamilyLocalIdChanged (Int32ConstArrayView new_to_old_ids) override
Notifies the connectivity that the source family has been compacted.
void notifySourceItemAdded (ItemLocalId item) override
Notifies the connectivity that an entity has been added to the source family.
void reserveMemoryForNbSourceItems (Int32 n, bool pre_alloc_connectivity) override
Reserves memory for n source entities.
void notifyReadFromDump () override
Notifies the connectivity that a read has been performed from a dump.
Ref< IIncrementalItemSourceConnectivity > toSourceReference () override
Returns a reference to the instance.
void _addCells (Int16 env_id, SmallSpan< const Int32 > cell_ids, ConstituentContainer &component, RunQueue &queue)
void _removeCells (Int16 env_id, SmallSpan< const Int32 > cell_ids, ConstituentContainer &component, RunQueue &queue)
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Public Member Functions inherited from Arcane::ReferenceCounterImpl
void addReference ()
void removeReference ()
void _internalAddReference ()
bool _internalRemoveReference ()
Private Member Functions
ARCCORE_DEFINE_REFERENCE_COUNTED_INCLASS_METHODS ()
void _addCells (Int16 env_id, ConstArrayView< Int32 > cell_ids, ComponentContainer &component)
void _removeCells (Int16 env_id, ConstArrayView< Int32 > cell_ids, ComponentContainer &component)
ARCCORE_DEFINE_REFERENCE_COUNTED_INCLASS_METHODS ()
Private Attributes
MeshMaterialMng * m_material_mng = nullptr
IItemFamily * m_cell_family = nullptr
Container * m_container = nullptr
UniqueArray< Int16 > m_environment_for_materials
Index of the environment to which a material belongs.
DualUniqueArray< Int16 > m_environment_for_materials
Index of the environment to which a material belongs.
bool m_is_active = false
bool m_is_force_transform_all_constituants = false
Additional Inherited Members
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Detailed Description
Management of constituent connectivity lists.
Definition at line 39 of file ComponentConnectivityList.h.
Constructor & Destructor Documentation
ConstituentConnectivityList()
Arcane::Materials::ConstituentConnectivityList::ConstituentConnectivityList (MeshMaterialMng * mm) explicit
Definition at line 291 of file ConstituentConnectivityList.cc.
~ConstituentConnectivityList()
Arcane::Materials::ConstituentConnectivityList::~ConstituentConnectivityList ()
Definition at line 307 of file ConstituentConnectivityList.cc.
Member Function Documentation
_addCells()
void Arcane::Materials::ConstituentConnectivityList::_addCells (Int16 env_id, SmallSpan< const Int32 > cell_ids, ConstituentContainer & component, RunQueue & queue)
Definition at line 359 of file ConstituentConnectivityList.cc.
_removeCells()
void Arcane::Materials::ConstituentConnectivityList::_removeCells (Int16 env_id, SmallSpan< const Int32 > cell_ids, ConstituentContainer & component, RunQueue & queue)
Definition at line 433 of file ConstituentConnectivityList.cc.
addCellsToEnvironment()
void Arcane::Materials::ConstituentConnectivityList::addCellsToEnvironment (Int16 env_id, SmallSpan< const Int32 > cell_ids, RunQueue & queue)
Definition at line 463 of file ConstituentConnectivityList.cc.
addCellsToMaterial()
void Arcane::Materials::ConstituentConnectivityList::addCellsToMaterial (Int16 mat_id, SmallSpan< const Int32 > cell_ids, RunQueue & queue)
Definition at line 481 of file ConstituentConnectivityList.cc.
cellNbMaterial()
Int16 Arcane::Materials::ConstituentConnectivityList::cellNbMaterial (CellLocalId cell_id, Int16 env_id) const
Number of materials of cell cell_id for environment index env_id.
Definition at line 520 of file ConstituentConnectivityList.cc.
References m_environment_for_materials.
cellsNbEnvironment()
ConstArrayView< Int16 > Arcane::Materials::ConstituentConnectivityList::cellsNbEnvironment () const
Definition at line 499 of file ConstituentConnectivityList.cc.
cellsNbMaterial()
ConstArrayView< Int16 > Arcane::Materials::ConstituentConnectivityList::cellsNbMaterial () const
Definition at line 508 of file ConstituentConnectivityList.cc.
endCreate()
void Arcane::Materials::ConstituentConnectivityList::endCreate (bool is_continue)
Definition at line 316 of file ConstituentConnectivityList.cc.
fillCellsIsPartial()
void Arcane::Materials::ConstituentConnectivityList::fillCellsIsPartial (SmallSpan< const Int32 > cells_local_id, Int16 env_id, SmallSpan< bool > cells_is_partial, RunQueue & queue)
Fills cells_is_partial indicating if the cell is partial for environment env_id.
Definition at line 608 of file ConstituentConnectivityList.cc.
References cellsNbEnvironment(), Arcane::Accelerator::RunQueue::isAcceleratorPolicy(), m_environment_for_materials, Arcane::Accelerator::makeCommand(), RUNCOMMAND_LOOP1, and Arcane::SpanImpl< T, SizeType, Extent >::size().
Referenced by Arcane::Materials::IncrementalComponentModifier::_addItemsToEnvironment().
fillCellsNbMaterial()
void Arcane::Materials::ConstituentConnectivityList::fillCellsNbMaterial (SmallSpan< const Int32 > cells_local_id, Int16 env_id, SmallSpan< Int16 > cells_nb_material, RunQueue & queue)
Fills cells_nb_material with the number of materials of environment env_id.
Definition at line 537 of file ConstituentConnectivityList.cc.
References Arcane::Accelerator::RunQueue::executionPolicy(), Arcane::Accelerator::isAcceleratorPolicy(), m_environment_for_materials, Arcane::Accelerator::makeCommand(), RUNCOMMAND_LOOP1, and Arcane::SpanImpl< T, SizeType, Extent >::size().
fillCellsToTransform()
Int32 Arcane::Materials::ConstituentConnectivityList::fillCellsToTransform (SmallSpan< const Int32 > cells_local_id, Int16 env_id, SmallSpan< bool > cells_do_transform, bool is_add, RunQueue & queue)
Fills cells_do_transform indicating if the cell transitions from pure to partial.
Returns the number of transformed cells
Definition at line 564 of file ConstituentConnectivityList.cc.
References cellsNbEnvironment(), Arcane::Accelerator::RunQueue::isAcceleratorPolicy(), m_environment_for_materials, Arcane::Accelerator::makeCommand(), RUNCOMMAND_LOOP1, and Arcane::SpanImpl< T, SizeType, Extent >::size().
Referenced by Arcane::Materials::IncrementalComponentModifier::_computeCellsToTransformForMaterial().
fillModifiedConstituents()
void Arcane::Materials::ConstituentConnectivityList::fillModifiedConstituents (SmallSpan< const Int32 > cells_local_id, SmallSpan< bool > is_modified_materials, SmallSpan< bool > is_modified_environments, int modified_mat_id, bool is_add, const RunQueue & queue)
Fills the constituents affected by a modification.
The cells affected by the modification are given by cells_local_id. modified_mat_id is the ID of the material added (if is_add is true) or removed (if is_add is false).
Sets is_modified_materials and is_modified_environments to true if they are in one of the cells in cells_local_id.
This method allows optimizing the calculation of constituents that will be impacted by a modification by trying to determine in advance which ones will be impacted. This avoids calling calculation kernels (for example, calculating the list of cells to transform for a constituent) if we know the constituent is not impacted.
It is possible to revert to the old mechanism and remove this optimization by filling is_modified_materials and is_modified_environments with true for all constituents. This is the case if m_is_force_transform_all_constituants is true.
Note
it is important that is_modified_materials and is_modified_environments is true if the corresponding constituent is modified. Otherwise, there will be an inconsistency in the constituents. However, it is not serious if we mark a constituent as modified and it turns out not to be the case. This just means we will perform unnecessary operations (in MeshMaterialVariableIndexer::transformCells()).
Definition at line 679 of file ConstituentConnectivityList.cc.
References cellsNbEnvironment(), Arcane::ITraceMng::info(), Arcane::Accelerator::RunQueue::isAcceleratorPolicy(), m_environment_for_materials, Arcane::Accelerator::makeCommand(), RUNCOMMAND_LOOP1, Arcane::SpanImpl< T, SizeType, Extent >::size(), and Arcane::TraceAccessor::traceMng().
isActive()
bool Arcane::Materials::ConstituentConnectivityList::isActive () const inline
Indicates if the instance is active.
Valid only after calling endCreate(). If the instance is not active, none of the methods that modify the constituent list should be called.
Definition at line 121 of file ConstituentConnectivityList.h.
notifyReadFromDump() [1/2]
void Arcane::Materials::ConstituentConnectivityList::notifyReadFromDump () override virtual
Notifies the connectivity that a read has been performed from a dump.
Implements Arcane::IIncrementalItemSourceConnectivity.
Definition at line 826 of file ConstituentConnectivityList.cc.
notifyReadFromDump() [2/2]
void Arcane::Materials::ConstituentConnectivityList::notifyReadFromDump () override virtual
Notifies the connectivity that a read has been performed from a dump.
Implements Arcane::IIncrementalItemSourceConnectivity.
notifySourceFamilyLocalIdChanged() [1/2]
void Arcane::Materials::ConstituentConnectivityList::notifySourceFamilyLocalIdChanged (Int32ConstArrayView new_to_old_ids) override virtual
Notifies the connectivity that the source family has been compacted.
Implements Arcane::IIncrementalItemSourceConnectivity.
Definition at line 791 of file ConstituentConnectivityList.cc.
notifySourceFamilyLocalIdChanged() [2/2]
void Arcane::Materials::ConstituentConnectivityList::notifySourceFamilyLocalIdChanged (Int32ConstArrayView new_to_old_ids) override virtual
Notifies the connectivity that the source family has been compacted.
Implements Arcane::IIncrementalItemSourceConnectivity.
notifySourceItemAdded() [1/2]
void Arcane::Materials::ConstituentConnectivityList::notifySourceItemAdded (ItemLocalId item) override virtual
Notifies the connectivity that an entity has been added to the source family.
Implements Arcane::IIncrementalItemSourceConnectivity.
Definition at line 800 of file ConstituentConnectivityList.cc.
notifySourceItemAdded() [2/2]
void Arcane::Materials::ConstituentConnectivityList::notifySourceItemAdded (ItemLocalId item) override virtual
Notifies the connectivity that an entity has been added to the source family.
Implements Arcane::IIncrementalItemSourceConnectivity.
printConstituents()
void Arcane::Materials::ConstituentConnectivityList::printConstituents (SmallSpan< const Int32 > cells_local_id) const
Displays the constituents of a list of entities.
Parameters
cells_local_id List of local IDs of the entities
Definition at line 638 of file ConstituentConnectivityList.cc.
References Arcane::TraceAccessor::info(), and Arcane::SpanImpl< T, SizeType, Extent >::size().
removeAllConnectivities()
void Arcane::Materials::ConstituentConnectivityList::removeAllConnectivities ()
Removes all connected entities.
Definition at line 843 of file ConstituentConnectivityList.cc.
removeCellsToEnvironment()
void Arcane::Materials::ConstituentConnectivityList::removeCellsToEnvironment (Int16 env_id, SmallSpan< const Int32 > cell_ids, RunQueue & queue)
Definition at line 472 of file ConstituentConnectivityList.cc.
removeCellsToMaterial()
void Arcane::Materials::ConstituentConnectivityList::removeCellsToMaterial (Int16 mat_id, SmallSpan< const Int32 > cell_ids, RunQueue & queue)
Definition at line 490 of file ConstituentConnectivityList.cc.
reserveMemoryForNbSourceItems() [1/2]
void Arcane::Materials::ConstituentConnectivityList::reserveMemoryForNbSourceItems (Int32 n, bool pre_alloc_connectivity) override virtual
Reserves memory for n source entities.
Calling this method is optional but prevents multiple reallocations during successive calls to notifySourceItemAdded().
If pre_alloc_connectivity is true, it also pre-allocates the list of connectivities based on the value of preAllocatedSize(). For example, if preAllocatedSize() is 4 and n is 10000, we will pre-allocate for 40000 connectivities. To avoid unnecessary memory overconsumption, connectivities should only be pre-allocated if we are sure we will use them.
Reimplemented from Arcane::IIncrementalItemSourceConnectivity.
Definition at line 816 of file ConstituentConnectivityList.cc.
References Arcane::TraceAccessor::info().
reserveMemoryForNbSourceItems() [2/2]
void Arcane::Materials::ConstituentConnectivityList::reserveMemoryForNbSourceItems (Int32 n, bool pre_alloc_connectivity) override virtual
Reserves memory for n source entities.
Calling this method is optional but prevents multiple reallocations during successive calls to notifySourceItemAdded().
If pre_alloc_connectivity is true, it also pre-allocates the list of connectivities based on the value of preAllocatedSize(). For example, if preAllocatedSize() is 4 and n is 10000, we will pre-allocate for 40000 connectivities. To avoid unnecessary memory overconsumption, connectivities should only be pre-allocated if we are sure we will use them.
Reimplemented from Arcane::IIncrementalItemSourceConnectivity.
sourceFamily() [1/2]
IItemFamily * Arcane::Materials::ConstituentConnectivityList::sourceFamily () const inline override virtual
Source family.
Implements Arcane::IIncrementalItemSourceConnectivity.
Definition at line 81 of file ComponentConnectivityList.h.
sourceFamily() [2/2]
IItemFamily * Arcane::Materials::ConstituentConnectivityList::sourceFamily () const inline override virtual
Source family.
Implements Arcane::IIncrementalItemSourceConnectivity.
Definition at line 127 of file ConstituentConnectivityList.h.
toSourceReference() [1/2]
Ref< IIncrementalItemSourceConnectivity > Arcane::Materials::ConstituentConnectivityList::toSourceReference () override virtual
Returns a reference to the instance.
Implements Arcane::IIncrementalItemSourceConnectivity.
Definition at line 834 of file ConstituentConnectivityList.cc.
References Arccore::makeRef().
toSourceReference() [2/2]
Ref< IIncrementalItemSourceConnectivity > Arcane::Materials::ConstituentConnectivityList::toSourceReference () override virtual
Returns a reference to the instance.
Implements Arcane::IIncrementalItemSourceConnectivity.
Member Data Documentation
m_cell_family
IItemFamily * Arcane::Materials::ConstituentConnectivityList::m_cell_family = nullptr private
Definition at line 92 of file ComponentConnectivityList.h.
m_container
Container * Arcane::Materials::ConstituentConnectivityList::m_container = nullptr private
Definition at line 93 of file ComponentConnectivityList.h.
m_environment_for_materials [1/2]
UniqueArray<Int16> Arcane::Materials::ConstituentConnectivityList::m_environment_for_materials private
Index of the environment to which a material belongs.
Definition at line 96 of file ComponentConnectivityList.h.
Referenced by cellNbMaterial(), fillCellsIsPartial(), fillCellsNbMaterial(), fillCellsToTransform(), and fillModifiedConstituents().
m_environment_for_materials [2/2]
DualUniqueArray<Int16> Arcane::Materials::ConstituentConnectivityList::m_environment_for_materials private
Index of the environment to which a material belongs.
Definition at line 142 of file ConstituentConnectivityList.h.
m_is_active
bool Arcane::Materials::ConstituentConnectivityList::m_is_active = false private
Definition at line 143 of file ConstituentConnectivityList.h.
m_is_force_transform_all_constituants
bool Arcane::Materials::ConstituentConnectivityList::m_is_force_transform_all_constituants = false private
Definition at line 144 of file ConstituentConnectivityList.h.
m_material_mng
MeshMaterialMng * Arcane::Materials::ConstituentConnectivityList::m_material_mng = nullptr private
Definition at line 91 of file ComponentConnectivityList.h.
The documentation for this class was generated from the following files:
ComponentConnectivityList.h
ConstituentConnectivityList.h
ConstituentConnectivityList.cc