Arcane: Arcane::MeshHandle Class Reference
Arcane::MeshHandle Class Reference
Handle on a mesh.
#include <arcane/core/MeshHandle.h>
Classes
class MeshHandleRef
Public Member Functions
IMesh * mesh () const
Associated mesh.
bool hasMesh () const
Indicates if the associated mesh has already been created (i.e.: mesh() is valid).
IMesh * meshOrNull () const
Returns the mesh associated with this instance.
ISubDomain * subDomain () const
Associated sub-domain. Null if isNull() is true.
IMeshMng * meshMng () const
Associated mesh manager. nullptr if isNull() is true.
ITraceMng * traceMng () const
Associated trace manager. nullptr if isNull() is true.
IVariableMng * variableMng () const
Associated variable manager. nullptr if isNull() is true.
IApplication * application () const
Associated application. nullptr if isNull() is true.
IUserDataList * meshUserDataList () const
Associated user data.
const String & meshName () const
bool isNull () const
Indicates if the handle is null (it does not reference any existing mesh or not).
IObservable * onDestroyObservable () const
Observable to be notified of destruction.
const void * reference () const
void _setMesh (IMesh *mesh)
void _destroyMesh ()
IMesh * _internalMeshOrNull () const
Private Member Functions
MeshHandle (ISubDomain *sd, const String &name)
Private Attributes
Arccore::ReferenceCounter< MeshHandleRef > m_ref
Friends
class MeshMng
Detailed Description
Handle on a mesh.
This class uses reference counting semantics.
This class allows managing a reference to a mesh (IMesh) before it is explicitly created. This allows services and modules to specify which mesh they refer to during their construction.
It also allows associating user data with the mesh via meshUserDataList().
Definition at line 47 of file MeshHandle.h.
Constructor & Destructor Documentation
MeshHandle() [1/2]
Arcane::MeshHandle::MeshHandle ()
Definition at line 105 of file MeshHandle.cc.
MeshHandle() [2/2]
Arcane::MeshHandle::MeshHandle (ISubDomain * sd, const String & name) private
Definition at line 96 of file MeshHandle.cc.
Member Function Documentation
_destroyMesh()
void Arcane::MeshHandle::_destroyMesh () inline
Definition at line 177 of file MeshHandle.h.
_internalMeshOrNull()
IMesh * Arcane::MeshHandle::_internalMeshOrNull () const inline
Definition at line 180 of file MeshHandle.h.
_setMesh()
void Arcane::MeshHandle::_setMesh (IMesh * mesh) inline
Definition at line 174 of file MeshHandle.h.
References mesh().
application()
IApplication * Arcane::MeshHandle::application () const
Associated application. nullptr if isNull() is true.
Definition at line 177 of file MeshHandle.cc.
hasMesh()
bool Arcane::MeshHandle::hasMesh () const
Indicates if the associated mesh has already been created (i.e.: mesh() is valid).
Definition at line 123 of file MeshHandle.cc.
Referenced by Arcane::VerifierService::_getVariables(), and Arcane::MeshMng::destroyMesh().
isNull()
bool Arcane::MeshHandle::isNull () const inline
Indicates if the handle is null (it does not reference any existing mesh or not).
Definition at line 163 of file MeshHandle.h.
Referenced by Arcane::TimeHistoryMngInternal::_addHistoryValue(), Arcane::TimeHistoryMngInternal::_dumpSummaryOfCurves(), Arcane::TimeHistoryMngInternal::_dumpSummaryOfCurvesLegacy(), Arcane::TimeHistoryMngInternal::dumpCurves(), Arcane::Materials::MeshMaterialVariableCommonStaticImpl< TrueType >::getReference(), Arcane::Materials::IMeshMaterialMng::getTrueReference(), Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType >::getVariableReference(), Arcane::TimeHistoryMngInternal::iterationsAndValues(), and Arcane::TimeHistoryMngInternal::updateMetaData().
mesh()
IMesh * Arcane::MeshHandle::mesh () const
Associated mesh.
It is forbidden to call this method if the mesh has not yet been created. Eventually, an exception will be raised in this case.
If we are not sure that the mesh exists, we can test its existence via hasMesh().
Precondition
hasMesh() == true
Definition at line 133 of file MeshHandle.cc.
References ARCANE_FATAL.
Referenced by Arcane::Hdf5VariableReaderHelper2::_createCorrespondance(), Arcane::VerifierService::_getVariables(), Arcane::mesh::DynamicMesh::_readFromDump(), _setMesh(), Arcane::MeshMng::destroyMesh(), and Arcane::mesh::ItemFamily::readFromDump().
meshMng()
IMeshMng * Arcane::MeshHandle::meshMng () const
Associated mesh manager. nullptr if isNull() is true.
Definition at line 114 of file MeshHandle.cc.
Referenced by Arcane::CaseOptions::_setMeshHandleAndCheckDisabled().
meshName()
const String & Arcane::MeshHandle::meshName () const inline
Definition at line 160 of file MeshHandle.h.
meshOrNull()
IMesh * Arcane::MeshHandle::meshOrNull () const
Returns the mesh associated with this instance.
Unlike mesh(), this can be called even if the associated mesh has not yet been created. In this case, a null pointer is returned.
Definition at line 150 of file MeshHandle.cc.
Referenced by Arcane::ICartesianMesh::getReference(), and Arcane::MeshUtils::markMeshConnectivitiesAsMostlyReadOnly().
meshUserDataList()
IUserDataList * Arcane::MeshHandle::meshUserDataList () const inline
Associated user data.
Definition at line 158 of file MeshHandle.h.
Referenced by Arcane::ICartesianMesh::getReference().
onDestroyObservable()
IObservable * Arcane::MeshHandle::onDestroyObservable () const
Observable to be notified of destruction.
Definition at line 186 of file MeshHandle.cc.
reference()
const void * Arcane::MeshHandle::reference () const inline
Definition at line 169 of file MeshHandle.h.
subDomain()
ISubDomain * Arcane::MeshHandle::subDomain () const inline
Associated sub-domain. Null if isNull() is true.
Definition at line 141 of file MeshHandle.h.
References subDomain().
Referenced by subDomain().
traceMng()
ITraceMng * Arcane::MeshHandle::traceMng () const
Associated trace manager. nullptr if isNull() is true.
Definition at line 159 of file MeshHandle.cc.
variableMng()
IVariableMng * Arcane::MeshHandle::variableMng () const
Associated variable manager. nullptr if isNull() is true.
Definition at line 168 of file MeshHandle.cc.
Friends And Related Symbol Documentation
MeshMng
friend class MeshMng friend
Definition at line 52 of file MeshHandle.h.
Member Data Documentation
m_ref
Arccore::ReferenceCounter<MeshHandleRef> Arcane::MeshHandle::m_ref private
Definition at line 184 of file MeshHandle.h.
The documentation for this class was generated from the following files:
MeshHandle.h
MeshHandle.cc