Alien: Alien::BasicIndexManager::MyEntryImpl Class Reference
Alien::BasicIndexManager::MyEntryImpl Class Reference
Squelette de l'implementation locale de Entry La vraie implémentation est MyAbstractEntryImpl. Cette classe permet de la factorisation de code.
Public Member Functions
MyEntryImpl (const String &name, const IAbstractFamily *family, const Integer creationIndex, BasicIndexManager *manager, Integer kind)
Constructeur par défaut.
Arccore::ConstArrayView< Arccore::Integer > getOwnIndexes () const override
Retourne la liste des Index de l'Entry.
Arccore::ConstArrayView< Arccore::Integer > getOwnLocalIds () const override
Retourne la liste des Items de l'Entry.
Arccore::ConstArrayView< Arccore::Integer > getAllIndexes () const override
Retourne la liste des Index de l'Entry (own + ghost).
Arccore::ConstArrayView< Integer > getAllLocalIds () const override
Retourne la liste des Items de l'Entry (own + ghost).
void addTag (const String &tagname, const String &tagvalue) override
void removeTag (const String &tagname) override
bool hasTag (const String &tagname) override
String tagValue (const String &tagname) override
String getName () const override
Retourne le nom de l'entrée.
Integer getKind () const override
Retourne le type de support de l'Entry.
const IAbstractFamily & getFamily () const override
Retourne la famille abstraite de l'Entry.
IIndexManager * manager () const override
Référentiel du manager associé
Integer getCreationIndex () const
Public Member Functions inherited from Alien::IIndexManager::EntryImpl
virtual ~EntryImpl ()=default
Destructeur.
virtual void addTag (const Arccore::String &tagname, const Arccore::String &tagvalue)=0
Ajout d'un tag.
virtual void removeTag (const Arccore::String &tagname)=0
Suppression d'un tag.
virtual bool hasTag (const Arccore::String &tagname)=0
Test d'existance d'un tag.
virtual Arccore::String tagValue (const Arccore::String &tagname)=0
Lecture d'un tag.
Protected Member Functions
void reserve (const Integer n)
Préparation des buffers d'indices et d'items.
void finalize (const EntryIndexMap &entryIndex)
Fige les données de l'entry (fin de phase prepare).
void resetFamily (const IAbstractFamily *family)
void reserveLid (const Integer count)
bool isDefinedLid (const Integer localId) const
void defineLid (const Integer localId, const Integer pos)
void undefineLid (const Integer localId)
const UniqueArray< std::pair< Integer, Integer > > & definedLids () const
void freeDefinedLids ()
Private Attributes
std::map< String, String > m_tags
Integer m_creation_index
BasicIndexManager * m_manager
const String m_name
const IAbstractFamily * m_family
const Integer m_kind
std::vector< bool > m_is_defined
UniqueArray< std::pair< Integer, Integer > > m_defined_lids
UniqueArray< Integer > m_all_items
LocalIds des items gérés par cette entrée rangés own puis ghost.
UniqueArray< Integer > m_all_indices
Integer m_own_size
Nombre d'items own dans les tableaux m_all_*.
Integer m_size
Friends
class BasicIndexManager
Detailed Description
Squelette de l'implementation locale de Entry La vraie implémentation est MyAbstractEntryImpl. Cette classe permet de la factorisation de code.
Definition at line 56 of file BasicIndexManager.cc.
Constructor & Destructor Documentation
MyEntryImpl()
Alien::BasicIndexManager::MyEntryImpl::MyEntryImpl (const String & name, const IAbstractFamily * family, const Integer creationIndex, BasicIndexManager * manager, Integer kind) inline
Constructeur par défaut.
Definition at line 62 of file BasicIndexManager.cc.
References m_own_size, and manager().
Member Function Documentation
addTag()
void Alien::BasicIndexManager::MyEntryImpl::addTag (const String & tagname, const String & tagvalue) inline override
Definition at line 96 of file BasicIndexManager.cc.
definedLids()
const UniqueArray< std::pair< Integer, Integer > > & Alien::BasicIndexManager::MyEntryImpl::definedLids () const inline protected
Definition at line 225 of file BasicIndexManager.cc.
defineLid()
void Alien::BasicIndexManager::MyEntryImpl::defineLid (const Integer localId, const Integer pos) inline protected
Definition at line 185 of file BasicIndexManager.cc.
finalize()
void Alien::BasicIndexManager::MyEntryImpl::finalize (const EntryIndexMap & entryIndex) inline protected
Fige les données de l'entry (fin de phase prepare).
Utilisation réservée au 'friend' BasicIndexManager
Definition at line 138 of file BasicIndexManager.cc.
References m_all_indices, m_all_items, and m_own_size.
freeDefinedLids()
void Alien::BasicIndexManager::MyEntryImpl::freeDefinedLids () inline protected
Definition at line 231 of file BasicIndexManager.cc.
getAllIndexes()
Arccore::ConstArrayView< Arccore::Integer > Alien::BasicIndexManager::MyEntryImpl::getAllIndexes () const inline override virtual
Retourne la liste des Index de l'Entry (own + ghost).
Implements Alien::IIndexManager::EntryImpl.
Definition at line 86 of file BasicIndexManager.cc.
References m_all_indices.
Referenced by Alien::BasicIndexManager::getIndexes().
getAllLocalIds()
Arccore::ConstArrayView< Integer > Alien::BasicIndexManager::MyEntryImpl::getAllLocalIds () const inline override virtual
Retourne la liste des Items de l'Entry (own + ghost).
Implements Alien::IIndexManager::EntryImpl.
Definition at line 91 of file BasicIndexManager.cc.
References m_all_items.
getCreationIndex()
Integer Alien::BasicIndexManager::MyEntryImpl::getCreationIndex () const inline
Definition at line 268 of file BasicIndexManager.cc.
getFamily()
const IAbstractFamily & Alien::BasicIndexManager::MyEntryImpl::getFamily () const inline override virtual
Retourne la famille abstraite de l'Entry.
Implements Alien::IIndexManager::EntryImpl.
Definition at line 127 of file BasicIndexManager.cc.
Referenced by Alien::BasicIndexManager::keepAlive(), and Alien::BasicIndexManager::prepare().
getKind()
Integer Alien::BasicIndexManager::MyEntryImpl::getKind () const inline override virtual
Retourne le type de support de l'Entry.
Implements Alien::IIndexManager::EntryImpl.
Definition at line 118 of file BasicIndexManager.cc.
Referenced by Alien::BasicIndexManager::prepare().
getName()
String Alien::BasicIndexManager::MyEntryImpl::getName () const inline override virtual
Retourne le nom de l'entrée.
Implements Alien::IIndexManager::EntryImpl.
Definition at line 116 of file BasicIndexManager.cc.
getOwnIndexes()
Arccore::ConstArrayView< Arccore::Integer > Alien::BasicIndexManager::MyEntryImpl::getOwnIndexes () const inline override virtual
Retourne la liste des Index de l'Entry.
Implements Alien::IIndexManager::EntryImpl.
Definition at line 76 of file BasicIndexManager.cc.
References m_all_indices, and m_own_size.
getOwnLocalIds()
Arccore::ConstArrayView< Arccore::Integer > Alien::BasicIndexManager::MyEntryImpl::getOwnLocalIds () const inline override virtual
Retourne la liste des Items de l'Entry.
Implements Alien::IIndexManager::EntryImpl.
Definition at line 81 of file BasicIndexManager.cc.
References m_all_items, and m_own_size.
hasTag()
bool Alien::BasicIndexManager::MyEntryImpl::hasTag (const String & tagname) inline override
Definition at line 103 of file BasicIndexManager.cc.
isDefinedLid()
bool Alien::BasicIndexManager::MyEntryImpl::isDefinedLid (const Integer localId) const inline protected
Definition at line 183 of file BasicIndexManager.cc.
manager()
IIndexManager * Alien::BasicIndexManager::MyEntryImpl::manager () const inline override virtual
Référentiel du manager associé
Implements Alien::IIndexManager::EntryImpl.
Definition at line 129 of file BasicIndexManager.cc.
References Alien::IIndexManager::IIndexManager().
Referenced by MyEntryImpl().
removeTag()
void Alien::BasicIndexManager::MyEntryImpl::removeTag (const String & tagname) inline override
Definition at line 101 of file BasicIndexManager.cc.
reserve()
void Alien::BasicIndexManager::MyEntryImpl::reserve (const Integer n) inline protected
Préparation des buffers d'indices et d'items.
Utilisation réservée au 'friend' BasicIndexManager
Definition at line 134 of file BasicIndexManager.cc.
reserveLid()
void Alien::BasicIndexManager::MyEntryImpl::reserveLid (const Integer count) inline protected
Definition at line 176 of file BasicIndexManager.cc.
resetFamily()
void Alien::BasicIndexManager::MyEntryImpl::resetFamily (const IAbstractFamily * family) inline protected
Definition at line 173 of file BasicIndexManager.cc.
tagValue()
String Alien::BasicIndexManager::MyEntryImpl::tagValue (const String & tagname) inline override
Definition at line 108 of file BasicIndexManager.cc.
undefineLid()
void Alien::BasicIndexManager::MyEntryImpl::undefineLid (const Integer localId) inline protected
Definition at line 196 of file BasicIndexManager.cc.
Friends And Related Symbol Documentation
BasicIndexManager
friend class BasicIndexManager friend
Definition at line 58 of file BasicIndexManager.cc.
Member Data Documentation
m_all_indices
UniqueArray<Integer> Alien::BasicIndexManager::MyEntryImpl::m_all_indices private
Indices 'own' dans la numérotation globale de
Definition at line 261 of file BasicIndexManager.cc.
Referenced by finalize(), getAllIndexes(), and getOwnIndexes().
m_all_items
UniqueArray<Integer> Alien::BasicIndexManager::MyEntryImpl::m_all_items private
LocalIds des items gérés par cette entrée rangés own puis ghost.
Definition at line 260 of file BasicIndexManager.cc.
Referenced by finalize(), getAllLocalIds(), and getOwnLocalIds().
m_creation_index
Integer Alien::BasicIndexManager::MyEntryImpl::m_creation_index private
Definition at line 244 of file BasicIndexManager.cc.
m_defined_lids
UniqueArray<std::pair<Integer, Integer> > Alien::BasicIndexManager::MyEntryImpl::m_defined_lids private
Definition at line 255 of file BasicIndexManager.cc.
m_family
const IAbstractFamily* Alien::BasicIndexManager::MyEntryImpl::m_family private
Definition at line 247 of file BasicIndexManager.cc.
m_is_defined
std::vector<bool> Alien::BasicIndexManager::MyEntryImpl::m_is_defined private
Definition at line 250 of file BasicIndexManager.cc.
m_kind
const Integer Alien::BasicIndexManager::MyEntryImpl::m_kind private
Definition at line 248 of file BasicIndexManager.cc.
m_manager
BasicIndexManager* Alien::BasicIndexManager::MyEntryImpl::m_manager private
Definition at line 245 of file BasicIndexManager.cc.
m_name
const String Alien::BasicIndexManager::MyEntryImpl::m_name private
Definition at line 246 of file BasicIndexManager.cc.
m_own_size
Integer Alien::BasicIndexManager::MyEntryImpl::m_own_size private
Nombre d'items own dans les tableaux m_all_*.
l'index-manager par cette entrée rangés own puis ghost
Definition at line 264 of file BasicIndexManager.cc.
Referenced by finalize(), getOwnIndexes(), getOwnLocalIds(), and MyEntryImpl().
m_size
Integer Alien::BasicIndexManager::MyEntryImpl::m_size private
Definition at line 265 of file BasicIndexManager.cc.
m_tags
std::map<String, String> Alien::BasicIndexManager::MyEntryImpl::m_tags private
Definition at line 243 of file BasicIndexManager.cc.
The documentation for this class was generated from the following file:
BasicIndexManager.cc