Arcane: Arcane::ICaseFunction Class Reference
Arcane::ICaseFunction Class Reference abstract
Public Types
enum eParamType { ParamUnknown = 0 , ParamReal = 1 , ParamInteger = 2 }
Type of a function parameter.
enum eValueType {
ValueUnknown = 0 , ValueReal = 1 , ValueInteger = 2 , ValueBool = 3 ,
ValueString = 4 , ValueReal3 = 5
}
Type of a function value.
Public Member Functions
virtual ~ICaseFunction ()=default
Releases resources.
Function Name
virtual String name () const =0
function name
virtual void setName (const String &new_name)=0
Sets the function name to new_name.
Parameter Type
virtual eParamType paramType () const =0
Function parameter type.
virtual void setParamType (eParamType type)=0
Sets the function parameter type.
Value Type
virtual eValueType valueType () const =0
Function value type.
virtual void setValueType (eValueType type)=0
Sets the function value type.
virtual void setTransformValueFunction (const String &str)=0
Sets a value transformation function. For now, this is just a multiplicative coefficient. The string str must be convertible to the value type.
virtual String transformValueFunction () const =0
Returns the value transformation function.
virtual void setTransformParamFunction (const String &str)=0
Sets a parameter transformation function. For now, this is just a multiplicative coefficient. It is only applied to real parameters. The string str must be convertible to a real number.
virtual String transformParamFunction () const =0
Parameter transformation function.
virtual bool checkIfValid () const =0
Checks the validity of the function.
virtual void setDeltatCoef (Real v)=0
Sets the value of the deltat multiplier coefficient.
virtual Real deltatCoef () const =0
Value of the deltat multiplier coefficient.
virtual void value (Real param, Real &v) const =0
Value v of the option for parameter param.
virtual void value (Real param, Integer &v) const =0
Value v of the option for parameter param.
virtual void value (Real param, bool &v) const =0
Value v of the option for parameter param.
virtual void value (Real param, String &v) const =0
Value v of the option for parameter param.
virtual void value (Real param, Real3 &v) const =0
Value v of the option for parameter param.
virtual void value (Integer param, Real &v) const =0
Value v of the option for parameter param.
virtual void value (Integer param, Integer &v) const =0
Value v of the option for parameter param.
virtual void value (Integer param, bool &v) const =0
virtual void value (Integer param, String &v) const =0
Value v of the option for parameter param.
virtual void value (Integer param, Real3 &v) const =0
Value v of the option for parameter param.
Detailed Description
Definition at line 45 of file ICaseFunction.h.
Member Enumeration Documentation
eParamType
enum Arcane::ICaseFunction::eParamType
Type of a function parameter.
Enumerator
ParamUnknown
Unknown parameter type.
ParamReal
Real type parameter.
ParamInteger
Integer type parameter.
Definition at line 54 of file ICaseFunction.h.
eValueType
enum Arcane::ICaseFunction::eValueType
Type of a function value.
Enumerator
ValueUnknown
Unknown value type.
ValueReal
Real type value.
ValueInteger
Integer type value.
ValueBool
Boolean type value.
ValueString
String type value.
ValueReal3
'Real3' type value
Definition at line 63 of file ICaseFunction.h.
Member Function Documentation
checkIfValid()
virtual bool Arcane::ICaseFunction::checkIfValid () const pure virtual
Checks the validity of the function.
Return values
true if the function is valid,
false otherwise.
Implemented in Arcane::CaseFunction, and Arcane::CaseTable.
deltatCoef()
virtual Real Arcane::ICaseFunction::deltatCoef () const pure virtual
Value of the deltat multiplier coefficient.
Implemented in Arcane::CaseFunction.
name()
virtual String Arcane::ICaseFunction::name () const pure virtual
function name
Implemented in Arcane::CaseFunction.
Referenced by Arcane::CaseOptions::read().
paramType()
virtual eParamType Arcane::ICaseFunction::paramType () const pure virtual
Function parameter type.
Implemented in Arcane::CaseFunction.
Referenced by Arcane::CaseOptions::read(), and Arcane::CaseOptionSimpleT< T >::updateFromFunction().
setDeltatCoef()
virtual void Arcane::ICaseFunction::setDeltatCoef (Real v) pure virtual
Sets the value of the deltat multiplier coefficient.
This coefficient, 0.0 by default, is used for functions that take physical time as a parameter. In this case, the function uses the global current time as a parameter, to which the global current time step multiplied by this coefficient is added.
Implemented in Arcane::CaseFunction.
setName()
virtual void Arcane::ICaseFunction::setName (const String & new_name) pure virtual
Sets the function name to new_name.
Implemented in Arcane::CaseFunction.
setParamType()
virtual void Arcane::ICaseFunction::setParamType (eParamType type) pure virtual
Sets the function parameter type.
Implemented in Arcane::CaseFunction, and Arcane::CaseTable.
setTransformParamFunction()
virtual void Arcane::ICaseFunction::setTransformParamFunction (const String & str) pure virtual
Sets a parameter transformation function. For now, this is just a multiplicative coefficient. It is only applied to real parameters. The string str must be convertible to a real number.
Implemented in Arcane::CaseFunction.
setTransformValueFunction()
virtual void Arcane::ICaseFunction::setTransformValueFunction (const String & str) pure virtual
Sets a value transformation function. For now, this is just a multiplicative coefficient. The string str must be convertible to the value type.
Implemented in Arcane::CaseFunction.
setValueType()
virtual void Arcane::ICaseFunction::setValueType (eValueType type) pure virtual
Sets the function value type.
Implemented in Arcane::CaseFunction.
transformParamFunction()
virtual String Arcane::ICaseFunction::transformParamFunction () const pure virtual
Parameter transformation function.
Implemented in Arcane::CaseFunction.
transformValueFunction()
virtual String Arcane::ICaseFunction::transformValueFunction () const pure virtual
Returns the value transformation function.
Implemented in Arcane::CaseFunction.
value() [1/9]
virtual void Arcane::ICaseFunction::value (Integer param, Integer & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
References value().
value() [2/9]
virtual void Arcane::ICaseFunction::value (Integer param, Real & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
value() [3/9]
virtual void Arcane::ICaseFunction::value (Integer param, Real3 & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
value() [4/9]
virtual void Arcane::ICaseFunction::value (Integer param, String & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
value() [5/9]
virtual void Arcane::ICaseFunction::value (Real param, bool & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
value() [6/9]
virtual void Arcane::ICaseFunction::value (Real param, Integer & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
value() [7/9]
virtual void Arcane::ICaseFunction::value (Real param, Real & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
Referenced by value().
value() [8/9]
virtual void Arcane::ICaseFunction::value (Real param, Real3 & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
value() [9/9]
virtual void Arcane::ICaseFunction::value (Real param, String & v) const pure virtual
Value v of the option for parameter param.
Implemented in Arcane::CaseFunction2, and Arcane::CaseTable.
valueType()
virtual eValueType Arcane::ICaseFunction::valueType () const pure virtual
Function value type.
Implemented in Arcane::CaseFunction.
Referenced by Arcane::CaseOptions::read().
The documentation for this class was generated from the following file:
ICaseFunction.h