Arcane: Arcane::Internal::ServiceInfo Class Reference
Arcane::Internal::ServiceInfo Class Reference
Public Member Functions
ServiceInfo (const String &local_name, const VersionInfo &version, Integer valid_dimension)
Constructor.
~ServiceInfo () override
Destructor.
IServiceFactoryInfo * factoryInfo () const override
Info on the factories available for this service.
void setFactoryInfo (IServiceFactoryInfo *sfi)
void setAxlContent (const FileContent &file_content)
int usageType () const override
Indicates where the service can be used.
Methods inherited from IServiceInfo
String localName () const override
Local part of the service name.
String namespaceURI () const override
Service name namespace.
VersionInfo version () const override
Service version.
Real axlVersion () const override
Version of the axl file describing this service.
bool allowDimension (Integer n) const override
Indicates if the service is usable in dimension n.
void addImplementedInterface (const String &name) override
Adds the name interface name to the interfaces implemented by this service.
StringCollection implementedInterfaces () const override
List of names of classes implemented by this service.
const String & caseOptionsFileName () const override
Name of the file containing the dataset (null if none).
ServiceFactory2Collection factories () const override
List of service factories.
ISingletonServiceFactory * singletonFactory () const override
Factory for singleton services (nullptr if not supported).
String tagName (const String &lang) const override
Name of the service XML element for the language lang. If lang is null, returns the default name.
const FileContent & axlContent () const override
Content of the AXL file associated with this service or module.
Specific construction methods
virtual void setAxlVersion (Real v) const
virtual void setCaseOptionsFileName (const String &fn)
virtual void addFactory (IServiceFactory2 *factory)
virtual void setDefaultTagName (const String &value)
virtual void setTagName (const String &value, const String &lang)
virtual void setSingletonFactory (Internal::ISingletonServiceFactory *f)
Public Member Functions inherited from Arcane::IServiceInfo
virtual ~IServiceInfo ()=default
Frees resources.
Static Public Member Functions
static ServiceInfo * create (const ServiceProperty &sp, const char *filename, int lineno)
static ServiceInfo * create (const String &name, int service_type)
Additional Inherited Members
Static Public Attributes inherited from Arcane::IServiceInfo
static const Integer Dim1 = 1
static const Integer Dim2 = 2
static const Integer Dim3 = 4
Detailed Description
Definition at line 49 of file ServiceInfo.h.
Constructor & Destructor Documentation
ServiceInfo()
Arcane::Internal::ServiceInfo::ServiceInfo (const String & local_name, const VersionInfo & version, Integer valid_dimension)
Constructor.
Definition at line 111 of file ServiceInfo.cc.
References version().
~ServiceInfo()
Arcane::Internal::ServiceInfo::~ServiceInfo () override
Destructor.
Definition at line 121 of file ServiceInfo.cc.
Member Function Documentation
addFactory()
void Arcane::Internal::ServiceInfo::addFactory (IServiceFactory2 * factory) virtual
Definition at line 210 of file ServiceInfo.cc.
addImplementedInterface()
void Arcane::Internal::ServiceInfo::addImplementedInterface (const String & name) override virtual
Adds the name interface name to the interfaces implemented by this service.
Implements Arcane::IServiceInfo.
Definition at line 172 of file ServiceInfo.cc.
Referenced by Arcane::Internal::ServiceInterfaceRegisterer< InterfaceType >::registerToServiceInfo().
allowDimension()
bool Arcane::Internal::ServiceInfo::allowDimension (Integer n) const override virtual
Indicates if the service is usable in dimension n.
Implements Arcane::IServiceInfo.
Definition at line 157 of file ServiceInfo.cc.
axlContent()
const FileContent & Arcane::Internal::ServiceInfo::axlContent () const override virtual
Content of the AXL file associated with this service or module.
Implements Arcane::IServiceInfo.
Definition at line 316 of file ServiceInfo.cc.
axlVersion()
Real Arcane::Internal::ServiceInfo::axlVersion () const override virtual
Version of the axl file describing this service.
Implements Arcane::IServiceInfo.
Definition at line 277 of file ServiceInfo.cc.
caseOptionsFileName()
const String & Arcane::Internal::ServiceInfo::caseOptionsFileName () const override virtual
Name of the file containing the dataset (null if none).
Implements Arcane::IServiceInfo.
Definition at line 192 of file ServiceInfo.cc.
create() [1/2]
ServiceInfo * Arcane::Internal::ServiceInfo::create (const ServiceProperty & sp, const char * filename, int lineno) static
Definition at line 334 of file ServiceInfo.cc.
create() [2/2]
ServiceInfo * Arcane::Internal::ServiceInfo::create (const String & name, int service_type) static
Definition at line 354 of file ServiceInfo.cc.
factories()
ServiceFactory2Collection Arcane::Internal::ServiceInfo::factories () const override virtual
List of service factories.
Implements Arcane::IServiceInfo.
Definition at line 219 of file ServiceInfo.cc.
factoryInfo()
IServiceFactoryInfo * Arcane::Internal::ServiceInfo::factoryInfo () const override virtual
Info on the factories available for this service.
Implements Arcane::IServiceInfo.
Definition at line 295 of file ServiceInfo.cc.
implementedInterfaces()
StringCollection Arcane::Internal::ServiceInfo::implementedInterfaces () const override virtual
List of names of classes implemented by this service.
Implements Arcane::IServiceInfo.
Definition at line 183 of file ServiceInfo.cc.
localName()
String Arcane::Internal::ServiceInfo::localName () const override virtual
Local part of the service name.
Implements Arcane::IServiceInfo.
Definition at line 139 of file ServiceInfo.cc.
namespaceURI()
String Arcane::Internal::ServiceInfo::namespaceURI () const override virtual
Service name namespace.
Implements Arcane::IServiceInfo.
Definition at line 130 of file ServiceInfo.cc.
setAxlContent()
void Arcane::Internal::ServiceInfo::setAxlContent (const FileContent & file_content)
Definition at line 310 of file ServiceInfo.cc.
setAxlVersion()
void Arcane::Internal::ServiceInfo::setAxlVersion (Real v) const virtual
Definition at line 286 of file ServiceInfo.cc.
setCaseOptionsFileName()
void Arcane::Internal::ServiceInfo::setCaseOptionsFileName (const String & fn) virtual
Definition at line 201 of file ServiceInfo.cc.
setDefaultTagName()
void Arcane::Internal::ServiceInfo::setDefaultTagName (const String & value) virtual
Definition at line 259 of file ServiceInfo.cc.
setFactoryInfo()
void Arcane::Internal::ServiceInfo::setFactoryInfo (IServiceFactoryInfo * sfi)
Definition at line 304 of file ServiceInfo.cc.
setSingletonFactory()
void Arcane::Internal::ServiceInfo::setSingletonFactory (Internal::ISingletonServiceFactory * f) virtual
Definition at line 237 of file ServiceInfo.cc.
setTagName()
void Arcane::Internal::ServiceInfo::setTagName (const String & value, const String & lang) virtual
Definition at line 268 of file ServiceInfo.cc.
singletonFactory()
ISingletonServiceFactory * Arcane::Internal::ServiceInfo::singletonFactory () const override virtual
Factory for singleton services (nullptr if not supported).
Implements Arcane::IServiceInfo.
Definition at line 228 of file ServiceInfo.cc.
tagName()
String Arcane::Internal::ServiceInfo::tagName (const String & lang) const override virtual
Name of the service XML element for the language lang. If lang is null, returns the default name.
Implements Arcane::IServiceInfo.
Definition at line 247 of file ServiceInfo.cc.
References Arcane::String::null().
usageType()
int Arcane::Internal::ServiceInfo::usageType () const override virtual
Indicates where the service can be used.
It is a combination of eServiceType values.
Implements Arcane::IServiceInfo.
Definition at line 325 of file ServiceInfo.cc.
version()
VersionInfo Arcane::Internal::ServiceInfo::version () const override virtual
Service version.
Implements Arcane::IServiceInfo.
Definition at line 148 of file ServiceInfo.cc.
Referenced by ServiceInfo().
The documentation for this class was generated from the following files:
ServiceInfo.h
ServiceInfo.cc