Arcane: Arcane::IMeshFactoryMng Class Reference
Arcane::IMeshFactoryMng Class Reference abstract
Interface of the mesh factory manager.
#include <arcane/core/IMeshFactoryMng.h>
Public Member Functions
virtual ~IMeshFactoryMng ()=default
Frees the resources.
virtual IMeshMng * meshMng () const =0
Associated mesh manager.
virtual IPrimaryMesh * createMesh (const MeshBuildInfo &build_info)=0
Creates a mesh or a sub-mesh.
Detailed Description
Interface of the mesh factory manager.
Definition at line 31 of file IMeshFactoryMng.h.
Member Function Documentation
createMesh()
virtual IPrimaryMesh * Arcane::IMeshFactoryMng::createMesh (const MeshBuildInfo & build_info) pure virtual
Creates a mesh or a sub-mesh.
The created mesh is automatically added to the associated meshMng().
Implemented in Arcane::MeshFactoryMng.
Referenced by Arcane::ArcaneCaseMeshService::createMesh(), Arcane::MainFactory::createMesh(), and Arcane::MainFactory::createSubMesh().
meshMng()
virtual IMeshMng * Arcane::IMeshFactoryMng::meshMng () const pure virtual
Associated mesh manager.
Implemented in Arcane::MeshFactoryMng.
The documentation for this class was generated from the following file:
IMeshFactoryMng.h