Arcane: Arcane::CodeService Class Reference
Arcane::CodeService Class Reference
Abstract class for a code service.
#include <arcane/core/CodeService.h>
Public Member Functions
CodeService (const ServiceBuildInfo &sbi)
bool parseArgs (StringList &) override
Parses the command line arguments.
ISubDomain * createAndLoadCase (ISession *session, const SubDomainBuildInfo &sdbi) override
Creates and loads the case using the info sdbi for the session session.
void initCase (ISubDomain *sub_domain, bool is_continue) override
Initializes the session session.
bool allowExecution () const override
Returns whether the code allows execution.
StringCollection validExtensions () const override
Returns the list of file extensions processed by the instance. The extension does not include the '.'.
Real lengthUnit () const override
Length unit used by the code.
IServiceInfo * serviceInfo () const override
Service information.
IBase * serviceParent () const override
Parent of this service.
IService * serviceInterface () override
Interface of this service (normally this).
Public Member Functions inherited from Arcane::ICodeService
~ICodeService ()=default
Frees resources.
virtual ISession * createSession ()=0
Creates a session.
Public Member Functions inherited from Arcane::IService
virtual ~IService ()
Releases resources.
Protected Member Functions
void _addExtension (const String &extension)
IApplication * _application () const
virtual void _preInitializeSubDomain (ISubDomain *)
Protected Member Functions inherited from Arcane::IService
IService ()
Constructor.
Private Attributes
CodeServicePrivate * m_p = nullptr
Detailed Description
Abstract class for a code service.
The derived class must implement ICodeService::createSession()
Definition at line 44 of file CodeService.h.
Constructor & Destructor Documentation
CodeService()
Arcane::CodeService::CodeService (const ServiceBuildInfo & sbi) explicit
Definition at line 78 of file CodeService.cc.
~CodeService()
Arcane::CodeService::~CodeService () override
Definition at line 87 of file CodeService.cc.
Member Function Documentation
_addExtension()
void Arcane::CodeService::_addExtension (const String & extension) protected
Definition at line 225 of file CodeService.cc.
_application()
IApplication * Arcane::CodeService::_application () const protected
Definition at line 234 of file CodeService.cc.
_preInitializeSubDomain()
virtual void Arcane::CodeService::_preInitializeSubDomain (ISubDomain *) inline protected virtual
Definition at line 73 of file CodeService.h.
allowExecution()
bool Arcane::CodeService::allowExecution () const override virtual
Returns whether the code allows execution.
Implements Arcane::ICodeService.
Definition at line 96 of file CodeService.cc.
createAndLoadCase()
ISubDomain * Arcane::CodeService::createAndLoadCase (ISession * session, const SubDomainBuildInfo & sdbi) override virtual
Creates and loads the case using the info sdbi for the session session.
Implements Arcane::ICodeService.
Definition at line 114 of file CodeService.cc.
References Arcane::ISession::createSubDomain(), Arcane::ITraceMng::error(), Arcane::ISubDomain::readCaseMeshes(), and Arcane::IBase::traceMng().
initCase()
void Arcane::CodeService::initCase (ISubDomain * sub_domain, bool is_continue) override virtual
Initializes the session session.
Parameters
is_continue indicates if we are resuming The case must already have been loaded by loadCase()
Implements Arcane::ICodeService.
Definition at line 142 of file CodeService.cc.
References Arcane::IVariableMng::_internalApi(), Arcane::ISubDomain::allocateMeshes(), Arcane::ISubDomain::caseMng(), Arcane::ISubDomain::checkpointMng(), Arcane::ISubDomain::doInitMeshPartition(), Arcane::IProfilingService::dumpJSON(), Arcane::ITimeLoopMng::execBuildEntryPoints(), Arcane::ITimeLoopMng::execInitEntryPoints(), Arcane::platform::getProcessId(), Arcane::platform::getProfilingService(), Arcane::ISubDomain::initializeMeshVariablesFromCaseFile(), Arcane::IVariableMngInternal::initializeVariables(), Arcane::String::localstr(), Arcane::ICaseMng::printOptions(), Arcane::ICheckpointMng::readCheckpoint(), Arcane::ICheckpointMng::readDefaultCheckpointInfo(), Arcane::ICaseMng::readOptions(), Arcane::ISubDomain::readOrReloadMeshes(), Arcane::ISubDomain::setIsContinue(), Arcane::ISubDomain::setIsInitialized(), Arcane::ProfilingSentryWithInitialize::setPrintAtEnd(), Arcane::ISubDomain::timeLoopMng(), and Arcane::ISubDomain::variableMng().
Referenced by Arcane::ArcaneCodeService::initCase().
lengthUnit()
Real Arcane::CodeService::lengthUnit () const inline override virtual
Length unit used by the code.
This must be 1.0 if the code uses the international system and thus the meter as the length unit. If the unit is the centimeter, for example, the value is 0.01.
This value can be used, for example, when reading the mesh if the mesh format supports the notion of length unit.
Implements Arcane::ICodeService.
Definition at line 60 of file CodeService.h.
parseArgs()
bool Arcane::CodeService::parseArgs (StringList & args) inline override virtual
Parses the command line arguments.
The array args only contains arguments that have not been interpreted by Arcane.
Recognized arguments must be removed from the list.
Return values
true if the execution must stop,
false if it continues normally
Implements Arcane::ICodeService.
Definition at line 54 of file CodeService.h.
serviceInfo()
IServiceInfo * Arcane::CodeService::serviceInfo () const override virtual
Service information.
Implements Arcane::IService.
Definition at line 207 of file CodeService.cc.
serviceInterface()
IService * Arcane::CodeService::serviceInterface () inline override virtual
Interface of this service (normally this).
Implements Arcane::IService.
Definition at line 66 of file CodeService.h.
serviceParent()
IBase * Arcane::CodeService::serviceParent () const override virtual
Parent of this service.
Implements Arcane::IService.
Definition at line 216 of file CodeService.cc.
validExtensions()
StringCollection Arcane::CodeService::validExtensions () const override virtual
Returns the list of file extensions processed by the instance. The extension does not include the '.'.
Implements Arcane::ICodeService.
Definition at line 105 of file CodeService.cc.
Member Data Documentation
m_p
CodeServicePrivate* Arcane::CodeService::m_p = nullptr private
Definition at line 77 of file CodeService.h.
The documentation for this class was generated from the following files:
CodeService.h
CodeService.cc