Arcane: Arcane::geometric::GeomShape Class Reference
Arcane::geometric::GeomShape Class Reference
Geometric elements.
Geometric shape.
#include <arcane/geometry/GeomShape.h>
Public Member Functions
GeomShapeMutableView toMutableView ()
Modifiable view of this instance.
Hexaedron8ShapeView initFromHexaedron8 (Hexaedron8ElementConstView hexa)
Initializes the shape with a hexahedron hexa and returns a view of it.
Quad4ShapeView initFromQuad4 (Quad4ElementConstView quad)
Initializes the shape with a quadrangle quad and returns a view of it.
Protected Member Functions
void _setArray (GeomShapeView &shape)
Private Attributes
Real3POD m_node_ptr [ItemStaticInfo::MAX_CELL_NODE]
Real3POD m_face_ptr [ItemStaticInfo::MAX_CELL_FACE]
Real3POD m_center
Friends
class GeomShapeView
Detailed Description
Geometric shape.
This class is only used to create a temporary geometric shape. For a geometric shape derived from a cell, you must go through the GeomShapeMng.
An instance of this class allows storing the information necessary for a geometric shape.
It is possible to directly initialize a geometric shape from a hexahedron (initFromHexaedron8()) or a quadrangle (initFromQuad4()). These methods initialize the shape and return a view of it.
GeomShape shape;
HexaElement hexa;
GeomShapeView shape_view = shape.initFromHexaedron8(hexa);
Todo
set up a specific initialization. For this, it will be necessary to use toMutableView() but it is also necessary to be able to specify the geomType().
Definition at line 52 of file src/arcane/geometry/GeomShape.h.
Member Function Documentation
_setArray()
void Arcane::geometric::GeomShape::_setArray (GeomShapeView & shape) inline protected
Definition at line 74 of file src/arcane/geometry/GeomShape.h.
initFromHexaedron8()
Hexaedron8ShapeView Arcane::geometric::GeomShape::initFromHexaedron8 (Hexaedron8ElementConstView hexa)
Initializes the shape with a hexahedron hexa and returns a view of it.
Definition at line 519 of file GeomShapeView.cc.
References Arcane::geometric::GeomShapeStdBuilder::computeNodePositionFromHexa(), and toMutableView().
initFromQuad4()
Quad4ShapeView Arcane::geometric::GeomShape::initFromQuad4 (Quad4ElementConstView quad)
Initializes the shape with a quadrangle quad and returns a view of it.
Definition at line 538 of file GeomShapeView.cc.
References Arcane::geometric::GeomShapeStdBuilder::computeNodePositionFromQuad(), and toMutableView().
toMutableView()
GeomShapeMutableView Arcane::geometric::GeomShape::toMutableView () inline
Modifiable view of this instance.
Definition at line 61 of file src/arcane/geometry/GeomShape.h.
Referenced by Arcane::geometric::GeomShapeView::initFromHexa(), initFromHexaedron8(), Arcane::geometric::GeomShapeView::initFromQuad(), and initFromQuad4().
Friends And Related Symbol Documentation
GeomShapeView
friend class GeomShapeView friend
Definition at line 56 of file src/arcane/geometry/GeomShape.h.
Member Data Documentation
m_center
Real3POD Arcane::geometric::GeomShape::m_center private
Definition at line 83 of file src/arcane/geometry/GeomShape.h.
m_face_ptr
Real3POD Arcane::geometric::GeomShape::m_face_ptr[ItemStaticInfo::MAX_CELL_FACE] private
Definition at line 82 of file src/arcane/geometry/GeomShape.h.
m_node_ptr
Real3POD Arcane::geometric::GeomShape::m_node_ptr[ItemStaticInfo::MAX_CELL_NODE] private
Definition at line 81 of file src/arcane/geometry/GeomShape.h.
The documentation for this class was generated from the following files:
src/arcane/geometry/GeomShape.h
GeomShapeView.cc