Alien: Alien::Matrix Class Reference
Alien::Matrix Class Reference final
Public Member Functions
Matrix (const MatrixDistribution &dist)
Matrix (Integer nrows, Integer ncols, Integer nrows_local, IMessagePassingMng *parallel_mng)
Matrix (Integer nrows, Integer ncols, IMessagePassingMng *parallel_mng)
Matrix (Matrix &&m)
Matrix & operator= (Matrix &&m)
Matrix (const Matrix &)=delete
Matrix & operator= (const Matrix &)=delete
template<typename E>
Matrix & operator= (const E &)
void visit (ICopyOnWriteMatrix &) const
Visit method.
const MatrixDistribution & distribution () const
const ISpace & rowSpace () const
Get row space associated to the matrix.
const ISpace & colSpace () const
Get col space associated to the matrix.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
MultiMatrixImpl * impl ()
Get the multimatrix implementation.
const MultiMatrixImpl * impl () const
Get the multimatrix implementation.
Private Attributes
std::shared_ptr< MultiMatrixImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from Alien::IMatrix
IMatrix ()
Constructor.
Detailed Description
Definition at line 36 of file Matrix.h.
Constructor & Destructor Documentation
Matrix() [1/5]
Alien::Matrix::Matrix ()
Definition at line 33 of file Matrix.cc.
Matrix() [2/5]
Alien::Matrix::Matrix (const MatrixDistribution & dist)
Definition at line 40 of file Matrix.cc.
Matrix() [3/5]
Alien::Matrix::Matrix (Integer nrows, Integer ncols, Integer nrows_local, IMessagePassingMng * parallel_mng)
Definition at line 47 of file Matrix.cc.
Matrix() [4/5]
Alien::Matrix::Matrix (Integer nrows, Integer ncols, IMessagePassingMng * parallel_mng)
Definition at line 57 of file Matrix.cc.
Matrix() [5/5]
Alien::Matrix::Matrix (Matrix && m)
Definition at line 65 of file Matrix.cc.
~Matrix()
Alien::Matrix::~Matrix ()
Definition at line 71 of file Matrix.cc.
Member Function Documentation
colSpace()
const ISpace & Alien::Matrix::colSpace () const virtual
Get col space associated to the matrix.
Returns
The col space
Implements Alien::IMatrix.
Definition at line 108 of file Matrix.cc.
References colSpace().
Referenced by colSpace().
distribution()
const MatrixDistribution & Alien::Matrix::distribution () const
Definition at line 92 of file Matrix.cc.
hasUserFeature()
bool Alien::Matrix::hasUserFeature (String feature) const
Definition at line 122 of file Matrix.cc.
impl() [1/2]
MultiMatrixImpl * Alien::Matrix::impl () virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 130 of file Matrix.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiMatrixImpl * Alien::Matrix::impl () const virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 145 of file Matrix.cc.
References impl().
operator=() [1/2]
template<typename E> Matrix & Alien::Matrix::operator= (const E & expr)
Definition at line 911 of file MVExpr.h.
operator=() [2/2]
Matrix & Alien::Matrix::operator= (Matrix && m)
Definition at line 76 of file Matrix.cc.
rowSpace()
const ISpace & Alien::Matrix::rowSpace () const virtual
Get row space associated to the matrix.
Returns
The row space
Implements Alien::IMatrix.
Definition at line 100 of file Matrix.cc.
References rowSpace().
Referenced by rowSpace().
setUserFeature()
void Alien::Matrix::setUserFeature (String feature)
Definition at line 115 of file Matrix.cc.
visit()
void Alien::Matrix::visit (ICopyOnWriteMatrix &) const virtual
Visit method.
Implements Alien::IMatrix.
Definition at line 84 of file Matrix.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiMatrixImpl> Alien::Matrix::m_impl private
Definition at line 79 of file Matrix.h.
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cc
MVExpr.h