Arcane: Arcane::Materials::MeshBlockBuildInfo Class Reference
Arcane::Materials::MeshBlockBuildInfo Class Reference
Materials and Media.
Brief: Information for the creation of a block.
#include <arcane/materials/MeshBlockBuildInfo.h>
Public Member Functions
MeshBlockBuildInfo (const String &name, const CellGroup &cells)
Creates the information for a block named name on the cells cells.
const String & name () const
Block name.
const CellGroup & cells () const
List of block entities.
void addEnvironment (IMeshEnvironment *env)
Brief: Adds the environment env to the block.
ConstArrayView< IMeshEnvironment * > environments () const
List of environments in the block.
Private Attributes
String m_name
CellGroup m_cells
UniqueArray< IMeshEnvironment * > m_environments
Detailed Description
Brief: Information for the creation of a block.
This instance contains the necessary information for the creation of a block.
For more information, refer to IMeshBlock.
Once the specified creation information is provided, the block must be created via IMeshMaterialMng::createBlock().
Definition at line 49 of file MeshBlockBuildInfo.h.
Constructor & Destructor Documentation
MeshBlockBuildInfo()
Arcane::Materials::MeshBlockBuildInfo::MeshBlockBuildInfo (const String & name, const CellGroup & cells)
Creates the information for a block named name on the cells cells.
Definition at line 27 of file MeshBlockBuildInfo.cc.
References cells(), and name().
~MeshBlockBuildInfo()
Arcane::Materials::MeshBlockBuildInfo::~MeshBlockBuildInfo ()
Definition at line 37 of file MeshBlockBuildInfo.cc.
Member Function Documentation
addEnvironment()
void Arcane::Materials::MeshBlockBuildInfo::addEnvironment (IMeshEnvironment * env)
Brief: Adds the environment env to the block.
The environment must already have been created via IMeshMaterialMng::createEnvironment().
Definition at line 45 of file MeshBlockBuildInfo.cc.
References Arcane::Materials::IMeshComponent::name().
Referenced by Arcane::Materials::MeshMaterialMng::recreateFromDump().
cells()
const CellGroup & Arcane::Materials::MeshBlockBuildInfo::cells () const inline
List of block entities.
Definition at line 63 of file MeshBlockBuildInfo.h.
Referenced by MeshBlockBuildInfo().
environments()
ConstArrayView< IMeshEnvironment * > Arcane::Materials::MeshBlockBuildInfo::environments () const inline
List of environments in the block.
Definition at line 76 of file MeshBlockBuildInfo.h.
Referenced by Arcane::Materials::MeshMaterialMng::createBlock().
name()
const String & Arcane::Materials::MeshBlockBuildInfo::name () const inline
Block name.
Definition at line 60 of file MeshBlockBuildInfo.h.
Referenced by Arcane::Materials::MeshMaterialMng::createBlock(), and MeshBlockBuildInfo().
Member Data Documentation
m_cells
CellGroup Arcane::Materials::MeshBlockBuildInfo::m_cells private
Definition at line 84 of file MeshBlockBuildInfo.h.
m_environments
UniqueArray<IMeshEnvironment*> Arcane::Materials::MeshBlockBuildInfo::m_environments private
Definition at line 85 of file MeshBlockBuildInfo.h.
m_name
String Arcane::Materials::MeshBlockBuildInfo::m_name private
Definition at line 83 of file MeshBlockBuildInfo.h.
The documentation for this class was generated from the following files:
MeshBlockBuildInfo.h
MeshBlockBuildInfo.cc