Arcane: Arcane::Materials::AllEnvData Class Reference
Arcane::Materials::AllEnvData Class Reference
Information on environment values.
#include <arcane/materials/internal/AllEnvData.h>
Classes
class RecomputeConstituentCellInfos
Public Member Functions
AllEnvData (MeshMaterialMng *mmg)
void forceRecompute (bool compute_all)
Updates structures following a modification of material or environment cells.
void recomputeIncremental ()
void endCreate (bool is_continue)
Notification of the end of environment/material creation.
ConstituentConnectivityList * componentConnectivityList ()
ComponentItemInternalData * componentItemInternalData ()
void _computeInfosForAllEnvCells1 (RecomputeConstituentCellInfos &work_info)
void _computeInfosForAllEnvCells2 (RecomputeConstituentCellInfos &work_info)
void _computeInfosForEnvCells (RecomputeConstituentCellInfos &work_info)
Positions the info for EnvCells.
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Private Member Functions
void _computeNbEnvAndNbMatPerCell ()
void _computeAndResizeEnvItemsInternal ()
bool _isFullVerbose () const
void _rebuildMaterialsAndEnvironmentsFromGroups ()
void _checkLocalIdsCoherency () const
Checks the coherence of variableIndexer().localIds() with the global cell associated with the environment.
void _printAllEnvCells (CellVectorView ids)
void _checkConnectivityCoherency ()
void _rebuildIncrementalConnectivitiesFromGroups ()
Rebuilds the incremental connectivities for groups.
Private Attributes
MeshMaterialMng * m_material_mng = nullptr
ConstituentConnectivityList * m_component_connectivity_list = nullptr
Ref< IIncrementalItemSourceConnectivity > m_component_connectivity_list_ref
Int32 m_verbose_debug_level = 0
Verbosity level.
ComponentItemInternalData m_item_internal_data
Int64 m_current_mesh_timestamp = -1
Friends
class IncrementalComponentModifier
Additional Inherited Members
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Detailed Description
Information on environment values.
Definition at line 43 of file AllEnvData.h.
Constructor & Destructor Documentation
AllEnvData()
Arcane::Materials::AllEnvData::AllEnvData (MeshMaterialMng * mmg) explicit
Definition at line 74 of file AllEnvData.cc.
Member Function Documentation
_checkConnectivityCoherency()
void Arcane::Materials::AllEnvData::_checkConnectivityCoherency () private
Definition at line 576 of file AllEnvData.cc.
_checkLocalIdsCoherency()
void Arcane::Materials::AllEnvData::_checkLocalIdsCoherency () const private
Checks the coherence of variableIndexer().localIds() with the global cell associated with the environment.
Definition at line 397 of file AllEnvData.cc.
References ARCANE_FATAL, ENUMERATE_COMPONENTCELL, Arcane::Materials::ConstituentItem::globalCell(), and Arcane::Item::localId().
Referenced by forceRecompute().
_computeAndResizeEnvItemsInternal()
void Arcane::Materials::AllEnvData::_computeAndResizeEnvItemsInternal () private
Definition at line 129 of file AllEnvData.cc.
_computeInfosForAllEnvCells1()
void Arcane::Materials::AllEnvData::_computeInfosForAllEnvCells1 (RecomputeConstituentCellInfos & work_info)
Definition at line 243 of file AllEnvData.cc.
_computeInfosForAllEnvCells2()
void Arcane::Materials::AllEnvData::_computeInfosForAllEnvCells2 (RecomputeConstituentCellInfos & work_info)
Definition at line 283 of file AllEnvData.cc.
_computeInfosForEnvCells()
void Arcane::Materials::AllEnvData::_computeInfosForEnvCells (RecomputeConstituentCellInfos & work_info)
Positions the info for EnvCells.
Definition at line 313 of file AllEnvData.cc.
References Arcane::ItemGroup::_internalApi(), Arcane::Materials::matimpl::ConstituentItemBase::_setNbSubItem(), Arcane::Materials::matimpl::ConstituentItemBase::_setVariableIndex(), Arcane::Accelerator::RunQueuePool::barrier(), Arcane::TraceAccessor::info(), Arcane::ItemGroupImplInternal::itemsLocalId(), Arcane::Accelerator::makeCommand(), Arcane::Materials::MeshMaterialVariableIndexer::maxIndexInMultipleArray(), Arcane::IItemFamily::maxLocalId(), Arcane::ItemGroupImplInternal::notifySimdPaddingDone(), Arcane::Array< T >::resize(), RUNCOMMAND_LOOP1, Arcane::ItemGroup::size(), Arcane::SpanImpl< T, SizeType, Extent >::size(), and Arcane::Array< T >::view().
Referenced by forceRecompute().
_computeNbEnvAndNbMatPerCell()
void Arcane::Materials::AllEnvData::_computeNbEnvAndNbMatPerCell () private
Definition at line 114 of file AllEnvData.cc.
_isFullVerbose()
bool Arcane::Materials::AllEnvData::_isFullVerbose () const private
Definition at line 105 of file AllEnvData.cc.
_printAllEnvCells()
void Arcane::Materials::AllEnvData::_printAllEnvCells (CellVectorView ids) private
Definition at line 550 of file AllEnvData.cc.
_rebuildIncrementalConnectivitiesFromGroups()
void Arcane::Materials::AllEnvData::_rebuildIncrementalConnectivitiesFromGroups () private
Rebuilds the incremental connectivities for groups.
Definition at line 187 of file AllEnvData.cc.
References Arcane::Accelerator::makeQueue().
Referenced by forceRecompute().
_rebuildMaterialsAndEnvironmentsFromGroups()
void Arcane::Materials::AllEnvData::_rebuildMaterialsAndEnvironmentsFromGroups () private
Definition at line 204 of file AllEnvData.cc.
componentConnectivityList()
ConstituentConnectivityList * Arcane::Materials::AllEnvData::componentConnectivityList () inline
Definition at line 66 of file AllEnvData.h.
componentItemInternalData()
ComponentItemInternalData * Arcane::Materials::AllEnvData::componentItemInternalData () inline
Definition at line 70 of file AllEnvData.h.
endCreate()
void Arcane::Materials::AllEnvData::endCreate (bool is_continue)
Notification of the end of environment/material creation.
Definition at line 95 of file AllEnvData.cc.
forceRecompute()
void Arcane::Materials::AllEnvData::forceRecompute (bool compute_all)
Updates structures following a modification of material or environment cells.
This method reconstructs information only from the entity groups associated with materials and environments. Material variables are not taken into account by this method, so they may be invalidated after this call. If you want to preserve the values, you must first save the partial values, apply this method, and then restore the partial values. The MeshMaterialBackup class allows this saving/restoring.
Note that this method can be used during recovery while preserving material variable values because the group structure is the same after a recovery, which does not invalidate the partial values.
Definition at line 433 of file AllEnvData.cc.
References _checkLocalIdsCoherency(), _computeInfosForEnvCells(), _rebuildIncrementalConnectivitiesFromGroups(), Arcane::Materials::ConstituentItem::_varIndex(), Arcane::arcaneIsCheck(), ENUMERATE_COMPONENTITEM, Arcane::TraceAccessor::info(), Arcane::ItemVectorView::localIds(), m_verbose_debug_level, Arcane::ItemGroup::name(), Arcane::Materials::MeshMaterialVariableIndexer::name(), Arcane::ConstArrayView< T >::size(), Arcane::ItemGroup::size(), and Arcane::ItemGroup::view().
recomputeIncremental()
void Arcane::Materials::AllEnvData::recomputeIncremental ()
Definition at line 539 of file AllEnvData.cc.
Friends And Related Symbol Documentation
IncrementalComponentModifier
friend class IncrementalComponentModifier friend
Definition at line 46 of file AllEnvData.h.
Member Data Documentation
m_component_connectivity_list
ConstituentConnectivityList* Arcane::Materials::AllEnvData::m_component_connectivity_list = nullptr private
Definition at line 78 of file AllEnvData.h.
m_component_connectivity_list_ref
Ref<IIncrementalItemSourceConnectivity> Arcane::Materials::AllEnvData::m_component_connectivity_list_ref private
Definition at line 79 of file AllEnvData.h.
m_current_mesh_timestamp
Int64 Arcane::Materials::AllEnvData::m_current_mesh_timestamp = -1 private
Definition at line 85 of file AllEnvData.h.
m_item_internal_data
ComponentItemInternalData Arcane::Materials::AllEnvData::m_item_internal_data private
Definition at line 84 of file AllEnvData.h.
m_material_mng
MeshMaterialMng* Arcane::Materials::AllEnvData::m_material_mng = nullptr private
Definition at line 77 of file AllEnvData.h.
m_verbose_debug_level
Int32 Arcane::Materials::AllEnvData::m_verbose_debug_level = 0 private
Verbosity level.
Definition at line 82 of file AllEnvData.h.
Referenced by forceRecompute().
The documentation for this class was generated from the following files:
AllEnvData.h
AllEnvData.cc