Alien: Alien::BlockVector Class Reference
Alien::BlockVector Class Reference final
Public Member Functions
BlockVector (const Block &block, const VectorDistribution &dist)
BlockVector (Integer nrows, Integer nrows_local, const Block &block, IMessagePassingMng *parallel_mng)
BlockVector (Integer nrows, const Block &block, IMessagePassingMng *parallel_mng)
BlockVector (BlockVector &&vector)
BlockVector & operator= (BlockVector &&vector)
BlockVector (const BlockVector &)=delete
BlockVector & operator= (const BlockVector &)=delete
void init (const Block &block, const VectorDistribution &dist)
void free ()
void clear ()
void visit (ICopyOnWriteVector &) const override
Visit method.
const VectorDistribution & distribution () const
const ISpace & space () const override
Get the space associated to the vector.
void setUserFeature (String feature)
bool hasUserFeature (Arccore::String feature) const
const Block & block () const
MultiVectorImpl * impl () override
Get the multivector implementation.
const MultiVectorImpl * impl () const override
Get the multivector implementation.
Private Attributes
std::shared_ptr< MultiVectorImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from Alien::IVector
IVector ()
Constructor.
Detailed Description
Definition at line 37 of file BlockVector.h.
Constructor & Destructor Documentation
BlockVector() [1/5]
Alien::BlockVector::BlockVector ()
Definition at line 33 of file BlockVector.cc.
BlockVector() [2/5]
Alien::BlockVector::BlockVector (const Block & block, const VectorDistribution & dist)
Definition at line 40 of file BlockVector.cc.
BlockVector() [3/5]
Alien::BlockVector::BlockVector (Integer nrows, Integer nrows_local, const Block & block, IMessagePassingMng * parallel_mng)
Definition at line 48 of file BlockVector.cc.
BlockVector() [4/5]
Alien::BlockVector::BlockVector (Integer nrows, const Block & block, IMessagePassingMng * parallel_mng)
Definition at line 59 of file BlockVector.cc.
BlockVector() [5/5]
Alien::BlockVector::BlockVector (BlockVector && vector)
Definition at line 69 of file BlockVector.cc.
Member Function Documentation
block()
const Block & Alien::BlockVector::block () const nodiscard
Definition at line 142 of file BlockVector.cc.
clear()
void Alien::BlockVector::clear ()
Definition at line 99 of file BlockVector.cc.
distribution()
const VectorDistribution & Alien::BlockVector::distribution () const nodiscard
Definition at line 122 of file BlockVector.cc.
free()
void Alien::BlockVector::free ()
Definition at line 92 of file BlockVector.cc.
hasUserFeature()
bool Alien::BlockVector::hasUserFeature (Arccore::String feature) const nodiscard
Definition at line 136 of file BlockVector.cc.
impl() [1/2]
const MultiVectorImpl * Alien::BlockVector::impl () const nodiscard override virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 170 of file BlockVector.cc.
References impl().
impl() [2/2]
MultiVectorImpl * Alien::BlockVector::impl () override virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 155 of file BlockVector.cc.
References impl().
Referenced by impl(), and impl().
init()
void Alien::BlockVector::init (const Block & block, const VectorDistribution & dist)
Definition at line 84 of file BlockVector.cc.
operator=()
BlockVector & Alien::BlockVector::operator= (BlockVector && vector)
Definition at line 76 of file BlockVector.cc.
setUserFeature()
void Alien::BlockVector::setUserFeature (String feature)
Definition at line 129 of file BlockVector.cc.
space()
const ISpace & Alien::BlockVector::space () const nodiscard override virtual
Get the space associated to the vector.
Returns
The space
Implements Alien::IVector.
Definition at line 107 of file BlockVector.cc.
References space().
Referenced by space().
visit()
void Alien::BlockVector::visit (ICopyOnWriteVector &) const override virtual
Visit method.
Implements Alien::IVector.
Definition at line 114 of file BlockVector.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiVectorImpl> Alien::BlockVector::m_impl private
Definition at line 84 of file BlockVector.h.
The documentation for this class was generated from the following files:
BlockVector.h
BlockVector.cc