Arcane: Arcane::PostProcessorWriterCommonBase Class Reference
Arcane::PostProcessorWriterCommonBase Class Reference
Base class for a writer for post-processing information.
#include <arcane/core/PostProcessorWriterBase.h>
Public Member Functions
void setBaseDirectoryName (const String &dirname) override
Positions the output directory name for files.
const String & baseDirectoryName () override
Name of the output directory for files.
void setBaseFileName (const String &filename) override
Positions the name of the file containing the outputs.
const String & baseFileName () override
Name of the file containing the outputs.
void setTimes (ConstArrayView< Real > times) override
Positions the list of times.
ConstArrayView< Real > times () override
List of saved times.
void setVariables (VariableCollection variables) override
Positions the list of variables to output.
VariableCollection variables () override
List of variables to save.
void setGroups (ItemGroupCollection groups) override
Positions the list of groups to output.
ItemGroupCollection groups () override
List of groups to save.
Public Member Functions inherited from Arcane::IPostProcessorWriter
virtual ~IPostProcessorWriter ()=default
Releases resources.
virtual void build ()=0
Constructs the instance.
virtual IDataWriter * dataWriter ()=0
Returns the writer associated with this post-processor.
virtual String getBaseDirectoryName ()
Name of the output directory for files.
virtual String getBaseFileName ()
Name of the file containing the outputs.
virtual void setMesh (IMesh *mesh)
Positions the mesh.
virtual void notifyBeginWrite ()=0
Notifies that an output is going to be performed with the current parameters.
virtual void notifyEndWrite ()=0
Notifies that an output has just been performed.
virtual void close ()=0
Closes the writer. After closing, it can no longer be used.
Detailed Description
Base class for a writer for post-processing information.
Definition at line 37 of file PostProcessorWriterBase.h.
Constructor & Destructor Documentation
PostProcessorWriterCommonBase()
Arcane::PostProcessorWriterCommonBase::PostProcessorWriterCommonBase ()
Definition at line 64 of file PostProcessorWriterBase.cc.
~PostProcessorWriterCommonBase()
Arcane::PostProcessorWriterCommonBase::~PostProcessorWriterCommonBase () override
Definition at line 73 of file PostProcessorWriterBase.cc.
Member Function Documentation
baseDirectoryName()
const String & Arcane::PostProcessorWriterCommonBase::baseDirectoryName () override virtual
Name of the output directory for files.
Implements Arcane::IPostProcessorWriter.
Definition at line 103 of file PostProcessorWriterBase.cc.
Referenced by Arcane::ManualHdf5VariableWriter::notifyBeginWrite().
baseFileName()
const String & Arcane::PostProcessorWriterCommonBase::baseFileName () override virtual
Name of the file containing the outputs.
Implements Arcane::IPostProcessorWriter.
Definition at line 121 of file PostProcessorWriterBase.cc.
groups()
ItemGroupCollection Arcane::PostProcessorWriterCommonBase::groups () override virtual
List of groups to save.
Implements Arcane::IPostProcessorWriter.
Definition at line 175 of file PostProcessorWriterBase.cc.
Referenced by setGroups().
setBaseDirectoryName()
void Arcane::PostProcessorWriterCommonBase::setBaseDirectoryName (const String & dirname) override virtual
Positions the output directory name for files.
This directory must exist.
Implements Arcane::IPostProcessorWriter.
Definition at line 94 of file PostProcessorWriterBase.cc.
setBaseFileName()
void Arcane::PostProcessorWriterCommonBase::setBaseFileName (const String & filename) override virtual
Positions the name of the file containing the outputs.
Not all writers support changing the file name.
Implements Arcane::IPostProcessorWriter.
Definition at line 112 of file PostProcessorWriterBase.cc.
setGroups()
void Arcane::PostProcessorWriterCommonBase::setGroups (ItemGroupCollection groups) override virtual
Positions the list of groups to output.
The collection passed as an argument is cloned.
Implements Arcane::IPostProcessorWriter.
Definition at line 148 of file PostProcessorWriterBase.cc.
References groups().
setTimes()
void Arcane::PostProcessorWriterCommonBase::setTimes (ConstArrayView< Real > times) override virtual
Positions the list of times.
Implements Arcane::IPostProcessorWriter.
Definition at line 130 of file PostProcessorWriterBase.cc.
References times().
setVariables()
void Arcane::PostProcessorWriterCommonBase::setVariables (VariableCollection variables) override virtual
Positions the list of variables to output.
Implements Arcane::IPostProcessorWriter.
Definition at line 139 of file PostProcessorWriterBase.cc.
References variables().
times()
ConstArrayView< Real > Arcane::PostProcessorWriterCommonBase::times () override virtual
List of saved times.
Implements Arcane::IPostProcessorWriter.
Definition at line 157 of file PostProcessorWriterBase.cc.
Referenced by Arcane::ManualHdf5VariableWriter::notifyBeginWrite(), Arcane::ManualHdf5VariableWriter::notifyEndWrite(), and setTimes().
variables()
VariableCollection Arcane::PostProcessorWriterCommonBase::variables () override virtual
List of variables to save.
Implements Arcane::IPostProcessorWriter.
Definition at line 166 of file PostProcessorWriterBase.cc.
Referenced by Arcane::ManualHdf5VariableWriter::notifyBeginWrite(), Arcane::ManualHdf5VariableWriter::notifyEndWrite(), and setVariables().
The documentation for this class was generated from the following files:
PostProcessorWriterBase.h
PostProcessorWriterBase.cc