Arcane: Arcane::IPropertyMng Class Reference
Arcane::IPropertyMng Class Reference abstract
Interface of the property manager.
#include <arcane/core/IPropertyMng.h>
Public Member Functions
virtual ~IPropertyMng ()
Frees the resources.
virtual ITraceMng * traceMng () const =0
virtual PropertiesImpl * getPropertiesImpl (const String &full_name)=0
Retrieves the list of properties by full name full_name.
virtual void registerProperties (const Properties &p)=0
Registers the properties referenced by p.
virtual void destroyProperties (const Properties &p)=0
Deletes the properties referenced by p.
virtual void serialize (ISerializer *serializer)=0
Performs serialization.
virtual void writeTo (ByteArray &bytes)=0
Serializes property information into bytes.
virtual void readFrom (Span< const Byte > bytes)=0
Reads the serialized information contained in bytes.
virtual void print (std::ostream &o) const =0
Prints the properties and their values to the stream o.
virtual IObservable * writeObservable ()=0
Observable for writing.
virtual IObservable * readObservable ()=0
Observable for reading.
Detailed Description
Interface of the property manager.
Definition at line 38 of file IPropertyMng.h.
Constructor & Destructor Documentation
~IPropertyMng()
virtual Arcane::IPropertyMng::~IPropertyMng () inline virtual
Frees the resources.
Definition at line 42 of file IPropertyMng.h.
Member Function Documentation
destroyProperties()
virtual void Arcane::IPropertyMng::destroyProperties (const Properties & p) pure virtual
Deletes the properties referenced by p.
Implemented in Arcane::PropertyMng.
Referenced by Arcane::Properties::destroy().
getPropertiesImpl()
virtual PropertiesImpl * Arcane::IPropertyMng::getPropertiesImpl (const String & full_name) pure virtual
Retrieves the list of properties by full name full_name.
This method must only be called by the Properties class. To retrieve an instance, the Properties constructor must be used.
Implemented in Arcane::PropertyMng.
Referenced by Arcane::Properties::Properties(), and Arcane::Properties::Properties().
print()
virtual void Arcane::IPropertyMng::print (std::ostream & o) const pure virtual
Prints the properties and their values to the stream o.
Implemented in Arcane::PropertyMng.
readFrom()
virtual void Arcane::IPropertyMng::readFrom (Span< const Byte > bytes) pure virtual
Reads the serialized information contained in bytes.
The bytes array must have been created by a call to writeTo().
Implemented in Arcane::PropertyMng.
readObservable()
virtual IObservable * Arcane::IPropertyMng::readObservable () pure virtual
Observable for reading.
The observers registered in this observable are called at the end of readFrom().
Implemented in Arcane::PropertyMng.
registerProperties()
virtual void Arcane::IPropertyMng::registerProperties (const Properties & p) pure virtual
Registers the properties referenced by p.
Implemented in Arcane::PropertyMng.
Referenced by Arcane::Properties::Properties(), and Arcane::Properties::Properties().
serialize()
virtual void Arcane::IPropertyMng::serialize (ISerializer * serializer) pure virtual
Performs serialization.
Implemented in Arcane::PropertyMng.
writeObservable()
virtual IObservable * Arcane::IPropertyMng::writeObservable () pure virtual
Observable for writing.
The observers registered in this observable are called at the beginning of writeTo().
Implemented in Arcane::PropertyMng.
Referenced by Arcane::TimeHistoryMngInternal::addObservers().
writeTo()
virtual void Arcane::IPropertyMng::writeTo (ByteArray & bytes) pure virtual
Serializes property information into bytes.
Implemented in Arcane::PropertyMng.
The documentation for this class was generated from the following file:
IPropertyMng.h