Arcane: Arcane::mesh::ItemTools Class Reference
Arcane::mesh::ItemTools Class Reference
Utilities helping to find items based on others.
#include <arcane/mesh/ItemTools.h>
Static Public Member Functions
static bool isSameFace (Face face, Int64ConstArrayView face_nodes_uid)
static Face findFaceInNode2 (Node node, Integer face_type_id, Int64ConstArrayView face_nodes_uid)
static Edge findEdgeInNode2 (Node node, Int64 begin_node, Int64 end_node)
Static Private Member Functions
static ItemInternal * findFaceInNode (Node node, Integer face_type_id, Int64ConstArrayView face_nodes_uid)
static ItemInternal * findEdgeInNode (Node node, Int64 begin_node, Int64 end_node)
Detailed Description
Utilities helping to find items based on others.
Definition at line 32 of file ItemTools.h.
Member Function Documentation
findEdgeInNode()
ItemInternal * Arcane::mesh::ItemTools::findEdgeInNode (Node node, Int64 begin_node, Int64 end_node) static private
Searches for an edge connected to the node node and connecting the nodes with uids begin_node and end_node
Parameters
node : node to test
begin_node : uid of the first node of the searched edge
end_node : uid of the second node of the searched edge
Definition at line 84 of file ItemTools.cc.
References findEdgeInNode2(), and Arcane::Item::null().
findEdgeInNode2()
Edge Arcane::mesh::ItemTools::findEdgeInNode2 (Node node, Int64 begin_node, Int64 end_node) static
Searches for an edge connected to the node node and connecting the nodes with uids begin_node and end_node
Parameters
node : node to test
begin_node : uid of the first node of the searched edge
end_node : uid of the second node of the searched edge
Definition at line 72 of file ItemTools.cc.
References Arcane::Node::edges().
Referenced by Arcane::mesh::OneMeshItemAdder::addOneParentItem(), and findEdgeInNode().
findFaceInNode()
ItemInternal * Arcane::mesh::ItemTools::findFaceInNode (Node node, Integer face_type_id, Int64ConstArrayView face_nodes_uid) static private
Searches for a face connected to the node node corresponding to the list of nodes face_nodes_uid.
Parameters
node : node to test
face_type_id : type of the face searched
face_nodes_uid : a list of node uids
Definition at line 59 of file ItemTools.cc.
References findFaceInNode2(), and Arcane::Item::null().
findFaceInNode2()
Face Arcane::mesh::ItemTools::findFaceInNode2 (Node node, Integer face_type_id, Int64ConstArrayView face_nodes_uid) static
Searches for a face connected to the node node corresponding to the list of nodes face_nodes_uid.
Parameters
node : node to test
face_type_id : type of the face searched
face_nodes_uid : a list of node uids
Definition at line 43 of file ItemTools.cc.
References Arcane::Node::faces(), and isSameFace().
Referenced by Arcane::mesh::FaceUniqueIdBuilder::_computeFacesUniqueIdsParallelV1(), findFaceInNode(), and Arcane::mesh::MeshNodeMerger::mergeNodes().
isSameFace()
bool Arcane::mesh::ItemTools::isSameFace (Face face, Int64ConstArrayView face_nodes_uid) static
Checks if the list of nodes of a face matches a provided list Compares the uids of the nodes. The order must be the same.
Parameters
face : the face to test
face_nodes_uid : a list of node uids
Definition at line 28 of file ItemTools.cc.
References Arcane::ItemWithNodes::nodes().
Referenced by findFaceInNode2().
The documentation for this class was generated from the following files:
ItemTools.h
ItemTools.cc