Arcane: Arcane::ItemInternalConnectivityList Class Reference
Arcane::ItemInternalConnectivityList Class Reference
Public Types
enum {
NODE_IDX = 0 , EDGE_IDX = 1 , FACE_IDX = 2 , CELL_IDX = 3 ,
HPARENT_IDX = 4 , HCHILD_IDX = 5 , MAX_ITEM_KIND = 6
}
Public Member Functions
void updateMeshItemInternalList ()
Int32ConstArrayView connectivityIndex (Int32 item_kind) const
Connectivity index array for entities of kind item_kind.
Int32ConstArrayView connectivityList (Int32 item_kind) const
Array containing the connectivity list for entities of kind item_kind.
Int32ConstArrayView connectivityNbItem (Int32 item_kind) const
Array containing the number of connected entities for entities of kind item_kind.
Int32 maxNbConnectedItem (Int32 item_kind) const
Maximum number of connected entities.
ItemConnectivityContainerView containerView (Int32 item_kind) const
constexpr ItemBaseBuildInfo nodeBase (Int32 lid, Int32 aindex) const
constexpr ItemBaseBuildInfo edgeBase (Int32 lid, Int32 aindex) const
constexpr ItemBaseBuildInfo faceBase (Int32 lid, Int32 aindex) const
constexpr ItemBaseBuildInfo cellBase (Int32 lid, Int32 aindex) const
ItemBaseBuildInfo hParentBase (Int32 lid, Int32 aindex, ItemSharedInfo *isf) const
ItemBaseBuildInfo hChildBase (Int32 lid, Int32 aindex, ItemSharedInfo *isf) const
auto nodeList (Int32 lid) const
auto edgeList (Int32 lid) const
auto faceList (Int32 lid) const
auto cellList (Int32 lid) const
Static Public Attributes
static ItemInternalConnectivityList nullInstance
Friends
class ItemBase
class ItemInternal
class Item
Detailed Description
Definition at line 94 of file ItemInternal.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Definition at line 166 of file ItemInternal.h.
Constructor & Destructor Documentation
ItemInternalConnectivityList()
Arcane::ItemInternalConnectivityList::ItemInternalConnectivityList () inline
Definition at line 183 of file ItemInternal.h.
Member Function Documentation
cellBase()
ItemBaseBuildInfo Arcane::ItemInternalConnectivityList::cellBase (Int32 lid, Int32 aindex) const inline constexpr
Definition at line 297 of file ItemInternal.h.
cellList()
auto Arcane::ItemInternalConnectivityList::cellList (Int32 lid) const inline
Definition at line 313 of file ItemInternal.h.
connectivityIndex()
Int32ConstArrayView Arcane::ItemInternalConnectivityList::connectivityIndex (Int32 item_kind) const inline
Connectivity index array for entities of kind item_kind.
Definition at line 253 of file ItemInternal.h.
References connectivityIndex().
Referenced by connectivityIndex().
connectivityList()
Int32ConstArrayView Arcane::ItemInternalConnectivityList::connectivityList (Int32 item_kind) const inline
Array containing the connectivity list for entities of kind item_kind.
Definition at line 259 of file ItemInternal.h.
References connectivityList().
Referenced by connectivityList().
connectivityNbItem()
Int32ConstArrayView Arcane::ItemInternalConnectivityList::connectivityNbItem (Int32 item_kind) const inline
Array containing the number of connected entities for entities of kind item_kind.
Definition at line 265 of file ItemInternal.h.
References connectivityNbItem().
Referenced by connectivityNbItem().
containerView()
ItemConnectivityContainerView Arcane::ItemInternalConnectivityList::containerView (Int32 item_kind) const inline
Definition at line 278 of file ItemInternal.h.
edgeBase()
ItemBaseBuildInfo Arcane::ItemInternalConnectivityList::edgeBase (Int32 lid, Int32 aindex) const inline constexpr
Definition at line 289 of file ItemInternal.h.
edgeList()
auto Arcane::ItemInternalConnectivityList::edgeList (Int32 lid) const inline
Definition at line 311 of file ItemInternal.h.
faceBase()
ItemBaseBuildInfo Arcane::ItemInternalConnectivityList::faceBase (Int32 lid, Int32 aindex) const inline constexpr
Definition at line 293 of file ItemInternal.h.
faceList()
auto Arcane::ItemInternalConnectivityList::faceList (Int32 lid) const inline
Definition at line 312 of file ItemInternal.h.
hChildBase()
ItemBaseBuildInfo Arcane::ItemInternalConnectivityList::hChildBase (Int32 lid, Int32 aindex, ItemSharedInfo * isf) const inline
Definition at line 305 of file ItemInternal.h.
hParentBase()
ItemBaseBuildInfo Arcane::ItemInternalConnectivityList::hParentBase (Int32 lid, Int32 aindex, ItemSharedInfo * isf) const inline
Definition at line 301 of file ItemInternal.h.
maxNbConnectedItem()
Int32 Arcane::ItemInternalConnectivityList::maxNbConnectedItem (Int32 item_kind) const inline
Maximum number of connected entities.
Definition at line 273 of file ItemInternal.h.
nodeBase()
ItemBaseBuildInfo Arcane::ItemInternalConnectivityList::nodeBase (Int32 lid, Int32 aindex) const inline constexpr
Definition at line 285 of file ItemInternal.h.
nodeList()
auto Arcane::ItemInternalConnectivityList::nodeList (Int32 lid) const inline
Definition at line 310 of file ItemInternal.h.
updateMeshItemInternalList()
void Arcane::ItemInternalConnectivityList::updateMeshItemInternalList () inline
Definition at line 200 of file ItemInternal.h.
Friends And Related Symbol Documentation
Item
friend class Item friend
Definition at line 101 of file ItemInternal.h.
ItemBase
friend class ItemBase friend
Definition at line 99 of file ItemInternal.h.
ItemInternal
friend class ItemInternal friend
Definition at line 100 of file ItemInternal.h.
Member Data Documentation
nullInstance
ItemInternalConnectivityList Arcane::ItemInternalConnectivityList::nullInstance static
Definition at line 179 of file ItemInternal.h.
The documentation for this class was generated from the following files:
ItemInternal.h
ItemInternal.cc