Alien: Matrix Constructor
Matrix Constructor
Topics
Block related API
Functions
Alien::Move::MatrixData::MatrixData ()
Alien::Move::MatrixData::MatrixData (const Space &space, const MatrixDistribution &dist)
Alien::Move::MatrixData::MatrixData (const Space &row_space, const Space &col_space, const MatrixDistribution &dist)
Alien::Move::MatrixData::MatrixData (Integer size, const MatrixDistribution &dist)
Alien::Move::MatrixData::MatrixData (Integer row_size, Integer col_size, const MatrixDistribution &dist)
Alien::Move::MatrixData::MatrixData (const MatrixDistribution &dist)
Alien::Move::MatrixData::MatrixData (MatrixData &&matrix)
virtual Alien::Move::MatrixData::~MatrixData ()=default
}@
MatrixData & Alien::Move::MatrixData::operator= (MatrixData &&matrix)
Move from Matrix.
void Alien::Move::MatrixData::init (const Space &space, const MatrixDistribution &dist)
Alien::Move::MatrixData::MatrixData (const MatrixData &)=delete
void Alien::Move::MatrixData::operator= (const MatrixData &)=delete
MatrixData Alien::Move::MatrixData::clone () const
Alien::Move::VectorData::VectorData ()
Alien::Move::VectorData::VectorData (const ISpace &space, const VectorDistribution &dist)
Alien::Move::VectorData::VectorData (Integer size, const VectorDistribution &dist)
Alien::Move::VectorData::VectorData (const VectorDistribution &dist)
Alien::Move::VectorData::VectorData (VectorData &&vector)
virtual Alien::Move::VectorData::~VectorData ()=default
VectorData & Alien::Move::VectorData::operator= (VectorData &&vector)
Move from Vector.
void Alien::Move::VectorData::init (const ISpace &space, const VectorDistribution &dist)
Alien::Move::VectorData::VectorData (const VectorData &)=delete
VectorData & Alien::Move::VectorData::operator= (const VectorData &)=delete
VectorData Alien::Move::VectorData::clone () const
Detailed Description
Function Documentation
clone() [1/2]
MatrixData Alien::Move::MatrixData::clone () const
Definition at line 232 of file MatrixData.cc.
clone() [2/2]
VectorData Alien::Move::VectorData::clone () const
Definition at line 209 of file VectorData.cc.
init() [1/2]
void Alien::Move::MatrixData::init (const Space & space, const MatrixDistribution & dist)
Initialize a Matrix with a Space.
Parameters
Space related functions. Domain and Codomain Space for the Matrix.
dist Parallel Distribution.
Definition at line 96 of file MatrixData.cc.
References Alien::MatrixDistribution::clone().
Referenced by ~MatrixData().
init() [2/2]
void Alien::Move::VectorData::init (const ISpace & space, const VectorDistribution & dist)
Initialize a Vector with a Space.
Parameters
space Definition Space.
dist Parallel Distribution.
Definition at line 76 of file VectorData.cc.
References Alien::VectorDistribution::clone(), and space().
Referenced by ~VectorData().
MatrixData() [1/8]
Alien::Move::MatrixData::MatrixData ()
Empty constructor
This matrix must be associated with a \r Space before use.
Definition at line 39 of file MatrixData.cc.
Referenced by createMatrixData, MatrixData(), MatrixData(), operator=(), operator=(), and ~MatrixData().
MatrixData() [2/8]
Alien::Move::MatrixData::MatrixData (const MatrixData &) delete
Only support move semantic
References MatrixData().
MatrixData() [3/8]
Alien::Move::MatrixData::MatrixData (const MatrixDistribution & dist) explicit
Build a new matrix on MatrixDistribution
Parameters
dist Parallel distribution.
This matrix is directly ready to use.
Definition at line 75 of file MatrixData.cc.
MatrixData() [4/8]
Alien::Move::MatrixData::MatrixData (const Space & row_space, const Space & col_space, const MatrixDistribution & dist)
Build a new matrix from two Spaces
Parameters
row_space Domain Space of the matrix.
col_space Codomain Space of the matrix.
dist Parallel distribution.
This matrix is directly ready to use.
Definition at line 53 of file MatrixData.cc.
MatrixData() [5/8]
Alien::Move::MatrixData::MatrixData (const Space & space, const MatrixDistribution & dist)
Build a new matrix from a Space
Parameters
Space related functions. Domain (and Codomain) Space of the matrix.
dist Parallel distribution.
This matrix is directly ready to use.
Definition at line 46 of file MatrixData.cc.
MatrixData() [6/8]
Alien::Move::MatrixData::MatrixData (Integer row_size, Integer col_size, const MatrixDistribution & dist)
Build a new matrix from two sizes.
Matlab-like interface, matrix is defined as a [0, n-1]x[0, m-1] array.
Parameters
row_size Number of rows of the matrix.
col_size Number of rows of the matrix.
dist Parallel distribution.
This matrix is ready to use on an anonymous Space.
Definition at line 68 of file MatrixData.cc.
MatrixData() [7/8]
Alien::Move::MatrixData::MatrixData (Integer size, const MatrixDistribution & dist)
Build a new matrix from a size.
Matlab-like interface, matrix is defined as a [0, n-1]x[0, n-1] array.
Parameters
size Number of rows and columns of the matrix.
dist Parallel distribution.
This matrix is ready to use on an anonymous Space.
Definition at line 61 of file MatrixData.cc.
MatrixData() [8/8]
Alien::Move::MatrixData::MatrixData (MatrixData && matrix)
Move constructor for Matrix
Parameters
matrix Matrix to move from.
Definition at line 82 of file MatrixData.cc.
References MatrixData().
operator=() [1/4]
void Alien::Move::MatrixData::operator= (const MatrixData &) delete
Only support move semantic
References clear(), colSpace(), distribution(), free(), MatrixData(), rowSpace(), and visit().
operator=() [2/4]
MatrixData & Alien::Move::MatrixData::operator= (MatrixData && matrix)
Move from Matrix.
Move assignment
Parameters
matrix Matrix to move from.
Definition at line 88 of file MatrixData.cc.
References MatrixData().
Referenced by ~MatrixData().
operator=() [3/4]
VectorData & Alien::Move::VectorData::operator= (const VectorData &) delete
Only support move semantic
References clear(), createVectorData, distribution(), free(), hasUserFeature(), impl(), setUserFeature(), space(), VectorData(), and visit().
operator=() [4/4]
VectorData & Alien::Move::VectorData::operator= (VectorData && vector)
Move from Vector.
Move assignment
Parameters
matrix Vector to move from.
Definition at line 68 of file VectorData.cc.
References VectorData().
Referenced by ~VectorData().
VectorData() [1/6]
Alien::Move::VectorData::VectorData ()
Empty constructor
This vector must be associated with a Space before use.
Definition at line 37 of file VectorData.cc.
Referenced by createVectorData, operator=(), operator=(), VectorData(), VectorData(), and ~VectorData().
VectorData() [2/6]
Alien::Move::VectorData::VectorData (const ISpace & space, const VectorDistribution & dist)
Build a new Vector from a Space
Parameters
space Definition Space of the Vector.
dist Parallel distribution.
This vector is directly ready to use.
See also
VectorData::VectorData(const VectorDistribution&).
Definition at line 44 of file VectorData.cc.
References space().
VectorData() [3/6]
Alien::Move::VectorData::VectorData (const VectorData &) delete
Only support move semantic
References VectorData().
VectorData() [4/6]
Alien::Move::VectorData::VectorData (const VectorDistribution & dist) explicit
Build a new Vector from a Space
 \param space Definition Space of the Vector.
 \param dist Parallel distribution.
 This vector is directly ready to use.
Definition at line 56 of file VectorData.cc.
References space().
VectorData() [5/6]
Alien::Move::VectorData::VectorData (Integer size, const VectorDistribution & dist)
Build a new Vector from a size.
Matlab-like interface, Vector is defined as a [0, n-1] array.
Parameters
size Number of elements of the vector.
dist Parallel distribution.
This vector is ready to use on an anonymous Space.
See also
VectorData::VectorData(const VectorDistribution&).
Definition at line 50 of file VectorData.cc.
VectorData() [6/6]
Alien::Move::VectorData::VectorData (VectorData && vector)
Move constructor for Vector
Parameters
vector Vector to move from.
Definition at line 62 of file VectorData.cc.
References VectorData().
~MatrixData()
virtual Alien::Move::MatrixData::~MatrixData () virtual default
}@
Destructor All internal data structures will be deleted.
References init(), MatrixData(), and operator=().
~VectorData()
virtual Alien::Move::VectorData::~VectorData () virtual default
}@
Destructor All internal data structures will be deleted.
References init(), operator=(), space(), and VectorData().