Arcane: Arcane::Parallel::Stat Class Reference
Arcane::Parallel::Stat Class Reference
Statistics on parallelism.
Classes
class CumulativeStat
class SerializedStats
Serialization info.
Public Types
using Base = MP::Stat
using CumulativeStatMap = std::map<String, CumulativeStat>
Public Types inherited from Arcane::MessagePassing::Stat
using OneStatMap = std::map<String, OneStat*>
DEPRECATED.
typedef std::pair< String, OneStat * > OneStatValue
Public Types inherited from Arcane::MessagePassing::IStat
using OneStatMap = std::map<String, OneStat*>
Public Member Functions
MP::IStat * toArccoreStat () override
void add (const String &name, double elapsed_time, Int64 msg_size) override
Adds a statistic.
void print (ITraceMng *msg) override
Prints the statistics to trace.
void enable (bool is_enabled) override
Enables or disables statistics.
void dumpJSON (JSONWriter &writer) override
Outputs the statistics in JSON format.
void saveValues (ITraceMng *tm, Properties *p) override
Saves the current values into p.
void mergeValues (ITraceMng *tm, Properties *p) override
Merges the current values with those saved in p.
void printCollective (IParallelMng *pm) override
Displays the statistics collectively.
Public Member Functions inherited from Arcane::MessagePassing::Stat
~Stat () override
Releases resources.
void print (std::ostream &o)
const OneStatMap & stats () const override
Retrieval of statistics.
const StatData & getData () const
const StatCollection & statList () const override
Retrieval of statistics.
void resetCurrentStat () override
Resets current statistics.
Public Member Functions inherited from Arcane::MessagePassing::IStat
virtual ~IStat ()=default
Frees resources.
Public Member Functions inherited from Arcane::Parallel::IStat
virtual ~IStat ()
Frees resources.
Private Member Functions
void _mergeStats (CumulativeStatMap &stat_map)
Merges the instance's values with those contained within the instance.
void _printCollective (const CumulativeStatMap &stat_map, IParallelMng *pm)
Private Attributes
CumulativeStatMap m_previous_stat_map
Detailed Description
Statistics on parallelism.
Definition at line 45 of file arcane/src/arcane/core/parallel/Stat.cc.
Member Typedef Documentation
Base
using Arcane::Parallel::Stat::Base = MP::Stat
Definition at line 51 of file arcane/src/arcane/core/parallel/Stat.cc.
CumulativeStatMap
using Arcane::Parallel::Stat::CumulativeStatMap = std::map<String, CumulativeStat>
Definition at line 63 of file arcane/src/arcane/core/parallel/Stat.cc.
Member Function Documentation
_mergeStats()
void Arcane::Parallel::Stat::_mergeStats (CumulativeStatMap & stat_map) private
Merges the instance's values with those contained within the instance.
Definition at line 248 of file arcane/src/arcane/core/parallel/Stat.cc.
References Arcane::MessagePassing::Stat::statList().
Referenced by mergeValues(), printCollective(), and saveValues().
_printCollective()
void Arcane::Parallel::Stat::_printCollective (const CumulativeStatMap & stat_map, IParallelMng * pm) private
Definition at line 304 of file arcane/src/arcane/core/parallel/Stat.cc.
add()
void Arcane::Parallel::Stat::add (const String & name, double elapsed_time, Int64 msg_size) override virtual
Adds a statistic.
Parameters
name name of the statistic
elapsed_time time used for the message
msg_size size of the message sent.
Reimplemented from Arcane::MessagePassing::Stat.
Definition at line 148 of file arcane/src/arcane/core/parallel/Stat.cc.
References Arccore::MessagePassing::Stat::add().
dumpJSON()
void Arcane::Parallel::Stat::dumpJSON (JSONWriter & writer) override virtual
Outputs the statistics in JSON format.
Implements Arcane::Parallel::IStat.
Definition at line 183 of file arcane/src/arcane/core/parallel/Stat.cc.
References Arcane::Parallel::dumpJSON(), and Arcane::MessagePassing::Stat::statList().
enable()
void Arcane::Parallel::Stat::enable (bool is_enabled) inline override virtual
Enables or disables statistics.
If statistics are disabled, the call to add() has no effect.
Reimplemented from Arcane::MessagePassing::Stat.
Definition at line 108 of file arcane/src/arcane/core/parallel/Stat.cc.
mergeValues()
void Arcane::Parallel::Stat::mergeValues (ITraceMng * tm, Properties * p) override virtual
Merges the current values with those saved in p.
Implements Arcane::Parallel::IStat.
Definition at line 217 of file arcane/src/arcane/core/parallel/Stat.cc.
References _mergeStats(), Arcane::Properties::get(), Arcane::Properties::getInt32WithDefault(), and Arcane::ITraceMng::info().
print()
void Arcane::Parallel::Stat::print (ITraceMng * trace) override virtual
Prints the statistics to trace.
Implements Arcane::Parallel::IStat.
Definition at line 157 of file arcane/src/arcane/core/parallel/Stat.cc.
References Arcane::ITraceMng::info(), Arcane::MessagePassing::Stat::statList(), and Arcane::Convert::toInt64().
printCollective()
void Arcane::Parallel::Stat::printCollective (IParallelMng * pm) override virtual
Displays the statistics collectively.
Displays statistics common to all ranks associated with pm.
This operation is collective.
Implements Arcane::Parallel::IStat.
Definition at line 281 of file arcane/src/arcane/core/parallel/Stat.cc.
References _mergeStats(), Arcane::ITraceMng::info(), and Arcane::IParallelMng::traceMng().
saveValues()
void Arcane::Parallel::Stat::saveValues (ITraceMng * tm, Properties * p) override virtual
Saves the current values into p.
Implements Arcane::Parallel::IStat.
Definition at line 196 of file arcane/src/arcane/core/parallel/Stat.cc.
References _mergeStats(), Arcane::ITraceMng::info(), and Arcane::Properties::set().
toArccoreStat()
MP::IStat * Arcane::Parallel::Stat::toArccoreStat () inline override virtual
Implements Arcane::Parallel::IStat.
Definition at line 104 of file arcane/src/arcane/core/parallel/Stat.cc.
Member Data Documentation
m_previous_stat_map
CumulativeStatMap Arcane::Parallel::Stat::m_previous_stat_map private
Definition at line 116 of file arcane/src/arcane/core/parallel/Stat.cc.
The documentation for this class was generated from the following file:
arcane/src/arcane/core/parallel/Stat.cc