Arcane: Arcane::ICaseMng Class Reference
Arcane::ICaseMng Class Reference abstract
CaseOption
Case manager interface.
#include <arcane/core/ICaseMng.h>
Public Member Functions
virtual ~ICaseMng ()=default
Frees resources.
virtual IApplication * application ()=0
Associated application.
virtual ITraceMng * traceMng ()=0
Trace manager.
virtual IMeshMng * meshMng () const =0
Associated mesh manager.
virtual ISubDomain * subDomain ()=0
Sub-domain manager.
virtual ICaseDocument * caseDocument ()=0
XML document of the dataset (can be null if no dataset).
virtual ICaseDocumentFragment * caseDocumentFragment ()=0
Fragment of the XML Document associated with the dataset (can be null if no dataset).
virtual IPhysicalUnitSystem * physicalUnitSystem () const =0
Associated unit system.
virtual ICaseDocument * readCaseDocument (const String &filename, ByteConstArrayView bytes)=0
Reads the XML document of the dataset.
virtual void readOptions (bool is_phase1)=0
Reads the dataset options corresponding to the used modules.
virtual void printOptions ()=0
Prints the option values.
virtual void readFunctions ()=0
Reads the dataset tables.
virtual void registerOptions (ICaseOptions *)=0
Registers a list of dataset options.
virtual void unregisterOptions (ICaseOptions *)=0
Unregisters a list of dataset options.
virtual CaseOptionsCollection blocks () const =0
Collection of option blocks.
virtual ICaseFunction * findFunction (const String &name) const =0
Returns the function by name name or nullptr if none exists.
virtual CaseFunctionCollection functions ()=0
Returns the list of tables.
virtual void removeFunction (ICaseFunction *func, bool dofree)=0
Deletes a function.
virtual void removeFunction (ICaseFunction *func)=0
Deletes a function.
virtual void addFunction (ICaseFunction *func)=0
Adds the function func.
virtual void addFunction (Ref< ICaseFunction > func)=0
Adds the function func.
virtual void updateOptions (Real current_time, Real current_deltat, Integer current_iteration)=0
Updates the options based on a time-marching table.
virtual void setTreatWarningAsError (bool v)=0
Sets the way warnings are treated.
virtual bool isTreatWarningAsError () const =0
Indicates whether warnings in the dataset should be treated as errors and cause the code to stop.
virtual void setAllowUnkownRootElelement (bool v)=0
Sets the permission for unknown elements at the document root.
virtual bool isAllowUnkownRootElelement () const =0
Indicates whether unknown elements at the document root are allowed.
virtual IObservable * observable (eCaseMngEventType type)=0
Observable on the instance.
virtual Ref< ICaseMng > toReference ()=0
virtual ICaseMngInternal * _internalImpl ()=0
Internal implementation.
Detailed Description
Case manager interface.
This interface is managed by a reference counter and should not be explicitly destroyed.
Definition at line 56 of file ICaseMng.h.
Member Function Documentation
addFunction() [1/2]
virtual void Arcane::ICaseMng::addFunction (ICaseFunction * func) pure virtual
Adds the function func.
Addition can only be done during initialization. The caller remains the owner of the func instance and must remove it via removeFunction().
References addFunction().
Referenced by addFunction(), and addFunction().
addFunction() [2/2]
virtual void Arcane::ICaseMng::addFunction (Ref< ICaseFunction > func) pure virtual
Adds the function func.
Addition can only be done during initialization.
References addFunction().
functions()
virtual CaseFunctionCollection Arcane::ICaseMng::functions () pure virtual
Returns the list of tables.
The returned pointer is no longer valid as soon as the list of tables changes.
observable()
virtual IObservable * Arcane::ICaseMng::observable (eCaseMngEventType type) pure virtual
Observable on the instance.
The type of the observable is given by type
References observable().
Referenced by observable().
removeFunction() [1/2]
virtual void Arcane::ICaseMng::removeFunction (ICaseFunction * func) pure virtual
Deletes a function.
Deletes the function func. If this function is not in this list, nothing is done.
References removeFunction().
removeFunction() [2/2]
virtual void Arcane::ICaseMng::removeFunction (ICaseFunction * func, bool dofree) pure virtual
Deletes a function.
Deletes the function func. If this function is not in this list, nothing is done. If dofree is true, the delete operator is called on this function.
References removeFunction().
Referenced by removeFunction(), and removeFunction().
setTreatWarningAsError()
virtual void Arcane::ICaseMng::setTreatWarningAsError (bool v) pure virtual
Sets the way warnings are treated.
See also
isTreatWarningAsError().
References setTreatWarningAsError().
Referenced by setTreatWarningAsError().
updateOptions()
virtual void Arcane::ICaseMng::updateOptions (Real current_time, Real current_deltat, Integer current_iteration) pure virtual
Updates the options based on a time-marching table.
For each option dependent on a marching table, updates its value using the current_time parameter if it is a marching table with a real parameter, or current_iteration if it is a marching table with an integer parameter. If the option function has a non-zero coefficient ICaseFunction::deltatCoef(), the time used is equal to current_time + coef*current_deltat.
Parameters
current_time time used as parameter for the function
current_deltat deltat used as parameter for the function
current_iteration iteration used as parameter for the function
References updateOptions().
Referenced by Arcane::ModuleMaster::masterContinueInit(), Arcane::ModuleMaster::masterStartInit(), Arcane::ModuleMaster::timeLoopBegin(), and updateOptions().
The documentation for this class was generated from the following file:
ICaseMng.h