Alien: Alien::IIndexManager::IAbstractFamily Class Reference
Alien::IIndexManager::IAbstractFamily Class Reference abstract
Interface des familles abstraites pour l'indexation de items.
#include <core/alien/index_manager/IIndexManager.h>
Classes
class Item
Public Member Functions
virtual IAbstractFamily * clone () const =0
Construit un clone de cet objet.
virtual Arccore::Int32 maxLocalId () const =0
Identifiant maximal des localIds pour cette famille.
virtual void uniqueIdToLocalId (Arccore::ArrayView< Arccore::Int32 > localIds, Arccore::ConstArrayView< Arccore::Int64 > uniqueIds) const =0
Convertit des uniqueIds en localIds. Erreur fatale si un item n'est pas retrouvé
virtual Item item (Arccore::Int32 localId) const =0
Retourne un objet Item à partir de son localId.
virtual Arccore::SharedArray< Arccore::Integer > owners (Arccore::ConstArrayView< Arccore::Int32 > localIds) const =0
virtual Arccore::SharedArray< Arccore::Int64 > uids (Arccore::ConstArrayView< Arccore::Int32 > localIds) const =0
Retourne l'ensemble des uniqueIds d'un ensemble d'item décrits par leur localIds.
virtual Arccore::SharedArray< Arccore::Int32 > allLocalIds () const =0
Retourne l'ensemble des identifiants locaux de la famille.
Detailed Description
Interface des familles abstraites pour l'indexation de items.
Definition at line 32 of file IIndexManager.h.
Member Function Documentation
allLocalIds()
virtual Arccore::SharedArray< Arccore::Int32 > Alien::IIndexManager::IAbstractFamily::allLocalIds () const pure virtual
Retourne l'ensemble des identifiants locaux de la famille.
Implemented in Alien::AbstractFamily.
clone()
virtual IAbstractFamily * Alien::IIndexManager::IAbstractFamily::clone () const pure virtual
Construit un clone de cet objet.
Implemented in Alien::AbstractFamily.
Referenced by Alien::BasicIndexManager::keepAlive().
maxLocalId()
virtual Arccore::Int32 Alien::IIndexManager::IAbstractFamily::maxLocalId () const pure virtual
Identifiant maximal des localIds pour cette famille.
Implemented in Alien::AbstractFamily.
Referenced by Alien::BasicIndexManager::getIndexes(), and Alien::BasicIndexManager::getIndexes().
owners()
virtual Arccore::SharedArray< Arccore::Integer > Alien::IIndexManager::IAbstractFamily::owners (Arccore::ConstArrayView< Arccore::Int32 > localIds) const pure virtual
Retourne l'ensemble des owners (propriétaires) d'un ensemble d'item décrits par leur localIds
Referenced by Alien::BasicIndexManager::prepare().
The documentation for this class was generated from the following file:
IIndexManager.h