Arcane: Arcane::Accelerator::RunCommand Class Reference
Arcane::Accelerator::RunCommand Class Reference
Management of an accelerator command.
#include <arccore/common/accelerator/RunCommand.h>
Public Member Functions
RunCommand (RunCommand &&command)=delete
RunCommand (const RunCommand &)=delete
RunCommand & operator= (const RunCommand &)=delete
RunCommand & operator= (RunCommand &&)=delete
eExecutionPolicy executionPolicy () const
Command execution policy.
RunCommand & addTraceInfo (const TraceInfo &ti)
Sets the trace information.
RunCommand & addKernelName (const String &v)
Sets the kernel name.
RunCommand & addNbThreadPerBlock (Int32 v)
Sets the number of threads per block for accelerators.
RunCommand & addNbStride (Int32 v)
Sets the number of strides for loop decomposition on accelerator/.
Int32 nbStride () const
Number of loop decomposition strides.
const TraceInfo & traceInfo () const
Trace information.
const String & kernelName () const
Kernel name.
Int32 nbThreadPerBlock () const
void setParallelLoopOptions (const ParallelLoopOptions &opt)
Sets the multi-thread loop configuration.
const ParallelLoopOptions & parallelLoopOptions () const
Multi-thread loop configuration.
Protected Member Functions
RunCommand (const RunQueue &run_queue)
Friends
class ViewBuildInfo
template<typename T, Int32 Extent>
class LocalMemory
Impl::IReduceMemoryImpl * Impl::internalGetOrCreateReduceMemoryImpl (RunCommand *command)
RunCommand makeCommand (const RunQueue &run_queue)
Creates a command associated with the queue run_queue.
RunCommand makeCommand (const RunQueue *run_queue)
Creates a command associated with the queue run_queue.
RunCommand & operator<< (RunCommand &command, const TraceInfo &trace_info)
Displaying command information.
Detailed Description
Management of an accelerator command.
A command is associated with an execution queue (RunQueue) and its lifespan must not exceed that of the latter.
A command is an operation that will be executed on the accelerator associated with the RunQueue instance used when calling makeCommand(). On a GPU, this corresponds to a kernel.
For more information, refer to the section Compute Kernels (RunCommand).
Definition at line 46 of file arccore/src/common/arccore/common/accelerator/RunCommand.h.
Constructor & Destructor Documentation
~RunCommand()
Arcane::Accelerator::RunCommand::~RunCommand ()
Definition at line 44 of file RunCommand.cc.
RunCommand()
Arcane::Accelerator::RunCommand::RunCommand (const RunQueue & run_queue) explicit protected
Definition at line 34 of file RunCommand.cc.
Member Function Documentation
addKernelName()
RunCommand & Arcane::Accelerator::RunCommand::addKernelName (const String & v)
Sets the kernel name.
This name is used for tracing or debugging.
Definition at line 104 of file RunCommand.cc.
addNbStride()
RunCommand & Arcane::Accelerator::RunCommand::addNbStride (Int32 v)
Sets the number of strides for loop decomposition on accelerator/.
The default value is 1, which indicates that the loop is not decomposed. This method does nothing if the command is not executed on an accelerator. This value is only used for classical loops (RUNCOMMAND_LOOP()) or on entities (RUNCOMMAND_ENUMERATE()).
Warning
EXPERIMENTAL API. TO BE USED ONLY IN ARCANE
Definition at line 128 of file RunCommand.cc.
addNbThreadPerBlock()
RunCommand & Arcane::Accelerator::RunCommand::addNbThreadPerBlock (Int32 v)
Sets the number of threads per block for accelerators.
If the value v is zero, the default choice is used. If the value v is positive, its minimum valid value depends on the accelerator. Generally, it is at least 32.
Definition at line 114 of file RunCommand.cc.
addTraceInfo()
RunCommand & Arcane::Accelerator::RunCommand::addTraceInfo (const TraceInfo & ti)
Sets the trace information.
This information is used for tracing or debugging. The RUNCOMMAND_LOOP or RUNCOMMAND_ENUMERATE macros automatically call this method.
Definition at line 94 of file RunCommand.cc.
Referenced by operator<<.
executionPolicy()
eExecutionPolicy Arcane::Accelerator::RunCommand::executionPolicy () const
Command execution policy.
Execution policy of the command.
Definition at line 58 of file RunCommand.cc.
Referenced by Arcane::Accelerator::WorkGroupLoopRangeBase< IsCooperativeLaunch, IndexType_ >::setBlockSize().
kernelName()
const String & Arcane::Accelerator::RunCommand::kernelName () const
Kernel name.
Definition at line 76 of file RunCommand.cc.
nbStride()
Int32 Arcane::Accelerator::RunCommand::nbStride () const
Number of loop decomposition strides.
Definition at line 275 of file RunCommand.cc.
Referenced by Arcane::Accelerator::Impl::_applyGenericLoop(), and Arcane::Accelerator::impl::_applyItems().
nbThreadPerBlock()
Int32 Arcane::Accelerator::RunCommand::nbThreadPerBlock () const
Definition at line 85 of file RunCommand.cc.
parallelLoopOptions()
const ParallelLoopOptions & Arcane::Accelerator::RunCommand::parallelLoopOptions () const
Multi-thread loop configuration.
Definition at line 152 of file RunCommand.cc.
Referenced by Arcane::Accelerator::WorkGroupLoopRangeBase< IsCooperativeLaunch, IndexType_ >::setBlockSize().
setParallelLoopOptions()
void Arcane::Accelerator::RunCommand::setParallelLoopOptions (const ParallelLoopOptions & opt)
Sets the multi-thread loop configuration.
Definition at line 143 of file RunCommand.cc.
Referenced by Arcane::Accelerator::WorkGroupLoopRangeBase< IsCooperativeLaunch, IndexType_ >::setBlockSize().
traceInfo()
const TraceInfo & Arcane::Accelerator::RunCommand::traceInfo () const
Trace information.
Definition at line 67 of file RunCommand.cc.
Friends And Related Symbol Documentation
LocalMemory
template<typename T, Int32 Extent> friend class LocalMemory friend
Definition at line 52 of file arccore/src/common/arccore/common/accelerator/RunCommand.h.
makeCommand [1/2]
RunCommand makeCommand (const RunQueue & run_queue) friend
Creates a command associated with the queue run_queue.
Definition at line 289 of file arccore/src/common/arccore/common/accelerator/RunQueue.h.
makeCommand [2/2]
RunCommand makeCommand (const RunQueue * run_queue) friend
Creates a command associated with the queue run_queue.
Definition at line 299 of file arccore/src/common/arccore/common/accelerator/RunQueue.h.
References ARCCORE_CHECK_POINTER.
operator<<
RunCommand & operator<< (RunCommand & command, const TraceInfo & trace_info) friend
Displaying command information.
Definition at line 161 of file RunCommand.cc.
References addTraceInfo(), and operator<<.
Referenced by operator<<.
ViewBuildInfo
friend class ViewBuildInfo friend
Definition at line 51 of file arccore/src/common/arccore/common/accelerator/RunCommand.h.
The documentation for this class was generated from the following files:
arccore/src/common/arccore/common/accelerator/RunCommand.h
RunCommand.cc