Arcane: Arcane::MachineShMemWinBase Class Reference
Arcane::MachineShMemWinBase Class Reference
Class allowing the creation of a shared memory window between the subdomains of the same node.
#include <arcane/core/MachineShMemWinBase.h>
Public Member Functions
MachineShMemWinBase (IParallelMng *pm, Int64 sizeof_segment, Int32 sizeof_elem)
Constructor.
ConstArrayView< Int32 > machineRanks () const
Method to obtain the ranks that possess a segment in the window.
void barrier () const
Method to wait until all processes/threads on the node call this method to continue execution.
Span< std::byte > segmentView ()
Method to obtain a view of our segment.
Span< std::byte > segmentView (Int32 rank)
Method to obtain a view of the segment of another subdomain on the node.
Span< const std::byte > segmentConstView () const
Method to obtain a view of our segment.
Span< const std::byte > segmentConstView (Int32 rank) const
Method to obtain a view of the segment of another subdomain on the node.
void add (Span< const std::byte > elem)
Method to add elements into our segment.
void add ()
Method to be called by the subdomain(s) that do not wish to add elements to its segment.
void addToAnotherSegment (Int32 rank, Span< const std::byte > elem)
Method to add elements into the segment of another subdomain.
void addToAnotherSegment ()
Method to be called by the subdomain(s) that do not wish to add elements into the segment of another subdomain.
void reserve (Int64 new_nb_elem_segment_capacity)
Method to reserve memory space in our segment.
void reserve ()
Method to be called by the subdomain(s) that do not wish to reserve more memory for their segments.
void resize (Int64 new_nb_elem_segment)
Method to resize our segment.
void resize ()
Method to be called by the subdomain(s) that do not wish to resize their segments.
void shrink ()
Method to reduce the reserved memory space for the segments to the minimum necessary.
Private Attributes
IParallelMngInternal * m_pm_internal
Ref< MessagePassing::IMachineShMemWinBaseInternal > m_node_window_base
Int32 m_sizeof_elem
Detailed Description
Class allowing the creation of a shared memory window between the subdomains of the same node.
The segments of this window are not contiguous in memory and can be resized.
The add() method allows elements to be added iteratively.
Definition at line 52 of file MachineShMemWinBase.h.
Constructor & Destructor Documentation
MachineShMemWinBase()
Arcane::MachineShMemWinBase::MachineShMemWinBase (IParallelMng * pm, Int64 sizeof_segment, Int32 sizeof_elem)
Constructor.
Parameters
pm The parallelMng to use.
sizeof_segment The total size of our segment (in bytes / must be divisible by sizeof_elem).
sizeof_elem The size of an element in our segment (in bytes).
Definition at line 33 of file MachineShMemWinBase.cc.
Member Function Documentation
add() [1/2]
void Arcane::MachineShMemWinBase::add ()
Method to be called by the subdomain(s) that do not wish to add elements to its segment.
Collective call.
Note
The methods add(..) and addToAnotherSegment(..) must not be mixed.
See the documentation for add(Span<const std::byte> elem).
Definition at line 106 of file MachineShMemWinBase.cc.
add() [2/2]
void Arcane::MachineShMemWinBase::add (Span< const std::byte > elem)
Method to add elements into our segment.
Collective call.
Note
The methods add(..) and addToAnotherSegment(..) must not be mixed.
If the segment is too small, it will be resized.
Subdomains that do not wish to add elements can call the add() method without parameters or this method with an empty view.
Parameters
elem The elements to add.
Definition at line 97 of file MachineShMemWinBase.cc.
addToAnotherSegment() [1/2]
void Arcane::MachineShMemWinBase::addToAnotherSegment ()
Method to be called by the subdomain(s) that do not wish to add elements into the segment of another subdomain.
Collective call.
Note
The methods add(..) and addToAnotherSegment(..) must not be mixed.
See the documentation for addToAnotherSegment(Int32 rank, Span<const Type> elem).
Definition at line 124 of file MachineShMemWinBase.cc.
addToAnotherSegment() [2/2]
void Arcane::MachineShMemWinBase::addToAnotherSegment (Int32 rank, Span< const std::byte > elem)
Method to add elements into the segment of another subdomain.
Collective call.
Note
The methods add(..) and addToAnotherSegment(..) must not be mixed.
Two subdomains must not add elements to the same subdomain segment.
If the target segment is too small, it will be resized.
Subdomains that do not wish to add elements can call the addToAnotherSegment() method without parameters.
Parameters
rank The rank of the subdomain whose segment is to be modified.
elem The elements to add.
Definition at line 115 of file MachineShMemWinBase.cc.
barrier()
void Arcane::MachineShMemWinBase::barrier () const
Method to wait until all processes/threads on the node call this method to continue execution.
Definition at line 52 of file MachineShMemWinBase.cc.
machineRanks()
ConstArrayView< Int32 > Arcane::MachineShMemWinBase::machineRanks () const
Method to obtain the ranks that possess a segment in the window.
Non-collective call.
Returns
A view containing the rank IDs.
Definition at line 43 of file MachineShMemWinBase.cc.
reserve() [1/2]
void Arcane::MachineShMemWinBase::reserve ()
Method to be called by the subdomain(s) that do not wish to reserve more memory for their segments.
Collective call.
See the documentation for reserve(Int64 new_nb_elem_segment_capacity).
Definition at line 142 of file MachineShMemWinBase.cc.
reserve() [2/2]
void Arcane::MachineShMemWinBase::reserve (Int64 new_nb_elem_segment_capacity)
Method to reserve memory space in our segment.
Collective call.
This method does nothing if new_capacity is less than the memory space already allocated for the segment. For subdomains that do not wish to increase the available memory space for their segment, it is possible to set the new_capacity parameter to 0 or use the reserve() method (without arguments).
The reserved space will have a size greater than or equal to new_capacity.
This method does not resize the segment; you must always use the add() method to add elements.
To resize the segment, the resize(Int64 new_size) method is available.
Parameters
new_nb_elem_segment_capacity The requested new capacity (in number of elements, not in bytes).
Definition at line 133 of file MachineShMemWinBase.cc.
resize() [1/2]
void Arcane::MachineShMemWinBase::resize ()
Method to be called by the subdomain(s) that do not wish to resize their segments.
Collective call.
See the documentation for resize(Int64 new_nb_elem_segment).
Definition at line 160 of file MachineShMemWinBase.cc.
resize() [2/2]
void Arcane::MachineShMemWinBase::resize (Int64 new_nb_elem_segment)
Method to resize our segment.
Collective call.
If the provided size is less than the current size of the segment, elements located after the provided size will be deleted.
For subdomains that do not wish to resize their segment, it is possible to set the new_size argument to -1 or call the method resize() (without arguments).
Parameters
new_nb_elem_segment The new size (in number of elements, not in bytes).
Definition at line 151 of file MachineShMemWinBase.cc.
Referenced by Arcane::MachineShMemWinMemoryAllocator::reallocate().
segmentConstView() [1/2]
Span< const std::byte > Arcane::MachineShMemWinBase::segmentConstView () const
Method to obtain a view of our segment.
Non-collective call.
Returns
A view.
Definition at line 79 of file MachineShMemWinBase.cc.
segmentConstView() [2/2]
Span< const std::byte > Arcane::MachineShMemWinBase::segmentConstView (Int32 rank) const
Method to obtain a view of the segment of another subdomain on the node.
Non-collective call.
Parameters
rank The rank of the subdomain.
Returns
A view.
Definition at line 88 of file MachineShMemWinBase.cc.
segmentView() [1/2]
Span< std::byte > Arcane::MachineShMemWinBase::segmentView ()
Method to obtain a view of our segment.
Non-collective call.
Returns
A view.
Definition at line 61 of file MachineShMemWinBase.cc.
Referenced by Arcane::MachineShMemWinMemoryAllocator::deallocate(), and Arcane::MachineShMemWinMemoryAllocator::reallocate().
segmentView() [2/2]
Span< std::byte > Arcane::MachineShMemWinBase::segmentView (Int32 rank)
Method to obtain a view of the segment of another subdomain on the node.
Non-collective call.
Parameters
rank The rank of the subdomain.
Returns
A view.
Definition at line 70 of file MachineShMemWinBase.cc.
shrink()
void Arcane::MachineShMemWinBase::shrink ()
Method to reduce the reserved memory space for the segments to the minimum necessary.
Collective call.
Definition at line 169 of file MachineShMemWinBase.cc.
Member Data Documentation
m_node_window_base
Ref<MessagePassing::IMachineShMemWinBaseInternal> Arcane::MachineShMemWinBase::m_node_window_base private
Definition at line 254 of file MachineShMemWinBase.h.
m_pm_internal
IParallelMngInternal* Arcane::MachineShMemWinBase::m_pm_internal private
Definition at line 253 of file MachineShMemWinBase.h.
m_sizeof_elem
Int32 Arcane::MachineShMemWinBase::m_sizeof_elem private
Definition at line 255 of file MachineShMemWinBase.h.
The documentation for this class was generated from the following files:
MachineShMemWinBase.h
MachineShMemWinBase.cc