Arcane: Arcane::AbstractArrayBase Class Reference
Arcane::AbstractArrayBase Class Reference
Internal base class for arrays.
#include </__w/arcaneframework.github.io/arcaneframework.github.io/framework/arccore/src/common/arccore/common/AbstractArray.h>
Inherited by Arcane::AbstractArray< DataType >, Arcane::AbstractArray< GroupIndexInfo >, Arcane::AbstractArray< Arcane::UniqueArray< Arcane::AMRPatchPosition > >, Arcane::AbstractArray< Arcane::AMRPatchPosition >, Arcane::AbstractArray< CartCoord >, Arcane::AbstractArray< ItemInternal * >, Arcane::AbstractArray< Cell >, Arcane::AbstractArray< Arcane::IItemFamily * >, Arcane::AbstractArray< Arcane::Ref< Arcane::Accelerator::RunQueue > >, Arcane::AbstractArray< Arcane::Accelerator::DeviceInfo >, Arcane::AbstractArray< std::byte >, Arcane::AbstractArray< unsigned int >, Arcane::AbstractArray< Arcane::Accelerator::Impl::RunCommandImpl * >, Arcane::AbstractArray< Arcane::Accelerator::RunQueue >, Arcane::AbstractArray< Int32 * >, Arcane::AbstractArray< Arcane::SharedArray< Integer > >, Arcane::AbstractArray< Arcane::Ref< Arcane::IParallelMng > >, Arcane::AbstractArray< Arcane::AlephMatrix * >, Arcane::AbstractArray< Arcane::AlephKernelArguments * >, Arcane::AbstractArray< Arcane::AlephKernelResults * >, Arcane::AbstractArray< AlephInt >, Arcane::AbstractArray< Arcane::MessagePassing::Request >, Arcane::AbstractArray< double >, Arcane::AbstractArray< Arcane::UniqueArray< Arcane::Alina::GaussSeidelRelaxation::parallel_sweep::task > >, Arcane::AbstractArray< Arcane::Alina::GaussSeidelRelaxation::parallel_sweep::task >, Arcane::AbstractArray< Arcane::UniqueArray< ptrdiff_t > >, Arcane::AbstractArray< ptrdiff_t >, Arcane::AbstractArray< Arcane::UniqueArray< value_type > >, Arcane::AbstractArray< value_type >, Arcane::AbstractArray< Arcane::UniqueArray< Arcane::Alina::Impl::ILUSolver< BuiltinBackend< value_type, col_type, ptr_type > >::sptr_solve::task > >, Arcane::AbstractArray< Arcane::Alina::Impl::ILUSolver< BuiltinBackend< value_type, col_type, ptr_type > >::sptr_solve::task >, Arcane::AbstractArray< Arcane::UniqueArray< DataType > >, Arcane::AbstractArray< Arcane::UniqueArray2< DataType > >, Arcane::AbstractArray< Arcane::AnyItem::LinkFamilyInternal::LinkData >, Arcane::AbstractArray< Arcane::ArrayView< DataType > >, Arcane::AbstractArray< Arcane::IVariable * >, Arcane::AbstractArray< Arcane::Array2View< DataType > >, Arcane::AbstractArray< Arcane::IPrimaryMesh * >, Arcane::AbstractArray< Arcane::ArcaneInitialPartitioner::TrueOwnerInfo >, Arcane::AbstractArray< float >, Arcane::AbstractArray< Arcane::ArcaneMainBatch::SessionExec::SubInfo * >, Arcane::AbstractArray< Arcane::ITimeStats * >, Arcane::AbstractArray< Arcane::AxlOptionsBuilder::OneOption >, Arcane::AbstractArray< Arcane::BinaryTree::TreeNode >, Arcane::AbstractArray< Arcane::CartesianConnectivity::Index >, Arcane::AbstractArray< Arcane::CartesianConnectivity::Permutation >, Arcane::AbstractArray< Arcane::ItemGroupT< Cell > >, Arcane::AbstractArray< Arcane::ICartesianMeshPatch * >, Arcane::AbstractArray< Arcane::Ref< Arcane::CartesianMeshPatch > >, Arcane::AbstractArray< Arcane::CaseOptionError >, Arcane::AbstractArray< Arcane::ICaseOptions * >, Arcane::AbstractArray< Arcane::ICaseOptionList * >, Arcane::AbstractArray< Arcane::String >, Arcane::AbstractArray< Arcane::ReferenceCounter< Arcane::ICaseOptions > >, Arcane::AbstractArray< InterfaceType * >, Arcane::AbstractArray< Arcane::Ref< InterfaceType > >, Arcane::AbstractArray< Arcane::IDataCompressor * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IDataCompressor > >, Arcane::AbstractArray< Arcane::ICaseMeshService * >, Arcane::AbstractArray< Arcane::Ref< Arcane::ICaseMeshService > >, Arcane::AbstractArray< Arcane::ItemGroup >, Arcane::AbstractArray< Arcane::IDirectExecution * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IDirectExecution > >, Arcane::AbstractArray< Arcane::IMeshPartitioner * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IMeshPartitioner > >, Arcane::AbstractArray< Arcane::ITimeLoopService * >, Arcane::AbstractArray< Arcane::Ref< Arcane::ITimeLoopService > >, Arcane::AbstractArray< Arcane::IUnitTest * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IUnitTest > >, Arcane::AbstractArray< Arcane::IXmlUnitTest * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IXmlUnitTest > >, Arcane::AbstractArray< Arcane::SmallVariant >, Arcane::AbstractArray< Arcane::impl::CartesianItemDirectionInfo >, Arcane::AbstractArray< Arcane::StoreIProxyItemVariable >, Arcane::AbstractArray< Arcane::VariableSyncInfo >, Arcane::AbstractArray< Arcane::Item >, Arcane::AbstractArray< Arcane::DumpWEnsight7::EnsightPart >, Arcane::AbstractArray< Arcane::Ref< Arcane::OStringStream > >, Arcane::AbstractArray< Arcane::Cell >, Arcane::AbstractArray< Arcane::EventObserverBase * >, Arcane::AbstractArray< Arcane::SharedArray< Int32 > >, Arcane::AbstractArray< KeyTypeValue >, Arcane::AbstractArray< Arcane::HashTableBaseT::HashData * >, Arcane::AbstractArray< Arcane::UniqueArray * >, Arcane::AbstractArray< Arcane::HashTableMapT::Data * >, Arcane::AbstractArray< Arcane::Hdf5VariableReaderHelper * >, Arcane::AbstractArray< Arcane::Hdf5VariableInfoBase * >, Arcane::AbstractArray< Arcane::Hdf5VariableReaderHelper::TimeVariableInfoBase * >, Arcane::AbstractArray< Arcane::Hdf5VariableReaderHelper2::TimeVariableInfoBase * >, Arcane::AbstractArray< TimePathPair >, Arcane::AbstractArray< Arcane::Hdf5VariableWriterHelper * >, Arcane::AbstractArray< Arcane::IAlephVector * >, Arcane::AbstractArray< Arcane::IAlephMatrix * >, Arcane::AbstractArray< Arcane::ReferenceCounter< Arcane::Internal::IServiceFactory2 > >, Arcane::AbstractArray< Arcane::ItemAllocationInfo::FamilyInfo >, Arcane::AbstractArray< Arcane::ItemAllocationInfo::ConnectedFamilyInfo >, Arcane::AbstractArray< Arcane::ItemInternal * >, Arcane::AbstractArray< std::set< Int64 > >, Arcane::AbstractArray< Arcane::UniqueArray< Int32 > >, Arcane::AbstractArray< Arcane::ItemGroupImpl * >, Arcane::AbstractArray< Arcane::ItemTypeInfo * >, Arcane::AbstractArray< Arcane::LegacyMeshBuilder::MeshBuildInfo >, Arcane::AbstractArray< int >, Arcane::AbstractArray< Arcane::MEDMeshReader::MEDToArcaneItemInfo >, Arcane::AbstractArray< Arcane::MEDMeshReader::MEDGroupInfo >, Arcane::AbstractArray< med_int >, Arcane::AbstractArray< Arcane::MatVec::AMGLevel * >, Arcane::AbstractArray< Arcane::Span< Arcane::Materials::ConstituentItemLocalId > >, Arcane::AbstractArray< Arcane::Materials::ConstituentItemLocalId >, Arcane::AbstractArray< Arcane::Materials::ConstituentItemSharedInfo >, Arcane::AbstractArray< Arcane::Materials::ConstituentItemIndex >, Arcane::AbstractArray< Arcane::Materials::MatVarIndex >, Arcane::AbstractArray< Arcane::Materials::CopyBetweenDataInfo >, Arcane::AbstractArray< PrivatePartType * >, Arcane::AbstractArray< ContainerViewType >, Arcane::AbstractArray< Arcane::Materials::IMeshEnvironment * >, Arcane::AbstractArray< Arcane::Materials::IMeshMaterial * >, Arcane::AbstractArray< Arcane::Materials::MeshMaterial * >, Arcane::AbstractArray< Arcane::Materials::MeshEnvironmentBuildInfo::MatInfo >, Arcane::AbstractArray< Arcane::Materials::IMeshMaterialVariable * >, Arcane::AbstractArray< Arcane::Materials::MeshMaterialInfo * >, Arcane::AbstractArray< Arcane::Materials::IMeshComponent * >, Arcane::AbstractArray< Arcane::Materials::MeshEnvironment * >, Arcane::AbstractArray< Arcane::Materials::IMeshBlock * >, Arcane::AbstractArray< Arcane::Materials::MeshBlock * >, Arcane::AbstractArray< Arcane::Materials::MeshMaterialVariableIndexer * >, Arcane::AbstractArray< Arcane::Materials::MaterialModifierOperation * >, Arcane::AbstractArray< Arcane::Span< std::byte > >, Arcane::AbstractArray< Arcane::VariableRef * >, Arcane::AbstractArray< Arcane::Materials::MeshMaterialVariableDependInfo >, Arcane::AbstractArray< Arcane::VariableDependInfo >, Arcane::AbstractArray< Arcane::UniqueArray< Arcane::Materials::MatVarIndex > >, Arcane::AbstractArray< Arcane::Materials::MeshMaterialVariable * >, Arcane::AbstractArray< Arcane::Materials::MultiBufferMeshMaterialSynchronizeBuffer::BufferInfo >, Arcane::AbstractArray< Arcane::Materials::OneBufferMeshMaterialSynchronizeBuffer::BufferInfo >, Arcane::AbstractArray< Arcane::ICaseMeshMasterService * >, Arcane::AbstractArray< Arcane::Ref< Arcane::ICaseMeshMasterService > >, Arcane::AbstractArray< Arcane::IMesh * >, Arcane::AbstractArray< Arcane::MeshHandle >, Arcane::AbstractArray< Arcane::SharedArray< Arcane::Cell > >, Arcane::AbstractArray< eMarkCellWithConstraint >, Arcane::AbstractArray< Arcane::Ref< Arcane::IMeshReader > >, Arcane::AbstractArray< Arcane::MessagePassing::HybridParallelMng * >, Arcane::AbstractArray< Arcane::MessagePassing::ISerializeMessage * >, Arcane::AbstractArray< MPI_Win >, Arcane::AbstractArray< Arcane::Span< const std::byte > >, Arcane::AbstractArray< MPI_Status >, Arcane::AbstractArray< Arcane::MessagePassing::Mpi::MpiSerializeDispatcher::SerializeSubRequest * >, Arcane::AbstractArray< Arcane::Ref< Arcane::MessagePassing::ISerializeMessage > >, Arcane::AbstractArray< Arcane::MessagePassing::SharedMemoryMessageQueue::SubQueue * >, Arcane::AbstractArray< Arcane::MessagePassing::SharedMemoryMessageRequest * >, Arcane::AbstractArray< Type >, Arcane::AbstractArray< Arcane::MessagePassing::SharedMemoryParallelDispatch< DataType > * >, Arcane::AbstractArray< Arcane::MessagePassing::SharedMemoryParallelDispatchBase * >, Arcane::AbstractArray< Arcane::MessagePassing::internal::SerializeMessageList::ProbeInfo >, Arcane::AbstractArray< idx_t >, Arcane::AbstractArray< MPI_Request >, Arcane::AbstractArray< MPI_Datatype >, Arcane::AbstractArray< Arcane::Real3 >, Arcane::AbstractArray< Arcane::MshMeshReader::MeshV4EntitiesNodes >, Arcane::AbstractArray< Arcane::MshMeshReader::MeshV4EntitiesWithNodes >, Arcane::AbstractArray< Arcane::MshMeshReader::MeshV4ElementsBlock >, Arcane::AbstractArray< Arcane::UniqueArray< Arcane::MshMeshReader::MeshPhysicalName > >, Arcane::AbstractArray< Arcane::MshMeshReader::MeshPhysicalName >, Arcane::AbstractArray< Arcane::MshMeshWriter::PhysicalTagInfo >, Arcane::AbstractArray< Arcane::MshMeshWriter::ArcaneToMshTypeInfo >, Arcane::AbstractArray< Arcane::MshMeshWriter::EntityInfo >, Arcane::AbstractArray< Arcane::ItemTypeId >, Arcane::AbstractArray< Arcane::MshParallelMeshReader::MshToArcaneTypeInfo >, Arcane::AbstractArray< Arcane::MshParallelMeshReader::MshElementBlock >, Arcane::AbstractArray< Arcane::MshParallelMeshReader::MshNodeBlock >, Arcane::AbstractArray< Arcane::MutableMemoryView >, Arcane::AbstractArray< Arcane::NodeDirectionMng::ItemDirectionInfo >, Arcane::AbstractArray< Arcane::Node >, Arcane::AbstractArray< Arcane::Face >, Arcane::AbstractArray< Arcane::IAlephTopology * >, Arcane::AbstractArray< long_long >, Arcane::AbstractArray< KeyType >, Arcane::AbstractArray< Arcane::SharedArray< Arcane::ItemLocalId > >, Arcane::AbstractArray< Arcane::ItemLocalId >, Arcane::AbstractArray< Arcane::SerializeMessage * >, Arcane::AbstractArray< Arcane::ParameterList::Impl::NameValuePair >, Arcane::AbstractArray< Arcane::ParameterListWithCaseOption::Impl::NameValuePair >, Arcane::AbstractArray< Arcane::Ref< Arcane::ParameterOptionAddrPart > >, Arcane::AbstractArray< Arcane::ParameterOptionElement >, Arcane::AbstractArray< Arcane::IPropertyType * >, Arcane::AbstractArray< Arcane::PropertyImpl::PropertyKeyValues::NameValuePair >, Arcane::AbstractArray< Arcane::IServiceFactoryInfo * >, Arcane::AbstractArray< Arcane::ModuleFactoryReference >, Arcane::AbstractArray< Arcane::UniqueArray< Real > >, Arcane::AbstractArray< Arcane::IMeshPartitionerBase * >, Arcane::AbstractArray< Arcane::ConstArrayView< Int32 > >, Arcane::AbstractArray< Arcane::ConstArrayView< Int64 > >, Arcane::AbstractArray< Arcane::ConstArrayView< Real > >, Arcane::AbstractArray< Arcane::SharedArray< Int64 > >, Arcane::AbstractArray< Arcane::SharedArray< Real > >, Arcane::AbstractArray< Arcane::UnitTestServiceAdapter::TestFuncInfo >, Arcane::AbstractArray< Arcane::VariableDiff::DiffInfo >, Arcane::AbstractArray< Arcane::VariableReaderMng::VarReadInfo >, Arcane::AbstractArray< Arcane::INumericDataInternal * >, Arcane::AbstractArray< CompareStatus >, Arcane::AbstractArray< unsigned char >, Arcane::AbstractArray< Arcane::MeshVariableScalarRefT< Cell, Real3 > * >, Arcane::AbstractArray< Arcane::Ref< Arcane::VtkHdfV2DataWriter::ItemGroupCollectiveInfo > >, Arcane::AbstractArray< Arcane::Ref< Arcane::GatherGroupInfo > >, Arcane::AbstractArray< Arcane::Ref< Arcane::impl::IGenericReader > >, Arcane::AbstractArray< Arcane::impl::MshMeshGenerationInfo::MshEntitiesNodes >, Arcane::AbstractArray< Arcane::impl::MshMeshGenerationInfo::MshPeriodicOneInfo >, Arcane::AbstractArray< Arcane::mesh::DynamicMesh * >, Arcane::AbstractArray< Arcane::mesh::ItemFamily * >, Arcane::AbstractArray< Arcane::IItemFamilyModifier * >, Arcane::AbstractArray< Arcane::IExtraGhostCellsBuilder * >, Arcane::AbstractArray< Arcane::IExtraGhostItemsBuilder * >, Arcane::AbstractArray< Arcane::IExtraGhostParticlesBuilder * >, Arcane::AbstractArray< Arcane::ItemUniqueId >, Arcane::AbstractArray< Arcane::mesh::IncrementalItemConnectivity * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IIncrementalItemSourceConnectivity > >, Arcane::AbstractArray< Arcane::Ref< Arcane::IIncrementalItemTargetConnectivity > >, Arcane::AbstractArray< Arcane::mesh::ItemConnectivitySelector * >, Arcane::AbstractArray< Arcane::IGraph2 * >, Arcane::AbstractArray< Arcane::IItemFamilySerializeStepFactory * >, Arcane::AbstractArray< Arcane::mesh::ItemInfoMultiList::MyInfo >, Arcane::AbstractArray< Arcane::mesh::ItemSharedInfoWithType * >, Arcane::AbstractArray< Arcane::mesh::ItemGroupsSerializer2 * >, Arcane::AbstractArray< Arcane::IItemFamilySerializeStep * >, Arcane::AbstractArray< Arcane::mesh::ItemsOwnerBuilderImpl::ItemOwnerInfo >, Arcane::AbstractArray< Arcane::TiedNode >, Arcane::AbstractArray< Arcane::TiedFace >, Arcane::AbstractArray< Arcane::mesh::TiedInterfaceExchanger::OneSubDomainInfo * >, Arcane::AbstractArray< Arcane::mesh::TiedInterfaceFace * >, Arcane::AbstractArray< Arcane::mesh::TiedInterface * >, Arcane::AbstractArray< Arcane::ItemGroupT< Face > >, Arcane::AbstractArray< Arcane::AlephVector * >, Arcane::AbstractArray< Arcane::AlephParams * >, Arcane::AbstractArray< ArcaneTest::AlephSolver * >, Arcane::AbstractArray< ArcaneTest::AlephMultiTest::SolverBuildInfo >, Arcane::AbstractArray< ArcaneTest::AlephTestScheme * >, Arcane::AbstractArray< Arcane::Ref< ArcaneTest::AlephTestScheme > >, Arcane::AbstractArray< Arcane::IMeshBuilder * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IMeshBuilder > >, Arcane::AbstractArray< Arcane::ICaseMeshReader * >, Arcane::AbstractArray< Arcane::Ref< Arcane::ICaseMeshReader > >, Arcane::AbstractArray< Arcane::IMeshSubdivider * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IMeshSubdivider > >, Arcane::AbstractArray< Arcane::ICheckpointWriter * >, Arcane::AbstractArray< Arcane::Ref< Arcane::ICheckpointWriter > >, Arcane::AbstractArray< Arcane::IPostProcessorWriter * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IPostProcessorWriter > >, Arcane::AbstractArray< Arcane::IExternalPlugin * >, Arcane::AbstractArray< Arcane::Ref< Arcane::IExternalPlugin > >, and Arcane::AbstractArray< T >.
Public Member Functions
IMemoryAllocator * allocator () const
MemoryAllocationOptions allocationOptions () const
void setDebugName (const String &name)
Sets the array name for debug information.
String debugName () const
Debug name (null if no name specified).
Protected Member Functions
virtual bool _isUseOwnMetaData () const
Indicates if m_md refers to m_meta_data.
void _swapMetaData (AbstractArrayBase &rhs)
void _copyMetaData (const AbstractArrayBase &rhs)
void _allocateMetaData ()
void _deallocateMetaData (ArrayMetaData *md)
void _checkValidSharedArray ()
Static Protected Member Functions
static constexpr RunQueue * _nullRunQueue ()
Explicit method for a null RunQueue.
Protected Attributes
ArrayMetaData * m_md = nullptr
ArrayMetaData m_meta_data
Private Member Functions
void _checkSetUseOwnMetaData ()
Detailed Description
Internal base class for arrays.
This class only manages metadata for arrays such as the number of elements or capacity.
m_md is a pointer containing the array's metadata. If the array is shared (SharedArray, SharedArray2), then this pointer is dynamically allocated and in this case _isUseOwnMetaData() must return false. If the array is not shared (UniqueArray or UniqueArray2), then the metadata is kept directly in the array instance to avoid unnecessary allocations and m_md then points to m_meta_data. In all cases, you must not use m_meta_data directly, but always go through m_md.
Definition at line 47 of file AbstractArray.h.
Constructor & Destructor Documentation
AbstractArrayBase()
Arcane::AbstractArrayBase::AbstractArrayBase () inline
Definition at line 51 of file AbstractArray.h.
Member Function Documentation
_allocateMetaData()
void Arcane::AbstractArrayBase::_allocateMetaData () inline protected
Definition at line 116 of file AbstractArray.h.
_checkSetUseOwnMetaData()
void Arcane::AbstractArrayBase::_checkSetUseOwnMetaData () inline private
Definition at line 151 of file AbstractArray.h.
_checkValidSharedArray()
void Arcane::AbstractArrayBase::_checkValidSharedArray () inline protected
Definition at line 141 of file AbstractArray.h.
_copyMetaData()
void Arcane::AbstractArrayBase::_copyMetaData (const AbstractArrayBase & rhs) inline protected
Definition at line 107 of file AbstractArray.h.
_deallocateMetaData()
void Arcane::AbstractArrayBase::_deallocateMetaData (ArrayMetaData * md) inline protected
Definition at line 133 of file AbstractArray.h.
_isUseOwnMetaData()
virtual bool Arcane::AbstractArrayBase::_isUseOwnMetaData () const inline protected virtual
Indicates if m_md refers to m_meta_data.
This is the case for UniqueArray and UniqueArray2 but not for SharedArray and SharedArray2.
Reimplemented in Arcane::SharedArray2< T >, Arcane::SharedArray2< BFloat16 >, Arcane::SharedArray2< BFloat16 >, Arcane::SharedArray2< bool >, Arcane::SharedArray2< bool >, Arcane::SharedArray2< Byte >, Arcane::SharedArray2< Byte >, Arcane::SharedArray2< Float16 >, Arcane::SharedArray2< Float16 >, Arcane::SharedArray2< Float32 >, Arcane::SharedArray2< Float32 >, Arcane::SharedArray2< Int16 >, Arcane::SharedArray2< Int16 >, Arcane::SharedArray2< Int32 >, Arcane::SharedArray2< Int32 >, Arcane::SharedArray2< Int64 >, Arcane::SharedArray2< Int64 >, Arcane::SharedArray2< Int8 >, Arcane::SharedArray2< Int8 >, Arcane::SharedArray2< Integer >, Arcane::SharedArray2< Integer >, Arcane::SharedArray2< Pointer >, Arcane::SharedArray2< Pointer >, Arcane::SharedArray2< Real >, Arcane::SharedArray2< Real >, Arcane::SharedArray2< Real2 >, Arcane::SharedArray2< Real2 >, Arcane::SharedArray2< Real2x2 >, Arcane::SharedArray2< Real2x2 >, Arcane::SharedArray2< Real3 >, Arcane::SharedArray2< Real3 >, Arcane::SharedArray2< Real3x3 >, Arcane::SharedArray2< Real3x3 >, Arcane::SharedArray2< String >, Arcane::SharedArray2< String >, Arcane::SharedArray2< UChar >, Arcane::SharedArray2< UChar >, Arcane::SharedArray< T >, Arcane::SharedArray< AlephInt >, Arcane::SharedArray< Arcane::Cell >, Arcane::SharedArray< Arcane::IItemFamily * >, Arcane::SharedArray< Arcane::ItemInternal * >, Arcane::SharedArray< Arcane::ItemLocalId >, Arcane::SharedArray< Arcane::ItemUniqueId >, Arcane::SharedArray< Arcane::mesh::TiedInterfaceFace * >, Arcane::SharedArray< Arcane::SharedArray< Int32 > >, Arcane::SharedArray< Arcane::TiedFace >, Arcane::SharedArray< Arcane::TiedNode >, Arcane::SharedArray< BFloat16 >, Arcane::SharedArray< BFloat16 >, Arcane::SharedArray< bool >, Arcane::SharedArray< bool >, Arcane::SharedArray< Byte >, Arcane::SharedArray< Byte >, Arcane::SharedArray< DataType >, Arcane::SharedArray< EdgeTypeConstRef >, Arcane::SharedArray< EdgeTypeConstRef >, Arcane::SharedArray< EdgeTypeRef >, Arcane::SharedArray< EdgeTypeRef >, Arcane::SharedArray< Float16 >, Arcane::SharedArray< Float16 >, Arcane::SharedArray< Float32 >, Arcane::SharedArray< Float32 >, Arcane::SharedArray< Int16 >, Arcane::SharedArray< Int16 >, Arcane::SharedArray< Int32 >, Arcane::SharedArray< Int32 >, Arcane::SharedArray< Int64 >, Arcane::SharedArray< Int64 >, Arcane::SharedArray< Int8 >, Arcane::SharedArray< Int8 >, Arcane::SharedArray< Integer >, Arcane::SharedArray< Integer >, Arcane::SharedArray< Pointer >, Arcane::SharedArray< Pointer >, Arcane::SharedArray< Real >, Arcane::SharedArray< Real >, Arcane::SharedArray< Real2 >, Arcane::SharedArray< Real2 >, Arcane::SharedArray< Real2x2 >, Arcane::SharedArray< Real2x2 >, Arcane::SharedArray< Real3 >, Arcane::SharedArray< Real3 >, Arcane::SharedArray< Real3x3 >, Arcane::SharedArray< Real3x3 >, Arcane::SharedArray< std::set< Int64 > >, Arcane::SharedArray< String >, Arcane::SharedArray< String >, Arcane::SharedArray< UChar >, Arcane::SharedArray< UChar >, Arcane::SharedArray< VertexTypeConstRef >, Arcane::SharedArray< VertexTypeConstRef >, Arcane::SharedArray< VertexTypeRef >, Arcane::SharedArray< VertexTypeRef >, Arcane::SharedArray< XmlNode >, Arcane::SharedArray< XmlNode >, Arccore::SharedArray2< T >, and Arccore::SharedArray< T >.
Definition at line 92 of file AbstractArray.h.
_nullRunQueue()
constexpr RunQueue * Arcane::AbstractArrayBase::_nullRunQueue () inline static constexpr protected
Explicit method for a null RunQueue.
Definition at line 84 of file AbstractArray.h.
Referenced by Arcane::AbstractArray< DataType >::_checkFreeMemory(), Arcane::AbstractArray< DataType >::_initFromSpan(), and Arcane::AbstractArray< DataType >::_move().
_swapMetaData()
void Arcane::AbstractArrayBase::_swapMetaData (AbstractArrayBase & rhs) inline protected
Definition at line 99 of file AbstractArray.h.
allocationOptions()
MemoryAllocationOptions Arcane::AbstractArrayBase::allocationOptions () const inline
Definition at line 63 of file AbstractArray.h.
allocator()
IMemoryAllocator * Arcane::AbstractArrayBase::allocator () const inline
Definition at line 59 of file AbstractArray.h.
debugName()
String Arcane::AbstractArrayBase::debugName () const
Debug name (null if no name specified).
Definition at line 330 of file arccore/src/common/arccore/common/Array.cc.
setDebugName()
void Arcane::AbstractArrayBase::setDebugName (const String & name)
Sets the array name for debug information.
This name can be used, for example, for listing displays.
Definition at line 321 of file arccore/src/common/arccore/common/Array.cc.
Member Data Documentation
m_md
ArrayMetaData* Arcane::AbstractArrayBase::m_md = nullptr protected
Definition at line 78 of file AbstractArray.h.
m_meta_data
ArrayMetaData Arcane::AbstractArrayBase::m_meta_data protected
Definition at line 79 of file AbstractArray.h.
The documentation for this class was generated from the following files:
AbstractArray.h
arccore/src/common/arccore/common/Array.cc