Arcane: Arcane::IVariable Class Reference
Arcane::IVariable Class Reference abstract
Interface of a variable.
#include <arcane/core/IVariable.h>
Public Types
enum eDependType { DPT_PreviousTime , DPT_CurrentTime }
Dependency Type.
enum {
PNoDump = (1 << 0) , PNoNeedSync = (1 << 1) , PHasTrace = (1 << 2) , PSubDomainDepend = (1 << 3) ,
PSubDomainPrivate = (1 << 4) , PExecutionDepend = (1 << 5) , PPrivate = (1 << 6) , PTemporary = (1 << 7) ,
PNoRestore = (1 << 8) , PNoExchange = (1 << 9) , PPersistant = (1 << 10) , PNoReplicaSync = (1 << 11) ,
PInShMem = (1 << 12) , PDumpNull = (1 << 13)
}
Properties of a variable.
Public Member Functions
virtual ~IVariable ()=default
Frees resources.
virtual ISubDomain * subDomain ()=0
Subdomain associated with the variable (TODO deprecate end of 2023).
virtual IVariableMng * variableMng () const =0
Variable manager associated with the variable.
virtual Real allocatedMemory () const =0
Memory size (in Bytes) used by the variable.
virtual String name () const =0
Variable name.
virtual String fullName () const =0
Full variable name (with family prefix).
virtual eDataType dataType () const =0
Data type managed by the variable (Real, Integer, ...).
virtual eItemKind itemKind () const =0
Kind of mesh entities on which the variable is based.
virtual Integer dimension () const =0
Dimension of the variable.
virtual Integer multiTag () const =0
Indicates if the variable is a multi-sized array.
virtual Integer nbElement () const =0
Number of elements of the variable.
virtual int property () const =0
Returns the properties of the variable.
virtual void notifyReferencePropertyChanged ()=0
virtual void addVariableRef (VariableRef *var_ref)=0
Adds a reference to this variable.
virtual void removeVariableRef (VariableRef *var_ref)=0
Removes a reference to this variable.
virtual VariableRef * firstReference () const =0
First reference (or null) on this variable.
virtual Integer nbReference () const =0
Number of references on this variable.
virtual void setTraceInfo (Integer id, eTraceType tt)=0
virtual void resize (Integer new_size)=0
Sets the number of elements for an array variable.
virtual void resizeFromGroup ()=0
Sets the number of elements for a mesh variable.
virtual void shrinkMemory ()=0
Frees any additional memory allocated for the data.
virtual void setAllocationInfo (const DataAllocationInfo &v)=0
Sets allocation information.
virtual DataAllocationInfo allocationInfo () const =0
Allocation information.
virtual bool initialize (const ItemGroup &group, const String &value)=0
Initializes the variable on a group.
Verification Operations
virtual Int32 checkIfSync (Integer max_print=0)=0
Checks if the variable is properly synchronized.
virtual Int32 checkIfSame (IDataReader *reader, Integer max_print, bool compare_ghost)=0
Checks that the variable is identical to a reference value.
virtual Int32 checkIfSameOnAllReplica (Integer max_print=0)=0
Checks if the variable has the same values on all replicas.
virtual void synchronize ()=0
Synchronizes the variable.
virtual void synchronize (Int32ConstArrayView local_ids)
Synchronizes the variable on a list of entities.
virtual IMesh * mesh () const =0
Mesh associated with the variable.
virtual MeshHandle meshHandle () const =0
Mesh associated with the variable.
virtual ItemGroup itemGroup () const =0
Associated mesh group.
virtual String itemGroupName () const =0
Name of the associated entity group.
virtual IItemFamily * itemFamily () const =0
Associated entity family.
virtual String itemFamilyName () const =0
Name of the associated family (null if none).
virtual String meshName () const =0
Name of the associated mesh (null if none).
virtual VariableMetaData * createMetaData () const =0
Creates an instance containing the variable's metadata.
virtual Ref< VariableMetaData > createMetaDataRef () const =0
Creates an instance containing the variable's metadata.
virtual void syncReferences ()=0
Synchronizes references.
virtual void setUsed (bool v)=0
Sets the usage state of the variable.
virtual bool isUsed () const =0
Usage state of the variable.
virtual bool isPartial () const =0
Indicates if the variable is partial.
virtual void copyItemsValues (Int32ConstArrayView source, Int32ConstArrayView destination)=0
Copies the values of entities numbered source into entities numbered destination.
virtual void copyItemsMeanValues (Int32ConstArrayView first_source, Int32ConstArrayView second_source, Int32ConstArrayView destination)=0
Copies the mean values of entities numbered first_source and second_source into entities numbered destination.
virtual void compact (Int32ConstArrayView new_to_old_ids)=0
Compresses the variable's values.
virtual void changeGroupIds (Int32ConstArrayView old_to_new_ids)=0
pH: EXPERIMENTAL
virtual IData * data ()=0
Data associated with the variable.
virtual const IData * data () const =0
Data associated with the variable.
virtual IDataFactoryMng * dataFactoryMng () const =0
Data factory associated with the variable.
Serialization operations
virtual void serialize (ISerializer *sbuffer, IDataOperation *operation=0)=0
virtual void serialize (ISerializer *sbuffer, Int32ConstArrayView ids, IDataOperation *operation=0)=0
Serializes the variable for identifiers ids.
virtual ARCANE_DEPRECATED_2018 void write (IDataWriter *writer)=0
Saves the variable.
virtual ARCANE_DEPRECATED_2018 void read (IDataReader *reader)=0
virtual void notifyEndRead ()=0
Notifies of external modification of data().
virtual void notifyBeginWrite ()=0
Notifies of the start of writing data().
virtual IObservable * writeObservable ()=0
Write observable.
virtual IObservable * readObservable ()=0
Read observable.
virtual IObservable * onSizeChangedObservable ()=0
Size change observable.
virtual void addTag (const String &tagname, const String &tagvalue)=0
Adds the tag tagname with the value tagvalue.
virtual void removeTag (const String &tagname)=0
Removes the tag tagname.
virtual bool hasTag (const String &tagname)=0
true if the variable has the tag tagname
virtual String tagValue (const String &tagname)=0
Value of the tag tagname. The string is null if the tag does not exist.
virtual void print (std::ostream &o) const =0
Prints the variable's values to the stream o.
Static Public Attributes
static const char * TAG_POST_PROCESSING = "PostProcessing"
Tag used to indicate if a variable will be post-processed.
static const char * TAG_POST_PROCESSING_AT_THIS_ITERATION = "PostProcessingAtThisIteration"
Tag used to indicate if a variable will be post-processed at this iteration.
Friends
class VariableMng
Dependency Management
virtual void update ()=0
Recalculates the variable if necessary.
virtual void update (Real wanted_time)=0
virtual void setUpToDate ()=0
Indicates that the variable has just been updated.
virtual Int64 modifiedTime ()=0
Time when the variable was updated.
virtual void addDepend (IVariable *var, eDependType dt)=0
Adds var to the list of dependencies.
virtual void addDepend (IVariable *var, eDependType dt, const TraceInfo &tinfo)=0
Adds var to the list of dependencies with trace info tinfo.
virtual void removeDepend (IVariable *var)=0
Removes var from the list of dependencies.
virtual void setComputeFunction (IVariableComputeFunction *v)=0
Sets the variable's recalculation function.
virtual IVariableComputeFunction * computeFunction ()=0
Function used to update the variable.
virtual void dependInfos (Array< VariableDependInfo > &infos)=0
Dependency information.
virtual IMemoryAccessTrace * memoryAccessTrace () const =0
virtual void setIsSynchronized ()=0
Indicates that the variable is synchronized.
virtual void setIsSynchronized (const ItemGroup &item_group)=0
Indicates that the variable is synchronized on the group item_group.
virtual IVariableInternal * _internalApi ()=0
Internal Arcane API.
static Int64 incrementModifiedTime ()
Increments the modification counter and returns its value before modification.
Detailed Description
Interface of a variable.
The implementation of this interface is the Variable class.
Generally, this interface is not used directly. Variables are managed by the VariableRef class and its derived classes.
Definition at line 39 of file IVariable.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Properties of a variable.
Enumerator
PNoDump
Indicates that the variable should not be saved.
This property is collective: it must be set on all subdomains (or on none).
PNoNeedSync
Indicates that the variable is not necessarily synchronized.
This means it is normal for the variable values to be different from one processor to another on ghost cells
PHasTrace
Indicates that the variable is traced (only in trace mode).
PSubDomainDepend
Indicates that the variable value is dependent on the subdomain.
This means, among other things, that the variable value is different as soon as the number of subdomains changes. This is, for example, the case of the variable containing the number of the subdomain owning an entity.
PSubDomainPrivate
Indicates that the variable is private to the subdomain.
This means that the variable is dependent on the subdomain and specifically that it does not necessarily exist on all subdomains. This property cannot be set for mesh variables.
PExecutionDepend
Indicates that the variable value is dependent on the execution.
The values of these variables change between two executions. This is, for example, the case of a variable containing the CPU time used.
PPrivate
Indicates that the variable is private.
A private variable cannot possess more than one reference. This property can only be set when the variable is created
PTemporary
Indicates that the variable is temporary.
A temporary variable is temporary, as its name suggests. It cannot be saved, is not transferred during mesh balancing (but can be synchronized), and is not saved during rollback.
A temporary variable that is no longer used (no references to it) can be deallocated.
PNoRestore
Indicates that the variable should not be restored.
A variable of this type is neither saved nor restored during rollback.
PNoExchange
Indicates that the variable should not be exchanged.
A variable of this type is not exchanged during mesh repartitioning, for example. This prevents the sending of unnecessary data if this variable is only used temporarily or if it is recalculated in one of the entry points called following a repartitioning.
PPersistant
Indicates that the variable is persistent.
A persistent variable is not destroyed even if there are no references to it anymore.
PNoReplicaSync
Indicates that the variable does not necessarily have the same value across replicas.
This means it is normal for the variable values to be different on the same subdomains of other replicas.
PInShMem
Indicates that the variable must be allocated in shared memory.
The MachineShMemWinMemoryAllocator will be used. The MachineShMemWinVariable class can be used with this variable.
PDumpNull
Indicates that the save will be null for this variable and for this subdomain.
A save will be performed, but with a default value (value = 0 for a scalar, empty array for an array).
Only works for unsupported variables.
Definition at line 55 of file IVariable.h.
eDependType
enum Arcane::IVariable::eDependType
Dependency Type.
Definition at line 44 of file IVariable.h.
Member Function Documentation
_internalApi()
virtual IVariableInternal * Arcane::IVariable::_internalApi () pure virtual
Internal Arcane API.
Implemented in Arcane::Variable.
References _internalApi().
Referenced by _internalApi(), and Arcane::VariableComparer::apply().
addDepend() [1/2]
virtual void Arcane::IVariable::addDepend (IVariable * var, eDependType dt) pure virtual
Adds var to the list of dependencies.
Implemented in Arcane::Variable.
References addDepend().
Referenced by addDepend(), and addDepend().
addDepend() [2/2]
virtual void Arcane::IVariable::addDepend (IVariable * var, eDependType dt, const TraceInfo & tinfo) pure virtual
Adds var to the list of dependencies with trace info tinfo.
Implemented in Arcane::Variable.
References addDepend().
addTag()
virtual void Arcane::IVariable::addTag (const String & tagname, const String & tagvalue) pure virtual
Adds the tag tagname with the value tagvalue.
Implemented in Arcane::Variable.
References addTag().
Referenced by addTag().
addVariableRef()
virtual void Arcane::IVariable::addVariableRef (VariableRef * var_ref) pure virtual
Adds a reference to this variable.
Precondition
var_ref must not already reference a variable.
Implemented in Arcane::Variable.
allocatedMemory()
virtual Real Arcane::IVariable::allocatedMemory () const pure virtual
Memory size (in Bytes) used by the variable.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
allocationInfo()
virtual DataAllocationInfo Arcane::IVariable::allocationInfo () const pure virtual
Allocation information.
Implemented in Arcane::Variable.
References allocationInfo().
Referenced by allocationInfo().
changeGroupIds()
virtual void Arcane::IVariable::changeGroupIds (Int32ConstArrayView old_to_new_ids) pure virtual
pH: EXPERIMENTAL
Implemented in Arcane::Variable.
References changeGroupIds().
Referenced by changeGroupIds().
checkIfSame()
virtual Int32 Arcane::IVariable::checkIfSame (IDataReader * reader, Integer max_print, bool compare_ghost) pure virtual
Checks that the variable is identical to a reference value.
This operation checks that the variable values are identical to a reference value read from the reader reader.
For each value different from the reference, a message is displayed.
Parameters
max_print maximum number of messages to display. If 0, no element is displayed. If positive, display at most max_print elements. If negative, all elements are displayed.
compare_ghost if true, compares values both on owned entities and ghost entities. Otherwise, it only compares on owned entities.
Returns
the number of different reference values.
Implemented in Arcane::Variable.
References checkIfSame().
Referenced by checkIfSame().
checkIfSameOnAllReplica()
virtual Int32 Arcane::IVariable::checkIfSameOnAllReplica (Integer max_print = 0) pure virtual
Checks if the variable has the same values on all replicas.
Compare the variable's values with those of the same subdomain of other replicas. For each different element, a message is displayed.
This method is collective across the same subdomain as other replicas. Therefore, it should only be called if the variable exists on all subdomains otherwise it causes a blocking.
This method only works for variables of numeric types. In this case, it throws a NotSupportedException.
Parameters
max_print maximum number of messages to display. If 0, no elements are displayed. If positive, displays at most max_print elements. If negative, all elements are displayed. For each different element, the minimum and maximum value is displayed.
Returns
the number of different values of the reference.
Implemented in Arcane::Variable.
References checkIfSameOnAllReplica().
Referenced by checkIfSameOnAllReplica().
checkIfSync()
virtual Int32 Arcane::IVariable::checkIfSync (Integer max_print = 0) pure virtual
Checks if the variable is properly synchronized.
This operation only works for mesh variables.
A variable is synchronized when its values are the same across all subdomains, both on owned elements and ghost elements.
For each unsynchronized element, a message is displayed.
Parameters
max_print maximum number of messages to display. If 0, no element is displayed. If positive, display at most max_print elements. If negative, all elements are displayed.
Returns
the number of different reference values.
Implemented in Arcane::Variable.
References checkIfSync().
Referenced by checkIfSync().
compact()
virtual void Arcane::IVariable::compact (Int32ConstArrayView new_to_old_ids) pure virtual
Compresses the variable's values.
This operation is internal to Arcane and must be done in conjunction with the entity family corresponding to this variable.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References compact().
Referenced by compact().
computeFunction()
virtual IVariableComputeFunction * Arcane::IVariable::computeFunction () pure virtual
Function used to update the variable.
Implemented in Arcane::Variable.
References computeFunction().
Referenced by computeFunction().
copyItemsMeanValues()
virtual void Arcane::IVariable::copyItemsMeanValues (Int32ConstArrayView first_source, Int32ConstArrayView second_source, Int32ConstArrayView destination) pure virtual
Copies the mean values of entities numbered first_source and second_source into entities numbered destination.
Parameters
first_source list of localIds of the 1st source
second_source list of localIds of the 2nd source
destination list of destination localIds
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References copyItemsMeanValues().
Referenced by copyItemsMeanValues().
copyItemsValues()
virtual void Arcane::IVariable::copyItemsValues (Int32ConstArrayView source, Int32ConstArrayView destination) pure virtual
Copies the values of entities numbered source into entities numbered destination.
Note
This operation is internal to Arcane and must be done in conjunction with the entity family corresponding to this variable.
Parameters
source list of source localIds
destination list of destination localIds
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References copyItemsValues().
Referenced by copyItemsValues().
createMetaData()
virtual VariableMetaData * Arcane::IVariable::createMetaData () const pure virtual
Creates an instance containing the variable's metadata.
The returned instance must be destroyed by calling the delete operator.
Implemented in Arcane::Variable.
References createMetaData().
Referenced by createMetaData().
createMetaDataRef()
virtual Ref< VariableMetaData > Arcane::IVariable::createMetaDataRef () const pure virtual
Creates an instance containing the variable's metadata.
Implemented in Arcane::Variable.
References createMetaDataRef().
Referenced by createMetaDataRef().
data() [1/2]
virtual const IData * Arcane::IVariable::data () const pure virtual
Data associated with the variable.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References data().
data() [2/2]
virtual IData * Arcane::IVariable::data () pure virtual
Data associated with the variable.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References data().
Referenced by Arcane::Variable::_setData(), Arcane::Variable::allocationInfo(), data(), data(), Arcane::VariableUtils::prefetchVariableAsync(), Arcane::Variable::read(), Arcane::Hdf5VariableReaderHelper::readInit(), Arcane::Variable::setAllocationInfo(), and Arcane::Variable::write().
dataFactoryMng()
virtual IDataFactoryMng * Arcane::IVariable::dataFactoryMng () const pure virtual
Data factory associated with the variable.
Implemented in Arcane::Variable.
References dataFactoryMng().
Referenced by dataFactoryMng().
dataType()
virtual eDataType Arcane::IVariable::dataType () const pure virtual
Data type managed by the variable (Real, Integer, ...).
Implemented in Arcane::Variable.
Referenced by Arcane::Hdf5VariableInfoBase::create(), Arcane::Hdf5VariableReaderHelper2::readAndUpdateTimeVariables(), Arcane::VtkHdfDataWriter::write(), and Arcane::VtkHdfV2DataWriter::write().
dependInfos()
virtual void Arcane::IVariable::dependInfos (Array< VariableDependInfo > & infos) pure virtual
Dependency information.
Fills the array infos with dependency information.
Implemented in Arcane::Variable.
References dependInfos().
Referenced by dependInfos().
dimension()
virtual Integer Arcane::IVariable::dimension () const pure virtual
Dimension of the variable.
The possible values are as follows:
0 for a scalar variable.
1 for a mono-dimensional array variable or a mesh scalar variable.
2 for a bi-dimensional array variable or a mesh array variable.
Implemented in Arcane::Variable.
Referenced by Arcane::Hdf5VariableInfoBase::create(), Arcane::VtkHdfDataWriter::write(), and Arcane::VtkHdfV2DataWriter::write().
firstReference()
virtual VariableRef * Arcane::IVariable::firstReference () const pure virtual
First reference (or null) on this variable.
Implemented in Arcane::Variable.
fullName()
virtual String Arcane::IVariable::fullName () const pure virtual
Full variable name (with family prefix).
Implemented in Arcane::Variable.
Referenced by Arcane::Hdf5VariableInfoBase::create(), Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType >::getVariableReference(), Arcane::ManualHdf5VariableWriter::notifyEndWrite(), Arcane::Hdf5VariableReaderHelper::readInit(), Arcane::VariableCollection::sortByName(), and Arcane::ManualHdf5DataWriter::write().
hasTag()
virtual bool Arcane::IVariable::hasTag (const String & tagname) pure virtual
true if the variable has the tag tagname
Implemented in Arcane::Variable.
References hasTag().
Referenced by hasTag(), and Arcane::MeshUtils::markMeshConnectivitiesAsMostlyReadOnly().
incrementModifiedTime()
Int64 Arcane::IVariable::incrementModifiedTime () static
Increments the modification counter and returns its value before modification.
Definition at line 205 of file Variable.cc.
Referenced by setIsSynchronized(), Arcane::Materials::MeshMaterialVariable::setUpToDate(), and Arcane::Variable::setUpToDate().
initialize()
virtual bool Arcane::IVariable::initialize (const ItemGroup & group, const String & value) pure virtual
Initializes the variable on a group.
Initializes the variable with the value value for all elements of the group group.
This operation is only usable with mesh variables.
Parameters
group_name group. It must correspond to an existing group of the variable's type (e.g., CellGroup for a cell variable).
value initialization value. The string must be convertible to the variable's type.
Return values
true in case of error or if the variable is not a mesh variable.
false if the initialization is successful.
Implemented in Arcane::Variable, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, and Arcane::VariableArrayT< Real3x3 >.
References initialize().
Referenced by initialize().
isPartial()
virtual bool Arcane::IVariable::isPartial () const pure virtual
Indicates if the variable is partial.
A variable is partial when it is not defined on all entities of a family. In this case, group()!=itemFamily()->allItems().
Implemented in Arcane::Variable.
References isPartial().
Referenced by Arcane::Hdf5VariableInfoBase::create(), isPartial(), Arcane::VtkHdfV2DataWriter::write(), and Arcane::Hdf5ItemVariableInfo< VariableType, DataType >::writeVariable().
isUsed()
virtual bool Arcane::IVariable::isUsed () const pure virtual
Usage state of the variable.
Implemented in Arcane::Variable.
References isUsed().
Referenced by isUsed(), and Arcane::VariableUtils::prefetchVariableAsync().
itemFamily()
virtual IItemFamily * Arcane::IVariable::itemFamily () const pure virtual
Associated entity family.
Returns
the family associated with the variable or 0 if the variable has no family.
If a variable is not used or not yet allocated, the returned value is null. However, the variable can still be associated with a family. In this case, you must use the itemFamilyName() function to retrieve the name of this family.
Implemented in Arcane::Variable.
References itemFamily().
Referenced by Arcane::Hdf5VariableInfoBase::create(), itemFamily(), and Arcane::Hdf5VariableReaderHelper::open().
itemFamilyName()
virtual String Arcane::IVariable::itemFamilyName () const pure virtual
Name of the associated family (null if none).
Implemented in Arcane::Variable.
References itemFamilyName().
Referenced by itemFamilyName(), and Arcane::ManualHdf5VariableWriter::notifyEndWrite().
itemGroup()
virtual ItemGroup Arcane::IVariable::itemGroup () const pure virtual
Associated mesh group.
Returns
the associated mesh group if for a mesh variable or the null group if the variable is not a mesh variable.
If a variable is not used or not yet allocated, the returned value is the null group. However, the variable can still be associated with a group. In this case, you must use the itemGroupName() function to retrieve the name of this group.
Implemented in Arcane::Variable.
References itemGroup().
Referenced by Arcane::Parallel::VariableParallelOperationBase::addVariable(), itemGroup(), Arcane::ManualHdf5DataWriter::write(), and Arcane::Hdf5VariableInfoBase::writeGroup().
itemGroupName()
virtual String Arcane::IVariable::itemGroupName () const pure virtual
Name of the associated entity group.
Implemented in Arcane::Variable.
References itemGroupName().
Referenced by itemGroupName(), and Arcane::Hdf5VariableReaderHelper2::open().
itemKind()
virtual eItemKind Arcane::IVariable::itemKind () const pure virtual
Kind of mesh entities on which the variable is based.
For scalar or array variables, there is no kind, and the method returns IK_Unknown. For other variables, it returns the kind of the mesh element (Node, Cell, ...), namely:
IK_Node for nodes
IK_Edge for edges
IK_Face for faces
IK_Cell for cells
IK_Particle for particles
IK_DoF for degrees of freedom
Implemented in Arcane::Variable.
Referenced by Arcane::VerifierService::_getVariables(), Arcane::ManualHdf5VariableWriter::notifyEndWrite(), Arcane::Hdf5VariableReaderHelper::open(), Arcane::VtkHdfDataWriter::write(), and Arcane::VtkHdfV2DataWriter::write().
mesh()
virtual IMesh * Arcane::IVariable::mesh () const pure virtual
Mesh associated with the variable.
This operation is only meaningful for variables on mesh entities.
Implemented in Arcane::Variable.
References mesh().
Referenced by mesh().
meshHandle()
virtual MeshHandle Arcane::IVariable::meshHandle () const pure virtual
Mesh associated with the variable.
This operation is only meaningful for variables on mesh entities.
Implemented in Arcane::Variable.
References meshHandle().
Referenced by Arcane::VerifierService::_getVariables(), Arcane::MeshUtils::markMeshConnectivitiesAsMostlyReadOnly(), and meshHandle().
meshName()
virtual String Arcane::IVariable::meshName () const pure virtual
Name of the associated mesh (null if none).
Implemented in Arcane::Variable.
References meshName().
Referenced by meshName().
modifiedTime()
virtual Int64 Arcane::IVariable::modifiedTime () pure virtual
Time when the variable was updated.
Implemented in Arcane::Variable.
References modifiedTime().
Referenced by modifiedTime(), and Arcane::Materials::MeshMaterialVariable::update().
multiTag()
virtual Integer Arcane::IVariable::multiTag () const pure virtual
Indicates if the variable is a multi-sized array.
This value is only useful for 2D or higher arrays.
0 for a scalar variable or standard 2D array.
1 for a multi-sized 2D array variable.
2 for an ancient format 2D array variable (obsolete).
Implemented in Arcane::Variable.
name()
virtual String Arcane::IVariable::name () const pure virtual
Variable name.
Implemented in Arcane::Variable.
Referenced by Arcane::Parallel::VariableParallelOperationBase::applyOperation(), Arcane::ManualHdf5VariableWriter::notifyEndWrite(), Arcane::Hdf5VariableReaderHelper::open(), Arcane::VtkHdfDataWriter::write(), and Arcane::VtkHdfV2DataWriter::write().
nbElement()
virtual Integer Arcane::IVariable::nbElement () const pure virtual
Number of elements of the variable.
The returned values depend on the dimension of the variable:
for dimension 0, returns 1,
for dimension 1, returns the number of elements in the array
for dimension 2, returns the total number of elements by summing the number of elements per dimension.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
nbReference()
virtual Integer Arcane::IVariable::nbReference () const pure virtual
Number of references on this variable.
Implemented in Arcane::Variable.
notifyBeginWrite()
virtual void Arcane::IVariable::notifyBeginWrite () pure virtual
Notifies of the start of writing data().
This method triggers the observables registered in writeObservable().
Implemented in Arcane::Variable.
References notifyBeginWrite().
Referenced by notifyBeginWrite().
notifyEndRead()
virtual void Arcane::IVariable::notifyEndRead () pure virtual
Notifies of external modification of data().
Signals to the instance the end of a read operation that modified data(). This method must therefore be called as soon as a modification of data() has been performed. This method triggers the observables registered in readObservable().
Implemented in Arcane::Variable.
References notifyEndRead().
Referenced by notifyEndRead().
notifyReferencePropertyChanged()
virtual void Arcane::IVariable::notifyReferencePropertyChanged () pure virtual
Indicates that the properties of one of the references to this variable have changed (internal)
Implemented in Arcane::Variable.
onSizeChangedObservable()
virtual IObservable * Arcane::IVariable::onSizeChangedObservable () pure virtual
Size change observable.
The observers registered in this observable are called when the number of elements of the variable changes. This is the case, for example, after a remeshing for a cell variable
Implemented in Arcane::Variable.
References onSizeChangedObservable().
Referenced by onSizeChangedObservable().
print()
virtual void Arcane::IVariable::print (std::ostream & o) const pure virtual
Prints the variable's values to the stream o.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References print().
Referenced by print().
property()
virtual int Arcane::IVariable::property () const pure virtual
Returns the properties of the variable.
Implemented in Arcane::Variable.
Referenced by Arcane::VerifierService::_getVariables().
read()
virtual ARCANE_DEPRECATED_2018 void Arcane::IVariable::read (IDataReader * reader) pure virtual
Reads the variable.
Deprecated
Should be replaced by the following code:
IVariable* var;
reader->read(var,var->data());
var->notifyEndRead();
Implemented in Arcane::Variable.
References read().
Referenced by read().
readObservable()
virtual IObservable * Arcane::IVariable::readObservable () pure virtual
Read observable.
The observers registered in this observable are called after reading the variable (read operation).
Implemented in Arcane::Variable.
References readObservable().
Referenced by readObservable().
removeDepend()
virtual void Arcane::IVariable::removeDepend (IVariable * var) pure virtual
Removes var from the list of dependencies.
Implemented in Arcane::Variable.
References removeDepend().
Referenced by removeDepend().
removeTag()
virtual void Arcane::IVariable::removeTag (const String & tagname) pure virtual
Removes the tag tagname.
If the tag tagname is not in the list, nothing happens.
Implemented in Arcane::Variable.
References removeTag().
Referenced by removeTag().
removeVariableRef()
virtual void Arcane::IVariable::removeVariableRef (VariableRef * var_ref) pure virtual
Removes a reference to this variable.
Precondition
var_ref must reference this variable (an call to addVariableRef() must have been made on this variable).
Implemented in Arcane::Variable.
resize()
virtual void Arcane::IVariable::resize (Integer new_size) pure virtual
Sets the number of elements for an array variable.
When the variable is a 1D or 2D array type, it sets the number of array elements to new_size. For a 2D array, the number of elements in the first dimension is modified.
This operation must not be called for mesh variables because the number of elements is determined automatically based on the number of entities in the group it relies on. For this type of variable, resizeFromGroup() must be called.
This operation synchronizes the references (syncReferences()).
Implemented in Arcane::Variable.
References resize().
Referenced by resize().
resizeFromGroup()
virtual void Arcane::IVariable::resizeFromGroup () pure virtual
Sets the number of elements for a mesh variable.
Reallocates the size of the mesh variable based on the group it relies on.
This operation only has an effect on mesh variables. For others, no action is performed.
This operation synchronizes the references (syncReferences()).
Implemented in Arcane::Variable.
References resizeFromGroup().
Referenced by resizeFromGroup().
serialize() [1/2]
virtual void Arcane::IVariable::serialize (ISerializer * sbuffer, IDataOperation * operation = 0) pure virtual
Serializes the variable.
The operation is only meaningful in read mode (ISerializer::ModeGet)
Implemented in Arcane::Variable.
References serialize().
Referenced by Arcane::Parallel::VariableParallelOperationBase::applyOperation(), serialize(), and serialize().
serialize() [2/2]
virtual void Arcane::IVariable::serialize (ISerializer * sbuffer, Int32ConstArrayView ids, IDataOperation * operation = 0) pure virtual
Serializes the variable for identifiers ids.
Serialization depends on the variable's dimension. For scalar variables (dimension=0), nothing is done. For array or mesh variables, ids corresponds to an array of first dimension indirection.
The operation is only meaningful in read mode (ISerializer::ModeGet)
Implemented in Arcane::Variable.
References serialize().
setAllocationInfo()
virtual void Arcane::IVariable::setAllocationInfo (const DataAllocationInfo & v) pure virtual
Sets allocation information.
Implemented in Arcane::Variable.
References setAllocationInfo().
Referenced by Arcane::MeshUtils::markMeshConnectivitiesAsMostlyReadOnly(), Arcane::VariableUtils::markVariableAsMostlyReadOnly(), and setAllocationInfo().
setComputeFunction()
virtual void Arcane::IVariable::setComputeFunction (IVariableComputeFunction * v) pure virtual
Sets the variable's recalculation function.
The specified function v must be allocated via the new operator. If a recalculation function already existed, it is destroyed (via the delete operator) and replaced by this one.
Implemented in Arcane::Variable.
References setComputeFunction().
Referenced by setComputeFunction().
setIsSynchronized() [1/2]
virtual void Arcane::IVariable::setIsSynchronized () pure virtual
Indicates that the variable is synchronized.
This operation is collective.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References setIsSynchronized().
Referenced by setIsSynchronized(), and setIsSynchronized().
setIsSynchronized() [2/2]
virtual void Arcane::IVariable::setIsSynchronized (const ItemGroup & item_group) pure virtual
Indicates that the variable is synchronized on the group item_group.
This operation is collective.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References incrementModifiedTime(), and setIsSynchronized().
setUpToDate()
virtual void Arcane::IVariable::setUpToDate () pure virtual
Indicates that the variable has just been updated.
For correct dependency management, this property must be called every time a variable has been updated.
Implemented in Arcane::Variable.
References setUpToDate().
Referenced by setUpToDate().
setUsed()
virtual void Arcane::IVariable::setUsed (bool v) pure virtual
Sets the usage state of the variable.
If \v is false, the variable becomes unusable and all associated resources are released.
If \v is true, the variable is considered used and if it is a mesh variable and setItemGroup() has not been called, the variable is allocated to the group of all entities.
Implemented in Arcane::Variable.
References setUsed().
Referenced by setUsed().
shrinkMemory()
virtual void Arcane::IVariable::shrinkMemory () pure virtual
Frees any additional memory allocated for the data.
This method is only useful for non-scalar variables
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References shrinkMemory().
Referenced by shrinkMemory().
subDomain()
virtual ISubDomain * Arcane::IVariable::subDomain () pure virtual
Subdomain associated with the variable (TODO deprecate end of 2023).
Implemented in Arcane::Variable.
synchronize() [1/2]
virtual void Arcane::IVariable::synchronize () pure virtual
Synchronizes the variable.
La synchronisation ne peut se faire que sur les variables du maillage.
Implemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
References synchronize().
Referenced by synchronize().
synchronize() [2/2]
void Arcane::IVariable::synchronize (Int32ConstArrayView local_ids) virtual
Synchronizes the variable on a list of entities.
Synchronization can only be performed on mesh variables. Only the entities listed in local_ids will be synchronized. Note: an entity present in this list on one subdomain must be present in this list for any other subdomain that possesses this entity.
Reimplemented in Arcane::Array2VariableT< T >, Arcane::Array2VariableT< DataType >, Arcane::Array2VariableT< Int32 >, Arcane::Array2VariableT< Int64 >, Arcane::Array2VariableT< Real >, Arcane::Array2VariableT< Real2 >, Arcane::Array2VariableT< Real2x2 >, Arcane::Array2VariableT< Real3 >, Arcane::Array2VariableT< Real3x3 >, Arcane::VariableArrayT< T >, Arcane::VariableArrayT< DataType >, Arcane::VariableArrayT< Int32 >, Arcane::VariableArrayT< Int64 >, Arcane::VariableArrayT< Real >, Arcane::VariableArrayT< Real2 >, Arcane::VariableArrayT< Real2x2 >, Arcane::VariableArrayT< Real3 >, Arcane::VariableArrayT< Real3x3 >, Arcane::VariableScalarT< T >, and Arcane::VariableScalarT< DataType >.
Definition at line 301 of file InterfaceImpl.cc.
References ARCANE_THROW.
syncReferences()
virtual void Arcane::IVariable::syncReferences () pure virtual
Synchronizes references.
Synchronizes the values of references (VariableRef) to this variable with the variable's current value. This method is called automatically when a scalar variable is modified or the number of elements of an array variable changes.
Implemented in Arcane::Variable.
References syncReferences().
Referenced by syncReferences().
tagValue()
virtual String Arcane::IVariable::tagValue (const String & tagname) pure virtual
Value of the tag tagname. The string is null if the tag does not exist.
Implemented in Arcane::Variable.
References tagValue().
Referenced by tagValue().
update()
virtual void Arcane::IVariable::update () pure virtual
Recalculates the variable if necessary.
Through the dependency mechanism, this operation is called recursively on all variables that the instance depends on. The recalculation function computeFunction() is then called if it turns out that one of the variables it depends on has been modified more recently.
Precondition
computeFunction() != 0
Implemented in Arcane::Variable.
References update().
Referenced by update(), and Arcane::Materials::MeshMaterialVariable::update().
variableMng()
virtual IVariableMng * Arcane::IVariable::variableMng () const pure virtual
Variable manager associated with the variable.
Implemented in Arcane::Variable.
Referenced by Arcane::Hdf5ItemVariableInfo< VariableType, DataType >::writeVariable().
write()
virtual ARCANE_DEPRECATED_2018 void Arcane::IVariable::write (IDataWriter * writer) pure virtual
Saves the variable.
Deprecated
Should be replaced by the following code:
IVariable* var;
var->notifyBeginWrite();
writer->write(var,var->data());
Implemented in Arcane::Variable.
References write().
Referenced by write().
writeObservable()
virtual IObservable * Arcane::IVariable::writeObservable () pure virtual
Write observable.
The observers registered in this observable are called before writing the variable (write operation).
Implemented in Arcane::Variable.
References writeObservable().
Referenced by writeObservable().
Friends And Related Symbol Documentation
VariableMng
friend class VariableMng friend
Definition at line 180 of file IVariable.h.
Member Data Documentation
TAG_POST_PROCESSING
const char * Arcane::IVariable::TAG_POST_PROCESSING = "PostProcessing" static
Tag used to indicate if a variable will be post-processed.
Definition at line 173 of file IVariable.h.
TAG_POST_PROCESSING_AT_THIS_ITERATION
const char * Arcane::IVariable::TAG_POST_PROCESSING_AT_THIS_ITERATION = "PostProcessingAtThisIteration" static
Tag used to indicate if a variable will be post-processed at this iteration.
Definition at line 176 of file IVariable.h.
The documentation for this class was generated from the following files:
IVariable.h
InterfaceImpl.cc
Variable.cc