Alien: Alien::Vector Class Reference
Alien::Vector Class Reference final
Public Member Functions
Vector (const VectorDistribution &dist)
Vector (Integer nrows, Integer nrows_local, IMessagePassingMng *parallel_mng)
Vector (Arccore::Integer nrows, IMessagePassingMng *parallel_mng)
Vector (Vector &&vector)
Vector & operator= (Vector &&vector)
Vector (const Vector &)=delete
Vector & operator= (const Vector &)=delete
template<typename E>
Vector & operator= (const E &)
void visit (ICopyOnWriteVector &) const
Visit method.
const VectorDistribution & distribution () const
const ISpace & space () const
Get the space associated to the vector.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
MultiVectorImpl * impl ()
Get the multivector implementation.
const MultiVectorImpl * impl () const
Get the multivector implementation.
void setName (std::string name)
std::string const & name () const
Private Attributes
std::shared_ptr< MultiVectorImpl > m_impl
std::string m_name = "UnamedVector"
Additional Inherited Members
Protected Member Functions inherited from Alien::IVector
IVector ()
Constructor.
Detailed Description
Definition at line 36 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/4]
Alien::Vector::Vector ()
Definition at line 33 of file Vector.cc.
Vector() [2/4]
Alien::Vector::Vector (const VectorDistribution & dist)
Definition at line 40 of file Vector.cc.
Vector() [3/4]
Alien::Vector::Vector (Integer nrows, Integer nrows_local, IMessagePassingMng * parallel_mng)
Definition at line 46 of file Vector.cc.
Vector() [4/4]
Alien::Vector::Vector (Vector && vector)
Definition at line 61 of file Vector.cc.
~Vector()
Alien::Vector::~Vector () inline
Definition at line 49 of file Vector.h.
Member Function Documentation
distribution()
const VectorDistribution & Alien::Vector::distribution () const
Definition at line 92 of file Vector.cc.
hasUserFeature()
bool Alien::Vector::hasUserFeature (String feature) const
Definition at line 106 of file Vector.cc.
impl() [1/2]
MultiVectorImpl * Alien::Vector::impl () virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 114 of file Vector.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiVectorImpl * Alien::Vector::impl () const virtual
Get the multivector implementation.
Returns
The multivector implementation
Implements Alien::IVector.
Definition at line 129 of file Vector.cc.
References impl().
name()
std::string const & Alien::Vector::name () const inline
Definition at line 83 of file Vector.h.
operator=() [1/2]
template<typename E> Vector & Alien::Vector::operator= (const E & expr)
Definition at line 901 of file MVExpr.h.
operator=() [2/2]
Vector & Alien::Vector::operator= (Vector && vector)
Definition at line 68 of file Vector.cc.
setName()
void Alien::Vector::setName (std::string name) inline
Definition at line 82 of file Vector.h.
setUserFeature()
void Alien::Vector::setUserFeature (String feature)
Definition at line 99 of file Vector.cc.
space()
const ISpace & Alien::Vector::space () const virtual
Get the space associated to the vector.
Returns
The space
Implements Alien::IVector.
Definition at line 84 of file Vector.cc.
References space().
Referenced by space().
visit()
void Alien::Vector::visit (ICopyOnWriteVector &) const virtual
Visit method.
Implements Alien::IVector.
Definition at line 76 of file Vector.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiVectorImpl> Alien::Vector::m_impl private
Definition at line 77 of file Vector.h.
m_name
std::string Alien::Vector::m_name = "UnamedVector" private
Definition at line 79 of file Vector.h.
The documentation for this class was generated from the following files:
Vector.h
Vector.cc
MVExpr.h