Arcane: Arcane::Materials::MeshBlock Class Reference
Arcane::Materials::MeshBlock Class Reference
Block of a mesh.
#include <arcane/materials/MeshBlock.h>
Public Member Functions
MeshBlock (IMeshMaterialMng *mm, Int32 block_id, const MeshBlockBuildInfo &infos)
virtual IMeshMaterialMng * materialMng ()
Associated manager.
virtual const String & name () const
Block name.
virtual const CellGroup & cells () const
Cell group of this block.
virtual ConstArrayView< IMeshEnvironment * > environments ()
List of environments in this block.
virtual Integer nbEnvironment () const
Number of environments in the block.
virtual Int32 id () const
Block identifier. It is also the index (starting from 0) of this block in the list of blocks.
virtual AllEnvCellVectorView view ()
View of the environments cells corresponding to this block.
void build ()
Public functions but reserved for IMeshMaterialMng.
void addEnvironment (IMeshEnvironment *env)
Adds the environment env to the block.
void removeEnvironment (IMeshEnvironment *env)
Removes the environment env from the block.
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Private Attributes
IMeshMaterialMng * m_material_mng
Material manager.
Int32 m_block_id
Material identifier (index of this material in the list of materials).
String m_name
Material name.
CellGroup m_cells
List of cells for this material.
UniqueArray< IMeshEnvironment * > m_environments
List of materials/environments in this block.
Additional Inherited Members
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Detailed Description
Block of a mesh.
This class is for internal use in Arcane and should not be used explicitly. The IMeshBlock interface must be used to access the materials.
Definition at line 41 of file MeshBlock.h.
Constructor & Destructor Documentation
MeshBlock()
Arcane::Materials::MeshBlock::MeshBlock (IMeshMaterialMng * mm, Int32 block_id, const MeshBlockBuildInfo & infos)
Definition at line 31 of file MeshBlock.cc.
~MeshBlock()
virtual Arcane::Materials::MeshBlock::~MeshBlock () inline virtual
Definition at line 48 of file MeshBlock.h.
Member Function Documentation
addEnvironment()
void Arcane::Materials::MeshBlock::addEnvironment (IMeshEnvironment * env)
Adds the environment env to the block.
This can only be done during the initialization phase (before IMeshMaterialMng::endCreate() has been called).
Definition at line 68 of file MeshBlock.cc.
References m_environments, and Arcane::Materials::IMeshComponent::name().
Referenced by Arcane::Materials::MeshMaterialMng::addEnvironmentToBlock().
build()
void Arcane::Materials::MeshBlock::build ()
Public functions but reserved for IMeshMaterialMng.
Definition at line 45 of file MeshBlock.cc.
Referenced by Arcane::Materials::MeshMaterialMng::createBlock().
cells()
virtual const CellGroup & Arcane::Materials::MeshBlock::cells () const inline virtual
Cell group of this block.
Implements Arcane::Materials::IMeshBlock.
Definition at line 54 of file MeshBlock.h.
References m_cells.
environments()
virtual ConstArrayView< IMeshEnvironment * > Arcane::Materials::MeshBlock::environments () inline virtual
List of environments in this block.
Implements Arcane::Materials::IMeshBlock.
Definition at line 55 of file MeshBlock.h.
References m_environments.
id()
virtual Int32 Arcane::Materials::MeshBlock::id () const inline virtual
Block identifier. It is also the index (starting from 0) of this block in the list of blocks.
Implements Arcane::Materials::IMeshBlock.
Definition at line 63 of file MeshBlock.h.
References m_block_id.
materialMng()
virtual IMeshMaterialMng * Arcane::Materials::MeshBlock::materialMng () inline virtual
Associated manager.
Implements Arcane::Materials::IMeshBlock.
Definition at line 52 of file MeshBlock.h.
References m_material_mng.
name()
virtual const String & Arcane::Materials::MeshBlock::name () const inline virtual
Block name.
Implements Arcane::Materials::IMeshBlock.
Definition at line 53 of file MeshBlock.h.
References m_name.
nbEnvironment()
virtual Integer Arcane::Materials::MeshBlock::nbEnvironment () const inline virtual
Number of environments in the block.
Implements Arcane::Materials::IMeshBlock.
Definition at line 59 of file MeshBlock.h.
References m_environments.
removeEnvironment()
void Arcane::Materials::MeshBlock::removeEnvironment (IMeshEnvironment * env)
Removes the environment env from the block.
This can only be done during the initialization phase (before IMeshMaterialMng::endCreate() has been called).
Definition at line 87 of file MeshBlock.cc.
References m_environments, and Arcane::Materials::IMeshComponent::name().
Referenced by Arcane::Materials::MeshMaterialMng::removeEnvironmentToBlock().
view()
AllEnvCellVectorView Arcane::Materials::MeshBlock::view () virtual
View of the environments cells corresponding to this block.
Implements Arcane::Materials::IMeshBlock.
Definition at line 53 of file MeshBlock.cc.
References m_cells, and m_material_mng.
Member Data Documentation
m_block_id
Int32 Arcane::Materials::MeshBlock::m_block_id private
Material identifier (index of this material in the list of materials).
Definition at line 85 of file MeshBlock.h.
Referenced by id().
m_cells
CellGroup Arcane::Materials::MeshBlock::m_cells private
List of cells for this material.
Definition at line 91 of file MeshBlock.h.
Referenced by cells(), and view().
m_environments
UniqueArray<IMeshEnvironment*> Arcane::Materials::MeshBlock::m_environments private
List of materials/environments in this block.
Definition at line 94 of file MeshBlock.h.
Referenced by addEnvironment(), environments(), nbEnvironment(), and removeEnvironment().
m_material_mng
IMeshMaterialMng* Arcane::Materials::MeshBlock::m_material_mng private
Material manager.
Definition at line 82 of file MeshBlock.h.
Referenced by materialMng(), and view().
m_name
String Arcane::Materials::MeshBlock::m_name private
Material name.
Definition at line 88 of file MeshBlock.h.
Referenced by name().
The documentation for this class was generated from the following files:
MeshBlock.h
MeshBlock.cc