Arcane: Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType > Class Template Reference
Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType > Class Template Reference
Static Public Member Functions
static MaterialVariableTypeInfo _buildVarTypeInfo (MatVarSpace space)
static TrueType * getVariableReference (const MaterialVariableBuildInfo &v, MatVarSpace mvs)
Returns a variable associated with a constituent.
static TrueType * getVariableReference (IMeshMaterialVariable *var)
Returns the concrete type of a constituent variable.
Detailed Description
template<typename TrueType>
class Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType >
Definition at line 231 of file core/materials/IMeshMaterialVariable.h.
Member Function Documentation
_buildVarTypeInfo()
template<typename TrueType> MaterialVariableTypeInfo Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType >::_buildVarTypeInfo (MatVarSpace space) static
Definition at line 38 of file IMeshMaterialVariable.cc.
getVariableReference() [1/2]
template<typename TrueType> TrueType * Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType >::getVariableReference (const MaterialVariableBuildInfo & v, MatVarSpace mvs) static
Returns a variable associated with a constituent.
Returns the constituent variable based on the information provided by v and mvs. If the variable does not yet exist, it is created.
Definition at line 59 of file IMeshMaterialVariable.cc.
References ARCANE_CHECK_POINTER, ARCANE_FATAL, Arcane::Materials::IMeshMaterialVariableFactoryMng::createVariable(), Arcane::Materials::MaterialVariableTypeInfo::fullName(), Arcane::Materials::IMeshMaterialMng::getReference(), Arcane::MeshHandle::isNull(), and Arcane::Materials::IMeshMaterialMng::variableFactoryMng().
getVariableReference() [2/2]
template<typename TrueType> TrueType * Arcane::Materials::MeshMaterialVariableBuildTraits< TrueType >::getVariableReference (IMeshMaterialVariable * var) static
Returns the concrete type of a constituent variable.
Converts var to the TrueType. If this is not possible, it throws an exception.
Definition at line 92 of file IMeshMaterialVariable.cc.
References ARCANE_CHECK_POINTER, ARCANE_FATAL, Arcane::IVariable::fullName(), and Arcane::Materials::IMeshMaterialVariable::globalVariable().
The documentation for this class was generated from the following files:
core/materials/IMeshMaterialVariable.h
IMeshMaterialVariable.cc