Arcane: Arcane::MeshPartitionerBase Class Reference
Arcane::MeshPartitionerBase Class Reference
StandardService
Base class for a load balancing service.
#include <arcane/std/MeshPartitionerBase.h>
Public Types
enum eMarkCellWithConstraint {
eCellClassical , eCellReference , eCellGrouped , eCellGhost ,
eCellInAConstraint
}
Public Member Functions
MeshPartitionerBase (const ServiceBuildInfo &sbi)
ISubDomain * subDomain () const
IMesh * mesh () const override
Mesh associated with the partitioner.
void setMaximumComputationTime (Real v) override
Sets the proportion of computation time.
Real maximumComputationTime () const override
void setImbalance (Real v) override
Sets the computation time imbalance.
Real imbalance () const override
Computation time imbalance.
void setMaxImbalance (Real v) override
Sets the maximum allowed imbalance.
Real maxImbalance () const override
Maximum allowed imbalance.
void setComputationTimes (RealConstArrayView v) override
Computation time of this subdomain. The first element indicates the computation time of the subdomain corresponding to calculations whose cost is proportional to the cells. The following must be associated with a variable (to be done).
RealConstArrayView computationTimes () const override
void setCellsWeight (ArrayView< float > weights, Integer nb_weight) override
Allows defining the weights of objects to be partitioned: ILoadBalanceMng must now be used.
ArrayView< float > cellsWeight () const override
Integer nbCellWeight () const
void setILoadBalanceMng (ILoadBalanceMng *mng) override
Changes the ILoadBalanceMng to use.
ILoadBalanceMng * loadBalanceMng () const override
void notifyEndPartition () override
Notification when a re-partitioning finishes (after entity exchange).
virtual void changeOwnersFromCells ()
Positions the new owners of nodes, edges and faces based on the cells.
virtual void initConstraints (bool uidref=true)
virtual void freeConstraints ()
virtual Int32 nbOwnCellsWithConstraints () const
virtual Real getNeighbourCellsUidWithConstraints (Cell cell, Int64Array &neighbourcells, Array< float > *commWeights=NULL, bool noCellContrib=false)
virtual Integer nbNeighbourCellsWithConstraints (Cell cell)
virtual void getNeighbourNodesUidWithConstraints (Cell cell, Int64UniqueArray neighbournodes)
virtual Int32 localIdWithConstraints (Cell cell)
virtual Int32 localIdWithConstraints (Int32 cell_lid)
virtual void invertArrayLid2LidCompacted ()
virtual SharedArray< float > cellsWeightsWithConstraints (Int32 max_nb_weight=0, bool ask_lb_cells=false)
virtual SharedArray< float > cellsSizeWithConstraints ()
virtual bool cellUsedWithConstraints (Cell cell)
virtual bool cellUsedWithWeakConstraints (std::pair< Int64, Int64 > &paired_item)
virtual void changeCellOwner (Item cell, VariableItemInt32 &cells_new_owner, Int32 new_owner)
virtual bool haveConstraints ()
virtual bool haveWeakConstraints ()
Public Member Functions inherited from Arcane::AbstractService
~AbstractService () override
Destructor.
virtual void build ()
Build-level construction of the service.
IServiceInfo * serviceInfo () const override
Access to service information. See IServiceInfo for details.
IBase * serviceParent () const override
Access to the base interface of main Arcane objects.
IService * serviceInterface () override
Returns the low-level IService interface of the service.
Public Member Functions inherited from Arcane::TraceAccessor
TraceAccessor (ITraceMng *m)
Constructs an accessor via the trace manager m.
TraceAccessor (const TraceAccessor &rhs)
Copy constructor.
TraceAccessor & operator= (const TraceAccessor &rhs)
Copy assignment operator.
virtual ~TraceAccessor ()
Frees resources.
ITraceMng * traceMng () const
Trace manager.
TraceMessage info () const
Flow for an information message.
TraceMessage pinfo () const
Flow for a parallel information message.
TraceMessage info (char category) const
Flow for an information message of a given category.
TraceMessage pinfo (char category) const
Flow for a parallel information message of a given category.
TraceMessage info (bool v) const
Flow for an information message.
TraceMessage warning () const
Flow for a warning message.
TraceMessage pwarning () const
TraceMessage error () const
Flow for an error message.
TraceMessage perror () const
TraceMessage log () const
Flow for a log message.
TraceMessage plog () const
Flow for a log message.
TraceMessage logdate () const
Flow for a log message preceded by the date.
TraceMessage fatal () const
Flow for a fatal error message.
TraceMessage pfatal () const
Flow for a parallel fatal error message.
TraceMessageDbg debug (Trace::eDebugLevel=Trace::Medium) const
Flow for a debug message.
Trace::eDebugLevel configDbgLevel () const
Debug level of the configuration file.
TraceMessage info (Int32 verbose_level) const
Flow for an information message of a given level.
TraceMessage linfo () const
Flow for an information message with the local information level of this instance.
TraceMessage linfo (Int32 relative_level) const
Flow for an information message with the local information level of this instance.
void fatalMessage (const StandaloneTraceMessage &o) const
Public Member Functions inherited from Arcane::IService
virtual ~IService ()
Releases resources.
Public Member Functions inherited from Arcane::IMeshPartitioner
virtual void build ()=0
virtual void partitionMesh (bool initial_partition, Int32 nb_part)=0
virtual IPrimaryMesh * primaryMesh () override
Associated mesh.
virtual void partitionMesh (bool initial_partition)=0
Public Member Functions inherited from Arcane::IMeshPartitionerBase
virtual ~IMeshPartitionerBase ()=default
Releases resources.
Protected Member Functions
virtual void dumpObject (String filename="toto")
Dumps the partitioning information to disk.
virtual void * getCommunicator () const
virtual Parallel::Communicator communicator () const
virtual bool cellComm ()
virtual void _initArrayCellsWithConstraints ()
virtual void _initFilterLidCells ()
virtual void _initUidRef ()
virtual void _initUidRef (VariableCellInteger &cell_renum_uid)
virtual void _initLid2LidCompacted ()
virtual void _initNbCellsWithConstraints ()
virtual void _clearCellWgt ()
bool _isNonManifoldMesh () const
Int32 _meshDimension () const
Protected Member Functions inherited from Arcane::AbstractService
AbstractService (const ServiceBuildInfo &)
Constructor from a ServiceBuildInfo.
Protected Member Functions inherited from Arcane::TraceAccessor
void _setLocalVerboseLevel (Int32 v)
Int32 _localVerboseLevel () const
Protected Member Functions inherited from Arcane::IService
IService ()
Constructor.
Protected Attributes
IItemFamily * m_cell_family = nullptr
Private Member Functions
Real _addNgb (const Cell &cell, const Face &face, Int64Array &neighbourcells, Array< bool > &contrib, HashTableMapT< Int64, Int32 > &map, Array< float > *ptrcommWeights, Int32 offset, HashTableMapT< Int32, Int32 > &lids, bool special=false)
bool _createConstraintsLists (Int64MultiArray2 &tied_uid)
SharedArray< float > _cellsProjectWeights (VariableCellArrayReal &cellWgtIn, Int32 nbWgt) const
SharedArray< float > _cellsProjectWeights (VariableCellReal &cellWgtIn) const
void _checkCreateVar ()
Private Attributes
ISubDomain * m_sub_domain = nullptr
IMesh * m_mesh = nullptr
IParallelMng * m_pm_sub = nullptr
ILoadBalanceMng * m_lbMng = nullptr
ILoadBalanceMngInternal * m_lb_mng_internal = nullptr
Real m_maximum_computation_time = 0.0
Real m_imbalance = 0.0
Real m_max_imbalance = 0.0
UniqueArray< Real > m_computation_times
UniqueArray< SharedArray< Cell > > m_cells_with_constraints
std::set< std::pair< Int64, Int64 > > m_cells_with_weak_constraints
Integer m_nb_cells_with_constraints = 0
UniqueArray< eMarkCellWithConstraint > m_filter_lid_cells
UniqueArray< Int32 > m_local_id_2_local_id_compacted
VariableCellInt64 * m_unique_id_reference = nullptr
UniqueArray< Int32 > m_check
bool m_is_non_manifold_mesh = false
Int32 m_mesh_dimension = -1
Detailed Description
Base class for a load balancing service.
Definition at line 40 of file MeshPartitionerBase.h.
Member Enumeration Documentation
eMarkCellWithConstraint
enum Arcane::MeshPartitionerBase::eMarkCellWithConstraint
Definition at line 90 of file MeshPartitionerBase.h.
Constructor & Destructor Documentation
MeshPartitionerBase()
Arcane::MeshPartitionerBase::MeshPartitionerBase (const ServiceBuildInfo & sbi) explicit
Definition at line 55 of file MeshPartitionerBase.cc.
~MeshPartitionerBase()
Arcane::MeshPartitionerBase::~MeshPartitionerBase () override
Definition at line 72 of file MeshPartitionerBase.cc.
Member Function Documentation
_addNgb()
Real Arcane::MeshPartitionerBase::_addNgb (const Cell & cell, const Face & face, Int64Array & neighbourcells, Array< bool > & contrib, HashTableMapT< Int64, Int32 > & map, Array< float > * ptrcommWeights, Int32 offset, HashTableMapT< Int32, Int32 > & lids, bool special = false) private
Definition at line 428 of file MeshPartitionerBase.cc.
_cellsProjectWeights() [1/2]
SharedArray< float > Arcane::MeshPartitionerBase::_cellsProjectWeights (VariableCellArrayReal & cellWgtIn, Int32 nbWgt) const private
Definition at line 671 of file MeshPartitionerBase.cc.
_cellsProjectWeights() [2/2]
SharedArray< float > Arcane::MeshPartitionerBase::_cellsProjectWeights (VariableCellReal & cellWgtIn) const private
Definition at line 702 of file MeshPartitionerBase.cc.
_checkCreateVar()
void Arcane::MeshPartitionerBase::_checkCreateVar () private
Definition at line 287 of file MeshPartitionerBase.cc.
_clearCellWgt()
void Arcane::MeshPartitionerBase::_clearCellWgt () protected virtual
Definition at line 802 of file MeshPartitionerBase.cc.
_createConstraintsLists()
bool Arcane::MeshPartitionerBase::_createConstraintsLists (Int64MultiArray2 & tied_uid) private
Definition at line 152 of file MeshPartitionerBase.cc.
_initArrayCellsWithConstraints()
void Arcane::MeshPartitionerBase::_initArrayCellsWithConstraints () protected virtual
Definition at line 207 of file MeshPartitionerBase.cc.
_initFilterLidCells()
void Arcane::MeshPartitionerBase::_initFilterLidCells () protected virtual
Definition at line 257 of file MeshPartitionerBase.cc.
_initLid2LidCompacted()
void Arcane::MeshPartitionerBase::_initLid2LidCompacted () protected virtual
info()<<"m_local_id_2_local_id_compacted["<<icell->localId()<<"(gid:"<<icell->uniqueId()<<")] = "<<index-1;
Definition at line 344 of file MeshPartitionerBase.cc.
References ENUMERATE_CELL.
_initNbCellsWithConstraints()
void Arcane::MeshPartitionerBase::_initNbCellsWithConstraints () protected virtual
Definition at line 375 of file MeshPartitionerBase.cc.
_initUidRef() [1/2]
void Arcane::MeshPartitionerBase::_initUidRef () protected virtual
Definition at line 297 of file MeshPartitionerBase.cc.
_initUidRef() [2/2]
void Arcane::MeshPartitionerBase::_initUidRef (VariableCellInteger & cell_renum_uid) protected virtual
Definition at line 320 of file MeshPartitionerBase.cc.
_isNonManifoldMesh()
bool Arcane::MeshPartitionerBase::_isNonManifoldMesh () const inline protected
Definition at line 168 of file MeshPartitionerBase.h.
_meshDimension()
Int32 Arcane::MeshPartitionerBase::_meshDimension () const inline protected
Definition at line 169 of file MeshPartitionerBase.h.
cellComm()
virtual bool Arcane::MeshPartitionerBase::cellComm () inline protected virtual
Definition at line 154 of file MeshPartitionerBase.h.
cellsSizeWithConstraints()
SharedArray< float > Arcane::MeshPartitionerBase::cellsSizeWithConstraints () virtual
Definition at line 643 of file MeshPartitionerBase.cc.
cellsWeight()
ArrayView< float > Arcane::MeshPartitionerBase::cellsWeight () const override virtual
Implements Arcane::IMeshPartitioner.
Definition at line 796 of file MeshPartitionerBase.cc.
cellsWeightsWithConstraints()
SharedArray< float > Arcane::MeshPartitionerBase::cellsWeightsWithConstraints (Int32 max_nb_weight = 0, bool ask_lb_cells = false) virtual
Definition at line 650 of file MeshPartitionerBase.cc.
cellUsedWithConstraints()
bool Arcane::MeshPartitionerBase::cellUsedWithConstraints (Cell cell) virtual
Definition at line 723 of file MeshPartitionerBase.cc.
cellUsedWithWeakConstraints()
bool Arcane::MeshPartitionerBase::cellUsedWithWeakConstraints (std::pair< Int64, Int64 > & paired_item) virtual
Definition at line 731 of file MeshPartitionerBase.cc.
changeCellOwner()
void Arcane::MeshPartitionerBase::changeCellOwner (Item cell, VariableItemInt32 & cells_new_owner, Int32 new_owner) virtual
Definition at line 739 of file MeshPartitionerBase.cc.
changeOwnersFromCells()
void Arcane::MeshPartitionerBase::changeOwnersFromCells () virtual
Positions the new owners of nodes, edges and faces based on the cells.
Assuming the new owners of the cells are known (and synchronized), determines the new owners of the other entities.
Definition at line 100 of file MeshPartitionerBase.cc.
Referenced by Arcane::MetisMeshPartitioner::_partitionMesh(), Arcane::SplitSDMeshPartitioner::ConnexifieDomaine(), Arcane::SplitSDMeshPartitioner::Equilibrage(), and Arcane::SplitSDMeshPartitioner::init().
communicator()
Parallel::Communicator Arcane::MeshPartitionerBase::communicator () const protected virtual
Definition at line 91 of file MeshPartitionerBase.cc.
computationTimes()
RealConstArrayView Arcane::MeshPartitionerBase::computationTimes () const inline override virtual
Implements Arcane::IMeshPartitioner.
Definition at line 65 of file MeshPartitionerBase.h.
dumpObject()
void Arcane::MeshPartitionerBase::dumpObject (String filename = "toto") protected virtual
Dumps the partitioning information to disk.
Definition at line 855 of file MeshPartitionerBase.cc.
References Arcane::Array< T >::add(), Arcane::centralizePartInfo(), dumpObject(), ENUMERATE_CELL, Arcane::Array< T >::fill(), mesh(), Arcane::IParallelMng::reduce(), Arcane::MessagePassing::ReduceSum, Arcane::AbstractArray< T >::size(), Arcane::Convert::toDouble(), Arcane::StringBuilder::toString(), and Arcane::IParallelMng::waitAllRequests().
Referenced by dumpObject().
freeConstraints()
void Arcane::MeshPartitionerBase::freeConstraints () virtual
Definition at line 134 of file MeshPartitionerBase.cc.
getCommunicator()
void * Arcane::MeshPartitionerBase::getCommunicator () const protected virtual
Definition at line 82 of file MeshPartitionerBase.cc.
getNeighbourCellsUidWithConstraints()
Real Arcane::MeshPartitionerBase::getNeighbourCellsUidWithConstraints (Cell cell, Int64Array & neighbourcells, Array< float > * commWeights = NULL, bool noCellContrib = false) virtual
Definition at line 478 of file MeshPartitionerBase.cc.
getNeighbourNodesUidWithConstraints()
void Arcane::MeshPartitionerBase::getNeighbourNodesUidWithConstraints (Cell cell, Int64UniqueArray neighbournodes) virtual
Definition at line 604 of file MeshPartitionerBase.cc.
haveConstraints()
virtual bool Arcane::MeshPartitionerBase::haveConstraints () inline virtual
Definition at line 143 of file MeshPartitionerBase.h.
haveWeakConstraints()
virtual bool Arcane::MeshPartitionerBase::haveWeakConstraints () inline virtual
Definition at line 145 of file MeshPartitionerBase.h.
imbalance()
Real Arcane::MeshPartitionerBase::imbalance () const inline override virtual
Computation time imbalance.
Implements Arcane::IMeshPartitioner.
Definition at line 59 of file MeshPartitionerBase.h.
Referenced by Arcane::MetisMeshPartitioner::_partitionMesh().
initConstraints()
void Arcane::MeshPartitionerBase::initConstraints (bool uidref = true) virtual
Definition at line 109 of file MeshPartitionerBase.cc.
invertArrayLid2LidCompacted()
void Arcane::MeshPartitionerBase::invertArrayLid2LidCompacted () virtual
Definition at line 629 of file MeshPartitionerBase.cc.
loadBalanceMng()
ILoadBalanceMng * Arcane::MeshPartitionerBase::loadBalanceMng () const inline override virtual
Implements Arcane::IMeshPartitioner.
Definition at line 73 of file MeshPartitionerBase.h.
localIdWithConstraints() [1/2]
Int32 Arcane::MeshPartitionerBase::localIdWithConstraints (Cell cell) virtual
Definition at line 615 of file MeshPartitionerBase.cc.
localIdWithConstraints() [2/2]
Int32 Arcane::MeshPartitionerBase::localIdWithConstraints (Int32 cell_lid) virtual
Definition at line 621 of file MeshPartitionerBase.cc.
maxImbalance()
Real Arcane::MeshPartitionerBase::maxImbalance () const inline override virtual
Maximum allowed imbalance.
Implements Arcane::IMeshPartitioner.
Definition at line 62 of file MeshPartitionerBase.h.
Referenced by Arcane::MetisMeshPartitioner::_partitionMesh(), and Arcane::SplitSDMeshPartitioner::Equilibrage().
maximumComputationTime()
Real Arcane::MeshPartitionerBase::maximumComputationTime () const inline override virtual
Implements Arcane::IMeshPartitioner.
Definition at line 56 of file MeshPartitionerBase.h.
mesh()
IMesh * Arcane::MeshPartitionerBase::mesh () const inline override virtual
Mesh associated with the partitioner.
Implements Arcane::IMeshPartitioner.
Definition at line 52 of file MeshPartitionerBase.h.
Referenced by dumpObject().
nbCellWeight()
Integer Arcane::MeshPartitionerBase::nbCellWeight () const
Definition at line 790 of file MeshPartitionerBase.cc.
nbNeighbourCellsWithConstraints()
Integer Arcane::MeshPartitionerBase::nbNeighbourCellsWithConstraints (Cell cell) virtual
Definition at line 410 of file MeshPartitionerBase.cc.
nbOwnCellsWithConstraints()
Int32 Arcane::MeshPartitionerBase::nbOwnCellsWithConstraints () const virtual
Definition at line 402 of file MeshPartitionerBase.cc.
notifyEndPartition()
void Arcane::MeshPartitionerBase::notifyEndPartition () inline override virtual
Notification when a re-partitioning finishes (after entity exchange).
Implements Arcane::IMeshPartitionerBase.
Reimplemented in Arcane::ZoltanMeshPartitioner.
Definition at line 77 of file MeshPartitionerBase.h.
setCellsWeight()
void Arcane::MeshPartitionerBase::setCellsWeight (ArrayView< float > weights, Integer nb_weight) override virtual
Allows defining the weights of objects to be partitioned: ILoadBalanceMng must now be used.
Implements Arcane::IMeshPartitioner.
Definition at line 765 of file MeshPartitionerBase.cc.
References ENUMERATE_CELL, Arcane::IVariable::PExecutionDepend, Arcane::IVariable::PNoDump, Arcane::IVariable::PTemporary, setCellsWeight(), and Arcane::StringBuilder::toString().
Referenced by setCellsWeight().
setComputationTimes()
void Arcane::MeshPartitionerBase::setComputationTimes (RealConstArrayView v) inline override virtual
Computation time of this subdomain. The first element indicates the computation time of the subdomain corresponding to calculations whose cost is proportional to the cells. The following must be associated with a variable (to be done).
Implements Arcane::IMeshPartitioner.
Definition at line 64 of file MeshPartitionerBase.h.
setILoadBalanceMng()
void Arcane::MeshPartitionerBase::setILoadBalanceMng (ILoadBalanceMng * mng) inline override virtual
Changes the ILoadBalanceMng to use.
Implements Arcane::IMeshPartitioner.
Definition at line 72 of file MeshPartitionerBase.h.
setImbalance()
void Arcane::MeshPartitionerBase::setImbalance (Real v) inline override virtual
Sets the computation time imbalance.
Implements Arcane::IMeshPartitioner.
Definition at line 58 of file MeshPartitionerBase.h.
setMaxImbalance()
void Arcane::MeshPartitionerBase::setMaxImbalance (Real v) inline override virtual
Sets the maximum allowed imbalance.
Implements Arcane::IMeshPartitioner.
Definition at line 61 of file MeshPartitionerBase.h.
setMaximumComputationTime()
void Arcane::MeshPartitionerBase::setMaximumComputationTime (Real v) inline override virtual
Sets the proportion of computation time.
Proportion of computation time Computation time of the most heavily loaded subdomain
Implements Arcane::IMeshPartitioner.
Definition at line 55 of file MeshPartitionerBase.h.
subDomain()
ISubDomain * Arcane::MeshPartitionerBase::subDomain () const inline
Definition at line 51 of file MeshPartitionerBase.h.
Member Data Documentation
m_cell_family
IItemFamily* Arcane::MeshPartitionerBase::m_cell_family = nullptr protected
Definition at line 189 of file MeshPartitionerBase.h.
m_cells_with_constraints
UniqueArray<SharedArray<Cell> > Arcane::MeshPartitionerBase::m_cells_with_constraints private
Definition at line 202 of file MeshPartitionerBase.h.
m_cells_with_weak_constraints
std::set<std::pair<Int64, Int64> > Arcane::MeshPartitionerBase::m_cells_with_weak_constraints private
Definition at line 203 of file MeshPartitionerBase.h.
m_check
UniqueArray<Int32> Arcane::MeshPartitionerBase::m_check private
Definition at line 210 of file MeshPartitionerBase.h.
m_computation_times
UniqueArray<Real> Arcane::MeshPartitionerBase::m_computation_times private
Definition at line 199 of file MeshPartitionerBase.h.
m_filter_lid_cells
UniqueArray<eMarkCellWithConstraint> Arcane::MeshPartitionerBase::m_filter_lid_cells private
Definition at line 205 of file MeshPartitionerBase.h.
m_imbalance
Real Arcane::MeshPartitionerBase::m_imbalance = 0.0 private
Definition at line 197 of file MeshPartitionerBase.h.
m_is_non_manifold_mesh
bool Arcane::MeshPartitionerBase::m_is_non_manifold_mesh = false private
Definition at line 211 of file MeshPartitionerBase.h.
m_lb_mng_internal
ILoadBalanceMngInternal* Arcane::MeshPartitionerBase::m_lb_mng_internal = nullptr private
Definition at line 194 of file MeshPartitionerBase.h.
m_lbMng
ILoadBalanceMng* Arcane::MeshPartitionerBase::m_lbMng = nullptr private
Definition at line 193 of file MeshPartitionerBase.h.
m_local_id_2_local_id_compacted
UniqueArray<Int32> Arcane::MeshPartitionerBase::m_local_id_2_local_id_compacted private
Definition at line 206 of file MeshPartitionerBase.h.
m_max_imbalance
Real Arcane::MeshPartitionerBase::m_max_imbalance = 0.0 private
Definition at line 198 of file MeshPartitionerBase.h.
m_maximum_computation_time
Real Arcane::MeshPartitionerBase::m_maximum_computation_time = 0.0 private
Definition at line 196 of file MeshPartitionerBase.h.
m_mesh
IMesh* Arcane::MeshPartitionerBase::m_mesh = nullptr private
Definition at line 184 of file MeshPartitionerBase.h.
m_mesh_dimension
Int32 Arcane::MeshPartitionerBase::m_mesh_dimension = -1 private
Definition at line 212 of file MeshPartitionerBase.h.
m_nb_cells_with_constraints
Integer Arcane::MeshPartitionerBase::m_nb_cells_with_constraints = 0 private
Definition at line 204 of file MeshPartitionerBase.h.
m_pm_sub
IParallelMng* Arcane::MeshPartitionerBase::m_pm_sub = nullptr private
Definition at line 185 of file MeshPartitionerBase.h.
m_sub_domain
ISubDomain* Arcane::MeshPartitionerBase::m_sub_domain = nullptr private
Definition at line 183 of file MeshPartitionerBase.h.
m_unique_id_reference
VariableCellInt64* Arcane::MeshPartitionerBase::m_unique_id_reference = nullptr private
Definition at line 207 of file MeshPartitionerBase.h.
The documentation for this class was generated from the following files:
MeshPartitionerBase.h
MeshPartitionerBase.cc