Alien: Alien::RedistributedMatrix Class Reference
Alien::RedistributedMatrix Class Reference final
Public Member Functions
RedistributedMatrix (RedistributedMatrix &&matrix)=delete
RedistributedMatrix (IMatrix &matrix, Redistributor &redist)
RedistributedMatrix & operator= (RedistributedMatrix &&matrix)=delete
RedistributedMatrix (const RedistributedMatrix &matrix)=delete
RedistributedMatrix & operator= (const RedistributedMatrix &matrix)=delete
void visit (ICopyOnWriteMatrix &) const
Visit method.
const MatrixDistribution & distribution () const
const ISpace & rowSpace () const
Get row space associated to the matrix.
const ISpace & colSpace () const
Get col space associated to the matrix.
void setUserFeature (String feature)
bool hasUserFeature (String feature) const
MultiMatrixImpl * impl ()
Get the multimatrix implementation.
const MultiMatrixImpl * impl () const
Get the multimatrix implementation.
Private Attributes
std::shared_ptr< MultiMatrixImpl > m_impl
Additional Inherited Members
Protected Member Functions inherited from Alien::IMatrix
IMatrix ()
Constructor.
Detailed Description
Definition at line 36 of file RedistributedMatrix.h.
Constructor & Destructor Documentation
RedistributedMatrix()
Alien::RedistributedMatrix::RedistributedMatrix (IMatrix & matrix, Redistributor & redist)
Definition at line 34 of file RedistributedMatrix.cc.
~RedistributedMatrix()
Alien::RedistributedMatrix::~RedistributedMatrix ()
Definition at line 38 of file RedistributedMatrix.cc.
Member Function Documentation
colSpace()
const ISpace & Alien::RedistributedMatrix::colSpace () const virtual
Get col space associated to the matrix.
Returns
The col space
Implements Alien::IMatrix.
Definition at line 66 of file RedistributedMatrix.cc.
References colSpace().
Referenced by colSpace().
distribution()
const MatrixDistribution & Alien::RedistributedMatrix::distribution () const
Definition at line 50 of file RedistributedMatrix.cc.
hasUserFeature()
bool Alien::RedistributedMatrix::hasUserFeature (String feature) const
Definition at line 80 of file RedistributedMatrix.cc.
impl() [1/2]
MultiMatrixImpl * Alien::RedistributedMatrix::impl () virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 88 of file RedistributedMatrix.cc.
References impl().
Referenced by impl(), and impl().
impl() [2/2]
const MultiMatrixImpl * Alien::RedistributedMatrix::impl () const virtual
Get the multimatrix implementation.
Returns
The multimatrix implementation
Implements Alien::IMatrix.
Definition at line 103 of file RedistributedMatrix.cc.
References impl().
rowSpace()
const ISpace & Alien::RedistributedMatrix::rowSpace () const virtual
Get row space associated to the matrix.
Returns
The row space
Implements Alien::IMatrix.
Definition at line 58 of file RedistributedMatrix.cc.
References rowSpace().
Referenced by rowSpace().
setUserFeature()
void Alien::RedistributedMatrix::setUserFeature (String feature)
Definition at line 73 of file RedistributedMatrix.cc.
visit()
void Alien::RedistributedMatrix::visit (ICopyOnWriteMatrix &) const virtual
Visit method.
Implements Alien::IMatrix.
Definition at line 42 of file RedistributedMatrix.cc.
References visit().
Referenced by visit().
Member Data Documentation
m_impl
std::shared_ptr<MultiMatrixImpl> Alien::RedistributedMatrix::m_impl private
Definition at line 69 of file RedistributedMatrix.h.
The documentation for this class was generated from the following files:
RedistributedMatrix.h
RedistributedMatrix.cc