Alien: Alien::SimpleCSRtoDoKMatrixConverter Class Reference
Alien::SimpleCSRtoDoKMatrixConverter Class Reference
Public Types
typedef SimpleCSRMatrix< Arccore::Real > SrcMatrix
typedef DoKMatrix TgtMatrix
Public Types inherited from Alien::IMatrixConverter
typedef Alien::IMatrixImpl IMatrixImpl
Type of matrix implementation.
typedef Alien::BackEndId BackEndId
Type of matrix backend.
Public Member Functions
BackEndId sourceBackend () const override
Get the source backend id.
BackEndId targetBackend () const override
Get the target backend id.
void convert (const IMatrixImpl *sourceImpl, IMatrixImpl *targetImpl) const override
Convert a matrix from one format to another.
Public Member Functions inherited from Alien::IMatrixConverter
virtual ~IMatrixConverter ()
Free resources.
Public Member Functions inherited from Alien::ObjectWithTrace
template<typename T>
void alien_info (T &&t) const
template<typename T>
void alien_debug (T &&t) const
template<typename T>
void alien_warning (T &&t) const
template<typename T>
void alien_fatal (T &&t) const
ITraceMng * traceMng () const
Private Member Functions
void _build (const SrcMatrix &src, TgtMatrix &tgt) const
Additional Inherited Members
Static Public Member Functions inherited from Alien::IMatrixConverter
template<typename T>
static T & cast (IMatrixImpl *impl, BackEndId backend)
Cast a matrix implementation in its actual type.
template<typename T>
static const T & cast (const IMatrixImpl *impl, BackEndId backend)
Const cast a matrix implementation in its actual type.
Protected Member Functions inherited from Alien::ObjectWithTrace
TraceMessage cout () const
Detailed Description
Definition at line 33 of file dok/converters/from_simple_csr_matrix.h.
Member Typedef Documentation
SrcMatrix
typedef SimpleCSRMatrix<Arccore::Real> Alien::SimpleCSRtoDoKMatrixConverter::SrcMatrix
Definition at line 36 of file dok/converters/from_simple_csr_matrix.h.
TgtMatrix
typedef DoKMatrix Alien::SimpleCSRtoDoKMatrixConverter::TgtMatrix
Definition at line 37 of file dok/converters/from_simple_csr_matrix.h.
Constructor & Destructor Documentation
SimpleCSRtoDoKMatrixConverter()
Alien::SimpleCSRtoDoKMatrixConverter::SimpleCSRtoDoKMatrixConverter ()
Definition at line 21 of file dok/converters/from_simple_csr_matrix.cc.
~SimpleCSRtoDoKMatrixConverter()
Alien::SimpleCSRtoDoKMatrixConverter::~SimpleCSRtoDoKMatrixConverter () virtual
Definition at line 23 of file dok/converters/from_simple_csr_matrix.cc.
Member Function Documentation
_build()
void Alien::SimpleCSRtoDoKMatrixConverter::_build (const SrcMatrix & src, TgtMatrix & tgt) const private
Definition at line 54 of file dok/converters/from_simple_csr_matrix.cc.
convert()
void Alien::SimpleCSRtoDoKMatrixConverter::convert (const IMatrixImpl * sourceImpl, IMatrixImpl * targetImpl) const override virtual
Convert a matrix from one format to another.
Parameters
[in] sourceImpl Implementation of the source matrix
[in,out] targetImpl Implementation of the target matrix
Implements Alien::IMatrixConverter.
Definition at line 37 of file dok/converters/from_simple_csr_matrix.cc.
References Alien::IMatrixImpl::block(), Alien::IMatrixConverter::cast(), sourceBackend(), and targetBackend().
sourceBackend()
BackEndId Alien::SimpleCSRtoDoKMatrixConverter::sourceBackend () const override virtual
Get the source backend id.
Returns
The source backend id
Implements Alien::IMatrixConverter.
Definition at line 26 of file dok/converters/from_simple_csr_matrix.cc.
Referenced by convert().
targetBackend()
BackEndId Alien::SimpleCSRtoDoKMatrixConverter::targetBackend () const override virtual
Get the target backend id.
Returns
The target backend id
Implements Alien::IMatrixConverter.
Definition at line 32 of file dok/converters/from_simple_csr_matrix.cc.
Referenced by convert().
The documentation for this class was generated from the following files:
dok/converters/from_simple_csr_matrix.h
dok/converters/from_simple_csr_matrix.cc