Arcane: Arcane::VariableCollection Class Reference
Arcane::VariableCollection Class Reference
Variable collection.
#include <arcane/core/VariableCollection.h>
Public Types
typedef VariableCollectionEnumerator Enumerator
Public Member Functions
VariableCollection (const Enumerator &rhs)
void add (IVariable *var)
void add (VariableRef &var)
IVariable * front ()
Integer count () const
template<class Function>
Function each (Function f)
Applies the functor f to all elements in the collection.
void clear ()
bool empty () const
VariableCollection clone () const
VariableCollectionEnumerator enumerator () const
bool contains (IVariable *v) const
bool contains (VariableRef &v) const
void sortByName (bool is_ascendent)
Sorts the list by ascending or descending variable names.
Friends
class VariableCollectionEnumerator
Detailed Description
Variable collection.
This type has a reference semantics (like the SharedArray class).
Definition at line 88 of file VariableCollection.h.
Member Typedef Documentation
Enumerator
typedef VariableCollectionEnumerator Arcane::VariableCollection::Enumerator
Definition at line 116 of file VariableCollection.h.
Constructor & Destructor Documentation
VariableCollection() [1/2]
Arcane::VariableCollection::VariableCollection ()
Definition at line 25 of file VariableCollection.cc.
VariableCollection() [2/2]
Arcane::VariableCollection::VariableCollection (const Enumerator & rhs)
Definition at line 34 of file VariableCollection.cc.
Member Function Documentation
add() [1/2]
void Arcane::VariableCollection::add (IVariable * var) inline
Definition at line 125 of file VariableCollection.h.
add() [2/2]
void Arcane::VariableCollection::add (VariableRef & var) inline
Definition at line 130 of file VariableCollection.h.
clear()
void Arcane::VariableCollection::clear () inline
Definition at line 153 of file VariableCollection.h.
clone()
VariableCollection Arcane::VariableCollection::clone () const inline
Definition at line 163 of file VariableCollection.h.
contains() [1/2]
bool Arcane::VariableCollection::contains (IVariable * v) const inline
Definition at line 175 of file VariableCollection.h.
contains() [2/2]
bool Arcane::VariableCollection::contains (VariableRef & v) const inline
Definition at line 180 of file VariableCollection.h.
count()
Integer Arcane::VariableCollection::count () const inline
Definition at line 140 of file VariableCollection.h.
each()
template<class Function> Function Arcane::VariableCollection::each (Function f) inline
Applies the functor f to all elements in the collection.
Definition at line 147 of file VariableCollection.h.
empty()
bool Arcane::VariableCollection::empty () const inline
Definition at line 158 of file VariableCollection.h.
enumerator()
VariableCollectionEnumerator Arcane::VariableCollection::enumerator () const inline
Definition at line 170 of file VariableCollection.h.
front()
IVariable * Arcane::VariableCollection::front () inline
Definition at line 135 of file VariableCollection.h.
sortByName()
void Arcane::VariableCollection::sortByName (bool is_ascendent)
Sorts the list by ascending or descending variable names.
Definition at line 44 of file VariableCollection.cc.
References Arcane::Array< T >::begin(), Arcane::Array< T >::end(), Arcane::IVariable::fullName(), Arcane::Array< T >::rbegin(), and Arcane::Array< T >::rend().
Friends And Related Symbol Documentation
VariableCollectionEnumerator
friend class VariableCollectionEnumerator friend
Definition at line 115 of file VariableCollection.h.
The documentation for this class was generated from the following files:
VariableCollection.h
VariableCollection.cc